import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import game from "../src/games/attention-author-boss-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";
const ID="attention-author-boss-v1",PROMPT="変則ムーブの作者を3回つかまえて",HELP="残像・フェイント・画面外逃走を見切ってタップ。",TASK={kind:"authorBoss",prompt:PROMPT,help:HELP,hits:3,duration:10000},source=await readFile(new URL("../src/games/attention-author-boss-v1.js",import.meta.url),"utf8");
const noop=()=>{};class Gradient{addColorStop(){}}const ctx=()=>new Proxy({globalAlpha:1,createLinearGradient:()=>new Gradient(),createRadialGradient:()=>new Gradient()},{get(o,k){return k in o?o[k]:noop},set(o,k,v){o[k]=v;return true}});
class Style{setProperty(key,value){this[key]=String(value)}}
class Element extends EventTarget{constructor(tag,doc){super();this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.children=[];this.parentElement=null;this.attributes=new Map();this.dataset={};this.style=new Style();this.className="";this.textContent="";this.hidden=false;this.disabled=false;this.tabIndex=-1;this.width=0;this.height=0;this.context=this.tagName==="CANVAS"?ctx():null}append(...nodes){nodes.forEach(node=>{node.parentElement=this;this.children.push(node)})}replaceChildren(...nodes){this.children=[];this.append(...nodes)}setAttribute(k,v){this.attributes.set(k,String(v))}getAttribute(k){return this.attributes.get(k)??null}focus(){this.ownerDocument.activeElement=this}getContext(){return this.context}getBoundingClientRect(){const width=Number.parseFloat(this.style.width)||393,height=Number.parseFloat(this.style.height)||330;return{left:0,top:0,width,height,right:width,bottom:height}}}
function documentFor(dpr=3){const view=new EventTarget();view.devicePixelRatio=dpr;const doc={activeElement:null,defaultView:view};doc.createElement=tag=>new Element(tag,doc);return doc}
function event(type,properties={}){const value=new Event(type,{bubbles:true,cancelable:true});Object.entries(properties).forEach(([key,item])=>Object.defineProperty(value,key,{value:item}));return value}
function harness({reduced=true,viewport={width:393,height:852,dpr:3},owner=documentFor(viewport.dpr)}={}){const controller=new AbortController(),host=owner.createElement("div"),qa={},jobs=[],listeners=new Set(),finishes=[];let deadline=null,frame=null,time=0,disposed=false;host.getBoundingClientRect=()=>({left:0,top:0,width:viewport.width,height:viewport.height});const dispose=()=>{if(disposed)return;controller.abort();disposed=true;jobs.forEach(job=>job.active=false);if(deadline)deadline.active=false;frame=null;listeners.forEach(item=>item.target.removeEventListener(item.type,item.fn,item.options));listeners.clear()};const context={host,signal:controller.signal,reducedMotion:reduced,viewport,qa,finish(correct,result){if(disposed||finishes.length)return false;finishes.push({correct,result});return true},later(fn,ms){const job={fn,at:time+ms,active:true};jobs.push(job);return job},setDeadline(ms,fn){deadline={fn,at:time+ms,active:true};return deadline},frame(fn){frame=fn;return()=>{frame=null}},listen(target,type,fn,options){target.addEventListener(type,fn,options);const item={target,type,fn,options};listeners.add(item);return()=>{target.removeEventListener(type,fn,options);listeners.delete(item)}}};const runNext=()=>{const job=jobs.filter(item=>item.active).sort((a,b)=>a.at-b.at)[0];if(!job)return false;time=job.at;job.active=false;job.fn();return true},runAll=()=>{let guard=0;while(runNext()&&guard++<1000);assert.ok(guard<1000)},step=at=>{time=at;if(frame&&frame(at)===false)frame=null},timeout=()=>{if(deadline?.active&&!disposed){deadline.active=false;deadline.fn()}};return{context,host,owner,qa,finishes,dispose,runNext,runAll,step,timeout,get pending(){return jobs.filter(item=>item.active).length},get frame(){return Boolean(frame)},get listeners(){return listeners.size}}}
const parts=h=>{const stage=h.host.children[1],head=stage.children[0],board=stage.children[1];return{stage,head,board,canvas:board.children[0],target:board.children[1],status:stage.children[2]}};
const makeTask=()=>JSON.parse(JSON.stringify(TASK));
function waitReady(h,api){let guard=0;while(!api.inspect().ready&&guard++<12)assert.equal(h.runNext(),true);assert.ok(guard<12);return api.inspect()}
function solveReduced(h,api){for(let hit=0;hit<3;hit++){const before=api.inspect();if(!before.ready)waitReady(h,api);h.runAll();assert.equal(api.inspect().ready,true);assert.equal(api.catch(),true);assert.equal(api.inspect().hits,hit+1);if(hit<2)assert.equal(h.runNext(),true)}}

test("metadata and exact published factory task are frozen",()=>{assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.0",tier:2,flavor:"wild",step:1,family:"attention-author-boss",category:"attention"});assert.deepEqual(game.generate(),TASK);assert.deepEqual(Object.keys(game.generate()),["kind","prompt","help","hits","duration"])});
test("5000 generated tasks remain exact, cloneable, finite, and valid",()=>{const started=performance.now();for(let i=0;i<5000;i++){const task=game.generate({randomInt:()=>i});assert.deepEqual(task,TASK);assert.deepEqual(structuredClone(task),task);assert.deepEqual(game.validate(task),[])}assert.ok(performance.now()-started<2500)});
test("validator rejects extras and every changed published field",()=>{const variants=[null,{...TASK,extra:true},{...TASK,kind:"boss"},{...TASK,prompt:"changed"},{...TASK,help:"changed"},{...TASK,hits:2},{...TASK,duration:9999}];variants.forEach((task,index)=>assert.ok(game.validate(task).length,`variant ${index}`));assert.deepEqual(game.validate(makeTask()),[])});
test("plain JSON resumes with one deterministic pseudo-shuffled unique mode sequence",()=>{const a=harness(),b=harness();game.render(makeTask(),a.context);game.render(JSON.parse(JSON.stringify(makeTask())),b.context);const sa=a.qa[ID].sequence(),sb=b.qa[ID].sequence();assert.deepEqual(sa,sb);assert.equal(sa.length,3);assert.equal(new Set(sa).size,3);assert.deepEqual([...sa].sort(),["afterimage","dance","vanish"]);a.dispose();b.dispose()});
test("afterimage is ghost-only until tracked reveal and wrong input never catches",()=>{const h=harness();game.render(makeTask(),h.context);const api=h.qa[ID];while(api.inspect().activeMode!=="afterimage"){if(!api.inspect().ready)waitReady(h,api);h.runAll();api.catch();if(api.inspect().hits<3)h.runNext()}const initial=api.inspect();assert.equal(initial.ready,false);assert.ok(initial.ghost);const hits=initial.hits;assert.equal(api.miss({x:initial.ghost.x,y:initial.ghost.y}),false);assert.equal(api.inspect().hits,hits);waitReady(h,api);assert.equal(api.inspect().ghost,null);assert.equal(api.inspect().targetVisible,true);h.dispose()});
test("normal dance owns one tracked frame, moves the real target, and stops on catch",()=>{const h=harness({reduced:false});game.render(makeTask(),h.context);const api=h.qa[ID];while(api.inspect().activeMode!=="dance"){if(!api.inspect().ready)waitReady(h,api);api.catch();if(api.inspect().hits<3)h.runNext()}assert.equal(api.inspect().ready,true);assert.equal(h.frame,true);const before=api.inspect().targetPos;assert.deepEqual(api.inspect().timing,{afterimageMs:520,reducedAfterimageMs:650,vanishMs:430,reducedVanishMs:600,interModeMs:240,danceAnimationMs:1450,danceStepMs:1650,reducedDanceStepMs:1800});h.step(420);const after=api.inspect().targetPos;assert.notDeepEqual(after,before);h.step(1450);const settled=api.inspect().targetPos;h.step(1550);assert.deepEqual(api.inspect().targetPos,settled);h.step(1700);assert.notDeepEqual(api.inspect().targetPos,settled);assert.ok(api.inspect().frames>0);api.catch();assert.equal(h.frame,false);h.dispose()});
test("vanish has a non-catchable exit and tracked return before one valid catch",()=>{const h=harness();game.render(makeTask(),h.context);const api=h.qa[ID];while(api.inspect().activeMode!=="vanish"){if(!api.inspect().ready)waitReady(h,api);h.runAll();api.catch();if(api.inspect().hits<3)h.runNext()}const hits=api.inspect().hits;assert.equal(api.inspect().ready,false);assert.equal(api.catch(),false);assert.equal(api.inspect().hits,hits);assert.ok(api.inspect().vanishProgress>0);waitReady(h,api);assert.equal(api.inspect().vanishProgress,1);assert.equal(api.catch(),true);h.dispose()});
test("three real mode catches advance 0/3 to 3/3 and preserve exact success payload",()=>{const h=harness(),task=makeTask();game.render(task,h.context);const api=h.qa[ID];solveReduced(h,api);assert.deepEqual(h.finishes.map(item=>item.correct),[true]);assert.equal(api.inspect().hits,3);assert.equal(api.inspect().result,"success");assert.equal(h.finishes[0].result.detail,"変則ムーブごと作者を確保しました。");assert.equal(h.finishes[0].result.quality,1);assert.deepEqual(api.inspect().modeEntries,api.inspect().sequence);api.catch();h.timeout();assert.equal(h.finishes.length,1)});
test("background, early target, and missed spatial reticle stay at the same hit count",()=>{const h=harness();game.render(makeTask(),h.context);const api=h.qa[ID],{board,stage}=parts(h),start=api.inspect().hits;board.dispatchEvent(event("pointerdown",{clientX:2,clientY:2,pointerId:1}));assert.equal(api.inspect().hits,start);for(let i=0;i<8;i++){stage.dispatchEvent(event("keydown",{key:"ArrowLeft"}));stage.dispatchEvent(event("keydown",{key:"ArrowUp"}))}stage.dispatchEvent(event("keydown",{key:"Enter"}));assert.equal(api.inspect().hits,start);assert.ok(api.inspect().wrongInputs>=2);h.dispose()});
test("touch target and focused keyboard target catch once and lock repeated input",()=>{const h=harness();game.render(makeTask(),h.context);const api=h.qa[ID],{stage,target}=parts(h);waitReady(h,api);const first=api.inspect().hits;target.dispatchEvent(event("pointerdown",{pointerId:2,pointerType:"touch"}));assert.equal(api.inspect().hits,first+1);const lockedWrongs=api.inspect().wrongInputs;target.dispatchEvent(event("pointerdown",{pointerId:3,pointerType:"touch"}));stage.dispatchEvent(event("keydown",{key:"Enter"}));assert.equal(api.inspect().hits,first+1);assert.equal(api.inspect().wrongInputs,lockedWrongs);h.runNext();waitReady(h,api);target.focus();assert.equal(h.owner.activeElement,target);target.dispatchEvent(event("keydown",{key:"Enter"}));assert.equal(api.inspect().hits,first+2);assert.equal(stage.tabIndex,0);h.dispose()});
test("deadline keeps the exact escape detail and cannot double-finish",()=>{const h=harness();game.render(makeTask(),h.context);h.timeout();assert.deepEqual(h.finishes.map(item=>item.correct),[false]);assert.equal(h.finishes[0].result.detail,"作者は変則ムーブで締切の向こうへ逃げました。");assert.equal(h.qa[ID].inspect().result,"timeout");h.timeout();h.qa[ID].catch();assert.equal(h.finishes.length,1)});
test("reduced mode has nonzero tracked stages, no frame, DPR3, and eight parity scenes",()=>{const h=harness({viewport:{width:402,height:874,dpr:4}});game.render(makeTask(),h.context);const api=h.qa[ID];assert.equal(h.frame,false);solveReduced(h,api);assert.ok(api.inspect().stages>0);assert.equal(api.inspect().frames,0);const canvas=api.inspect().canvas;assert.equal(canvas.dpr,3);assert.equal(canvas.pixelWidth,canvas.cssWidth*3);assert.equal(canvas.pixelHeight,canvas.cssHeight*3);for(const scene of["ready","afterimage","dance","vanish","hit1","hit2","success","timeout"])assert.equal(api.showScene(scene),true);h.dispose()});
test("ownerDocument rendering and disposal clear staged work, QA, deadline, frame, and listeners",async()=>{const h=harness();game.render(makeTask(),h.context);assert.ok(h.pending>0||h.qa[ID].inspect().ready);h.dispose();h.runAll();h.timeout();assert.equal(h.qa[ID],undefined);assert.equal(h.pending,0);assert.equal(h.frame,false);assert.equal(h.listeners,0);assert.deepEqual(h.finishes,[]);const previousRaf=globalThis.requestAnimationFrame,previousCancel=globalThis.cancelAnimationFrame;let id=0;const frames=new Map();globalThis.requestAnimationFrame=fn=>{frames.set(++id,fn);return id};globalThis.cancelAnimationFrame=key=>frames.delete(key);try{const owner=documentFor(),host=owner.createElement("div"),qa={},finishes=[],runtime=createGameRuntime({host,qa,reducedMotion:false,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(makeTask(),runtime.context);runtime.dispose();await delay(600);assert.equal(qa[ID],undefined);assert.deepEqual(finishes,[]);assert.equal(frames.size,0);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(previousRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=previousRaf;if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement)\b/);assert.doesNotMatch(source,/author\.png|https?:\/\//)});
