import game from "../src/games/attention-laundry-rescue-v1.js";import{createGameRuntime}from"../src/game-kernel.js";
window.__LAUNDRY_ERRORS__=[];window.onerror=(message,source,line,column,error)=>window.__LAUNDRY_ERRORS__.push({type:"error",message:String(error?.message||message),source,line,column});window.onunhandledrejection=event=>window.__LAUNDRY_ERRORS__.push({type:"rejection",message:String(event.reason?.message||event.reason)});
const params=new URLSearchParams(location.search),width=Number(params.get("width"))||393,reduced=params.get("motion")==="reduced",auto=params.get("auto")==="1";document.body.style.width=`${width}px`;const task=game.generate({randomInt:()=>0}),host=document.querySelector("#challenge"),result=document.querySelector("#result"),qa={},frameDeltas=[];let previous=performance.now(),monitoring=true,runtime,controls=null,initial=null;const monitor=now=>{if(!monitoring)return;frameDeltas.push(now-previous);previous=now;if(frameDeltas.length<900)requestAnimationFrame(monitor)};requestAnimationFrame(monitor);
const finish=(correct,detail)=>{monitoring=false;result.hidden=false;result.textContent=`${correct?"成功":"失敗"} — ${detail.detail}`;if(!auto)return;queueMicrotask(()=>{const inspection=runtime.inspect(),failures=[];if(!correct)failures.push("solve failed");if(!controls?.touch||!controls?.keyboard)failures.push("controls failed");if(!(inspection.disposed&&inspection.aborted&&!inspection.timeouts&&!inspection.frames&&!inspection.listeners))failures.push("cleanup failed");if(document.body.scrollWidth>width)failures.push("overflow");const report={status:failures.length?"fail":"pass",failures,correct,detail,controls,viewport:{width,dpr:devicePixelRatio,pointerEvents:"PointerEvent"in window,bodyScrollWidth:document.body.scrollWidth},canvas:initial.canvas,runtime:inspection,errors:[...window.__LAUNDRY_ERRORS__],resources:performance.getEntriesByType("resource").map(x=>new URL(x.name).pathname)};const pre=document.createElement("pre");pre.dataset.status=report.status;pre.textContent=JSON.stringify(report,null,2);document.body.replaceChildren(pre)})};
runtime=createGameRuntime({host,reducedMotion:reduced,viewport:{width,height:innerHeight,dpr:devicePixelRatio},qa,onFinish:finish});game.render(task,runtime.context);const api=qa[game.metadata.id];initial=api.inspect();
if(auto){const canvas=host.querySelector(".alr-canvas"),rect=canvas.getBoundingClientRect(),emit=(type,x,y)=>canvas.dispatchEvent(new PointerEvent(type,{bubbles:true,cancelable:true,pointerId:9,pointerType:"touch",clientX:rect.left+rect.width*x,clientY:rect.top+rect.height*y}));emit("pointerdown",.56,.66);emit("pointermove",.5,.255);emit("pointerup",.5,.255);controls={touch:api.inspect().busy,keyboard:false};let solutionIndex=1;const drive=()=>{if(!qa[game.metadata.id])return;if(api.inspect().busy){runtime.context.later(drive,35);return}if(solutionIndex>=task.solution.length)return;const target=task.solution[solutionIndex];let guard=0;while(api.inspect().selected!==target&&guard++<12)canvas.dispatchEvent(new KeyboardEvent("keydown",{bubbles:true,cancelable:true,key:"ArrowRight"}));canvas.dispatchEvent(new KeyboardEvent("keydown",{bubbles:true,cancelable:true,key:"Enter"}));controls.keyboard=document.activeElement===canvas;solutionIndex++;runtime.context.later(drive,35)};runtime.context.later(drive,reduced?560:35)}
const scene=params.get("scene");if(scene)api.showScene(scene);
if(params.get("measureLog")==="1")runtime.context.later(()=>{monitoring=false;const stable=frameDeltas.slice(5),inspection=api.inspect(),query=new URLSearchParams({frames:String(stable.length),averageFrameMs:(stable.reduce((a,b)=>a+b,0)/Math.max(1,stable.length)).toFixed(3),maxFrameMs:Math.max(0,...stable).toFixed(3),gameFrames:String(inspection.frames),pixelWidth:String(inspection.canvas.pixelWidth),pixelHeight:String(inspection.canvas.pixelHeight),dpr:String(inspection.canvas.dpr)});location.replace(`attention-laundry-rescue-v1.performance-result.html?${query}`)},1500);
window.__LAUNDRY_FIXTURE__={task,qa,runtime,evidence:()=>({game:qa[game.metadata.id]?.inspect(),runtime:runtime.inspect()})};
