import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";

const moduleUrl=new URL("../src/games/attention-driving-safety-v1.js",import.meta.url);
const moduleSource=await readFile(moduleUrl,"utf8");
const game=(await import(`data:text/javascript;base64,${Buffer.from(moduleSource).toString("base64")}`)).default;
const ID="attention-driving-safety-v1";

function randomHelpers(initialSeed=0x5eed2026){let seed=initialSeed>>>0;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/0x100000000),randomInt=(min,max)=>min+Math.floor(random()*(max-min+1));return{random,randomInt,pick:values=>values[randomInt(0,values.length-1)],shuffle:values=>[...values].sort(()=>random()-.5)}}
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}sync(){this.owner._className=[...this.values].join(" ")}}
class FakeStyle{constructor(){this.values=new Map()}setProperty(name,value){this.values.set(name,String(value))}}
const noop=()=>{};
function fakeCanvasContext(){const gradient={addColorStop:noop};return new Proxy({createLinearGradient:()=>gradient,createRadialGradient:()=>gradient,measureText:()=>({width:10})},{get(target,key){return key in target?target[key]:noop},set(target,key,value){target[key]=value;return true}})}
class FakeElement extends EventTarget{
  constructor(tagName,ownerDocument){super();this.tagName=tagName.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.attributes=new Map();this.dataset={};this.style=new FakeStyle();this.classList=new FakeClassList(this);this._className="";this.textContent="";this.type="";this.disabled=false;this.hidden=false;this.tabIndex=-1;this.width=0;this.height=0;this.title=""}
  set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}
  append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this.children=[...nodes]}
  setAttribute(name,value){this.attributes.set(name,String(value))}getAttribute(name){return this.attributes.get(name)??null}
  focus(){this.ownerDocument.activeElement=this}get offsetWidth(){return this.ownerDocument.viewportWidth||390}
  getContext(kind){return this.tagName==="CANVAS"&&kind==="2d"?fakeCanvasContext():null}
  getBoundingClientRect(){const width=Number.parseFloat(this.style.width)||this.ownerDocument.viewportWidth||390,height=Number.parseFloat(this.style.height)||Math.round(width*.72);return{left:0,top:0,width,height,right:width,bottom:height}}
}
function createFakeDocument(name="document"){const view=new EventTarget();view.devicePixelRatio=3;view.performance=globalThis.performance;const documentRef={name,activeElement:null,defaultView:view,viewportWidth:390};documentRef.createElement=tag=>new FakeElement(tag,documentRef);return documentRef}
function installFakeDocument(){const previous=globalThis.document;globalThis.document=createFakeDocument("global");return()=>{if(previous===undefined)delete globalThis.document;else globalThis.document=previous}}
function createHarness({reducedMotion=false,viewport={width:393,height:852,dpr:3},ownerDocument=globalThis.document}={}){
  const controller=new AbortController(),host=ownerDocument.createElement("div"),qa={},pending=[],listeners=new Set(),frames=new Set(),finishes=[];let deadline=null,disposed=false,finishCalls=0,frameTime=performance.now(),timerClock=0;ownerDocument.viewportWidth=viewport.width;host.getBoundingClientRect=()=>({left:0,top:0,width:viewport.width,height:viewport.height,right:viewport.width,bottom:viewport.height});
  const context={host,signal:controller.signal,reducedMotion,viewport,qa,
    finish(correct,result){finishCalls++;if(disposed||finishes.length)return false;finishes.push({correct,result});return true},
    setDeadline(ms,fn){deadline={ms,fn,active:true};return deadline},
    later(fn,ms){const job={fn,ms,at:timerClock+Math.max(0,Number(ms)||0),active:true};pending.push(job);return job},
    frame(fn){const loop={fn,active:true};frames.add(loop);return()=>{loop.active=false;frames.delete(loop)}},
    listen(target,type,fn,options){target.addEventListener(type,fn,options);const record={target,type,fn,options};listeners.add(record);return()=>{target.removeEventListener(type,fn,options);listeners.delete(record)}}
  };
  const nextPending=()=>pending.filter(item=>item.active).sort((a,b)=>a.at-b.at)[0]||null;
  const runFor=ms=>{const target=timerClock+Math.max(0,Number(ms)||0);let guard=0,job=nextPending();while(job&&job.at<=target&&!disposed&&guard++<1000){timerClock=job.at;job.active=false;job.fn();job=nextPending()}if(guard>=1000)throw new Error("timed work did not settle");timerClock=target};
  const runAll=()=>{let guard=0,job=nextPending();while(job&&!disposed&&guard++<1000){timerClock=job.at;job.active=false;job.fn();job=nextPending()}if(guard>=1000)throw new Error("pending work did not settle")};
  const stepFrames=(count=1,step=1000/60)=>{for(let index=0;index<count;index++){frameTime+=step;for(const loop of[...frames])if(loop.active&&loop.fn(frameTime)===false){loop.active=false;frames.delete(loop)}}};
  const triggerDeadline=()=>{if(deadline?.active&&!disposed){deadline.active=false;deadline.fn();return true}return false};
  const dispose=()=>{if(disposed)return;disposed=true;if(deadline)deadline.active=false;pending.forEach(job=>job.active=false);frames.clear();controller.abort();listeners.forEach(({target,type,fn,options})=>target.removeEventListener(type,fn,options));listeners.clear()};
  return{context,host,qa,finishes,runFor,runAll,stepFrames,triggerDeadline,dispose,get pendingCount(){return pending.filter(job=>job.active).length},get listenerCount(){return listeners.size},get frameCount(){return frames.size},get finishCalls(){return finishCalls}};
}
const eventWith=(type,properties={})=>{const event=new Event(type,{bubbles:true,cancelable:true});Object.entries(properties).forEach(([key,value])=>Object.defineProperty(event,key,{value}));return event};
const stageFrom=host=>host.children[1],stripFrom=host=>stageFrom(host).children[1],boardFrom=host=>stageFrom(host).children[3],canvasFrom=host=>boardFrom(host).children[0],paperFrom=host=>boardFrom(host).children[1],controlsFrom=host=>stageFrom(host).children[4],feedbackFrom=host=>stageFrom(host).children[5],nextFrom=host=>feedbackFrom(host).children[4];
function answerAndAdvance(api,choice,last=false){const result=api.answer(choice);assert.ok(result==="correct"||result==="incorrect");assert.equal(api.completeTransition(),true);assert.equal(api.next(),last?"complete":"next");return result}
function finishAll(harness,task,choices=task.proof.answers){const api=harness.qa[ID];choices.forEach((choice,index)=>answerAndAdvance(api,choice,index===choices.length-1));harness.runAll();return api}

test("metadata is the reserved driving-safety identity",()=>{assert.deepEqual(game.metadata,{id:ID,introducedIn:"2.0",category:"attention",tier:2,flavor:"classic",step:1,family:"attention-driving-safety"});assert.equal(typeof game.generate,"function");assert.equal(typeof game.validate,"function");assert.equal(typeof game.render,"function")});

test("render creates all game nodes through context.host.ownerDocument",()=>{const previous=globalThis.document,foreign=createFakeDocument("iframe");globalThis.document={createElement(){throw new Error("global document must not be used")}};try{const harness=createHarness({ownerDocument:foreign});game.render(game.generate({randomInt:min=>min}),harness.context);const visit=node=>{assert.equal(node.ownerDocument,foreign);node.children.forEach(visit)};visit(harness.host);assert.equal(foreign.activeElement,stageFrom(harness.host));harness.dispose()}finally{if(previous===undefined)delete globalThis.document;else globalThis.document=previous}});

test("5000 generations stay finite, cloneable, authored, and cover all five safety topics",()=>{const helpers=randomHelpers(),orders=new Set(),started=performance.now();for(let index=0;index<5000;index++){const task=game.generate(helpers);assert.deepEqual(game.validate(task),[]);assert.doesNotThrow(()=>structuredClone(task));assert.equal(task.questions.length,5);assert.equal(new Set(task.questions.map(question=>question.id)).size,5);assert.deepEqual(task.proof.answers,task.questions.map(question=>question.answer));assert.deepEqual(task.proof.ids,task.questions.map(question=>question.id));assert.equal(task.source.label,"本試験形式・警察庁教則準拠");assert.equal(task.source.confirmed,"2026-07-26");assert.match(task.source.url,/^https:\/\/www\.npa\.go\.jp\//);assert.doesNotMatch(`${task.prompt} ${task.help}`,/過去問|公式問題/);orders.add(task.order)}assert.equal(orders.size,5);assert.ok(performance.now()-started<1600)});

test("generation has an exact bounded fallback under hostile helpers",()=>{const low=game.generate({randomInt:()=>-999}),high=game.generate({randomInt:()=>999}),broken=game.generate({randomInt(){throw new Error("hostile")}});assert.equal(low.order,0);assert.equal(high.order,4);assert.deepEqual(broken,low);assert.deepEqual(game.validate(low),[]);assert.deepEqual(game.validate(high),[])});

test("validator rejects answer, scene, wording, source, proof, duration, order, and extras",()=>{const task=game.generate({randomInt:min=>min}),broken=structuredClone(task);broken.questions[0].answer=false;broken.questions[1].scene="generic-card";broken.questions[2].statement="changed";broken.source.confirmed="never";broken.proof.answers.pop();broken.duration=100;broken.order=99;broken.extra=true;const issues=game.validate(broken).join(" | ");for(const word of["questions","source","proof","duration","order","unexpected"])assert.match(issues,new RegExp(word))});

test("plain saved task resumes and all five causal answers finish true exactly once",async()=>{const restore=installFakeDocument();try{const task=structuredClone(game.generate({randomInt:min=>min})),fresh=(await import(`data:text/javascript;base64,${Buffer.from(moduleSource).toString("base64")}#resume-${Date.now()}`)).default,harness=createHarness();assert.deepEqual(fresh.validate(task),[]);fresh.render(task,harness.context);const api=finishAll(harness,task),state=api.inspect();assert.equal(state.phase,"final");assert.equal(state.result,"complete");assert.equal(state.score,5);assert.equal(state.answers.length,5);assert.equal(state.done,true);assert.deepEqual(harness.finishes.map(entry=>entry.correct),[true]);assert.equal(harness.finishes[0].result.reason,"complete");assert.equal(harness.finishes[0].result.score,5);const performanceLabel=canvasFrom(harness.host).getAttribute("aria-label");assert.match(performanceLabel,/携帯電話 正解/);assert.match(performanceLabel,/踏切 正解/);assert.doesNotMatch(performanceLabel,/[○×]/,"terminal performance badges must not reuse proposition-answer symbols");harness.triggerDeadline();api.answer(false);api.next();harness.runAll();assert.equal(harness.finishCalls,1);assert.equal(harness.finishes.length,1)}finally{restore()}});

test("every wrong choice still reveals correct action and reason before the next scene",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:min=>min}),harness=createHarness({reducedMotion:true});game.render(task,harness.context);const api=harness.qa[ID];for(let index=0;index<task.questions.length;index++){const question=task.questions[index];assert.equal(api.answer(!question.answer),"incorrect");assert.equal(api.inspect().phase,"review");assert.equal(controlsFrom(harness.host).hidden,true);const feedback=feedbackFrom(harness.host);assert.equal(feedback.hidden,false);assert.equal(feedback.dataset.correct,"false");assert.match(feedback.children[0].textContent,/あなたの回答/);assert.match(feedback.children[0].textContent,/正答/);assert.match(feedback.children[1].children[0].textContent,/正しい行動/);assert.equal(feedback.children[1].children[1].textContent,question.action);assert.match(feedback.children[2].children[0].textContent,/理由/);assert.equal(feedback.children[2].children[1].textContent,question.reason);assert.match(feedback.children[3].children[1].textContent,/警察庁教則 2024年11月版/);assert.match(feedback.children[3].children[1].textContent,/2026-07-26確認/);assert.equal(api.next(),false,"transition must settle before continuing");api.completeTransition();assert.equal(api.next(),index===task.questions.length-1?"complete":"next")}harness.runAll();assert.deepEqual(harness.finishes.map(entry=>entry.correct),[false]);assert.equal(harness.finishes[0].result.score,0);assert.equal(api.inspect().answers.length,5)}finally{restore()}});

test("mixed answers all remain causal and produce one score-led incomplete final",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:min=>min}),harness=createHarness(),choices=[true,true,false,true,true];game.render(task,harness.context);const api=finishAll(harness,task,choices);assert.equal(api.inspect().score,3);assert.equal(api.inspect().answers.length,5);assert.equal(stageFrom(harness.host).dataset.phase,"final");assert.match(paperFrom(harness.host).textContent,/3問/);const performanceLabel=canvasFrom(harness.host).getAttribute("aria-label");assert.match(performanceLabel,/横断歩道 正解/);assert.match(performanceLabel,/携帯電話 不正解/);assert.match(performanceLabel,/踏切 正解/);assert.doesNotMatch(performanceLabel,/[○×]/,"terminal performance badges must say 正解 or 不正解");assert.deepEqual(harness.finishes.map(entry=>entry.correct),[false]);assert.equal(harness.finishes[0].result.score,3)}finally{restore()}});

test("deadline after partial progress commits timeout once and preserves progress",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:min=>min}),harness=createHarness();game.render(task,harness.context);const api=harness.qa[ID];api.answer(task.questions[0].answer);api.completeTransition();api.next();assert.equal(harness.triggerDeadline(),true);assert.equal(harness.triggerDeadline(),false);assert.equal(api.inspect().phase,"timeout");assert.equal(api.inspect().result,"timeout");assert.match(paperFrom(harness.host).textContent,/1問回答/);assert.deepEqual(harness.finishes.map(entry=>entry.correct),[false]);assert.equal(harness.finishes[0].result.reason,"timeout");assert.equal(harness.finishes[0].result.answered,1);api.answer(false);api.next();assert.equal(harness.finishCalls,1)}finally{restore()}});

test("reduced feedback uses tracked finite stages and owns no animation frame",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:min=>min}),harness=createHarness({reducedMotion:true});game.render(task,harness.context);const api=harness.qa[ID];assert.equal(api.answer(true),"correct");assert.equal(api.inspect().transition.progress,0);assert.ok(harness.pendingCount>=3);assert.equal(harness.frameCount,0);harness.runFor(70);assert.equal(api.inspect().transition.progress,.42);harness.runFor(70);assert.equal(api.inspect().transition.progress,.76);harness.runFor(70);assert.equal(api.inspect().busy,false);assert.equal(document.activeElement,nextFrom(harness.host));assert.equal(api.inspect().frames,0)}finally{restore()}});

test("dispose during feedback cancels stages, deadline, listeners, frame, QA, and finish",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:min=>min}),harness=createHarness({reducedMotion:true});game.render(task,harness.context);harness.qa[ID].answer(true);assert.ok(harness.pendingCount>=3);harness.dispose();harness.runAll();harness.triggerDeadline();assert.equal(harness.pendingCount,0);assert.equal(harness.listenerCount,0);assert.equal(harness.frameCount,0);assert.equal(harness.finishes.length,0);assert.equal(harness.qa[ID],undefined)}finally{restore()}});

test("touch and keyboard paths, visible focus state, and DPR3 backing work at 402 by 874",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:min=>min}),harness=createHarness({reducedMotion:true,viewport:{width:402,height:874,dpr:3}});game.render(task,harness.context);const api=harness.qa[ID],stage=stageFrom(harness.host),circle=controlsFrom(harness.host).children[0];assert.equal(document.activeElement,stage);circle.dispatchEvent(eventWith("pointerdown",{pointerType:"touch"}));assert.equal(api.inspect().selected,true);assert.equal(api.inspect().answers.length,0);assert.equal(circle.dataset.selected,"true");circle.dispatchEvent(eventWith("click",{detail:1}));assert.equal(api.inspect().answers.length,1);harness.runFor(210);nextFrom(harness.host).dispatchEvent(eventWith("click",{detail:0}));stage.dispatchEvent(eventWith("keydown",{key:"X"}));assert.equal(api.inspect().answers.length,2);harness.runFor(210);nextFrom(harness.host).dispatchEvent(eventWith("click",{detail:0}));stage.dispatchEvent(eventWith("keydown",{key:"ArrowRight"}));assert.equal(document.activeElement,controlsFrom(harness.host).children[1]);controlsFrom(harness.host).children[1].dispatchEvent(eventWith("click",{detail:0}));assert.equal(api.inspect().answers.length,3);const view=api.inspect().canvas;assert.equal(view.dpr,3);assert.equal(view.width,view.cssWidth*3);assert.equal(view.height,view.cssHeight*3);assert.equal(stage.dataset.reduced,"true");assert.equal(harness.frameCount,0)}finally{restore()}});

test("real reduced kernel advances feedback and disposes without a delayed commit",async()=>{const restore=installFakeDocument(),previousCancel=globalThis.cancelAnimationFrame;globalThis.cancelAnimationFrame=()=>{};try{const task=game.generate({randomInt:min=>min}),qa={},finishes=[],host=document.createElement("div");host.getBoundingClientRect=()=>({width:393,height:852});const runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(task,runtime.context);qa[ID].answer(true);assert.ok(runtime.inspect().timeouts>=4);assert.equal(runtime.inspect().frames,0);await delay(230);assert.equal(qa[ID].inspect().busy,false);runtime.dispose();assert.equal(qa[ID],undefined);await delay(240);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{restore();if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}});

test("normal tracked canvas sustains a high-resolution 60fps-equivalent workload",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(4)),harness=createHarness({viewport:{width:430,height:932,dpr:3}});game.render(task,harness.context);const started=performance.now();harness.stepFrames(600);const elapsed=performance.now()-started,state=harness.qa[ID].inspect();assert.equal(state.frames,600);assert.ok(elapsed<950,`600 frames took ${elapsed.toFixed(1)}ms`);assert.equal(harness.frameCount,1);harness.dispose()}finally{restore()}});

test("source stays ownerDocument-only, tracked-lifetime, offline, audio-free, and past-question-claim free",()=>{assert.match(moduleSource,/context\.host\?\.ownerDocument/);assert.doesNotMatch(moduleSource,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(moduleSource,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(moduleSource,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement)\b/);assert.doesNotMatch(moduleSource,/公式過去問|本試験過去問/);assert.doesNotMatch(moduleSource,/[\u{1F300}-\u{1FAFF}]/u)});
