import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";

const moduleUrl=new URL("../src/games/attention-screw-out-v1.js",import.meta.url),moduleSource=await readFile(moduleUrl,"utf8");
const importGame=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${moduleSource}\n// ${suffix}`).toString("base64")}`)).default;
const game=await importGame("primary"),ID="attention-screw-out-v1";
function randomHelpers(initialSeed=0x51a7){let seed=initialSeed>>>0;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32),randomInt=(min,max)=>min+Math.floor(random()*(max-min+1));return{random,randomInt,pick:values=>values[randomInt(0,values.length-1)],shuffle:values=>[...values]}}
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}toggle(value,force){const add=force===undefined?!this.values.has(value):force;add?this.values.add(value):this.values.delete(value);this.sync();return add}sync(){this.owner._className=[...this.values].join(" ")}}
class FakeStyle{constructor(){this.values=new Map()}setProperty(name,value){this.values.set(name,String(value))}}
const noop=()=>{};function fakeCanvasContext(){const gradient={addColorStop:noop};return new Proxy({createLinearGradient:()=>gradient,createRadialGradient:()=>gradient},{get(target,key){return key in target?target[key]:noop},set(target,key,value){target[key]=value;return true}})}
class FakeElement extends EventTarget{constructor(tagName,ownerDocument){super();this.tagName=tagName.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.attributes=new Map();this.dataset={};this.style=new FakeStyle();this.classList=new FakeClassList(this);this._className="";this.textContent="";this.type="";this.disabled=false;this.width=0;this.height=0}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this.children=[...nodes]}setAttribute(name,value){this.attributes.set(name,String(value))}getAttribute(name){return this.attributes.get(name)??null}focus(){this.ownerDocument.activeElement=this}getContext(kind){return this.tagName==="CANVAS"&&kind==="2d"?fakeCanvasContext():null}getBoundingClientRect(){const width=Number.parseFloat(this.style.width)||390,height=Number.parseFloat(this.style.height)||359;return{left:0,top:0,width,height,right:width,bottom:height}}}
function createFakeDocument(name="document"){const view=new EventTarget();view.devicePixelRatio=3;const documentRef={name,activeElement:null,defaultView:view};documentRef.createElement=tag=>new FakeElement(tag,documentRef);return documentRef}
function installFakeDocument(){const previous=globalThis.document;globalThis.document=createFakeDocument("global");return()=>{if(previous===undefined)delete globalThis.document;else globalThis.document=previous}}
function createHarness({reducedMotion=false,viewport={width:390,height:844,dpr:2},ownerDocument=globalThis.document}={}){const controller=new AbortController(),host=ownerDocument.createElement("div"),qa={},pending=[],listeners=new Set(),finishes=[];let deadline=null,disposed=false,frameCalls=0;host.getBoundingClientRect=()=>({left:0,top:0,width:viewport.width-16,height:viewport.height,right:viewport.width-16,bottom:viewport.height});const context={host,signal:controller.signal,reducedMotion,viewport,qa,finish(correct,result){if(disposed||finishes.length)return false;finishes.push({correct,result});return true},setDeadline(ms,fn){deadline={ms,fn,active:true};return deadline},later(fn,ms){const job={fn,ms,active:true};pending.push(job);return job},frame(){frameCalls++;return()=>{}},listen(target,type,fn,options){target.addEventListener(type,fn,options);const record={target,type,fn,options};listeners.add(record);return()=>{target.removeEventListener(type,fn,options);listeners.delete(record)}}};const runAll=()=>{let guard=0;while(pending.some(job=>job.active)){if(++guard>100)throw Error("pending loop");const jobs=pending.splice(0);jobs.forEach(job=>{if(job.active&&!disposed){job.active=false;job.fn()}})}};const triggerDeadline=()=>{if(deadline?.active&&!disposed){deadline.active=false;deadline.fn()}};const dispose=()=>{if(disposed)return;controller.abort();disposed=true;pending.forEach(job=>job.active=false);if(deadline)deadline.active=false;listeners.forEach(({target,type,fn,options})=>target.removeEventListener(type,fn,options));listeners.clear()};return{context,host,qa,finishes,runAll,triggerDeadline,dispose,get pendingCount(){return pending.filter(job=>job.active).length},get listenerCount(){return listeners.size},get frameCalls(){return frameCalls}}}
const eventWith=(type,properties={})=>{const event=new Event(type,{bubbles:true,cancelable:true});Object.entries(properties).forEach(([key,value])=>Object.defineProperty(event,key,{value}));return event};
const stage=host=>host.children[1],board=host=>stage(host).children[1],boltButtons=host=>board(host).children[1].children;
const publishedFallback=()=>({kind:"screwOut",prompt:"ボルトを抜く順番を読んで",help:"上に乗った板の下のボルトは回せません。",plates:[{id:0,layer:0,dir:"h",r:1,c0:0,c1:2,color:"#F2953F",bolts:[3,5],covers:[4]},{id:1,layer:1,dir:"v",c:1,r0:0,r1:2,color:"#5FB6E0",bolts:[1,7],covers:[]},{id:2,layer:2,dir:"h",r:2,c0:0,c1:1,color:"#66C08C",bolts:[6,7],covers:[]}],bolts:[3,5,1,7,6],answer:[3,5,1,7,6],wins:1,total:120,duration:60000});

const solve=(task,harness)=>{for(const bolt of task.answer){assert.equal(harness.qa[ID].pull(bolt),"started");harness.runAll()}};

test("metadata is the published stable identity",()=>{assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.11",tier:2,flavor:"quirky",step:1,family:"attention-screw-out",category:"attention"});assert.equal(typeof game.generate,"function");assert.equal(typeof game.validate,"function");assert.equal(typeof game.render,"function")});
test("render creates every node from context.host.ownerDocument, not global document",()=>{const previous=globalThis.document,foreign=createFakeDocument("iframe");globalThis.document={createElement(){throw Error("global document used")}};try{const harness=createHarness({ownerDocument:foreign}),task=game.generate(randomHelpers(3));game.render(task,harness.context);const visit=node=>{assert.equal(node.ownerDocument,foreign);node.children.forEach(visit)};visit(harness.host);assert.equal(foreign.activeElement,null);harness.dispose()}finally{if(previous===undefined)delete globalThis.document;else globalThis.document=previous}});
test("2500 generated puzzles terminate, clone, preserve dependencies, and are exhaustively exact",()=>{const helpers=randomHelpers(),wins=new Set(),layouts=new Set(),started=performance.now();for(let index=0;index<2500;index++){const task=game.generate(helpers),issues=game.validate(task);assert.deepEqual(issues,[],`generation ${index}: ${issues}`);assert.doesNotThrow(()=>structuredClone(task));assert.equal(task.plates.length,3);assert.equal(task.bolts.length,6);assert.equal(new Set(task.bolts).size,6);assert.equal(task.total,720);assert.ok(task.wins/task.total<=.2);assert.ok(task.plates.some(plate=>plate.covers.length));wins.add(task.wins);layouts.add(JSON.stringify(task.plates))}assert.deepEqual([...wins].sort((a,b)=>a-b),[48,80]);assert.ok(layouts.size>=8);assert.ok(performance.now()-started<30000,"2500 proof validations exceeded the runaway guard")});
test("generation is bounded and returns a strict authored fallback",()=>{const task=game.generate({random:()=>0,randomInt:min=>min});assert.deepEqual(game.validate(task),[]);assert.deepEqual(task.answer,[0,2,6,8,1,7]);assert.equal(task.wins,80);assert.equal(task.total,720)});
test("validator rejects changed geometry, endpoints, dependencies, answer order, counts, and solvability metadata",()=>{const task=game.generate(randomHelpers(9));const geometry=structuredClone(task);if(geometry.plates[0].dir==="h")geometry.plates[0].c1=9;else geometry.plates[0].r1=9;assert.match(game.validate(geometry).join(" | "),/span/);const endpoints=structuredClone(task);endpoints.plates[1].bolts[0]=0;assert.match(game.validate(endpoints).join(" | "),/endpoints|endpoint order/);const covers=structuredClone(task);covers.plates[0].covers=[];assert.match(game.validate(covers).join(" | "),/dependency/);const answer=structuredClone(task);[answer.answer[0],answer.answer[1]]=[answer.answer[1],answer.answer[0]];assert.match(game.validate(answer).join(" | "),/first exhaustive/);const wins=structuredClone(task);wins.wins++;assert.match(game.validate(wins).join(" | "),/exhaustive solvability/);const total=structuredClone(task);total.total--;assert.match(game.validate(total).join(" | "),/every bolt permutation/)});
test("validator reports malformed plain data without throwing",()=>{const malformed={kind:"screwOut",prompt:"ボルトを抜く順番を読んで",help:"上に乗った板の下のボルトは回せません。",duration:60000,plates:[null,{},{}],bolts:[],answer:[],wins:0,total:1};let issues;assert.doesNotThrow(()=>{issues=game.validate(malformed)});assert.ok(issues.length>=5)});
test("the exact published emergency descriptor remains accepted for saved-session compatibility",()=>{const task=publishedFallback();assert.deepEqual(game.validate(task),[]);assert.equal(task.answer.length,5);const changed=structuredClone(task);changed.plates[0].covers=[];assert.notDeepEqual(game.validate(changed),[])});
test("published plain-data fallback resumes and completes correctly without mutation",()=>{const restore=installFakeDocument();try{const task=publishedFallback(),saved=JSON.stringify(task),harness=createHarness({reducedMotion:true});game.render(structuredClone(task),harness.context);solve(task,harness);assert.deepEqual(harness.finishes.map(entry=>entry.correct),[true]);assert.equal(harness.qa[ID].inspect().remaining,0);assert.equal(JSON.stringify(task),saved);harness.triggerDeadline();assert.equal(harness.finishes.length,1)}finally{restore()}});
test("plain generated JSON resumes through a fresh module and exact winning order",async()=>{const restore=installFakeDocument();try{const task=JSON.parse(JSON.stringify(game.generate(randomHelpers(7)))),fresh=await importGame(`resume-${Date.now()}`);assert.deepEqual(fresh.validate(task),[]);const harness=createHarness({reducedMotion:true});fresh.render(task,harness.context);solve(task,harness);assert.deepEqual(harness.finishes.map(entry=>entry.correct),[true]);assert.match(harness.finishes[0].result.detail,/3枚/)}finally{restore()}});
test("a legal removal causes visible progress before the remaining dependency opens",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(3)),harness=createHarness({reducedMotion:true});game.render(task,harness.context);const before=harness.qa[ID].inspect(),bolt=task.answer[0];assert.equal(harness.qa[ID].pull(bolt),"started");assert.equal(harness.qa[ID].inspect().busy,true);harness.runAll();const after=harness.qa[ID].inspect();assert.deepEqual(after.removed,[bolt]);assert.equal(after.order.length,1);assert.ok(after.remaining<=before.remaining);assert.match(after.status,/外れました/)}finally{restore()}});
test("pulling a covered bolt is blocked, shakes its plate, and finishes incorrect once",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(9)),harness=createHarness();game.render(task,harness.context);const blocked=harness.qa[ID].blockedBolt();assert.ok(Number.isInteger(blocked));assert.equal(harness.qa[ID].pull(blocked),"blocked");assert.equal(board(harness.host).classList.contains("aso-blocked"),true);assert.equal(harness.qa[ID].inspect().blocked,blocked);harness.runAll();assert.deepEqual(harness.finishes.map(entry=>entry.correct),[false]);assert.equal(harness.finishes[0].result.reason,"blocked");harness.triggerDeadline();assert.equal(harness.finishes.length,1)}finally{restore()}});
test("the winning order removes all plates and success commits exactly once",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(6)),harness=createHarness();game.render(task,harness.context);solve(task,harness);assert.deepEqual(harness.finishes.map(entry=>entry.correct),[true]);assert.equal(board(harness.host).classList.contains("aso-success"),true);assert.equal(harness.qa[ID].inspect().remaining,0);assert.equal(harness.qa[ID].pull(task.answer[0]),false);harness.triggerDeadline();assert.equal(harness.finishes.length,1)}finally{restore()}});
test("deadline with plates remaining paints timeout and finishes incorrect exactly once",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(7)),harness=createHarness();game.render(task,harness.context);harness.triggerDeadline();harness.triggerDeadline();assert.deepEqual(harness.finishes.map(entry=>entry.correct),[false]);assert.equal(harness.finishes[0].result.reason,"timeout");assert.equal(board(harness.host).classList.contains("aso-timeout"),true);assert.match(harness.qa[ID].inspect().status,/時間切れ/)}finally{restore()}});
test("dispose cancels removal, success, deadline, listeners, frame ownership, and QA",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(8)),harness=createHarness();game.render(task,harness.context);assert.equal(harness.qa[ID].pull(task.answer[0]),"started");assert.ok(harness.pendingCount>0);assert.equal(harness.frameCalls,1);harness.dispose();harness.runAll();harness.triggerDeadline();assert.equal(harness.finishes.length,0);assert.equal(harness.pendingCount,0);assert.equal(harness.listenerCount,0);assert.equal(harness.qa[ID],undefined)}finally{restore()}});
test("real createGameRuntime disposal synchronously removes QA and all tracked work",async()=>{const restore=installFakeDocument(),previousRaf=globalThis.requestAnimationFrame,previousCancel=globalThis.cancelAnimationFrame;globalThis.requestAnimationFrame=callback=>setTimeout(()=>callback(performance.now()),0);globalThis.cancelAnimationFrame=id=>clearTimeout(id);try{const task=game.generate(randomHelpers(10)),qa={},finishes=[],host=document.createElement("div");host.getBoundingClientRect=()=>({width:393,height:852});const runtime=createGameRuntime({host,qa,reducedMotion:false,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(task,runtime.context);qa[ID].pull(task.answer[0]);assert.ok(runtime.inspect().timeouts>=2);runtime.dispose();assert.equal(qa[ID],undefined);await delay(700);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{restore();if(previousRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=previousRaf;if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}});
test("pointer/touch and keyboard controls keep visible focus and preserve reduced-motion DPR",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(11)),harness=createHarness({reducedMotion:true,viewport:{width:402,height:874,dpr:3}});game.render(task,harness.context);const buttons=boltButtons(harness.host),first=buttons[task.bolts.indexOf(task.answer[0])];buttons[0].focus();assert.equal(document.activeElement,buttons[0]);buttons[0].dispatchEvent(eventWith("keydown",{key:"ArrowRight"}));assert.ok(document.activeElement!==null);first.dispatchEvent(eventWith("pointerdown",{pointerId:9}));assert.equal(harness.qa[ID].inspect().busy,true);harness.runAll();assert.equal(harness.qa[ID].inspect().removed.includes(task.answer[0]),true);const canvas=harness.qa[ID].inspect().canvas;assert.equal(canvas.dpr,3);assert.equal(canvas.width,canvas.cssWidth*3);assert.equal(canvas.height,canvas.cssHeight*3);assert.equal(harness.frameCalls,0);assert.equal(stage(harness.host).dataset.reduced,"true")}finally{restore()}});
test("source uses ownerDocument, tracked lifetime APIs, and no network path",()=>{assert.match(moduleSource,/context\.host\?\.ownerDocument/);assert.doesNotMatch(moduleSource,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(moduleSource,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(moduleSource,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon)\b/)});
