import game from"../src/games/attention-kana-count-v1.js";
import{createGameRuntime}from"../src/game-kernel.js";
const TARGETS=["さ","き","の"],CHARS=["さ","き","の","ち","ら"],DELTAS=[-3,-2,-1,1,2,3];
function tracedCase(index){const traces=[],cases=[{target:"さ",indices:[0,1,2,3,4,0,1,2,3,4,0,1,2,3,4,0,1,0],deltas:[-3,-2,-1],shuffle:values=>[values[2],values[0],values[3],values[1]],label:"SA · COUNT 5"},{target:"き",indices:[0,2,3,4,0,2,3,4,0,2,3,4,0,2,3,4,0,2],deltas:[-3,-2,-1,1,2,3],shuffle:values=>[...values].reverse(),label:"KI · COUNT 0 · CLAMP"},{target:"の",indices:[2,2,0,2,1,2,3,2,4,2,0,2,1,2,3,2,4,0],deltas:[1,-2,3],shuffle:values=>[...values],label:"NO · COUNT 9"}][index],indices=[...cases.indices],deltas=[...cases.deltas],helper={pick(values){let value;if(values.length===TARGETS.length&&values.every((item,i)=>item===TARGETS[i])&&traces.length===0)value=cases.target;else if(values.length===CHARS.length&&values.every((item,i)=>item===CHARS[i]))value=values[indices.shift()];else if(values.length===DELTAS.length&&values.every((item,i)=>item===DELTAS[i]))value=deltas.shift();else throw new Error("unexpected pick domain");traces.push({kind:"pick",values:[...values],value});return value},shuffle(values){const value=cases.shuffle([...values]);traces.push({kind:"shuffle",values:[...values],value:[...value]});return value}},task=game.generate(helper);return{task,traces,label:cases.label}}
const CASES=Object.freeze([0,1,2].map(index=>{const value=tracedCase(index);return Object.freeze({task:Object.freeze(value.task),traces:Object.freeze(value.traces),label:value.label})})),params=new URLSearchParams(location.search),width=Number(params.get("width"))||393,motion=params.get("motion")==="reduced"?"reduced":"normal",family=Math.max(0,Math.min(2,Number(params.get("family"))||0)),requestedScene=params.get("scene")||"initial",reduced=motion==="reduced",live=params.get("live")==="1",auto=params.get("auto")==="1",task=CASES[family].task,host=document.querySelector("#challenge"),result=document.querySelector("#result"),qa={},finishes=[],errors=[];document.body.style.width=`${width}px`;document.querySelector("#prompt").textContent=task.prompt;document.querySelector("#help").textContent=task.help;addEventListener("error",event=>errors.push(event.message||"page error"));addEventListener("unhandledrejection",event=>errors.push(String(event.reason)));
const runtime=createGameRuntime({host,qa,reducedMotion:reduced,viewport:{width,height:innerHeight,dpr:devicePixelRatio},onFinish:(correct,payload)=>{finishes.push({correct,payload});result.hidden=false;result.textContent=`${correct?"正解":"残念"} · ${payload.detail||`正解は「${payload.answerLabel}」`}`}});game.render(structuredClone(task),runtime.context);const api=qa[game.metadata.id];if(!live&&!auto&&!api.showScene(requestedScene))throw new Error(`unknown scene ${requestedScene}`);
const evidence=()=>{const resources=performance.getEntriesByType("resource"),external=resources.filter(entry=>new URL(entry.name).origin!==location.origin),state=api.inspect();return{variant:"module",family,label:CASES[family].label,traces:structuredClone(CASES[family].traces),requestedScene,renderedScene:requestedScene,live,auto,motion,width,dpr:devicePixelRatio,task:structuredClone(task),state,finishes:structuredClone(finishes),runtime:runtime.inspect(),layout:{scrollWidth:document.body.scrollWidth,innerWidth},resources:resources.map(entry=>entry.name),external:external.map(entry=>entry.name),errors:[...errors]}};
if(auto){const buttons=host.querySelectorAll(".akc-choice"),stage=host.querySelector(".akc-stage"),answerIndex=task.options.indexOf(task.answer);if(family!==1)buttons[answerIndex].dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:17,pointerType:"touch"}));else{stage.focus();const row=Math.floor(answerIndex/2),column=answerIndex%2;for(let i=0;i<column;i++)stage.dispatchEvent(new KeyboardEvent("keydown",{bubbles:true,cancelable:true,key:"ArrowRight"}));for(let i=0;i<row;i++)stage.dispatchEvent(new KeyboardEvent("keydown",{bubbles:true,cancelable:true,key:"ArrowDown"}));stage.dispatchEvent(new KeyboardEvent("keydown",{bubbles:true,cancelable:true,key:"Enter"}))}}
if(params.get("measureLog")==="1"){const deltas=[],measure=(previous,count)=>requestAnimationFrame(now=>{deltas.push(now-previous);if(count<99)measure(now,count+1);else{const stable=deltas.slice(5),state=api.inspect(),query=new URLSearchParams({frames:String(stable.length),averageFrameMs:(stable.reduce((a,b)=>a+b,0)/stable.length).toFixed(3),maxFrameMs:Math.max(...stable).toFixed(3),gameFrames:String(state.frames),dpr:String(state.dpr),tokenCount:String(state.tokens.length)});location.replace(`attention-kana-count-v1.performance-result.html?${query}`)}});measure(performance.now(),0)}
window.__ATTENTION_KANA_COUNT_MODULE_FIXTURE__={game,cases:CASES.map(value=>({task:structuredClone(value.task),traces:structuredClone(value.traces),label:value.label})),task:structuredClone(task),qa,api,runtime,evidence};document.documentElement.dataset.ready="true";
