import game from "../src/games/attention-author-boss-v1.js";
import{createGameRuntime}from"../src/game-kernel.js";
const TASK=Object.freeze({kind:"authorBoss",prompt:"変則ムーブの作者を3回つかまえて",help:"残像・フェイント・画面外逃走を見切ってタップ。",hits:3,duration:10000});
const params=new URLSearchParams(location.search),width=Number(params.get("width"))||393,motion=params.get("motion")==="reduced"?"reduced":"normal",requestedScene=params.get("scene")||"ready",reduced=motion==="reduced",live=params.get("live")==="1",auto=params.get("auto")==="1",host=document.querySelector("#challenge"),result=document.querySelector("#result"),qa={},finishes=[],errors=[];document.body.style.width=`${width}px`;addEventListener("error",event=>errors.push(event.message||"page error"));addEventListener("unhandledrejection",event=>errors.push(String(event.reason)));
const runtime=createGameRuntime({host,qa,reducedMotion:reduced,viewport:{width,height:innerHeight,dpr:devicePixelRatio},onFinish:(correct,payload)=>{finishes.push({correct,payload});result.hidden=false;result.textContent=`${correct?"成功":"失敗"} — ${payload.detail}`}});game.render(structuredClone(TASK),runtime.context);const api=qa[game.metadata.id];if(!live&&!auto&&!api.showScene(requestedScene))throw new Error(`unknown scene ${requestedScene}`);
const evidence=()=>{const resources=performance.getEntriesByType("resource"),external=resources.filter(entry=>new URL(entry.name).origin!==location.origin),state=api?.inspect?.()||null;return{variant:"module",requestedScene,renderedScene:requestedScene,live,auto,motion,width,dpr:devicePixelRatio,task:structuredClone(TASK),constants:{hits:3,duration:10000,modes:["afterimage","dance","vanish"],afterimageMs:520,vanishMs:430,interModeMs:240},state,finishes:structuredClone(finishes),runtime:runtime.inspect(),layout:{scrollWidth:document.body.scrollWidth,innerWidth,canvas:state?.canvas||null},resources:resources.map(entry=>entry.name),external:external.map(entry=>entry.name),errors:[...errors]}};
if(auto){const target=host.querySelector(".ab-target"),stage=host.querySelector(".ab-stage");let hit=0;const drive=()=>{const current=api?.inspect();if(!current||current.done)return;if(!current.ready){setTimeout(drive,40);return}if(hit===0)target.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:19,pointerType:"touch"}));else if(hit===1){target.focus();target.dispatchEvent(new KeyboardEvent("keydown",{bubbles:true,cancelable:true,key:"Enter"}))}else{const dx=current.targetPos.x-current.cursor.x,dy=current.targetPos.y-current.cursor.y;api.moveCursor(dx,dy);stage.focus();stage.dispatchEvent(new KeyboardEvent("keydown",{bubbles:true,cancelable:true,key:"Enter"}))}hit++;setTimeout(drive,60)};drive()}
if(params.get("measureLog")==="1"){const deltas=[];let previous=performance.now(),count=0;const measure=now=>{deltas.push(now-previous);previous=now;if(++count<100)requestAnimationFrame(measure);else{const stable=deltas.slice(5),state=api.inspect(),query=new URLSearchParams({frames:String(stable.length),averageFrameMs:(stable.reduce((a,b)=>a+b,0)/stable.length).toFixed(3),maxFrameMs:Math.max(...stable).toFixed(3),gameFrames:String(state.frames),pixelWidth:String(state.canvas.pixelWidth),pixelHeight:String(state.canvas.pixelHeight),dpr:String(state.canvas.dpr)});location.replace(`attention-author-boss-v1.performance-result.html?${query}`)}};requestAnimationFrame(measure)}
window.__AUTHOR_BOSS_MODULE_FIXTURE__={game,task:structuredClone(TASK),qa,api,runtime,evidence};document.documentElement.dataset.ready="true";
