import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";

const moduleUrl=new URL("../src/games/attention-farm-close-v1.js",import.meta.url);
const moduleSource=await readFile(moduleUrl,"utf8");
const game=(await import(`data:text/javascript;base64,${Buffer.from(moduleSource).toString("base64")}`)).default;
const ID="attention-farm-close-v1";

function randomHelpers(initialSeed=0x5eed4312){
  let seed=initialSeed>>>0;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/0x100000000);const randomInt=(min,max)=>min+Math.floor(random()*(max-min+1));
  return{random,randomInt,pick:values=>values[randomInt(0,values.length-1)],shuffle:values=>[...values].sort(()=>random()-.5)};
}
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}sync(){this.owner._className=[...this.values].join(" ")}}
class FakeStyle{constructor(){this.values=new Map()}setProperty(name,value){this.values.set(name,String(value))}}
const noop=()=>{};
function fakeCanvasContext(){const gradient={addColorStop:noop};return new Proxy({createLinearGradient:()=>gradient,createRadialGradient:()=>gradient,measureText:()=>({width:10})},{get(target,key){return key in target?target[key]:noop},set(target,key,value){target[key]=value;return true}})}
class FakeElement extends EventTarget{
  constructor(tagName,ownerDocument){super();this.tagName=tagName.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.attributes=new Map();this.dataset={};this.style=new FakeStyle();this.classList=new FakeClassList(this);this._className="";this.textContent="";this.type="";this.disabled=false;this.hidden=false;this.tabIndex=-1;this.width=0;this.height=0}
  set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}
  append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this.children=[...nodes]}
  setAttribute(name,value){this.attributes.set(name,String(value))}getAttribute(name){return this.attributes.get(name)??null}
  focus(){this.ownerDocument.activeElement=this}get offsetWidth(){return this.ownerDocument.viewportWidth||390}
  getContext(kind){return this.tagName==="CANVAS"&&kind==="2d"?fakeCanvasContext():null}
  getBoundingClientRect(){const width=Number.parseFloat(this.style.width)||this.ownerDocument.viewportWidth||390,height=Number.parseFloat(this.style.height)||Math.round(width*1.03);return{left:0,top:0,width,height,right:width,bottom:height}}
}
function createFakeDocument(name="document"){const view=new EventTarget();view.devicePixelRatio=3;view.performance=globalThis.performance;const documentRef={name,activeElement:null,defaultView:view,viewportWidth:390};documentRef.createElement=tag=>new FakeElement(tag,documentRef);return documentRef}
function installFakeDocument(){const previous=globalThis.document;globalThis.document=createFakeDocument("global");return()=>{if(previous===undefined)delete globalThis.document;else globalThis.document=previous}}
function createHarness({reducedMotion=false,viewport={width:393,height:852,dpr:3},ownerDocument=globalThis.document}={}){
  const controller=new AbortController(),host=ownerDocument.createElement("div"),qa={},pending=[],listeners=new Set(),frames=new Set(),finishes=[];let deadline=null,disposed=false,finishCalls=0,frameTime=performance.now(),timerClock=0;ownerDocument.viewportWidth=viewport.width;host.getBoundingClientRect=()=>({left:0,top:0,width:viewport.width,height:viewport.height,right:viewport.width,bottom:viewport.height});
  const context={host,signal:controller.signal,reducedMotion,viewport,qa,
    finish(correct,result){finishCalls++;if(disposed||finishes.length)return false;finishes.push({correct,result});return true},
    setDeadline(ms,fn){deadline={ms,fn,active:true};return deadline},
    later(fn,ms){const job={fn,ms,at:timerClock+Math.max(0,Number(ms)||0),active:true};pending.push(job);return job},
    frame(fn){const loop={fn,active:true};frames.add(loop);return()=>{loop.active=false;frames.delete(loop)}},
    listen(target,type,fn,options){target.addEventListener(type,fn,options);const record={target,type,fn,options};listeners.add(record);return()=>{target.removeEventListener(type,fn,options);listeners.delete(record)}}
  };
  const nextPending=()=>pending.filter(item=>item.active).sort((a,b)=>a.at-b.at)[0]||null;
  const runNext=()=>{const job=nextPending();if(!job||disposed)return false;timerClock=job.at;job.active=false;job.fn();return true};
  const runFor=ms=>{const target=timerClock+Math.max(0,Number(ms)||0);let guard=0,job=nextPending();while(job&&job.at<=target&&!disposed&&guard++<1000){timerClock=job.at;job.active=false;job.fn();job=nextPending()}if(guard>=1000)throw new Error("timed work did not settle");timerClock=target};
  const runAll=()=>{let guard=0,job=nextPending();while(job&&!disposed&&guard++<100){timerClock=job.at;job.active=false;job.fn();job=nextPending()}if(guard>=100)throw new Error("pending work did not settle")};
  const stepFrames=(count=1,step=1000/60)=>{for(let index=0;index<count;index++){frameTime+=step;for(const loop of[...frames])if(loop.active&&loop.fn(frameTime)===false){loop.active=false;frames.delete(loop)}}};
  const triggerDeadline=()=>{if(deadline?.active&&!disposed){deadline.active=false;deadline.fn();return true}return false};
  const dispose=()=>{if(disposed)return;disposed=true;if(deadline)deadline.active=false;pending.forEach(job=>job.active=false);frames.clear();controller.abort();listeners.forEach(({target,type,fn,options})=>target.removeEventListener(type,fn,options));listeners.clear()};
  return{context,host,qa,finishes,runNext,runFor,runAll,stepFrames,triggerDeadline,dispose,get pendingCount(){return pending.filter(job=>job.active).length},get listenerCount(){return listeners.size},get frameCount(){return frames.size},get finishCalls(){return finishCalls}};
}
const eventWith=(type,properties={})=>{const event=new Event(type,{bubbles:true,cancelable:true});Object.entries(properties).forEach(([key,value])=>Object.defineProperty(event,key,{value}));return event};
const stageFrom=host=>host.children[1],boardFrom=host=>stageFrom(host).children[1],canvasFrom=host=>boardFrom(host).children[0],inventoryFrom=host=>stageFrom(host).children[2],toolPanelFrom=host=>stageFrom(host).children[3],zonePanelFrom=host=>stageFrom(host).children[4],closeButtonFrom=host=>stageFrom(host).children[5],checkPanelFrom=host=>stageFrom(host).children[6],drivePanelFrom=host=>stageFrom(host).children[7];
const toolButton=(host,id)=>toolPanelFrom(host).children.find(button=>button.dataset.id===id),zoneButton=(host,id)=>zonePanelFrom(host).children.find(button=>button.dataset.id===id),driveButton=(host,id)=>drivePanelFrom(host).children.find(button=>button.dataset.id===id);
function settle(api){assert.equal(api.completeTransition(),true)}
function followProof(harness,task){
  const api=harness.qa[ID];for(const trip of task.proof.trips){for(const id of trip){assert.equal(api.collect(id),"collecting");settle(api)}for(const id of trip){assert.equal(api.selectHeld(id),true);assert.equal(api.store(task.tools.find(tool=>tool.id===id).zone),"storing");settle(api)}}assert.equal(api.closeFarm(),"closing");settle(api);assert.equal(api.check("bed"),"checking");settle(api);assert.equal(api.check("gate"),"checking");settle(api);for(const choice of task.proof.drive){assert.equal(api.drive(choice),"driving");settle(api)}return api;
}

test("metadata is the reserved original-game identity",()=>{assert.deepEqual(game.metadata,{id:ID,introducedIn:"2.0",tier:3,flavor:"satisfying",step:1,family:"attention-farm-close",category:"attention"});assert.equal(typeof game.generate,"function");assert.equal(typeof game.validate,"function");assert.equal(typeof game.render,"function")});

test("render creates every node through context.host.ownerDocument",()=>{const previous=globalThis.document,foreign=createFakeDocument("iframe");globalThis.document={createElement(){throw new Error("global document must not be used")}};try{const task=game.generate(randomHelpers(1)),harness=createHarness({ownerDocument:foreign});game.render(task,harness.context);const visit=node=>{assert.equal(node.ownerDocument,foreign);node.children.forEach(visit)};visit(harness.host);assert.equal(foreign.activeElement,canvasFrom(harness.host));harness.dispose()}finally{if(previous===undefined)delete globalThis.document;else globalThis.document=previous}});

test("5000 generated closures are finite, cloneable, authored, and retain a real daylight proof",()=>{const helpers=randomHelpers(),pairs=new Set(),started=performance.now();for(let index=0;index<5000;index++){const task=game.generate(helpers);assert.deepEqual(game.validate(task),[],`generation ${index}`);assert.doesNotThrow(()=>structuredClone(task));assert.equal(task.tools.length,6);assert.equal(task.zones.length,4);assert.equal(task.capacity,2);assert.ok(task.duration>=30000&&task.duration<=55000);assert.equal(task.sunsetBudget-task.proof.cost,7);assert.equal(task.proof.trips.flat().length,6);assert.equal(new Set(task.proof.trips.flat()).size,6);assert.deepEqual(task.proof.checks,["bed","gate"]);pairs.add(`${task.layout}:${task.route}`)}assert.equal(pairs.size,36);assert.ok(performance.now()-started<2000)});

test("generation has a bounded exact fallback under hostile integer helpers",()=>{const low=game.generate({randomInt:()=>-999}),high=game.generate({randomInt:()=>999});assert.equal(low.layout,0);assert.equal(low.route,0);assert.equal(high.layout,5);assert.equal(high.route,5);assert.deepEqual(game.validate(low),[]);assert.deepEqual(game.validate(high),[])});

test("validator rejects geometry, capacity, zones, road, proof, budget, duration, copy, and extras",()=>{const task=game.generate(randomHelpers(8)),broken=structuredClone(task);broken.tools[0].x+=.01;broken.capacity=3;broken.zones[0].accepts.pop();broken.roadChoices[0]="right";broken.proof.cost++;broken.sunsetBudget++;broken.duration=1000;broken.prompt="changed";broken.extra=true;const issues=game.validate(broken).join(" | ");for(const word of["tools","capacity","zones","roadChoices","proof","sunsetBudget","duration","prompt","unexpected"])assert.match(issues,new RegExp(word))});

test("plain-data proof stores all tools, checks bed then gate, and reaches home exactly once",async()=>{const restore=installFakeDocument();try{const generated=game.generate(randomHelpers(12)),plain=structuredClone(generated),fresh=(await import(`data:text/javascript;base64,${Buffer.from(moduleSource).toString("base64")}#resume-${Date.now()}`)).default,harness=createHarness();assert.deepEqual(fresh.validate(plain),[]);fresh.render(plain,harness.context);const api=followProof(harness,plain),state=api.inspect();assert.equal(state.result,"success");assert.equal(state.phase,"home");assert.equal(state.stored.length,6);assert.deepEqual(state.checks,{bed:true,gate:true});assert.equal(state.roadIndex,plain.roadChoices.length);assert.equal(state.remaining,7);harness.runAll();assert.deepEqual(harness.finishes.map(entry=>entry.correct),[true]);assert.equal(harness.finishes[0].result.reason,"home");assert.match(harness.finishes[0].result.detail,/荷台と門/);harness.triggerDeadline();api.drive("left");harness.runAll();assert.equal(harness.finishes.length,1);assert.equal(harness.finishCalls,1)}finally{restore()}});

test("capacity two blocks a third pickup without spending daylight",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:min=>min}),harness=createHarness();game.render(task,harness.context);const api=harness.qa[ID];api.collect("hoe");settle(api);api.collect("rake");settle(api);const before=api.inspect();assert.equal(api.collect("sickle"),"full");const after=api.inspect();assert.deepEqual(after.carried,["hoe","rake"]);assert.equal(after.remaining,before.remaining);assert.match(after.status,/2つまで/);assert.equal(after.done,false)}finally{restore()}});

test("selected tool sent to a wrong semantic zone fails distinctly",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(21)),harness=createHarness();game.render(task,harness.context);const api=harness.qa[ID];api.collect("sickle");settle(api);assert.equal(api.store("rack"),"wrong-zone");harness.runAll();assert.equal(api.inspect().result,"wrong-zone");assert.equal(api.inspect().attemptedZone,"rack");assert.deepEqual(harness.finishes.map(entry=>entry.result.reason),["wrong-zone"]);assert.equal(boardFrom(harness.host).dataset.result,"wrong-zone")}finally{restore()}});

test("closing with visible or carried tools reports a left-behind failure",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(22)),harness=createHarness();game.render(task,harness.context);const api=harness.qa[ID];api.collect("hoe");settle(api);assert.equal(api.closeFarm(),"left-behind");harness.runAll();assert.equal(api.inspect().result,"left-behind");assert.match(harness.finishes[0].result.detail,/置き忘れ/)}finally{restore()}});

test("gate before truck-bed inspection is a separate check failure",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(23)),harness=createHarness();game.render(task,harness.context);const api=harness.qa[ID];for(const trip of task.proof.trips){for(const id of trip){api.collect(id);settle(api)}for(const id of trip){api.selectHeld(id);api.store(task.tools.find(tool=>tool.id===id).zone);settle(api)}}api.closeFarm();settle(api);assert.equal(api.inspect().phase,"check");assert.equal(api.check("gate"),"check");harness.runAll();assert.equal(api.inspect().result,"check");assert.match(harness.finishes[0].result.detail,/荷台/)}finally{restore()}});

test("a wrong signed road turn fails independently",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(24)),harness=createHarness();game.render(task,harness.context);const api=harness.qa[ID];for(const trip of task.proof.trips){for(const id of trip){api.collect(id);settle(api)}for(const id of trip){api.selectHeld(id);api.store(task.tools.find(tool=>tool.id===id).zone);settle(api)}}api.closeFarm();settle(api);api.check("bed");settle(api);api.check("gate");settle(api);const wrong=["left","straight","right"].find(choice=>choice!==api.inspect().expected);assert.equal(api.drive(wrong),"drive");harness.runAll();assert.equal(api.inspect().result,"drive");assert.equal(harness.finishes[0].result.reason,"drive") }finally{restore()}});

test("inefficient single-tool trips exhaust the finite sunset action budget",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:min=>min}),harness=createHarness();game.render(task,harness.context);const api=harness.qa[ID];for(const tool of task.tools){if(api.inspect().done)break;const taking=api.collect(tool.id);if(taking==="sunset")break;settle(api);api.selectHeld(tool.id);const storing=api.store(tool.zone);if(storing==="sunset")break;settle(api)}harness.runAll();assert.equal(api.inspect().result,"sunset");assert.equal(harness.finishes[0].result.reason,"sunset");assert.match(harness.finishes[0].result.detail,/日が暮れ/)}finally{restore()}});

test("real deadline paints sunset and commits once",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(31)),harness=createHarness();game.render(task,harness.context);assert.equal(harness.triggerDeadline(),true);assert.equal(harness.triggerDeadline(),false);const api=harness.qa[ID];assert.equal(api.inspect().result,"sunset");assert.equal(boardFrom(harness.host).dataset.result,"sunset");assert.deepEqual(harness.finishes.map(entry=>entry.correct),[false]);assert.equal(harness.finishes[0].result.reason,"sunset");assert.equal(harness.finishCalls,1)}finally{restore()}});

test("busy transition locks other actions and reduced stages settle readably without a frame",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(32)),harness=createHarness({reducedMotion:true}),apiTask=structuredClone(task);game.render(apiTask,harness.context);const api=harness.qa[ID];assert.equal(api.collect("hoe"),"collecting");assert.equal(api.collect("rake"),false);assert.equal(api.inspect().transition.progress,0);harness.runFor(70);assert.equal(api.inspect().transition.progress,.45);harness.runFor(70);assert.equal(api.inspect().transition.progress,.78);harness.runFor(70);assert.deepEqual(api.inspect().carried,["hoe"]);assert.equal(api.inspect().frames,0);assert.equal(harness.frameCount,0)}finally{restore()}});

test("dispose during reduced collection cancels stages, deadline, listeners, QA, and finish",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(33)),harness=createHarness({reducedMotion:true});game.render(task,harness.context);harness.qa[ID].collect("basket");assert.ok(harness.pendingCount>=3);assert.equal(harness.frameCount,0);harness.dispose();harness.runAll();harness.triggerDeadline();assert.equal(harness.pendingCount,0);assert.equal(harness.listenerCount,0);assert.equal(harness.frameCount,0);assert.equal(harness.finishes.length,0);assert.equal(harness.qa[ID],undefined)}finally{restore()}});

test("real reduced runtime advances staged touch collection and disposes cleanly",async()=>{const restore=installFakeDocument(),previousCancel=globalThis.cancelAnimationFrame;globalThis.cancelAnimationFrame=()=>{};try{const task=game.generate(randomHelpers(34)),qa={},finishes=[],host=document.createElement("div");host.getBoundingClientRect=()=>({width:393,height:852});const runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(task,runtime.context);toolButton(host,"hoe").dispatchEvent(eventWith("pointerdown",{pointerType:"touch"}));assert.ok(runtime.inspect().timeouts>=4);assert.equal(runtime.inspect().frames,0);await delay(230);assert.deepEqual(qa[ID].inspect().carried,["hoe"]);runtime.dispose();assert.equal(qa[ID],undefined);await delay(240);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{restore();if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}});

test("touch, keyboard steering, visible focus, reduced mode, and DPR backing stay usable",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:min=>min}),harness=createHarness({reducedMotion:true,viewport:{width:402,height:874,dpr:3}});game.render(task,harness.context);const api=harness.qa[ID],canvas=canvasFrom(harness.host);assert.equal(document.activeElement,canvas);toolButton(harness.host,"hoe").dispatchEvent(eventWith("pointerdown",{pointerType:"touch"}));harness.runFor(210);assert.deepEqual(api.inspect().carried,["hoe"]);for(const trip of task.proof.trips){for(const id of trip){if(api.inspect().tools[id]!=="field")continue;api.collect(id);harness.runFor(210)}for(const id of trip){if(api.inspect().tools[id]!=="held")continue;api.selectHeld(id);api.store(task.tools.find(tool=>tool.id===id).zone);harness.runFor(210)}}if(api.inspect().tools.hoe==="held"){api.selectHeld("hoe");api.store("rack");harness.runFor(210)}api.closeFarm();harness.runFor(210);api.check("bed");harness.runFor(210);api.check("gate");harness.runFor(210);for(const choice of task.roadChoices){canvas.dispatchEvent(eventWith("keydown",{key:choice==="left"?"ArrowLeft":choice==="right"?"ArrowRight":"ArrowUp"}));harness.runFor(210)}harness.runAll();assert.equal(api.inspect().result,"success");assert.equal(api.inspect().frames,0);assert.equal(harness.frameCount,0);const view=api.inspect().canvas;assert.equal(view.dpr,3);assert.equal(view.width,view.cssWidth*3);assert.equal(view.height,view.cssHeight*3);assert.equal(stageFrom(harness.host).dataset.reduced,"true")}finally{restore()}});

test("normal tracked painting sustains a 60fps-equivalent high-resolution workload",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(41)),harness=createHarness({viewport:{width:430,height:932,dpr:3}});game.render(task,harness.context);const started=performance.now();harness.stepFrames(600);const elapsed=performance.now()-started,state=harness.qa[ID].inspect();assert.equal(state.frames,600);assert.ok(elapsed<900,`600 frames took ${elapsed.toFixed(1)}ms`);assert.equal(harness.frameCount,1);harness.dispose()}finally{restore()}});

test("source is ownerDocument-only, tracked-lifetime, network/audio/emoji free",()=>{assert.match(moduleSource,/context\.host\?\.ownerDocument/);assert.doesNotMatch(moduleSource,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(moduleSource,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(moduleSource,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement)\b/);assert.doesNotMatch(moduleSource,/[\u{1F300}-\u{1FAFF}]/u)});
