import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import game from "../src/games/attention-laundry-rescue-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";
const ID="attention-laundry-rescue-v1",source=await readFile(new URL("../src/games/attention-laundry-rescue-v1.js",import.meta.url),"utf8"),generate=v=>game.generate({randomInt:()=>v});
class ClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean));this.sync()}sync(){this.owner._className=[...this.values].join(" ")}add(...items){items.forEach(item=>this.values.add(item));this.sync()}remove(...items){items.forEach(item=>this.values.delete(item));this.sync()}contains(item){return this.values.has(item)}toggle(item,force){const add=force===undefined?!this.values.has(item):force;add?this.values.add(item):this.values.delete(item);this.sync();return add}}
class Style{constructor(){this.values=new Map()}setProperty(key,value){this.values.set(key,String(value))}}
const noop=()=>{};class Gradient{addColorStop(){}}const ctx=()=>new Proxy({globalAlpha:1,createLinearGradient:()=>new Gradient(),createRadialGradient:()=>new Gradient()},{get(o,k){return k in o?o[k]:noop},set(o,k,v){o[k]=v;return true}});
class Element extends EventTarget{constructor(tag,doc){super();this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.children=[];this.parentElement=null;this.attributes=new Map();this.dataset={};this.style=new Style();this.classList=new ClassList(this);this._className="";this.textContent="";this.type="";this.disabled=false;this.tabIndex=-1;this.width=0;this.height=0;this.context=this.tagName==="CANVAS"?ctx():null}set className(v){this._className=String(v);this.classList.reset(v)}get className(){return this._className}append(...nodes){nodes.forEach(node=>{node.parentElement=this;this.children.push(node)})}replaceChildren(...nodes){this.children=[];this.append(...nodes)}setAttribute(k,v){this.attributes.set(k,String(v))}getAttribute(k){return this.attributes.get(k)??null}focus(){this.ownerDocument.activeElement=this}getContext(){return this.context}getBoundingClientRect(){const width=Number.parseFloat(this.style.values.get("width"))||393,height=Number.parseFloat(this.style.values.get("height"))||597;return{left:0,top:0,width,height,right:width,bottom:height}}}
function documentFor(dpr=3){const view=new EventTarget();view.devicePixelRatio=dpr;const doc={activeElement:null,defaultView:view};doc.createElement=tag=>new Element(tag,doc);return doc}
function event(type,properties={}){const value=new Event(type,{bubbles:true,cancelable:true});Object.entries(properties).forEach(([key,item])=>Object.defineProperty(value,key,{value:item}));return value}
function harness({reduced=true,viewport={width:393,height:852,dpr:3},owner=documentFor(viewport.dpr)}={}){const controller=new AbortController(),host=owner.createElement("div"),qa={},jobs=[],listeners=new Set(),finishes=[];let deadline=null,frame=null,time=0,disposed=false;host.getBoundingClientRect=()=>({left:0,top:0,width:viewport.width,height:viewport.height});const dispose=()=>{if(disposed)return;controller.abort();disposed=true;jobs.forEach(job=>job.active=false);if(deadline)deadline.active=false;frame=null;listeners.forEach(item=>item.target.removeEventListener(item.type,item.fn,item.options));listeners.clear()};const context={host,signal:controller.signal,reducedMotion:reduced,viewport,qa,finish(correct,result){if(disposed||finishes.length)return false;finishes.push({correct,result});return true},later(fn,ms){const job={fn,at:time+ms,active:true};jobs.push(job);return job},setDeadline(ms,fn){deadline={fn,at:time+ms,active:true};return deadline},frame(fn){frame=fn;return()=>{frame=null}},listen(target,type,fn,options){target.addEventListener(type,fn,options);const item={target,type,fn,options};listeners.add(item);return()=>{target.removeEventListener(type,fn,options);listeners.delete(item)}}};const runNext=()=>{const job=jobs.filter(item=>item.active).sort((a,b)=>a.at-b.at)[0];if(!job)return false;time=job.at;job.active=false;job.fn();return true};const runAll=()=>{while(runNext());};const step=at=>{time=at;if(frame&&frame(at)===false)frame=null};const timeout=()=>{if(deadline?.active&&!disposed){deadline.active=false;deadline.fn()}};return{context,host,owner,qa,finishes,dispose,runNext,runAll,step,timeout,get pending(){return jobs.filter(item=>item.active).length},get frame(){return Boolean(frame)},get listeners(){return listeners.size}}}
const parts=h=>{const stage=h.host.children[1];return{stage,status:stage.children[0],canvas:stage.children[1],controls:stage.children[2],progress:stage.children[3]}};
function loadAll(h,task){for(const id of task.solution){assert.equal(h.qa[ID].load(id),true);h.runAll()}}

test("metadata is the accepted original-game identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"2.0",tier:2,flavor:"wild",step:1,family:"attention-laundry-rescue",category:"attention"}));
test("1000 finite mirrored rooms clone, validate, and retain exact laundry proofs",()=>{const started=performance.now(),variants=new Set();for(let i=0;i<1000;i++){const task=generate(i%2);assert.doesNotThrow(()=>structuredClone(task));assert.deepEqual(game.validate(task),[]);assert.equal(task.objects.length,9);assert.equal(task.solution.length,5);assert.equal(task.proof.laundry,5);assert.equal(task.proof.distractors,4);assert.equal(task.proof.occlusions,3);variants.add(JSON.stringify(task.objects.map(item=>[item.x,item.rotation])))}assert.equal(variants.size,2);assert.ok(performance.now()-started<3000)});
test("proof contains every garment and excludes wife, dog, phone, and detergent",()=>{for(const variant of [0,1]){const task=generate(variant),byId=new Map(task.objects.map(item=>[item.id,item]));assert.deepEqual([...task.solution].sort(),task.objects.filter(item=>item.role==="laundry").map(item=>item.id).sort());assert.ok(task.solution.every(id=>byId.get(id).role==="laundry"));assert.ok(task.objects.filter(item=>item.role!=="laundry").every(item=>!task.solution.includes(item.id)))}});
test("validator rejects geometry, semantics, occlusion, answer, duration, and proof mutations",()=>{const task=generate(0),items=[{...task,duration:1}];const geometry=structuredClone(task);geometry.objects[0].x=-1;items.push(geometry);const role=structuredClone(task);role.objects[0].role="laundry";items.push(role);const material=structuredClone(task);delete material.objects[1].material;items.push(material);const occlusion=structuredClone(task);occlusion.occlusions.pop();items.push(occlusion);const answer=structuredClone(task);answer.solution[0]="wife";items.push(answer);const proof=structuredClone(task);proof.proof.distractors=3;items.push(proof);items.forEach((item,index)=>assert.ok(game.validate(item).length,`mutation ${index}`))});
test("plain JSON resume loads all garments and commits one success",()=>{const task=JSON.parse(JSON.stringify(generate(0))),h=harness();game.render(task,h.context);loadAll(h,task);assert.deepEqual(h.finishes.map(item=>item.correct),[true]);assert.equal(h.qa[ID].inspect().loaded.length,5);assert.match(h.finishes[0].result.detail,/5点/);h.timeout();assert.equal(h.finishes.length,1)});
test("real touch drag shows occupied hand, returns invalid drop, then loads in the deep mouth",()=>{const task=generate(0),h=harness();game.render(task,h.context);const {canvas}=parts(h),rect=canvas.getBoundingClientRect(),at=(type,x,y)=>canvas.dispatchEvent(event(type,{pointerId:7,pointerType:"touch",clientX:rect.width*x,clientY:rect.height*y}));at("pointerdown",.31,.57);assert.equal(h.qa[ID].inspect().heldId,"shirt");at("pointermove",.4,.75);at("pointerup",.4,.75);assert.equal(h.qa[ID].inspect().invalidId,"shirt");h.runAll();at("pointerdown",.31,.57);at("pointermove",.5,.255);at("pointerup",.5,.255);assert.equal(h.qa[ID].inspect().busy,true);h.runAll();assert.ok(h.qa[ID].inspect().loaded.includes("shirt"));h.dispose()});
test("wife grab is an immediate single retained failure",()=>{const h=harness();game.render(generate(0),h.context);assert.equal(h.qa[ID].grab("wife"),true);h.runAll();assert.deepEqual(h.finishes.map(item=>item.correct),[false]);assert.equal(h.qa[ID].inspect().result,"wife");assert.equal(h.qa[ID].inspect().wrongId,"wife");assert.match(h.finishes[0].result.detail,/妻/);h.timeout();assert.equal(h.finishes.length,1)});
test("dog grab is a separate unharmed terminal failure",()=>{const h=harness();game.render(generate(0),h.context);assert.equal(h.qa[ID].grab("dog"),true);h.runAll();assert.deepEqual(h.finishes.map(item=>item.correct),[false]);assert.equal(h.qa[ID].inspect().result,"dog");assert.match(h.finishes[0].result.detail,/犬/)});
test("wrong nonlaundry and timeout remain distinct",()=>{const wrong=harness();game.render(generate(0),wrong.context);wrong.qa[ID].grab("phone");wrong.runAll();assert.equal(wrong.qa[ID].inspect().result,"nonlaundry");assert.match(wrong.finishes[0].result.detail,/衣類ではありません/);const timeout=harness();game.render(generate(0),timeout.context);timeout.timeout();timeout.runAll();assert.equal(timeout.qa[ID].inspect().result,"timeout");assert.match(timeout.finishes[0].result.detail,/5点残/)});
test("keyboard cycles with visible focus, starts load, and locks repeat input",()=>{const task=generate(0),h=harness();game.render(task,h.context);const {canvas,stage}=parts(h);assert.equal(h.owner.activeElement,canvas);const before=h.qa[ID].inspect().selected;canvas.dispatchEvent(event("keydown",{key:"ArrowRight"}));assert.notEqual(h.qa[ID].inspect().selected,before);let guard=0;while(h.qa[ID].inspect().selected!=="trousers"&&guard++<12)canvas.dispatchEvent(event("keydown",{key:"ArrowRight"}));canvas.dispatchEvent(event("keydown",{key:"Enter"}));const locked=h.qa[ID].inspect();assert.equal(locked.busy,true);canvas.dispatchEvent(event("keydown",{key:"ArrowRight"}));assert.equal(h.qa[ID].inspect().selected,locked.selected);assert.equal(stage.dataset.keyboard,"true");h.dispose()});
test("normal owns a frame while reduced loading exposes two tracked stages",()=>{const normal=harness({reduced:false});game.render(generate(0),normal.context);assert.equal(normal.frame,true);normal.qa[ID].load("shirt");normal.step(0);normal.step(310);assert.equal(normal.qa[ID].inspect().busy,true);normal.step(590);assert.equal(normal.qa[ID].inspect().busy,false);normal.dispose();const reduced=harness();game.render(generate(0),reduced.context);reduced.qa[ID].load("shirt");assert.equal(reduced.pending,2);reduced.runNext();assert.equal(reduced.qa[ID].inspect().phase,"mid-load");assert.equal(reduced.qa[ID].inspect().busy,true);reduced.runNext();assert.equal(reduced.qa[ID].inspect().phase,"settled");assert.ok(reduced.qa[ID].inspect().loaded.includes("shirt"));reduced.dispose()});
test("DPR backing and ten concept visual states remain inspectable",()=>{const h=harness({viewport:{width:402,height:874,dpr:4}});game.render(generate(0),h.context);const api=h.qa[ID],canvas=api.inspect().canvas;assert.equal(canvas.dpr,3);assert.equal(canvas.pixelWidth,canvas.cssWidth*3);assert.equal(canvas.pixelHeight,canvas.cssHeight*3);for(const scene of ["initial","drag","progress","invalid","wife","dog","nonlaundry","success","timeout","reduced-stage"])assert.equal(api.showScene(scene),true);api.showScene("drag");assert.equal(api.inspect().carriedId,"shirt");assert.ok(!api.inspect().floorIds.includes("shirt"));api.showScene("reduced-stage");assert.equal(api.inspect().carriedId,"cardigan");assert.ok(!api.inspect().floorIds.includes("cardigan"));assert.equal(api.inspect().floorIds.filter(id=>id==="cardigan").length,0);h.dispose()});
test("dispose clears normal/reduced work, QA, deadline, listeners, and forbidden source paths",async()=>{const staged=harness();game.render(generate(0),staged.context);staged.qa[ID].load("shirt");assert.equal(staged.pending,2);staged.dispose();staged.runAll();staged.timeout();assert.equal(staged.qa[ID],undefined);assert.equal(staged.pending,0);assert.equal(staged.listeners,0);assert.deepEqual(staged.finishes,[]);const previousRaf=globalThis.requestAnimationFrame,previousCancel=globalThis.cancelAnimationFrame;let id=0;const frames=new Map();globalThis.requestAnimationFrame=fn=>{frames.set(++id,fn);return id};globalThis.cancelAnimationFrame=key=>frames.delete(key);try{const owner=documentFor(),host=owner.createElement("div"),qa={},finishes=[],runtime=createGameRuntime({host,qa,reducedMotion:false,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(generate(0),runtime.context);qa[ID].load("shirt");runtime.dispose();await delay(500);assert.equal(qa[ID],undefined);assert.deepEqual(finishes,[]);assert.equal(frames.size,0);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(previousRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=previousRaf;if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement)\b/)});
