#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd);OUT=${1:-/tmp/agetest-attention-lint-shaver-v1-audit};cd "$ROOT";node tools/qa-browser-lanes.mjs start audit >/dev/null;rm -rf "$OUT";mkdir -p "$OUT"
layouts=(0 1 2);metrics=(393x852 402x874);motions=(normal reduced);scenes=(initial mid-clean cup-full-warning decoration-damage hole overflow success timeout)
ready='(async()=>{for(let i=0;i<240;i++){if(window.__LINT_SHAVER_FIXTURE__&&document.documentElement.dataset.ready==="true")return true;await new Promise(r=>setTimeout(r,25))}throw Error("ready timeout")})()'
for layout in "${layouts[@]}";do for metric in "${metrics[@]}";do width=${metric%x*};height=${metric#*x};for motion in "${motions[@]}";do for scene in "${scenes[@]}";do
 node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/attention-lint-shaver-v1.fixture.html?layout=$layout&scene=$scene&motion=$motion&width=$width" "$width" "$height" 3 >/dev/null
 node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null
 node tools/qa-browser-lanes.mjs eval audit 'window.__LINT_SHAVER_FIXTURE__.report()' >"$OUT/evidence-$layout-$metric-$scene-$motion.json"
 node tools/qa-browser-lanes.mjs screenshot audit "$OUT/layout$layout-$metric-$scene-$motion.png" >/dev/null
done;done;done;done
for layout in "${layouts[@]}";do for metric in "${metrics[@]}";do width=${metric%x*};height=${metric#*x};node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/attention-lint-shaver-v1.fixture.html?layout=$layout&scene=initial&motion=normal&width=$width" "$width" "$height" 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null;node tools/qa-browser-lanes.mjs eval audit '(async()=>{const f=window.__LINT_SHAVER_FIXTURE__,d=[];let p=performance.now();await new Promise(resolve=>{const tick=n=>{d.push(n-p);p=n;if(d.length===90)resolve();else requestAnimationFrame(tick)};requestAnimationFrame(tick)});const r=f.report();return{status:d.length===90&&r.runtime.frames===0&&!r.external.length&&!r.errors.length&&r.viewport.bodyScrollWidth<=r.width?"pass":"fail",layout:f.layout,frames:d.length,averageFrameMs:d.reduce((a,b)=>a+b,0)/d.length,maxFrameMs:Math.max(...d),gameOwnedFrames:r.runtime.frames,overflow:r.viewport.bodyScrollWidth>r.width,external:r.external,errors:r.errors,viewport:r.viewport,canvas:r.state.canvas}})()' >"$OUT/performance-initial-$layout-$metric.json";done;done
for metric in 390x844 430x932;do width=${metric%x*};height=${metric#*x};for layout in "${layouts[@]}";do for motion in "${motions[@]}";do for scene in initial success;do node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/attention-lint-shaver-v1.fixture.html?layout=$layout&scene=$scene&motion=$motion&width=$width" "$width" "$height" 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null;node tools/qa-browser-lanes.mjs eval audit 'window.__LINT_SHAVER_FIXTURE__.report()' >"$OUT/supplemental-$layout-$metric-$scene-$motion.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/supplemental-$layout-$metric-$scene-$motion.png" >/dev/null;done;done;done;done
for layout in "${layouts[@]}";do for motion in "${motions[@]}";do
 node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/attention-lint-shaver-v1.fixture.html?layout=$layout&scene=initial&motion=$motion&width=402&live=1" 402 874 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null
 node tools/qa-browser-lanes.mjs eval audit '(async()=>{const f=window.__LINT_SHAVER_FIXTURE__,c=document.querySelector("canvas"),r=c.getBoundingClientRect(),wait=ms=>new Promise(q=>setTimeout(q,ms)),at=p=>({x:r.left+(.06+(p.x+.5)*.88/12)*r.width,y:r.top+(.12+(p.y+.5)*.81/14)*r.height}),fire=(type,p,id)=>{const q=at(p);c.dispatchEvent(new PointerEvent(type,{bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",isPrimary:true,clientX:q.x,clientY:q.y}))},stroke=async(path,id)=>{fire("pointerdown",path[0],id);for(const p of path.slice(1)){await wait(110);fire("pointermove",p,id)}fire("pointerup",path.at(-1),id);await wait(f.motion==="reduced"?130:20)};let id=30;for(const path of f.task.safeStrokes)await stroke(path,id++);const warning=f.api.inspect();const empty=[...document.querySelectorAll("button")][0];empty.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:80,pointerType:"touch"}));await wait(300);const emptied=f.api.inspect();for(const path of f.task.safeStrokes)await stroke(path,id++);const finish=[...document.querySelectorAll("button")][1];finish.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:81,pointerType:"touch"}));const locked=f.api.inspect();await wait(560);const report=f.report();return{layout:f.layout,motion:f.motion,warning,emptied,locked,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,targets:report.targets,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()' >"$OUT/touch-success-$layout-$motion.json"
 node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/attention-lint-shaver-v1.fixture.html?layout=$layout&scene=initial&motion=$motion&width=402&live=1" 402 874 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null
 node tools/qa-browser-lanes.mjs eval audit '(async()=>{const f=window.__LINT_SHAVER_FIXTURE__,c=document.querySelector("canvas"),r=c.getBoundingClientRect(),wait=ms=>new Promise(q=>setTimeout(q,ms)),part=f.task.protected[0],path=[{x:part.x?part.x-1:part.x+1,y:part.y},{x:part.x,y:part.y}],at=p=>({x:r.left+(.06+(p.x+.5)*.88/12)*r.width,y:r.top+(.12+(p.y+.5)*.81/14)*r.height}),fire=(type,p)=>{const q=at(p);c.dispatchEvent(new PointerEvent(type,{bubbles:true,cancelable:true,pointerId:92,pointerType:"touch",isPrimary:true,clientX:q.x,clientY:q.y}))};fire("pointerdown",path[0]);await wait(110);fire("pointermove",path[1]);fire("pointerup",path[1]);const locked=f.api.inspect();await wait(560);const report=f.report();return{layout:f.layout,motion:f.motion,part,locked,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,targets:report.targets,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()' >"$OUT/touch-damage-$layout-$motion.json"
done;done
for motion in "${motions[@]}";do
 node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/attention-lint-shaver-v1.fixture.html?layout=0&scene=initial&motion=$motion&width=402&live=1" 402 874 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null
 node tools/qa-browser-lanes.mjs eval audit '(async()=>{const f=window.__LINT_SHAVER_FIXTURE__,c=document.querySelector("canvas"),wait=ms=>new Promise(q=>setTimeout(q,ms)),keys=[],key=k=>{c.dispatchEvent(new KeyboardEvent("keydown",{key:k,bubbles:true,cancelable:true}));keys.push(k)},repeat=(k,n)=>{for(let i=0;i<n;i++)key(k)};c.focus();key(" ");repeat("ArrowRight",6);key(" ");repeat("ArrowLeft",4);repeat("ArrowDown",6);key(" ");repeat("ArrowRight",6);key(" ");const warning=f.api.inspect();key("e");await wait(300);const emptied=f.api.inspect();repeat("ArrowLeft",8);repeat("ArrowUp",6);key(" ");repeat("ArrowRight",6);key(" ");repeat("ArrowLeft",4);repeat("ArrowDown",6);key(" ");repeat("ArrowRight",6);key(" ");key("Enter");const locked=f.api.inspect();await wait(560);const report=f.report();return{motion:f.motion,keys,warning,emptied,locked,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,focused:c===document.activeElement,targets:report.targets,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()' >"$OUT/keyboard-$motion.json"
 node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/attention-lint-shaver-v1.fixture.html?layout=0&scene=initial&motion=$motion&width=402&live=1" 402 874 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null
 node tools/qa-browser-lanes.mjs eval audit '(async()=>{const f=window.__LINT_SHAVER_FIXTURE__;f.api.applyStroke(f.task.proof.canonical.plans[0].samples);const before=f.api.snapshot();f.runtime.context.setDeadline(180,f.api.expire);await new Promise(r=>setTimeout(r,760));const report=f.report();return{motion:f.motion,before,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()' >"$OUT/deadline-$motion.json"
 node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/attention-lint-shaver-v1.fixture.html?layout=0&scene=initial&motion=$motion&width=402&live=1" 402 874 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null
 node tools/qa-browser-lanes.mjs eval audit '(async()=>{const f=window.__LINT_SHAVER_FIXTURE__,c=document.querySelector("canvas"),r=c.getBoundingClientRect(),p=f.task.safeStrokes[0],at=q=>({x:r.left+(.06+(q.x+.5)*.88/12)*r.width,y:r.top+(.12+(q.y+.5)*.81/14)*r.height}),fire=(type,q)=>{const v=at(q);c.dispatchEvent(new PointerEvent(type,{bubbles:true,cancelable:true,pointerId:73,pointerType:"touch",clientX:v.x,clientY:v.y}))},wait=ms=>new Promise(q=>setTimeout(q,ms));fire("pointerdown",p[0]);await wait(110);fire("pointermove",p[1]);const state=f.api.inspect(),before=f.runtime.inspect();f.runtime.dispose();await wait(260);return{motion:f.motion,state,before,after:f.runtime.inspect(),qaPresent:Boolean(f.qa[f.game.metadata.id]),finishes:f.report().finishes}})()' >"$OUT/dispose-$motion.json"
 node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/attention-lint-shaver-v1.fixture.html?layout=0&scene=initial&motion=$motion&width=402&live=1" 402 874 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null
 node tools/qa-browser-lanes.mjs eval audit '(async()=>{const f=window.__LINT_SHAVER_FIXTURE__,c=document.querySelector("canvas"),r=c.getBoundingClientRect(),p=f.task.safeStrokes[0][0],x=r.left+(.06+(p.x+.5)*.88/12)*r.width,y=r.top+(.12+(p.y+.5)*.81/14)*r.height;c.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:64,pointerType:"touch",clientX:x,clientY:y}));const d=[];let previous=performance.now();await new Promise(resolve=>{const tick=now=>{d.push(now-previous);previous=now;if(d.length===90)resolve();else requestAnimationFrame(tick)};requestAnimationFrame(tick)});const state=f.api.inspect(),runtime=f.runtime.inspect(),report=f.report(),result={status:d.length===90&&runtime.frames===(f.motion==="normal"?1:0)&&!report.external.length&&!report.errors.length&&report.viewport.bodyScrollWidth<=report.width?"pass":"fail",motion:f.motion,frames:d.length,averageFrameMs:d.reduce((a,b)=>a+b,0)/d.length,maxFrameMs:Math.max(...d),gameOwnedFrames:runtime.frames,state,runtime,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors};f.runtime.dispose();return result})()' >"$OUT/performance-drag-$motion.json"
done
OUT="$OUT" python - <<'PY'
from pathlib import Path
from PIL import Image,ImageChops,ImageStat
import json,math,os
root=Path(os.environ['OUT']);layouts=[0,1,2];metrics=['393x852','402x874'];motions=['normal','reduced'];scenes=['initial','mid-clean','cup-full-warning','decoration-damage','hole','overflow','success','timeout'];rows=[]
for l in layouts:
 for m in metrics:
  for s in scenes:
   a=Image.open(root/f'layout{l}-{m}-{s}-normal.png').convert('RGB');b=Image.open(root/f'layout{l}-{m}-{s}-reduced.png').convert('RGB');d=ImageChops.difference(a,b);stat=ImageStat.Stat(d);rows.append({'key':f'{l}-{m}-{s}','size':[a.width,a.height],'mae':round(sum(stat.mean)/3,3),'rmse':round(math.sqrt(sum(v*v for v in stat.rms)/3),3),'normalizedRMSE':round(math.sqrt(sum(v*v for v in stat.rms)/3)/255,6),'changed':round(sum(px!=(0,0,0) for px in d.getdata())/(a.width*a.height),4)})
report={'canonicalViewports':[{'width':393,'height':852,'dpr':3},{'width':402,'height':874,'dpr':3}],'layouts':layouts,'states':scenes,'comparisons':len(rows),'screenshots':len(rows)*2,'allDpr3':True,'allFullResolution':all(row['size'] in ([1179,2556],[1206,2622]) for row in rows),'maxMAE':max(row['mae'] for row in rows),'meanMAE':round(sum(row['mae'] for row in rows)/len(rows),3),'maxNormalizedRMSE':max(row['normalizedRMSE'] for row in rows),'meanChanged':round(sum(row['changed'] for row in rows)/len(rows),4),'rows':rows};(root/'comparison-report.json').write_text(json.dumps(report,indent=2));print(json.dumps({k:v for k,v in report.items() if k!='rows'},indent=2))
PY
