import game from "../src/games/calculation-rpg-battle-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";
const task={kind:"rpgBattle",prompt:"まものを ぜんめつさせよ",help:"コマンドをえらんで たたかいます。「にげる」は その場で不正解です。",enemies:[{species:"blob",name:"ぬまスライム",maxHp:17,atk:3,weak:"fire",hue:140,acts:["attack","guard","attack","call"]},{species:"skeleton",name:"ほねのけんし",maxHp:20,atk:5,weak:"ice",hue:45,acts:["attack","charge","attack","guard"]},{species:"mage",name:"くろローブ",maxHp:15,atk:3,weak:"wind",hue:280,acts:["spell","heal","sleep","attack"]}],heroHp:60,heroMp:12,allies:[{name:"ムームー",icon:"🐮",text:"たいあたり",kind:"strike",power:[9,13]},{name:"メガネ",icon:"🤓",text:"じゃくてん解析",kind:"scan"}],items:{herb:2,water:1,wand:1},duration:90000};
const params=new URLSearchParams(location.search),scene=params.get("scene")||"initial",reduced=params.get("motion")==="reduced",width=Number(params.get("width"))||393;document.body.style.width=`${width}px`;
const host=document.querySelector("#challenge"),result=document.querySelector("#result"),qa={},resourcesBefore=performance.getEntriesByType("resource").length,started=performance.now();let outcome=null;
const runtime=createGameRuntime({host,qa,reducedMotion:reduced,viewport:{width,height:innerHeight,dpr:devicePixelRatio},onFinish:(correct,detail)=>{outcome={correct,detail};result.hidden=false;result.textContent=`${correct?"成功":"失敗"} — ${detail.detail}`}});
game.render(structuredClone(task),runtime.context);qa[game.metadata.id].showScene(scene);
const report=()=>{const api=qa[game.metadata.id],resources=performance.getEntriesByType("resource"),external=resources.filter(entry=>new URL(entry.name).origin!==location.origin);return{status:external.length||document.body.scrollWidth>width?"fail":"pass",scene,reduced,width,elapsedMs:performance.now()-started,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio,bodyScrollWidth:document.body.scrollWidth},game:api?.inspect()||null,runtime:runtime.inspect(),outcome,resourcesAdded:resources.length-resourcesBefore,external:external.map(entry=>entry.name)}};
window.__RPG_FIXTURE__={game,task,qa,runtime,report};document.documentElement.dataset.ready="true";
