import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import game from "../src/games/calculation-rpg-battle-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";

const ID="calculation-rpg-battle-v1";
const source=await readFile(new URL("../src/games/calculation-rpg-battle-v1.js",import.meta.url),"utf8");
const PUBLISHED_TASK={kind:"rpgBattle",prompt:"まものを ぜんめつさせよ",help:"コマンドをえらんで たたかいます。「にげる」は その場で不正解です。",enemies:[
  {species:"blob",name:"ぬまスライム",maxHp:17,atk:3,weak:"fire",hue:140,acts:["attack","guard","attack","call"]},
  {species:"skeleton",name:"ほねのけんし",maxHp:20,atk:5,weak:"ice",hue:45,acts:["attack","charge","attack","guard"]},
  {species:"mage",name:"くろローブ",maxHp:15,atk:3,weak:"wind",hue:280,acts:["spell","heal","sleep","attack"]}
],heroHp:60,heroMp:12,allies:[{name:"ムームー",icon:"🐮",text:"たいあたり",kind:"strike",power:[9,13]},{name:"メガネ",icon:"🤓",text:"じゃくてん解析",kind:"scan"}],items:{herb:2,water:1,wand:1},duration:90000};

function randomHelpers(initialSeed=0x1badd00d){let seed=initialSeed>>>0;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/0x100000000),randomInt=(min,max)=>min+Math.floor(random()*(max-min+1)),pick=values=>values[randomInt(0,values.length-1)],shuffle=values=>{const copy=[...values];for(let i=copy.length-1;i>0;i--){const j=randomInt(0,i);[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};return{random,randomInt,pick,shuffle}}
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}sync(){this.owner._className=[...this.values].join(" ")}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}toggle(value,force){const next=force===undefined?!this.values.has(value):Boolean(force);next?this.values.add(value):this.values.delete(value);this.sync();return next}}
class FakeStyle{constructor(){this.values=new Map()}setProperty(name,value){this.values.set(name,String(value))}}
class FakeContext{constructor(){this.transforms=[];this.fillRects=0}setTransform(...value){this.transforms.push(value)}clearRect(){}fillRect(){this.fillRects++}}
class FakeText{constructor(value,ownerDocument){this.textContent=String(value);this.ownerDocument=ownerDocument;this.children=[]}}
class FakeElement extends EventTarget{
  constructor(tagName,ownerDocument){super();this.tagName=tagName.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.attributes=new Map();this.dataset={};this.style=new FakeStyle();this.classList=new FakeClassList(this);this._className="";this._textContent="";this.type="";this.disabled=false;this.hidden=false;this.tabIndex=-1;this.width=0;this.height=0;this.context=this.tagName==="CANVAS"?new FakeContext():null}
  set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}
  set textContent(value){this._textContent=String(value);this.children=[]}get textContent(){return this._textContent+this.children.map(child=>child.textContent||"").join("")}
  append(...nodes){nodes.forEach(node=>this.children.push(typeof node==="string"?new FakeText(node,this.ownerDocument):node))}replaceChildren(...nodes){this.children=[];this._textContent="";this.append(...nodes)}
  setAttribute(name,value){this.attributes.set(name,String(value))}getAttribute(name){return this.attributes.get(name)??null}
  focus(){this.ownerDocument.activeElement=this}get offsetWidth(){return 390}
  remove(){for(const node of this.ownerDocument.nodes||[]){const index=node.children.indexOf(this);if(index>=0)node.children.splice(index,1)}}
  getContext(type){return type==="2d"?this.context:null}
}
class FakePointerEvent extends Event{constructor(type,options={}){super(type,options);this.pointerType=options.pointerType||""}}
function createDocument(dpr=3){const view=new EventTarget();view.devicePixelRatio=dpr;view.PointerEvent=FakePointerEvent;view.Event=Event;const documentRef={activeElement:null,defaultView:view,createElement:null,nodes:[]};documentRef.createElement=tag=>{const node=new FakeElement(tag,documentRef);documentRef.nodes.push(node);return node};return documentRef}
function eventWith(type,properties={}){const event=new Event(type,{bubbles:true,cancelable:true});Object.entries(properties).forEach(([key,value])=>Object.defineProperty(event,key,{value}));return event}
function createHarness({reducedMotion=false,viewport={width:393,height:852,dpr:3},ownerDocument=createDocument(viewport.dpr)}={}){
  const controller=new AbortController(),host=ownerDocument.createElement("div"),qa={},jobs=[],listeners=new Set(),finishes=[];let deadline=null,now=0,disposed=false;
  const context={host,signal:controller.signal,reducedMotion,viewport,qa,profile:{name:"テスト勇者"},finish(correct,result){if(disposed||finishes.length)return false;finishes.push({correct:Boolean(correct),result});return true},setDeadline(ms,fn){deadline={at:now+ms,fn,active:true};return deadline},later(fn,ms){const job={at:now+Math.max(0,ms),fn,active:true};jobs.push(job);return job},frame(){throw new Error("battle must not request a frame loop")},listen(target,type,fn,options){target.addEventListener(type,fn,options);const record={target,type,fn,options};listeners.add(record);return()=>{target.removeEventListener(type,fn,options);listeners.delete(record)}}};
  const runFor=ms=>{const target=now+ms;let guard=0;while(guard++<500){const job=jobs.filter(item=>item.active&&item.at<=target).sort((a,b)=>a.at-b.at)[0];if(!job)break;now=job.at;job.active=false;job.fn()}if(guard>=500)throw new Error("scheduled battle work did not settle");now=target};
  const runAll=()=>{let guard=0;while(guard++<500){const job=jobs.filter(item=>item.active).sort((a,b)=>a.at-b.at)[0];if(!job)break;now=job.at;job.active=false;job.fn()}if(guard>=500)throw new Error("scheduled battle work did not settle")};
  const triggerDeadline=()=>{if(!deadline?.active)return false;deadline.active=false;deadline.fn();return true};
  const dispose=()=>{if(disposed)return;disposed=true;jobs.forEach(job=>job.active=false);if(deadline)deadline.active=false;controller.abort();listeners.forEach(({target,type,fn,options})=>target.removeEventListener(type,fn,options));listeners.clear()};
  return{context,host,qa,finishes,runFor,runAll,triggerDeadline,dispose,ownerDocument,get pendingCount(){return jobs.filter(job=>job.active).length},get listenerCount(){return listeners.size}};
}
const stageOf=harness=>harness.host.children[1];
const fieldOf=harness=>stageOf(harness).children[0];
const logOf=harness=>stageOf(harness).children[4];
const menuOf=harness=>stageOf(harness).children[5];

test("metadata keeps the published stable identity",()=>{assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.1",tier:2,flavor:"wild",step:1,family:"calculation-rpg-battle",category:"calculation"});assert.equal(typeof game.generate,"function");assert.equal(typeof game.validate,"function");assert.equal(typeof game.render,"function")});

test("10,000 generations are cloneable, bounded, diverse, valid, and weakness-spell solvable",()=>{const helpers=randomHelpers(),sizes=new Set(),species=new Set(),allies=new Set(),started=performance.now();for(let index=0;index<10000;index++){const task=game.generate(helpers);assert.deepEqual(game.validate(task),[],`generation ${index}`);assert.doesNotThrow(()=>structuredClone(task));sizes.add(task.enemies.length);task.enemies.forEach(enemy=>species.add(enemy.species));task.allies.forEach(ally=>allies.add(ally.name));assert.ok(task.enemies.reduce((sum,enemy)=>sum+Math.ceil(enemy.maxHp/20),0)<=4)}assert.deepEqual([...sizes].sort(),[2,3]);assert.equal(species.size,5);assert.equal(allies.size,8);assert.ok(performance.now()-started<3000)});

test("generation rejects missing or hostile injected helpers",()=>{assert.throws(()=>game.generate({}),/required/);assert.throws(()=>game.generate({randomInt:min=>min,pick:()=>null,shuffle:values=>[...values]}),/pick/);assert.throws(()=>game.generate({randomInt:min=>min,pick:values=>values[0],shuffle:()=>[]}),/shuffle/)});

test("validator accepts the exact published plain save and rejects semantic mutations",()=>{assert.deepEqual(game.validate(structuredClone(PUBLISHED_TASK)),[]);const mutations=[{...PUBLISHED_TASK,kind:"choice"},{...PUBLISHED_TASK,prompt:"changed"},{...PUBLISHED_TASK,heroHp:59},{...PUBLISHED_TASK,heroMp:9},{...PUBLISHED_TASK,duration:1},{...PUBLISHED_TASK,enemies:PUBLISHED_TASK.enemies.slice(0,1)},{...PUBLISHED_TASK,items:{herb:3,water:1,wand:1}},{...PUBLISHED_TASK,allies:[PUBLISHED_TASK.allies[0],PUBLISHED_TASK.allies[0]]}];mutations.forEach((task,index)=>assert.ok(game.validate(task).length>0,`mutation ${index}`))});

test("published save resumes without mutation and calculation causes attack, enemy HP loss, retaliation, and hero HP loss",()=>{const task=structuredClone(PUBLISHED_TASK),before=structuredClone(task),harness=createHarness({reducedMotion:true});game.render(task,harness.context);const api=harness.qa[ID],initial=api.inspect();assert.equal(api.choose(0),true);assert.equal(api.inspect().phase,"target");assert.equal(api.target(0),true);const attacked=api.inspect();assert.equal(initial.enemies[0].hp-attacked.enemies[0].hp,8);assert.equal(attacked.attacks,1);assert.equal(attacked.lastDamage,8);harness.runFor(1100);const retaliated=api.inspect();assert.ok(retaliated.hero.hp<initial.hero.hp);assert.ok(retaliated.hitsTaken>=1);assert.deepEqual(task,before);harness.dispose()});

test("the saved weakness plan performs three calculated spells, empties HP bars, and wins",()=>{const harness=createHarness({reducedMotion:true});game.render(structuredClone(PUBLISHED_TASK),harness.context);const api=harness.qa[ID],cast=(elementIndex,targetIndex=0)=>{assert.equal(api.choose(1),true);assert.equal(api.choose(elementIndex),true);assert.equal(api.target(targetIndex),true)};cast(0);harness.runFor(1900);assert.equal(api.inspect().enemies[0].alive,false);cast(1);assert.equal(api.inspect().enemies[1].alive,false,JSON.stringify(api.inspect()));harness.runFor(1200);cast(2);harness.runAll();assert.ok(api.inspect().enemies.every(enemy=>!enemy.alive));assert.equal(api.inspect().attacks,3);assert.equal(api.inspect().result,"success");assert.deepEqual(harness.finishes.map(entry=>entry.correct),[true])});

test("published sweep ally damages every living enemy, defeats low-HP targets, and updates the retained field",()=>{const task=structuredClone(PUBLISHED_TASK),yen={name:"日本円",icon:"💴",text:"こばん投げ",kind:"sweep",power:[5,8]};task.allies=[yen,task.allies[1]];const before=structuredClone(task),harness=createHarness({reducedMotion:true});game.render(task,harness.context);const api=harness.qa[ID];assert.equal(api.choose(3),true);assert.equal(api.choose(2),true);assert.deepEqual(api.inspect().enemies.map(enemy=>enemy.hp),[6,9,4]);harness.runFor(1200);assert.equal(api.choose(4),true);assert.equal(api.choose(0),true);const swept=api.inspect();assert.equal(swept.phase,"action");assert.deepEqual(swept.enemies.map(enemy=>enemy.hp),[0,3,0]);assert.deepEqual(swept.enemies.map(enemy=>enemy.alive),[false,true,false]);assert.equal(swept.attacks,6);assert.deepEqual(logOf(harness).children.map(line=>line.textContent),["ぬまスライムに 7の ダメージ！","ほねのけんしに 6の ダメージ！","くろローブに 5の ダメージ！"]);assert.equal(fieldOf(harness).children[0].classList.contains("dying"),true);assert.equal(fieldOf(harness).children[2].classList.contains("dying"),true);assert.deepEqual(task,before);harness.dispose()});

test("published call summons bounded same-species enemies with field and turn participation without mutating the save",()=>{const task=structuredClone(PUBLISHED_TASK);task.enemies=[{...task.enemies[0],acts:["attack","call","attack","guard"]},{species:"bat",name:"よなきコウモリ",maxHp:19,atk:4,weak:"ice",hue:280,acts:["attack","attack","call","flee"]}];const before=structuredClone(task),harness=createHarness({reducedMotion:true});assert.deepEqual(game.validate(task),[]);game.render(task,harness.context);const api=harness.qa[ID];assert.equal(api.choose(0),true);assert.equal(api.target(0),true);harness.runFor(500);let called=api.inspect();assert.equal(called.enemies.length,4);assert.equal(called.summons,2);assert.ok(called.enemies.slice(2).every(enemy=>enemy.summoned&&enemy.called));assert.deepEqual(called.enemies.slice(2).map(enemy=>enemy.species).sort(),["bat","blob"]);assert.equal(fieldOf(harness).children.length,4);assert.ok(fieldOf(harness).children[2].children[2].children.length===1);assert.deepEqual(logOf(harness).children.map(line=>line.textContent).map(text=>/なかまを よんだ|あらわれた/.test(text)),[true,true]);harness.runFor(500);assert.equal(api.choose(0),true);assert.equal(api.target(0),true);harness.runFor(1000);called=api.inspect();assert.equal(called.enemies.length,4);assert.ok(called.enemies.filter(enemy=>enemy.summoned).every(enemy=>enemy.actionsTaken>=1));assert.deepEqual(task,before);harness.dispose()});

test("correct victory paints the retained win frame and finishes exactly once",()=>{const harness=createHarness({reducedMotion:true});game.render(structuredClone(PUBLISHED_TASK),harness.context);const api=harness.qa[ID];assert.equal(api.winNow(),true);assert.equal(api.winNow(),false);assert.equal(api.inspect().result,"success");assert.equal(stageOf(harness).children[2].textContent,"勝利！");harness.runAll();harness.triggerDeadline();harness.runAll();assert.equal(harness.finishes.length,1);assert.equal(harness.finishes[0].correct,true);assert.equal(harness.finishes[0].result.reason,"victory")});

test("run-away is an immediate wrong answer with a single finish",()=>{const harness=createHarness({reducedMotion:true});game.render(structuredClone(PUBLISHED_TASK),harness.context);assert.equal(harness.qa[ID].choose(5),true);harness.runAll();harness.triggerDeadline();harness.runAll();assert.deepEqual(harness.finishes.map(entry=>entry.correct),[false]);assert.equal(harness.finishes[0].result.reason,"flee");assert.match(harness.finishes[0].result.detail,/背中/)});

test("deadline timeout retains the battle and commits incorrect once",()=>{const harness=createHarness({reducedMotion:true});game.render(structuredClone(PUBLISHED_TASK),harness.context);assert.equal(harness.triggerDeadline(),true);assert.equal(harness.qa[ID].inspect().result,"timeout");harness.runAll();assert.deepEqual(harness.finishes.map(entry=>entry.correct),[false]);assert.equal(harness.finishes[0].result.reason,"timeout");assert.equal(harness.triggerDeadline(),false)});

test("QA published logs plus wrong-hit, progress, success, and failure scenes retain visible causality",()=>{const harness=createHarness({reducedMotion:true});game.render(structuredClone(PUBLISHED_TASK),harness.context);const api=harness.qa[ID];assert.equal(api.showScene("initial"),true);assert.deepEqual(logOf(harness).children.map(line=>line.textContent),["まものが あらわれた！"]);assert.equal(api.showScene("wrong-hit"),true);assert.equal(api.inspect().hero.hp,57);assert.equal(api.showScene("progress"),true);assert.deepEqual(logOf(harness).children.map(line=>line.textContent),["ぬまスライムを たおした！","たたかいは まだ つづいている。"]);assert.equal(api.inspect().enemies[0].alive,false);assert.equal(fieldOf(harness).children[1].children[1].textContent,"ほねのけんし\n弱点 氷");assert.ok(api.inspect().enemies.slice(1).every(enemy=>enemy.hp<enemy.maxHp));assert.equal(api.showScene("success"),true);assert.equal(api.inspect().result,"success");assert.equal(api.showScene("failure"),true);assert.equal(api.inspect().hero.hp,0);assert.equal(api.inspect().result,"defeat");harness.dispose()});

test("touch command, keyboard focus shortcuts, target focus, reduced motion, and DPR3 sprites remain usable",()=>{const harness=createHarness({reducedMotion:true,viewport:{width:402,height:874,dpr:3}});game.render(structuredClone(PUBLISHED_TASK),harness.context);const stage=stageOf(harness),api=harness.qa[ID];stage.dispatchEvent(eventWith("keydown",{key:"1"}));assert.equal(harness.ownerDocument.activeElement,menuOf(harness).children[0]);menuOf(harness).children[0].dispatchEvent(new FakePointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerType:"touch"}));assert.equal(api.inspect().phase,"target");assert.match(api.inspect().focused,/ぬまスライム/);assert.deepEqual(api.inspect().spritePixels,{width:72,height:72});assert.equal(stage.dataset.reduced,"true");harness.dispose()});

test("dispose cancels pending idle/action work, deadline, listeners, QA, and finish",()=>{const harness=createHarness();game.render(structuredClone(PUBLISHED_TASK),harness.context);assert.ok(harness.pendingCount>0);assert.ok(harness.listenerCount>0);harness.qa[ID].choose(0);harness.qa[ID].target(0);harness.dispose();harness.runAll();harness.triggerDeadline();assert.equal(harness.qa[ID],undefined);assert.equal(harness.pendingCount,0);assert.equal(harness.listenerCount,0);assert.deepEqual(harness.finishes,[])});

test("real kernel disposal leaves no battle timers or listeners",async()=>{const previousCancel=globalThis.cancelAnimationFrame;globalThis.cancelAnimationFrame=()=>{};try{const ownerDocument=createDocument(),host=ownerDocument.createElement("div"),qa={},finishes=[],runtime=createGameRuntime({host,qa,reducedMotion:false,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(structuredClone(PUBLISHED_TASK),runtime.context);assert.ok(runtime.inspect().timeouts>=4);runtime.dispose();await delay(10);assert.equal(qa[ID],undefined);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}});

test("render owns DOM, avoids frame churn, and 200 cold renders stay bounded",()=>{const foreign=createDocument(),previous=globalThis.document;globalThis.document={createElement(){throw new Error("global document must not be used")}};try{const started=performance.now();for(let index=0;index<200;index++){const harness=createHarness({ownerDocument:foreign});game.render(structuredClone(PUBLISHED_TASK),harness.context);const visit=node=>{assert.equal(node.ownerDocument,foreign);node.children.forEach(visit)};visit(harness.host);harness.dispose()}assert.ok(performance.now()-started<1500)}finally{if(previous===undefined)delete globalThis.document;else globalThis.document=previous}});

test("source uses tracked lifetime APIs with no network, audio, globals, or direct timers",()=>{assert.match(source,/context\.host\?\.ownerDocument/);assert.match(source,/context\.listen/);assert.match(source,/context\.later/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|Audio|AudioContext|speechSynthesis)\b/)});
