import test from"node:test";import assert from"node:assert/strict";import{readFile}from"node:fs/promises";import{setTimeout as delay}from"node:timers/promises";import{performance}from"node:perf_hooks";import{createGameRuntime}from"../src/game-kernel.js";
const url=new URL("../src/games/calculation-flower-share-v1.js",import.meta.url),source=await readFile(url,"utf8"),loaded=await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`),game=loaded.default,analyzeFlowers=loaded.analyzeFlowers,ID="calculation-flower-share-v1",IDS=["s1","s2","s3","s4","s5","s6","d1","d2","d3"],gen=(i=0)=>game.generate({pick:r=>r[i]});
class CL{constructor(o){this.o=o;this.s=new Set}reset(v){this.s=new Set(String(v||"").split(/\s+/).filter(Boolean))}sync(){this.o._c=[...this.s].join(" ")}add(...v){v.forEach(x=>this.s.add(x));this.sync()}remove(...v){v.forEach(x=>this.s.delete(x));this.sync()}contains(v){return this.s.has(v)}toggle(v,f){const n=f===undefined?!this.s.has(v):!!f;n?this.s.add(v):this.s.delete(v);this.sync();return n}}
class Style{setProperty(k,v){this[k]=String(v)}}class E extends EventTarget{constructor(tag,d){super();this.ownerDocument=d;this.children=[];this.parentNode=null;this.attributes=new Map;this.dataset={};this.style=new Style;this.classList=new CL(this);this._c="";this._t="";this.disabled=false;this.tabIndex=-1}set className(v){this._c=String(v);this.classList.reset(v)}get className(){return this._c}set textContent(v){this._t=String(v);this.children=[]}get textContent(){return this._t+this.children.map(x=>x.textContent).join("")}append(...ns){for(const n of ns){if(n?.parentNode){const i=n.parentNode.children.indexOf(n);if(i>=0)n.parentNode.children.splice(i,1)}if(n)n.parentNode=this;this.children.push(n)}}replaceChildren(...n){this.children=[];this._t="";this.append(...n)}setAttribute(k,v){this.attributes.set(k,String(v))}getAttribute(k){return this.attributes.get(k)??null}focus(){this.ownerDocument.activeElement=this}getBoundingClientRect(){const vase=this.classList.contains("cfs-vase-card"),flower=this.classList.contains("cfs-flower"),width=vase?110:flower?70:this.ownerDocument.width,height=vase?300:flower?60:650;return{left:0,top:0,width,height,right:width,bottom:height}}}
const fakeDoc=()=>{const d={activeElement:null,width:393,defaultView:new EventTarget};d.createElement=t=>new E(t,d);return d};
function harness({task=gen(),reduced=false,width=393}={}){const d=fakeDoc(),host=d.createElement("div"),qa={},controller=new AbortController,jobs=[],listeners=new Set,frames=new Set,finishes=[];let clock=0,order=0,disposed=false,calls=0;d.width=width;const c={host,qa,signal:controller.signal,reducedMotion:reduced,viewport:{width,height:852,dpr:3},later(fn,ms){const j={fn,at:clock+ms,order:order++,active:true};jobs.push(j);return j},setDeadline(ms,fn){return c.later(fn,ms)},frame(fn){frames.add(fn)},listen(t,type,fn,opt){t.addEventListener(type,fn,opt);listeners.add({t,type,fn,opt})},finish(correct,payload){calls++;if(disposed||finishes.length)return false;finishes.push({correct,payload:structuredClone(payload)});return true}};game.render(task,c);const runTo=end=>{let guard=0;while(guard++<500){const j=jobs.filter(x=>x.active).sort((a,b)=>a.at-b.at||a.order-b.order)[0];if(!j||j.at>end||disposed)break;clock=j.at;j.active=false;j.fn()}clock=end},runFor=ms=>runTo(clock+ms),dispose=()=>{disposed=true;jobs.forEach(j=>j.active=false);frames.clear();controller.abort();for(const r of listeners)r.t.removeEventListener(r.type,r.fn,r.opt);listeners.clear()};return{d,qa,finishes,runTo,runFor,dispose,get pending(){return jobs.filter(j=>j.active).length},get listeners(){return listeners.size},get frames(){return frames.size},get calls(){return calls}}}const api=h=>h.qa[ID],ev=(type,p={})=>{const e=new Event(type,{bubbles:true,cancelable:true});for(const[k,v]of Object.entries(p))Object.defineProperty(e,k,{value:v});return e};

test("metadata is assigned tier two",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"2.0",tier:2,flavor:"satisfying",step:1,family:"calculation-flower-share",category:"calculation"}));
test("three authored variants are finite plain data",()=>{for(let i=0;i<3;i++){const t=gen(i);assert.equal(t.flowers.length,9);assert.equal(t.vases.length,3);assert.equal(t.duration,20000);assert.equal(t.flowers.reduce((s,f)=>s+f.units,0),12);assert.deepEqual(game.validate(t),[]);assert.doesNotThrow(()=>structuredClone(t))}});
test("hostile picker falls back",()=>assert.deepEqual(game.generate({pick(){throw Error()}}),gen()));
test("independent ternary enumeration proves exact 19683 and 810",()=>{const t=gen(),bins=[[],[],[]];let total=0,valid=0;const visit=i=>{if(i===9){total++;if(analyzeFlowers(t.flowers,bins).success)valid++;return}for(let v=0;v<3;v++){bins[v].push(IDS[i]);visit(i+1);bins[v].pop()}};visit(0);assert.equal(total,19683);assert.equal(valid,810);assert.deepEqual(t.proof,{totalAllocations:19683,validAllocations:810,validTypePatterns:7,placementOrders:362880,totalUnits:12,everyPlacementReversible:true})});
test("validator rejects rules proof capacity inventory held and extras",()=>{const base=gen();for(const mutate of[t=>t.extra=1,t=>t.flowers[0].units=2,t=>t.vases[0].capacity=5,t=>t.proof.validAllocations=1,t=>t.state.tray.push("s1"),t=>t.duration=1]){const t=structuredClone(base);mutate(t);assert.notDeepEqual(game.validate(t),[])}const h=harness(),a=api(h);a.pick("s1");const held=a.snapshotTask();assert.deepEqual(game.validate(held),[]);held.state.held.index=99;assert.notDeepEqual(game.validate(held),[]);h.dispose()});
test("render shows three distinct vases, twelve dots and nine flowers",()=>{const h=harness(),a=api(h),s=a.inspect();assert.equal(a.elements.vaseCards.length,3);assert.equal(a.elements.dotRows.flatMap(r=>r.children).length,12);assert.equal(a.elements.flowerButtons.size,9);assert.deepEqual(s.analysis.loads,[0,0,0]);assert.equal(s.tray.length,9);h.dispose()});
test("single and double flowers light one and two physical dots",()=>{const h=harness(),a=api(h);a.pick("s1");a.dropVase(0);h.runFor(160);assert.deepEqual(a.inspect().analysis.loads,[1,0,0]);a.pick("d1");a.dropVase(1);h.runFor(160);assert.deepEqual(a.inspect().analysis.loads,[1,2,0]);h.dispose()});
test("over capacity returns gently without move or inventory loss",()=>{const h=harness(),a=api(h);a.apply([["d1","d2"],[],[]],gen().start.filter(x=>!["d1","d2"].includes(x)),2);const before=a.inspect();a.pick("s1");assert.equal(a.dropVase(0),false);let s=a.inspect();assert.equal(s.reject,0);assert.equal(s.moves,2);assert.deepEqual(s.vases,before.vases);assert.deepEqual(s.tray,before.tray);h.runFor(140);assert.equal(a.inspect().reject,-1);h.dispose()});
test("flowers move between vases and back to tray reversibly",()=>{const h=harness(),a=api(h);a.pick("s1");a.dropVase(0);h.runFor(160);a.pick("s1");a.dropVase(1);h.runFor(160);assert.deepEqual(a.inspect().vases,[[],["s1"],[]]);a.pick("s1");a.dropTray();h.runFor(160);assert.ok(a.inspect().tray.includes("s1"));assert.equal(new Set([...a.inspect().vases.flat(),...a.inspect().tray]).size,9);h.dispose()});
test("cancel restores exact order",()=>{const h=harness(),a=api(h),before=a.inspect();a.pick(before.tray[4]);a.cancel();assert.deepEqual(a.inspect().tray,before.tray);assert.deepEqual(a.inspect().vases,before.vases);h.dispose()});
test("keyboard arrows and Space share pickup drop path",()=>{const h=harness(),a=api(h),b=a.elements.flowerButtons.get("s1");b.focus();b.dispatchEvent(ev("keydown",{key:" "}));assert.equal(a.inspect().held.id,"s1");const v=a.elements.vaseCards[0];v.focus();v.dispatchEvent(ev("keydown",{key:" "}));h.runFor(160);assert.deepEqual(a.inspect().analysis.loads,[1,0,0]);v.dispatchEvent(ev("keydown",{key:"ArrowRight"}));assert.equal(h.d.activeElement,a.elements.vaseCards[1]);h.dispose()});
test("success auto commits after tracked snap exactly once",()=>{const h=harness(),a=api(h),valid=[["d1","d2"],["d3","s1","s2"],["s3","s4","s5"]];a.apply(valid,["s6"],8);a.pick("s6");a.dropVase(2);h.runFor(159);assert.equal(h.finishes.length,0);h.runFor(1);assert.equal(a.inspect().outcome,"success");h.runFor(220);assert.equal(h.finishes.length,1);assert.equal(h.finishes[0].correct,true);assert.deepEqual(h.finishes[0].payload.analysis.loads,[4,4,4]);assert.equal(h.calls,1);h.dispose()});
test("exact 20000 deadline retains arrangement and held flower",()=>{const h=harness(),a=api(h);a.pick("d1");const before=a.inspect();h.runTo(19999);assert.equal(h.finishes.length,0);h.runTo(20000);assert.equal(h.finishes.length,1);assert.equal(h.finishes[0].payload.outcome,"timeout");assert.deepEqual(h.finishes[0].payload.state.held,before.held);assert.deepEqual(h.finishes[0].payload.analysis,before.analysis);assert.equal(a.inspect().remaining,0);h.dispose()});
test("normal and reduced retain nonzero snap without RAF",()=>{const n=harness(),na=api(n);na.pick("s1");na.dropVase(0);assert.equal(na.inspect().snapStage,0);n.runFor(80);assert.equal(na.inspect().snapStage,1);n.runFor(80);assert.equal(na.inspect().snapStage,2);const r=harness({reduced:true}),ra=api(r);ra.pick("s1");ra.dropVase(0);assert.equal(ra.inspect().snapStage,1);r.runFor(60);assert.equal(ra.inspect().snapStage,2);assert.equal(n.frames+r.frames,0);n.dispose();r.dispose()});
test("plain JSON held resume is exact",()=>{const h=harness(),a=api(h);a.pick("d2");const saved=JSON.parse(JSON.stringify(a.snapshotTask()));assert.deepEqual(game.validate(saved),[]);const h2=harness({task:saved});assert.deepEqual(api(h2).inspect().held,a.inspect().held);assert.deepEqual(api(h2).inspect().tray,a.inspect().tray);h.dispose();h2.dispose()});
test("dispose clears all tracked work and prevents finish",()=>{const h=harness(),a=api(h);a.pick("s1");a.dropVase(0);assert.ok(h.pending>=3);h.dispose();h.runTo(30000);assert.equal(h.pending,0);assert.equal(h.listeners,0);assert.equal(h.frames,0);assert.deepEqual(h.finishes,[]);assert.equal(a.inspect().disposed,true)});
test("real kernel disposal during reduced snap leaves no work",async()=>{const d=fakeDoc(),host=d.createElement("div"),qa={},finish=[],old=globalThis.cancelAnimationFrame;globalThis.cancelAnimationFrame=()=>{};try{const r=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(c,p)=>finish.push({c,p})});game.render(gen(),r.context);qa[ID].pick("s1");qa[ID].dropVase(0);r.dispose();await delay(150);assert.equal(qa[ID],undefined);assert.deepEqual(finish,[]);assert.deepEqual(r.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(old===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=old}});
test("300 cold renders stay bounded",()=>{const start=performance.now();for(let i=0;i<300;i++){const h=harness({task:gen(i%3),reduced:!!(i%2),width:i%2?390:430});assert.equal(api(h).elements.flowerButtons.size,9);h.dispose()}assert.ok(performance.now()-start<2200)});
test("source is context tracked offline ownerDocument only and clean",()=>{assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|AudioContext|localStorage)\b/);assert.doesNotMatch(source,/data-(?:answer|correct|target|solution)/);assert.doesNotMatch(source,/\p{Extended_Pictographic}/u)});
