import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import game from "../src/games/inhibition-opposite-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";
const ID="inhibition-opposite-v1",source=await readFile(new URL("../src/games/inhibition-opposite-v1.js",import.meta.url),"utf8"),appSource=await readFile(new URL("../app.js",import.meta.url),"utf8"),VALUES=["左","右"];
const taskFor=(shown="左")=>({kind:"choice",prompt:`「${shown}」と反対を選んで`,help:"読んだとおりには押さない。",options:["左","右"],answer:shown==="左"?"右":"左",duration:4500});
const importFresh=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n// ${suffix}`).toString("base64")}`)).default;
function seededPick(initial=0x0f0517e){let seed=initial>>>0,calls=0;return{pick(values){calls++;assert.deepEqual([...values],VALUES);seed=(Math.imul(seed,1664525)+1013904223)>>>0;return values[Math.floor(seed/2**32*values.length)]},get calls(){return calls}}}
function legacyGenerate(helper){const shown=helper.pick(["左","右"]),answer=shown==="左"?"右":"左";return{kind:"choice",prompt:`「${shown}」と反対を選んで`,help:"読んだとおりには押さない。",options:["左","右"],answer,duration:4500}}
class ClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(v){this.values=new Set(String(v||"").split(/\s+/).filter(Boolean));this.sync()}sync(){this.owner._className=[...this.values].join(" ")}add(...v){v.forEach(x=>this.values.add(x));this.sync()}remove(...v){v.forEach(x=>this.values.delete(x));this.sync()}contains(v){return this.values.has(v)}toggle(v,force){const next=force===undefined?!this.values.has(v):Boolean(force);next?this.values.add(v):this.values.delete(v);this.sync();return next}}
const noop=()=>{};class Gradient{addColorStop(){}}function context2d(){return new Proxy({globalAlpha:1,createLinearGradient:()=>new Gradient()},{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)})}
class Element extends EventTarget{constructor(tag,owner){super();this.tagName=tag.toUpperCase();this.ownerDocument=owner;this.children=[];this.parentElement=null;this.attributes=new Map();this.dataset={};this.style={};this._className="";this.classList=new ClassList(this);this.textContent="";this.clientWidth=393;this.width=0;this.height=0;this.disabled=false;this.type="";this.ctx=this.tagName==="CANVAS"?context2d():null}set className(v){this._className=String(v);this.classList.reset(v)}get className(){return this._className}append(...nodes){for(const node of nodes){node.parentElement=this;this.children.push(node)}}replaceChildren(...nodes){this.children=[];this.append(...nodes)}setAttribute(k,v){this.attributes.set(k,String(v))}getAttribute(k){return this.attributes.get(k)??null}focus(){this.ownerDocument.activeElement=this}blur(){if(this.ownerDocument.activeElement===this)this.ownerDocument.activeElement=null}getContext(){return this.ctx}click(){if(!this.disabled)this.dispatchEvent(new Event("click",{bubbles:true,cancelable:true}))}getBoundingClientRect(){const width=Number.parseFloat(this.style.width)||this.clientWidth||393,height=Number.parseFloat(this.style.height)||178;return{left:0,top:0,width,height,right:width,bottom:height}}}
function documentFor(dpr=3){const view=new EventTarget();view.devicePixelRatio=dpr;const owner={defaultView:view,activeElement:null};owner.createElement=tag=>new Element(tag,owner);return owner}
function harness({reduced=false,viewport={width:393,height:852,dpr:3},owner=documentFor(viewport.dpr)}={}){const controller=new AbortController(),host=owner.createElement("div"),qa={},listeners=new Set(),finishes=[];host.clientWidth=viewport.width;let deadline=null,disposed=false;const dispose=()=>{if(disposed)return;disposed=true;controller.abort();if(deadline)deadline.on=false;for(const item of listeners)item.target.removeEventListener(item.type,item.fn,item.options);listeners.clear()};const context={host,qa,signal:controller.signal,reducedMotion:reduced,viewport,finish(correct,result={}){if(disposed||finishes.length)return false;finishes.push({correct:Boolean(correct),result});dispose();return true},setDeadline(ms,fn){deadline={ms,fn,on:true};return deadline},listen(target,type,fn,options){target.addEventListener(type,fn,options);const item={target,type,fn,options};listeners.add(item);return()=>{target.removeEventListener(type,fn,options);listeners.delete(item)}},later(){throw Error("opposite must not schedule non-deadline timers")},frame(){throw Error("opposite must not book frames")}};const triggerDeadline=()=>{if(deadline?.on&&!disposed){deadline.on=false;deadline.fn();return true}return false};return{context,host,owner,qa,finishes,dispose,triggerDeadline,get deadline(){return deadline}}}
function mount(options={}){const h=harness(options),task=options.task||taskFor();game.render(task,h.context);const api=h.qa[ID],stage=h.host.children[1],scene=stage.children[0],status=stage.children[1],choices=stage.children[2];return Object.assign(h,{task,api,stage,scene,canvas:scene.children[0],word:scene.children[1],status,choices,buttons:choices.children})}
const key=(target,value)=>{const event=new Event("keydown",{bubbles:true,cancelable:true});Object.defineProperty(event,"key",{value});target.dispatchEvent(event);return event};

test("metadata preserves published v1.0 identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.0",tier:2,flavor:"classic",step:1,family:"inhibition-opposite",category:"inhibition"}));
test("10,000 generations exactly match one pick and current factory shape",()=>{const a=seededPick(0xa8761a1),b=seededPick(0xa8761a1),seen=new Set();for(let i=0;i<10000;i++){const actual=game.generate(a),legacy=legacyGenerate(b);assert.deepEqual(actual,legacy,`generation ${i}`);assert.deepEqual(Object.keys(actual),["kind","prompt","help","options","answer","duration"]);assert.deepEqual(game.validate(actual),[]);assert.doesNotThrow(()=>structuredClone(actual));seen.add(actual.prompt)}assert.equal(a.calls,10000);assert.equal(b.calls,10000);assert.equal(seen.size,2)});
test("both shown values preserve exact prompt, opposite answer, fixed options, and identical DOM",()=>{let shape=null;for(const shown of VALUES){const task=taskFor(shown);assert.deepEqual(game.validate(task),[]);assert.equal(task.answer,shown==="左"?"右":"左");assert.deepEqual(task.options,VALUES);const h=mount({task}),current={sceneClass:h.scene.className,wordClass:h.word.className,childCount:h.word.children.length,canvasClass:h.canvas.className};assert.equal(h.word.textContent,shown);assert.equal(h.api.inspect().shown,shown);assert.equal(h.canvas.getAttribute("aria-label"),shown);shape??=current;assert.deepEqual(current,shape);h.dispose()}});
test("generator requires pick and rejects hostile shown values",()=>{assert.throws(()=>game.generate(),/pick is required/);for(const value of["上","",null,1])assert.throws(()=>game.generate({pick:()=>value}),/左 or 右/)});
test("strict validator rejects prompt, opposite answer, option order, timing, extra and missing fields",()=>{const valid=taskFor("左"),mutations=[null,[],{...valid,kind:"expression"},{...valid,prompt:"左と反対を選んで"},{...valid,prompt:"「上」と反対を選んで"},{...valid,help:"changed"},{...valid,options:["右","左"]},{...valid,options:["左"]},{...valid,answer:"左"},{...valid,duration:4499},{...valid,shown:"左"},Object.fromEntries(Object.entries(valid).filter(([key])=>key!=="prompt"))];for(const value of mutations)assert.ok(game.validate(value).length,JSON.stringify(value))});
test("legacy factory is removed while generic choice authority remains pinned",()=>{assert.doesNotMatch(appSource,/\{id:"inhibition-opposite-v1",version:"1\.0",category:"inhibition",make:/);for(const exact of['if(task.kind==="choice"){makeChoices(task);startDeadline(task.duration,()=>genericTimeout(task));return}','button.textContent=value','finishTask(v===task.answer,{answerLabel:task.answer})','detail:"時間切れです。脳は定時退社しました。"'])assert.ok(appSource.includes(exact),exact)});
test("plain JSON fresh-module resume renders exact shown word and succeeds immediately",async()=>{const fresh=await importFresh(Date.now()),task=JSON.parse(JSON.stringify(taskFor("右"))),h=harness();fresh.render(task,h.context);const api=h.qa[ID],state=api.inspect();assert.equal(state.shown,"右");assert.equal(state.prompt,task.prompt);assert.deepEqual(state.buttons.map(x=>x.text),VALUES);api.choose("左");assert.deepEqual(h.finishes,[{correct:true,result:{answerLabel:"左"}}]);assert.equal(api.inspect().feedbackStages,1)});
test("wrong and success preserve exact result, feedback, lock, and one finish",()=>{for(const shown of VALUES)for(const correct of[false,true]){const h=mount({task:taskFor(shown)}),selected=correct?h.task.answer:VALUES.find(value=>value!==h.task.answer);h.api.choose(selected);assert.deepEqual(h.finishes,[{correct,result:{answerLabel:h.task.answer}}]);const state=h.api.inspect();assert.equal(state.result,correct?"success":"wrong");assert.equal(state.selected,selected);assert.equal(state.choicesEnabled,false);assert.equal(state.feedbackStages,1);assert.ok(h.buttons.every(button=>button.disabled));h.api.choose(h.task.answer);assert.equal(h.finishes.length,1)}});
test("click and native Enter/Space share fixed two-choice focus path",()=>{for(const value of["Enter"," "]){const h=mount({task:taskFor("左")}),button=h.buttons[1];button.focus();const event=key(button,value);assert.equal(event.defaultPrevented,true);assert.deepEqual(h.finishes,[{correct:true,result:{answerLabel:"右"}}])}const click=mount({task:taskFor("右")});click.buttons[1].click();assert.equal(click.finishes[0].correct,false)});
test("4500ms deadline returns exact generic timeout payload",()=>{for(const shown of VALUES){const h=mount({task:taskFor(shown)});assert.equal(h.deadline.ms,4500);h.triggerDeadline();assert.deepEqual(h.finishes,[{correct:false,result:{detail:"時間切れです。脳は定時退社しました。",answerLabel:h.task.answer}}]);assert.equal(h.api.inspect().result,"timeout");assert.equal(h.api.inspect().feedbackStages,1)}});
test("normal and reduced retain feedback with zero continuous frames",()=>{for(const reduced of[false,true]){const h=mount({reduced});h.api.choose(h.task.answer);assert.equal(h.api.inspect().reduced,reduced);assert.equal(h.api.inspect().feedbackStages,1);assert.equal(h.api.inspect().frames,0)}});
test("393/402 DPR3 exposes five scenes for both shown values with one neutral treatment",()=>{let treatment=null;for(const shown of VALUES)for(const reduced of[false,true])for(const viewport of[{width:393,height:852,dpr:3},{width:402,height:874,dpr:4}]){const h=mount({task:taskFor(shown),reduced,viewport}),canvas=h.api.inspect().canvas,current={scene:h.scene.className,word:h.word.className,canvas:h.canvas.className,children:h.word.children.length};assert.equal(canvas.dpr,3);assert.equal(canvas.pixelWidth,canvas.cssWidth*3);assert.equal(canvas.pixelHeight,canvas.cssHeight*3);treatment??=current;assert.deepEqual(current,treatment);for(const scene of["initial","focus","wrong","success","timeout"])assert.equal(h.api.showScene(scene),true);h.dispose()}});
test("real runtime disposal cancels deadline, listeners, QA and finish",async()=>{const owner=documentFor(),host=owner.createElement("div"),qa={},finishes=[],oldRaf=globalThis.requestAnimationFrame,oldCancel=globalThis.cancelAnimationFrame;globalThis.requestAnimationFrame=()=>{throw Error("unexpected frame")};globalThis.cancelAnimationFrame=()=>{};try{const runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(taskFor("右"),runtime.context);runtime.dispose();await delay(80);assert.deepEqual(finishes,[]);assert.equal(qa[ID],undefined);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(oldRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=oldRaf;if(oldCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=oldCancel}});
test("ownerDocument and render source forbid raw lifetime, assets, icons, asymmetry, and direction cues",()=>{const owner=documentFor(),old=globalThis.document;globalThis.document={createElement(){throw Error("global document used")}};try{const h=mount({owner});const visit=node=>{assert.equal(node.ownerDocument,owner);node.children.forEach(visit)};visit(h.host);h.dispose()}finally{if(old===undefined)delete globalThis.document;else globalThis.document=old}assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement)\b/);assert.doesNotMatch(source,/(?:\.src\s*=|url\s*\()/);const renderSource=source.slice(source.indexOf("function render("),source.indexOf("export default"));assert.doesNotMatch(renderSource,/(?:shown\s*===|data-direction|direction-|io-word-|nth-child|nth-of-type|translateX|rotate|←|→|⬅|➡|👈|👉)/i);assert.equal((source.match(/\.io-word\{/g)||[]).length,1)});
