import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import game from "../src/games/inhibition-stroop-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";
const ID="inhibition-stroop-v1",source=await readFile(new URL("../src/games/inhibition-stroop-v1.js",import.meta.url),"utf8"),appSource=await readFile(new URL("../app.js",import.meta.url),"utf8"),styleSource=await readFile(new URL("../style.css",import.meta.url),"utf8"),NAMES=["むらさき","みどり","オレンジ","あお"],CLASSES={むらさき:"ink-purple",みどり:"ink-green",オレンジ:"ink-orange",あお:"ink-blue"},COLORS={むらさき:"#8B52B0",みどり:"#408B68",オレンジ:"#D77A32",あお:"#3E79B7"},COMBOS=NAMES.flatMap(word=>NAMES.filter(ink=>ink!==word).map(ink=>[word,ink]));
const importFresh=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n// ${suffix}`).toString("base64")}`)).default;
function helpers(initial=0x57a00){let seed=initial>>>0;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32),randomInt=(min,max)=>min+Math.floor(random()*(max-min+1)),pick=values=>values[randomInt(0,values.length-1)],shuffle=values=>{const copy=[...values];for(let i=copy.length-1;i>0;i--){const j=randomInt(0,i);[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};return{pick,shuffle}}
function legacyGenerate(h){const word=h.pick(NAMES),ink=h.pick(NAMES.filter(x=>x!==word));return{kind:"stroop",prompt:"文字ではなく、インクの色は？",help:"読んだら負け。見てください。",word,ink,options:h.shuffle(NAMES),answer:ink,duration:6500}}
const taskFor=(index=0)=>{const[word,ink]=COMBOS[index],shift=index%4,options=[...NAMES.slice(shift),...NAMES.slice(0,shift)];return{kind:"stroop",prompt:"文字ではなく、インクの色は？",help:"読んだら負け。見てください。",word,ink,options,answer:ink,duration:6500}};
class ClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(v){this.values=new Set(String(v||"").split(/\s+/).filter(Boolean));this.sync()}sync(){this.owner._className=[...this.values].join(" ")}add(...v){v.forEach(x=>this.values.add(x));this.sync()}remove(...v){v.forEach(x=>this.values.delete(x));this.sync()}contains(v){return this.values.has(v)}toggle(v,force){const next=force===undefined?!this.values.has(v):Boolean(force);next?this.values.add(v):this.values.delete(v);this.sync();return next}}
const noop=()=>{};class Gradient{addColorStop(){}}function context2d(){return new Proxy({globalAlpha:1,createLinearGradient:()=>new Gradient()},{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)})}
class Element extends EventTarget{constructor(tag,owner){super();this.tagName=tag.toUpperCase();this.ownerDocument=owner;this.children=[];this.parentElement=null;this.attributes=new Map();this.dataset={};this.style={};this._className="";this.classList=new ClassList(this);this.textContent="";this.clientWidth=393;this.width=0;this.height=0;this.disabled=false;this.type="";this.ctx=this.tagName==="CANVAS"?context2d():null}set className(v){this._className=String(v);this.classList.reset(v)}get className(){return this._className}append(...nodes){for(const node of nodes){node.parentElement=this;this.children.push(node)}}replaceChildren(...nodes){this.children=[];this.append(...nodes)}setAttribute(k,v){this.attributes.set(k,String(v))}getAttribute(k){return this.attributes.get(k)??null}focus(){this.ownerDocument.activeElement=this}blur(){if(this.ownerDocument.activeElement===this)this.ownerDocument.activeElement=null}getContext(){return this.ctx}click(){if(!this.disabled)this.dispatchEvent(new Event("click",{bubbles:true,cancelable:true}))}getBoundingClientRect(){const width=Number.parseFloat(this.style.width)||this.clientWidth||393,height=Number.parseFloat(this.style.height)||190;return{left:0,top:0,width,height,right:width,bottom:height}}}
function documentFor(dpr=3){const view=new EventTarget();view.devicePixelRatio=dpr;const owner={defaultView:view,activeElement:null};owner.createElement=tag=>new Element(tag,owner);return owner}
function harness({reduced=false,viewport={width:393,height:852,dpr:3},owner=documentFor(viewport.dpr)}={}){const controller=new AbortController(),host=owner.createElement("div"),qa={},listeners=new Set(),finishes=[];host.clientWidth=viewport.width;let deadline=null,disposed=false;const dispose=()=>{if(disposed)return;disposed=true;controller.abort();if(deadline)deadline.on=false;for(const item of listeners)item.target.removeEventListener(item.type,item.fn,item.options);listeners.clear()};const context={host,qa,signal:controller.signal,reducedMotion:reduced,viewport,finish(correct,result={}){if(disposed||finishes.length)return false;finishes.push({correct:Boolean(correct),result});dispose();return true},setDeadline(ms,fn){deadline={ms,fn,on:true};return deadline},listen(target,type,fn,options){target.addEventListener(type,fn,options);const item={target,type,fn,options};listeners.add(item);return()=>{target.removeEventListener(type,fn,options);listeners.delete(item)}},later(){throw Error("stroop must not schedule non-deadline timers")},frame(){throw Error("stroop must not book frames")}};const triggerDeadline=()=>{if(deadline?.on&&!disposed){deadline.on=false;deadline.fn();return true}return false};return{context,host,owner,qa,finishes,dispose,triggerDeadline,get deadline(){return deadline}}}
function mount(options={}){const h=harness(options),task=options.task||taskFor();game.render(task,h.context);const api=h.qa[ID],stage=h.host.children[1],scene=stage.children[0],status=stage.children[1],choices=stage.children[2];return Object.assign(h,{task,api,stage,scene,canvas:scene.children[0],word:scene.children[1],status,choices,buttons:choices.children})}

test("metadata preserves published identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.0",tier:1,flavor:"classic",step:1,family:"inhibition-stroop",category:"inhibition"}));
test("10,000 generations exactly preserve word pick, unequal ink pick, full shuffle, and plain shape",()=>{const a=helpers(0xa8761a1),b=helpers(0xa8761a1),seen=new Set();for(let i=0;i<10000;i++){const actual=game.generate(a),legacy=legacyGenerate(b);assert.deepEqual(actual,legacy,`generation ${i}`);assert.deepEqual(Object.keys(actual),["kind","prompt","help","word","ink","options","answer","duration"]);assert.deepEqual(game.validate(actual),[]);assert.doesNotThrow(()=>structuredClone(actual));seen.add(`${actual.word}/${actual.ink}`)}assert.equal(seen.size,12)});
test("all 12 ordered combinations preserve inequality, class mapping, exact color, answer, and four options",()=>{for(let index=0;index<12;index++){const task=taskFor(index),[word,ink]=COMBOS[index];assert.deepEqual(game.validate(task),[]);assert.equal(task.word,word);assert.equal(task.ink,ink);assert.notEqual(word,ink);assert.equal(task.answer,ink);assert.deepEqual(new Set(task.options),new Set(NAMES));const h=mount({task});assert.equal(h.word.textContent,word);assert.ok(h.word.classList.contains(CLASSES[ink]));assert.equal(h.api.inspect().mappedColor,COLORS[ink]);assert.ok(h.buttons.every(button=>!button.className.includes("ink-")));h.dispose()}});
test("generator requires helpers and rejects hostile picks",()=>{assert.throws(()=>game.generate(),/pick and shuffle/);assert.throws(()=>game.generate({pick:()=>"しろ",shuffle:x=>[...x]}),/supplied word/);let n=0;assert.throws(()=>game.generate({pick:values=>n++?"しろ":values[0],shuffle:x=>[...x]}),/unequal color/)});
test("validator rejects copy, duration, unknown/equal colors, false answer, missing/duplicate/foreign options",()=>{const valid=taskFor(),items=[null,{...valid,kind:"choice"},{...valid,prompt:"changed"},{...valid,help:"changed"},{...valid,duration:1},{...valid,word:"しろ"},{...valid,ink:valid.word},{...valid,answer:valid.word},{...valid,options:["むらさき","むらさき","オレンジ","あお"]},{...valid,options:["むらさき","みどり","オレンジ"]},{...valid,options:["むらさき","みどり","オレンジ","しろ"]}];for(const item of items)assert.ok(game.validate(item).length)});
test("legacy factory is removed while exact names, classes, stroop branch, and CSS colors remain pinned",()=>{assert.doesNotMatch(appSource,/\{id:"inhibition-stroop-v1",version:"1\.0",category:"inhibition",make:/);for(const exact of['const COLOR_NAMES=["むらさき","みどり","オレンジ","あお"]','const COLOR_CLASSES={"むらさき":"ink-purple","みどり":"ink-green","オレンジ":"ink-orange","あお":"ink-blue"}','if(task.kind==="stroop")','word.className=`stroop-word ${COLOR_CLASSES[task.ink]}`','makeChoices(task);startDeadline(task.duration,()=>genericTimeout(task))'])assert.ok(appSource.includes(exact),exact);for(const color of Object.values(COLORS))assert.ok(styleSource.includes(color))});
test("plain JSON fresh-module resume renders exact word and succeeds immediately with exact payload",async()=>{const fresh=await importFresh(Date.now()),task=JSON.parse(JSON.stringify(taskFor(7))),h=harness();fresh.render(task,h.context);const api=h.qa[ID],state=api.inspect();assert.equal(state.word,task.word);assert.equal(state.ink,task.ink);assert.equal(state.wordClass,CLASSES[task.ink]);assert.deepEqual(state.buttons.map(x=>x.text),task.options);api.choose(task.answer);assert.deepEqual(h.finishes,[{correct:true,result:{answerLabel:task.answer}}]);assert.equal(api.inspect().feedbackStages,1)});
test("wrong/success exact result, feedback, lock, and single finish",()=>{for(const correct of[false,true]){const h=mount(),selected=correct?h.task.answer:h.task.options.find(x=>x!==h.task.answer);h.api.choose(selected);assert.deepEqual(h.finishes,[{correct,result:{answerLabel:h.task.answer}}]);const state=h.api.inspect();assert.equal(state.result,correct?"success":"wrong");assert.equal(state.selected,selected);assert.equal(state.choicesEnabled,false);assert.equal(state.feedbackStages,1);assert.ok(h.buttons.every(x=>x.disabled));h.api.choose(h.task.answer);assert.equal(h.finishes.length,1)}});
test("click and explicit Enter/Space share 2x2 focus choice path",()=>{for(const key of["Enter"," "]){const h=mount(),answer=h.buttons.find(x=>x.textContent===h.task.answer);answer.focus();const event=new Event("keydown",{bubbles:true,cancelable:true});Object.defineProperty(event,"key",{value:key});answer.dispatchEvent(event);assert.equal(event.defaultPrevented,true);assert.equal(h.finishes[0].correct,true)}const click=mount();click.buttons.find(x=>x.textContent!==click.task.answer).click();assert.equal(click.finishes[0].correct,false)});
test("6500ms deadline returns exact generic timeout payload",()=>{const h=mount();assert.equal(h.deadline.ms,6500);h.triggerDeadline();assert.deepEqual(h.finishes,[{correct:false,result:{detail:"時間切れです。脳は定時退社しました。",answerLabel:h.task.answer}}]);assert.equal(h.api.inspect().result,"timeout");assert.equal(h.api.inspect().feedbackStages,1)});
test("normal and reduced retain feedback with no continuous frame",()=>{for(const reduced of[false,true]){const h=mount({reduced});h.api.choose(h.task.answer);assert.equal(h.api.inspect().reduced,reduced);assert.equal(h.api.inspect().feedbackStages,1);assert.equal(h.api.inspect().frames,0)}});
test("393/402 DPR3 exposes five scenes for every combination with neutral uncolored choices",()=>{for(let combo=0;combo<12;combo++)for(const reduced of[false,true])for(const viewport of[{width:393,height:852,dpr:3},{width:402,height:874,dpr:4}]){const h=mount({task:taskFor(combo),reduced,viewport}),canvas=h.api.inspect().canvas;assert.equal(canvas.dpr,3);assert.equal(canvas.pixelWidth,canvas.cssWidth*3);assert.equal(canvas.pixelHeight,canvas.cssHeight*3);assert.ok(h.buttons.every(button=>!button.className.includes("ink-")));for(const scene of["initial","focus","wrong","success","timeout"]){assert.equal(h.api.showScene(scene),true);if(scene==="initial"||scene==="focus")assert.equal(h.api.inspect().status.includes(h.task.answer),false)}h.dispose()}});
test("real runtime disposal cancels deadline/listeners/QA without finish",async()=>{const owner=documentFor(),host=owner.createElement("div"),qa={},finishes=[],oldRaf=globalThis.requestAnimationFrame,oldCancel=globalThis.cancelAnimationFrame;globalThis.requestAnimationFrame=()=>{throw Error("unexpected frame")};globalThis.cancelAnimationFrame=()=>{};try{const runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(taskFor(),runtime.context);runtime.dispose();await delay(80);assert.deepEqual(finishes,[]);assert.equal(qa[ID],undefined);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(oldRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=oldRaf;if(oldCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=oldCancel}});
test("ownerDocument and source forbid raw lifetime, network, audio, asset, and colored answer hints",()=>{const owner=documentFor(),old=globalThis.document;globalThis.document={createElement(){throw Error("global document used")}};try{const h=mount({owner});const visit=node=>{assert.equal(node.ownerDocument,owner);node.children.forEach(visit)};visit(h.host);h.dispose()}finally{if(old===undefined)delete globalThis.document;else globalThis.document=old}assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement)\b/);assert.doesNotMatch(source,/(?:\.src\s*=|url\s*\()/);assert.doesNotMatch(source,/st-choice[^}]*color:\s*(?:#8B52B0|#408B68|#D77A32|#3E79B7)/)});
