#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.."&&pwd);STAMP=$(date +%Y%m%d-%H%M%S);OUT=${1:-/tmp/agetest-inhibition-bubble-keep-v1-audit-$STAMP};cd "$ROOT";[[ ! -e "$OUT" ]]||{ echo "output exists" >&2;exit 2;};mkdir -p "$OUT";node tools/qa-browser-lanes.mjs start audit >/dev/null
ready='(async()=>{for(let i=0;i<240;i++){if(window.__BUBBLE_KEEP_FIXTURE__&&document.documentElement.dataset.ready==="true")return true;await new Promise(r=>setTimeout(r,25))}throw Error("ready")})()';nav(){ local v=$1 s=$2 m=$3 w=$4 h=$5 live=${6:-0};node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/inhibition-bubble-keep-v1.fixture.html?variant=$v&scene=$s&motion=$m&width=$w&live=$live" "$w" "$h" 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null;}
variants=(0 1 2 3);metrics=(393x852 402x874);motions=(normal reduced);scenes=(initial round-pop partial meter-1 meter-2 success exhausted timeout)
for v in "${variants[@]}";do for metric in "${metrics[@]}";do w=${metric%x*};h=${metric#*x};for m in "${motions[@]}";do for s in "${scenes[@]}";do nav "$v" "$s" "$m" "$w" "$h";node tools/qa-browser-lanes.mjs eval audit 'window.__BUBBLE_KEEP_FIXTURE__.report()' >"$OUT/evidence-$v-$metric-$s-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/board$v-$metric-$s-$m.png" >/dev/null;done;nav "$v" initial "$m" "$w" "$h" 1;node tools/qa-browser-lanes.mjs eval audit '(()=>{const f=window.__BUBBLE_KEEP_FIXTURE__,b=f.api.elements.buttons[0];b.focus();document.body.classList.add("fixture-focus");return{focused:b===document.activeElement,state:f.api.inspect(),report:f.report()}})()' >"$OUT/focus-$v-$metric-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/focus-$v-$metric-$m.png" >/dev/null;done;done;done
for metric in 390x844 430x932;do w=${metric%x*};h=${metric#*x};for v in "${variants[@]}";do for m in "${motions[@]}";do for s in initial success;do nav "$v" "$s" "$m" "$w" "$h";node tools/qa-browser-lanes.mjs eval audit 'window.__BUBBLE_KEEP_FIXTURE__.report()' >"$OUT/boundary-$v-$metric-$s-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/boundary-board$v-$metric-$s-$m.png" >/dev/null;done;done;done;done
cue='(()=>{const f=window.__BUBBLE_KEEP_FIXTURE__;return{variant:f.variant,bubbles:f.api.elements.buttons.map(b=>({shape:b.dataset.shape,size:b.dataset.size,answer:b.getAttribute("data-answer"),correct:b.getAttribute("data-correct"),rect:b.getBoundingClientRect().toJSON()})),report:f.report()}})()';for v in "${variants[@]}";do nav "$v" initial normal 393 852;node tools/qa-browser-lanes.mjs eval audit "$cue" >"$OUT/no-hidden-cue-$v.json";done
tap='(async()=>{const f=window.__BUBBLE_KEEP_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms)),fire=b=>{const q=b.getBoundingClientRect(),o={bubbles:true,cancelable:true,pointerId:81,pointerType:"touch",isPrimary:true,button:0,clientX:q.left+q.width/2,clientY:q.top+q.height/2};b.dispatchEvent(new PointerEvent("pointerdown",o));b.dispatchEvent(new PointerEvent("pointerup",o));b.dispatchEvent(new MouseEvent("click",{bubbles:true,cancelable:true,detail:1,clientX:o.clientX,clientY:o.clientY}))},trace=[];for(const b of f.api.elements.buttons.filter(x=>x.dataset.shape==="round")){fire(b);const during=f.api.inspect();await wait(f.motion==="reduced"?95:175);trace.push({during,after:f.api.inspect()})}await wait(220);const report=f.report();return{status:report.status,variant:f.variant,motion:f.motion,trace,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,targets:report.targets,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()';for v in "${variants[@]}";do for m in "${motions[@]}";do nav "$v" initial "$m" 390 844 1;node tools/qa-browser-lanes.mjs eval audit "$tap" >"$OUT/touch-success-$v-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/touch-success-$v-$m.png" >/dev/null;done;done
keyboard='(async()=>{const f=window.__BUBBLE_KEEP_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms)),stage=f.api.elements.stage,key=k=>stage.dispatchEvent(new KeyboardEvent("keydown",{key:k,bubbles:true,cancelable:true}));f.api.elements.buttons[0].focus();key("ArrowRight");const arrowFocus=f.api.inspect().focusedIndex;for(const b of f.api.elements.buttons.filter(x=>x.dataset.shape==="round")){b.focus();key(" ");await wait(f.motion==="reduced"?95:175)}await wait(220);const report=f.report();return{status:report.status,variant:f.variant,motion:f.motion,arrowFocus,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,targets:report.targets,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()';for pair in 0:normal 3:reduced;do v=${pair%:*};m=${pair#*:};nav "$v" initial "$m" 430 932 1;node tools/qa-browser-lanes.mjs eval audit "$keyboard" >"$OUT/keyboard-$v-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/keyboard-success-$v-$m.png" >/dev/null;done
recover='(async()=>{const f=window.__BUBBLE_KEEP_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms)),star=f.api.elements.buttons.find(b=>b.dataset.shape==="star"),fire=b=>b.dispatchEvent(new MouseEvent("click",{bubbles:true,cancelable:true,detail:1}));fire(star);await wait(f.motion==="reduced"?90:130);const one=f.api.inspect();fire(star);await wait(f.motion==="reduced"?90:130);const two=f.api.inspect();for(const b of f.api.elements.buttons.filter(x=>x.dataset.shape==="round")){fire(b);await wait(f.motion==="reduced"?95:175)}await wait(220);const report=f.report();return{motion:f.motion,one,two,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()';exhaust='(async()=>{const f=window.__BUBBLE_KEEP_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms)),star=f.api.elements.buttons.find(b=>b.dataset.shape==="star"),fire=()=>star.dispatchEvent(new MouseEvent("click",{bubbles:true,cancelable:true,detail:1}));fire();await wait(f.motion==="reduced"?90:130);fire();await wait(f.motion==="reduced"?90:130);fire();await wait(220);const report=f.report();return{motion:f.motion,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()';for m in "${motions[@]}";do nav 2 initial "$m" 390 844 1;node tools/qa-browser-lanes.mjs eval audit "$recover" >"$OUT/recover-success-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/recover-success-$m.png" >/dev/null;nav 2 initial "$m" 390 844 1;node tools/qa-browser-lanes.mjs eval audit "$exhaust" >"$OUT/exhaust-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/exhaust-$m.png" >/dev/null;done
deadline='(async()=>{const f=window.__BUBBLE_KEEP_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms));f.api.showScene("meter-2");const before=f.api.inspect();for(let i=0;i<200;i++){if(f.report().finishes.length)break;await wait(100)}const elapsed=performance.now()-f.renderedAt,report=f.report();return{motion:f.motion,elapsed,before,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()';nav 1 initial normal 390 844 1;node tools/qa-browser-lanes.mjs eval audit "$deadline" >"$OUT/deadline-390x844-normal.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/deadline-390x844-normal.png" >/dev/null;nav 1 initial reduced 430 932 1;node tools/qa-browser-lanes.mjs eval audit "$deadline" >"$OUT/deadline-430x932-reduced.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/deadline-430x932-reduced.png" >/dev/null
disposeNormal='(async()=>{const f=window.__BUBBLE_KEEP_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms)),round=f.api.elements.buttons.find(b=>b.dataset.shape==="round");round.click();const state=f.api.inspect(),before=f.runtime.inspect();f.runtime.dispose();await wait(220);return{state,before,after:f.runtime.inspect(),qaPresent:Boolean(f.qa[f.game.metadata.id]),finishes:f.report().finishes}})()';disposeReduced='(async()=>{const f=window.__BUBBLE_KEEP_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms)),round=f.api.elements.buttons.find(b=>b.dataset.shape==="round");round.click();const state=f.api.inspect(),before=f.runtime.inspect();f.runtime.dispose();await wait(220);return{state,before,after:f.runtime.inspect(),qaPresent:Boolean(f.qa[f.game.metadata.id]),finishes:f.report().finishes}})()';nav 0 initial normal 390 844 1;node tools/qa-browser-lanes.mjs eval audit "$disposeNormal" >"$OUT/dispose-390x844-normal.json";nav 0 initial reduced 430 932 1;node tools/qa-browser-lanes.mjs eval audit "$disposeReduced" >"$OUT/dispose-430x932-reduced.json"
perf='(async()=>{const f=window.__BUBBLE_KEEP_FIXTURE__,round=f.api.elements.buttons.find(b=>b.dataset.shape==="round"),d=[];round.click();const ownedAtStart=f.runtime.inspect().frames;let p=performance.now();await new Promise(resolve=>{const tick=n=>{d.push(n-p);p=n;if(d.length===90)resolve();else requestAnimationFrame(tick)};requestAnimationFrame(tick)});const report=f.report(),runtime=f.runtime.inspect(),expected=f.motion==="normal"?1:0,result={status:d.length===90&&ownedAtStart===expected&&runtime.frames===0&&!report.external.length&&!report.errors.length&&report.viewport.bodyScrollWidth<=report.width?"pass":"fail",motion:f.motion,frames:d.length,averageFrameMs:d.reduce((a,b)=>a+b,0)/d.length,maxFrameMs:Math.max(...d),ownedAtStart,gameOwnedFramesAfter:runtime.frames,state:f.api.inspect(),runtime,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors};f.runtime.dispose();return result})()';nav 0 initial normal 390 844 1;node tools/qa-browser-lanes.mjs eval audit "$perf" >"$OUT/performance-390x844-normal.json";nav 3 initial reduced 430 932 1;node tools/qa-browser-lanes.mjs eval audit "$perf" >"$OUT/performance-430x932-reduced.json"
OUT="$OUT" python - <<'PY'
from pathlib import Path
from PIL import Image,ImageChops,ImageStat
import json,math,os,subprocess
r=Path(os.environ['OUT']);variants=range(4);metrics=['393x852','402x874'];motions=['normal','reduced'];scenes=['initial','round-pop','partial','meter-1','meter-2','success','exhausted','timeout'];rows=[];fail=[]
for v in variants:
 for metric in metrics:
  for scene in scenes:
   a=Image.open(r/f'board{v}-{metric}-{scene}-normal.png').convert('RGB');b=Image.open(r/f'board{v}-{metric}-{scene}-reduced.png').convert('RGB');d=ImageChops.difference(a,b);st=ImageStat.Stat(d);rows.append({'key':f'{v}-{metric}-{scene}','size':[a.width,a.height],'mae':round(sum(st.mean)/3,3),'normalizedRMSE':round(math.sqrt(sum(x*x for x in st.rms)/3)/255,6),'changed':round(sum(px!=(0,0,0) for px in d.getdata())/(a.width*a.height),5)})
   for m in motions:
    e=json.loads((r/f'evidence-{v}-{metric}-{scene}-{m}.json').read_text());s=e['state'];ok=(scene!='initial' or len(s['tappedRoundIds'])==0 and s['starTaps']==0) and (scene!='round-pop' or s['popping'] is not None and s['popState']==1) and (scene!='partial' or len(s['tappedRoundIds'])==2 and not s['done']) and (scene!='meter-1' or s['starTaps']==1 and not s['done']) and (scene!='meter-2' or s['starTaps']==2 and not s['done']) and (scene!='success' or s['result']=='success' and len(s['remainingRoundIds'])==0) and (scene!='exhausted' or s['result']=='exhausted' and s['starTaps']==3) and (scene!='timeout' or s['result']=='timeout')
    if e['status']!='pass' or e['dpr']!=3 or e['errors'] or e['external'] or e['viewport']['bodyScrollWidth']>e['width'] or min(min(t['height'],t['width']) for t in e['targets'])<44 or not ok:fail.append(f'evidence {v} {metric} {scene} {m}')
for v in variants:
 e=json.loads((r/f'no-hidden-cue-{v}.json').read_text());bs=e['bubbles']
 if len(bs)!=8 or sum(b['shape']=='round' and b['size']=='small' for b in bs)!=5 or sum(b['shape']=='star' and b['size']=='large' for b in bs)!=3 or any(b['answer'] or b['correct'] or min(b['rect']['width'],b['rect']['height'])<44 for b in bs):fail.append(f'cue {v}')
for v in variants:
 for m in motions:
  e=json.loads((r/f'touch-success-{v}-{m}.json').read_text())
  if not(e['status']=='pass' and len(e['trace'])==5 and all(x['during']['popState']==1 for x in e['trace']) and e['after']['result']=='success' and e['after']['starTaps']==0 and len(e['finishes'])==1 and e['finishes'][0]['correct'] and not e['overflow'] and not e['errors']):fail.append(f'touch {v} {m}')
for v,m in [(0,'normal'),(3,'reduced')]:
 e=json.loads((r/f'keyboard-{v}-{m}.json').read_text())
 if not(e['arrowFocus']>=0 and e['after']['result']=='success' and len(e['finishes'])==1 and e['finishes'][0]['correct'] and not e['overflow']):fail.append(f'keyboard {v} {m}')
for m in motions:
 e=json.loads((r/f'recover-success-{m}.json').read_text())
 if not(e['one']['starTaps']==1 and not e['one']['done'] and e['two']['starTaps']==2 and not e['two']['done'] and e['after']['result']=='success' and e['after']['starTaps']==2 and len(e['finishes'])==1):fail.append(f'recover {m}')
 e=json.loads((r/f'exhaust-{m}.json').read_text())
 if not(e['after']['result']=='exhausted' and e['after']['starTaps']==3 and len(e['finishes'])==1 and not e['finishes'][0]['correct']):fail.append(f'exhaust {m}')
for metric,m in [('390x844','normal'),('430x932','reduced')]:
 e=json.loads((r/f'deadline-{metric}-{m}.json').read_text())
 if not(17750<=e['elapsed']<=18550 and e['after']['result']=='timeout' and e['before']['tappedRoundIds']==e['after']['tappedRoundIds'] and e['before']['remainingRoundIds']==e['after']['remainingRoundIds'] and e['before']['starTaps']==e['after']['starTaps'] and len(e['finishes'])==1):fail.append(f'deadline {metric} {m}')
 e=json.loads((r/f'dispose-{metric}-{m}.json').read_text())
 if not(e['after']['disposed'] and e['after']['timeouts']==0 and e['after']['frames']==0 and e['after']['listeners']==0 and not e['qaPresent'] and not e['finishes']):fail.append(f'dispose {metric} {m}')
 e=json.loads((r/f'performance-{metric}-{m}.json').read_text())
 if not(e['status']=='pass' and e['frames']==90 and e['ownedAtStart']==(1 if m=='normal' else 0) and e['gameOwnedFramesAfter']==0 and not e['overflow'] and not e['errors']):fail.append(f'perf {metric} {m}')
for metric in ['390x844','430x932']:
 w,h=map(int,metric.split('x'))
 for v in variants:
  for m in motions:
   for s in ['initial','success']:
    e=json.loads((r/f'boundary-{v}-{metric}-{s}-{m}.json').read_text());im=Image.open(r/f'boundary-board{v}-{metric}-{s}-{m}.png')
    if e['status']!='pass' or e['dpr']!=3 or e['errors'] or e['external'] or e['viewport']['bodyScrollWidth']>w or min(min(t['height'],t['width']) for t in e['targets'])<44 or im.size!=(w*3,h*3):fail.append(f'boundary {v} {metric} {s} {m}')
for v in variants:
 for metric in metrics:
  for m in motions:
   e=json.loads((r/f'focus-{v}-{metric}-{m}.json').read_text())
   if not e['focused'] or e['report']['status']!='pass':fail.append(f'focus {v} {metric} {m}')
files=[str(r/f'board0-393x852-{s}-normal.png') for s in scenes];subprocess.run(['magick','montage',*files,'-thumbnail','393x852','-tile','8x1','-geometry','+4+0',str(r/'director-contact-sheet.png')],check=True)
report={'status':'pass' if not fail else 'fail','canonicalViewports':[{'width':393,'height':852,'dpr':3},{'width':402,'height':874,'dpr':3}],'variants':list(variants),'states':scenes,'comparisons':len(rows),'canonicalScreenshots':len(rows)*2,'focusScreenshots':16,'boundaryScreenshots':32,'touchRoutes':8,'keyboardRoutes':2,'recoverRoutes':2,'exhaustionRoutes':2,'allDpr3':not any('evidence' in x for x in fail),'allFullResolution':all(x['size'] in ([1179,2556],[1206,2622]) for x in rows),'maxMAE':max(x['mae'] for x in rows),'maxNormalizedRMSE':max(x['normalizedRMSE'] for x in rows),'failures':fail,'rows':rows};(r/'comparison-report.json').write_text(json.dumps(report,indent=2));print(json.dumps({k:v for k,v in report.items() if k!='rows'},indent=2));raise SystemExit(bool(fail))
PY
echo "$OUT"
