import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import game from "../src/games/inhibition-flanker-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";

const ID="inhibition-flanker-v1",source=await readFile(new URL("../src/games/inhibition-flanker-v1.js",import.meta.url),"utf8"),appSource=await readFile(new URL("../app.js",import.meta.url),"utf8"),ANSWERS=["左","右"];
const taskFor=(answer="左")=>({kind:"flanker",prompt:"真ん中の矢印はどっち？",help:"外野の声は無視。",line:answer==="左"?"→ → ← → →":"← ← → ← ←",options:["左","右"],answer,duration:5500});
const importFresh=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n// ${suffix}`).toString("base64")}`)).default;
function seededPick(initial=0x10f1a){let seed=initial>>>0,calls=0;return{pick(values){calls++;assert.deepEqual([...values],ANSWERS);seed=(Math.imul(seed,1664525)+1013904223)>>>0;return values[Math.floor(seed/2**32*values.length)]},get calls(){return calls}}}
function legacyGenerate(helper){const answer=helper.pick(["左","右"]),center=answer==="左"?"←":"→",outer=answer==="左"?"→":"←";return{kind:"flanker",prompt:"真ん中の矢印はどっち？",help:"外野の声は無視。",line:`${outer} ${outer} ${center} ${outer} ${outer}`,options:["左","右"],answer,duration:5500}}
class ClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(v){this.values=new Set(String(v||"").split(/\s+/).filter(Boolean));this.sync()}sync(){this.owner._className=[...this.values].join(" ")}add(...v){v.forEach(x=>this.values.add(x));this.sync()}remove(...v){v.forEach(x=>this.values.delete(x));this.sync()}contains(v){return this.values.has(v)}toggle(v,force){const next=force===undefined?!this.values.has(v):Boolean(force);next?this.values.add(v):this.values.delete(v);this.sync();return next}}
const noop=()=>{};class Gradient{addColorStop(){}}function context2d(){return new Proxy({globalAlpha:1,createLinearGradient:()=>new Gradient()},{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)})}
class Element extends EventTarget{constructor(tag,owner){super();this.tagName=tag.toUpperCase();this.ownerDocument=owner;this.children=[];this.parentElement=null;this.attributes=new Map();this.dataset={};this.style={};this._className="";this.classList=new ClassList(this);this.textContent="";this.clientWidth=393;this.width=0;this.height=0;this.disabled=false;this.type="";this.ctx=this.tagName==="CANVAS"?context2d():null}set className(v){this._className=String(v);this.classList.reset(v)}get className(){return this._className}append(...nodes){for(const node of nodes){node.parentElement=this;this.children.push(node)}}replaceChildren(...nodes){this.children=[];this.append(...nodes)}setAttribute(k,v){this.attributes.set(k,String(v))}getAttribute(k){return this.attributes.get(k)??null}focus(){this.ownerDocument.activeElement=this}blur(){if(this.ownerDocument.activeElement===this)this.ownerDocument.activeElement=null}getContext(){return this.ctx}click(){if(!this.disabled)this.dispatchEvent(new Event("click",{bubbles:true,cancelable:true}))}getBoundingClientRect(){const width=Number.parseFloat(this.style.width)||this.clientWidth||393,height=Number.parseFloat(this.style.height)||178;return{left:0,top:0,width,height,right:width,bottom:height}}}
function documentFor(dpr=3){const view=new EventTarget();view.devicePixelRatio=dpr;const owner={defaultView:view,activeElement:null};owner.createElement=tag=>new Element(tag,owner);return owner}
function harness({reduced=false,viewport={width:393,height:852,dpr:3},owner=documentFor(viewport.dpr)}={}){const controller=new AbortController(),host=owner.createElement("div"),qa={},listeners=new Set(),finishes=[];host.clientWidth=viewport.width;let deadline=null,disposed=false;const dispose=()=>{if(disposed)return;disposed=true;controller.abort();if(deadline)deadline.on=false;for(const item of listeners)item.target.removeEventListener(item.type,item.fn,item.options);listeners.clear()};const context={host,qa,signal:controller.signal,reducedMotion:reduced,viewport,finish(correct,result={}){if(disposed||finishes.length)return false;finishes.push({correct:Boolean(correct),result});dispose();return true},setDeadline(ms,fn){deadline={ms,fn,on:true};return deadline},listen(target,type,fn,options){target.addEventListener(type,fn,options);const item={target,type,fn,options};listeners.add(item);return()=>{target.removeEventListener(type,fn,options);listeners.delete(item)}},later(){throw Error("flanker must not schedule non-deadline timers")},frame(){throw Error("flanker must not book frames")}};const triggerDeadline=()=>{if(deadline?.on&&!disposed){deadline.on=false;deadline.fn();return true}return false};return{context,host,owner,qa,finishes,dispose,triggerDeadline,get deadline(){return deadline}}}
function mount(options={}){const h=harness(options),task=options.task||taskFor();game.render(task,h.context);const api=h.qa[ID],stage=h.host.children[1],scene=stage.children[0],status=stage.children[1],choices=stage.children[2];return Object.assign(h,{task,api,stage,scene,canvas:scene.children[0],line:scene.children[1],status,choices,buttons:choices.children})}
const key=(target,value)=>{const event=new Event("keydown",{bubbles:true,cancelable:true});Object.defineProperty(event,"key",{value});target.dispatchEvent(event);return event};

test("metadata preserves the published v1.0 identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.0",tier:1,flavor:"classic",step:1,family:"inhibition-flanker",category:"inhibition"}));
test("10,000 generations exactly match one answer pick and the current factory shape",()=>{const a=seededPick(0xa8761a1),b=seededPick(0xa8761a1),seen=new Set();for(let i=0;i<10000;i++){const actual=game.generate(a),legacy=legacyGenerate(b);assert.deepEqual(actual,legacy,`generation ${i}`);assert.deepEqual(Object.keys(actual),["kind","prompt","help","line","options","answer","duration"]);assert.deepEqual(game.validate(actual),[]);assert.doesNotThrow(()=>structuredClone(actual));seen.add(actual.answer)}assert.equal(a.calls,10000);assert.equal(b.calls,10000);assert.deepEqual(seen,new Set(ANSWERS))});
test("both frozen directions preserve exact center/outer derivation, line, answer, and fixed options",()=>{for(const answer of ANSWERS){const task=taskFor(answer),arrows=task.line.split(" ");assert.deepEqual(game.validate(task),[]);assert.equal(arrows.length,5);assert.equal(arrows[2],answer==="左"?"←":"→");assert.ok([0,1,3,4].every(index=>arrows[index]===(answer==="左"?"→":"←")));assert.deepEqual(task.options,["左","右"]);const h=mount({task});assert.equal(h.line.textContent,task.line);assert.deepEqual(h.api.inspect().arrows,arrows);assert.equal(h.line.children.length,0);h.dispose()}});
test("generator requires pick and rejects hostile answers",()=>{assert.throws(()=>game.generate(),/pick is required/);assert.throws(()=>game.generate({pick:()=>"上"}),/左 or 右/);assert.throws(()=>game.generate({pick:()=>null}),/左 or 右/)});
test("strict validator rejects copy, timing, derivation, option order, extra and missing fields",()=>{const valid=taskFor(),mutations=[null,[],{...valid,kind:"choice"},{...valid,prompt:"changed"},{...valid,help:"changed"},{...valid,duration:5499},{...valid,answer:"上"},{...valid,line:"→ → → → →"},{...valid,options:["右","左"]},{...valid,options:["左","右","上"]},{...valid,center:"←"},Object.fromEntries(Object.entries(valid).filter(([key])=>key!=="line"))];for(const value of mutations)assert.ok(game.validate(value).length,JSON.stringify(value))});
test("current authority strings pin exact factory and generic flanker branch when still present",()=>{const factory='{id:"inhibition-flanker-v1",version:"1.0",category:"inhibition",make:()=>{const answer=pick(["左","右"]),center=answer==="左"?"←":"→",outer=answer==="左"?"→":"←";return{kind:"flanker",prompt:"真ん中の矢印はどっち？",help:"外野の声は無視。",line:`${outer} ${outer} ${center} ${outer} ${outer}`,options:["左","右"],answer,duration:5500}}}';if(appSource.includes(ID))assert.ok(appSource.includes(factory));for(const exact of['if(task.kind==="flanker")','line.className="expression"','line.textContent=task.line','makeChoices(task,{symbol:true})','startDeadline(task.duration,()=>genericTimeout(task))'])assert.ok(appSource.includes(exact),exact)});
test("plain JSON fresh-module resume renders the exact line and succeeds immediately",async()=>{const fresh=await importFresh(Date.now()),task=JSON.parse(JSON.stringify(taskFor("右"))),h=harness();fresh.render(task,h.context);const api=h.qa[ID],state=api.inspect();assert.equal(state.line,task.line);assert.deepEqual(state.arrows,["←","←","→","←","←"]);assert.deepEqual(state.buttons.map(x=>x.text),["左","右"]);api.choose("右");assert.deepEqual(h.finishes,[{correct:true,result:{answerLabel:"右"}}]);assert.equal(api.inspect().feedbackStages,1)});
test("wrong and success preserve exact result, synchronous feedback, lock, and one finish",()=>{for(const answer of ANSWERS)for(const correct of[false,true]){const h=mount({task:taskFor(answer)}),selected=correct?answer:ANSWERS.find(value=>value!==answer);h.api.choose(selected);assert.deepEqual(h.finishes,[{correct,result:{answerLabel:answer}}]);const state=h.api.inspect();assert.equal(state.result,correct?"success":"wrong");assert.equal(state.selected,selected);assert.equal(state.choicesEnabled,false);assert.equal(state.feedbackStages,1);assert.ok(h.buttons.every(button=>button.disabled));h.api.choose(answer);assert.equal(h.finishes.length,1)}});
test("touch/click, directional focus, and Enter/Space share the fixed left/right choice path",()=>{for(const arrow of["ArrowLeft","ArrowRight"]){const h=mount({task:taskFor("右")});h.buttons[0].blur();const move=key(h.stage,arrow);assert.equal(move.defaultPrevented,true);assert.equal(h.owner.activeElement,h.buttons[arrow==="ArrowLeft"?0:1]);const confirm=key(h.owner.activeElement,"Enter");assert.equal(confirm.defaultPrevented,true);assert.equal(h.finishes[0].correct,arrow==="ArrowRight")}for(const value of["Enter"," "]){const h=mount({task:taskFor("左")}),button=h.buttons[0];button.focus();const event=key(button,value);assert.equal(event.defaultPrevented,true);assert.deepEqual(h.finishes,[{correct:true,result:{answerLabel:"左"}}])}const click=mount({task:taskFor("右")});click.buttons[0].click();assert.equal(click.finishes[0].correct,false)});
test("5500ms deadline returns the exact generic timeout payload",()=>{for(const answer of ANSWERS){const h=mount({task:taskFor(answer)});assert.equal(h.deadline.ms,5500);h.triggerDeadline();assert.deepEqual(h.finishes,[{correct:false,result:{detail:"時間切れです。脳は定時退社しました。",answerLabel:answer}}]);assert.equal(h.api.inspect().result,"timeout");assert.equal(h.api.inspect().feedbackStages,1)}});
test("normal and reduced retain feedback with zero continuous frames",()=>{for(const reduced of[false,true]){const h=mount({reduced});h.api.choose(h.task.answer);assert.equal(h.api.inspect().reduced,reduced);assert.equal(h.api.inspect().feedbackStages,1);assert.equal(h.api.inspect().frames,0)}});
test("393/402 DPR3 exposes five exact scenes in both directions without center-specific DOM",()=>{for(const answer of ANSWERS)for(const reduced of[false,true])for(const viewport of[{width:393,height:852,dpr:3},{width:402,height:874,dpr:4}]){const h=mount({task:taskFor(answer),reduced,viewport}),state=h.api.inspect(),canvas=state.canvas;assert.equal(canvas.dpr,3);assert.equal(canvas.pixelWidth,canvas.cssWidth*3);assert.equal(canvas.pixelHeight,canvas.cssHeight*3);assert.equal(h.line.children.length,0);assert.deepEqual(state.arrows,taskFor(answer).line.split(" "));for(const scene of["initial","focus","wrong","success","timeout"])assert.equal(h.api.showScene(scene),true);h.dispose()}});
test("real runtime disposal cancels deadline, listeners, QA and finish",async()=>{const owner=documentFor(),host=owner.createElement("div"),qa={},finishes=[],oldRaf=globalThis.requestAnimationFrame,oldCancel=globalThis.cancelAnimationFrame;globalThis.requestAnimationFrame=()=>{throw Error("unexpected frame")};globalThis.cancelAnimationFrame=()=>{};try{const runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(taskFor(),runtime.context);runtime.dispose();await delay(80);assert.deepEqual(finishes,[]);assert.equal(qa[ID],undefined);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(oldRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=oldRaf;if(oldCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=oldCancel}});
test("ownerDocument and source forbid raw lifetime, network, audio, asset, and center cues",()=>{const owner=documentFor(),old=globalThis.document;globalThis.document={createElement(){throw Error("global document used")}};try{const h=mount({owner});const visit=node=>{assert.equal(node.ownerDocument,owner);node.children.forEach(visit)};visit(h.host);h.dispose()}finally{if(old===undefined)delete globalThis.document;else globalThis.document=old}assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement)\b/);assert.doesNotMatch(source,/(?:\.src\s*=|url\s*\()/);assert.doesNotMatch(source,/(?:nth-child|nth-of-type|center-arrow|centerArrow|highlight)/i);assert.equal((source.match(/\.if-line\{/g)||[]).length,1)});
