#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.."&&pwd);STAMP=$(date +%Y%m%d-%H%M%S);OUT=${1:-/tmp/agetest-language-notice-trim-v1-audit-$STAMP};cd "$ROOT";[[ ! -e "$OUT" ]]||{ echo "output exists: $OUT" >&2;exit 2;};mkdir -p "$OUT";node tools/qa-browser-lanes.mjs start audit >/dev/null
ready='(async()=>{for(let i=0;i<240;i++){if(window.__NOTICE_TRIM_FIXTURE__&&document.documentElement.dataset.ready==="true")return true;await new Promise(r=>setTimeout(r,25))}throw Error("ready")})()'
nav(){ local n=$1 s=$2 m=$3 w=$4 h=$5 live=${6:-0};node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/language-notice-trim-v1.fixture.html?notice=$n&scene=$s&motion=$m&width=$w&live=$live" "$w" "$h" 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null;}
notices=(0 1 2 3);metrics=(393x852 402x874);motions=(normal reduced);scenes=(initial one-over editing exact-fit overflow missing-place-time lost-condition meaningless-deletion authored-tone-miss success timeout)
for n in "${notices[@]}";do for metric in "${metrics[@]}";do w=${metric%x*};h=${metric#*x};for m in "${motions[@]}";do for s in "${scenes[@]}";do nav "$n" "$s" "$m" "$w" "$h";node tools/qa-browser-lanes.mjs eval audit 'window.__NOTICE_TRIM_FIXTURE__.report()' >"$OUT/evidence-$n-$metric-$s-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/notice$n-$metric-$s-$m.png" >/dev/null;done;nav "$n" initial "$m" "$w" "$h" 1;node tools/qa-browser-lanes.mjs eval audit '(()=>{const f=window.__NOTICE_TRIM_FIXTURE__,b=f.api.elements.buttons[0];b.focus();document.body.classList.add("fixture-focus");return{focused:b===document.activeElement,state:f.api.inspect(),report:f.report()}})()' >"$OUT/focus-$n-$metric-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/focus-$n-$metric-$m.png" >/dev/null;done;done;done
for metric in 390x844 430x932;do w=${metric%x*};h=${metric#*x};for n in "${notices[@]}";do for m in "${motions[@]}";do for s in initial success;do nav "$n" "$s" "$m" "$w" "$h";node tools/qa-browser-lanes.mjs eval audit 'window.__NOTICE_TRIM_FIXTURE__.report()' >"$OUT/boundary-$n-$metric-$s-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/boundary-notice$n-$metric-$s-$m.png" >/dev/null;done;done;done;done
cue_js='(()=>{const f=window.__NOTICE_TRIM_FIXTURE__,buttons=f.api.elements.buttons,styles=buttons.map(b=>{const s=getComputedStyle(b);return{className:b.className,border:s.border,bg:s.backgroundImage,color:s.color,height:b.getBoundingClientRect().height,answer:b.getAttribute("data-answer"),correct:b.getAttribute("data-correct"),solution:b.getAttribute("data-solution")}}),task=f.task;return{notice:f.notice,rackOrder:task.rackOrder,chipOrder:task.chips.map(c=>c.id),validMasks:task.proof.validMasks,styles,state:f.api.inspect(),report:f.report()}})()'
for n in "${notices[@]}";do nav "$n" initial normal 402 874;node tools/qa-browser-lanes.mjs eval audit "$cue_js" >"$OUT/no-cue-$n.json";done

touch_js='(async()=>{const f=window.__NOTICE_TRIM_FIXTURE__,api=f.api,wait=ms=>new Promise(r=>setTimeout(r,ms)),wanted=new Set(f.task.chips.filter((_,i)=>f.task.proof.exactFitMask&(1<<i)).map(c=>c.id)),removed=[],press=b=>b.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerType:"touch",pointerId:71,isPrimary:true}));for(const id of f.task.rackOrder)if(!wanted.has(id)){const i=f.task.chips.findIndex(c=>c.id===id),b=api.elements.buttons[i];press(b);removed.push({id,state:api.inspect()});await wait(f.motion==="reduced"?115:190)}const before=api.inspect(),submit=api.elements.submitButton;submit.dispatchEvent(new MouseEvent("click",{bubbles:true,cancelable:true,detail:1}));const locked=api.inspect();await wait(f.motion==="reduced"?130:230);const report=f.report();return{status:report.status,notice:f.notice,motion:f.motion,removed,before,locked,after:api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,targets:report.targets,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()'
for n in "${notices[@]}";do for m in "${motions[@]}";do nav "$n" initial "$m" 402 874 1;node tools/qa-browser-lanes.mjs eval audit "$touch_js" >"$OUT/touch-$n-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/touch-success-$n-$m.png" >/dev/null;done;done
keyboard_js='(async()=>{const f=window.__NOTICE_TRIM_FIXTURE__,api=f.api,stage=api.elements.stage,wait=ms=>new Promise(r=>setTimeout(r,ms)),wanted=new Set(f.task.chips.filter((_,i)=>f.task.proof.exactFitMask&(1<<i)).map(c=>c.id)),keys=[],key=k=>{stage.dispatchEvent(new KeyboardEvent("keydown",{key:k,bubbles:true,cancelable:true}));keys.push(k)};api.elements.buttons[api.inspect().selected].focus();for(const id of f.task.rackOrder){const target=f.task.chips.findIndex(c=>c.id===id);let guard=0;while(api.inspect().selected!==target&&guard++<12)key("ArrowRight");if(!wanted.has(id)){key(" ");await wait(f.motion==="reduced"?115:190)}}const before=api.inspect();api.elements.submitButton.focus();api.elements.submitButton.click();const locked=api.inspect();await wait(f.motion==="reduced"?130:230);const report=f.report();return{status:report.status,notice:f.notice,motion:f.motion,keys,before,locked,after:api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,focused:document.activeElement?.textContent||null,targets:report.targets,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()'
for pair in 0:normal 3:reduced;do n=${pair%:*};m=${pair#*:};nav "$n" initial "$m" 402 874 1;node tools/qa-browser-lanes.mjs eval audit "$keyboard_js" >"$OUT/keyboard-$n-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/keyboard-success-$n-$m.png" >/dev/null;done

deadline_js='(async()=>{const f=window.__NOTICE_TRIM_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms));f.api.toggle(3);await wait(f.motion==="reduced"?115:190);const before=f.api.inspect();f.runtime.context.setDeadline(180,f.api.timeout);await wait(500);const report=f.report();return{motion:f.motion,before,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()'
dispose_js='(async()=>{const f=window.__NOTICE_TRIM_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms));f.api.toggle(3);const state=f.api.inspect(),before=f.runtime.inspect();f.runtime.dispose();await wait(260);return{motion:f.motion,state,before,after:f.runtime.inspect(),disposedState:f.api.inspect(),qaPresent:Boolean(f.qa[f.game.metadata.id]),finishes:f.report().finishes}})()'
perf_js='(async()=>{const f=window.__NOTICE_TRIM_FIXTURE__,d=[];f.api.toggle(3);let p=performance.now();await new Promise(resolve=>{const tick=n=>{d.push(n-p);p=n;if(d.length===90)resolve();else requestAnimationFrame(tick)};requestAnimationFrame(tick)});const report=f.report(),runtime=f.runtime.inspect();return{status:d.length===90&&runtime.frames===0&&!report.external.length&&!report.errors.length&&report.viewport.bodyScrollWidth<=report.width?"pass":"fail",motion:f.motion,frames:d.length,averageFrameMs:d.reduce((a,b)=>a+b,0)/d.length,maxFrameMs:Math.max(...d),gameOwnedFrames:runtime.frames,state:f.api.inspect(),runtime,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()'
for m in "${motions[@]}";do nav 2 initial "$m" 402 874 1;node tools/qa-browser-lanes.mjs eval audit "$deadline_js" >"$OUT/deadline-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/deadline-$m.png" >/dev/null;nav 2 initial "$m" 402 874 1;node tools/qa-browser-lanes.mjs eval audit "$dispose_js" >"$OUT/dispose-$m.json";done
for metric in "${metrics[@]}";do w=${metric%x*};h=${metric#*x};for m in "${motions[@]}";do nav 1 initial "$m" "$w" "$h" 1;node tools/qa-browser-lanes.mjs eval audit "$perf_js" >"$OUT/performance-$metric-$m.json";done;done
OUT="$OUT" python - <<'PY'
from pathlib import Path
from PIL import Image,ImageChops,ImageStat
import json,math,os
root=Path(os.environ['OUT']);notices=range(4);metrics=['393x852','402x874'];motions=['normal','reduced'];scenes=['initial','one-over','editing','exact-fit','overflow','missing-place-time','lost-condition','meaningless-deletion','authored-tone-miss','success','timeout'];expected={'initial':None,'one-over':None,'editing':None,'exact-fit':None,'overflow':'overflow','missing-place-time':'missing-place-time','lost-condition':'lost-condition','meaningless-deletion':'meaningless-deletion','authored-tone-miss':'authored-tone-miss','success':'success','timeout':'timeout'};rows=[];fail=[]
for n in notices:
 for metric in metrics:
  for scene in scenes:
   a=Image.open(root/f'notice{n}-{metric}-{scene}-normal.png').convert('RGB');b=Image.open(root/f'notice{n}-{metric}-{scene}-reduced.png').convert('RGB');d=ImageChops.difference(a,b);stat=ImageStat.Stat(d);rows.append({'key':f'{n}-{metric}-{scene}','size':[a.width,a.height],'mae':round(sum(stat.mean)/3,3),'normalizedRMSE':round(math.sqrt(sum(v*v for v in stat.rms)/3)/255,6),'changed':round(sum(px!=(0,0,0) for px in d.getdata())/(a.width*a.height),5)})
   for m in motions:
    e=json.loads((root/f'evidence-{n}-{metric}-{scene}-{m}.json').read_text());s=e['state'];geometry=s['outcome']==expected[scene] and (scene!='exact-fit' or s['evaluation']['width']==e['task']['capacity']) and (scene!='one-over' or s['evaluation']['width']==e['task']['capacity']+1)
    if e['status']!='pass' or e['dpr']!=3 or e['errors'] or e['external'] or e['viewport']['bodyScrollWidth']>e['width'] or min(t['height'] for t in e['targets'])<44 or min(t['width'] for t in e['targets'])<44 or not geometry:fail.append(f'evidence {n} {metric} {scene} {m}')
for n in notices:
 for metric in metrics:
  for m in motions:
   e=json.loads((root/f'focus-{n}-{metric}-{m}.json').read_text())
   if not e['focused'] or e['report']['status']!='pass' or e['report']['viewport']['bodyScrollWidth']>e['report']['width'] or min(t['height'] for t in e['report']['targets'])<44 or min(t['width'] for t in e['report']['targets'])<44:fail.append(f'focus {n} {metric} {m}')
 e=json.loads((root/f'no-cue-{n}.json').read_text());style=e['styles'][0]
 if e['rackOrder']==e['chipOrder'] or any(x['className']!=style['className'] or x['border']!=style['border'] or x['bg']!=style['bg'] or x['color']!=style['color'] or x['answer'] or x['correct'] or x['solution'] for x in e['styles']):fail.append(f'cue {n}')
for n in notices:
 for m in motions:
  e=json.loads((root/f'touch-{n}-{m}.json').read_text())
  if not(e['status']=='pass' and e['before']['evaluation']['outcome']=='success' and e['before']['evaluation']['width']==e['before']['evaluation']['preview']['capacity'] and e['locked']['done'] and len(e['finishes'])==1 and e['finishes'][0]['correct'] and min(t['height'] for t in e['targets'])>=44 and not e['overflow'] and not e['external'] and not e['errors']):fail.append(f'touch {n} {m}')
for n,m in [(0,'normal'),(3,'reduced')]:
 e=json.loads((root/f'keyboard-{n}-{m}.json').read_text())
 if not(e['before']['evaluation']['outcome']=='success' and e['locked']['done'] and len(e['finishes'])==1 and e['finishes'][0]['correct'] and not e['overflow'] and not e['errors']):fail.append(f'keyboard {n} {m}')
for m in motions:
 e=json.loads((root/f'deadline-{m}.json').read_text())
 if not(e['after']['outcome']=='timeout' and len(e['finishes'])==1 and all(e['before'][k]==e['after'][k] for k in ['active','selected','history']) and e['before']['evaluation']==e['after']['evaluation']):fail.append(f'deadline {m}')
 e=json.loads((root/f'dispose-{m}.json').read_text())
 if not(e['after']['disposed'] and e['after']['timeouts']==0 and e['after']['listeners']==0 and not e['qaPresent'] and not e['finishes']):fail.append(f'dispose {m}')
for metric in metrics:
 for m in motions:
  e=json.loads((root/f'performance-{metric}-{m}.json').read_text())
  if not(e['status']=='pass' and e['frames']==90 and e['gameOwnedFrames']==0 and not e['overflow'] and not e['external'] and not e['errors']):fail.append(f'performance {metric} {m}')
for metric in ['390x844','430x932']:
 w,h=map(int,metric.split('x'))
 for n in notices:
  for m in motions:
   for scene in ['initial','success']:
    e=json.loads((root/f'boundary-{n}-{metric}-{scene}-{m}.json').read_text());im=Image.open(root/f'boundary-notice{n}-{metric}-{scene}-{m}.png')
    if e['status']!='pass' or e['dpr']!=3 or e['errors'] or e['external'] or e['viewport']['bodyScrollWidth']>w or min(t['height'] for t in e['targets'])<44 or min(t['width'] for t in e['targets'])<44 or im.size!=(w*3,h*3):fail.append(f'boundary {n} {metric} {scene} {m}')
report={'status':'pass' if not fail else 'fail','canonicalViewports':[{'width':393,'height':852,'dpr':3},{'width':402,'height':874,'dpr':3}],'notices':list(notices),'states':scenes,'comparisons':len(rows),'canonicalScreenshots':len(rows)*2,'focusScreenshots':16,'boundaryScreenshots':32,'touchRoutes':8,'keyboardRoutes':2,'allDpr3':not any('evidence' in x for x in fail),'allFullResolution':all(r['size'] in ([1179,2556],[1206,2622]) for r in rows),'maxMAE':max(r['mae'] for r in rows),'maxNormalizedRMSE':max(r['normalizedRMSE'] for r in rows),'failures':fail,'rows':rows};(root/'comparison-report.json').write_text(json.dumps(report,indent=2));print(json.dumps({k:v for k,v in report.items() if k!='rows'},indent=2));raise SystemExit(bool(fail))
PY
echo "$OUT"
