import test from"node:test";
import assert from"node:assert/strict";
import{readFile}from"node:fs/promises";
import{setTimeout as delay}from"node:timers/promises";
import{performance}from"node:perf_hooks";
import{createGameRuntime}from"../src/game-kernel.js";
const moduleUrl=new URL("../src/games/language-label-jar-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8"),loaded=await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`),game=loaded.default,analyzeLayout=loaded.analyzeLayout,ID="language-label-jar-v1",LABEL_IDS=["g1","l1","b1","g2","b2"];
const generated=(index=0)=>game.generate({pick:rows=>rows[index]});
const permutations=values=>values.length<2?[values]:values.flatMap((value,index)=>permutations([...values.slice(0,index),...values.slice(index+1)]).map(rest=>[value,...rest]));
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}sync(){this.owner._className=[...this.values].join(" ")}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}toggle(value,force){const next=force===undefined?!this.values.has(value):Boolean(force);next?this.values.add(value):this.values.delete(value);this.sync();return next}}
class FakeStyle{setProperty(key,value){this[key]=String(value)}}
class FakeElement extends EventTarget{constructor(tagName,ownerDocument){super();this.tagName=tagName.toUpperCase();this.ownerDocument=ownerDocument;this.parentNode=null;this.children=[];this.attributes=new Map();this.dataset={};this.style=new FakeStyle;this.classList=new FakeClassList(this);this._className="";this._textContent="";this.type="";this.disabled=false;this.hidden=false;this.tabIndex=-1;this._slotIndices=[]}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}set textContent(value){this._textContent=String(value);this.children=[]}get textContent(){return this._textContent+this.children.map(child=>child.textContent||"").join("")}append(...nodes){for(const node of nodes){if(node?.parentNode){const at=node.parentNode.children.indexOf(node);if(at>=0)node.parentNode.children.splice(at,1)}if(node&&typeof node==="object")node.parentNode=this;this.children.push(node)}}replaceChildren(...nodes){for(const child of this.children)if(child?.parentNode===this)child.parentNode=null;this.children=[];this._textContent="";this.append(...nodes)}setAttribute(name,value){this.attributes.set(name,String(value))}getAttribute(name){return this.attributes.get(name)??null}focus(){this.ownerDocument.activeElement=this;this.dispatchEvent(new Event("focus"))}getBoundingClientRect(){const slot=this.classList.contains("llj-slot"),label=this.classList.contains("llj-label"),width=slot?88:label?64:this.ownerDocument.viewportWidth,height=slot?52:label?46:620,left=slot?20:0,top=slot?180:0;return{width,height,left,top,right:left+width,bottom:top+height}}}
function fakeDocument(){const doc={activeElement:null,viewportWidth:393,defaultView:new EventTarget};doc.createElement=tag=>new FakeElement(tag,doc);return doc}
function harness({task=generated(),reducedMotion=false,width=393,dpr=3}={}){const doc=fakeDocument(),host=doc.createElement("div"),controller=new AbortController,qa={},jobs=[],listeners=new Set,frames=new Set,finishes=[];let clock=0,disposed=false,order=0,finishCalls=0;doc.viewportWidth=width;const context={host,qa,signal:controller.signal,reducedMotion,viewport:{width,height:852,dpr},later(fn,ms){const job={fn,at:clock+Math.max(0,Number(ms)||0),order:order++,active:true};jobs.push(job);return job},setDeadline(ms,fn){return context.later(fn,ms)},frame(fn){frames.add(fn);return()=>frames.delete(fn)},listen(target,type,fn,options){target.addEventListener(type,fn,options);const row={target,type,fn,options};listeners.add(row);return()=>{target.removeEventListener(type,fn,options);listeners.delete(row)}},finish(correct,payload){finishCalls++;if(disposed||finishes.length)return false;finishes.push({correct:Boolean(correct),payload:structuredClone(payload)});return true}};game.render(task,context);const next=()=>jobs.filter(job=>job.active).sort((a,b)=>a.at-b.at||a.order-b.order)[0]||null,runTo=target=>{let job=next(),guard=0;while(job&&job.at<=target&&!disposed&&guard++<500){clock=job.at;job.active=false;job.fn();job=next()}clock=target},runFor=ms=>runTo(clock+ms),dispose=()=>{if(disposed)return;disposed=true;jobs.forEach(job=>job.active=false);frames.clear();controller.abort();for(const{target,type,fn,options}of listeners)target.removeEventListener(type,fn,options);listeners.clear()};return{doc,host,qa,context,finishes,runTo,runFor,dispose,get pendingCount(){return jobs.filter(job=>job.active).length},get frameCount(){return frames.size},get listenerCount(){return listeners.size},get finishCalls(){return finishCalls}}}
const apiOf=h=>h.qa[ID],eventWith=(type,properties={})=>{const event=new Event(type,{bubbles:true,cancelable:true});for(const[key,value]of Object.entries(properties))Object.defineProperty(event,key,{value});return event};

test("metadata is the assigned tier-two satisfying original",()=>{assert.deepEqual(game.metadata,{id:ID,introducedIn:"2.0",tier:2,flavor:"satisfying",step:1,family:"language-label-jar",category:"language"})});
test("generation selects exactly one of three finite authored pantries",()=>{for(let index=0;index<3;index++){const trace=[],task=game.generate({pick(rows){trace.push(structuredClone(rows));return rows[index]}});assert.equal(trace.length,1);assert.deepEqual(trace[0].map(row=>row.id),["amber-pantry","cream-pantry","rose-pantry"]);assert.deepEqual(Object.keys(task),["kind","prompt","help","variantId","ingredients","jars","labels","start","proof","duration","state"]);assert.equal(task.duration,20000);assert.equal(task.ingredients.length,3);assert.equal(task.jars.length,4);assert.equal(task.labels.length,5);assert.deepEqual(game.validate(task),[]);assert.doesNotThrow(()=>structuredClone(task))}});
test("hostile picker falls back finitely without changing label rules",()=>{const task=game.generate({pick(){throw Error("x")}});assert.deepEqual(task,generated(0));assert.deepEqual(game.generate({pick:()=>({id:"unknown"})}),task);assert.deepEqual(game.generate({}),task)});
test("independent enumeration proves 120 full mappings with exactly four valid",()=>{for(let row=0;row<3;row++){const task=generated(row),all=permutations(task.labels.map(label=>label.id)),valid=all.filter(slots=>analyzeLayout(task.labels,task.jars,slots).success);assert.equal(all.length,120);assert.equal(valid.length,4);assert.deepEqual(task.proof,{totalFullArrangements:120,validFullArrangements:4,invalidFullArrangements:116,placementOrders:120,everyMoveReversible:true})}});
test("all full mappings analyze totally with exact mismatch identities",()=>{const task=generated(),all=permutations(LABEL_IDS);let invalid=0;for(const slots of all){const a=analyzeLayout(task.labels,task.jars,slots),b=analyzeLayout(structuredClone(task.labels),structuredClone(task.jars),[...slots]);assert.deepEqual(a,b);assert.equal(a.filled,5);assert.equal(a.total,5);assert.equal(a.full,true);assert.ok(a.mismatches.every(index=>index>=0&&index<5));if(!a.success)invalid++}assert.equal(invalid,116)});
test("validator rejects copy, duration, rule, legend, jar picture, proof, and extras",()=>{const base=generated(),broken=structuredClone(base);Object.assign(broken,{extra:true,kind:"quiz",prompt:"答え",help:"知識",duration:1,variantId:"other"});let issues=game.validate(broken).join(" | ");for(const key of["fields","kind","copy","duration","variantId"])assert.match(issues,new RegExp(key));for(const mutate of[t=>t.ingredients[0].label="KNOWN",t=>t.jars[3].ingredients.pop(),t=>t.labels[0].ingredient="leaf",t=>t.start.reverse(),t=>t.proof.validFullArrangements=1]){const task=structuredClone(base);mutate(task);assert.notDeepEqual(game.validate(task),[])}});
test("strict state validation preserves exact inventory and held-source consistency",()=>{const task=generated(),h=harness({task}),api=apiOf(h);assert.equal(api.pickLabel(task.start[2]),true);const held=api.snapshotTask();assert.deepEqual(game.validate(held),[]);for(const mutate of[t=>t.state.extra=true,t=>t.state.slots.push(null),t=>t.state.tray.push(t.state.tray[0]),t=>t.state.held.before.tray.reverse(),t=>t.state.held.index=99,t=>t.state.moves=-1]){const bad=structuredClone(held);mutate(bad);assert.notDeepEqual(game.validate(bad),[])}h.dispose()});
test("render owns warm finite DOM with three legend cards, four jars, five slots and labels",()=>{const h=harness(),api=apiOf(h),s=api.inspect();assert.equal(api.elements.stage.ownerDocument,h.doc);assert.equal(api.elements.legend.children.length,3);assert.equal(api.elements.jarCards.length,4);assert.equal(api.elements.slotButtons.length,5);assert.equal(api.elements.labelButtons.size,5);assert.equal(api.elements.jarCards[3]._slotIndices.length,2);assert.deepEqual(s.slots,[null,null,null,null,null]);assert.equal(s.tray.length,5);assert.equal(s.held,null);assert.equal(s.remaining,20);assert.equal(s.analysis.success,false);h.dispose()});
test("pointer-style press and jar release use one reversible placement path",()=>{const h=harness(),api=apiOf(h),id=api.inspect().tray[0],button=api.elements.labelButtons.get(id),slot=api.elements.slotButtons[0];button.dispatchEvent(eventWith("pointerdown",{pointerId:7,pointerType:"touch",clientX:40,clientY:40}));assert.equal(api.inspect().drag.id,id);h.doc.defaultView.dispatchEvent(eventWith("pointerup",{pointerId:7,pointerType:"touch",clientX:50,clientY:200}));assert.equal(api.inspect().slots[0],id);assert.equal(api.inspect().moves,1);assert.equal(api.inspect().snapStage,0);h.runFor(160);assert.equal(api.inspect().snapStage,2);h.dispose()});
test("tap pickup and occupied drop exchange labels without loss",()=>{const h=harness(),api=apiOf(h),[a,b]=api.inspect().tray;assert.equal(api.pickLabel(a),true);assert.equal(api.dropHeld(0),true);h.runFor(160);assert.equal(api.pickLabel(b),true);assert.equal(api.dropHeld(0),true);h.runFor(160);let s=api.inspect();assert.equal(s.slots[0],b);assert.ok(s.tray.includes(a));assert.deepEqual([...s.slots.filter(Boolean),...s.tray].sort(),[...LABEL_IDS].sort());assert.equal(api.pickLabel(a),true);assert.equal(api.dropHeld(0),true);h.runFor(160);s=api.inspect();assert.equal(s.slots[0],a);assert.ok(s.tray.includes(b));h.dispose()});
test("cancel restores exact slot and tray order",()=>{const h=harness(),api=apiOf(h),before=api.inspect();assert.equal(api.pickLabel(before.tray[3]),true);assert.equal(api.cancelHeld(),true);const after=api.inspect();assert.deepEqual(after.slots,before.slots);assert.deepEqual(after.tray,before.tray);assert.equal(after.moves,0);h.dispose()});
test("full mismatch stays playable with gentle exact mismatch cue",()=>{const task=generated(),invalid=permutations(LABEL_IDS).find(slots=>{const a=analyzeLayout(task.labels,task.jars,slots);return!a.success&&a.mismatches.length>=3}),h=harness({task}),api=apiOf(h);assert.equal(api.applyLayout(invalid,[],5),true);let s=api.inspect();assert.equal(s.analysis.full,true);assert.equal(s.analysis.success,false);assert.ok(s.analysis.mismatches.length>=3);assert.equal(s.note,"絵を見直して、入れ替えられます");assert.equal(s.done,false);const first=s.slots[0];assert.equal(api.pickLabel(first),true);assert.equal(api.dropHeld(1),true);h.runFor(160);assert.equal(api.inspect().moves,6);assert.equal(api.inspect().done,false);h.dispose()});
test("all 120 placement orders can reach a valid mapping",()=>{const task=generated(),valid=permutations(LABEL_IDS).find(slots=>analyzeLayout(task.labels,task.jars,slots).success);for(const order of permutations([0,1,2,3,4])){const h=harness({task}),api=apiOf(h);for(const index of order){assert.equal(api.pickLabel(valid[index]),true);assert.equal(api.dropHeld(index),true);h.runFor(160)}h.runFor(220);assert.equal(api.inspect().outcome,"success");assert.equal(h.finishes.length,1);assert.equal(h.finishes[0].correct,true);h.dispose()}});
test("normal success waits for tracked snap and commits exactly once",()=>{const task=generated(),valid=permutations(LABEL_IDS).find(slots=>analyzeLayout(task.labels,task.jars,slots).success),h=harness({task}),api=apiOf(h);api.applyLayout([valid[0],valid[1],valid[2],valid[3],null],[valid[4]],4);assert.equal(api.pickLabel(valid[4]),true);assert.equal(api.dropHeld(4),true);assert.equal(api.inspect().busy,true);h.runFor(159);assert.equal(h.finishes.length,0);h.runFor(1);assert.equal(api.inspect().done,true);assert.equal(api.inspect().outcome,"success");h.runFor(219);assert.equal(h.finishes.length,0);h.runFor(1);assert.equal(h.finishes.length,1);assert.equal(h.finishes[0].payload.outcome,"success");assert.deepEqual(h.finishes[0].payload.state.slots,valid);assert.equal(h.finishCalls,1);assert.equal(api.completeSuccess(),false);h.dispose()});
test("keyboard arrows move focus and Space pickup-drop shares edit functions",()=>{const h=harness(),api=apiOf(h),id=api.inspect().tray[0],button=api.elements.labelButtons.get(id),slot=api.elements.slotButtons[0];button.focus();button.dispatchEvent(eventWith("keydown",{key:" "}));assert.equal(api.inspect().held.id,id);slot.focus();slot.dispatchEvent(eventWith("keydown",{key:" "}));assert.equal(api.inspect().slots[0],id);h.runFor(160);slot.focus();slot.dispatchEvent(eventWith("keydown",{key:"ArrowRight"}));assert.equal(h.doc.activeElement,api.elements.slotButtons[1]);button.focus();button.dispatchEvent(eventWith("keydown",{key:" "}));assert.equal(api.inspect().held.id,id);button.dispatchEvent(eventWith("keydown",{key:"Escape"}));assert.equal(api.inspect().held,null);assert.equal(api.inspect().slots[0],id);assert.equal(api.inspect().moves,1);h.dispose()});
test("exact 20000ms timeout retains partial layout, held label, and mapping",()=>{const h=harness(),api=apiOf(h),id=api.inspect().tray[0];api.pickLabel(id);const before=api.inspect();h.runTo(19999);assert.equal(h.finishes.length,0);h.runTo(20000);assert.equal(h.finishes.length,1);const result=h.finishes[0];assert.equal(result.correct,false);assert.equal(result.payload.outcome,"timeout");assert.deepEqual(result.payload.state.slots,before.slots);assert.deepEqual(result.payload.state.tray,before.tray);assert.deepEqual(result.payload.state.held,before.held);assert.deepEqual(result.payload.analysis,before.analysis);assert.equal(api.inspect().remaining,0);assert.equal(h.finishCalls,1);h.dispose()});
test("normal and reduced use nonzero tracked snap stills without frames",()=>{const normal=harness(),n=apiOf(normal),id=n.inspect().tray[0];n.pickLabel(id);n.dropHeld(0);assert.equal(n.inspect().snapStage,0);normal.runFor(79);assert.equal(n.inspect().snapStage,0);normal.runFor(1);assert.equal(n.inspect().snapStage,1);normal.runFor(80);assert.equal(n.inspect().snapStage,2);assert.equal(normal.frameCount,0);const reduced=harness({reducedMotion:true}),r=apiOf(reduced),rid=r.inspect().tray[0];r.pickLabel(rid);r.dropHeld(0);assert.equal(r.inspect().snapStage,1);reduced.runFor(59);assert.equal(r.inspect().snapStage,1);reduced.runFor(1);assert.equal(r.inspect().snapStage,2);assert.equal(reduced.frameCount,0);normal.dispose();reduced.dispose()});
test("plain JSON partial and held resumes reproduce exact finite state",()=>{const a=harness(),api=apiOf(a),first=api.inspect().tray[0];api.pickLabel(first);api.dropHeld(3);a.runFor(160);api.pickLabel(api.inspect().tray[1]);const saved=JSON.parse(JSON.stringify(api.snapshotTask()));assert.deepEqual(game.validate(saved),[]);const b=harness({task:saved}),bApi=apiOf(b);assert.deepEqual(bApi.inspect().slots,api.inspect().slots);assert.deepEqual(bApi.inspect().tray,api.inspect().tray);assert.deepEqual(bApi.inspect().held,api.inspect().held);assert.deepEqual(bApi.inspect().analysis,api.inspect().analysis);a.dispose();b.dispose()});
test("dispose during active drag and snap clears timers, listeners, QA, and finish",()=>{const h=harness(),api=apiOf(h),id=api.inspect().tray[0];api.pickLabel(id);api.dropHeld(0);assert.ok(h.pendingCount>=3);h.dispose();h.runTo(30000);assert.equal(h.pendingCount,0);assert.equal(h.listenerCount,0);assert.equal(h.frameCount,0);assert.deepEqual(h.finishes,[]);assert.equal(h.qa[ID],undefined);assert.equal(api.inspect().disposed,true)});
test("real kernel disposal is synchronous during reduced snap",async()=>{const doc=fakeDocument(),host=doc.createElement("div"),qa={},finishes=[],previousCancel=globalThis.cancelAnimationFrame;globalThis.cancelAnimationFrame=()=>{};try{const runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,payload)=>finishes.push({correct,payload})});game.render(generated(),runtime.context);const api=qa[ID],id=api.inspect().tray[0];api.pickLabel(id);api.dropHeld(0);runtime.dispose();await delay(180);assert.equal(qa[ID],undefined);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}});
test("300 cold renders stay finite with fixed large controls and capped work",()=>{const started=performance.now();for(let index=0;index<300;index++){const h=harness({task:generated(index%3),reducedMotion:Boolean(index%2),width:index%2?390:430,dpr:3}),api=apiOf(h);assert.equal(api.elements.slotButtons.length,5);assert.equal(api.elements.labelButtons.size,5);assert.equal(h.frameCount,0);h.dispose()}assert.ok(performance.now()-started<2200)});
test("source is ownerDocument-only, tracked, offline, audio/emoji/frame-free, and answer-attribute-free",()=>{assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement|localStorage|sessionStorage)\b/);assert.doesNotMatch(source,/data-(?:answer|correct|target|solution)/);assert.doesNotMatch(source,/\p{Extended_Pictographic}/u)});
