import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {performance} from "node:perf_hooks";
import {createGameRuntime} from "../src/game-kernel.js";
const url=new URL("../src/games/language-notice-trim-v1.js",import.meta.url),source=await readFile(url,"utf8"),load=async tag=>import(`data:text/javascript;base64,${Buffer.from(`${source}\n//${tag}`).toString("base64")}`),loaded=await load("main"),game=loaded.default,evaluate=loaded.evaluate,ID="language-notice-trim-v1",taskAt=index=>game.generate({pick:values=>values[index]});
class Classes{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean));this.sync()}sync(){this.owner._className=[...this.values].join(" ")}add(...v){v.forEach(x=>this.values.add(x));this.sync()}remove(...v){v.forEach(x=>this.values.delete(x));this.sync()}contains(v){return this.values.has(v)}toggle(v,force){const next=force===undefined?!this.values.has(v):Boolean(force);next?this.values.add(v):this.values.delete(v);this.sync();return next}}
class El extends EventTarget{constructor(tag,doc){super();this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.children=[];this.parentElement=null;this.attributes=new Map();this.dataset={};this.style={};this.classList=new Classes(this);this._className="";this._text="";this.disabled=false;this.type="";this.tabIndex=-1}set className(v){this._className=String(v);this.classList.reset(v)}get className(){return this._className}set textContent(v){this._text=String(v);this.children=[]}get textContent(){return this._text+this.children.map(c=>c.textContent||"").join("")}append(...nodes){for(const n of nodes){n.parentElement=this;this.children.push(n)}}replaceChildren(...nodes){this.children=[];this._text="";this.append(...nodes)}setAttribute(k,v){this.attributes.set(k,String(v))}getAttribute(k){return this.attributes.get(k)??null}focus(){this.ownerDocument.activeElement=this}getBoundingClientRect(){return{left:0,top:0,width:this.ownerDocument.width,height:this.tagName==="BUTTON"?44:600,right:this.ownerDocument.width,bottom:600}}}
function docFor(width=393){const view=new EventTarget(),doc={width,activeElement:null,defaultView:view};doc.createElement=tag=>new El(tag,doc);return doc}
function harness({task=taskAt(0),reduced=false,width=393,dpr=3}={}){const doc=docFor(width),host=doc.createElement("div"),qa={},controller=new AbortController(),jobs=[],listeners=new Set(),finishes=[];let clock=0,seq=0,disposed=false;host.getBoundingClientRect=()=>({width,height:852,left:0,top:0,right:width,bottom:852});const context={host,qa,signal:controller.signal,reducedMotion:reduced,viewport:{width,height:852,dpr},later(fn,ms){const job={fn,at:clock+ms,seq:seq++,active:true};jobs.push(job);return job},setDeadline(ms,fn){return context.later(fn,ms)},frame(){throw Error("frame forbidden")},listen(target,type,fn,options){target.addEventListener(type,fn,options);const row={target,type,fn,options};listeners.add(row);return()=>{target.removeEventListener(type,fn,options);listeners.delete(row)}},finish(correct,payload){if(disposed||finishes.length)return false;finishes.push({correct,payload:structuredClone(payload)});return true}};game.render(task,context);const next=()=>jobs.filter(j=>j.active).sort((a,b)=>a.at-b.at||a.seq-b.seq)[0],runTo=target=>{let j=next(),guard=0;while(j&&j.at<=target&&!disposed){if(++guard>1000)throw Error("loop");clock=j.at;j.active=false;j.fn();j=next()}clock=target},runFor=ms=>runTo(clock+ms),runAll=()=>{let j=next(),guard=0;while(j&&!disposed){if(++guard>1000)throw Error("loop");runTo(j.at);j=next()}},dispose=()=>{if(disposed)return;disposed=true;jobs.forEach(j=>j.active=false);controller.abort();for(const r of listeners)r.target.removeEventListener(r.type,r.fn,r.options);listeners.clear()};return{doc,host,qa,context,finishes,runTo,runFor,runAll,dispose,get pending(){return jobs.filter(j=>j.active).length},get listeners(){return listeners.size}}}
const api=h=>h.qa[ID],event=(type,props={})=>{const e=new Event(type,{bubbles:true,cancelable:true});for(const[k,v]of Object.entries(props))Object.defineProperty(e,k,{value:v});return e},idsFor=(task,mask)=>task.chips.filter((_,i)=>mask&(1<<i)).map(c=>c.id),setMask=(task,api,mask)=>{const wanted=new Set(idsFor(task,mask)),state=api.inspect();task.chips.forEach((chip,index)=>{if(state.active.includes(chip.id)!==wanted.has(chip.id))assert.equal(api.toggle(index),true)})};
function independent(task,ids){const set=new Set(ids),width=task.chips.reduce((n,c)=>n+(set.has(c.id)?c.width:0),0),counts={place:0,time:0,condition:0,action:0};for(const[id,slots]of Object.entries(task.authority.slotByChip))if(set.has(id))for(const slot of slots)counts[slot]++;const partial=task.authority.allOrNone.some(group=>{const n=group.filter(id=>set.has(id)).length;return n>0&&n<group.length}),tone=task.authority.tone.accepted.some(id=>set.has(id));if(width>task.capacity)return"overflow";if(!counts.place||!counts.time)return"missing-place-time";if(!counts.condition)return"lost-condition";if(!counts.action||partial)return"meaningless-deletion";if(!tone)return"authored-tone-miss";return"success"}

test("metadata is the assigned quirky tier-three original",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"2.0",tier:3,flavor:"quirky",step:1,family:"language-notice-trim",category:"language"}));
test("10000 generations remain finite strict plain authored tasks",()=>{const seen=new Set(),started=performance.now();for(let i=0;i<10000;i++){const task=taskAt(i%4);assert.deepEqual(game.validate(task),[]);assert.doesNotThrow(()=>structuredClone(task));assert.deepEqual(JSON.parse(JSON.stringify(task)),task);assert.equal(task.duration,30000);assert.equal(task.chips.length,11);assert.equal(task.proof.subsets,2048);seen.add(task.noticeId)}assert.equal(seen.size,4);assert.ok(performance.now()-started<30000)});
test("hostile and absent pick fall back once without unbounded helper use",()=>{let calls=0;const a=game.generate({pick(){calls++;throw Error("x")}}),b=game.generate({pick:()=>({noticeId:"other"})}),c=game.generate();assert.equal(calls,1);assert.deepEqual(a,taskAt(0));assert.deepEqual(b,a);assert.deepEqual(c,a)});
test("independent enumeration proves all 8192 subsets, exactly two solutions, exact fit and one over",()=>{let subsets=0;for(let index=0;index<4;index++){const task=taskAt(index),valid=[];let exact=null,oneOver=null;for(let mask=0;mask<1<<task.chips.length;mask++){const ids=idsFor(task,mask),outcome=independent(task,ids),actual=evaluate(task,ids);assert.equal(actual.outcome,outcome);if(outcome==="success"){valid.push(mask);if(actual.width===task.capacity)exact??=mask}if(actual.width===task.capacity+1&&actual.slotCounts.place&&actual.slotCounts.time&&actual.slotCounts.condition&&actual.slotCounts.action===2&&!actual.partialGroup&&actual.tone)oneOver??=mask;subsets++}assert.equal(valid.length,2);assert.deepEqual(valid,task.proof.validMasks);assert.equal(exact,task.proof.exactFitMask);assert.equal(oneOver,task.proof.oneOverMask);assert.ok(task.proof.initialWidth>task.capacity)}assert.equal(subsets,8192)});
test("authority is total finite task data and never asks real etiquette",()=>{for(let i=0;i<4;i++){const task=taskAt(i);assert.deepEqual(task.authority.requiredSlots,["place","time","condition","action"]);assert.deepEqual(Object.keys(task.authority.slotByChip).sort(),["action-a","action-b","condition","place","time"]);assert.equal(task.authority.allOrNone.length,1);assert.equal(task.authority.tone.accepted.length,1);assert.deepEqual(task.authority.precedence,["overflow","missing-place-time","lost-condition","meaningless-deletion","authored-tone-miss","success"])}});
test("validator rejects copy, widths, authority, proof, order, extras, and malformed resume",()=>{const base=taskAt(0),mutations=[t=>t.prompt="別",t=>t.capacity++,t=>t.chips[0].width++,t=>t.chips.reverse(),t=>t.authority.tone.accepted=[],t=>t.proof.solutionCount=1,t=>t.state.active.reverse(),t=>t.state.selected=99,t=>t.state.history.push(["bad"]),t=>t.extra=true];mutations.forEach((change,i)=>{const task=structuredClone(base);change(task);assert.ok(game.validate(task).length,`mutation ${i}`)});assert.ok(game.validate(null).length)});
test("render owns nodes, starts overflowing, and exposes no answer marker",()=>{const task=taskAt(0),before=structuredClone(task),h=harness({task}),a=api(h),s=a.inspect();assert.equal(s.evaluation.outcome,"overflow");assert.equal(s.evaluation.width,task.proof.initialWidth);assert.equal(s.active.length,11);assert.equal(s.dpr,3);assert.equal(h.doc.activeElement,a.elements.buttons[0]);const visit=node=>{assert.equal(node.ownerDocument,h.doc);for(const child of node.children)visit(child)};visit(h.host);for(const button of a.elements.buttons){assert.equal(button.getAttribute("data-answer"),null);assert.equal(button.getAttribute("data-correct"),null)}assert.deepEqual(task,before);h.dispose()});
test("each finite slot and action dependency changes recipient preview causally",()=>{const task=taskAt(0),h=harness({task}),a=api(h);setMask(task,a,task.proof.validMasks[0]);let s=a.inspect();assert.equal(s.evaluation.preview.pose,"approaching");for(const [id,field,pose]of[["place","place","searching"],["time","time","searching"],["condition","condition","passing"],["action-a","action","stalled"],["tone","tone","neutral"]]){const index=task.chips.findIndex(c=>c.id===id);a.toggle(index);s=a.inspect();assert.equal(s.evaluation.preview[field],false);assert.equal(s.evaluation.preview.pose,pose);a.toggle(index)}h.dispose()});
test("real pointer-down remove and restore retain stable authored order",()=>{const task=taskAt(1),h=harness({task}),a=api(h),button=a.elements.buttons[3];button.dispatchEvent(event("pointerdown",{pointerType:"touch"}));assert.equal(a.inspect().active.includes("near"),false);assert.equal(h.doc.activeElement,button);button.dispatchEvent(event("pointerdown",{pointerType:"touch"}));assert.equal(a.inspect().active.includes("near"),true);assert.deepEqual(a.inspect().active,task.chips.map(c=>c.id));assert.equal(a.inspect().history.length,2);h.dispose()});
test("undo and restore-all reverse subsets without changing authority",()=>{const h=harness(),a=api(h);a.toggle(1);a.toggle(3);const active=a.inspect().active;assert.equal(a.undo(),true);assert.notDeepEqual(a.inspect().active,active);assert.equal(a.restoreAll(),true);assert.equal(a.inspect().active.length,11);assert.equal(a.restoreAll(),false);h.dispose()});
test("keyboard arrows Space and R share toggle and focus paths",()=>{const task=taskAt(0),h=harness({task}),a=api(h),stage=a.elements.stage,nextIndex=task.chips.findIndex(chip=>chip.id===task.rackOrder[2]);stage.dispatchEvent(event("keydown",{key:"ArrowRight"}));assert.equal(a.inspect().selected,nextIndex);assert.equal(h.doc.activeElement,a.elements.buttons[nextIndex]);stage.dispatchEvent(event("keydown",{key:" "}));assert.equal(a.inspect().active.includes(task.chips[nextIndex].id),false);stage.dispatchEvent(event("keydown",{key:"r"}));assert.equal(a.inspect().active.length,11);a.elements.buttons[2].dispatchEvent(event("click",{detail:0}));assert.equal(a.inspect().active.includes("time"),false);h.dispose()});
test("all six authored classifications lock immediately and finish once with retained geometry",()=>{for(let taskIndex=0;taskIndex<4;taskIndex++){const task=taskAt(taskIndex);for(const outcome of["overflow","missing-place-time","lost-condition","meaningless-deletion","authored-tone-miss","success"]){const h=harness({task}),a=api(h),mask=outcome==="success"?task.proof.exactFitMask:task.proof.sampleMasks[outcome];setMask(task,a,mask);const before=a.inspect();assert.equal(before.evaluation.outcome,outcome);assert.equal(a.submit(),true);assert.equal(a.inspect().done,true);assert.equal(a.submit(),false);h.runAll();assert.equal(h.finishes.length,1);const finish=h.finishes[0];assert.equal(finish.correct,outcome==="success");assert.equal(finish.payload.outcome,outcome);assert.equal(finish.payload.width,before.evaluation.width);assert.deepEqual(finish.payload.active,before.active);assert.equal(finish.payload.notice,before.evaluation.preview.notice);h.dispose()}}});
test("exact-fit success retains requested tone and one-line physical width",()=>{for(let i=0;i<4;i++){const task=taskAt(i),h=harness({task}),a=api(h);setMask(task,a,task.proof.exactFitMask);const s=a.inspect();assert.equal(s.evaluation.width,task.capacity);assert.equal(s.evaluation.tone,true);assert.equal(s.evaluation.preview.fit,true);a.submit();h.runAll();assert.equal(h.finishes[0].payload.preview.pose,"approaching");h.dispose()}});
test("exact 30000ms timeout retains chips width preview selection and history",()=>{const task=taskAt(2),h=harness({task}),a=api(h);a.toggle(3);a.toggle(5);const before=a.inspect();h.runTo(29999);assert.equal(h.finishes.length,0);h.runTo(30000);assert.equal(h.finishes.length,1);const after=a.inspect(),payload=h.finishes[0].payload;assert.equal(payload.outcome,"timeout");for(const key of["active","selected","history"])assert.deepEqual(after[key],before[key]);assert.equal(payload.width,before.evaluation.width);assert.deepEqual(payload.preview,before.evaluation.preview);assert.equal(h.finishes.length,1);h.dispose()});
test("normal and reduced edits use distinct nonzero tracked preview stages without RAF",()=>{const normal=harness(),n=api(normal);n.toggle(1);assert.equal(n.inspect().previewStage,.25);normal.runFor(89);assert.equal(n.inspect().previewStage,.25);normal.runFor(1);assert.equal(n.inspect().previewStage,.65);normal.runFor(90);assert.equal(n.inspect().previewStage,1);const reduced=harness({reduced:true}),r=api(reduced);r.toggle(1);assert.equal(r.inspect().previewStage,.25);reduced.runFor(55);assert.equal(r.inspect().previewStage,.65);reduced.runFor(50);assert.equal(r.inspect().previewStage,1);normal.dispose();reduced.dispose()});
test("JSON snapshot renders identically through a fresh module and can finish",async()=>{const task=taskAt(3),first=harness({task}),a=api(first);a.toggle(3);a.toggle(5);const saved=JSON.parse(JSON.stringify(a.snapshotTask()));assert.deepEqual(game.validate(saved),[]);const fresh=(await load(`fresh-${Date.now()}`)).default;const restoreGame=globalThis.__noticeGame;globalThis.__noticeGame=fresh;try{const doc=docFor(),host=doc.createElement("div"),controller=new AbortController(),qa={},jobs=[],finishes=[],context={host,qa,signal:controller.signal,reducedMotion:true,viewport:{width:393,height:852,dpr:3},later(fn,ms){jobs.push(fn)},setDeadline(){},frame(){throw Error("frame")},listen(target,type,fn,options){target.addEventListener(type,fn,options)},finish(correct,payload){finishes.push({correct,payload})}};fresh.render(saved,context);assert.deepEqual(qa[ID].inspect().active,a.inspect().active);assert.deepEqual(qa[ID].inspect().history,a.inspect().history);setMask(saved,qa[ID],saved.proof.exactFitMask);qa[ID].submit();jobs.forEach(fn=>fn());assert.equal(finishes.length,1);assert.equal(finishes[0].correct,true);controller.abort()}finally{globalThis.__noticeGame=restoreGame;first.dispose()}});
test("showScene covers frozen browser evidence without committing finish",()=>{const h=harness(),a=api(h);for(const scene of["initial","one-over","editing","exact-fit","success","timeout","overflow","missing-place-time","lost-condition","meaningless-deletion","authored-tone-miss"]){assert.equal(a.showScene(scene),true);assert.equal(a.inspect().scene,scene)}assert.equal(a.showScene("other"),false);assert.deepEqual(h.finishes,[]);h.dispose()});
test("dispose during preview and feedback clears listeners QA timers and finish",()=>{for(const reduced of[false,true]){const h=harness({reduced}),a=api(h);a.toggle(1);a.submit();assert.ok(h.pending>=3);h.dispose();h.runTo(40000);assert.equal(h.qa[ID],undefined);assert.equal(h.listeners,0);assert.deepEqual(h.finishes,[]);assert.equal(a.inspect().disposed,true)}});
test("real kernel disposal leaves no notice work alive",async()=>{const doc=docFor(),host=doc.createElement("div"),qa={},finishes=[],previous=globalThis.cancelAnimationFrame;globalThis.cancelAnimationFrame=()=>{};try{const runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,payload)=>finishes.push({correct,payload})});game.render(taskAt(0),runtime.context);qa[ID].toggle(1);runtime.dispose();await delay(180);assert.equal(qa[ID],undefined);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{previous===undefined?delete globalThis.cancelAnimationFrame:globalThis.cancelAnimationFrame=previous}});
test("390-430 ownership, DPR cap, 44px targets and bounded cold rendering",()=>{const started=performance.now();for(let i=0;i<500;i++){const h=harness({task:taskAt(i%4),width:i%2?390:430,dpr:5,reduced:Boolean(i%2)}),a=api(h),s=a.inspect();assert.equal(s.dpr,3);assert.ok(s.targetHeights.every(height=>height>=44));assert.equal(a.elements.buttons.length,11);h.dispose()}assert.ok(performance.now()-started<2500)});
test("source is ownerDocument-only, finite, tracked, offline, audio-free, and advice-free",()=>{assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement|localStorage|sessionStorage|indexedDB)\b/);assert.doesNotMatch(source,/https?:\/\//);assert.doesNotMatch(source,/[\p{Extended_Pictographic}]/u);assert.doesNotMatch(source,/礼儀|マナー|安全|医療|緊急|公共|正しい敬語/);assert.doesNotMatch(source,/data-(?:answer|correct|solution|target)/)});
