import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";
const moduleUrl=new URL("../src/games/memory-missing-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8"),legacySource=await readFile(new URL("../app.js",import.meta.url),"utf8"),game=(await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`)).default,ID="memory-missing-v1",POOL=["🍇","鍵","傘","月","猫","靴","山","時計","魚","本"];
const fixedTask=(shown=["🍇","鍵","傘","月","猫"],answer="靴",options=["猫","靴","鍵","月"])=>({kind:"flashChoice",prompt:"なかったものを選んで",help:"まず5つを覚えてください。",shown:[...shown],options:[...options],answer,duration:7500});
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}sync(){this.owner._className=[...this.values].join(" ")}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}toggle(value,force){const next=force===undefined?!this.values.has(value):Boolean(force);next?this.values.add(value):this.values.delete(value);this.sync();return next}}
class FakeElement extends EventTarget{constructor(tagName,ownerDocument){super();this.tagName=tagName.toUpperCase();this.ownerDocument=ownerDocument;this.parentNode=null;this.children=[];this.attributes=new Map();this.dataset={};this.style={};this.classList=new FakeClassList(this);this._className="";this._textContent="";this.type="";this.disabled=false;this.hidden=false;this.tabIndex=-1}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}set textContent(value){this._textContent=String(value);this.children=[]}get textContent(){return this._textContent+this.children.map(child=>child.textContent||"").join("")}append(...nodes){for(const node of nodes){if(node?.parentNode){const old=node.parentNode.children.indexOf(node);if(old>=0)node.parentNode.children.splice(old,1)}if(node&&typeof node==="object")node.parentNode=this;this.children.push(node)}}replaceChildren(...nodes){this.children=[];this._textContent="";this.append(...nodes)}setAttribute(name,value){this.attributes.set(name,String(value))}getAttribute(name){return this.attributes.get(name)??null}removeAttribute(name){this.attributes.delete(name)}focus(){this.ownerDocument.activeElement=this;this.dispatchEvent(new Event("focus"))}getBoundingClientRect(){return{width:this.ownerDocument.viewportWidth,height:500,left:0,top:0,right:this.ownerDocument.viewportWidth,bottom:500}}}
function fakeDocument(){const doc={activeElement:null,viewportWidth:393,defaultView:new EventTarget()};doc.createElement=tag=>new FakeElement(tag,doc);return doc}
function harness({task=fixedTask(),reducedMotion=false,width=393}={}){const doc=fakeDocument(),host=doc.createElement("div"),controller=new AbortController(),qa={},pending=[],listeners=new Set(),frames=new Set(),finishes=[];let clock=0,disposed=false,finishCalls=0,order=0;doc.viewportWidth=width;const context={host,qa,signal:controller.signal,reducedMotion,viewport:{width,height:852,dpr:3},later(fn,ms){const job={fn,at:clock+Math.max(0,Number(ms)||0),order:order++,active:true};pending.push(job);return job},setDeadline(ms,fn){return context.later(fn,ms)},frame(fn){frames.add(fn);return()=>frames.delete(fn)},listen(target,type,fn,options){target.addEventListener(type,fn,options);const row={target,type,fn,options};listeners.add(row);return()=>{target.removeEventListener(type,fn,options);listeners.delete(row)}},finish(correct,payload){finishCalls++;if(disposed||finishes.length)return false;finishes.push({correct:Boolean(correct),payload});return true}};game.render(task,context);const next=()=>pending.filter(job=>job.active).sort((a,b)=>a.at-b.at||a.order-b.order)[0]||null,runTo=target=>{let job=next(),guard=0;while(job&&job.at<=target&&!disposed&&guard++<100){clock=job.at;job.active=false;job.fn();job=next()}clock=target},runFor=ms=>runTo(clock+ms),dispose=()=>{if(disposed)return;disposed=true;pending.forEach(job=>job.active=false);frames.clear();controller.abort();listeners.forEach(({target,type,fn,options})=>target.removeEventListener(type,fn,options));listeners.clear()};return{context,doc,host,qa,finishes,runTo,runFor,dispose,get clock(){return clock},get pendingCount(){return pending.filter(job=>job.active).length},get frameCount(){return frames.size},get listenerCount(){return listeners.size},get finishCalls(){return finishCalls}}}
const apiOf=h=>h.qa[ID],eventWith=(type,properties={})=>{const event=new Event(type,{bubbles:true,cancelable:true});for(const[key,value]of Object.entries(properties))Object.defineProperty(event,key,{value});return event};

test("metadata identifies the published 1.0 quirky missing-item memory port",()=>{assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.0",tier:1,flavor:"quirky",step:1,family:"memory-missing",category:"memory"})});
test("current factory plus exact 5000ms renderFlashChoice and generic result semantics are the sole source",()=>{if(legacySource.includes('id:"memory-missing-v1"')){assert.match(legacySource,/const all=\["🍇","鍵","傘","月","猫","靴","山","時計","魚","本"\],shown=shuffle\(all\)\.slice\(0,5\),absent=pick\(all\.filter\(x=>!shown\.includes\(x\)\)\),others=shuffle\(shown\)\.slice\(0,3\)/);assert.match(legacySource,/options:shuffle\(\[absent,\.\.\.others\]\),answer:absent,duration:7500/)}assert.match(legacySource,/const FLASH_EXPOSURE_MS = 5000/);assert.match(legacySource,/function renderFlashChoice\(task\)[\s\S]*?items\.classList\.add\("covered"\)[\s\S]*?choices\.hidden=false[\s\S]*?startDeadline\(task\.duration,\(\)=>genericTimeout\(task\)\)/);assert.match(legacySource,/finishTask\(v===task\.answer,\{answerLabel:task\.answer\}\)/)});
test("5000 generations preserve full shuffle, absent pick, shown shuffle, and outer shuffle call order",()=>{let calls=0;const seen=new Set(),shownOrders=new Set();for(let run=0;run<5000;run++){const trace=[];let shuffleCall=0,first,third;const rotate=(values,shift)=>[...values.slice(shift%values.length),...values.slice(0,shift%values.length)],task=game.generate({shuffle(values){trace.push(["shuffle",[...values]]);shuffleCall++;const result=rotate(values,run+shuffleCall*3);if(shuffleCall===1)first=result;if(shuffleCall===2)third=result;return result},pick(values){trace.push(["pick",[...values]]);return values[(Math.floor(run/10)+run)%values.length]}}),shown=first.slice(0,5),absent=POOL.filter(value=>!shown.includes(value));calls+=trace.length;assert.deepEqual(trace[0],["shuffle",POOL]);assert.deepEqual(trace[1],["pick",absent]);assert.deepEqual(trace[2],["shuffle",shown]);assert.deepEqual(trace[3],["shuffle",[task.answer,...third.slice(0,3)]]);assert.deepEqual(Object.keys(task),["kind","prompt","help","shown","options","answer","duration"]);assert.deepEqual(task.shown,shown);assert.ok(absent.includes(task.answer));assert.equal(task.options.length,4);assert.ok(task.options.includes(task.answer));assert.ok(task.options.filter(value=>value!==task.answer).every(value=>shown.includes(value)));assert.deepEqual(game.validate(task),[]);assert.doesNotThrow(()=>structuredClone(task));seen.add(task.answer);shownOrders.add(task.shown.join("|"))}assert.equal(calls,20000);assert.equal(seen.size,10);assert.ok(shownOrders.size>=10)});
test("hostile helpers still attempt all four random calls and fall back finitely",()=>{const trace=[],task=game.generate({shuffle(values){trace.push(["shuffle",[...values]]);return null},pick(values){trace.push(["pick",[...values]]);throw new Error("hostile")}});assert.deepEqual(trace,[["shuffle",POOL],["pick",["靴","山","時計","魚","本"]],["shuffle",["🍇","鍵","傘","月","猫"]],["shuffle",["靴","🍇","鍵","傘"]]]);assert.deepEqual(task,fixedTask(["🍇","鍵","傘","月","猫"],"靴",["靴","🍇","鍵","傘"]));assert.deepEqual(game.generate({}),task)});
test("validator rejects extras, copy, changed counts, duplicates, replacement values, leaked answer, distractors, and duration",()=>{const broken={...fixedTask(),extra:true,kind:"choice",prompt:"changed",help:"changed",shown:["🍇","鍵","鍵","🙂"],options:["靴","山","時計"],answer:"🍇",duration:1},issues=game.validate(broken).join(" | ");for(const fragment of["fields","kind","prompt","help","duration","shown","answer","options"])assert.match(issues,new RegExp(fragment));assert.deepEqual(game.validate(fixedTask()),[]);assert.deepEqual(game.validate(fixedTask(["傘","月","靴","山","時計"],"猫",["猫","山","傘","時計"])),[])});
test("render starts exact five-item observation with hidden disabled choices and no option or answer cue",()=>{const h=harness(),api=apiOf(h),state=api.inspect();assert.equal(state.phase,"flash");assert.deepEqual(state.visibleShown,["🍇","鍵","傘","月","猫"]);assert.equal(state.covered,0);assert.equal(state.choicesHidden,true);assert.equal(state.disabled,4);assert.deepEqual(state.optionText,["猫","靴","鍵","月"]);assert.deepEqual(state.classes,["mmv-choice","mmv-choice","mmv-choice","mmv-choice"]);assert.equal(api.choose(1),false);assert.equal(h.doc.activeElement,api.elements.stage);h.dispose()});
test("exact 5000ms conceal atomically blanks all fronts before enabling recall",()=>{const h=harness(),api=apiOf(h);h.runTo(4999);assert.equal(api.inspect().phase,"flash");assert.deepEqual(api.inspect().visibleShown,["🍇","鍵","傘","月","猫"]);h.runTo(5000);const state=api.inspect();assert.equal(state.phase,"recall");assert.equal(state.revealed,true);assert.deepEqual(state.visibleShown,["","","","",""]);assert.equal(state.covered,5);assert.equal(state.choicesHidden,false);assert.equal(state.disabled,0);assert.equal(state.recallCopy,"さっき、なかったものは？");assert.equal(h.finishes.length,0)});
test("real touch correct selection after recall locks immediately and commits generic payload after 180ms",()=>{const h=harness(),api=apiOf(h);h.runTo(5000);api.elements.buttons[1].dispatchEvent(eventWith("pointerdown",{pointerType:"touch"}));const state=api.inspect();assert.equal(state.phase,"success");assert.equal(state.selectedValue,"靴");assert.equal(state.correct,true);assert.equal(state.disabled,4);assert.ok(state.classes[1].includes("correct"));h.runFor(179);assert.equal(h.finishes.length,0);h.runFor(1);assert.deepEqual(h.finishes,[{correct:true,payload:{answerLabel:"靴"}}]);h.runTo(12500);assert.equal(h.finishCalls,1)});
test("wrong recall selection is distinct, locks all choices, and returns generic answerLabel",()=>{const h=harness(),api=apiOf(h);h.runTo(5000);api.choose(0);const state=api.inspect();assert.equal(state.phase,"wrong");assert.equal(state.selectedValue,"猫");assert.ok(state.classes[0].includes("wrong"));assert.equal(state.disabled,4);h.runFor(180);assert.deepEqual(h.finishes,[{correct:false,payload:{answerLabel:"靴"}}]);assert.equal(h.finishCalls,1)});
test("7500ms deadline starts only at recall and expires exactly at absolute 12500ms",()=>{const h=harness(),api=apiOf(h);h.runTo(12499);assert.equal(h.finishes.length,0);assert.equal(api.inspect().phase,"recall");h.runTo(12500);assert.equal(api.inspect().phase,"timeout");assert.equal(api.inspect().covered,5);assert.deepEqual(h.finishes,[{correct:false,payload:{detail:"時間切れです。脳は定時退社しました。",answerLabel:"靴"}}]);api.timeout();assert.equal(h.finishCalls,1)});
test("a choice at absolute 12499ms locks out deadline and commits only after feedback",()=>{const h=harness(),api=apiOf(h);h.runTo(12499);api.choose(1);h.runTo(12500);assert.equal(api.inspect().phase,"success");assert.equal(h.finishes.length,0);h.runTo(12679);assert.deepEqual(h.finishes,[{correct:true,payload:{answerLabel:"靴"}}]);assert.equal(h.finishCalls,1)});
test("keyboard arrows navigate the 2x2 recall grid and native activation shares the checker",()=>{const h=harness(),api=apiOf(h);h.runTo(5000);api.focus(0);api.elements.choices.dispatchEvent(eventWith("keydown",{key:"ArrowRight"}));assert.equal(api.inspect().focused,1);api.elements.choices.dispatchEvent(eventWith("keydown",{key:"ArrowDown"}));assert.equal(api.inspect().focused,3);api.elements.buttons[3].dispatchEvent(eventWith("click",{detail:0}));assert.equal(api.inspect().selectedValue,"月");h.runFor(180);assert.deepEqual(h.finishes,[{correct:false,payload:{answerLabel:"靴"}}])});
test("reduced motion preserves exact exposure, recall deadline, and nonzero feedback with no frame",()=>{const h=harness({reducedMotion:true}),api=apiOf(h);assert.equal(api.inspect().reduced,true);h.runTo(4999);assert.equal(api.inspect().revealed,false);h.runTo(5000);api.choose(1);h.runFor(179);assert.equal(h.finishes.length,0);h.runFor(1);assert.equal(h.finishes.length,1);assert.equal(h.frameCount,0)});
test("plain cloned task resumes exact flash and recall in fresh renderers without mutation",()=>{const task=structuredClone(fixedTask(["傘","月","靴","山","時計"],"猫",["猫","山","傘","時計"])),before=structuredClone(task),a=harness({task}),b=harness({task:structuredClone(task)});a.runTo(5000);b.runTo(5000);assert.deepEqual(apiOf(a).inspect().optionText,apiOf(b).inspect().optionText);apiOf(a).choose(0);apiOf(b).choose(0);a.runFor(180);b.runFor(180);assert.deepEqual(a.finishes,b.finishes);assert.deepEqual(task,before)});
test("dispose during observation or feedback clears reveal, deadline, commit, listeners, QA, and frames",()=>{for(const afterReveal of[false,true]){const h=harness(),api=apiOf(h);if(afterReveal){h.runTo(5000);api.choose(1)}assert.ok(h.pendingCount>0);h.dispose();h.runTo(20000);assert.equal(h.pendingCount,0);assert.equal(h.listenerCount,0);assert.equal(h.frameCount,0);assert.equal(h.finishes.length,0);assert.equal(h.qa[ID],undefined);assert.equal(api.inspect().disposed,true)}});
test("real kernel disposal after recall removes feedback, deadline, listeners, and commit",async()=>{const doc=fakeDocument(),host=doc.createElement("div"),qa={},finishes=[],previousCancel=globalThis.cancelAnimationFrame;globalThis.cancelAnimationFrame=()=>{};try{const runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,payload)=>finishes.push({correct,payload})});game.render(fixedTask(),runtime.context);qa[ID].reveal();qa[ID].choose(1);assert.equal(runtime.inspect().frames,0);assert.ok(runtime.inspect().timeouts>=2);runtime.dispose();await delay(240);assert.equal(qa[ID],undefined);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}});
test("source is ownerDocument-only, tracked, offline, frame-free, asset-free, and contains no answer cue field",()=>{assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement|localStorage|sessionStorage)\b/);assert.doesNotMatch(source,/\b(?:img|canvas|src)\s*=/);assert.doesNotMatch(source,/data-(?:answer|correct|rule|category)/)});
