#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd);LANE_TOOL="$ROOT/tools/qa-browser-lanes.mjs";LANE=${QA_BROWSER_LANE:-flow};HTTP_PORT=${QA_BROWSER_HTTP_PORT:-8861};OUT="$ROOT/test/memory-missing-v1-visual";MODULE="http://127.0.0.1:$HTTP_PORT/test/memory-missing-v1.fixture.html";LEGACY="http://127.0.0.1:$HTTP_PORT/test/memory-missing-v1.legacy-fixture.html";FAMILIES=(grape key cat clock);SCENES=(initial flash recall focus wrong success timeout);MOTIONS=(normal reduced)
mkdir -p "$OUT";rm -f "$OUT"/*.png "$OUT"/*.json
nav(){ node "$LANE_TOOL" navigate "$LANE" "$1" "$2" "$3" 3 >/dev/null; };evaljs(){ node "$LANE_TOOL" eval "$LANE" "$1"; };shot(){ node "$LANE_TOOL" screenshot "$LANE" "$1" >/dev/null; };ready(){ evaljs '(async()=>{for(let i=0;i<120;i++){if(document.documentElement.dataset.ready==="true")return true;await new Promise(r=>setTimeout(r,50))}throw Error("fixture not ready")})()' >/dev/null; }
for metrics in 393x852 402x874;do
 width=${metrics%x*};height=${metrics#*x}
 for motion in "${MOTIONS[@]}";do for family in "${FAMILIES[@]}";do for scene in "${SCENES[@]}";do
  nav "$LEGACY?family=$family&scene=$scene&motion=$motion&width=$width&capture=$(date +%s%N)" "$width" "$height";ready;evaljs 'memoryMissingLegacyFixture.evidence()' > "$OUT/$metrics-$motion-$family-$scene-legacy.json";shot "$OUT/$metrics-$motion-$family-$scene-legacy.png"
  nav "$MODULE?family=$family&scene=$scene&motion=$motion&width=$width&capture=$(date +%s%N)" "$width" "$height";ready;evaljs 'memoryMissingModuleFixture.evidence()' > "$OUT/$metrics-$motion-$family-$scene-module.json";shot "$OUT/$metrics-$motion-$family-$scene-module.png"
  montage -label 'CURRENT APP' "$OUT/$metrics-$motion-$family-$scene-legacy.png" -label 'MODULE' "$OUT/$metrics-$motion-$family-$scene-module.png" -tile 2x1 -geometry +8+28 -background '#ede6f2' -fill '#382b42' -pointsize 20 "$OUT/$metrics-$motion-$family-$scene-parity.png"
 done;done;done
 nav "$MODULE?family=grape&scene=initial&motion=normal&width=$width&perf=$(date +%s%N)" "$width" "$height";ready
 evaljs '(async()=>{const deltas=[];let before=performance.now();for(let i=0;i<120;i++)await new Promise(resolve=>requestAnimationFrame(now=>{deltas.push(now-before);before=now;resolve()}));const e=memoryMissingModuleFixture.evidence(),stable=deltas.slice(5);return{viewport:e.viewport,frames:stable.length,averageFrameMs:stable.reduce((a,b)=>a+b,0)/stable.length,maxFrameMs:Math.max(...stable),over25ms:stable.filter(v=>v>25).length,state:e.state,lifecycle:e.lifecycle,runtime:e.runtime,errors:e.errors,external:e.external,overflow:e.overflow}})()' > "$OUT/$metrics-performance.json"
 evaljs '(async()=>{const before=memoryMissingModuleFixture.evidence();memoryMissingModuleFixture.dispose();await new Promise(r=>setTimeout(r,80));return{before,after:memoryMissingModuleFixture.evidence()}})()' > "$OUT/$metrics-dispose.json"
done
for metrics in 390x844 430x932;do width=${metrics%x*};height=${metrics#*x};for family in "${FAMILIES[@]}";do for implementation in legacy module;do if [[ "$implementation" == legacy ]];then url=$LEGACY;object=memoryMissingLegacyFixture;else url=$MODULE;object=memoryMissingModuleFixture;fi;nav "$url?family=$family&scene=initial&motion=normal&width=$width&boundary=$(date +%s%N)" "$width" "$height";ready;evaljs "$object.evidence()" > "$OUT/boundary-$width-$family-$implementation.json";shot "$OUT/boundary-$metrics-$family-$implementation.png";done;montage -label 'CURRENT APP' "$OUT/boundary-$metrics-$family-legacy.png" -label 'MODULE' "$OUT/boundary-$metrics-$family-module.png" -tile 2x1 -geometry +8+28 -background '#ede6f2' -fill '#382b42' -pointsize 20 "$OUT/boundary-$metrics-$family-parity.png";done;done
python - "$OUT" "$LANE" <<'PY'
import json,sys
from datetime import date
from pathlib import Path
out=Path(sys.argv[1]);lane=sys.argv[2];families=['grape','key','cat','clock'];scenes=['initial','flash','recall','focus','wrong','success','timeout'];motions=['normal','reduced'];viewports=['393x852','402x874'];expected={'grape':{'shown':['鍵','傘','月','猫','靴'],'options':['猫','🍇','鍵','月'],'answer':'🍇'},'key':{'shown':['🍇','山','時計','魚','本'],'options':['時計','本','鍵','魚'],'answer':'鍵'},'cat':{'shown':['傘','月','靴','山','時計'],'options':['猫','山','傘','時計'],'answer':'猫'},'clock':{'shown':['🍇','鍵','猫','魚','本'],'options':['魚','猫','本','時計'],'answer':'時計'}}
def load(name):return json.loads((out/name).read_text())
def payload(result):return None if result is None else {'correct':result['correct'],'payload':result['payload']}
def core(row):
 s=row['state'];return {'phase':s['phase'],'done':s['done'],'revealed':s['revealed'],'selectedIndex':s['selectedIndex'],'selectedValue':s['selectedValue'],'correct':s['correct'],'focused':s['focused'],'shownValues':s['shownValues'],'visibleShown':s['visibleShown'],'covered':s['covered'],'choicesHidden':s['choicesHidden'],'optionText':s['optionText'],'recallCopy':s['recallCopy'],'externalHelp':s['externalHelp'],'result':payload(row['result'])}
pairs=[]
for viewport in viewports:
 for motion in motions:
  for family in families:
   for scene in scenes:
    legacy=load(f'{viewport}-{motion}-{family}-{scene}-legacy.json');module=load(f'{viewport}-{motion}-{family}-{scene}-module.json');pairs.append({'viewport':viewport,'motion':motion,'family':family,'scene':scene,'legacy':legacy,'module':module,'coreEqual':core(legacy)==core(module)})
def behavior(pair):
 legacy,module,scene,family=pair['legacy'],pair['module'],pair['scene'],pair['family'];spec=expected[family];state=module['state'];task=module['task']
 if not pair['coreEqual'] or legacy['task']!=task:return False
 if task!={'kind':'flashChoice','prompt':'なかったものを選んで','help':'まず5つを覚えてください。','shown':spec['shown'],'options':spec['options'],'answer':spec['answer'],'duration':7500}:return False
 if state['shownValues']!=spec['shown'] or state['optionText']!=spec['options'] or spec['answer'] in spec['shown']:return False
 if scene in ('initial','flash'):return state['phase']=='flash' and not state['revealed'] and state['visibleShown']==spec['shown'] and state['covered']==0 and state['choicesHidden'] and state['disabled']==4 and state['selectedIndex'] is None and len(set(state['classes']))==1 and module['lifecycle']['clock']==(0 if scene=='initial' else 2500)
 if scene=='recall':return state['phase']=='recall' and state['revealed'] and state['visibleShown']==['','','','',''] and state['covered']==5 and not state['choicesHidden'] and state['disabled']==0 and state['recallCopy']=='さっき、なかったものは？' and state['externalHelp']=='さっき、なかったものは？' and module['lifecycle']['clock']==5000
 if scene=='focus':return state['phase']=='recall' and state['revealed'] and state['covered']==5 and state['focused']==1 and module['controls']['focus'] and state['selectedIndex'] is None
 if scene=='wrong':return state['phase']=='wrong' and state['done'] and state['committed'] and state['covered']==5 and not state['correct'] and state['disabled']==4 and module['controls']['keyboard'] and module['controls']['focus'] and payload(module['result'])=={'correct':False,'payload':{'answerLabel':spec['answer']}}
 if scene=='success':return state['phase']=='success' and state['done'] and state['committed'] and state['covered']==5 and state['correct'] and state['disabled']==4 and module['controls']['touch'] and payload(module['result'])=={'correct':True,'payload':{'answerLabel':spec['answer']}}
 if scene=='timeout':return state['phase']=='timeout' and state['done'] and state['committed'] and state['covered']==5 and state['disabled']==4 and payload(module['result'])=={'correct':False,'payload':{'detail':'時間切れです。脳は定時退社しました。','answerLabel':spec['answer']}} and module['result']['at']==12500
 return False
perf={v:load(f'{v}-performance.json') for v in viewports};dispose={v:load(f'{v}-dispose.json') for v in viewports};boundaries={(w,f,i):load(f'boundary-{w}-{f}-{i}.json') for w in ('390','430') for f in families for i in ('legacy','module')}
checks={'pairCount':len(pairs),'allFrozenTasksExact':all(pair['legacy']['task']==pair['module']['task'] for pair in pairs),'allCoreParity':all(pair['coreEqual'] for pair in pairs),'allBehavior':all(behavior(pair) for pair in pairs),'motionModeExact':all(pair['module']['state']['reduced']==(pair['motion']=='reduced') for pair in pairs),'allNoErrors':all(not pair[side]['errors'] for pair in pairs for side in ('legacy','module')),'allNoExternal':all(not pair[side]['external'] for pair in pairs for side in ('legacy','module')),'allNoOverflow':all(not pair[side]['overflow'] for pair in pairs for side in ('legacy','module')),'allDpr3':all(pair[side]['viewport']['dpr']==3 for pair in pairs for side in ('legacy','module')),'performancePass':all(row['frames']>=110 and row['averageFrameMs']<20 and row['maxFrameMs']<50 and row['lifecycle']['frames']==0 and row['runtime']['frames']==0 and not row['errors'] and not row['external'] and not row['overflow'] for row in perf.values()),'disposePass':all(row['after']['lifecycle']['disposed'] and row['after']['lifecycle']['pending']==0 and row['after']['lifecycle']['frames']==0 and row['after']['lifecycle']['listeners']==0 and row['after']['lifecycle']['aborted'] and row['after']['runtime']=={'disposed':True,'finished':False,'finishCalls':0,'commits':0,'timeouts':0,'frames':0,'listeners':0,'aborted':True} for row in dispose.values()),'boundaries390And430':all(row['viewport']['width']==int(width) and row['viewport']['dpr']==3 and not row['overflow'] and not row['errors'] and not row['external'] for (width,family,implementation),row in boundaries.items())}
report={'game':'memory-missing-v1','status':'pass' if all(checks.values()) else 'fail','captured':str(date.today()),'lane':{'name':lane,'tool':'tools/qa-browser-lanes.mjs'},'viewports':['393x852 DPR3','402x874 DPR3'],'families':families,'motions':motions,'scenes':scenes,'checks':checks,'performance':perf,'dispose':dispose,'boundaries':{f'{w}-{f}-{i}':row for (w,f,i),row in boundaries.items()},'pairs':pairs,'screenshots':sorted(path.name for path in out.glob('*.png'))}
(out.parent/'memory-missing-v1.browser-evidence.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'status':report['status'],'checks':checks},ensure_ascii=False))
PY
