#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd);LANE_TOOL="$ROOT/tools/qa-browser-lanes.mjs";LANE=${QA_BROWSER_LANE:-flow};HTTP_PORT=${QA_BROWSER_HTTP_PORT:-8861};OUT="$ROOT/test/memory-recipe-order-v1-visual";URL="http://127.0.0.1:$HTTP_PORT/test/memory-recipe-order-v1.fixture.html";CASES=(alpha beta delta);SCENES=(encode fold ready action1 action2 action3 focus adjacent-stuck adjacent-separated lid-lock omission duplicate success timeout);MOTIONS=(normal reduced)
mkdir -p "$OUT";rm -f "$OUT"/*.png "$OUT"/*.json
nav(){ node "$LANE_TOOL" navigate "$LANE" "$1" "$2" "$3" 3 >/dev/null; };evaljs(){ node "$LANE_TOOL" eval "$LANE" "$1"; };shot(){ node "$LANE_TOOL" screenshot "$LANE" "$1" >/dev/null; };ready(){ evaljs '(async()=>{for(let i=0;i<120;i++){if(document.documentElement.dataset.ready==="true")return true;await new Promise(r=>setTimeout(r,50))}throw Error("fixture not ready")})()' >/dev/null; }
for metrics in 393x852 402x874;do
 width=${metrics%x*};height=${metrics#*x}
 for motion in "${MOTIONS[@]}";do for caseName in "${CASES[@]}";do for scene in "${SCENES[@]}";do
  nav "$URL?case=$caseName&scene=$scene&motion=$motion&width=$width&capture=$(date +%s%N)" "$width" "$height";ready;evaljs 'memoryRecipeOrderFixture.evidence()' > "$OUT/$metrics-$motion-$caseName-$scene.json";shot "$OUT/$metrics-$motion-$caseName-$scene.png"
 done;done;done
 nav "$URL?case=alpha&scene=ready&motion=normal&width=$width&perf=$(date +%s%N)" "$width" "$height";ready
 evaljs '(async()=>{const deltas=[];let before=performance.now();for(let i=0;i<120;i++)await new Promise(resolve=>requestAnimationFrame(now=>{deltas.push(now-before);before=now;resolve()}));const e=memoryRecipeOrderFixture.evidence(),stable=deltas.slice(5);return{viewport:e.viewport,frames:stable.length,averageFrameMs:stable.reduce((a,b)=>a+b,0)/stable.length,maxFrameMs:Math.max(...stable),over25ms:stable.filter(v=>v>25).length,state:e.state,lifecycle:e.lifecycle,runtime:e.runtime,errors:e.errors,external:e.external,overflow:e.overflow}})()' > "$OUT/$metrics-performance.json"
 nav "$URL?case=alpha&scene=ready&motion=normal&width=$width&dispose=$(date +%s%N)" "$width" "$height";ready
 evaljs '(async()=>{const api=memoryRecipeOrderFixture.qa[memoryRecipeOrderFixture.game.metadata.id];api.act("lid");const before=memoryRecipeOrderFixture.evidence();memoryRecipeOrderFixture.dispose();await new Promise(r=>setTimeout(r,80));return{before,after:memoryRecipeOrderFixture.evidence()}})()' > "$OUT/$metrics-dispose.json"
done
for metrics in 390x844 430x932;do width=${metrics%x*};height=${metrics#*x};for caseName in "${CASES[@]}";do for scene in encode success;do nav "$URL?case=$caseName&scene=$scene&motion=normal&width=$width&boundary=$(date +%s%N)" "$width" "$height";ready;evaljs 'memoryRecipeOrderFixture.evidence()' > "$OUT/boundary-$width-$caseName-$scene.json";shot "$OUT/boundary-$metrics-$caseName-$scene.png";done;done;done
python - "$OUT" "$LANE" <<'PY'
import hashlib,json,sys
from datetime import date
from pathlib import Path
out=Path(sys.argv[1]);lane=sys.argv[2];cases=['alpha','beta','delta'];scenes=['encode','fold','ready','action1','action2','action3','focus','adjacent-stuck','adjacent-separated','lid-lock','omission','duplicate','success','timeout'];motions=['normal','reduced'];viewports=['393x852','402x874'];specs={'alpha':{'order':['dew','dust','fold','lid'],'layout':['dust','lid','dew','fold']},'beta':{'order':['dust','fold','dew','lid'],'layout':['dew','dust','lid','fold']},'delta':{'order':['dew','fold','dust','lid'],'layout':['dust','dew','lid','fold']}};labels={'dew':'しずく玉を注ぐ','dust':'きら粉を振る','fold':'うずべらを一周','lid':'月ぶたを閉じる'}
def load(name):return json.loads((out/name).read_text())
def result(row):
 r=row['result'];return None if r is None else {'correct':r['correct'],'reason':r['payload']['reason'],'effect':r['payload']['effect'],'completed':r['payload']['completed'],'panState':r['payload']['panState'],'correctPrefix':r['payload']['correctPrefix'],'at':r['at']}
def exact_task(row,case):
 t=row['task'];s=specs[case];return t['kind']=='recipeOrder' and t['prompt']=='ヨゾラ焼きの手順を覚えて' and t['help']=='カードが閉じたら、道具を鍋へ運んで同じ順に。' and t['order']==s['order'] and t['layout']==s['layout'] and t['encodingMs']==6000 and t['duration']==14000 and [a['id'] for a in t['actions']]==['dew','dust','fold','lid'] and len(t['proof']['actionTransitions'])==96 and len(t['proof']['finishTransitions'])==24 and len(t['proof']['layoutAudit'])==144 and t['proof']['totalActionRows']==96 and t['proof']['totalFinishRows']==24 and t['proof']['totalLayoutRows']==144 and t['proof']['allowedLayoutsPerOrder']==[8,8,8,8,8,8]
def behavior(row):
 scene=row['scene'];case=row['caseName'];s=specs[case];state=row['state'];swap=130 if row['reduced'] else 260;prefix=s['order'];base=6000
 if not exact_task(row,case) or row['cueNodes']!=0:return False
 if scene=='encode':return state['phase']=='encode' and state['orderVisible'] and state['recipeRows']==4 and state['toolsHidden'] and state['completed']==[] and row['lifecycle']['clock']==0
 if scene=='fold':return state['phase']=='folding' and state['foldStages']==2 and state['orderVisible'] and state['toolsHidden'] and row['lifecycle']['clock']==5800
 if not state['cardHidden'] or state['recipeRows']!=0 or state['orderVisible'] or state['toolsHidden']:return False
 if scene=='ready':return state['phase']=='execute' and state['completed']==[] and state['panState']=='empty' and state['disabled']==0 and row['neutralMaterials'] and row['lifecycle']['clock']==6000
 if scene=='action1':return state['phase']=='execute' and state['completed']==prefix[:1] and state['correctPrefix']==1 and state['panState']==f'mix:{prefix[0]}' and row['controls']['touchDrag'] and row['lifecycle']['clock']==base+swap
 if scene=='action2':return state['phase']=='execute' and state['completed']==prefix[:2] and state['correctPrefix']==2 and row['controls']['keyboard'] and row['lifecycle']['clock']==base+swap*2
 if scene=='action3':return state['phase']=='execute' and state['completed']==prefix[:3] and state['correctPrefix']==3 and row['lifecycle']['clock']==base+swap*3
 if scene=='focus':return state['phase']=='execute' and state['focused']==1 and row['controls']['focus'] and state['completed']==[] and row['neutralMaterials']
 if scene=='adjacent-stuck':return state['result']=={'reason':'adjacent-error','effect':'stuck','correct':False} and state['completed']==['fold'] and state['panState']=='stuck' and state['committed'] and result(row)=={'correct':False,'reason':'adjacent-error','effect':'stuck','completed':['fold'],'panState':'stuck','correctPrefix':0,'at':base+swap}
 if scene=='adjacent-separated':
  wrong=next(x for x in ['dew','dust'] if x!=prefix[0]);return state['result']=={'reason':'adjacent-error','effect':'separated','correct':False} and state['completed']==[wrong] and state['panState']=='separated' and row['controls']['keyboard'] and state['committed']
 if scene=='lid-lock':return state['result']=={'reason':'lid-lock','effect':'sealed','correct':False} and state['completed']==['lid'] and state['lidClosed'] and state['panState']=='sealed' and state['disabled']==4 and state['committed']
 if scene=='omission':return state['result']=={'reason':'omission','effect':'missing-3','correct':False} and state['completed']==prefix[:1] and state['panState']==f'mix:{prefix[0]}' and row['controls']['finish'] and state['committed']
 if scene=='duplicate':return state['result']=={'reason':'duplicate','effect':'exhausted','correct':False} and state['history']==[prefix[0],prefix[0]] and state['completed']==prefix[:1] and state['panState']==f'exhausted:{prefix[0]}' and row['controls']['keyboard'] and state['committed']
 if scene=='success':return state['result']=={'reason':'success','effect':'finished','correct':True} and state['completed']==prefix and state['correctPrefix']==4 and state['lidClosed'] and state['panState']=='finished' and row['controls']['touchDrag'] and row['controls']['keyboard'] and state['committed'] and result(row)['correct']
 if scene=='timeout':return state['result']=={'reason':'timeout','effect':'retained','correct':False} and state['completed']==prefix[:1] and state['panState']==f'mix:{prefix[0]}' and state['committed'] and result(row)['at']==20000
 return False
def cue_free(order,layout):
 rotations=lambda values:[values[i:]+values[:i] for i in range(4)]
 cyclic=layout in rotations(order);reverse=layout in rotations(list(reversed(order)));pairs={(order[i],order[(i+1)%4]) for i in range(4)};adjacent=sum((layout[i],layout[(i+1)%4]) in pairs for i in range(4));positions={value:(index//2,index%2) for index,value in enumerate(layout)};grid=sum(abs(positions[order[i]][0]-positions[order[(i+1)%4]][0])+abs(positions[order[i]][1]-positions[order[(i+1)%4]][1])==1 for i in range(4));return not cyclic and not reverse and adjacent<=1 and grid<=2
rows=[load(f'{viewport}-{motion}-{case}-{scene}.json') for viewport in viewports for motion in motions for case in cases for scene in scenes];perf={v:load(f'{v}-performance.json') for v in viewports};dispose={v:load(f'{v}-dispose.json') for v in viewports};boundaries={(w,c,s):load(f'boundary-{w}-{c}-{s}.json') for w in ('390','430') for c in cases for s in ('encode','success')}
checks={'frameCount':len(rows),'allFrozenTasksExact':all(exact_task(row,row['caseName']) for row in rows),'allBehavior':all(behavior(row) for row in rows),'allNoOrderCue':all(row['cueNodes']==0 and cue_free(row['task']['order'],row['task']['layout']) and (row['scene'] in ('encode','fold') or row['state']['recipeRows']==0 and row['state']['cardHidden']) for row in rows),'neutralReadyLayout':all(row['neutralMaterials'] and min(target['width'] for target in row['targets'])>=56 and min(target['height'] for target in row['targets'])>=56 for row in rows if row['scene'] in ('ready','focus')),'motionModeExact':all(row['state']['reduced']==row['reduced'] for row in rows) and sum(1 for row in rows if row['reduced'])==len(rows)//2,'allNoErrors':all(not row['errors'] for row in rows),'allNoExternal':all(not row['external'] for row in rows),'allNoOverflow':all(not row['overflow'] for row in rows),'allDpr3':all(row['viewport']['dpr']==3 for row in rows),'performancePass':all(row['frames']>=110 and row['averageFrameMs']<20 and row['maxFrameMs']<50 and row['lifecycle']['frames']==0 and row['runtime']['frames']==0 and not row['errors'] and not row['external'] and not row['overflow'] for row in perf.values()),'disposePass':all(row['after']['lifecycle']['disposed'] and row['after']['lifecycle']['pending']==0 and row['after']['lifecycle']['frames']==0 and row['after']['lifecycle']['listeners']==0 and row['after']['lifecycle']['aborted'] and row['after']['runtime']=={'disposed':True,'finished':False,'finishCalls':0,'commits':0,'timeouts':0,'frames':0,'listeners':0,'aborted':True} and not row['after']['errors'] for row in dispose.values()),'boundaries390And430':all(row['viewport']['width']==int(width) and row['viewport']['dpr']==3 and not row['overflow'] and not row['errors'] and not row['external'] for (width,case,scene),row in boundaries.items())}
def digest(value):return hashlib.sha256(json.dumps(value,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def audit(order,layout):
 rotations=lambda values:[values[i:]+values[:i] for i in range(4)]
 cyclic=layout in rotations(order);reverse=layout in rotations(list(reversed(order)));pairs={(order[i],order[(i+1)%4]) for i in range(4)};directed=sum((layout[i],layout[(i+1)%4]) in pairs for i in range(4));positions={value:(index//2,index%2) for index,value in enumerate(layout)};grid=sum(abs(positions[order[i]][0]-positions[order[(i+1)%4]][0])+abs(positions[order[i]][1]-positions[order[(i+1)%4]][1])==1 for i in range(4));return{'cyclicRotation':cyclic,'cyclicReverse':reverse,'directedAdjacentPairsIncludingWrap':directed,'gridAdjacentPairsIncludingWrap':grid,'allowed':not cyclic and not reverse and directed<=1 and grid<=2}
canonical={};task_hashes={}
for case in cases:
 task=next(row['task'] for row in rows if row['caseName']==case);proof=task['proof'];task_hashes[case]=digest(task);canonical[case]={'taskHash':task_hashes[case],'taskSummary':{key:task[key] for key in ('kind','prompt','help','actions','order','layout','encodingMs','duration','resume')},'proofHash':digest(proof),'proofSummary':{key:proof[key] for key in ('totalActionRows','totalFinishRows','totalLayoutRows','allowedLayoutsPerOrder','layoutPolicy','finishPolicy','resumePolicy')},'layoutAudit':audit(task['order'],task['layout'])}
state_keys=('phase','orderVisible','cardHidden','recipeRows','toolsHidden','finishHidden','history','completed','used','correctPrefix','panState','lidClosed','result','locked','disposed','committed','finishCalls','foldStages','mutationStages','focused','disabled','status','railText','panAria','reduced','dragging')
def slim_state(state):return{key:state.get(key) for key in state_keys if key in state}
def slim_frame(row,screenshot=None):
 targets=row.get('targets',[]);return{'viewport':row['viewport'],'motion':'reduced' if row['reduced'] else 'normal','case':row['caseName'],'scene':row['scene'],'taskHash':task_hashes[row['caseName']],'layoutAudit':audit(row['task']['order'],row['task']['layout']),'state':slim_state(row['state']),'controls':row.get('controls'),'result':row.get('result'),'lifecycle':row.get('lifecycle'),'runtime':row.get('runtime'),'targets':{'count':len(targets),'minWidth':min((target['width'] for target in targets),default=0),'minHeight':min((target['height'] for target in targets),default=0),'equalNeutralMaterials':row.get('neutralMaterials')},'cueNodes':row.get('cueNodes'),'errors':row.get('errors'),'external':row.get('external'),'overflow':row.get('overflow'),'screenshot':screenshot}
def slim_perf(row):return{key:(slim_state(row[key]) if key=='state' else row[key]) for key in ('viewport','frames','averageFrameMs','maxFrameMs','over25ms','state','lifecycle','runtime','errors','external','overflow')}
frame_summaries=[]
for row in rows:
 metric=f"{row['viewport']['width']}x{row['viewport']['height']}";name=f"{metric}-{'reduced' if row['reduced'] else 'normal'}-{row['caseName']}-{row['scene']}.png";frame_summaries.append(slim_frame(row,name))
screenshot_manifest=[]
for path in sorted(out.glob('*.png')):screenshot_manifest.append({'name':path.name,'bytes':path.stat().st_size,'sha256':hashlib.sha256(path.read_bytes()).hexdigest()})
report={'game':'memory-recipe-order-v1','status':'pass' if all(checks.values()) else 'fail','captured':str(date.today()),'originalGame':True,'lane':{'name':lane,'tool':'tools/qa-browser-lanes.mjs'},'viewports':['393x852 DPR3','402x874 DPR3'],'cases':cases,'motions':motions,'scenes':scenes,'checks':checks,'canonicalTasks':canonical,'performance':{key:slim_perf(value) for key,value in perf.items()},'dispose':{key:{'before':slim_frame(value['before']),'after':slim_frame(value['after'])} for key,value in dispose.items()},'boundaries':{f'{w}-{c}-{s}':slim_frame(row,f'boundary-{w}x{row["viewport"]["height"]}-{c}-{s}.png') for (w,c,s),row in boundaries.items()},'frames':frame_summaries,'screenshots':screenshot_manifest}
(out.parent/'memory-recipe-order-v1.browser-evidence.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'status':report['status'],'checks':checks,'evidenceBytes':(out.parent/'memory-recipe-order-v1.browser-evidence.json').stat().st_size},ensure_ascii=False))
PY
