import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";

const moduleUrl=new URL("../src/games/memory-path-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8"),legacySource=await readFile(new URL("../app.js",import.meta.url),"utf8"),game=(await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`)).default,ID="memory-path-v1";
const fixedTask=(path=[4,1,8])=>({kind:"memoryPath",prompt:"光る順番を覚えて",help:"あとで同じ順番にタップ。",path:[...path],duration:7200});
function seededShuffle(seed=0x10f7a){return values=>{const copy=[...values];for(let index=copy.length-1;index>0;index--){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const other=Math.floor(seed/0x100000000*(index+1));[copy[index],copy[other]]=[copy[other],copy[index]]}return copy}}
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}sync(){this.owner._className=[...this.values].join(" ")}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}toggle(value,force){const next=force===undefined?!this.values.has(value):Boolean(force);next?this.values.add(value):this.values.delete(value);this.sync();return next}}
class FakeStyle{constructor(){this.values=new Map()}setProperty(name,value){this.values.set(name,String(value))}}
class FakeElement extends EventTarget{constructor(tagName,ownerDocument){super();this.tagName=tagName.toUpperCase();this.ownerDocument=ownerDocument;this.parentNode=null;this.children=[];this.attributes=new Map();this.dataset={};this.style=new FakeStyle();this.classList=new FakeClassList(this);this._className="";this._textContent="";this.type="";this.disabled=false;this.tabIndex=-1}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}set textContent(value){this._textContent=String(value);this.children=[]}get textContent(){return this._textContent+this.children.map(child=>child.textContent||"").join("")}append(...nodes){for(const node of nodes){if(node?.parentNode){const old=node.parentNode.children.indexOf(node);if(old>=0)node.parentNode.children.splice(old,1)}if(node&&typeof node==="object")node.parentNode=this;this.children.push(node)}}replaceChildren(...nodes){this.children.forEach(node=>{if(node&&typeof node==="object")node.parentNode=null});this.children=[];this._textContent="";this.append(...nodes)}setAttribute(name,value){this.attributes.set(name,String(value))}getAttribute(name){return this.attributes.get(name)??null}focus(){this.ownerDocument.activeElement=this;this.dispatchEvent(new Event("focus"))}getBoundingClientRect(){return{left:0,top:0,width:this.ownerDocument.viewportWidth,height:420,right:this.ownerDocument.viewportWidth,bottom:420}}}
function fakeDocument(){const doc={activeElement:null,viewportWidth:393,defaultView:new EventTarget()};doc.createElement=tag=>new FakeElement(tag,doc);return doc}
function harness({task=fixedTask(),reducedMotion=false,width=393}={}){const doc=fakeDocument(),host=doc.createElement("div"),helpNode=doc.createElement("p"),controller=new AbortController(),qa={},pending=[],frames=new Set(),listeners=new Set(),finishes=[];let clock=0,disposed=false,finishCalls=0;doc.viewportWidth=width;const context={host,helpNode,qa,signal:controller.signal,reducedMotion,viewport:{width,height:852,dpr:3},now:()=>clock,later(fn,ms){const job={fn,at:clock+Math.max(0,Number(ms)||0),active:true};pending.push(job);return job},setDeadline(ms,fn){return context.later(fn,ms)},frame(fn){frames.add(fn);return()=>frames.delete(fn)},listen(target,type,fn,options){target.addEventListener(type,fn,options);const record={target,type,fn,options};listeners.add(record);return()=>{target.removeEventListener(type,fn,options);listeners.delete(record)}},finish(correct,payload){finishCalls++;if(disposed||finishes.length)return false;finishes.push({correct:Boolean(correct),payload});return true}};game.render(task,context);const next=()=>pending.filter(job=>job.active).sort((a,b)=>a.at-b.at)[0]||null,runTo=target=>{let guard=0,job=next();while(job&&job.at<=target&&!disposed&&guard++<100){clock=job.at;job.active=false;job.fn();job=next()}if(guard>=100)throw new Error("timer loop");clock=target},runFor=ms=>runTo(clock+ms),dispose=()=>{if(disposed)return;disposed=true;pending.forEach(job=>job.active=false);frames.clear();controller.abort();listeners.forEach(({target,type,fn,options})=>target.removeEventListener(type,fn,options));listeners.clear()};return{context,task,doc,host,helpNode,qa,finishes,runTo,runFor,dispose,get clock(){return clock},get pendingCount(){return pending.filter(job=>job.active).length},get listenerCount(){return listeners.size},get frameCount(){return frames.size},get finishCalls(){return finishCalls}}}
const eventWith=(type,properties={})=>{const event=new Event(type,{bubbles:true,cancelable:true});for(const[key,value]of Object.entries(properties))Object.defineProperty(event,key,{value});return event};
const apiOf=h=>h.qa[ID];

test("metadata identifies the published 1.0 classic memory port",()=>{assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.0",tier:1,flavor:"classic",step:1,family:"memory-path",category:"memory"})});
test("legacy factory is removed while current renderer constants and outcome copy remain pinned",()=>{assert.doesNotMatch(legacySource,/\{id:"memory-path-v1",version:"1\.0",category:"memory",make:/);assert.match(legacySource,/MEMORY_PATH_RECALL_MS = 5000/);assert.match(legacySource,/MEMORY_PATH_FLASH_START_MS = 600/);assert.match(legacySource,/MEMORY_PATH_FLASH_STEP_MS = 1300/);assert.match(legacySource,/MEMORY_PATH_FLASH_ON_MS = 750/);assert.match(legacySource,/classList\.remove\("chosen"\),180/);assert.match(legacySource,/順番が迷子になりました。/);assert.match(legacySource,/順番どおりです。/);assert.match(legacySource,/記憶が時間切れになりました。/)});
test("5000 generations use shuffle-all-nine then slice three, remain exact, cloneable, and valid",()=>{const shuffle=seededShuffle(),seen=new Set();for(let run=0;run<5000;run++){let received=null;const task=game.generate({shuffle(values){received=[...values];return shuffle(values)}});assert.deepEqual(received,[0,1,2,3,4,5,6,7,8]);assert.deepEqual(Object.keys(task),["kind","prompt","help","path","duration"]);assert.deepEqual(game.validate(task),[]);assert.doesNotThrow(()=>structuredClone(task));assert.equal(task.path.length,3);assert.equal(new Set(task.path).size,3);seen.add(task.path.join(""))}assert.ok(seen.size>100)});
test("hostile shuffle has one finite canonical fallback",()=>{const missing=game.generate({}),thrown=game.generate({shuffle(){throw new Error("hostile")}}),bad=game.generate({shuffle:()=>[8,8,8]});assert.deepEqual(missing,fixedTask([0,1,2]));assert.deepEqual(thrown,missing);assert.deepEqual(bad,missing)});
test("validator rejects changed shape, copy, duration, malformed paths, and timing hook",()=>{const task={...fixedTask(),extra:true,kind:"memory",prompt:"changed",help:"changed",path:[1,1,9],duration:1,recallAfterMs:0},issues=game.validate(task).join(" | ");for(const fragment of["fields","kind","prompt","help","duration","path","recallAfterMs"])assert.match(issues,new RegExp(fragment));assert.deepEqual(game.validate({...fixedTask(),recallAfterMs:4000}),[])});
test("render creates one semantic 3x3 field through host.ownerDocument",()=>{const h=harness(),api=apiOf(h);assert.equal(h.host.children.length,2);assert.equal(api.elements.buttons.length,9);assert.ok(api.elements.buttons.every(button=>button.ownerDocument===h.doc));assert.equal(api.elements.grid.getAttribute("role"),"grid");assert.deepEqual(api.elements.buttons.map(button=>button.getAttribute("aria-label")),["1行1列のマス","1行2列のマス","1行3列のマス","2行1列のマス","2行2列のマス","2行3列のマス","3行1列のマス","3行2列のマス","3行3列のマス"]);assert.equal(h.doc.activeElement,api.elements.stage);h.dispose()});
test("exact flash on/off schedule and recall-relative deadline match current legacy",()=>{const h=harness(),api=apiOf(h);assert.equal(api.inspect().help,"あとで同じ順番にタップ。");assert.equal(api.inspect().disabled,9);h.runTo(599);assert.equal(api.inspect().activeFlash,null);h.runTo(600);assert.equal(api.inspect().activeFlash,4);h.runTo(1349);assert.equal(api.inspect().activeFlash,4);h.runTo(1350);assert.equal(api.inspect().activeFlash,null);h.runTo(1899);assert.equal(api.inspect().activeFlash,null);h.runTo(1900);assert.equal(api.inspect().activeFlash,1);h.runTo(2650);assert.equal(api.inspect().activeFlash,null);h.runTo(3200);assert.equal(api.inspect().activeFlash,8);h.runTo(3950);assert.equal(api.inspect().activeFlash,null);h.runTo(4999);assert.equal(api.inspect().phase,"observe");h.runTo(5000);const state=api.inspect();assert.equal(state.phase,"recall");assert.equal(state.help,"同じ順番でタップしてください。");assert.equal(h.helpNode.textContent,"同じ順番でタップしてください。");assert.equal(state.disabled,0);assert.deepEqual(state.events.map(({type,cell,step,at})=>[type,cell,step,at]),[["flash-on",4,0,600],["flash-off",4,0,1350],["flash-on",1,1,1900],["flash-off",1,1,2650],["flash-on",8,2,3200],["flash-off",8,2,3950],["recall",null,null,5000]]);h.runTo(12199);assert.equal(h.finishes.length,0);h.runTo(12200);assert.deepEqual(h.finishes,[{correct:false,payload:{detail:"記憶が時間切れになりました。"}}])});
test("optional recallAfterMs is honored without changing generated tasks",()=>{const task={...fixedTask(),recallAfterMs:4000},h=harness({task}),api=apiOf(h);h.runTo(3999);assert.equal(api.inspect().phase,"observe");h.runTo(4000);assert.equal(api.inspect().phase,"recall");assert.equal(api.inspect().events.at(-1).at,4000);assert.equal(JSON.stringify(task),api.inspect().taskJSON);h.dispose()});
test("recall removes every flash and exposes no sequence order in tile DOM",()=>{const h=harness(),api=apiOf(h);h.runTo(5000);const state=api.inspect();assert.equal(state.activeFlash,null);assert.ok(state.classes.every(value=>value==="mpv-tile"));assert.ok(api.elements.buttons.every(button=>Object.keys(button.dataset).join(",")==="cell"));assert.ok(api.elements.buttons.every(button=>!/順|番目|答/.test(button.getAttribute("aria-label"))));assert.equal(api.elements.grid.textContent,"");h.dispose()});
test("correct taps are sequential, pulse exactly 180ms, and success quality uses render elapsed",()=>{const task=fixedTask(),h=harness({task}),api=apiOf(h);h.runTo(5000);assert.equal(api.choose(4),true);assert.equal(api.inspect().cursor,1);assert.ok(api.inspect().classes[4].includes("chosen"));h.runFor(179);assert.ok(api.inspect().classes[4].includes("chosen"));h.runFor(1);assert.equal(api.inspect().classes[4],"mpv-tile");assert.equal(api.choose(1),true);h.runFor(180);h.runTo(7000);assert.equal(api.choose(8),true);assert.equal(api.inspect().done,true);assert.deepEqual(api.inspect().entered,[4,1,8]);assert.equal(h.finishes.length,1);assert.equal(h.finishes[0].correct,true);assert.equal(h.finishes[0].payload.detail,"順番どおりです。");assert.equal(h.finishes[0].payload.quality,1-7000/9000);assert.equal(api.choose(0),false);h.runTo(12200);assert.equal(h.finishCalls,1)});
test("wrong tap fails immediately on that tile with the exact published detail",()=>{const h=harness(),api=apiOf(h);h.runTo(5000);assert.equal(api.choose(4),true);const before=h.clock;assert.equal(api.choose(2),true);assert.equal(h.clock,before);const state=api.inspect();assert.equal(state.done,true);assert.equal(state.wrongCell,2);assert.ok(state.classes[2].includes("wrong"));assert.equal(state.disabled,9);assert.deepEqual(h.finishes,[{correct:false,payload:{detail:"順番が迷子になりました。"}}]);assert.equal(api.choose(1),false);assert.equal(h.finishCalls,1)});
test("pre-recall input is locked and timeout preserves exact recall-relative wording once",()=>{const h=harness(),api=apiOf(h);assert.equal(api.choose(4),false);assert.equal(api.inspect().cursor,0);api.elements.buttons[4].dispatchEvent(eventWith("pointerdown",{pointerType:"touch"}));assert.equal(api.inspect().cursor,0);h.runTo(12200);assert.equal(api.inspect().phase,"timeout");assert.equal(api.inspect().help,"記憶が時間切れになりました。");assert.deepEqual(h.finishes,[{correct:false,payload:{detail:"記憶が時間切れになりました。"}}]);h.runFor(10000);assert.equal(h.finishCalls,1)});
test("real touch and native keyboard grid focus share sequential checking",()=>{const h=harness(),api=apiOf(h);h.runTo(5000);api.elements.buttons[4].dispatchEvent(eventWith("pointerdown",{pointerType:"touch"}));assert.equal(api.inspect().cursor,1);api.focus(4);api.elements.grid.dispatchEvent(eventWith("keydown",{key:"ArrowUp"}));assert.equal(api.inspect().focused,1);api.elements.buttons[1].dispatchEvent(eventWith("click",{detail:0}));assert.equal(api.inspect().cursor,2);api.elements.grid.dispatchEvent(eventWith("keydown",{key:"ArrowDown"}));api.elements.grid.dispatchEvent(eventWith("keydown",{key:"ArrowDown"}));api.elements.grid.dispatchEvent(eventWith("keydown",{key:"ArrowRight"}));assert.equal(api.inspect().focused,8);api.elements.buttons[8].dispatchEvent(eventWith("click",{detail:0}));assert.equal(api.inspect().done,true);assert.deepEqual(h.finishes.map(item=>item.correct),[true])});
test("reduced motion retains the same nonzero flash, pulse, recall, and deadline timings without frames",()=>{const h=harness({reducedMotion:true}),api=apiOf(h);assert.equal(h.frameCount,0);h.runTo(600);assert.equal(api.inspect().activeFlash,4);h.runTo(1350);assert.equal(api.inspect().activeFlash,null);h.runTo(5000);assert.equal(api.inspect().phase,"recall");api.choose(4);h.runFor(179);assert.ok(api.inspect().classes[4].includes("chosen"));h.runFor(1);assert.equal(api.inspect().classes[4],"mpv-tile");assert.equal(h.frameCount,0);h.runTo(12200);assert.deepEqual(h.finishes.at(-1),{correct:false,payload:{detail:"記憶が時間切れになりました。"}})});
test("plain cloned task resumes in a fresh renderer without mutation",()=>{const task=structuredClone(fixedTask([7,3,5])),before=structuredClone(task),first=harness({task}),second=harness({task:structuredClone(task)});first.runTo(3200);second.runTo(3200);assert.deepEqual(apiOf(first).inspect().events,apiOf(second).inspect().events);first.runTo(5000);second.runTo(5000);[7,3,5].forEach(cell=>{apiOf(first).choose(cell);apiOf(second).choose(cell)});assert.deepEqual(first.finishes,second.finishes);assert.deepEqual(task,before)});
test("dispose cancels all flash/recall/deadline work, listeners, and QA",()=>{const h=harness(),api=apiOf(h);assert.equal(h.pendingCount,7);assert.ok(h.listenerCount>0);h.runTo(600);h.dispose();h.runTo(20000);assert.equal(h.pendingCount,0);assert.equal(h.listenerCount,0);assert.equal(h.frameCount,0);assert.equal(h.finishes.length,0);assert.equal(h.qa[ID],undefined);assert.equal(api.inspect().disposed,true)});
test("real runtime disposal during observation leaves no timers, frames, listeners, QA, or commit",async()=>{const doc=fakeDocument(),host=doc.createElement("div"),qa={},finishes=[],previousCancel=globalThis.cancelAnimationFrame;globalThis.cancelAnimationFrame=()=>{};try{const runtime=createGameRuntime({host,qa,reducedMotion:false,viewport:{width:393,height:852,dpr:3},onFinish:(correct,payload)=>finishes.push({correct,payload})});game.render(fixedTask(),runtime.context);assert.equal(runtime.inspect().timeouts,7);assert.equal(runtime.inspect().frames,0);assert.ok(runtime.inspect().listeners>0);runtime.dispose();await delay(800);assert.equal(qa[ID],undefined);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}});
test("source uses host ownerDocument and tracked lifetime only, with no continuous RAF/network/audio/order leak",()=>{assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement)\b/);assert.doesNotMatch(source,/data-(?:order|step|answer)/);assert.doesNotMatch(source,/[\u{1F300}-\u{1FAFF}]/u)});
