import game from "../src/games/memory-missing-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";
const make=(shown,answer,options)=>({kind:"flashChoice",prompt:"なかったものを選んで",help:"まず5つを覚えてください。",shown,options,answer,duration:7500}),TASKS={grape:make(["鍵","傘","月","猫","靴"],"🍇",["猫","🍇","鍵","月"]),key:make(["🍇","山","時計","魚","本"],"鍵",["時計","本","鍵","魚"]),cat:make(["傘","月","靴","山","時計"],"猫",["猫","山","傘","時計"]),clock:make(["🍇","鍵","猫","魚","本"],"時計",["魚","猫","本","時計"])},params=new URLSearchParams(location.search),family=params.get("family")in TASKS?params.get("family"):"grape",scene=params.get("scene")||"initial",reduced=params.get("motion")==="reduced",width=Number(params.get("width"))||393,task=structuredClone(TASKS[family]),host=document.querySelector("#challenge"),resultNode=document.querySelector("#result"),label=document.querySelector("#fixture-label"),qa={},errors=[];document.body.style.width=`${width}px`;document.querySelector("#question-title").textContent=task.prompt;document.querySelector("#question-help").textContent=task.help;label.textContent=`MODULE · ${reduced?"REDUCED":"NORMAL"}`;addEventListener("error",event=>errors.push(String(event.error?.stack||event.message)));addEventListener("unhandledrejection",event=>errors.push(String(event.reason?.stack||event.reason)));
function controlled(){const controller=new AbortController(),jobs=[],listeners=new Set(),frames=new Set(),finishes=[];let clock=0,order=0,disposed=false,finishCalls=0;const later=(fn,ms)=>{const job={fn,at:clock+Math.max(0,Number(ms)||0),order:order++,active:true};jobs.push(job);return job},next=()=>jobs.filter(job=>job.active).sort((a,b)=>a.at-b.at||a.order-b.order)[0]||null,advanceTo=target=>{let job=next(),guard=0;while(job&&job.at<=target&&!disposed&&guard++<100){clock=job.at;job.active=false;job.fn();job=next()}clock=target},context={host,qa,signal:controller.signal,reducedMotion:reduced,viewport:{width,height:innerHeight,dpr:devicePixelRatio},later,setDeadline:(ms,fn)=>later(fn,ms),frame(fn){frames.add(fn);return()=>frames.delete(fn)},listen(target,type,fn,options){target.addEventListener(type,fn,options);const row={target,type,fn,options};listeners.add(row);return()=>{target.removeEventListener(type,fn,options);listeners.delete(row)}},finish(correct,payload){finishCalls++;if(disposed||finishes.length)return false;finishes.push({correct:Boolean(correct),payload:structuredClone(payload),at:clock});resultNode.textContent=`${correct?"正解":"残念"} · ${payload.detail||`正解は「${payload.answerLabel}」`}`;return true}};const dispose=()=>{if(disposed)return;disposed=true;jobs.forEach(job=>job.active=false);frames.clear();controller.abort();listeners.forEach(({target,type,fn,options})=>target.removeEventListener(type,fn,options));listeners.clear()};return{context,advanceTo,dispose,finishes,inspect:()=>({clock,disposed,finishCalls,pending:jobs.filter(job=>job.active).length,frames:frames.size,listeners:listeners.size,aborted:controller.signal.aborted})}}
const probeHost=document.createElement("div"),probeQa={},realRuntime=createGameRuntime({host:probeHost,qa:probeQa,reducedMotion:reduced,viewport:{width,height:innerHeight,dpr:devicePixelRatio},onFinish(){}});game.render(structuredClone(task),realRuntime.context);const clock=controlled();game.render(structuredClone(task),clock.context);const api=qa[game.metadata.id],answerIndex=task.options.indexOf(task.answer),wrongIndex=task.options.findIndex(value=>value!==task.answer),touch=index=>api.elements.buttons[index].dispatchEvent(new PointerEvent("pointerdown",{pointerType:"touch",bubbles:true,cancelable:true})),activate=index=>api.elements.buttons[index].dispatchEvent(new MouseEvent("click",{detail:0,bubbles:true,cancelable:true})),key=value=>api.elements.choices.dispatchEvent(new KeyboardEvent("keydown",{key:value,bubbles:true,cancelable:true}));let controls={touch:false,keyboard:false,focus:false};
if(scene==="flash")clock.advanceTo(2500);
else if(scene==="recall")clock.advanceTo(5000);
else if(scene==="focus"){clock.advanceTo(5000);api.focus(0);key("ArrowRight");controls.focus=api.inspect().focused===1}
else if(scene==="wrong"){clock.advanceTo(5000);api.focus(wrongIndex);controls.focus=api.inspect().focused===wrongIndex;activate(wrongIndex);controls.keyboard=api.inspect().selectedIndex===wrongIndex;clock.advanceTo(5180);api.elements.stage.focus({preventScroll:true})}
else if(scene==="success"){clock.advanceTo(5000);touch(answerIndex);controls.touch=api.inspect().selectedIndex===answerIndex;clock.advanceTo(5180)}
else if(scene==="timeout")clock.advanceTo(12500);
document.documentElement.dataset.ready="true";document.body.dataset.scene=scene;
window.memoryMissingModuleFixture={game,task:()=>structuredClone(task),inspect:()=>api.inspect(),advanceTo:clock.advanceTo,dispose(){clock.dispose();realRuntime.dispose()},evidence(){const resources=performance.getEntriesByType("resource").map(entry=>entry.name),external=resources.filter(name=>new URL(name,location.href).origin!==location.origin);return{implementation:"module",family,scene,reduced,task:structuredClone(task),state:api.inspect(),controls,result:clock.finishes[0]||null,lifecycle:clock.inspect(),runtime:realRuntime.inspect(),options:api.elements.buttons.map((button,index)=>({index,text:button.textContent,className:button.className,disabled:button.disabled,aria:button.getAttribute("aria-label")})),viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio,scrollWidth:document.body.scrollWidth},errors:[...errors],external,overflow:document.body.scrollWidth>innerWidth}}};
