import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {performance} from "node:perf_hooks";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";
const moduleUrl=new URL("../src/games/memory-reverse-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8"),importGame=async tag=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n//${tag}`).toString("base64")}`)).default,game=await importGame("primary"),ID="memory-reverse-v1",PROMPT="数字を逆から思い出して",HELP="4つの順番を覚えてください。",AFTER="逆の順番はどれ？";
const representative=()=>({kind:"flashChoice",prompt:PROMPT,help:HELP,afterHelp:AFTER,shown:["9","4","1","7"],options:["1 → 7 → 9 → 4","7 → 1 → 4 → 9","7 → 4 → 1 → 9","9 → 4 → 1 → 7"],answer:"7 → 1 → 4 → 9",duration:8500});
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}add(...values){values.forEach(value=>this.values.add(value));this.sync()}contains(value){return this.values.has(value)}sync(){this.owner._className=[...this.values].join(" ")}}
class FakeElement extends EventTarget{constructor(tag,ownerDocument){super();this.tagName=tag.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.attributes=new Map();this.dataset={};this._className="";this.classList=new FakeClassList(this);this.textContent="";this.hidden=false;this.disabled=false;this.type=""}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}append(...nodes){this.children.push(...nodes)}setAttribute(key,value){this.attributes.set(key,String(value))}getAttribute(key){return this.attributes.get(key)??null}focus(){this.ownerDocument.activeElement=this}getBoundingClientRect(){return{left:0,top:0,width:170,height:65,right:170,bottom:65}}}
class FakeDocument{constructor(){this.activeElement=null;this.created=[]}createElement(tag){const node=new FakeElement(tag,this);this.created.push(node);return node}}
function harness({reducedMotion=false}={}){const document=new FakeDocument(),host=new FakeElement("div",document),qa={},controller=new AbortController(),jobs=[],listeners=[],finishes=[];let disposed=false,deadline={active:false,ms:0,fn:null};const context={host,signal:controller.signal,reducedMotion,viewport:{width:390,height:844,dpr:3},qa,later:(fn,ms)=>{const job={fn,ms,active:true};jobs.push(job);return()=>job.active=false},frame:()=>{throw new Error("memory-reverse must not frame")},listen:(target,type,fn,options)=>{target.addEventListener(type,fn,options);const item={target,type,fn,options,active:true};listeners.push(item);return()=>{if(item.active){item.active=false;target.removeEventListener(type,fn,options)}}},setDeadline:(ms,fn)=>{deadline={active:true,ms,fn}},finish:(correct,result)=>{if(!disposed)finishes.push({correct,result})}};controller.signal.addEventListener("abort",()=>{disposed=true;jobs.forEach(job=>job.active=false);deadline.active=false},{once:true});return{context,host,qa,document,finishes,run(ms){const job=jobs.find(value=>value.active&&value.ms===ms);assert.ok(job,`missing ${ms}`);job.active=false;job.fn()},triggerDeadline(){if(deadline.active){deadline.active=false;deadline.fn()}},get deadline(){return deadline},get activeJobs(){return jobs.filter(value=>value.active).length},get activeListeners(){return listeners.filter(value=>value.active).length},dispose(){controller.abort();listeners.forEach(value=>{if(value.active)value.target.removeEventListener(value.type,value.fn,value.options);value.active=false})}}}
function install(){const old={document:globalThis.document,requestAnimationFrame:globalThis.requestAnimationFrame,cancelAnimationFrame:globalThis.cancelAnimationFrame};globalThis.document={createElement(){throw new Error("global document")}};globalThis.requestAnimationFrame=()=>1;globalThis.cancelAnimationFrame=()=>{};return()=>{for(const [key,value] of Object.entries(old)){if(value===undefined)delete globalThis[key];else globalThis[key]=value}}}
const recall=h=>{h.run(5000);return h.qa[ID]};

test("metadata is the published v1.0 identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.0",tier:2,flavor:"classic",step:1,family:"memory-reverse",category:"memory"}));
test("generation preserves the exact two shuffle calls and representative JSON",()=>{const calls=[],shuffle=values=>{calls.push([...values]);if(calls.length===1)return[9,4,1,7,2,8,6,3,5];return[values[2],values[0],values[3],values[1]]},actual=game.generate({shuffle});assert.deepEqual(calls,[[1,2,3,4,5,6,7,8,9],["7 → 1 → 4 → 9","9 → 4 → 1 → 7","1 → 7 → 9 → 4","7 → 4 → 1 → 9"]]);assert.deepEqual(actual,representative());assert.equal(JSON.stringify(actual),JSON.stringify(representative()))});
test("1000 generations keep exact shown selection, transforms, options, and call count",()=>{for(let seed=0;seed<1000;seed++){let calls=0;const shuffle=values=>{calls++;const a=[...values],offset=seed%a.length;return a.slice(offset).concat(a.slice(0,offset)).reverse()},task=game.generate({shuffle}),s=task.shown;assert.equal(calls,2);assert.equal(s.length,4);assert.equal(new Set(s).size,4);assert.equal(task.answer,[...s].reverse().join(" → "));assert.deepEqual(new Set(task.options),new Set([task.answer,s.join(" → "),[s[2],s[3],s[0],s[1]].join(" → "),[s[3],s[1],s[2],s[0]].join(" → ")]));assert.deepEqual(game.validate(task),[])}});
test("validator rejects changed fields, digits, transforms, order semantics, and retunes",()=>{const mutations=[v=>v.kind="choice",v=>v.prompt+="!",v=>v.help="x",v=>v.afterHelp="x",v=>v.duration=8501,v=>v.shown[0]=v.shown[1],v=>v.shown[0]="0",v=>v.answer=v.options.at(-1),v=>v.options[0]="7 → 9 → 4 → 1",v=>v.exposureMs=5000];for(const mutate of mutations){const value=structuredClone(representative());mutate(value);assert.ok(game.validate(value).length)}for(const value of [null,[],"memory",{}])assert.ok(game.validate(value).length)});
test("render creates every node from ownerDocument and starts exact flash with hidden disabled choices",()=>{const restore=install();try{const h=harness();game.render(representative(),h.context);const state=h.qa[ID].inspect();assert.ok(h.document.created.every(node=>node.ownerDocument===h.document));assert.deepEqual({phase:state.phase,status:state.status,covered:state.stripCovered,hidden:state.choicesHidden,disabled:state.buttons.map(v=>v.disabled),jobs:h.activeJobs,deadline:h.deadline.active,exposure:state.exposureMs},{phase:"FLASH",status:HELP,covered:false,hidden:true,disabled:[true,true,true,true],jobs:1,deadline:false,exposure:5000})}finally{restore()}});
test("normal and reduced preserve exact nonzero 5000ms observation",()=>{const restore=install();try{for(const reducedMotion of [false,true]){const h=harness({reducedMotion});game.render(representative(),h.context);assert.equal(h.qa[ID].choose(0),false);const api=recall(h),state=api.inspect();assert.equal(state.phase,"RECALL");assert.equal(state.stripCovered,true);assert.equal(state.status,AFTER);assert.equal(state.choicesHidden,false);assert.deepEqual(state.buttons.map(v=>v.disabled),[false,false,false,false]);assert.equal(h.deadline.ms,8500);assert.equal(h.activeJobs,0)}}finally{restore()}});
test("cover is established before choices enable and exact generated order is retained",()=>{const restore=install();try{const h=harness();game.render(representative(),h.context);const api=recall(h),state=api.inspect();assert.equal(state.stripCovered,true);assert.deepEqual(state.buttons.map(v=>v.text),representative().options);assert.deepEqual(state.buttons.map(v=>v.disabled),[false,false,false,false]);assert.equal(state.status,AFTER)}finally{restore()}});
test("wrong choice finishes immediately with exact generic result and locks",()=>{const restore=install();try{const h=harness();game.render(representative(),h.context);const api=recall(h),wrong=0;assert.notEqual(representative().options[wrong],representative().answer);assert.equal(api.choose(wrong),true);assert.deepEqual(h.finishes,[{correct:false,result:{answerLabel:representative().answer}}]);const state=api.inspect();assert.equal(state.phase,"DONE");assert.equal(state.result.answerLabel,representative().answer);assert.deepEqual(state.buttons.map(v=>v.disabled),[true,true,true,true]);assert.equal(api.choose(1),false);h.triggerDeadline();assert.equal(h.finishes.length,1)}finally{restore()}});
test("answer choice finishes immediately correct with exact generic result",()=>{const restore=install();try{const h=harness();game.render(representative(),h.context);const api=recall(h),index=representative().options.indexOf(representative().answer);assert.equal(api.choose(index),true);assert.deepEqual(h.finishes,[{correct:true,result:{answerLabel:representative().answer}}]);assert.equal(api.inspect().finishCalls,1)}finally{restore()}});
test("timeout is 8500 after recall and uses exact current generic copy",()=>{const restore=install();try{const h=harness();game.render(representative(),h.context);const api=recall(h);assert.deepEqual({ms:h.deadline.ms,active:h.deadline.active},{ms:8500,active:true});h.triggerDeadline();assert.deepEqual(h.finishes,[{correct:false,result:{detail:"時間切れです。脳は定時退社しました。",answerLabel:representative().answer}}]);assert.equal(api.inspect().phase,"DONE");assert.equal(api.inspect().finishCalls,1)}finally{restore()}});
test("deadline does not exist during observation and total expiry contract is 13500ms",()=>{const restore=install();try{const h=harness();game.render(representative(),h.context);assert.equal(h.deadline.active,false);recall(h);assert.equal(5000+h.deadline.ms,13500)}finally{restore()}});
test("focus helper exposes native focus and focus ring only during recall",()=>{const restore=install();try{const h=harness();game.render(representative(),h.context);const api=h.qa[ID];assert.equal(api.focus(0),false);recall(h);assert.equal(api.focus(2),true);assert.equal(api.inspect().focusedIndex,2);assert.match(source,/:focus-visible/)}finally{restore()}});
test("native pointer and zero-detail keyboard clicks share one choice path",()=>{const restore=install();try{for(const detail of [1,0]){const h=harness();game.render(representative(),h.context);const api=recall(h),index=representative().options.indexOf(representative().answer),button=api.elements?.buttons?.[index]||h.document.created.filter(node=>node.className==="mr-choice")[index],event=new Event("click",{bubbles:true,cancelable:true});Object.defineProperty(event,"detail",{value:detail});button.dispatchEvent(event);assert.deepEqual(h.finishes.map(v=>v.correct),[true])}}finally{restore()}});
test("plain JSON fresh resume replays exact observation then succeeds",async()=>{const restore=install();try{const saved=JSON.parse(JSON.stringify(representative())),fresh=await importGame(`resume-${Date.now()}`),h=harness({reducedMotion:true});assert.deepEqual(fresh.validate(saved),[]);fresh.render(saved,h.context);assert.equal(h.qa[ID].inspect().phase,"FLASH");recall(h);h.qa[ID].choose(saved.options.indexOf(saved.answer));assert.deepEqual(h.finishes,[{correct:true,result:{answerLabel:saved.answer}}])}finally{restore()}});
test("dispose during flash and recall clears all owned work and finish",()=>{const restore=install();try{for(const duringRecall of [false,true]){const h=harness();game.render(representative(),h.context);if(duringRecall)recall(h);h.dispose();assert.equal(h.activeJobs,0);assert.equal(h.deadline.active,false);assert.equal(h.activeListeners,0);assert.equal(h.qa[ID],undefined);assert.equal(h.finishes.length,0)}}finally{restore()}});
test("real kernel disposal leaves no surviving flash or recall work",async()=>{const restore=install();try{const document=new FakeDocument(),host=new FakeElement("div",document),finishes=[],runtime=createGameRuntime({host,onFinish:(...args)=>finishes.push(args),reducedMotion:true,viewport:{width:390,height:844,dpr:3},qa:{}});game.render(representative(),runtime.context);runtime.dispose();await delay(100);assert.equal(finishes.length,0);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{restore()}});
test("generation and strict validation remain within interaction budget",()=>{const start=performance.now();for(let i=0;i<10000;i++)assert.deepEqual(game.validate(game.generate({shuffle:values=>[...values]})),[]);assert.ok(performance.now()-start<1000)});
test("source tracks exposure, listeners, and recall deadline without RAF or forbidden APIs",()=>{assert.match(source,/context\.later\(reveal,EXPOSURE_MS\)/);assert.match(source,/context\.setDeadline\(task\.duration/);assert.match(source,/context\.listen/);assert.doesNotMatch(source,/context\.frame/);assert.doesNotMatch(source,/\bdocument\.createElement\b/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|webkitAudioContext|new Audio|localStorage|sessionStorage|indexedDB)\b/);assert.doesNotMatch(source,/[\u{1F300}-\u{1FAFF}]/u)});
test("factory copy, separators, timing, and exact timeout copy remain source-pinned",()=>{assert.match(source,/数字を逆から思い出して/);assert.match(source,/4つの順番を覚えてください。/);assert.match(source,/逆の順番はどれ？/);assert.match(source,/join\(" → "\)/);assert.match(source,/EXPOSURE_MS=5000/);assert.match(source,/DURATION=8500/);assert.match(source,/時間切れです。脳は定時退社しました。/)});
