import game from "../src/games/memory-path-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";
const TASK=Object.freeze({kind:"memoryPath",prompt:"光る順番を覚えて",help:"あとで同じ順番にタップ。",path:Object.freeze([4,1,8]),duration:7200}),params=new URLSearchParams(location.search),scene=params.get("scene")||"initial",reduced=params.get("motion")==="reduced",width=Number(params.get("width"))||393,host=document.querySelector("#challenge"),helpNode=document.querySelector("#question-help"),resultNode=document.querySelector("#result"),label=document.querySelector("#fixture-label"),qa={},errors=[];document.body.style.width=`${width}px`;label.textContent=`MODULE · ${reduced?"REDUCED":"NORMAL"}`;
addEventListener("error",event=>errors.push(String(event.error?.stack||event.message)));addEventListener("unhandledrejection",event=>errors.push(String(event.reason?.stack||event.reason)));
function controlledContext(){const controller=new AbortController(),jobs=[],listeners=new Set(),frames=new Set(),finishes=[];let clock=0,disposed=false,finishCalls=0,order=0;const later=(fn,ms)=>{const job={fn,at:clock+Math.max(0,Number(ms)||0),order:order++,active:true};jobs.push(job);return job},next=()=>jobs.filter(job=>job.active).sort((a,b)=>a.at-b.at||a.order-b.order)[0]||null,advanceTo=target=>{let job=next(),guard=0;while(job&&job.at<=target&&!disposed&&guard++<100){clock=job.at;job.active=false;job.fn();job=next()}clock=target},context={host,helpNode,qa,signal:controller.signal,reducedMotion:reduced,viewport:{width,height:innerHeight,dpr:devicePixelRatio},now:()=>clock,later,setDeadline:(ms,fn)=>later(fn,ms),frame(fn){frames.add(fn);return()=>frames.delete(fn)},listen(target,type,fn,options){target.addEventListener(type,fn,options);const row={target,type,fn,options};listeners.add(row);return()=>{target.removeEventListener(type,fn,options);listeners.delete(row)}},finish(correct,payload){finishCalls++;if(disposed||finishes.length)return false;finishes.push({correct:Boolean(correct),payload:structuredClone(payload),at:clock});resultNode.textContent=`${correct?"成功":"失敗"} · ${payload.detail}`;return true}};const dispose=()=>{if(disposed)return;disposed=true;jobs.forEach(job=>job.active=false);frames.clear();controller.abort();listeners.forEach(({target,type,fn,options})=>target.removeEventListener(type,fn,options));listeners.clear()};return{context,advanceTo,dispose,finishes,inspect:()=>({clock,disposed,finishCalls,pending:jobs.filter(job=>job.active).length,frames:frames.size,listeners:listeners.size,aborted:controller.signal.aborted})}}
const probeHost=document.createElement("div"),probeQa={},realRuntime=createGameRuntime({host:probeHost,qa:probeQa,reducedMotion:reduced,viewport:{width,height:innerHeight,dpr:devicePixelRatio},onFinish(){}});game.render(structuredClone(TASK),realRuntime.context);const clock=controlledContext();game.render(structuredClone(TASK),clock.context);const api=qa[game.metadata.id],touch=cell=>api.elements.buttons[cell].dispatchEvent(new PointerEvent("pointerdown",{pointerType:"touch",bubbles:true,cancelable:true})),key=(target,value)=>target.dispatchEvent(new KeyboardEvent("keydown",{key:value,bubbles:true,cancelable:true})),activate=cell=>api.elements.buttons[cell].dispatchEvent(new MouseEvent("click",{detail:0,bubbles:true,cancelable:true}));let controls={touch:false,keyboard:false,focus:false};
function recall(){clock.advanceTo(5000)}
if(scene==="flash1")clock.advanceTo(600);else if(scene==="flash2")clock.advanceTo(1900);else if(scene==="flash3")clock.advanceTo(3200);else if(scene!=="initial"){
 recall();if(scene==="correct1"){touch(4);controls.touch=api.inspect().cursor===1}
 else if(scene==="correct2"){touch(4);controls.touch=api.inspect().cursor===1;api.focus(4);key(api.elements.grid,"ArrowUp");controls.focus=api.inspect().focused===1;activate(1);controls.keyboard=api.inspect().cursor===2;api.elements.stage.focus({preventScroll:true})}
 else if(scene==="wrong"){touch(4);activate(0)}
 else if(scene==="success"){touch(4);api.focus(4);key(api.elements.grid,"ArrowUp");activate(1);key(api.elements.grid,"ArrowDown");key(api.elements.grid,"ArrowDown");key(api.elements.grid,"ArrowRight");controls={touch:true,focus:api.inspect().focused===8,keyboard:true};activate(8);api.elements.stage.focus({preventScroll:true})}
 else if(scene==="focus"){api.focus(4);key(api.elements.grid,"ArrowUp");controls.focus=api.inspect().focused===1}
 else if(scene==="timeout")clock.advanceTo(12200)
}
document.documentElement.dataset.ready="true";document.body.dataset.scene=scene;
window.memoryPathModuleFixture={game,task:()=>structuredClone(TASK),inspect:()=>api.inspect(),advanceTo:clock.advanceTo,dispose(){clock.dispose();realRuntime.dispose()},evidence(){const resources=performance.getEntriesByType("resource").map(entry=>entry.name),external=resources.filter(name=>new URL(name,location.href).origin!==location.origin),state=api.inspect();return{implementation:"module",scene,reduced,task:structuredClone(TASK),state,controls,result:clock.finishes[0]||null,lifecycle:clock.inspect(),runtime:realRuntime.inspect(),help:helpNode.textContent,tiles:api.elements.buttons.map((button,index)=>({cell:index,className:button.className,disabled:button.disabled,aria:button.getAttribute("aria-label")})),viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio,scrollWidth:document.body.scrollWidth},errors:[...errors],external,overflow:document.body.scrollWidth>innerWidth}}};
