import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {performance} from "node:perf_hooks";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";

const moduleUrl=new URL("../src/games/memory-phone-pin-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8"),importGame=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n//${suffix}`).toString("base64")}`)).default,game=await importGame("primary"),ID="memory-phone-pin-v1";
function helpers(initial=0x91a7){let seed=initial>>>0;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32),randomInt=(a,b)=>a+Math.floor(random()*(b-a+1)),shuffle=value=>{const array=[...value];for(let i=array.length-1;i;i--){const j=randomInt(0,i);[array[i],array[j]]=[array[j],array[i]]}return array};return{random,randomInt,shuffle,pick:value=>value[randomInt(0,value.length-1)]}}
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}toggle(value,force){const add=force===undefined?!this.values.has(value):force;add?this.values.add(value):this.values.delete(value);this.sync();return add}sync(){this.owner._className=[...this.values].join(" ")}}
class FakeStyle{constructor(){this.values=new Map()}setProperty(key,value){this.values.set(key,String(value))}}
class FakeElement extends EventTarget{constructor(tag,ownerDocument){super();this.tagName=tag.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.attributes=new Map();this.dataset={};this.style=new FakeStyle();this.classList=new FakeClassList(this);this._className="";this.textContent="";this.disabled=false;this.type="";this.tabIndex=-1}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this.children=[...nodes]}setAttribute(key,value){this.attributes.set(key,String(value))}getAttribute(key){return this.attributes.get(key)??null}focus(){this.ownerDocument.activeElement=this}get offsetWidth(){return 390}}
class FakeDocument{constructor(){this.activeElement=null;this.created=[]}createElement(tag){const node=new FakeElement(tag,this);this.created.push(node);return node}}
function harness({reducedMotion=false}={}){const document=new FakeDocument(),host=new FakeElement("div",document),qa={},controller=new AbortController(),jobs=[],listeners=[],finishes=[],delays=[],deadline={callback:null,active:false};let disposed=false,nextId=0;const later=(fn,ms)=>{const job={id:++nextId,fn,ms,active:true};jobs.push(job);delays.push(ms);return()=>{job.active=false}};const context={host,signal:controller.signal,reducedMotion,viewport:{width:390,height:844,dpr:3},qa,later,frame:()=>{throw new Error("unexpected frame")},listen:(target,type,fn,options)=>{target.addEventListener(type,fn,options);const item={target,type,fn,options,active:true};listeners.push(item);return()=>{if(item.active){item.active=false;target.removeEventListener(type,fn,options)}}},setDeadline:(ms,fn)=>{deadline.callback=fn;deadline.active=true;delays.push(ms)},finish:(correct,result)=>{if(!disposed)finishes.push({correct,result})}};controller.signal.addEventListener("abort",()=>{disposed=true;deadline.active=false;jobs.forEach(job=>job.active=false)},{once:true});const runNext=()=>{const job=jobs.find(item=>item.active);if(!job)return false;job.active=false;job.fn();return true};return{context,host,qa,document,finishes,delays,get jobs(){return jobs.filter(job=>job.active).length},get listeners(){return listeners.filter(item=>item.active).length},runNext,runAll(limit=100){let count=0;while(runNext()&&count++<limit);assert.ok(count<limit,"jobs did not settle")},runUntil(predicate,limit=50){let count=0;while(!predicate()&&runNext()&&count++<limit);assert.ok(predicate(),"target phase was not reached")},triggerDeadline(){if(deadline.active){deadline.active=false;deadline.callback?.()}},dispose(){controller.abort();listeners.forEach(item=>{if(item.active)item.target.removeEventListener(item.type,item.fn,item.options);item.active=false})}}}
const stage=host=>host.children[1],wrongCode=pin=>`${(Number(pin[0])+1)%10}${pin.slice(1)}`,enter=(api,code)=>{for(const digit of code)assert.equal(api.press(digit),true)};
function install(){const previousDocument=globalThis.document,previousRequest=globalThis.requestAnimationFrame,previousCancel=globalThis.cancelAnimationFrame;globalThis.document={createElement(){throw new Error("global document used")}};globalThis.requestAnimationFrame=fn=>1;globalThis.cancelAnimationFrame=()=>{};return()=>{if(previousDocument===undefined)delete globalThis.document;else globalThis.document=previousDocument;if(previousRequest===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=previousRequest;if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}}

test("metadata is the reserved original memory identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"2.0",tier:2,flavor:"quirky",step:1,family:"memory-phone-pin",category:"memory"}));
test("render creates every node through context.host.ownerDocument",()=>{const restore=install();try{const h=harness();game.render(game.generate(helpers()),h.context);assert.ok(h.document.created.length>90);assert.ok(h.document.created.every(node=>node.ownerDocument===h.host.ownerDocument));assert.equal(h.qa[ID].inspect().phase,"ENCODE")}finally{restore()}});
test("2000 generated fictional PINs clone, validate, and retain a unique exhaustive decoder",()=>{const found=new Set();for(let i=0;i<2000;i++){const task=game.generate(helpers(i+1));assert.deepEqual(game.validate(task),[]);assert.doesNotThrow(()=>structuredClone(task));assert.equal(new Set(task.pin).size,4);assert.equal(task.cues.map(cue=>cue.digit).join(""),task.pin);assert.equal(task.proof.candidateSpace,10000);assert.equal(task.proof.matchingPins,1);task.pin.split("").forEach(digit=>found.add(digit))}assert.equal(found.size,10)});
test("generation remains finite and valid under hostile helper extrema",()=>{for(const value of [-1,0,9,999,NaN,Infinity]){let calls=0;const task=game.generate({randomInt:()=>{calls++;return value}});assert.ok(calls<=12);assert.deepEqual(game.validate(task),[])}});
test("validator rejects forged decoder, duplicate cue, proof, resume, timing, and palette",()=>{const base=game.generate(helpers(4)),cases=[task=>task.cues[0].kind="mosaic",task=>task.cues[1]={...task.cues[0],slot:2,digit:Number(task.pin[1])},task=>task.proof.matchingPins=2,task=>task.resume={phase:"WRONG",input:"12",attempts:0},task=>task.duration=1,task=>task.palette.ink="#ffffff",task=>task.pin="12345"];for(const mutate of cases){const task=structuredClone(base);mutate(task);assert.ok(game.validate(task).length>0)}assert.doesNotThrow(()=>game.validate({}));assert.ok(game.validate(null).length)});
test("plain JSON resume retains attempts, partial input, and phase in a fresh module",async()=>{const restore=install();try{const task=game.generate(helpers(5)),h=harness({reducedMotion:true});game.render(task,h.context);const api=h.qa[ID];api.forceCue();enter(api,wrongCode(task.pin));h.runUntil(()=>api.inspect().phase==="WRONG");h.runUntil(()=>api.inspect().phase==="CUE");api.press(task.pin[0]);api.press(task.pin[1]);const resume=JSON.parse(JSON.stringify(api.snapshot()));assert.deepEqual(resume,{phase:"INPUT",input:task.pin.slice(0,2),attempts:1});const saved=JSON.parse(JSON.stringify({...task,resume})),fresh=await importGame(`resume-${Date.now()}`),next=harness({reducedMotion:true});assert.deepEqual(fresh.validate(saved),[]);fresh.render(saved,next.context);assert.deepEqual(next.qa[ID].snapshot(),resume);enter(next.qa[ID],task.pin.slice(2));next.runAll();assert.equal(next.qa[ID].inspect().result,"success");assert.deepEqual(next.finishes.map(item=>item.correct),[true])}finally{restore()}});
test("partial input is reversible and consumes no attempt",()=>{const restore=install();try{const task=game.generate(helpers(6)),h=harness();game.render(task,h.context);const api=h.qa[ID];api.forceCue();api.press("1");api.press("2");assert.equal(api.backspace(),true);assert.equal(api.inspect().input,"1");assert.equal(api.inspect().attempts,0);assert.equal(api.backspace(),true);assert.equal(api.inspect().phase,"CUE");assert.equal(api.backspace(),false)}finally{restore()}});
test("exact fictional PIN unlocks once and cannot double finish",()=>{const restore=install();try{const task=game.generate(helpers(7)),h=harness({reducedMotion:true});game.render(task,h.context);const api=h.qa[ID];api.forceCue();enter(api,task.pin);h.runAll();assert.equal(api.inspect().result,"success");assert.deepEqual(h.finishes.map(item=>item.correct),[true]);h.triggerDeadline();assert.equal(h.finishes.length,1);assert.equal(api.press("1"),false)}finally{restore()}});
test("wrong complete attempts shake, mark lamps, and clear only after tracked settle",()=>{const restore=install();try{const task=game.generate(helpers(8)),h=harness(),api=(()=>{game.render(task,h.context);return h.qa[ID]})();api.forceCue();enter(api,wrongCode(task.pin));assert.equal(api.inspect().phase,"CHECK");h.runUntil(()=>api.inspect().phase==="WRONG");let state=api.inspect();assert.equal(state.input.length,4);assert.equal(state.attempts,1);assert.deepEqual(state.lamps,[true,false,false]);assert.equal(stage(h.host).classList.contains("wrong"),true);h.runUntil(()=>api.inspect().phase==="CUE");state=api.inspect();assert.equal(state.input,"");assert.equal(state.attempts,1);assert.ok(h.delays.every(ms=>ms>0))}finally{restore()}});
test("third complete failure enters lockout exactly once",()=>{const restore=install();try{const task=game.generate(helpers(9)),h=harness({reducedMotion:true});game.render(task,h.context);const api=h.qa[ID],bad=wrongCode(task.pin);api.forceCue();for(let attempt=1;attempt<=3;attempt++){enter(api,bad);if(attempt<3)h.runUntil(()=>api.inspect().phase==="CUE");else h.runAll()}const state=api.inspect();assert.equal(state.result,"lockout");assert.equal(state.attempts,3);assert.deepEqual(state.lamps,[true,true,true]);assert.equal(stage(h.host).classList.contains("lockout"),true);assert.deepEqual(h.finishes.map(item=>item.correct),[false]);h.triggerDeadline();assert.equal(h.finishes.length,1)}finally{restore()}});
test("encoding and reduced veil are distinct nonzero tracked stages",()=>{const restore=install();try{const task=game.generate(helpers(10)),h=harness({reducedMotion:true});game.render(task,h.context);const api=h.qa[ID];assert.equal(api.inspect().phase,"ENCODE");h.runNext();assert.equal(api.inspect().phase,"VEIL");h.runNext();assert.equal(api.inspect().phase,"CUE");assert.ok(h.delays.every(ms=>ms>0))}finally{restore()}});
test("deadline is distinct, preserves attempt/input counts, and finishes once",()=>{const restore=install();try{const task=game.generate(helpers(11)),h=harness();game.render(task,h.context);const api=h.qa[ID];api.forceCue();api.press("7");h.triggerDeadline();h.runAll();const state=api.inspect();assert.equal(state.result,"timeout");assert.equal(state.input,"7");assert.match(state.status,/TIME OVER/);assert.deepEqual(h.finishes.map(item=>item.result.reason),["timeout"]);h.triggerDeadline();assert.equal(h.finishes.length,1)}finally{restore()}});
test("dispose during wrong feedback clears owned work and cannot finish",()=>{const restore=install();try{const task=game.generate(helpers(12)),h=harness();game.render(task,h.context);const api=h.qa[ID];api.forceCue();enter(api,wrongCode(task.pin));assert.ok(h.jobs>0);h.dispose();h.runAll();h.triggerDeadline();assert.equal(h.finishes.length,0);assert.equal(h.jobs,0);assert.equal(h.listeners,0);assert.equal(h.qa[ID],undefined)}finally{restore()}});
test("pointer clicks, physical digits, backspace, focus, and disabled encoding share actions",()=>{const restore=install();try{const task=game.generate(helpers(13)),h=harness();game.render(task,h.context);const api=h.qa[ID],root=stage(h.host),scene=root.children[1],phone=scene.children[0],screen=phone.children[0],recall=screen.children[4],keypad=recall.children[4];assert.equal(api.press("1"),false);api.forceCue();const one=keypad.children[0];one.focus();assert.equal(h.document.activeElement,one);one.dispatchEvent(new Event("click"));assert.equal(api.inspect().input,"1");const keyboard=new Event("keydown",{cancelable:true});Object.defineProperty(keyboard,"key",{value:"2"});root.dispatchEvent(keyboard);assert.equal(api.inspect().input,"12");const back=new Event("keydown",{cancelable:true});Object.defineProperty(back,"key",{value:"Backspace"});root.dispatchEvent(back);assert.equal(api.inspect().input,"1");assert.match(source,/:focus-visible/)}finally{restore()}});
test("real kernel abort removes every handset-owned resource",async()=>{const restore=install();try{const document=new FakeDocument(),host=new FakeElement("div",document),finishes=[],runtime=createGameRuntime({host,onFinish:(...args)=>finishes.push(args),viewport:{width:390,height:844,dpr:3},reducedMotion:true,qa:{}});game.render(game.generate(helpers(14)),runtime.context);runtime.dispose();await delay(700);assert.equal(finishes.length,0);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{restore()}});
test("generation and exhaustive validation stay within interaction budget",()=>{const start=performance.now();for(let i=0;i<250;i++){const task=game.generate(helpers(i+20));assert.deepEqual(game.validate(task),[])}assert.ok(performance.now()-start<2500)});
test("source is ownerDocument-only, lifetime tracked, credential-safe, network-free, audio-free, and emoji-free",()=>{assert.doesNotMatch(source,/\bdocument\.createElement\b/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|localStorage|sessionStorage|indexedDB|AudioContext|webkitAudioContext|new Audio)\b/);assert.doesNotMatch(source,/[\u{1F300}-\u{1FAFF}]/u);assert.match(source,/context\.later/);assert.match(source,/context\.setDeadline/);assert.match(source,/context\.listen/);assert.match(source,/架空の練習用PIN/)});
