import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {performance} from "node:perf_hooks";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";
const moduleUrl=new URL("../src/games/reaction-target-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8"),importGame=async tag=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n//${tag}`).toString("base64")}`)).default,game=await importGame("primary"),ID="reaction-target-v1",PROMPT="逃げる紫をつかまえて",HELP="背景を押すと逃亡成功です。";
function helpers(initial=0x17a6){let seed=initial>>>0;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32),randomInt=(min,max)=>min+Math.floor(random()*(max-min+1));return{random,randomInt,pick:values=>values[randomInt(0,values.length-1)],shuffle:values=>[...values]}}
const legacyGenerate=({randomInt})=>({kind:"target",prompt:PROMPT,help:HELP,x:randomInt(8,72),y:randomInt(10,62),duration:5000});
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}sync(){this.owner._className=[...this.values].join(" ")}}
class FakeStyle{constructor(){this.values=new Map();this.transform=""}setProperty(key,value){this.values.set(key,String(value))}}
class FakeElement extends EventTarget{constructor(tag,ownerDocument){super();this.tagName=tag.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.attributes=new Map();this.style=new FakeStyle();this.classList=new FakeClassList(this);this._className="";this.textContent="";this.innerHTML="";this.hidden=false;this.disabled=false;this.tabIndex=-1;this.type=""}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}append(...nodes){this.children.push(...nodes)}setAttribute(key,value){this.attributes.set(key,String(value));if(key==="tabindex")this.tabIndex=Number(value)}getAttribute(key){return this.attributes.get(key)??null}removeAttribute(key){this.attributes.delete(key);if(key==="tabindex")this.tabIndex=-1}contains(node){return node===this||this.children.some(child=>child.contains?.(node))}focus(){this.ownerDocument.activeElement=this}get clientWidth(){return this.classList.contains("rt-arena")?320:320}get clientHeight(){return this.classList.contains("rt-arena")?208:56}get offsetWidth(){return this.classList.contains("rt-target")?51.2:this.clientWidth}get offsetHeight(){return this.classList.contains("rt-target")?51.2:this.clientHeight}getBoundingClientRect(){return{left:0,top:0,width:this.offsetWidth,height:this.offsetHeight,right:this.offsetWidth,bottom:this.offsetHeight}}}
class FakeDocument{constructor(){this.activeElement=null;this.created=[]}createElement(tag){const element=new FakeElement(tag,this);this.created.push(element);return element}}
function harness({reducedMotion=false,randomValues=[.2,.4,.8,.6],initialNow=0}={}){const document=new FakeDocument(),host=new FakeElement("div",document),qa={},controller=new AbortController(),jobs=[],listeners=[],finishes=[],frames=[];let nowValue=initialNow,randomIndex=0,disposed=false,deadline={active:false,fn:null,ms:0};const later=(fn,ms)=>{const job={fn,ms,active:true};jobs.push(job);return()=>job.active=false},context={host,signal:controller.signal,reducedMotion,viewport:{width:390,height:844,dpr:3},qa,now:()=>nowValue,random:()=>randomValues[randomIndex++%randomValues.length],later,frame:fn=>{const frame={fn,active:true};frames.push(frame);return()=>frame.active=false},listen:(target,type,fn,options)=>{target.addEventListener(type,fn,options);const item={target,type,fn,options,active:true};listeners.push(item);return()=>{if(item.active){item.active=false;target.removeEventListener(type,fn,options)}}},setDeadline:(ms,fn)=>{deadline={active:true,fn,ms}},finish:(correct,result)=>{if(!disposed)finishes.push({correct,result})}};controller.signal.addEventListener("abort",()=>{disposed=true;jobs.forEach(job=>job.active=false);frames.forEach(frame=>frame.active=false);deadline.active=false},{once:true});return{context,host,qa,document,finishes,setNow:value=>nowValue=value,runLater(ms=450){const job=jobs.find(item=>item.active&&item.ms===ms);assert.ok(job);job.active=false;job.fn()},runFrame(time){const frame=frames.find(item=>item.active);assert.ok(frame);if(frame.fn(time)===false)frame.active=false},triggerDeadline(){if(deadline.active){deadline.active=false;deadline.fn()}},get deadline(){return deadline},get activeJobs(){return jobs.filter(job=>job.active).length},get activeFrames(){return frames.filter(frame=>frame.active).length},get activeListeners(){return listeners.filter(listener=>listener.active).length},dispose(){controller.abort();listeners.forEach(item=>{if(item.active)item.target.removeEventListener(item.type,item.fn,item.options);item.active=false})}}}
const task=(x=32,y=40)=>({kind:"target",prompt:PROMPT,help:HELP,x,y,duration:5000});
function event(type,properties={}){const value=new Event(type,{cancelable:true,bubbles:true});for(const [key,item] of Object.entries(properties))Object.defineProperty(value,key,{value:item});return value}
function install(){const prior={document:globalThis.document,requestAnimationFrame:globalThis.requestAnimationFrame,cancelAnimationFrame:globalThis.cancelAnimationFrame};globalThis.document={createElement(){throw new Error("global document used")}};globalThis.requestAnimationFrame=()=>1;globalThis.cancelAnimationFrame=()=>{};return()=>{for(const [key,value] of Object.entries(prior)){if(value===undefined)delete globalThis[key];else globalThis[key]=value}}}

test("metadata is the published stable identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.0",tier:1,flavor:"wild",step:1,family:"reaction-target",category:"reaction"}));
test("1000 generated tasks are byte-equivalent to the current app.js factory",()=>{for(let seed=0;seed<1000;seed++){const actual=game.generate(helpers(seed)),expected=legacyGenerate(helpers(seed));assert.deepEqual(actual,expected);assert.equal(JSON.stringify(actual),JSON.stringify(expected));assert.deepEqual(game.validate(actual),[])}});
test("hostile generation is bounded, finite, and keeps only the published shape",()=>{for(const value of [-99,8,72,999,NaN,3.5,undefined]){let calls=0;const generated=game.generate({randomInt:()=>{calls++;if(value===undefined)throw new Error("hostile");return value}});assert.equal(calls<=2,true);assert.deepEqual(Object.keys(generated),["kind","prompt","help","x","y","duration"]);assert.deepEqual(game.validate(generated),[])}});
test("validator rejects forged fields, copy, coordinates, and duration",()=>{const mutations=[value=>value.kind="moving",value=>value.prompt+="!",value=>value.help="changed",value=>value.x=7,value=>value.x=8.1,value=>value.y=63,value=>value.duration=4999,value=>value.seed=1];for(const mutate of mutations){const value=task();mutate(value);assert.ok(game.validate(value).length)}for(const value of [null,[],"target"])assert.ok(game.validate(value).length)});
test("render creates every node from host.ownerDocument and starts hidden for exactly 450ms",()=>{const restore=install();try{const h=harness({reducedMotion:true});game.render(task(),h.context);const api=h.qa[ID],{arena,target}=api.elements;assert.ok(h.document.created.length>=5);assert.ok(h.document.created.every(node=>node.ownerDocument===h.document));assert.equal(api.inspect().phase,"HIDDEN");assert.equal(target.hidden,true);assert.equal(h.deadline.ms,5000);assert.equal(h.activeJobs,1);assert.equal(h.document.activeElement,arena);h.setNow(450);h.runLater();assert.equal(api.inspect().phase,"APPEARED");assert.equal(target.hidden,false);assert.equal(h.activeFrames,0)}finally{restore()}});
test("appearance uses the exact published clamped top-left position",()=>{const restore=install();try{for(const [x,y,expectedX,expectedY] of [[8,10,25.6,20.8],[72,62,230.4,128.96]]){const h=harness({reducedMotion:true});game.render(task(x,y),h.context);h.setNow(450);h.runLater();const state=h.qa[ID].inspect();assert.ok(Math.abs(state.x-expectedX)<1e-10);assert.ok(Math.abs(state.y-expectedY)<1e-10);assert.equal(state.transform,`translate3d(${expectedX.toFixed(1)}px,${expectedY.toFixed(1)}px,0)`);assert.equal(state.randomCalls,0)}}finally{restore()}});
test("normal motion consumes direction then speed randoms and preserves dt cap equations",()=>{const restore=install();try{const h=harness({randomValues:[.2,.4,.8,.6]});game.render(task(),h.context);h.setNow(450);h.runLater();let state=h.qa[ID].inspect();assert.equal(state.phase,"MOVING");assert.equal(state.randomCalls,4);assert.equal(state.vx,-140.8);assert.ok(Math.abs(state.vy-87.36)<1e-12);h.runFrame(470);state=h.qa[ID].inspect();assert.ok(Math.abs(state.x-99.584)<1e-12);assert.ok(Math.abs(state.y-84.9472)<1e-10);assert.equal(state.transform,"translate3d(99.6px,84.9px,0)");h.runFrame(1000);state=h.qa[ID].inspect();assert.ok(Math.abs(state.x-93.952)<1e-12);assert.ok(Math.abs(state.y-88.4416)<1e-10);assert.equal(state.frameSamples,2)}finally{restore()}});
test("wall bounce clamps and resamples only the collided axis with the published range",()=>{const restore=install();try{const values=[.1,0,.9,0,.75],h=harness({randomValues:values});game.render(task(8,10),h.context);h.setNow(450);h.runLater();assert.equal(h.qa[ID].inspect().vx,-128);for(let i=1;i<=5;i++)h.runFrame(450+i*40);const state=h.qa[ID].inspect();assert.equal(state.x,0);assert.equal(state.vx,152);assert.equal(state.randomCalls,5);assert.ok(state.y>20.8)}finally{restore()}});
test("actual target pointer catch returns exact rounded reaction, quality, and detail once",()=>{const restore=install();try{const h=harness({reducedMotion:true});game.render(task(),h.context);h.setNow(450);h.runLater();h.setNow(1684.56);h.qa[ID].elements.target.dispatchEvent(event("pointerdown",{pointerType:"touch",pointerId:7}));assert.equal(h.qa[ID].inspect().phase,"CAUGHT");assert.equal(h.finishes.length,1);assert.equal(h.finishes[0].correct,true);assert.deepEqual(h.finishes[0].result,{reactionMs:1235,quality:1-1234.56/4000,detail:"確保まで 1235 ms"});h.qa[ID].elements.target.dispatchEvent(event("pointerdown"));h.triggerDeadline();assert.equal(h.finishes.length,1)}finally{restore()}});
test("arrow focus plus zero-detail keyboard click catches the same exact target",()=>{const restore=install();try{const h=harness({reducedMotion:true});game.render(task(),h.context);h.setNow(450);h.runLater();const {arena,target}=h.qa[ID].elements;arena.dispatchEvent(event("keydown",{key:"ArrowRight"}));assert.equal(h.document.activeElement,target);h.setNow(700);target.dispatchEvent(event("click",{detail:0}));assert.deepEqual(h.finishes,[{correct:true,result:{reactionMs:250,quality:.9375,detail:"確保まで 250 ms"}}]);assert.match(source,/:focus-visible/)}finally{restore()}});
test("background click is immediate wrong even before appearance",()=>{const restore=install();try{const h=harness();game.render(task(),h.context);h.qa[ID].elements.arena.dispatchEvent(event("click"));assert.equal(h.qa[ID].inspect().phase,"MISS");assert.deepEqual(h.finishes,[{correct:false,result:{detail:"そこにはもう、紫はいません。"}}]);assert.equal(h.activeFrames,0);h.runLater();assert.equal(h.finishes.length,1)}finally{restore()}});
test("5000ms timeout is exact, distinct, and cannot double finish",()=>{const restore=install();try{const h=harness({reducedMotion:true});game.render(task(),h.context);assert.equal(h.deadline.ms,5000);h.triggerDeadline();assert.equal(h.qa[ID].inspect().phase,"TIMEOUT");assert.deepEqual(h.finishes,[{correct:false,result:{detail:"紫は逃げ切りました。"}}]);h.qa[ID].elements.arena.dispatchEvent(event("click"));assert.equal(h.finishes.length,1)}finally{restore()}});
test("plain JSON resume in a fresh module preserves the task and catch proof",async()=>{const restore=install();try{const saved=JSON.parse(JSON.stringify(game.generate(helpers(84)))),fresh=await importGame(`resume-${Date.now()}`),h=harness({reducedMotion:true});assert.deepEqual(fresh.validate(saved),[]);fresh.render(saved,h.context);assert.equal(h.qa[ID].inspect().taskJSON,JSON.stringify(saved));h.setNow(450);h.runLater();h.setNow(950);h.qa[ID].catch();assert.deepEqual(h.finishes,[{correct:true,result:{reactionMs:500,quality:.875,detail:"確保まで 500 ms"}}])}finally{restore()}});
test("dispose while moving cancels appearance, frame, deadline, listeners, QA, and finish",()=>{const restore=install();try{const h=harness();game.render(task(),h.context);h.setNow(450);h.runLater();assert.equal(h.activeFrames,1);h.dispose();assert.equal(h.activeJobs,0);assert.equal(h.activeFrames,0);assert.equal(h.activeListeners,0);assert.equal(h.qa[ID],undefined);h.triggerDeadline();assert.equal(h.finishes.length,0)}finally{restore()}});
test("real kernel disposal leaves no surviving target work",async()=>{const restore=install();try{const document=new FakeDocument(),host=new FakeElement("div",document),finishes=[],runtime=createGameRuntime({host,onFinish:(...args)=>finishes.push(args),viewport:{width:390,height:844,dpr:3},reducedMotion:true,qa:{}});game.render(task(),runtime.context);runtime.dispose();await delay(500);assert.equal(finishes.length,0);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{restore()}});
test("generation and validation stay inside the interaction budget",()=>{const started=performance.now();for(let i=0;i<10000;i++){const value=game.generate(helpers(i));assert.deepEqual(game.validate(value),[])}assert.ok(performance.now()-started<1200)});
test("source retains exact hitbox and tracked lifecycle with no forbidden paths",()=>{assert.match(source,/width:\$\{TARGET_REM\}rem;height:\$\{TARGET_REM\}rem/);assert.equal(source.includes("TARGET_REM=3.2"),true);assert.doesNotMatch(source,/\bdocument\.createElement\b/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|webkitAudioContext|new Audio|localStorage|sessionStorage)\b/);assert.doesNotMatch(source,/\b(?:src|href)\s*=/);assert.match(source,/context\.later\(appear,APPEAR_DELAY\)/);assert.match(source,/context\.setDeadline/);assert.match(source,/context\.frame\(step\)/);assert.match(source,/context\.listen/)});
