import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import game from "../src/games/reaction-emoji-runner-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";

const ID="reaction-emoji-runner-v1",moduleUrl=new URL("../src/games/reaction-emoji-runner-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8"),appSource=await readFile(new URL("../app.js",import.meta.url),"utf8"),legacyFixtureSource=await readFile(new URL("./reaction-emoji-runner-v1.legacy-fixture.mjs",import.meta.url),"utf8"),paritySource=await readFile(new URL("./reaction-emoji-runner-v1.parity-qa.mjs",import.meta.url),"utf8");
const importFresh=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n// ${suffix}`).toString("base64")}`)).default;
const published=hero=>({kind:"runner",prompt:"タップでジャンプ！丸太を越えて",help:"「よーい…」のあと、横から来る 🪵 に合わせて1回タップ。",hero,leadInMs:1500,travelMs:2800,duration:4800});
function helpers(initial=0x51a9e){let seed=initial>>>0;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32),randomInt=(min,max)=>min+Math.floor(random()*(max-min+1)),pick=values=>values[randomInt(0,values.length-1)];return{random,randomInt,pick}}
function legacyGenerate(h){return{kind:"runner",prompt:"タップでジャンプ！丸太を越えて",help:"「よーい…」のあと、横から来る 🪵 に合わせて1回タップ。",hero:h.pick(["😀","🤓","🤑","🐼"]),leadInMs:1500,travelMs:2800,duration:4800}}

class ClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean));this.sync()}sync(){this.owner._className=[...this.values].join(" ")}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}}
const noop=()=>{};class Gradient{addColorStop(){}}
function context2d(){return new Proxy({globalAlpha:1,createLinearGradient:()=>new Gradient(),createRadialGradient:()=>new Gradient()},{get:(target,key)=>key in target?target[key]:noop,set:(target,key,value)=>(target[key]=value,true)})}
class Element extends EventTarget{constructor(tag,owner){super();this.tagName=tag.toUpperCase();this.ownerDocument=owner;this.children=[];this.parentElement=null;this.attributes=new Map();this.dataset={};this.style={};this._className="";this.classList=new ClassList(this);this.textContent="";this.tabIndex=-1;this.clientWidth=393;this.width=0;this.height=0;this.ctx=this.tagName==="CANVAS"?context2d():null}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}append(...nodes){nodes.forEach(node=>{node.parentElement=this;this.children.push(node)})}replaceChildren(...nodes){this.children=[];this.append(...nodes)}setAttribute(key,value){this.attributes.set(key,String(value))}getAttribute(key){return this.attributes.get(key)??null}focus(){this.ownerDocument.activeElement=this}getContext(){return this.ctx}getBoundingClientRect(){const width=Number.parseFloat(this.style.width)||this.clientWidth||393,height=Number.parseFloat(this.style.height)||322;return{left:0,top:0,width,height,right:width,bottom:height}}}
function documentFor(dpr=3){const view=new EventTarget();view.devicePixelRatio=dpr;const owner={defaultView:view,activeElement:null};owner.createElement=tag=>new Element(tag,owner);return owner}
function event(type,props={}){const result=new Event(type,{bubbles:true,cancelable:true});for(const[key,value]of Object.entries(props))Object.defineProperty(result,key,{value});return result}
function harness({reduced=false,viewport={width:393,height:852,dpr:3},owner=documentFor(viewport.dpr)}={}){const controller=new AbortController(),host=owner.createElement("div"),qa={},jobs=[],listeners=new Set(),finishes=[];host.clientWidth=viewport.width;let frame=null,deadline=null,now=0,disposed=false,finishCalls=0;const dispose=()=>{if(disposed)return;disposed=true;controller.abort();for(const job of jobs)job.on=false;if(deadline)deadline.on=false;frame=null;for(const item of listeners)item.target.removeEventListener(item.type,item.fn,item.options);listeners.clear()};const context={host,signal:controller.signal,reducedMotion:reduced,viewport,qa,finish(correct,result={}){finishCalls++;if(disposed||finishes.length)return false;finishes.push({correct:Boolean(correct),result});dispose();return true},later(fn,ms){const job={at:now+Math.max(0,Number(ms)||0),fn,on:true};jobs.push(job);return job},setDeadline(ms,fn){deadline={at:now+ms,fn,on:true};return deadline},frame(fn){frame=fn;return()=>{frame=null}},listen(target,type,fn,options){target.addEventListener(type,fn,options);const item={target,type,fn,options};listeners.add(item);return()=>{target.removeEventListener(type,fn,options);listeners.delete(item)}}};const runNext=()=>{const job=jobs.filter(item=>item.on).sort((a,b)=>a.at-b.at)[0];if(!job)return false;now=job.at;job.on=false;job.fn();return true};const triggerDeadline=()=>{if(deadline?.on&&!disposed){deadline.on=false;deadline.fn();return true}return false};const step=time=>{if(frame&&frame(time)===false)frame=null};return{context,host,owner,qa,finishes,dispose,runNext,triggerDeadline,step,get frameActive(){return Boolean(frame)},get listenerCount(){return listeners.size},get finishCalls(){return finishCalls},get disposed(){return disposed}}}
function mount(options={}){const h=harness(options),task=published(options.hero||"🤓");game.render(task,h.context);const api=h.qa[ID],stage=h.host.children[1];return Object.assign(h,{task,api,stage,canvas:stage.children[0],status:stage.children[1]})}


test("metadata preserves the published 1.0 identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.0",tier:2,flavor:"wild",step:1,family:"reaction-emoji-runner",category:"reaction"}));
test("10,000 generations exactly equal the current app.js factory and remain plain",()=>{const actual=helpers(0xa8761a1),legacy=helpers(0xa8761a1),seen=new Set(),started=performance.now();for(let i=0;i<10000;i++){const task=game.generate(actual),reference=legacyGenerate(legacy);assert.deepEqual(task,reference,`generation ${i}`);assert.deepEqual(Object.keys(task),["kind","prompt","help","hero","leadInMs","travelMs","duration"]);assert.deepEqual(game.validate(task),[]);assert.doesNotThrow(()=>structuredClone(task));seen.add(task.hero)}assert.deepEqual([...seen].sort(),["😀","🤓","🤑","🐼"].sort());assert.ok(performance.now()-started<3000)});
test("generation requires injected pick and rejects a foreign pick result",()=>{assert.throws(()=>game.generate(),/pick/);assert.throws(()=>game.generate({pick:()=>"🐶"}),/supplied hero/)});
test("parity fixtures pin the exact current app.js task, equations, thresholds, and 48-frame matrix",()=>{assert.match(appSource,/\{id:"reaction-emoji-runner-v1",version:"1\.0",category:"reaction",make:\(\)=>\(\{kind:"runner",prompt:"タップでジャンプ！丸太を越えて",help:"「よーい…」のあと、横から来る 🪵 に合わせて1回タップ。",hero:pick\(\["😀","🤓","🤑","🐼"\]\),leadInMs:1500,travelMs:2800,duration:4800\}\)\}/);for(const exact of["x=110-elapsed/travel*125","jumpDuration=780*Math.max(1,travel/2800)","x<30&&x>14&&y<requiredClearance","if(x<4)","obstacle.style.left=\"24%\""])assert.ok(appSource.includes(exact),exact);for(const exact of["x=110-elapsed/travel*125","jumpDuration=780*Math.max(1,travel/2800)","x<30&&x>14&&y<requiredClearance","if(x<4)","obstacle.style.left=\"24%\""])assert.ok(legacyFixtureSource.includes(exact),`legacy fixture ${exact}`);assert.match(paritySource,/scenes=\["ready","approach","jump","success","collision","timeout"\]/);assert.match(paritySource,/viewports=\[\[393,852\],\[402,874\]\]/);assert.match(paritySource,/frames\.length===48/)});
test("strict validation rejects every changed published rule and optional retuning",()=>{const valid=published("😀"),mutations=[null,{...valid,kind:"choice"},{...valid,prompt:"changed"},{...valid,help:"changed"},{...valid,hero:"🐶"},{...valid,leadInMs:1499},{...valid,travelMs:2801},{...valid,duration:4799},{...valid,runnerClearance:37}];for(const mutation of mutations)assert.ok(game.validate(mutation).length)});
test("published plain JSON resumes in a fresh module and succeeds once in the legacy timing window",async()=>{const fresh=await importFresh(Date.now()),task=JSON.parse(JSON.stringify(published("🐼"))),h=harness();fresh.render(task,h.context);const api=h.qa[ID];assert.equal(api.inspect().phase,"READY");h.runNext();api.advance(1580);assert.equal(api.jump(),true);api.advance(900);const state=api.inspect();assert.equal(state.result,"success");assert.equal(state.finishCalls,1);assert.deepEqual(h.finishes.map(item=>item.correct),[true]);assert.equal(h.finishes[0].result.detail,"華麗なひと跳びです。");assert.ok(h.finishes[0].result.quality>.59&&h.finishes[0].result.quality<.61);h.triggerDeadline();assert.equal(h.finishes.length,1)});
test("normal path uses the exact x, 780ms sine arc, collision gate, and ordering",()=>{const h=mount();h.runNext();h.api.advance(1232);let state=h.api.inspect();assert.ok(Math.abs(state.x-55)<1e-8);assert.equal(state.jumpDuration,780);assert.equal(state.clearance,38);h.api.advance(348);h.api.jump();h.api.advance(390);state=h.api.inspect();assert.ok(state.x>14&&state.x<30);assert.ok(Math.abs(state.y-76)<.02);assert.equal(state.result,null);h.api.advance(430);assert.equal(h.api.inspect().result,"success");assert.equal(h.finishes.length,1)});
test("no jump and an early completed jump both collide with the current miss meaning",()=>{for(const early of[false,true]){const h=mount();h.runNext();if(early){h.api.advance(900);h.api.jump();h.api.advance(900)}else h.api.advance(1800);const state=h.api.inspect();assert.equal(state.result,"collision");assert.equal(state.x<30&&state.x>14,true);assert.equal(state.y<38,true);assert.equal(h.finishes[0].correct,false);assert.equal(h.finishes[0].result.detail,"丸太に老いを置いてきました。")}});
test("pre-start input is ignored and a new jump is accepted only after the published arc ends",()=>{const h=mount();h.stage.dispatchEvent(event("click",{detail:1,pointerType:"touch"}));assert.equal(h.api.inspect().jumps,0);h.runNext();assert.equal(h.api.jump(),true);assert.equal(h.api.jump(),false);h.api.advance(781);assert.equal(h.api.jump(),true);assert.equal(h.api.inspect().jumps,2);h.dispose()});
test("Touch click, Space, Enter, focus, and terminal input lock share jump",()=>{for(const input of["touch"," ","Enter"]){const h=mount();assert.equal(h.owner.activeElement,h.stage);h.runNext();h.api.advance(1580);if(input==="touch")h.stage.dispatchEvent(event("click",{detail:1,pointerType:"touch"}));else h.stage.dispatchEvent(event("keydown",{key:input}));assert.equal(h.api.inspect().jumps,1,input);h.api.advance(900);assert.equal(h.finishes.length,1);const before=h.api.inspect().jumps;h.stage.dispatchEvent(event("click",{detail:1,pointerType:"touch"}));assert.equal(h.api.inspect().jumps,before)}});
test("normal deadline begins after lead-in, uses current detail, and finishes once",()=>{const h=mount();assert.equal(h.triggerDeadline(),false);h.runNext();assert.equal(h.triggerDeadline(),true);assert.equal(h.api.inspect().result,"timeout");assert.equal(h.finishes.length,1);assert.equal(h.finishes[0].correct,false);assert.equal(h.finishes[0].result.detail,"ゴールが先に帰りました。");h.triggerDeadline();assert.equal(h.finishes.length,1)});
test("reduced motion is deterministic, static at 24%, has no RAF, and dodges immediately",()=>{const h=mount({reduced:true});assert.equal(h.frameActive,false);h.stage.dispatchEvent(event("click",{detail:1,pointerType:"touch"}));assert.equal(h.api.inspect().jumps,0);h.runNext();let state=h.api.inspect();assert.equal(state.x,24);assert.equal(state.phase,"APPROACH");assert.equal(h.frameActive,false);h.stage.dispatchEvent(event("keydown",{key:"Enter"}));state=h.api.inspect();assert.equal(state.result,"success");assert.equal(state.jumps,1);assert.equal(h.finishes[0].result.detail,"静止画モードで、丸太を回避しました。");assert.equal(h.frameActive,false)});
test("reduced deadline retains its distinct published timeout",()=>{const h=mount({reduced:true});h.runNext();h.triggerDeadline();assert.equal(h.api.inspect().result,"timeout");assert.equal(h.finishes[0].result.detail,"丸太が待ちくたびれました。");assert.equal(h.finishes[0].correct,false)});
test("normal mode owns one approximately-60fps tracked loop",()=>{const h=mount();h.runNext();const base=performance.now();for(let i=0;i<95;i++)h.step(base+i*1000/60);assert.equal(h.frameActive,true,JSON.stringify(h.api.inspect()));assert.ok(h.api.inspect().frames>=90);h.api.jump();for(let i=95;i<150&&h.frameActive;i++)h.step(base+i*1000/60);assert.equal(h.api.inspect().result,"success");assert.ok(h.api.inspect().frames>135&&h.api.inspect().frames<150)});
test("393/402 layouts cap backing at DPR3 and expose six parity scenes in both motions",()=>{for(const reduced of[false,true])for(const viewport of[{width:393,height:852,dpr:3},{width:402,height:874,dpr:4}]){const h=mount({reduced,viewport});const canvas=h.api.inspect().canvas;assert.equal(canvas.dpr,3);assert.equal(canvas.pixelWidth,canvas.cssWidth*3);assert.equal(canvas.pixelHeight,canvas.cssHeight*3);assert.ok(canvas.cssWidth<=viewport.width);assert.ok(canvas.cssHeight>48);for(const scene of["ready","approach","jump","success","collision","timeout"])assert.equal(h.api.showScene(scene),true,`${scene} ${reduced}`);h.dispose()}});
test("dispose cancels lead-in/frame/deadline/listeners/QA and prevents finish",async()=>{const oldRaf=globalThis.requestAnimationFrame,oldCancel=globalThis.cancelAnimationFrame;let id=0;const frames=new Map();globalThis.requestAnimationFrame=fn=>(frames.set(++id,fn),id);globalThis.cancelAnimationFrame=key=>frames.delete(key);try{const owner=documentFor(),host=owner.createElement("div"),qa={},finishes=[],runtime=createGameRuntime({host,qa,reducedMotion:false,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(published("🤓"),runtime.context);assert.ok(runtime.inspect().timeouts>=1);runtime.dispose();await delay(20);assert.deepEqual(finishes,[]);assert.equal(qa[ID],undefined);assert.equal(frames.size,0);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(oldRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=oldRaf;if(oldCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=oldCancel}});
test("render uses ownerDocument and source has no raw lifetime, network, audio, or external asset path",()=>{const owner=documentFor(),old=globalThis.document;globalThis.document={createElement(){throw Error("global document used")}};try{const h=mount({owner});const visit=node=>{assert.equal(node.ownerDocument,owner);node.children.forEach(visit)};visit(h.host);h.dispose()}finally{if(old===undefined)delete globalThis.document;else globalThis.document=old}assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement)\b/);assert.doesNotMatch(source,/(?:\.src\s*=|url\s*\()/)});
