import test from"node:test";import assert from"node:assert/strict";import{readFile}from"node:fs/promises";import{performance}from"node:perf_hooks";import{setTimeout as delay}from"node:timers/promises";import{createGameRuntime}from"../src/game-kernel.js";
const moduleUrl=new URL("../src/games/reaction-cupboard-catch-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8"),importGame=async tag=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n//${tag}`).toString("base64")}`)).default,game=await importGame("primary"),ID="reaction-cupboard-catch-v1";
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(v){this.values=new Set(String(v||"").split(/\s+/).filter(Boolean))}add(...v){v.forEach(x=>this.values.add(x));this.sync()}contains(v){return this.values.has(v)}sync(){this.owner._className=[...this.values].join(" ")}}
class FakeStyle{setProperty(k,v){this[k]=String(v)}}
class FakeElement extends EventTarget{constructor(tag,doc){super();this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.children=[];this.parentNode=null;this.dataset={};this.attributes=new Map();this.style=new FakeStyle();this.classList=new FakeClassList(this);this._className="";this.textContent="";this.disabled=false;this.hidden=false;this.type=""}set className(v){this._className=String(v);this.classList.reset(v)}get className(){return this._className}get lastChild(){return this.children.at(-1)||null}append(...nodes){nodes.forEach(node=>{node.parentNode=this;this.children.push(node)})}setAttribute(k,v){this.attributes.set(k,String(v))}getAttribute(k){return this.attributes.get(k)??null}focus(){this.ownerDocument.activeElement=this}getBoundingClientRect(){return{left:0,top:0,width:100,height:56,right:100,bottom:56}}}
class FakeDocument{constructor(){this.created=[];this.activeElement=null}createElement(tag){const e=new FakeElement(tag,this);this.created.push(e);return e}}
function harness({reducedMotion=false}={}){const document=new FakeDocument(),host=new FakeElement("div",document),qa={},controller=new AbortController(),jobs=[],listeners=[],finishes=[];let disposed=false,deadline={active:false,ms:0,fn:null},order=0;const context={host,signal:controller.signal,reducedMotion,viewport:{width:390,height:844,dpr:3},qa,later:(fn,ms)=>{const job={fn,ms,active:true,order:order++};jobs.push(job);return()=>job.active=false},frame:()=>{throw new Error("unexpected frame")},listen:(target,type,fn,options)=>{target.addEventListener(type,fn,options);const item={target,type,fn,options,active:true};listeners.push(item);return()=>{if(item.active){item.active=false;target.removeEventListener(type,fn,options)}}},setDeadline:(ms,fn)=>deadline={active:true,ms,fn},finish:(correct,result)=>{if(!disposed)finishes.push({correct,result})}};controller.signal.addEventListener("abort",()=>{disposed=true;jobs.forEach(v=>v.active=false);deadline.active=false},{once:true});return{context,host,qa,document,finishes,get deadline(){return deadline},get jobs(){return jobs.filter(v=>v.active).length},get listeners(){return listeners.filter(v=>v.active).length},runNext(){const job=jobs.filter(v=>v.active).sort((a,b)=>a.order-b.order)[0];if(!job)return false;job.active=false;job.fn();return true},triggerDeadline(){if(deadline.active){deadline.active=false;deadline.fn()}},dispose(){controller.abort();listeners.forEach(v=>{if(v.active)v.target.removeEventListener(v.type,v.fn,v.options);v.active=false})}}}
function install(){const prior={document:globalThis.document,requestAnimationFrame:globalThis.requestAnimationFrame,cancelAnimationFrame:globalThis.cancelAnimationFrame};globalThis.document={createElement(){throw new Error("global document")}};globalThis.requestAnimationFrame=()=>1;globalThis.cancelAnimationFrame=()=>{};return()=>{for(const[k,v]of Object.entries(prior)){if(v===undefined)delete globalThis[k];else globalThis[k]=v}}}
const mounted=(options={})=>{const h=harness(options),task=game.generate();game.render(task,h.context);return{h,task,api:h.qa[ID]}},toTick=(h,api,tick)=>{let guard=0;while(api.inspect().tick<tick&&!api.inspect().done){assert.equal(h.runNext(),true);assert.ok(++guard<50)}assert.equal(api.inspect().tick,tick)},catchUnload=(h,api,{tick,item,hand,zone})=>{toTick(h,api,tick);assert.equal(api.catchItem(item,hand),true);toTick(h,api,tick+1);assert.equal(api.unload(zone,hand),true)};

test("metadata and authored eight-item task are stable",()=>{const task=game.generate();assert.deepEqual(game.metadata,{id:ID,introducedIn:"2.0",tier:2,flavor:"wild",step:1,family:"reaction-cupboard-catch",category:"reaction"});assert.equal(task.kind,"cupboardCatch");assert.equal(task.items.length,8);assert.deepEqual(task.items.map(v=>v.catchTick),[3,6,9,9,12,15,18,21]);assert.deepEqual(task.hands,["left","right"]);assert.equal(task.duration,30000);assert.deepEqual(game.validate(task),[])});
test("generation is deterministic cloneable plain data",()=>{const a=game.generate(),b=game.generate();assert.deepEqual(a,b);assert.doesNotThrow(()=>structuredClone(a));assert.equal(a.resume.phase,"RUNNING");assert.equal(a.resume.tick,0);assert.deepEqual(a.resume.hands,{left:null,right:null});assert.equal(a.resume.stored.length,0)});
test("integer-tick proof exhaustively requires proactive unloading",()=>{const proof=game.generate().proof;assert.equal(proof.tickCount,23);assert.equal(proof.itemCount,8);assert.equal(proof.completeStates,1);assert.ok(proof.maxReachableStates>1);assert.equal(proof.proactiveUnloadRequired,true);assert.equal(proof.simultaneousTick,9);assert.deepEqual(proof.simultaneousItems,["tray-a","bowl-a"]);assert.deepEqual(proof.failureOutcomes,["miss","wrong-zone-slide","two-hand-collision","overloaded-hands","timeout"]);for(const boundary of proof.exactBoundaries){assert.equal(boundary.early+1,boundary.exact);assert.equal(boundary.late-1,boundary.exact)}});
test("validator rejects schedule, zone, timing, proof, and inconsistent resume",()=>{const mutations=[t=>t.items[0].catchTick=4,t=>t.items[0].zone="square",t=>t.zones.pop(),t=>t.tickMs=400,t=>t.duration=1,t=>t.proof.completeStates=0,t=>t.resume.tick=30,t=>t.resume.hands.left="plate-a",t=>{t.resume.itemStates["plate-a"]="STORED";t.resume.stored=[]},t=>t.resume.phase="TERMINAL"];for(const mutate of mutations){const task=game.generate();mutate(task);assert.ok(game.validate(task).length)}assert.ok(game.validate(null).length)});
test("render owns DOM and starts tracked tick zero with deadline",()=>{const restore=install();try{const{h,api}=mounted();assert.ok(h.document.created.every(v=>v.ownerDocument===h.document));const state=api.inspect();assert.equal(state.tick,0);assert.deepEqual(state.active,[]);assert.equal(h.jobs,1);assert.equal(h.deadline.ms,30000);assert.deepEqual(state.hands,{left:null,right:null})}finally{restore()}});
test("normal and reduced expose exact early, catch, and one-late miss boundaries",()=>{const restore=install();try{for(const reducedMotion of[false,true]){const{h,api}=mounted({reducedMotion});toTick(h,api,2);assert.equal(api.catchItem("plate-a","left"),false);assert.equal(api.inspect().itemStates["plate-a"],"FALLING");toTick(h,api,3);assert.deepEqual(api.inspect().active,["plate-a"]);assert.equal(api.inspect().itemStates["plate-a"],"CATCHABLE");h.runNext();assert.equal(api.inspect().tick,3);assert.equal(api.inspect().result.reason,"miss");assert.equal(api.inspect().itemStates["plate-a"],"MISSED");assert.equal(h.finishes.length,1)}}finally{restore()}});
test("caught hand cannot unload in same tick but can unload next tick",()=>{const restore=install();try{const{h,api}=mounted();toTick(h,api,3);assert.equal(api.catchItem("plate-a","left"),true);assert.equal(api.unload("circle","left"),false);toTick(h,api,4);assert.equal(api.unload("circle","left"),true);assert.deepEqual(api.inspect().stored,["plate-a"]);assert.equal(api.inspect().hands.left,null)}finally{restore()}});
test("simultaneous tick nine requires and occupies both hands",()=>{const restore=install();try{const{h,api}=mounted();catchUnload(h,api,{tick:3,item:"plate-a",hand:"left",zone:"circle"});catchUnload(h,api,{tick:6,item:"cup-a",hand:"left",zone:"arch"});toTick(h,api,9);assert.deepEqual(api.inspect().active,["tray-a","bowl-a"]);assert.equal(api.catchItem("tray-a","left"),true);assert.equal(api.catchItem("bowl-a","right"),true);assert.deepEqual(api.inspect().hands,{left:"tray-a",right:"bowl-a"});assert.deepEqual(api.inspect().acted,{left:true,right:true})}finally{restore()}});
test("finite proactive schedule stores all eight exactly once in both motion modes",()=>{const restore=install();try{for(const reducedMotion of[false,true]){const{h,api}=mounted({reducedMotion});catchUnload(h,api,{tick:3,item:"plate-a",hand:"left",zone:"circle"});catchUnload(h,api,{tick:6,item:"cup-a",hand:"left",zone:"arch"});toTick(h,api,9);api.catchItem("tray-a","left");api.catchItem("bowl-a","right");toTick(h,api,10);api.unload("square","left");api.unload("diamond","right");catchUnload(h,api,{tick:12,item:"plate-b",hand:"left",zone:"circle"});catchUnload(h,api,{tick:15,item:"cup-b",hand:"left",zone:"arch"});catchUnload(h,api,{tick:18,item:"tray-b",hand:"left",zone:"square"});toTick(h,api,21);api.catchItem("bowl-b","left");toTick(h,api,22);api.unload("diamond","left");const state=api.inspect();assert.equal(state.result.reason,"all-stored");assert.equal(state.stored.length,8);assert.equal(new Set(state.stored).size,8);assert.deepEqual(h.finishes.map(v=>v.correct),[true]);assert.equal(state.finishCalls,1);assert.equal(api.useHand("left"),false)}}finally{restore()}});
test("wrong shape zone retains one whole slid item",()=>{const restore=install();try{const{h,api}=mounted();toTick(h,api,3);api.catchItem("plate-a","left");toTick(h,api,4);assert.equal(api.unload("square","left"),true);const state=api.inspect();assert.equal(state.result.reason,"wrong-zone-slide");assert.equal(state.itemStates["plate-a"],"SLID");assert.equal(state.result.item,"plate-a");assert.equal(state.result.zone,"square");assert.equal(h.finishes.length,1)}finally{restore()}});
test("two hands directed to the same current item retain collision",()=>{const restore=install();try{const{h,api}=mounted();toTick(h,api,3);api.catchItem("plate-a","left");assert.equal(api.catchItem("plate-a","right"),true);const state=api.inspect();assert.equal(state.result.reason,"two-hand-collision");assert.deepEqual(state.result.hands,["left","right"]);assert.equal(state.hands.left,"plate-a");assert.equal(state.hands.right,null)}finally{restore()}});
test("occupied hand directed at later fall retains overload",()=>{const restore=install();try{const{h,api}=mounted();toTick(h,api,3);api.catchItem("plate-a","left");toTick(h,api,6);assert.equal(api.catchItem("cup-a","left"),true);const state=api.inspect();assert.equal(state.result.reason,"overloaded-hands");assert.equal(state.result.held,"plate-a");assert.equal(state.result.item,"cup-a");assert.equal(state.hands.left,"plate-a")}finally{restore()}});
test("timeout retains exact queue, occupied hand, and counter",()=>{const restore=install();try{const{h,api}=mounted();catchUnload(h,api,{tick:3,item:"plate-a",hand:"left",zone:"circle"});toTick(h,api,6);api.catchItem("cup-a","right");h.triggerDeadline();const state=api.inspect();assert.equal(state.result.reason,"timeout");assert.equal(state.result.tick,6);assert.deepEqual(state.result.hands,{left:null,right:"cup-a"});assert.deepEqual(state.result.stored,["plate-a"]);assert.equal(state.itemStates["cup-a"],"HELD");assert.equal(h.finishes.length,1)}finally{restore()}});
test("running plain resume restores exact tick, hand, states, and counter",async()=>{const restore=install();try{const first=mounted();catchUnload(first.h,first.api,{tick:3,item:"plate-a",hand:"left",zone:"circle"});toTick(first.h,first.api,6);first.api.catchItem("cup-a","right");const s=first.api.inspect(),task=game.generate();task.resume={phase:"RUNNING",tick:s.tick,itemStates:s.itemStates,hands:s.hands,acted:s.acted,stored:s.stored,selectedHand:s.selectedHand,lastCaught:s.lastCaught,result:null};assert.deepEqual(game.validate(task),[]);const fresh=await importGame(`running-${Date.now()}`),next=harness();fresh.render(JSON.parse(JSON.stringify(task)),next.context);assert.deepEqual(next.qa[ID].inspect().hands,s.hands);assert.deepEqual(next.qa[ID].inspect().stored,s.stored);assert.equal(next.qa[ID].inspect().tick,6);assert.equal(next.finishes.length,0)}finally{restore()}});
test("terminal plain resume restores miss without refinish",async()=>{const restore=install();try{const first=mounted();toTick(first.h,first.api,3);first.h.runNext();const s=first.api.inspect(),task=game.generate();task.resume={phase:"TERMINAL",tick:s.tick,itemStates:s.itemStates,hands:s.hands,acted:s.acted,stored:s.stored,selectedHand:s.selectedHand,lastCaught:s.lastCaught,result:s.result};assert.deepEqual(game.validate(task),[]);const fresh=await importGame(`terminal-${Date.now()}`),next=harness();fresh.render(JSON.parse(JSON.stringify(task)),next.context);assert.equal(next.qa[ID].inspect().result.reason,"miss");assert.equal(next.qa[ID].inspect().itemStates["plate-a"],"MISSED");assert.equal(next.finishes.length,0);assert.equal(next.deadline.active,false)}finally{restore()}});
test("touch-style hand/item actions and keyboard focus share controls",()=>{const restore=install();try{const{h,api}=mounted();toTick(h,api,3);const left=api.elements.handButtons.left;left.focus();assert.equal(h.document.activeElement,left);left.dispatchEvent(new Event("click"));assert.equal(api.inspect().hands.left,"plate-a");toTick(h,api,4);api.elements.zoneButtons.circle.dispatchEvent(new Event("click"));assert.deepEqual(api.inspect().stored,["plate-a"]);assert.match(source,/:focus-visible/)}finally{restore()}});
test("miss material contains at most one CSS crack and no debris or distress path",()=>{assert.match(source,/\.rcc-item\.missed \.rcc-object::after\{content:""/);assert.doesNotMatch(source,/::before[^}]*crack|shard|debris|blood|cleanup|broken glass/i);assert.doesNotMatch(source,/[ - ]/)});
test("dispose during active catch window cancels tick, deadline, listeners, QA, and finish",()=>{const restore=install();try{const{h,api}=mounted();toTick(h,api,3);assert.equal(api.inspect().active.length,1);h.dispose();while(h.runNext());h.triggerDeadline();assert.equal(h.jobs,0);assert.equal(h.deadline.active,false);assert.equal(h.listeners,0);assert.equal(h.finishes.length,0);assert.equal(h.qa[ID],undefined)}finally{restore()}});
test("real kernel disposal leaves no scheduled work",async()=>{const restore=install();try{const doc=new FakeDocument(),host=new FakeElement("div",doc),finishes=[],runtime=createGameRuntime({host,onFinish:(...v)=>finishes.push(v),reducedMotion:true,viewport:{width:390,height:844,dpr:3},qa:{}});game.render(game.generate(),runtime.context);runtime.dispose();await delay(400);assert.equal(finishes.length,0);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{restore()}});
test("generation, proof validation, and scheduling remain finite",()=>{const start=performance.now();for(let i=0;i<1000;i++)assert.deepEqual(game.validate(game.generate()),[]);assert.ok(performance.now()-start<2500)});
test("source is ownerDocument-only and tracked without network, audio, storage, RAF, or emoji",()=>{assert.doesNotMatch(source,/\bdocument\.createElement\b/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|webkitAudioContext|new Audio|localStorage|sessionStorage|indexedDB)\b/);assert.doesNotMatch(source,/[\u{1F300}-\u{1FAFF}]/u);assert.match(source,/context\.later\(advance/);assert.match(source,/context\.setDeadline/);assert.match(source,/context\.listen/);assert.doesNotMatch(source,/context\.frame/)});
