import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";
const moduleUrl=new URL("../src/games/reaction-shape-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8"),legacySource=await readFile(new URL("../app.js",import.meta.url),"utf8"),game=(await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`)).default,ID="reaction-shape-v1",NAMES=["まる","さんかく","しかく"],MARKS={まる:"●",さんかく:"▲",しかく:"■"};
const fixedTask=(answer="まる",options=["さんかく","まる","しかく"])=>({kind:"rotation",prompt:`${MARKS[answer]} の名前は？`,help:"見たままを選んでください。",symbol:MARKS[answer],options:[...options],answer,duration:5000});
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}sync(){this.owner._className=[...this.values].join(" ")}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}toggle(value,force){const next=force===undefined?!this.values.has(value):Boolean(force);next?this.values.add(value):this.values.delete(value);this.sync();return next}}
class FakeElement extends EventTarget{constructor(tagName,ownerDocument){super();this.tagName=tagName.toUpperCase();this.ownerDocument=ownerDocument;this.parentNode=null;this.children=[];this.attributes=new Map();this.dataset={};this.style={};this.classList=new FakeClassList(this);this._className="";this._textContent="";this.type="";this.disabled=false;this.tabIndex=-1}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}set textContent(value){this._textContent=String(value);this.children=[]}get textContent(){return this._textContent+this.children.map(child=>child.textContent||"").join("")}append(...nodes){for(const node of nodes){if(node?.parentNode){const old=node.parentNode.children.indexOf(node);if(old>=0)node.parentNode.children.splice(old,1)}if(node&&typeof node==="object")node.parentNode=this;this.children.push(node)}}replaceChildren(...nodes){this.children=[];this._textContent="";this.append(...nodes)}setAttribute(name,value){this.attributes.set(name,String(value))}getAttribute(name){return this.attributes.get(name)??null}focus(){this.ownerDocument.activeElement=this;this.dispatchEvent(new Event("focus"))}getBoundingClientRect(){return{width:this.ownerDocument.viewportWidth,height:420,left:0,top:0,right:this.ownerDocument.viewportWidth,bottom:420}}}
function fakeDocument(){const doc={activeElement:null,viewportWidth:393,defaultView:new EventTarget()};doc.createElement=tag=>new FakeElement(tag,doc);return doc}
function harness({task=fixedTask(),reducedMotion=false,width=393}={}){const doc=fakeDocument(),host=doc.createElement("div"),controller=new AbortController(),qa={},pending=[],listeners=new Set(),frames=new Set(),finishes=[];let clock=0,disposed=false,finishCalls=0,order=0;doc.viewportWidth=width;const context={host,qa,signal:controller.signal,reducedMotion,viewport:{width,height:852,dpr:3},later(fn,ms){const job={fn,at:clock+Math.max(0,Number(ms)||0),order:order++,active:true};pending.push(job);return job},setDeadline(ms,fn){return context.later(fn,ms)},frame(fn){frames.add(fn);return()=>frames.delete(fn)},listen(target,type,fn,options){target.addEventListener(type,fn,options);const row={target,type,fn,options};listeners.add(row);return()=>{target.removeEventListener(type,fn,options);listeners.delete(row)}},finish(correct,payload){finishCalls++;if(disposed||finishes.length)return false;finishes.push({correct:Boolean(correct),payload});return true}};game.render(task,context);const next=()=>pending.filter(job=>job.active).sort((a,b)=>a.at-b.at||a.order-b.order)[0]||null,runTo=target=>{let job=next(),guard=0;while(job&&job.at<=target&&!disposed&&guard++<100){clock=job.at;job.active=false;job.fn();job=next()}clock=target},runFor=ms=>runTo(clock+ms),dispose=()=>{if(disposed)return;disposed=true;pending.forEach(job=>job.active=false);frames.clear();controller.abort();listeners.forEach(({target,type,fn,options})=>target.removeEventListener(type,fn,options));listeners.clear()};return{context,doc,host,qa,finishes,runTo,runFor,dispose,get clock(){return clock},get pendingCount(){return pending.filter(job=>job.active).length},get frameCount(){return frames.size},get listenerCount(){return listeners.size},get finishCalls(){return finishCalls}}}
const apiOf=h=>h.qa[ID],eventWith=(type,properties={})=>{const event=new Event(type,{bubbles:true,cancelable:true});for(const[key,value]of Object.entries(properties))Object.defineProperty(event,key,{value});return event};

test("metadata identifies the published 1.15 classic reaction-shape port",()=>{assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.15",tier:1,flavor:"classic",step:1,family:"reaction-shape",category:"reaction"})});
test("legacy factory is removed while generic rotation, choice, and timeout semantics remain pinned",()=>{assert.doesNotMatch(legacySource,/\{id:"reaction-shape-v1",version:"1\.15",category:"reaction",make:/);assert.match(legacySource,/task\.kind==="rotation"[\s\S]*?makeChoices\(task,\{symbol:true\}\)/);assert.match(legacySource,/finishTask\(v===task\.answer,\{answerLabel:task\.answer\}\)/);assert.match(legacySource,/時間切れです。脳は定時退社しました。/)});
test("5000 generations preserve pick-before-shuffle order, exact task fields, marks, and full option set",()=>{let seed=0x815,calls=0;const seen=new Set(),orders=new Set();for(let run=0;run<5000;run++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const chosen=seed%3,trace=[],task=game.generate({pick(values){trace.push(["pick",[...values]]);return values[chosen]},shuffle(values){trace.push(["shuffle",[...values]]);const shift=(seed>>>8)%3;return[...values.slice(shift),...values.slice(0,shift)]}});calls+=trace.length;assert.deepEqual(trace,[["pick",NAMES],["shuffle",NAMES]]);assert.deepEqual(Object.keys(task),["kind","prompt","help","symbol","options","answer","duration"]);assert.equal(task.answer,NAMES[chosen]);assert.equal(task.symbol,MARKS[task.answer]);assert.equal(task.prompt,`${task.symbol} の名前は？`);assert.deepEqual(new Set(task.options),new Set(NAMES));assert.deepEqual(game.validate(task),[]);assert.doesNotThrow(()=>structuredClone(task));seen.add(task.answer);orders.add(task.options.join("|"))}assert.equal(calls,10000);assert.equal(seen.size,3);assert.ok(orders.size>=3)});
test("hostile helpers still attempt pick then shuffle once and fall back finitely",()=>{const trace=[],task=game.generate({pick(){trace.push("pick");throw new Error("hostile")},shuffle(values){trace.push(["shuffle",[...values]]);return null}});assert.deepEqual(trace,["pick",["shuffle",NAMES]]);assert.deepEqual(task,fixedTask("まる",NAMES));assert.deepEqual(game.generate({}),task)});
test("validator rejects extras, copy, marks, prompts, answer retunes, option changes, and duration changes",()=>{const broken={...fixedTask(),extra:true,kind:"choice",prompt:"▲ の名前は？",help:"色で選ぶ",symbol:"▲",options:["まる","さんかく","さんかく","ほし"],answer:"ほし",duration:1},issues=game.validate(broken).join(" | ");for(const fragment of["fields","kind","help","duration","answer","symbol","prompt","options"])assert.match(issues,new RegExp(fragment));assert.deepEqual(game.validate(fixedTask("さんかく",["しかく","まる","さんかく"])),[]);assert.deepEqual(game.validate(fixedTask("しかく",["しかく","さんかく","まる"])),[])});
test("render uses ownerDocument and preserves the exact mark plus task option order without an answer cue",()=>{const task=fixedTask("さんかく",["しかく","まる","さんかく"]),h=harness({task}),api=apiOf(h),state=api.inspect();assert.equal(api.elements.buttons.length,3);assert.ok(api.elements.buttons.every(button=>button.ownerDocument===h.doc));assert.equal(state.symbolText,"▲");assert.equal(state.symbolAria,"▲");assert.deepEqual(state.optionText,task.options);assert.deepEqual(state.classes,["rsv-choice","rsv-choice","rsv-choice"]);assert.equal(state.disabled,0);assert.ok(api.elements.buttons.every((button,index)=>button.getAttribute("aria-label")===`候補${index+1} ${task.options[index]}`));assert.equal(h.doc.activeElement,api.elements.stage);h.dispose()});
test("real touch correct selection locks immediately, holds tracked 180ms feedback, and uses generic payload",()=>{const h=harness(),api=apiOf(h),button=api.elements.buttons[1];button.dispatchEvent(eventWith("pointerdown",{pointerType:"touch"}));let state=api.inspect();assert.equal(state.phase,"success");assert.equal(state.selectedValue,"まる");assert.equal(state.correct,true);assert.equal(state.disabled,3);assert.ok(state.classes[1].includes("correct"));assert.equal(h.finishes.length,0);h.runFor(179);assert.equal(h.finishes.length,0);h.runFor(1);assert.deepEqual(h.finishes,[{correct:true,payload:{answerLabel:"まる"}}]);assert.equal(api.choose(0),false);h.runTo(5000);assert.equal(h.finishCalls,1)});
test("wrong selection is distinct, locks all three choices, and returns the generic answerLabel payload",()=>{const h=harness(),api=apiOf(h);assert.equal(api.choose(0),true);const state=api.inspect();assert.equal(state.phase,"wrong");assert.equal(state.selectedValue,"さんかく");assert.equal(state.correct,false);assert.ok(state.classes[0].includes("wrong"));assert.equal(state.disabled,3);h.runFor(180);assert.deepEqual(h.finishes,[{correct:false,payload:{answerLabel:"まる"}}]);assert.equal(h.finishCalls,1)});
test("exact 5000ms generic timeout wins once and never labels the answer in the symbol card",()=>{const h=harness(),api=apiOf(h);h.runTo(4999);assert.equal(h.finishes.length,0);h.runTo(5000);assert.equal(api.inspect().phase,"timeout");assert.equal(api.inspect().symbolText,"●");assert.equal(api.inspect().status,"時間切れです。脳は定時退社しました。");assert.deepEqual(h.finishes,[{correct:false,payload:{detail:"時間切れです。脳は定時退社しました。",answerLabel:"まる"}}]);api.timeout();h.runFor(1000);assert.equal(h.finishCalls,1)});
test("a choice at 4999ms locks out the deadline and commits only that choice after feedback",()=>{const h=harness(),api=apiOf(h);h.runTo(4999);api.choose(1);h.runTo(5000);assert.equal(api.inspect().phase,"success");assert.equal(h.finishes.length,0);h.runTo(5179);assert.deepEqual(h.finishes,[{correct:true,payload:{answerLabel:"まる"}}]);assert.equal(h.finishCalls,1)});
test("keyboard arrows follow the two-plus-full-row geometry and native activation shares the checker",()=>{const h=harness(),api=apiOf(h);api.focus(1);api.elements.choices.dispatchEvent(eventWith("keydown",{key:"ArrowDown"}));assert.equal(api.inspect().focused,2);api.elements.choices.dispatchEvent(eventWith("keydown",{key:"ArrowUp"}));assert.equal(api.inspect().focused,1);api.elements.choices.dispatchEvent(eventWith("keydown",{key:"ArrowLeft"}));assert.equal(api.inspect().focused,0);api.elements.buttons[0].dispatchEvent(eventWith("click",{detail:0}));assert.equal(api.inspect().selectedValue,"さんかく");h.runFor(180);assert.deepEqual(h.finishes,[{correct:false,payload:{answerLabel:"まる"}}])});
test("reduced motion retains nonzero tracked selected feedback and uses no frame loop",()=>{const h=harness({reducedMotion:true}),api=apiOf(h);assert.equal(api.inspect().reduced,true);assert.equal(h.frameCount,0);api.choose(1);h.runFor(179);assert.equal(h.finishes.length,0);assert.ok(api.inspect().classes[1].includes("correct"));h.runFor(1);assert.equal(h.finishes.length,1);assert.equal(h.frameCount,0)});
test("plain cloned tasks resume in fresh renderers identically without mutation",()=>{const task=structuredClone(fixedTask("しかく",["しかく","さんかく","まる"])),before=structuredClone(task),a=harness({task}),b=harness({task:structuredClone(task)});assert.deepEqual(apiOf(a).inspect().optionText,apiOf(b).inspect().optionText);apiOf(a).choose(0);apiOf(b).choose(0);a.runFor(180);b.runFor(180);assert.deepEqual(a.finishes,b.finishes);assert.deepEqual(task,before)});
test("dispose during feedback cancels commit, deadline, listeners, QA, and all owned work",()=>{const h=harness(),api=apiOf(h);api.choose(1);assert.ok(h.pendingCount>=2);assert.ok(h.listenerCount>0);h.dispose();h.runTo(10000);assert.equal(h.pendingCount,0);assert.equal(h.listenerCount,0);assert.equal(h.frameCount,0);assert.equal(h.finishes.length,0);assert.equal(h.qa[ID],undefined);assert.equal(api.inspect().disposed,true)});
test("real kernel disposal leaves no feedback/deadline/listener work or commit",async()=>{const doc=fakeDocument(),host=doc.createElement("div"),qa={},finishes=[],previousCancel=globalThis.cancelAnimationFrame;globalThis.cancelAnimationFrame=()=>{};try{const runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,payload)=>finishes.push({correct,payload})});game.render(fixedTask(),runtime.context);qa[ID].choose(1);assert.equal(runtime.inspect().frames,0);assert.ok(runtime.inspect().timeouts>=2);runtime.dispose();await delay(240);assert.equal(qa[ID],undefined);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}});
test("source is ownerDocument-only, tracked, offline, audio-free, frame-free, and has no answer/color cue field",()=>{assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement|localStorage|sessionStorage)\b/);assert.doesNotMatch(source,/data-(?:answer|correct|rule|color)/);assert.doesNotMatch(source,/className=.*MARKS|MARKS\[.*\].*className/)});
