#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.."&&pwd);STAMP=$(date +%Y%m%d-%H%M%S);OUT=${1:-/tmp/agetest-social-share-cookies-v1-audit-$STAMP};cd "$ROOT";[[ ! -e "$OUT" ]]||{ echo "output exists" >&2;exit 2;};mkdir -p "$OUT";node tools/qa-browser-lanes.mjs start audit >/dev/null
ready='(async()=>{for(let i=0;i<240;i++){if(window.__SHARE_COOKIES_FIXTURE__&&document.documentElement.dataset.ready==="true")return true;await new Promise(r=>setTimeout(r,25))}throw Error("ready")})()';nav(){ local v=$1 s=$2 m=$3 w=$4 h=$5 live=${6:-0};node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/social-share-cookies-v1.fixture.html?variant=$v&scene=$s&motion=$m&width=$w&live=$live" "$w" "$h" 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null;}
variants=(0 1 2 3);metrics=(393x852 402x874);motions=(normal reduced);scenes=(initial carried partial full-invalid-left full-invalid-right success timeout)
for v in "${variants[@]}";do for metric in "${metrics[@]}";do w=${metric%x*};h=${metric#*x};for m in "${motions[@]}";do for s in "${scenes[@]}";do nav "$v" "$s" "$m" "$w" "$h";node tools/qa-browser-lanes.mjs eval audit 'window.__SHARE_COOKIES_FIXTURE__.report()' >"$OUT/evidence-$v-$metric-$s-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/table$v-$metric-$s-$m.png" >/dev/null;done;nav "$v" initial "$m" "$w" "$h" 1;node tools/qa-browser-lanes.mjs eval audit '(()=>{const f=window.__SHARE_COOKIES_FIXTURE__,b=f.api.elements.cookies[0];b.focus();document.body.classList.add("fixture-focus");return{focused:b===document.activeElement,state:f.api.inspect(),report:f.report()}})()' >"$OUT/focus-$v-$metric-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/focus-$v-$metric-$m.png" >/dev/null;done;done;done
for metric in 390x844 430x932;do w=${metric%x*};h=${metric#*x};for v in "${variants[@]}";do for m in "${motions[@]}";do for s in initial success;do nav "$v" "$s" "$m" "$w" "$h";node tools/qa-browser-lanes.mjs eval audit 'window.__SHARE_COOKIES_FIXTURE__.report()' >"$OUT/boundary-$v-$metric-$s-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/boundary-table$v-$metric-$s-$m.png" >/dev/null;done;done;done;done
cue='(()=>{const f=window.__SHARE_COOKIES_FIXTURE__,buttons=f.api.elements.cookies,slots=[...f.api.elements.slots.values()];return{variant:f.variant,favorites:f.task.plates.map(p=>p.favorite),shapes:[...new Set(f.task.cookies.map(c=>c.shape))],cookies:buttons.map(b=>({answer:b.getAttribute("data-answer"),correct:b.getAttribute("data-correct"),shape:b.dataset.shape,rect:b.getBoundingClientRect().toJSON()})),slots:slots.map(s=>({answer:s.getAttribute("data-answer"),correct:s.getAttribute("data-correct"),rect:s.getBoundingClientRect().toJSON()})),report:f.report()}})()';for v in "${variants[@]}";do nav "$v" initial normal 393 852;node tools/qa-browser-lanes.mjs eval audit "$cue" >"$OUT/no-hidden-cue-$v.json";done
touch='(async()=>{const f=window.__SHARE_COOKIES_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms)),solution=f.api.solutionLocations(),trace=[];for(let i=0;i<8;i++){const b=f.api.elements.cookies[i],s=f.api.elements.slots.get(solution[i]),a=b.getBoundingClientRect(),z=s.getBoundingClientRect(),id=100+i;b.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",isPrimary:true,button:0,clientX:a.left+a.width/2,clientY:a.top+a.height/2}));b.dispatchEvent(new PointerEvent("pointermove",{bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",isPrimary:true,clientX:z.left+z.width/2,clientY:z.top+z.height/2}));b.dispatchEvent(new PointerEvent("pointerup",{bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",isPrimary:true,button:0,clientX:z.left+z.width/2,clientY:z.top+z.height/2}));await wait(f.motion==="reduced"?170:205);trace.push(f.api.inspect().locations[i])}await wait(260);const report=f.report();return{status:report.status,variant:f.variant,motion:f.motion,trace,solution,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,targets:report.targets,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()';for v in "${variants[@]}";do for m in "${motions[@]}";do nav "$v" initial "$m" 390 844 1;node tools/qa-browser-lanes.mjs eval audit "$touch" >"$OUT/touch-success-$v-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/touch-success-$v-$m.png" >/dev/null;done;done
keyboard='(async()=>{const f=window.__SHARE_COOKIES_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms)),key=(b,k)=>b.dispatchEvent(new KeyboardEvent("keydown",{key:k,bubbles:true,cancelable:true})),trace=[];for(let i=0;i<8;i++){const b=f.api.elements.cookies[i];b.focus();key(b," ");if(i===0)key(b,"ArrowRight");key(b," ");await wait(f.motion==="reduced"?170:205);trace.push(f.api.inspect().locations[i])}await wait(260);const report=f.report();return{status:report.status,variant:f.variant,motion:f.motion,trace,sawArrow:true,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,targets:report.targets,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()';for pair in 0:normal 3:reduced;do v=${pair%:*};m=${pair#*:};nav "$v" initial "$m" 430 932 1;node tools/qa-browser-lanes.mjs eval audit "$keyboard" >"$OUT/keyboard-$v-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/keyboard-success-$v-$m.png" >/dev/null;done
correctInvalid='(async()=>{const f=window.__SHARE_COOKIES_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms));f.api.showScene("full-invalid-left");const before=f.api.inspect(),loc=before.locations;let move=null;for(let i=0;i<8&&!move;i++)for(let j=i+1;j<8&&!move;j++){if(loc[i].split("-")[0]===loc[j].split("-")[0])continue;const next=[...loc];[next[i],next[j]]=[next[j],next[i]];if(f.api.evaluate(next).valid)move={i,destination:loc[j]}}if(!move)throw Error("no correction");const b=f.api.elements.cookies[move.i],s=f.api.elements.slots.get(move.destination),a=b.getBoundingClientRect(),z=s.getBoundingClientRect(),id=211;b.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",button:0,clientX:a.left+a.width/2,clientY:a.top+a.height/2}));b.dispatchEvent(new PointerEvent("pointermove",{bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",clientX:z.left+z.width/2,clientY:z.top+z.height/2}));b.dispatchEvent(new PointerEvent("pointerup",{bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",button:0,clientX:z.left+z.width/2,clientY:z.top+z.height/2}));await wait(f.motion==="reduced"?430:520);const report=f.report();return{motion:f.motion,before,move,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()';for m in "${motions[@]}";do nav 2 initial "$m" 390 844 1;node tools/qa-browser-lanes.mjs eval audit "$correctInvalid" >"$OUT/correction-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/correction-$m.png" >/dev/null;done
deadline='(async()=>{const f=window.__SHARE_COOKIES_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms));f.api.showScene("partial");const before=f.api.inspect();for(let i=0;i<220;i++){if(f.report().finishes.length)break;await wait(100)}const elapsed=performance.now()-f.renderedAt,report=f.report();return{motion:f.motion,elapsed,before,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()';nav 1 initial normal 390 844 1;node tools/qa-browser-lanes.mjs eval audit "$deadline" >"$OUT/deadline-390x844-normal.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/deadline-390x844-normal.png" >/dev/null;nav 1 initial reduced 430 932 1;node tools/qa-browser-lanes.mjs eval audit "$deadline" >"$OUT/deadline-430x932-reduced.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/deadline-430x932-reduced.png" >/dev/null
disposeNormal='(async()=>{const f=window.__SHARE_COOKIES_FIXTURE__,b=f.api.elements.cookies[0],r=b.getBoundingClientRect(),wait=ms=>new Promise(x=>setTimeout(x,ms));b.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:301,pointerType:"touch",button:0,clientX:r.left+r.width/2,clientY:r.top+r.height/2}));const state=f.api.inspect(),before=f.runtime.inspect();f.runtime.dispose();await wait(260);return{state,before,after:f.runtime.inspect(),qaPresent:Boolean(f.qa[f.game.metadata.id]),finishes:f.report().finishes}})()';disposeReduced='(async()=>{const f=window.__SHARE_COOKIES_FIXTURE__,wait=ms=>new Promise(x=>setTimeout(x,ms));f.api.place(0,"window-0");const state=f.api.inspect(),before=f.runtime.inspect();f.runtime.dispose();await wait(260);return{state,before,after:f.runtime.inspect(),qaPresent:Boolean(f.qa[f.game.metadata.id]),finishes:f.report().finishes}})()';nav 1 initial normal 390 844 1;node tools/qa-browser-lanes.mjs eval audit "$disposeNormal" >"$OUT/dispose-390x844-normal.json";nav 1 initial reduced 430 932 1;node tools/qa-browser-lanes.mjs eval audit "$disposeReduced" >"$OUT/dispose-430x932-reduced.json"
perf='(async()=>{const f=window.__SHARE_COOKIES_FIXTURE__,b=f.api.elements.cookies[0],r=b.getBoundingClientRect(),d=[];b.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:401,pointerType:"touch",button:0,clientX:r.left+r.width/2,clientY:r.top+r.height/2}));let p=performance.now();await new Promise(resolve=>{const tick=n=>{d.push(n-p);p=n;if(d.length===90)resolve();else requestAnimationFrame(tick)};requestAnimationFrame(tick)});const report=f.report(),runtime=f.runtime.inspect(),expected=f.motion==="normal"?1:0,result={status:d.length===90&&runtime.frames===expected&&!report.external.length&&!report.errors.length&&report.viewport.bodyScrollWidth<=report.width?"pass":"fail",motion:f.motion,frames:d.length,averageFrameMs:d.reduce((a,b)=>a+b,0)/d.length,maxFrameMs:Math.max(...d),gameOwnedFrames:runtime.frames,state:f.api.inspect(),runtime,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors};f.runtime.dispose();return result})()';nav 0 initial normal 390 844 1;node tools/qa-browser-lanes.mjs eval audit "$perf" >"$OUT/performance-390x844-normal.json";nav 3 initial reduced 430 932 1;node tools/qa-browser-lanes.mjs eval audit "$perf" >"$OUT/performance-430x932-reduced.json"
OUT="$OUT" python - <<'PY'
from pathlib import Path
from PIL import Image,ImageChops,ImageStat
import json,math,os,subprocess
r=Path(os.environ['OUT']);variants=range(4);metrics=['393x852','402x874'];motions=['normal','reduced'];scenes=['initial','carried','partial','full-invalid-left','full-invalid-right','success','timeout'];rows=[];fail=[]
for v in variants:
 for metric in metrics:
  for scene in scenes:
   a=Image.open(r/f'table{v}-{metric}-{scene}-normal.png').convert('RGB');b=Image.open(r/f'table{v}-{metric}-{scene}-reduced.png').convert('RGB');d=ImageChops.difference(a,b);st=ImageStat.Stat(d);rows.append({'key':f'{v}-{metric}-{scene}','size':[a.width,a.height],'mae':round(sum(st.mean)/3,3),'normalizedRMSE':round(math.sqrt(sum(x*x for x in st.rms)/3)/255,6),'changed':round(sum(px!=(0,0,0) for px in d.getdata())/(a.width*a.height),5)})
   for m in motions:
    e=json.loads((r/f'evidence-{v}-{metric}-{scene}-{m}.json').read_text());s=e['state'];ok=(scene!='initial' or all(x=='tray' for x in s['locations'])) and (scene!='carried' or s['carried']==0) and (scene!='partial' or not s['evaluation']['full']) and (scene!='full-invalid-left' or s['evaluation']['full'] and s['evaluation']['missing']==['window']) and (scene!='full-invalid-right' or s['evaluation']['full'] and s['evaluation']['missing']==['shelf']) and (scene!='success' or s['result']=='success' and s['evaluation']['valid']) and (scene!='timeout' or s['result']=='timeout')
    if e['status']!='pass' or e['dpr']!=3 or e['errors'] or e['external'] or e['viewport']['bodyScrollWidth']>e['width'] or min(min(t['height'],t['width']) for t in e['targets'])<44 or not ok:fail.append(f'evidence {v} {metric} {scene} {m}')
for v in variants:
 e=json.loads((r/f'no-hidden-cue-{v}.json').read_text())
 if len(e['shapes'])>3 or any(c['answer'] or c['correct'] or min(c['rect']['width'],c['rect']['height'])<44 for c in e['cookies']) or any(s['answer'] or s['correct'] or min(s['rect']['width'],s['rect']['height'])<44 for s in e['slots']):fail.append(f'cue {v}')
for v in variants:
 for m in motions:
  e=json.loads((r/f'touch-success-{v}-{m}.json').read_text())
  if not(e['status']=='pass' and e['trace']==e['solution'] and e['after']['result']=='success' and e['after']['evaluation']['valid'] and len(e['finishes'])==1 and e['finishes'][0]['correct'] and not e['overflow'] and not e['errors'] and not e['external']):fail.append(f'touch {v} {m}')
for v,m in [(0,'normal'),(3,'reduced')]:
 e=json.loads((r/f'keyboard-{v}-{m}.json').read_text())
 if not(e['status']=='pass' and e['sawArrow'] and e['after']['result']=='success' and e['after']['evaluation']['valid'] and len(e['finishes'])==1 and e['finishes'][0]['correct'] and not e['overflow'] and not e['errors']):fail.append(f'keyboard {v} {m}')
for m in motions:
 e=json.loads((r/f'correction-{m}.json').read_text())
 if not(e['before']['evaluation']['full'] and not e['before']['evaluation']['valid'] and e['before']['evaluation']['missing']==['window'] and e['after']['result']=='success' and len(e['finishes'])==1 and e['finishes'][0]['correct']):fail.append(f'correction {m}')
for metric,m in [('390x844','normal'),('430x932','reduced')]:
 e=json.loads((r/f'deadline-{metric}-{m}.json').read_text())
 if not(19750<=e['elapsed']<=20550 and e['after']['result']=='timeout' and e['before']['locations']==e['after']['locations'] and len(e['finishes'])==1 and not e['finishes'][0]['correct']):fail.append(f'deadline {metric} {m}')
 e=json.loads((r/f'dispose-{metric}-{m}.json').read_text())
 if not(e['after']['disposed'] and e['after']['timeouts']==0 and e['after']['frames']==0 and e['after']['listeners']==0 and not e['qaPresent'] and not e['finishes']):fail.append(f'dispose {metric} {m}')
 e=json.loads((r/f'performance-{metric}-{m}.json').read_text())
 if not(e['status']=='pass' and e['frames']==90 and e['gameOwnedFrames']==(1 if m=='normal' else 0) and not e['overflow'] and not e['errors']):fail.append(f'perf {metric} {m}')
for metric in ['390x844','430x932']:
 w,h=map(int,metric.split('x'))
 for v in variants:
  for m in motions:
   for s in ['initial','success']:
    e=json.loads((r/f'boundary-{v}-{metric}-{s}-{m}.json').read_text());im=Image.open(r/f'boundary-table{v}-{metric}-{s}-{m}.png')
    if e['status']!='pass' or e['dpr']!=3 or e['errors'] or e['external'] or e['viewport']['bodyScrollWidth']>w or min(min(t['height'],t['width']) for t in e['targets'])<44 or im.size!=(w*3,h*3):fail.append(f'boundary {v} {metric} {s} {m}')
for v in variants:
 for metric in metrics:
  for m in motions:
   e=json.loads((r/f'focus-{v}-{metric}-{m}.json').read_text())
   if not e['focused'] or e['report']['status']!='pass':fail.append(f'focus {v} {metric} {m}')
# Contact sheet: seven canonical states at contact size for director review.
files=[str(r/f'table0-393x852-{s}-normal.png') for s in scenes]
subprocess.run(['magick','montage',*files,'-thumbnail','393x852','-tile','7x1','-geometry','+4+0',str(r/'director-contact-sheet.png')],check=True)
report={'status':'pass' if not fail else 'fail','canonicalViewports':[{'width':393,'height':852,'dpr':3},{'width':402,'height':874,'dpr':3}],'variants':list(variants),'states':scenes,'comparisons':len(rows),'canonicalScreenshots':len(rows)*2,'focusScreenshots':16,'boundaryScreenshots':32,'touchRoutes':8,'keyboardRoutes':2,'correctionRoutes':2,'allDpr3':not any('evidence' in x for x in fail),'allFullResolution':all(x['size'] in ([1179,2556],[1206,2622]) for x in rows),'maxMAE':max(x['mae'] for x in rows),'maxNormalizedRMSE':max(x['normalizedRMSE'] for x in rows),'failures':fail,'rows':rows};(r/'comparison-report.json').write_text(json.dumps(report,indent=2));print(json.dumps({k:v for k,v in report.items() if k!='rows'},indent=2));raise SystemExit(bool(fail))
PY
echo "$OUT"
