import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";

const moduleUrl=new URL("../src/games/social-care-package-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8");
const importGame=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n// ${suffix}`).toString("base64")}`)).default;
const game=await importGame("primary"),ID="social-care-package-v1";
const scenarioTask=index=>game.generate({randomInt:()=>index});
function helpers(initial=0x5ca4e){let seed=initial>>>0;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32),randomInt=(min,max)=>min+Math.floor(random()*(max-min+1));return{random,randomInt,pick:values=>values[randomInt(0,values.length-1)]}}
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}sync(){this.owner._className=[...this.values].join(" ")}}
class FakeStyle{constructor(){this.values=new Map()}setProperty(key,value){this.values.set(key,String(value))}getPropertyValue(key){return this.values.get(key)||""}}
class FakeText{constructor(text,ownerDocument){this.data=String(text);this.ownerDocument=ownerDocument;this.children=[]}get textContent(){return this.data}set textContent(value){this.data=String(value)}}
class FakeElement extends EventTarget{constructor(tag,ownerDocument){super();this.tagName=tag.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.attributes=new Map();this.dataset={};this.style=new FakeStyle();this.classList=new FakeClassList(this);this._className="";this._text="";this.disabled=false;this.type="";this.tabIndex=-1}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}set textContent(value){this._text=String(value);this.children=[]}get textContent(){return this._text+this.children.map(child=>child?.textContent??String(child)).join("")}append(...nodes){nodes.forEach(node=>this.children.push(typeof node==="string"?new FakeText(node,this.ownerDocument):node))}replaceChildren(...nodes){this.children=[];this._text="";this.append(...nodes)}setAttribute(key,value){this.attributes.set(key,String(value))}getAttribute(key){return this.attributes.get(key)??null}focus(){this.ownerDocument.activeElement=this}setPointerCapture(){}getBoundingClientRect(){return{left:0,top:0,width:180,height:220,right:180,bottom:220}}}
function fakeDocument(name="fixture"){const view=new EventTarget();view.devicePixelRatio=3;const documentRef={name,defaultView:view,activeElement:null};documentRef.createElement=tag=>new FakeElement(tag,documentRef);return documentRef}
function installDocument(){const previous=globalThis.document;globalThis.document=fakeDocument();return()=>{if(previous===undefined)delete globalThis.document;else globalThis.document=previous}}
function harness({reducedMotion=false,viewport={width:393,height:852,dpr:3},ownerDocument=globalThis.document}={}){const controller=new AbortController(),host=ownerDocument.createElement("div"),qa={},jobs=[],listeners=new Set(),finishes=[];let deadline=null,disposed=false,frameCalls=0;const context={host,signal:controller.signal,qa,reducedMotion,viewport,finish(correct,detail){if(disposed||finishes.length)return false;finishes.push({correct,detail});return true},later(fn,ms){const job={fn,ms,active:true};jobs.push(job);return job},setDeadline(ms,fn){deadline={ms,fn,active:true};return deadline},frame(){frameCalls++;return()=>{}},listen(target,type,fn,options){target.addEventListener(type,fn,options);const row={target,type,fn,options};listeners.add(row);return()=>{target.removeEventListener(type,fn,options);listeners.delete(row)}}};const runOne=()=>{const job=jobs.find(value=>value.active);if(job&&!disposed){job.active=false;job.fn()}return job};const runAll=()=>{let guard=0;while(jobs.some(job=>job.active)){if(++guard>100)throw Error("pending loop");runOne()}};const triggerDeadline=()=>{if(deadline?.active&&!disposed){deadline.active=false;deadline.fn()}};const dispose=()=>{if(disposed)return;controller.abort();disposed=true;jobs.forEach(job=>job.active=false);if(deadline)deadline.active=false;for(const row of listeners)row.target.removeEventListener(row.type,row.fn,row.options);listeners.clear()};return{context,host,qa,finishes,runOne,runAll,triggerDeadline,dispose,get delays(){return jobs.filter(job=>job.active).map(job=>job.ms)},get pending(){return jobs.filter(job=>job.active).length},get listeners(){return listeners.size},get frameCalls(){return frameCalls}}}
const event=(type,props={})=>{const value=new Event(type,{bubbles:true,cancelable:true});for(const[key,item]of Object.entries(props))Object.defineProperty(value,key,{value:item});return value};
const stage=host=>host.children[1],note=host=>stage(host).children[0],work=host=>stage(host).children[1],shelf=host=>work(host).children[0],box=host=>work(host).children[1],finishButton=host=>stage(host).children[3],terminal=host=>stage(host).children[4],video=host=>stage(host).children[5];
const itemButton=(host,id)=>[...shelf(host).children,...box(host).children].find(node=>node.dataset?.id===id);
const settleMove=(api,h,id,inside=true)=>{assert.equal(inside?api.pack(id):api.remove(id),true);assert.ok(h.delays.every(ms=>ms>0));h.runAll();return api.inspect()};
const packPath=(api,h,path)=>path.forEach(id=>settleMove(api,h,id,true));
function independent(task,ids){const chosen=task.items.filter(item=>ids.includes(item.id)),size=chosen.reduce((a,b)=>a+b.size,0),supportive=chosen.filter(item=>item.kind==="supportive").length,intrusive=chosen.filter(item=>item.kind==="intrusive").length,base=chosen.reduce((a,b)=>a+b.base,0),timely=chosen.reduce((a,b)=>a+(b.kind==="supportive"&&task.timely.includes(b.id)?2:0),0),score=base+timely;return{outcome:!chosen.length||size>task.capacity?"invalid":intrusive?"intrusive":supportive>=task.minItems&&score>=task.minScore?"success":"mixed",size,supportive,intrusive,base,timely,score}}
function enumerate(task){const counts={invalid:0,mixed:0,intrusive:0,success:0};let best=null;for(let mask=0;mask<512;mask++){const ids=task.items.filter((_,i)=>mask&(1<<i)).map(x=>x.id),row=independent(task,ids);counts[row.outcome]++;if(row.outcome==="success"&&(!best||row.score>best.score||row.score===best.score&&row.size<best.size||row.score===best.score&&row.size===best.size&&ids.join("/")<best.ids.join("/")))best={...row,ids}}return{counts,best}}

test("metadata and module interface reserve the requested social identity",()=>{assert.deepEqual(game.metadata,{id:ID,introducedIn:"2.0",tier:2,flavor:"quirky",step:1,family:"social-care-package",category:"social"});for(const key of["generate","validate","render"])assert.equal(typeof game[key],"function")});
test("3000 generated tasks remain plain, finite, authored, and cover three current messages",()=>{const random=helpers(),seen=new Set();for(let i=0;i<3000;i++){const task=game.generate(random);seen.add(task.scenarioId);assert.deepEqual(game.validate(task),[]);assert.deepEqual(structuredClone(task),task);assert.equal(task.items.length,9);assert.equal(task.proof.totalSubsets,512);assert.equal(Object.values(task.proof.counts).reduce((a,b)=>a+b,0),512)}assert.deepEqual([...seen].sort(),["rain-laundry","report-week","rice-low"])});
test("independent enumeration reproduces all 512 subset counts and canonical maximum",()=>{for(let i=0;i<3;i++){const task=scenarioTask(i),proof=enumerate(task);assert.deepEqual(proof.counts,task.proof.counts);assert.equal(proof.best.score,task.proof.bestScore);assert.deepEqual(proof.best.ids,task.proof.answer);for(const outcome of["invalid","mixed","intrusive","success"])assert.ok(proof.counts[outcome]>0)}});
test("every supportive item steadily adds while either intrusive book has a much larger fixed penalty",()=>{for(let s=0;s<3;s++){const task=scenarioTask(s);for(const item of task.items){const row=independent(task,[item.id]);if(item.kind==="supportive"){assert.ok(row.score>=2);assert.equal(row.outcome,"mixed")}else{assert.equal(row.score,-14);assert.equal(row.outcome,"intrusive")}}assert.deepEqual(task.items.filter(x=>x.kind==="intrusive").map(x=>x.id),["gravure","friends"])}});
test("latest message changes timely bonus but never item classification",()=>{const tasks=[0,1,2].map(scenarioTask),kinds=tasks[0].items.map(item=>[item.id,item.kind]);for(const task of tasks)assert.deepEqual(task.items.map(item=>[item.id,item.kind]),kinds);assert.deepEqual(tasks.map(task=>task.timely),[["rice","pasta"],["noodles","gift"],["underwear","socks"]]);assert.equal(independent(tasks[0],["rice"]).score,6);assert.equal(independent(tasks[1],["rice"]).score,4);for(const task of tasks)assert.equal(independent(task,["gravure"]).outcome,"intrusive")});
test("validator rejects classification, penalty, message, capacity, threshold, and forged proof changes",()=>{const base=scenarioTask(0);for(const mutate of[task=>task.items[0].kind="intrusive",task=>task.items[7].base=-2,task=>task.items[2].size=3,task=>task.message.text="友達を作って",task=>task.timely[0]="gravure",task=>task.capacity=9,task=>task.minScore=1,task=>task.proof.counts.success++]){const task=structuredClone(base);mutate(task);assert.notDeepEqual(game.validate(task),[])}});
test("plain JSON save resumes in a fresh module and success stages reply then original local video still once",async()=>{const restore=installDocument();try{const task=JSON.parse(JSON.stringify(scenarioTask(0))),fresh=await importGame(`fresh-${Date.now()}`),h=harness({reducedMotion:true});assert.deepEqual(fresh.validate(task),[]);fresh.render(task,h.context);const api=h.qa[ID];packPath(api,h,task.proof.answer);assert.equal(api.finish(),true);assert.equal(api.inspect().result,"success");assert.equal(api.inspect().replyVisible,false);h.runOne();assert.equal(api.inspect().receipt,"既読");assert.equal(api.inspect().replyVisible,true);assert.equal(api.inspect().videoVisible,false);h.runOne();assert.equal(api.inspect().videoVisible,true);assert.match(video(h.host).getAttribute("aria-label"),/20歳/);h.runOne();assert.deepEqual(h.finishes.map(x=>[x.correct,x.detail.outcome]),[[true,"success"]]);h.triggerDeadline();h.runAll();assert.equal(h.finishes.length,1)}finally{restore()}});
test("pack, remove, and repack change real capacity and restore score",()=>{const restore=installDocument();try{const task=scenarioTask(1),h=harness();game.render(task,h.context);const api=h.qa[ID],empty=api.inspect().evaluation;let state=settleMove(api,h,"noodles");assert.equal(state.evaluation.score,5);assert.equal(state.evaluation.size,2);assert.ok(state.evaluation.score>empty.score);state=settleMove(api,h,"gift");assert.equal(state.evaluation.score,11);state=settleMove(api,h,"noodles",false);assert.deepEqual(state.selected,["gift"]);assert.equal(state.evaluation.score,6);state=settleMove(api,h,"noodles");assert.deepEqual(state.selected,["gift","noodles"]);assert.equal(itemButton(h.host,"noodles").getAttribute("aria-pressed"),"true")}finally{restore()}});
test("capacity overflow is invalid, preserves the box, and recovers without auto-finish",()=>{const restore=installDocument();try{const task=scenarioTask(0),h=harness({reducedMotion:true});game.render(task,h.context);const api=h.qa[ID];packPath(api,h,["rice","noodles","pasta","canned"]);assert.equal(api.inspect().evaluation.size,8);assert.equal(api.pack("gift"),false);assert.equal(api.inspect().invalid,true);assert.deepEqual(api.inspect().selected,["rice","noodles","pasta","canned"]);assert.equal(api.inspect().done,false);h.runAll();assert.equal(api.inspect().invalid,false);assert.equal(api.remove("canned"),true);h.runAll();assert.equal(api.pack("gift"),true);h.runAll();assert.equal(api.inspect().evaluation.size,8)}finally{restore()}});
test("photo book and friends book each force intrusive result, large negative score, read receipt, and no reply",()=>{const restore=installDocument();try{for(const id of["gravure","friends"]){const task=scenarioTask(2),h=harness({reducedMotion:true});game.render(task,h.context);const api=h.qa[ID];packPath(api,h,["noodles","pasta",id]);assert.equal(api.inspect().evaluation.outcome,"intrusive");assert.ok(api.inspect().evaluation.score<0);api.finish();assert.equal(stage(h.host).dataset.result,"intrusive");assert.match(terminal(h.host).textContent,id==="gravure"?/水着グラビア/:/友達の作り方/);h.runOne();assert.equal(api.inspect().receipt,"既読");assert.equal(api.inspect().replyVisible,false);assert.equal(note(h.host).children[2].textContent,"既読");h.runAll();assert.deepEqual(h.finishes.map(x=>[x.correct,x.detail.outcome]),[[false,"intrusive"]]);h.dispose()}}finally{restore()}});
test("mixed supportive parcel is distinct from intrusive and leaves the original memo read without reply",()=>{const restore=installDocument();try{const task=scenarioTask(0),h=harness({reducedMotion:true});game.render(task,h.context);const api=h.qa[ID];packPath(api,h,["canned","socks"]);assert.equal(api.inspect().evaluation.outcome,"mixed");api.finish();assert.equal(stage(h.host).dataset.result,"mixed");assert.match(terminal(h.host).textContent,/害のある品はありません/);h.runAll();assert.deepEqual(h.finishes.map(x=>[x.correct,x.detail.outcome]),[[false,"mixed"]]);assert.equal(api.inspect().receipt,"既読");assert.equal(api.inspect().replyVisible,false);assert.equal(api.inspect().videoVisible,false)}finally{restore()}});
test("timeout retains the partly packed box as unsent and commits once",()=>{const restore=installDocument();try{const task=scenarioTask(1),h=harness();game.render(task,h.context);const api=h.qa[ID];packPath(api,h,["gift","pasta"]);const before=api.inspect();h.triggerDeadline();assert.equal(api.inspect().result,"timeout");assert.deepEqual(api.inspect().selected,before.selected);assert.equal(stage(h.host).dataset.result,"timeout");assert.equal(api.inspect().receipt,"");h.runAll();assert.deepEqual(h.finishes.map(x=>[x.correct,x.detail.outcome]),[[false,"timeout"]]);h.triggerDeadline();h.runAll();assert.equal(h.finishes.length,1)}finally{restore()}});
test("captured touch drag puts a material item into the physical box and dragging out removes it",()=>{const restore=installDocument();try{const task=scenarioTask(0),h=harness({reducedMotion:true});game.render(task,h.context);const api=h.qa[ID],target=box(h.host);target.getBoundingClientRect=()=>({left:200,top:100,right:380,bottom:500,width:180,height:400});const button=itemButton(h.host,"rice"),pointerId=7;button.dispatchEvent(event("pointerdown",{pointerId,pointerType:"touch",clientX:40,clientY:140}));button.dispatchEvent(event("pointermove",{pointerId,pointerType:"touch",clientX:250,clientY:180}));assert.equal(api.inspect().drag.id,"rice");button.dispatchEvent(event("pointerup",{pointerId,pointerType:"touch",clientX:250,clientY:180}));h.runAll();assert.deepEqual(api.inspect().selected,["rice"]);assert.equal(button.getAttribute("aria-pressed"),"true");button.dispatchEvent(event("pointerdown",{pointerId:8,pointerType:"touch",clientX:250,clientY:180}));button.dispatchEvent(event("pointerup",{pointerId:8,pointerType:"touch",clientX:40,clientY:180}));h.runAll();assert.deepEqual(api.inspect().selected,[]);assert.equal(button.getAttribute("aria-pressed"),"false")}finally{restore()}});
test("keyboard pack/remove, focus, labels, reduced nonzero stages, and DPR3 stay usable",()=>{const restore=installDocument();try{const task=scenarioTask(2),h=harness({reducedMotion:true,viewport:{width:402,height:874,dpr:3}});game.render(task,h.context);const api=h.qa[ID],button=itemButton(h.host,"noodles");assert.equal(document.activeElement,itemButton(h.host,"noodles"));button.dispatchEvent(event("keydown",{key:"Enter"}));assert.equal(api.inspect().busy,true);assert.ok(h.delays.length===2&&h.delays.every(ms=>ms>0));h.runAll();assert.equal(api.inspect().selected[0],"noodles");assert.equal(api.inspect().dpr,3);assert.match(button.getAttribute("aria-label"),/箱の中/);button.dispatchEvent(event("keydown",{key:"Delete"}));h.runAll();assert.deepEqual(api.inspect().selected,[]);assert.equal(h.frameCalls,0);assert.equal(stage(h.host).dataset.reduced,"true");assert.match(stage(h.host).getAttribute("aria-label"),/成人/)}finally{restore()}});
test("dispose during movement and terminal stages cancels owned work, deadline, listeners, QA, and finish",()=>{const restore=installDocument();try{let h=harness(),task=scenarioTask(0);game.render(task,h.context);h.qa[ID].pack("rice");assert.ok(h.pending>0);h.dispose();h.runAll();h.triggerDeadline();assert.equal(h.pending,0);assert.equal(h.listeners,0);assert.equal(h.qa[ID],undefined);assert.deepEqual(h.finishes,[]);h=harness();game.render(task,h.context);packPath(h.qa[ID],h,task.proof.answer);h.qa[ID].finish();assert.ok(h.pending>0);h.dispose();h.runAll();assert.deepEqual(h.finishes,[])}finally{restore()}});
test("real runtime disposal leaves no packing or reply stages alive",async()=>{const restore=installDocument(),previousRaf=globalThis.requestAnimationFrame,previousCancel=globalThis.cancelAnimationFrame;globalThis.requestAnimationFrame=callback=>setTimeout(()=>callback(performance.now()),0);globalThis.cancelAnimationFrame=id=>clearTimeout(id);try{const task=scenarioTask(0),qa={},finishes=[],host=document.createElement("div"),runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,detail)=>finishes.push({correct,detail})});game.render(task,runtime.context);qa[ID].pack("rice");assert.ok(runtime.inspect().timeouts>=3);runtime.dispose();await delay(240);assert.equal(qa[ID],undefined);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{restore();if(previousRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=previousRaf;if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}});
test("render creates all nodes from host.ownerDocument",()=>{const previous=globalThis.document,foreign=fakeDocument("foreign");globalThis.document={createElement(){throw Error("global document used")}};try{const h=harness({ownerDocument:foreign});game.render(scenarioTask(0),h.context);const visit=node=>{assert.equal(node.ownerDocument,foreign);for(const child of node.children||[])visit(child)};visit(h.host);h.dispose()}finally{if(previous===undefined)delete globalThis.document;else globalThis.document=previous}});
test("source is ownerDocument-only, tracked, local, asset-free, audio-free, network-free, and emoji-free",()=>{assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|webkitAudioContext|new Audio)\b/);assert.doesNotMatch(source,/<img|\.png|\.jpe?g|\.webp|\.svg/i);assert.doesNotMatch(source,/[\u{1F300}-\u{1FAFF}]/u)});
