import game from "../src/games/social-thread-vibe-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";

const params=new URLSearchParams(location.search),scene=params.get("scene")||"initial",reduced=params.get("motion")==="reduced",width=Number(params.get("width"))||393,family=Math.max(0,Math.min(4,Number(params.get("family"))||0));
document.body.style.width=`${width}px`;
const persistedTask=game.generate({pick:values=>values[family],shuffle:values=>[...values]}),task=JSON.parse(JSON.stringify(persistedTask)),taskJson=JSON.stringify(task);let taskHash=2166136261;for(let index=0;index<taskJson.length;index++)taskHash=Math.imul(taskHash^taskJson.charCodeAt(index),16777619)>>>0;const taskIdentity={scenarioId:task.scenarioId,title:task.title,bytes:taskJson.length,hash:taskHash.toString(16).padStart(8,"0"),seedNumbers:task.seed.map(post=>post.no),incomingNumbers:task.turns.map(turn=>turn.incoming.no),answer:[...task.answer],wins:task.wins,total:task.total};
const host=document.querySelector("#challenge"),result=document.querySelector("#result"),qa={},resourcesBefore=performance.getEntriesByType("resource").length,started=performance.now();let outcome=null;
const runtime=createGameRuntime({host,qa,reducedMotion:reduced,viewport:{width,height:innerHeight,dpr:devicePixelRatio},onFinish:(correct,detail)=>{outcome={correct,detail};result.hidden=true;result.textContent=`${correct?"適温":"要調整"} — ${detail.detail}`}});
game.render(structuredClone(task),runtime.context);
const api=qa[game.metadata.id],wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),stageDelay=reduced?125:360,roundDelay=reduced?280:760,designatedChoice=task.turns[0].choices.find(choice=>choice.id===task.answer[0]),designatedIndex=task.turns[0].choices.indexOf(designatedChoice),causalMatch=/^causal-t([123])-(choice|reply|followup)$/.exec(scene),evidenceTurn=causalMatch?Number(causalMatch[1])-1:0,evidencePhase=causalMatch?.[2]||null,evidenceChoice=task.turns[evidenceTurn].choices.find(choice=>choice.id===task.answer[evidenceTurn]);
async function playPath(path){for(const choiceId of path){api.select(choiceId);await wait(roundDelay)}}
if(causalMatch){for(let index=0;index<evidenceTurn;index++){api.select(task.answer[index]);await wait(roundDelay)}const evidenceIndex=task.turns[evidenceTurn].choices.indexOf(evidenceChoice);if(evidencePhase==="choice")document.querySelectorAll(".stv-option")[evidenceIndex]?.focus();else{api.select(evidenceChoice.id);if(evidencePhase==="followup")await wait(stageDelay);runtime.dispose()}}
else if(scene==="input")document.querySelectorAll(".stv-option")[designatedIndex]?.focus();
else if(scene==="reply"){api.select(designatedChoice.id);runtime.dispose()}
else if(scene==="followup"){api.select(designatedChoice.id);await wait(stageDelay);runtime.dispose()}
else if(scene==="progress"){api.select(designatedChoice.id);await wait(roundDelay)}
else if(["success","cold","derail","flame"].includes(scene)){await playPath(api.pathFor(scene));await wait(reduced?150:680)}
else if(scene==="timeout"){api.timeout();await wait(reduced?150:480)}
await wait(reduced?20:330);

const report=()=>{
  const resources=performance.getEntriesByType("resource"),external=resources.filter(entry=>new URL(entry.name).origin!==location.origin),buttons=[...document.querySelectorAll(".stv-option")],thread=document.querySelector(".stv-thread"),threadBox=thread.getBoundingClientRect(),articles=[...thread.querySelectorAll(".stv-post")],firstVisible=articles.find(article=>article.getBoundingClientRect().bottom>threadBox.top+2),firstBox=firstVisible?.getBoundingClientRect(),gameState=api?.inspect()||null,ownPosts=gameState?.posts.filter(post=>post.kind==="you")||[],evidenceOwnPost=ownPosts[evidenceTurn]||null,evidenceFollowups=evidenceOwnPost?gameState.posts.filter(post=>post.kind==="reaction"&&post.no>evidenceOwnPost.no&&post.no<evidenceOwnPost.no+3):[],pickedButton=buttons.find(button=>button.classList.contains("is-picked"));
  return{status:external.length||document.body.scrollWidth>width?"fail":"pass",scene,reduced,width,family,taskIdentity,designatedChoice:{id:designatedChoice.id,text:designatedChoice.text},firstOwnPost:gameState?.posts.find(post=>post.kind==="you")||null,causalEvidence:{turn:evidenceTurn+1,phase:evidencePhase,choice:{id:evidenceChoice.id,text:evidenceChoice.text,replyTo:evidenceChoice.replyTo},ownPost:evidenceOwnPost,followups:evidenceFollowups,pickedChoiceId:pickedButton?.dataset.id||null,focusedChoiceId:buttons.find(button=>button===document.activeElement)?.dataset.id||null},threadBoundary:{complete:!firstBox||Math.abs(firstBox.top-(threadBox.top+1))<=2,firstVisibleNo:firstVisible?Number(firstVisible.querySelector(".stv-no")?.textContent):null,scrollTop:thread.scrollTop,tailPad:getComputedStyle(thread,"::after").height},elapsedMs:performance.now()-started,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio,bodyScrollWidth:document.body.scrollWidth,bodyScrollHeight:document.body.scrollHeight},game:gameState,runtime:runtime.inspect(),outcome,focusVisible:buttons.includes(document.activeElement),designatedFocused:document.activeElement===buttons[designatedIndex],touchTargets:buttons.map(button=>{const box=button.getBoundingClientRect();return{width:box.width,height:box.height}}),resourcesAdded:resources.length-resourcesBefore,external:external.map(entry=>entry.name)};
};
window.__STV_FIXTURE__={game,task,qa,runtime,report};document.documentElement.dataset.ready="true";
