import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {performance} from "node:perf_hooks";
import {createGameRuntime} from "../src/game-kernel.js";
const moduleUrl=new URL("../src/games/social-greeting-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8"),legacySource=await readFile(new URL("../app.js",import.meta.url),"utf8"),moduleFixtureSource=await readFile(new URL("social-greeting-v1.fixture.html",import.meta.url),"utf8"),legacyFixtureSource=await readFile(new URL("social-greeting-v1.legacy-fixture.html",import.meta.url),"utf8"),game=(await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`)).default,ID="social-greeting-v1";
const ROWS=[["朝、近所の人に会いました。","おはようございます",["おやすみなさい","いただきます","ごちそうさま"]],["お店で先に会計を譲ってもらいました。","ありがとうございます",["いってきます","おかえりなさい","はじめまして"]],["久しぶりに友人に会いました。","お久しぶりです",["いってらっしゃい","おつかれさま、また明日","ただいま"]]],HELP="いちばん自然なあいさつを。",TIMEOUT_DETAIL="時間切れです。脳は定時退社しました。";
const fixedTask=(rowIndex=0,options=[...ROWS[rowIndex].slice(1,2),...ROWS[rowIndex][2]])=>{const row=ROWS[rowIndex];return{kind:"choice",prompt:`${row[0]} なんと言う？`,help:HELP,options:[...options],answer:row[1],duration:7000}};
const permutations=values=>values.length<2?[values]:values.flatMap((value,index)=>permutations([...values.slice(0,index),...values.slice(index+1)]).map(rest=>[value,...rest]));
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}sync(){this.owner._className=[...this.values].join(" ")}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}toggle(value,force){const next=force===undefined?!this.values.has(value):Boolean(force);next?this.values.add(value):this.values.delete(value);this.sync();return next}}
class FakeElement extends EventTarget{constructor(tagName,ownerDocument){super();this.tagName=tagName.toUpperCase();this.ownerDocument=ownerDocument;this.parentNode=null;this.children=[];this.attributes=new Map();this.dataset={};this.style={};this.classList=new FakeClassList(this);this._className="";this._textContent="";this.type="";this.disabled=false;this.tabIndex=-1}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}set textContent(value){this._textContent=String(value);this.children=[]}get textContent(){return this._textContent+this.children.map(child=>child.textContent||"").join("")}append(...nodes){for(const node of nodes){if(node?.parentNode){const old=node.parentNode.children.indexOf(node);if(old>=0)node.parentNode.children.splice(old,1)}if(node&&typeof node==="object")node.parentNode=this;this.children.push(node)}}replaceChildren(...nodes){this.children=[];this._textContent="";this.append(...nodes)}setAttribute(name,value){this.attributes.set(name,String(value))}getAttribute(name){return this.attributes.get(name)??null}focus(){this.ownerDocument.activeElement=this;this.dispatchEvent(new Event("focus"))}blur(){if(this.ownerDocument.activeElement===this)this.ownerDocument.activeElement=null}getBoundingClientRect(){return{width:this.ownerDocument.viewportWidth,height:330,left:0,top:0,right:this.ownerDocument.viewportWidth,bottom:330}}}
function fakeDocument(){const doc={activeElement:null,viewportWidth:393,defaultView:new EventTarget()};doc.createElement=tag=>new FakeElement(tag,doc);return doc}
function harness({task=fixedTask(),reducedMotion=false,width=393,dpr=3}={}){const doc=fakeDocument(),host=doc.createElement("div"),controller=new AbortController(),qa={},pending=[],listeners=new Set(),frames=new Set(),finishes=[];let clock=0,disposed=false,finishCalls=0,order=0;doc.viewportWidth=width;const context={host,qa,signal:controller.signal,reducedMotion,viewport:{width,height:852,dpr},later(fn,ms){const job={fn,at:clock+Math.max(0,Number(ms)||0),order:order++,active:true};pending.push(job);return job},setDeadline(ms,fn){return context.later(fn,ms)},frame(fn){frames.add(fn);return()=>frames.delete(fn)},listen(target,type,fn,options){target.addEventListener(type,fn,options);const row={target,type,fn,options};listeners.add(row);return()=>{target.removeEventListener(type,fn,options);listeners.delete(row)}},finish(correct,payload){finishCalls++;if(disposed||finishes.length)return false;finishes.push({correct:Boolean(correct),payload});return true}};game.render(task,context);const next=()=>pending.filter(job=>job.active).sort((a,b)=>a.at-b.at||a.order-b.order)[0]||null,runTo=target=>{let job=next(),guard=0;while(job&&job.at<=target&&!disposed&&guard++<100){clock=job.at;job.active=false;job.fn();job=next()}clock=target},runFor=ms=>runTo(clock+ms),dispose=()=>{if(disposed)return;disposed=true;pending.forEach(job=>job.active=false);frames.clear();controller.abort();listeners.forEach(({target,type,fn,options})=>target.removeEventListener(type,fn,options));listeners.clear()};return{context,doc,host,qa,finishes,runTo,runFor,dispose,get clock(){return clock},get pendingCount(){return pending.filter(job=>job.active).length},get frameCount(){return frames.size},get listenerCount(){return listeners.size},get finishCalls(){return finishCalls}}}
const apiOf=h=>h.qa[ID],eventWith=(type,properties={})=>{const event=new Event(type,{bubbles:true,cancelable:true});for(const[key,value]of Object.entries(properties))Object.defineProperty(event,key,{value});return event};

test("metadata identifies the exact published v1.15 greeting port",()=>{assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.15",tier:1,flavor:"classic",step:1,family:"social-greeting",category:"social"})});
test("current source authority still contains the exact three-row factory and generic choice contract",()=>{assert.match(legacySource,/\{id:"social-greeting-v1",version:"1\.15",category:"social",make:\(\)=>\{const rows=\[\["朝、近所の人に会いました。","おはようございます",\["おやすみなさい","いただきます","ごちそうさま"\]\],\["お店で先に会計を譲ってもらいました。","ありがとうございます",\["いってきます","おかえりなさい","はじめまして"\]\],\["久しぶりに友人に会いました。","お久しぶりです",\["いってらっしゃい","おつかれさま、また明日","ただいま"\]\]\],r=pick\(rows\);return\{kind:"choice",prompt:`\$\{r\[0\]\} なんと言う？`,help:"いちばん自然なあいさつを。",options:shuffle\(\[r\[1\],\.\.\.r\[2\]\]\),answer:r\[1\],duration:7000\}\}\}/);assert.match(legacySource,/task\.kind==="choice"\)\{makeChoices\(task\);startDeadline\(task\.duration,\(\)=>genericTimeout\(task\)\)/);assert.match(legacySource,/finishTask\(v===task\.answer,\{answerLabel:task\.answer\}\)/);assert.match(legacySource,/時間切れです。脳は定時退社しました。/)});
test("generation calls pick then one outer shuffle and preserves every authored field",()=>{for(let rowIndex=0;rowIndex<3;rowIndex++){const trace=[],task=game.generate({pick(values){trace.push(["pick",structuredClone(values)]);return values[rowIndex]},shuffle(values){trace.push(["shuffle",[...values]]);return [...values].reverse()}}),row=ROWS[rowIndex];assert.deepEqual(trace,[['pick',ROWS],['shuffle',[row[1],...row[2]]]]);assert.deepEqual(task,fixedTask(rowIndex,[...row[2]].reverse().concat(row[1])));assert.deepEqual(Object.keys(task),["kind","prompt","help","options","answer","duration"]);assert.doesNotThrow(()=>structuredClone(task));assert.deepEqual(game.validate(task),[])}});
test("all 72 row and option permutations validate without rewriting",()=>{let count=0;for(let rowIndex=0;rowIndex<ROWS.length;rowIndex++){const values=[ROWS[rowIndex][1],...ROWS[rowIndex][2]];for(const order of permutations(values)){const task=fixedTask(rowIndex,order);assert.deepEqual(game.validate(task),[]);assert.deepEqual(task.options,order);count++}}assert.equal(count,72)});
test("hostile helpers are attempted in order and fall back finitely",()=>{const trace=[],task=game.generate({pick(){trace.push("pick");throw new Error("hostile")},shuffle(values){trace.push(["shuffle",[...values]]);return [values[0],values[0]]}});assert.deepEqual(trace,["pick",["shuffle",[ROWS[0][1],...ROWS[0][2]]]]);assert.deepEqual(task,fixedTask());assert.deepEqual(game.generate({}),fixedTask())});
test("validator rejects extras, copy edits, mixed rows, answers, options, and duration retunes",()=>{const broken={...fixedTask(),extra:true,kind:"expression",prompt:"朝、近所の人に会いました。なんと言う？",help:"丁寧に",options:["ありがとうございます","ありがとうございます","ただいま","新語"],answer:"ありがとうございます",duration:1},issues=game.validate(broken).join(" | ");for(const fragment of["fields","kind","help","duration","prompt","answer","options"])assert.match(issues,new RegExp(fragment));assert.deepEqual(game.validate(null),["task must be a plain choice object"])});
test("render is ownerDocument-only and exposes four equal uncued choices in frozen order",()=>{const task=fixedTask(2,["ただいま","お久しぶりです","いってらっしゃい","おつかれさま、また明日"]),h=harness({task}),api=apiOf(h),state=api.inspect();assert.equal(api.elements.buttons.length,4);assert.ok(api.elements.buttons.every(button=>button.ownerDocument===h.doc));assert.deepEqual(state.optionText,task.options);assert.deepEqual(state.classes,["sg-choice","sg-choice","sg-choice","sg-choice"]);assert.equal(state.disabled,0);assert.equal(state.status,"");assert.equal(state.result,null);assert.equal(state.dpr,3);assert.ok(api.elements.buttons.every((button,index)=>button.getAttribute("aria-label")===`候補${index+1} ${task.options[index]}`));assert.ok(api.elements.buttons.every(button=>button.getAttribute("data-answer")===null&&button.getAttribute("data-correct")===null));const longButton=api.elements.buttons[3],copy=longButton.children[0];assert.equal(longButton.textContent,"おつかれさま、また明日");assert.ok(copy.classList.contains("balanced"));assert.deepEqual(copy.children.map(node=>node.textContent),["おつかれさま、","また明日"]);assert.equal(h.doc.activeElement,api.elements.stage);h.dispose()});
test("all twelve authored choices use equality against the selected row and exact generic payload",()=>{for(let rowIndex=0;rowIndex<3;rowIndex++){const task=fixedTask(rowIndex),answer=task.answer;for(let index=0;index<4;index++){const h=harness({task:structuredClone(task)}),api=apiOf(h),correct=task.options[index]===answer;assert.equal(api.choose(index),true);assert.equal(api.inspect().correct,correct);h.runFor(180);assert.deepEqual(h.finishes,[{correct,payload:{answerLabel:answer}}]);assert.equal(h.finishCalls,1)}}});
test("real touch selection locks immediately and keeps a tracked 180ms success frame",()=>{const h=harness(),api=apiOf(h),button=api.elements.buttons[0];button.dispatchEvent(eventWith("pointerdown",{pointerType:"touch"}));let state=api.inspect();assert.equal(state.phase,"success");assert.equal(state.selectedValue,"おはようございます");assert.equal(state.disabled,4);assert.ok(state.classes[0].includes("correct"));assert.equal(h.finishes.length,0);h.runFor(179);assert.equal(h.finishes.length,0);h.runFor(1);assert.deepEqual(h.finishes,[{correct:true,payload:{answerLabel:"おはようございます"}}]);assert.equal(api.choose(1),false)});
test("wrong feedback is selected-only and returns no invented detail",()=>{const h=harness(),api=apiOf(h);assert.equal(api.choose(1),true);const state=api.inspect();assert.equal(state.phase,"wrong");assert.equal(state.selectedValue,"おやすみなさい");assert.equal(state.status,"不正解");assert.ok(state.classes[1].includes("wrong"));assert.ok(state.classes.filter(value=>value.includes("wrong")).length===1);h.runFor(180);assert.deepEqual(h.finishes,[{correct:false,payload:{answerLabel:"おはようございます"}}])});
test("exact 7000ms generic timeout commits once with authored answerLabel",()=>{const h=harness(),api=apiOf(h);h.runTo(6999);assert.equal(h.finishes.length,0);h.runTo(7000);assert.equal(api.inspect().phase,"timeout");assert.equal(api.inspect().status,TIMEOUT_DETAIL);assert.deepEqual(h.finishes,[{correct:false,payload:{detail:TIMEOUT_DETAIL,answerLabel:"おはようございます"}}]);assert.equal(api.timeout(),false);h.runFor(1000);assert.equal(h.finishCalls,1)});
test("a choice at 6999ms owns the result and the deadline cannot overwrite it",()=>{const h=harness(),api=apiOf(h);h.runTo(6999);api.choose(0);h.runTo(7000);assert.equal(api.inspect().phase,"success");assert.equal(h.finishes.length,0);h.runTo(7179);assert.deepEqual(h.finishes,[{correct:true,payload:{answerLabel:"おはようございます"}}]);assert.equal(h.finishCalls,1)});
test("2x2 arrow focus, number activation, and native keyboard click share the checker",()=>{const h=harness(),api=apiOf(h);api.focus(0);api.elements.choices.dispatchEvent(eventWith("keydown",{key:"ArrowRight"}));assert.equal(api.inspect().focused,1);api.elements.choices.dispatchEvent(eventWith("keydown",{key:"ArrowDown"}));assert.equal(api.inspect().focused,3);api.elements.choices.dispatchEvent(eventWith("keydown",{key:"ArrowLeft"}));assert.equal(api.inspect().focused,2);api.elements.choices.dispatchEvent(eventWith("keydown",{key:"ArrowUp"}));assert.equal(api.inspect().focused,0);api.elements.choices.dispatchEvent(eventWith("keydown",{key:"4"}));assert.equal(api.inspect().selectedIndex,3);h.runFor(180);assert.deepEqual(h.finishes,[{correct:false,payload:{answerLabel:"おはようございます"}}]);const native=harness(),nativeApi=apiOf(native);nativeApi.elements.buttons[0].dispatchEvent(eventWith("click",{detail:0}));assert.equal(nativeApi.inspect().phase,"success")});
test("reduced motion preserves finite feedback, clamps DPR, and owns no frame loop",()=>{const h=harness({reducedMotion:true,dpr:5}),api=apiOf(h);assert.equal(api.inspect().reduced,true);assert.equal(api.inspect().dpr,3);assert.equal(h.frameCount,0);api.choose(0);h.runFor(179);assert.equal(h.finishes.length,0);assert.ok(api.inspect().classes[0].includes("correct"));h.runFor(1);assert.equal(h.finishes.length,1);assert.equal(h.frameCount,0)});
test("plain cloned saved tasks resume identically without mutation",()=>{const task=structuredClone(fixedTask(1,["はじめまして","ありがとうございます","いってきます","おかえりなさい"])),before=structuredClone(task),a=harness({task}),b=harness({task:structuredClone(task)});assert.deepEqual(apiOf(a).inspect().optionText,apiOf(b).inspect().optionText);apiOf(a).choose(1);apiOf(b).choose(1);a.runFor(180);b.runFor(180);assert.deepEqual(a.finishes,b.finishes);assert.deepEqual(task,before)});
test("dispose during feedback cancels result, deadline, listeners, QA, and owned work",()=>{const h=harness(),api=apiOf(h);api.choose(0);assert.ok(h.pendingCount>=2);assert.ok(h.listenerCount>0);h.dispose();h.runTo(10000);assert.equal(h.pendingCount,0);assert.equal(h.listenerCount,0);assert.equal(h.frameCount,0);assert.equal(h.finishes.length,0);assert.equal(h.qa[ID],undefined);assert.equal(api.inspect().disposed,true)});
test("real kernel disposal is synchronous and leaves no delayed commit",async()=>{const doc=fakeDocument(),host=doc.createElement("div"),qa={},finishes=[],previousCancel=globalThis.cancelAnimationFrame;globalThis.cancelAnimationFrame=()=>{};try{const runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,payload)=>finishes.push({correct,payload})});game.render(fixedTask(),runtime.context);qa[ID].choose(0);assert.equal(runtime.inspect().frames,0);assert.ok(runtime.inspect().timeouts>=2);runtime.dispose();await delay(240);assert.equal(qa[ID],undefined);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}});
test("300 cold renders stay bounded and task/options never grow",()=>{const started=performance.now();for(let index=0;index<300;index++){const h=harness({task:fixedTask(index%3),reducedMotion:index%2===0});assert.equal(apiOf(h).elements.buttons.length,4);assert.equal(h.host.children.length,2);h.dispose()}assert.ok(performance.now()-started<1200)});
test("source is tracked, offline, ownerDocument-only, audio-free, frame-free, and cue-free",()=>{assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement|localStorage|sessionStorage)\b/);assert.doesNotMatch(source,/data-(?:answer|correct|rule|rank)/);assert.doesNotMatch(source,/\p{Extended_Pictographic}/u);for(const fixture of[moduleFixtureSource,legacyFixtureSource])assert.match(fixture,/prompt-tail\{white-space:nowrap\}/);assert.match(source,/"おつかれさま、また明日"[\s\S]*?"おつかれさま、"[\s\S]*?"また明日"/);assert.match(legacyFixtureSource,/"おつかれさま、","また明日"/)});
