import test from "node:test";
import assert from "node:assert/strict";
import {readFile,stat} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import game from "../src/games/social-date-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";
const ID="social-date-v1",PROMPT="会話をつないで、デートに誘って",HELP="相手の話を受けて、3回選びます。",FAILURE="会話はここでクランクアップしました。",TIMEOUT="考えている間に、閉館時間になりました。";
const AUTHORED=[
{name:"蒼真",age:26,role:"ブックカフェで会った青年",image:"assets/date-anime.webp",alt:"夕方のブックカフェにいる架空の成人男性",closing:"その誘い、うれしい。次の休みに行こう。",steps:[{line:"この店、静かで落ち着くんだ。よく来るの？",answer:"初めて。おすすめの本、教えてくれる？",choices:["初めて。おすすめの本、教えてくれる？","静かすぎて眠くなりそう","本よりスマホのほうが好き"]},{line:"映画の原作になった短編が好きかな。君は映画も観る？",answer:"観るよ。原作と比べるのも楽しそう",choices:["観るよ。原作と比べるのも楽しそう","結末だけ教えて","長い話は全部苦手"]},{line:"今度、その作品の上映があるんだ。",answer:"よかったら、一緒に観に行かない？",choices:["よかったら、一緒に観に行かない？","ひとりで楽しんできて","感想だけあとで送って"]}]},
{name:"蓮",age:32,role:"架空の映画俳優",image:"assets/date-actor.webp",alt:"夕暮れの映画セットにいる架空の成人男性俳優",closing:"いいね。撮影のない日に、二人で行こう。",steps:[{line:"やっと撮影が終わった。今日は少し難しい場面でね。",answer:"おつかれさま。どんなところが難しかったの？",choices:["おつかれさま。どんなところが難しかったの？","有名人も大変だね","それより写真を撮って"]},{line:"言葉より表情で伝える場面だったんだ。静かな映画は好き？",answer:"好き。表情を追うのも面白いよね",choices:["好き。表情を追うのも面白いよね","派手な場面だけ観たい","途中で寝るかも"]},{line:"小さな映画館で、昔の作品を観直したいと思ってる。",answer:"今度、その映画館に一緒に行かない？",choices:["今度、その映画館に一緒に行かない？","場所だけ教えて","誰か誘えば？"]}]},
{name:"理一郎",age:58,role:"美術館で会った紳士",image:"assets/date-gentleman.webp",alt:"閉館前の美術館ラウンジにいる架空の成人男性紳士",closing:"喜んで。次は作品の続きを、ゆっくり話しましょう。",steps:[{line:"この絵の前では、時間が少しゆっくり流れる気がします。",answer:"わかります。どこが一番お好きですか？",choices:["わかります。どこが一番お好きですか？","値段が気になります","そろそろ閉館ですよ"]},{line:"光の描き方ですね。近くに、この画家の小さな展示もあります。",answer:"それも見てみたいです。詳しいんですね",choices:["それも見てみたいです。詳しいんですね","有名なら見ます","説明は短めでお願いします"]},{line:"来週からだそうです。静かな午後にちょうどよさそうだ。",answer:"よろしければ、来週ご一緒しませんか？",choices:["よろしければ、来週ご一緒しませんか？","パンフレットだけください","おひとりでどうぞ"]}]}
],source=await readFile(new URL("../src/games/social-date-v1.js",import.meta.url),"utf8"),legacy=await readFile(new URL("../app.js",import.meta.url),"utf8");
const taskFor=(index=0,shuffle=values=>values)=>game.generate({pick:values=>values[index],shuffle}),copy=value=>structuredClone(value);
class ClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean));this.sync()}sync(){this.owner._className=[...this.values].join(" ")}add(...items){items.forEach(item=>this.values.add(item));this.sync()}remove(...items){items.forEach(item=>this.values.delete(item));this.sync()}contains(item){return this.values.has(item)}}
class Style{constructor(){this.values=new Map()}setProperty(key,value){this.values.set(key,String(value))}getPropertyValue(key){return this.values.get(key)||""}}
class TextNode{constructor(text,ownerDocument){this.ownerDocument=ownerDocument;this.data=String(text);this.children=[]}get textContent(){return this.data}set textContent(value){this.data=String(value)}}
class Element extends EventTarget{constructor(tag,ownerDocument){super();this.tagName=tag.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.parentElement=null;this.attributes=new Map();this.dataset={};this.style=new Style();this.classList=new ClassList(this);this._className="";this._text="";this.type="";this.disabled=false;this.hidden=false;this.tabIndex=-1;this.alt="";this.src=""}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}set textContent(value){this._text=String(value);this.children=[]}get textContent(){return this._text+this.children.map(child=>child?.textContent??"").join("")}append(...nodes){nodes.forEach(node=>{const value=typeof node==="string"?new TextNode(node,this.ownerDocument):node;value.parentElement=this;this.children.push(value)})}replaceChildren(...nodes){this.children=[];this._text="";this.append(...nodes)}setAttribute(key,value){this.attributes.set(key,String(value))}getAttribute(key){return this.attributes.get(key)??null}focus(){this.ownerDocument.activeElement=this}getBoundingClientRect(){return{left:0,top:0,width:320,height:220,right:320,bottom:220}}}
function ownerFor({dpr=3,time=0}={}){const view=new EventTarget();view.devicePixelRatio=dpr;let now=time;view.performance={now:()=>now};const owner={activeElement:null,defaultView:view,now:()=>now,setTime:value=>{now=value}};owner.createElement=tag=>new Element(tag,owner);return owner}
function event(type,properties={}){const value=new Event(type,{bubbles:true,cancelable:true});for(const[key,item]of Object.entries(properties))Object.defineProperty(value,key,{value:item});return value}
function harness({reduced=false,viewport={width:393,height:852,dpr:3},owner=ownerFor({dpr:viewport.dpr})}={}){const controller=new AbortController(),host=owner.createElement("div"),qa={},jobs=[],listeners=new Set(),finishes=[];let deadline=null,disposed=false,frameCalls=0;const context={host,signal:controller.signal,qa,reducedMotion:reduced,viewport,finish(correct,result){if(disposed||finishes.length)return false;finishes.push({correct,result});return true},later(fn,ms){const job={fn,ms,at:owner.now()+ms,active:true};jobs.push(job);return job},setDeadline(ms,fn){deadline={fn,ms,active:true};return deadline},frame(){frameCalls++;return()=>{}},listen(target,type,fn,options){target.addEventListener(type,fn,options);const item={target,type,fn,options};listeners.add(item);return()=>{target.removeEventListener(type,fn,options);listeners.delete(item)}}};const runNext=()=>{const job=jobs.filter(value=>value.active).sort((a,b)=>a.at-b.at)[0];if(!job||disposed)return false;owner.setTime(Math.max(owner.now(),job.at));job.active=false;job.fn();return true},runAll=()=>{let guard=0;while(runNext()&&guard++<100);assert.ok(guard<100)},triggerDeadline=()=>{if(deadline?.active&&!disposed){deadline.active=false;deadline.fn()}},dispose=()=>{if(disposed)return;controller.abort();disposed=true;jobs.forEach(job=>job.active=false);if(deadline)deadline.active=false;for(const item of listeners)item.target.removeEventListener(item.type,item.fn,item.options);listeners.clear()};return{context,host,owner,qa,finishes,runNext,runAll,triggerDeadline,dispose,get delays(){return jobs.filter(job=>job.active).map(job=>job.ms)},get pending(){return jobs.filter(job=>job.active).length},get listeners(){return listeners.size},get frameCalls(){return frameCalls}}}
const stage=h=>h.host.children[1],scene=h=>stage(h).children[1],portrait=h=>scene(h).children[0],copyNode=h=>scene(h).children[1],speech=h=>copyNode(h).children[2],hearts=h=>copyNode(h).children[3],choices=h=>stage(h).children[2],terminal=h=>stage(h).children[4];
const answer=(api,task,index)=>{assert.equal(api.choose(task.scenario.steps[index].answer),true);if(index<2)assert.equal(api.completeTransition(),true)};

test("metadata preserves the published social date identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.0",tier:2,flavor:"wild",step:1,family:"social-date",category:"social"}));
test("current app is still the exact DATE_SCENARIOS, factory, and renderer authority",()=>{assert.match(legacy,/const DATE_SCENARIOS=\[/);assert.match(legacy,/kind:"dateSim",prompt:"会話をつないで、デートに誘って",help:"相手の話を受けて、3回選びます。",scenario,duration:18000/);assert.match(legacy,/scenario\.steps\.forEach\(step=>step\.choices=shuffle\(step\.choices\)\)/);assert.match(legacy,/function renderDateSim\(task\)/);assert.match(legacy,/会話はここでクランクアップしました。/);assert.match(legacy,/考えている間に、閉館時間になりました。/);for(const scenario of AUTHORED)for(const text of[scenario.name,String(scenario.age),scenario.role,scenario.image,scenario.alt,scenario.closing,...scenario.steps.flatMap(step=>[step.line,step.answer,...step.choices])])assert.ok(legacy.includes(text),text)});
test("6000 generations are plain, exact, finite, and cover all families and permutations",()=>{const seen=new Set(),started=performance.now();for(let index=0;index<6000;index++){let call=0;const permutation=Math.floor(index/3)%6,task=game.generate({pick:values=>values[index%3],shuffle:values=>{call++;const orders=[[0,1,2],[0,2,1],[1,0,2],[1,2,0],[2,0,1],[2,1,0]];return orders[permutation].map(i=>values[i])}});assert.equal(call,3);assert.deepEqual(game.validate(task),[]);assert.deepEqual(copy(task),task);assert.deepEqual(Object.keys(task),["kind","prompt","help","scenario","duration"]);seen.add(`${task.scenario.name}:${permutation}`)}assert.ok(seen.size>=18);assert.ok(performance.now()-started<3000)});
test("generation preserves injected order, requires helpers, rejects foreign pick, and bounds hostile shuffle",()=>{const task=taskFor(1,values=>values.reverse());assert.deepEqual(task.scenario.steps.map(step=>step.choices),AUTHORED[1].steps.map(step=>[...step.choices].reverse()));assert.throws(()=>game.generate(),/pick and shuffle/);assert.throws(()=>game.generate({pick:()=>copy(AUTHORED[0]),shuffle:x=>x}),/supplied scenario/);for(const output of[null,[],["x"],Array(3).fill("x"),"bad"]){const value=game.generate({pick:items=>items[0],shuffle:()=>output});assert.deepEqual(value.scenario,AUTHORED[0]);assert.deepEqual(game.validate(value),[])}});
test("validator accepts permutations but rejects every authored field, shape, and additive mutation",()=>{const base=taskFor(),reversed=copy(base);reversed.scenario.steps.forEach(step=>step.choices.reverse());assert.deepEqual(game.validate(reversed),[]);const mutations=[t=>t.extra=true,t=>t.kind="choice",t=>t.prompt="別",t=>t.help="別",t=>t.duration=18001,t=>t.scenario.extra=true,t=>t.scenario.name="別",t=>t.scenario.age=27,t=>t.scenario.role="別",t=>t.scenario.image="assets/other.webp",t=>t.scenario.alt="別",t=>t.scenario.closing="別",t=>t.scenario.steps.pop(),t=>t.scenario.steps[0].extra=true,t=>t.scenario.steps[0].line="別",t=>t.scenario.steps[0].answer=t.scenario.steps[0].choices[1],t=>t.scenario.steps[0].choices[0]=t.scenario.steps[0].choices[1]];for(const [index,mutate]of mutations.entries()){const value=copy(base);mutate(value);assert.ok(game.validate(value).length,`mutation ${index}`)}for(const value of[null,{},[],{scenario:{}}])assert.doesNotThrow(()=>game.validate(value))});
test("render is ownerDocument-isolated and retains exact local portrait identity",async()=>{for(let index=0;index<3;index++){const owner=ownerFor(),h=harness({owner}),task=taskFor(index),previous=globalThis.document;globalThis.document={createElement(){throw Error("global document used")}};try{game.render(task,h.context);const api=h.qa[ID],state=api.inspect(),image=portrait(h).children[0];assert.equal(stage(h).ownerDocument,owner);assert.deepEqual(state.scenario,Object.fromEntries(Object.entries(AUTHORED[index]).filter(([key])=>key!=="steps")));assert.equal(state.imageSrc,AUTHORED[index].image);assert.equal(image.src,AUTHORED[index].image);assert.equal(image.alt,AUTHORED[index].alt);assert.equal(state.hearts,"♡♡♡");assert.equal(state.line,AUTHORED[index].steps[0].line);assert.deepEqual(state.options,AUTHORED[index].steps[0].choices);assert.ok(choices(h).children.every(button=>button.dataset.correct==="false"&&button.dataset.answer===undefined));assert.doesNotMatch(stage(h).textContent,/DATE ACCEPTED|CONVERSATION CUT|CLOSING TIME/);assert.ok((await stat(new URL(`../${AUTHORED[index].image}`,import.meta.url))).size>30000)}finally{h.dispose();if(previous===undefined)delete globalThis.document;else globalThis.document=previous}}});
test("plain JSON resume completes all three exact conversations and one delayed success",()=>{for(let index=0;index<3;index++){const task=JSON.parse(JSON.stringify(taskFor(index))),before=copy(task),h=harness({reduced:true});game.render(task,h.context);const api=h.qa[ID];assert.equal(speech(h).textContent,`「${task.scenario.steps[0].line}」`);assert.equal(hearts(h).textContent,"♡♡♡");answer(api,task,0);assert.equal(api.inspect().stepIndex,1);assert.equal(api.inspect().hearts,"♥♡♡");assert.deepEqual(api.inspect().options,task.scenario.steps[1].choices);answer(api,task,1);assert.equal(api.inspect().stepIndex,2);assert.equal(api.inspect().hearts,"♥♥♡");answer(api,task,2);assert.equal(api.inspect().phase,"closing");assert.equal(api.inspect().line,task.scenario.closing);assert.equal(api.inspect().hearts,"♥♥♥");assert.deepEqual(api.inspect().options,[]);assert.deepEqual(h.finishes,[]);h.runAll();assert.equal(api.inspect().result,"success");assert.equal(api.inspect().finishCalls,1);assert.deepEqual(h.finishes.map(value=>[value.correct,value.result.detail]),[[true,`${task.scenario.name}とのデート成立。予定表も動きました。`]]);assert.ok(h.finishes[0].result.quality>=0&&h.finishes[0].result.quality<=1);h.triggerDeadline();h.runAll();assert.equal(h.finishes.length,1);assert.deepEqual(task,before);h.dispose()}});
test("every published wrong choice at every step fails immediately with the current detail",()=>{for(let scenarioIndex=0;scenarioIndex<3;scenarioIndex++){const task=taskFor(scenarioIndex);for(let stepIndex=0;stepIndex<3;stepIndex++)for(const wrong of task.scenario.steps[stepIndex].choices.filter(value=>value!==task.scenario.steps[stepIndex].answer)){const h=harness();game.render(task,h.context);const api=h.qa[ID];for(let previous=0;previous<stepIndex;previous++)answer(api,task,previous);assert.equal(api.choose(wrong),true);assert.equal(api.inspect().result,"wrong");assert.equal(api.inspect().stepIndex,stepIndex);assert.equal(api.inspect().selected,wrong);assert.equal(terminal(h).children[1].textContent,FAILURE);assert.deepEqual(h.finishes,[{correct:false,result:{detail:FAILURE}}]);h.triggerDeadline();h.runAll();assert.equal(h.finishes.length,1);h.dispose()}}});
test("reduced correct acknowledgement has three nonzero deterministic stages and locks input",()=>{const task=taskFor(),h=harness({reduced:true});game.render(task,h.context);const api=h.qa[ID];assert.equal(api.choose(task.scenario.steps[0].answer),true);assert.equal(api.inspect().busy,true);assert.equal(api.choose(task.scenario.steps[0].choices[1]),false);assert.deepEqual(h.delays,[70,140,220]);h.runNext();assert.equal(api.inspect().ackProgress,.45);h.runNext();assert.equal(api.inspect().ackProgress,.8);h.runNext();assert.equal(api.inspect().stepIndex,1);assert.equal(api.inspect().hearts,"♥♡♡");assert.equal(h.frameCalls,0);h.dispose()});
test("third answer preserves the exact 450ms finish delay and elapsed quality formula",()=>{const owner=ownerFor({time:1000}),task=taskFor(2),h=harness({owner});game.render(task,h.context);const api=h.qa[ID];answer(api,task,0);answer(api,task,1);owner.setTime(9000);answer(api,task,2);assert.ok(h.delays.includes(450));assert.deepEqual(h.finishes,[]);api.completeFinish();assert.equal(h.finishes[0].result.quality,1-8000/18000);assert.equal(h.finishes[0].result.detail,"理一郎とのデート成立。予定表も動きました。");h.runAll();assert.equal(h.finishes.length,1);h.dispose()});
test("deadline retains initial or partial progress and completes an acknowledged answer first",()=>{let task=taskFor(1),h=harness();game.render(task,h.context);h.triggerDeadline();assert.equal(h.qa[ID].inspect().stepIndex,0);assert.equal(h.qa[ID].inspect().line,task.scenario.steps[0].line);assert.deepEqual(h.finishes,[{correct:false,result:{detail:TIMEOUT}}]);h.dispose();h=harness({reduced:true});game.render(task,h.context);const api=h.qa[ID];answer(api,task,0);api.choose(task.scenario.steps[1].answer);h.triggerDeadline();const state=api.inspect();assert.equal(state.result,"timeout");assert.equal(state.stepIndex,2);assert.equal(state.hearts,"♥♥♡");assert.equal(state.line,task.scenario.steps[2].line);assert.deepEqual(state.options,task.scenario.steps[2].choices);assert.deepEqual(h.finishes,[{correct:false,result:{detail:TIMEOUT}}]);h.runAll();assert.equal(h.finishes.length,1);h.dispose()});
test("a deadline inside the published 450ms closing window wins and cannot become success",()=>{const task=taskFor(),h=harness();game.render(task,h.context);const api=h.qa[ID];answer(api,task,0);answer(api,task,1);answer(api,task,2);assert.equal(api.inspect().phase,"closing");h.triggerDeadline();assert.equal(api.inspect().result,"timeout");assert.equal(api.inspect().line,task.scenario.closing);assert.equal(api.inspect().hearts,"♥♥♥");h.runAll();assert.deepEqual(h.finishes,[{correct:false,result:{detail:TIMEOUT}}]);h.dispose()});
test("touch, arrows, number keys, Enter, focus, and choice labels share selection",()=>{const task=taskFor(),h=harness();game.render(task,h.context);const api=h.qa[ID],group=choices(h);assert.equal(h.owner.activeElement,group.children[0]);group.dispatchEvent(event("keydown",{key:"ArrowDown"}));assert.equal(api.inspect().focusIndex,1);assert.equal(h.owner.activeElement,group.children[1]);group.dispatchEvent(event("keydown",{key:"ArrowUp"}));group.dispatchEvent(event("keydown",{key:"Enter"}));assert.equal(api.inspect().selected,task.scenario.steps[0].answer);api.completeTransition();const next=choices(h).children[0];next.dispatchEvent(event("pointerdown",{pointerType:"touch",pointerId:7}));assert.equal(api.inspect().selected,task.scenario.steps[1].answer);api.completeTransition();group.dispatchEvent(event("keydown",{key:"1"}));assert.equal(api.inspect().phase,"closing");assert.match(next.getAttribute("aria-label"),/^選択肢1、/);h.dispose()});
test("image failure keeps exact alt data and activates only the local silhouette fallback",()=>{for(let index=0;index<3;index++){const task=taskFor(index),h=harness();game.render(task,h.context);const api=h.qa[ID],image=portrait(h).children[0];assert.equal(api.inspect().fallback,false);image.dispatchEvent(event("error"));assert.equal(api.inspect().fallback,true);assert.equal(image.alt,task.scenario.alt);assert.equal(image.src,task.scenario.image);h.dispose()}});
test("DPR is capped at 3 and 393/402 production hooks remain inspectable",()=>{for(const [width,height]of[[393,852],[402,874]]){const task=taskFor(width===393?0:2),h=harness({viewport:{width,height,dpr:4}});game.render(task,h.context);const state=h.qa[ID].inspect();assert.equal(state.dpr,3);assert.deepEqual(state.viewport,{width,height,dpr:4});assert.equal(stage(h).dataset.reduced,"false");assert.equal(choices(h).children.length,3);assert.equal(portrait(h).children[0].src,task.scenario.image);h.dispose()}});
test("dispose during acknowledgement or final delay clears jobs, listeners, QA, and finish",()=>{const task=taskFor();let h=harness({reduced:true});game.render(task,h.context);h.qa[ID].choose(task.scenario.steps[0].answer);assert.equal(h.pending,3);h.dispose();h.runAll();h.triggerDeadline();assert.equal(h.pending,0);assert.equal(h.listeners,0);assert.equal(h.qa[ID],undefined);assert.deepEqual(h.finishes,[]);h=harness();game.render(task,h.context);answer(h.qa[ID],task,0);answer(h.qa[ID],task,1);answer(h.qa[ID],task,2);assert.ok(h.pending>0);h.dispose();h.runAll();assert.equal(h.qa[ID],undefined);assert.deepEqual(h.finishes,[])});
test("real reduced runtime exposes a midpoint then disposes without delayed progress",async()=>{const previousCancel=globalThis.cancelAnimationFrame;globalThis.cancelAnimationFrame=()=>{};try{const owner=ownerFor(),host=owner.createElement("div"),qa={},finishes=[],runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})}),task=taskFor();game.render(task,runtime.context);qa[ID].choose(task.scenario.steps[0].answer);await delay(90);assert.equal(qa[ID].inspect().ackProgress,.45);runtime.dispose();await delay(220);assert.equal(qa[ID],undefined);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}});
test("200 cold renders stay bounded and source uses tracked local-only ownership",()=>{const started=performance.now();for(let index=0;index<200;index++){const h=harness({reduced:index%2===0});game.render(taskFor(index%3),h.context);assert.equal(h.qa[ID].inspect().options.length,3);h.dispose()}assert.ok(performance.now()-started<1000);assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|webkitAudioContext|new Audio)\b/);assert.doesNotMatch(source,/https?:\/\//);assert.deepEqual([...source.matchAll(/assets\/date-[a-z-]+\.webp/g)].map(match=>match[0]).sort(),["assets/date-actor.webp","assets/date-anime.webp","assets/date-gentleman.webp"])});
