import test from "node:test";
import assert from "node:assert/strict";
import {readFile,stat} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import game from "../src/games/social-partner-mood-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";
const ID="social-partner-mood-v1",PROMPT="不機嫌なパートナーと話して",HELP="火に油を注がず、3回会話をつなぎます。",FAILURE="その一言で、室内の気圧がさらに下がりました。",SUCCESS="低気圧を会話で通過。関係修復ミッション成功。",TIMEOUT="考えている間に、閉館時間になりました。";
const SCENARIO={name:"直樹",age:36,role:"少し不機嫌なパートナー",image:"assets/partner-mood.webp",alt:"雨の夜のキッチンで対話を待つ架空の成人男性パートナー",closing:"うん。ちゃんと話せたら、少し気持ちがほどけた。",successDetail:SUCCESS,failureDetail:FAILURE,steps:[{line:"今日の予定、変更になったのを後から知ったんだけど。",answer:"先に伝えなくてごめん。今、話しても大丈夫？",choices:["先に伝えなくてごめん。今、話しても大丈夫？","そんなに怒ること？","顔がこわいよ"]},{line:"楽しみにしてたから、置いていかれた気がした。",answer:"楽しみにしてた気持ちを、軽く扱ってしまったね",choices:["楽しみにしてた気持ちを、軽く扱ってしまったね","でも仕事だから仕方ないよ","代わりに何か買えばいい？"]},{line:"埋め合わせって、どう考えてる？",answer:"都合を聞いて、二人で次の予定を決めたい",choices:["都合を聞いて、二人で次の予定を決めたい","今すぐ機嫌を直して","同じ予定を勝手に予約しておく"]}]},source=await readFile(new URL("../src/games/social-partner-mood-v1.js",import.meta.url),"utf8"),legacy=await readFile(new URL("../app.js",import.meta.url),"utf8"),copy=value=>structuredClone(value);
const taskFor=(shuffle=values=>values)=>game.generate({shuffle});
class ClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean));this.sync()}sync(){this.owner._className=[...this.values].join(" ")}add(...items){items.forEach(item=>this.values.add(item));this.sync()}remove(...items){items.forEach(item=>this.values.delete(item));this.sync()}contains(item){return this.values.has(item)}}
class Style{constructor(){this.values=new Map()}setProperty(key,value){this.values.set(key,String(value))}getPropertyValue(key){return this.values.get(key)||""}}
class TextNode{constructor(text,ownerDocument){this.ownerDocument=ownerDocument;this.data=String(text);this.children=[]}get textContent(){return this.data}set textContent(value){this.data=String(value)}}
class Element extends EventTarget{constructor(tag,ownerDocument){super();this.tagName=tag.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.parentElement=null;this.attributes=new Map();this.dataset={};this.style=new Style();this.classList=new ClassList(this);this._className="";this._text="";this.type="";this.disabled=false;this.hidden=false;this.tabIndex=-1;this.alt="";this.src=""}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}set textContent(value){this._text=String(value);this.children=[]}get textContent(){return this._text+this.children.map(child=>child?.textContent??"").join("")}append(...nodes){nodes.forEach(node=>{const value=typeof node==="string"?new TextNode(node,this.ownerDocument):node;value.parentElement=this;this.children.push(value)})}replaceChildren(...nodes){this.children=[];this._text="";this.append(...nodes)}setAttribute(key,value){this.attributes.set(key,String(value))}getAttribute(key){return this.attributes.get(key)??null}focus(){this.ownerDocument.activeElement=this}getBoundingClientRect(){return{left:0,top:0,width:320,height:220,right:320,bottom:220}}}
function ownerFor({dpr=3,time=0}={}){const view=new EventTarget();view.devicePixelRatio=dpr;let now=time;view.performance={now:()=>now};const owner={activeElement:null,defaultView:view,now:()=>now,setTime:value=>{now=value}};owner.createElement=tag=>new Element(tag,owner);return owner}
function event(type,properties={}){const value=new Event(type,{bubbles:true,cancelable:true});for(const[key,item]of Object.entries(properties))Object.defineProperty(value,key,{value:item});return value}
function harness({reduced=false,viewport={width:393,height:852,dpr:3},owner=ownerFor({dpr:viewport.dpr})}={}){const controller=new AbortController(),host=owner.createElement("div"),qa={},jobs=[],listeners=new Set(),finishes=[];let deadline=null,disposed=false,frameCalls=0;const context={host,signal:controller.signal,qa,reducedMotion:reduced,viewport,finish(correct,result){if(disposed||finishes.length)return false;finishes.push({correct,result});return true},later(fn,ms){const job={fn,ms,at:owner.now()+ms,active:true};jobs.push(job);return job},setDeadline(ms,fn){deadline={fn,ms,active:true};return deadline},frame(){frameCalls++;return()=>{}},listen(target,type,fn,options){target.addEventListener(type,fn,options);const item={target,type,fn,options};listeners.add(item);return()=>{target.removeEventListener(type,fn,options);listeners.delete(item)}}};const runNext=()=>{const job=jobs.filter(value=>value.active).sort((a,b)=>a.at-b.at)[0];if(!job||disposed)return false;owner.setTime(Math.max(owner.now(),job.at));job.active=false;job.fn();return true},runAll=()=>{let guard=0;while(runNext()&&guard++<100);assert.ok(guard<100)},triggerDeadline=()=>{if(deadline?.active&&!disposed){deadline.active=false;deadline.fn()}},dispose=()=>{if(disposed)return;controller.abort();disposed=true;jobs.forEach(job=>job.active=false);if(deadline)deadline.active=false;for(const item of listeners)item.target.removeEventListener(item.type,item.fn,item.options);listeners.clear()};return{context,host,owner,qa,finishes,runNext,runAll,triggerDeadline,dispose,get delays(){return jobs.filter(job=>job.active).map(job=>job.ms)},get pending(){return jobs.filter(job=>job.active).length},get listeners(){return listeners.size},get frameCalls(){return frameCalls}}}
const stage=h=>h.host.children[1],scene=h=>stage(h).children[1],portrait=h=>scene(h).children[0],copyNode=h=>scene(h).children[1],speech=h=>copyNode(h).children[2],hearts=h=>copyNode(h).children[3],choices=h=>stage(h).children[2],terminal=h=>stage(h).children[4];
const answer=(api,task,index)=>{assert.equal(api.choose(task.scenario.steps[index].answer),true);if(index<2)assert.equal(api.completeTransition(),true)};

test("metadata preserves the published partner-mood identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.0",tier:2,flavor:"quirky",step:1,family:"social-partner-mood",category:"social"}));
test("legacy factory is removed while the exact scenario and renderer authority remain",()=>{assert.match(legacy,/const PARTNER_MOOD_SCENARIO=/);assert.doesNotMatch(legacy,/\{id:"social-partner-mood-v1",version:"1\.0",category:"social",make:/);assert.match(legacy,/function renderDateSim\(task\)/);for(const text of[SCENARIO.name,String(SCENARIO.age),SCENARIO.role,SCENARIO.image,SCENARIO.alt,SCENARIO.closing,SCENARIO.successDetail,SCENARIO.failureDetail,...SCENARIO.steps.flatMap(step=>[step.line,step.answer,...step.choices])])assert.ok(legacy.includes(text),text)});
test("6000 generations call three shuffles, cover all six permutations, and stay exact plain data",()=>{const orders=[[0,1,2],[0,2,1],[1,0,2],[1,2,0],[2,0,1],[2,1,0]],seen=new Set(),started=performance.now();for(let index=0;index<6000;index++){let calls=0;const permutation=index%6,task=taskFor(values=>{calls++;return orders[permutation].map(i=>values[i])});assert.equal(calls,3);assert.deepEqual(game.validate(task),[]);assert.deepEqual(copy(task),task);assert.deepEqual(Object.keys(task),["kind","prompt","help","scenario","duration"]);assert.deepEqual(Object.keys(task.scenario),["name","age","role","image","alt","closing","successDetail","failureDetail","steps"]);seen.add(permutation)}assert.equal(seen.size,6);assert.ok(performance.now()-started<3000)});
test("generation preserves injected order, requires shuffle, and bounds hostile outputs",()=>{const task=taskFor(values=>values.reverse());assert.deepEqual(task.scenario.steps.map(step=>step.choices),SCENARIO.steps.map(step=>[...step.choices].reverse()));assert.throws(()=>game.generate(),/shuffle/);for(const output of[null,[],["x"],Array(3).fill("x"),"bad"]){const value=game.generate({shuffle:()=>output});assert.deepEqual(value.scenario,SCENARIO);assert.deepEqual(game.validate(value),[])}});
test("validator accepts permutations but rejects every task, scenario, detail, and step mutation",()=>{const base=taskFor(),reversed=copy(base);reversed.scenario.steps.forEach(step=>step.choices.reverse());assert.deepEqual(game.validate(reversed),[]);const mutations=[t=>t.extra=true,t=>t.kind="choice",t=>t.prompt="別",t=>t.help="別",t=>t.duration=18000,t=>t.scenario.extra=true,t=>t.scenario.name="別",t=>t.scenario.age=37,t=>t.scenario.role="別",t=>t.scenario.image="assets/other.webp",t=>t.scenario.alt="別",t=>t.scenario.closing="別",t=>t.scenario.successDetail="別",t=>t.scenario.failureDetail="別",t=>t.scenario.steps.pop(),t=>t.scenario.steps[0].extra=true,t=>t.scenario.steps[0].line="別",t=>t.scenario.steps[0].answer=t.scenario.steps[0].choices[1],t=>t.scenario.steps[0].choices[0]=t.scenario.steps[0].choices[1]];for(const[index,mutate]of mutations.entries()){const task=copy(base);mutate(task);assert.ok(game.validate(task).length,`mutation ${index}`)}for(const value of[null,{},[],{scenario:{}}])assert.doesNotThrow(()=>game.validate(value))});
test("render uses ownerDocument and exact checked-in portrait identity",async()=>{const owner=ownerFor(),h=harness({owner}),task=taskFor(),previous=globalThis.document;globalThis.document={createElement(){throw Error("global document used")}};try{game.render(task,h.context);const state=h.qa[ID].inspect(),image=portrait(h).children[0];assert.equal(stage(h).ownerDocument,owner);assert.deepEqual(state.scenario,Object.fromEntries(Object.entries(SCENARIO).filter(([key])=>key!=="steps")));assert.equal(state.imageSrc,SCENARIO.image);assert.equal(image.src,SCENARIO.image);assert.equal(image.alt,SCENARIO.alt);assert.ok((await stat(new URL(`../${SCENARIO.image}`,import.meta.url))).size>60000)}finally{h.dispose();if(previous===undefined)delete globalThis.document;else globalThis.document=previous}});
test("initial and advanced choices expose no answer, outcome, diagnosis, or sentiment leak",()=>{const h=harness(),task=taskFor();game.render(task,h.context);const api=h.qa[ID];for(let step=0;step<3;step++){const state=api.inspect();assert.deepEqual(state.options,task.scenario.steps[step].choices);assert.ok(choices(h).children.every(button=>button.dataset.correct==="false"&&button.dataset.answer===undefined));assert.doesNotMatch(stage(h).textContent,/CONVERSATION COMPLETE|CONVERSATION CUT|CLOSING TIME|sentiment|診断/);if(step<2)answer(api,task,step)}h.dispose()});
test("plain JSON resume follows all exact lines, hearts, closing, and one success detail",()=>{const task=JSON.parse(JSON.stringify(taskFor())),before=copy(task),h=harness({reduced:true});game.render(task,h.context);const api=h.qa[ID];assert.equal(speech(h).textContent,`「${task.scenario.steps[0].line}」`);assert.equal(hearts(h).textContent,"♡♡♡");answer(api,task,0);assert.equal(api.inspect().line,task.scenario.steps[1].line);assert.equal(api.inspect().hearts,"♥♡♡");answer(api,task,1);assert.equal(api.inspect().line,task.scenario.steps[2].line);assert.equal(api.inspect().hearts,"♥♥♡");answer(api,task,2);assert.equal(api.inspect().line,task.scenario.closing);assert.equal(api.inspect().hearts,"♥♥♥");assert.deepEqual(api.inspect().options,[]);h.runAll();assert.deepEqual(h.finishes.map(value=>[value.correct,value.result.detail]),[[true,SUCCESS]]);assert.equal(api.inspect().finishCalls,1);h.triggerDeadline();h.runAll();assert.equal(h.finishes.length,1);assert.deepEqual(task,before);h.dispose()});
test("all six authored wrong choices fail immediately with the exact current failure detail",()=>{const task=taskFor();for(let stepIndex=0;stepIndex<3;stepIndex++)for(const wrong of task.scenario.steps[stepIndex].choices.filter(value=>value!==task.scenario.steps[stepIndex].answer)){const h=harness();game.render(task,h.context);const api=h.qa[ID];for(let previous=0;previous<stepIndex;previous++)answer(api,task,previous);assert.equal(api.choose(wrong),true);assert.equal(api.inspect().result,"wrong");assert.equal(api.inspect().selected,wrong);assert.equal(terminal(h).children[1].textContent,FAILURE);assert.deepEqual(h.finishes,[{correct:false,result:{detail:FAILURE}}]);h.runAll();assert.equal(h.finishes.length,1);h.dispose()}});
test("reduced acknowledgement exposes three deterministic stages and locks repeated input",()=>{const task=taskFor(),h=harness({reduced:true});game.render(task,h.context);const api=h.qa[ID];api.choose(task.scenario.steps[0].answer);assert.equal(api.choose(task.scenario.steps[0].choices[1]),false);assert.deepEqual(h.delays,[70,140,220]);h.runNext();assert.equal(api.inspect().ackProgress,.45);h.runNext();assert.equal(api.inspect().ackProgress,.8);h.runNext();assert.equal(api.inspect().stepIndex,1);assert.equal(api.inspect().hearts,"♥♡♡");assert.equal(h.frameCalls,0);h.dispose()});
test("third answer keeps exact 450ms finish timing and elapsed-over-20000 quality",()=>{const owner=ownerFor({time:1000}),task=taskFor(),h=harness({owner});game.render(task,h.context);const api=h.qa[ID];answer(api,task,0);answer(api,task,1);owner.setTime(10550);answer(api,task,2);assert.ok(h.delays.includes(450));assert.deepEqual(h.finishes,[]);api.completeFinish();assert.equal(h.finishes[0].result.quality,1-9550/20000);assert.equal(h.finishes[0].result.detail,SUCCESS);h.runAll();assert.equal(h.finishes.length,1);h.dispose()});
test("deadline retains initial or acknowledged partial conversation exactly",()=>{const task=taskFor();let h=harness();game.render(task,h.context);h.triggerDeadline();assert.equal(h.qa[ID].inspect().stepIndex,0);assert.deepEqual(h.finishes,[{correct:false,result:{detail:TIMEOUT}}]);h.dispose();h=harness({reduced:true});game.render(task,h.context);const api=h.qa[ID];answer(api,task,0);api.choose(task.scenario.steps[1].answer);h.triggerDeadline();const state=api.inspect();assert.equal(state.result,"timeout");assert.equal(state.stepIndex,2);assert.equal(state.hearts,"♥♥♡");assert.equal(state.line,task.scenario.steps[2].line);assert.deepEqual(state.options,task.scenario.steps[2].choices);assert.deepEqual(h.finishes,[{correct:false,result:{detail:TIMEOUT}}]);h.runAll();assert.equal(h.finishes.length,1);h.dispose()});
test("deadline inside the published closing window wins over delayed success",()=>{const task=taskFor(),h=harness();game.render(task,h.context);const api=h.qa[ID];answer(api,task,0);answer(api,task,1);answer(api,task,2);assert.equal(api.inspect().phase,"closing");h.triggerDeadline();assert.equal(api.inspect().result,"timeout");assert.equal(api.inspect().line,SCENARIO.closing);assert.equal(api.inspect().hearts,"♥♥♥");h.runAll();assert.deepEqual(h.finishes,[{correct:false,result:{detail:TIMEOUT}}]);h.dispose()});
test("touch, arrows, number keys, Enter, focus, and labels select the same choices",()=>{const task=taskFor(),h=harness();game.render(task,h.context);const api=h.qa[ID],group=choices(h);assert.equal(h.owner.activeElement,group.children[0]);group.dispatchEvent(event("keydown",{key:"ArrowDown"}));assert.equal(api.inspect().focusIndex,1);group.dispatchEvent(event("keydown",{key:"ArrowUp"}));group.dispatchEvent(event("keydown",{key:"Enter"}));assert.equal(api.inspect().selected,task.scenario.steps[0].answer);api.completeTransition();const next=choices(h).children[0];next.dispatchEvent(event("pointerdown",{pointerType:"touch",pointerId:7}));assert.equal(api.inspect().selected,task.scenario.steps[1].answer);api.completeTransition();choices(h).dispatchEvent(event("keydown",{key:"1"}));assert.equal(api.inspect().phase,"closing");assert.match(next.getAttribute("aria-label"),/^選択肢1、/);h.dispose()});
test("local image fallback, DPR cap, and 393/402 production hooks remain exact",()=>{for(const[width,height]of[[393,852],[402,874]]){const task=taskFor(),h=harness({viewport:{width,height,dpr:4}});game.render(task,h.context);const api=h.qa[ID],image=portrait(h).children[0];assert.equal(api.inspect().dpr,3);assert.equal(api.inspect().fallback,false);image.dispatchEvent(event("error"));assert.equal(api.inspect().fallback,true);assert.equal(image.alt,SCENARIO.alt);assert.equal(image.src,SCENARIO.image);assert.equal(choices(h).children.length,3);h.dispose()}});
test("dispose during acknowledgement and final delay cancels jobs, listeners, QA, and finish",()=>{const task=taskFor();let h=harness({reduced:true});game.render(task,h.context);h.qa[ID].choose(task.scenario.steps[0].answer);assert.equal(h.pending,3);h.dispose();h.runAll();h.triggerDeadline();assert.equal(h.pending,0);assert.equal(h.listeners,0);assert.equal(h.qa[ID],undefined);assert.deepEqual(h.finishes,[]);h=harness();game.render(task,h.context);answer(h.qa[ID],task,0);answer(h.qa[ID],task,1);answer(h.qa[ID],task,2);h.dispose();h.runAll();assert.equal(h.qa[ID],undefined);assert.deepEqual(h.finishes,[])});
test("real reduced runtime exposes midpoint then disposes without delayed progress",async()=>{const previousCancel=globalThis.cancelAnimationFrame;globalThis.cancelAnimationFrame=()=>{};try{const owner=ownerFor(),host=owner.createElement("div"),qa={},finishes=[],runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})}),task=taskFor();game.render(task,runtime.context);qa[ID].choose(task.scenario.steps[0].answer);await delay(90);assert.equal(qa[ID].inspect().ackProgress,.45);runtime.dispose();await delay(220);assert.equal(qa[ID],undefined);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}});
test("200 cold renders are bounded and source is tracked, local-only, frame-free, and leak-free",()=>{const started=performance.now();for(let index=0;index<200;index++){const h=harness({reduced:index%2===0});game.render(taskFor(),h.context);assert.equal(h.qa[ID].inspect().options.length,3);h.dispose()}assert.ok(performance.now()-started<1000);assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|webkitAudioContext|new Audio)\b/);assert.doesNotMatch(source,/https?:\/\//);assert.deepEqual([...source.matchAll(/assets\/[a-z-]+\.webp/g)].map(match=>match[0]),["assets/partner-mood.webp"]);assert.doesNotMatch(source,/data-answer|sentiment|therapy|診断/)});
