import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";

const moduleUrl=new URL("../src/games/spatial-flow-link-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8"),ID="spatial-flow-link-v1";
const importGame=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n// ${suffix}`).toString("base64")}`)).default;
const game=await importGame("primary");
function helpers(seed=0xf109a11){const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32),randomInt=(a,b)=>a+Math.floor(random()*(b-a+1)),pick=v=>v[randomInt(0,v.length-1)];return{random,randomInt,pick,shuffle:v=>[...v]}}
const fixedTask=()=>{const route=[];for(let r=0;r<5;r++)for(let i=0;i<5;i++)route.push({r,c:r%2?4-i:i});const lengths=[6,6,6,7],solution=[];let cursor=0;lengths.forEach(length=>{solution.push(route.slice(cursor,cursor+length));cursor+=length});return{kind:"flowLink",prompt:"同じ色をつないで",help:"色の点から指をなぞって同じ色へ。すべての色をつなぎ、全部のマスを埋めれば成功です。",endpoints:solution.map((path,color)=>({color,a:{...path[0]},b:{...path.at(-1)}})),solution,size:5,duration:80000}};
const fallback=()=>({kind:"flowLink",prompt:"同じ色をつないで",help:"色の点から指をなぞって同じ色へ。",endpoints:[{color:0,a:{r:0,c:0},b:{r:0,c:4}},{color:1,a:{r:2,c:0},b:{r:2,c:4}},{color:2,a:{r:4,c:0},b:{r:4,c:4}},{color:3,a:{r:1,c:0},b:{r:3,c:4}}],solution:[],size:5,duration:80000});

class ClassList{constructor(owner){this.owner=owner;this.set=new Set()}sync(){this.owner._className=[...this.set].join(" ")}reset(value){this.set=new Set(String(value||"").split(/\s+/).filter(Boolean));this.sync()}add(...values){values.forEach(value=>this.set.add(value));this.sync()}remove(...values){values.forEach(value=>this.set.delete(value));this.sync()}contains(value){return this.set.has(value)}toggle(value,force){const add=force===undefined?!this.set.has(value):force;add?this.set.add(value):this.set.delete(value);this.sync();return add}}
class Style{constructor(){this.map=new Map()}setProperty(key,value){this.map.set(key,String(value))}}
const noop=()=>{};class Gradient{addColorStop(){}}
function canvasContext(){return new Proxy({globalAlpha:1,createLinearGradient:()=>new Gradient(),createRadialGradient:()=>new Gradient()},{get(target,key){return key in target?target[key]:noop},set(target,key,value){target[key]=value;return true}})}
class Element extends EventTarget{constructor(tag,doc){super();this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.children=[];this.attributes=new Map();this.dataset={};this.style=new Style();this._className="";this.classList=new ClassList(this);this.textContent="";this.tabIndex=-1;this.width=0;this.height=0;this.parentElement=null;this.ctx=this.tagName==="CANVAS"?canvasContext():null}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}append(...nodes){nodes.forEach(node=>{node.parentElement=this;this.children.push(node)})}replaceChildren(...nodes){this.children=[];this.append(...nodes)}setAttribute(key,value){this.attributes.set(key,String(value))}getAttribute(key){return this.attributes.get(key)??null}focus(){this.ownerDocument.activeElement=this}getContext(){return this.ctx}get offsetWidth(){return 393}getBoundingClientRect(){const width=Number.parseFloat(this.style.map.get("width"))||393,height=Number.parseFloat(this.style.map.get("height"))||401;return{left:0,top:0,width,height,right:width,bottom:height}}}
function documentFor(dpr=3){const view=new EventTarget();view.devicePixelRatio=dpr;const doc={activeElement:null,defaultView:view};doc.createElement=tag=>new Element(tag,doc);return doc}
function event(type,props={}){const value=new Event(type,{bubbles:true,cancelable:true});Object.entries(props).forEach(([key,item])=>Object.defineProperty(value,key,{value:item}));return value}
function harness({reduced=true,viewport={width:393,height:852,dpr:3},owner=documentFor(viewport.dpr)}={}){const controller=new AbortController(),host=owner.createElement("div"),qa={},jobs=[],listeners=new Set(),finishes=[];let frame=null,deadline=null,time=0,disposed=false;host.getBoundingClientRect=()=>({left:0,top:0,width:viewport.width,height:viewport.height});const dispose=()=>{if(disposed)return;controller.abort();disposed=true;jobs.forEach(job=>job.on=false);if(deadline)deadline.on=false;frame=null;listeners.forEach(item=>item.target.removeEventListener(item.type,item.fn,item.options));listeners.clear()};const context={host,signal:controller.signal,reducedMotion:reduced,viewport,qa,finish(correct,result){if(disposed||finishes.length)return false;finishes.push({correct,result});dispose();return true},later(fn,ms){const job={at:time+ms,fn,on:true};jobs.push(job);return job},setDeadline(ms,fn){deadline={at:time+ms,fn,on:true};return deadline},frame(fn){frame=fn;return()=>{frame=null}},listen(target,type,fn,options){target.addEventListener(type,fn,options);const item={target,type,fn,options};listeners.add(item);return()=>{target.removeEventListener(type,fn,options);listeners.delete(item)}}};const runAll=()=>{while(true){const job=jobs.filter(item=>item.on).sort((a,b)=>a.at-b.at)[0];if(!job)break;time=job.at;job.on=false;job.fn()}};const step=at=>{time=at;if(frame&&frame(at)===false)frame=null};const timeout=()=>{if(deadline?.on&&!disposed){deadline.on=false;deadline.fn()}};return{context,host,owner,qa,finishes,runAll,step,timeout,dispose,get listenerCount(){return listeners.size},get frameActive(){return Boolean(frame)},get pending(){return jobs.filter(job=>job.on).length}}}
const parts=h=>{const stage=h.host.children[1];return{stage,status:stage.children[0],canvas:stage.children[1],hint:stage.children[2]}};

test("metadata preserves the published stable identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.9",tier:3,flavor:"satisfying",step:1,family:"spatial-flow-link",category:"spatial"}));
test("5,000 generations terminate, clone, cover all cells, and validate a real solution",()=>{const random=helpers(),counts=new Set(),started=performance.now();for(let index=0;index<5000;index++){const task=game.generate(random);assert.deepEqual(game.validate(task),[],`task ${index}`);assert.doesNotThrow(()=>structuredClone(task));assert.equal(new Set(task.solution.flat().map(point=>`${point.r},${point.c}`)).size,25);counts.add(task.endpoints.length)}assert.deepEqual([...counts].sort(),[4,5]);assert.ok(performance.now()-started<5000)});
test("bounded generation returns and accepts the exact published emergency descriptor",()=>{const task=game.generate({random:()=>0,randomInt:(min,max)=>max+100,pick:values=>values[0]});assert.deepEqual(task,fallback());assert.deepEqual(game.validate(task),[])});
test("validator rejects changed rules, endpoint clashes, broken adjacency, overlap, and incomplete coverage",()=>{const task=fixedTask(),mutations=[];mutations.push({...task,prompt:"changed"},{...task,duration:1},{...task,size:4});const clash=structuredClone(task);clash.endpoints[1].a={...clash.endpoints[0].a};mutations.push(clash);const jump=structuredClone(task);jump.solution[0][1]={r:4,c:4};mutations.push(jump);const overlap=structuredClone(task);overlap.solution[1][1]={...overlap.solution[0][1]};mutations.push(overlap);const short=structuredClone(task);short.solution[3].pop();mutations.push(short);mutations.forEach((item,index)=>assert.ok(game.validate(item).length,`mutation ${index}`))});
test("published fallback plain data resumes through a playable recovery and finishes once",()=>{const h=harness();game.render(structuredClone(fallback()),h.context);const api=h.qa[ID];assert.equal(api.inspect().endpoints.length,4);assert.equal(api.solve(),true);h.runAll();assert.deepEqual(h.finishes.map(item=>item.correct),[true]);h.timeout();assert.equal(h.finishes.length,1)});
test("fresh plain-data task reload revalidates and completes without module memory",async()=>{const task=JSON.parse(JSON.stringify(game.generate(helpers(22)))),fresh=await importGame(`fresh-${Date.now()}`);assert.deepEqual(fresh.validate(task),[]);const h=harness();fresh.render(task,h.context);h.qa[ID].solve();h.runAll();assert.deepEqual(h.finishes.map(item=>item.correct),[true])});
test("touch drag has causal growth and keyboard can start, extend, and release with focus",()=>{const h=harness(),task=fixedTask();game.render(task,h.context);const {canvas}=parts(h),api=h.qa[ID];assert.equal(h.owner.activeElement,canvas);canvas.dispatchEvent(event("pointerdown",{pointerId:4,pointerType:"touch",clientX:66,clientY:84}));canvas.dispatchEvent(event("pointermove",{pointerId:4,pointerType:"touch",clientX:132,clientY:84}));assert.equal(api.inspect().drag,0);assert.ok(api.inspect().paths[0].length>=2);canvas.dispatchEvent(event("pointerup",{pointerId:4}));assert.equal(api.inspect().drag,-1);canvas.dispatchEvent(event("keydown",{key:"Enter"}));canvas.dispatchEvent(event("keydown",{key:"ArrowRight"}));assert.equal(api.inspect().drag,0);assert.ok(api.inspect().paths[0].length>=2);canvas.dispatchEvent(event("keydown",{key:"Enter"}));assert.equal(api.inspect().drag,-1);h.dispose()});
test("another color endpoint is illegal, visible, non-terminal, and does not finish",()=>{const h=harness(),apiTask=fixedTask();game.render(apiTask,h.context);const api=h.qa[ID];assert.equal(api.start({r:1,c:4}),true);const before=api.inspect().paths[0].length;assert.equal(api.extend({r:1,c:3}),false);assert.equal(api.inspect().invalid,true);assert.equal(api.inspect().paths[0].length,before);assert.equal(api.inspect().done,false);assert.equal(h.finishes.length,0);h.runAll();assert.equal(api.inspect().invalid,false);h.dispose()});
test("success, timeout, and double-finish paths commit exactly once",()=>{const success=harness();game.render(fixedTask(),success.context);success.qa[ID].solve();success.runAll();success.timeout();assert.deepEqual(success.finishes.map(item=>item.correct),[true]);const timeout=harness();game.render(fixedTask(),timeout.context);timeout.timeout();timeout.timeout();assert.deepEqual(timeout.finishes.map(item=>item.correct),[false]);assert.match(timeout.finishes[0].result.detail,/時間切れ/)});
test("normal motion uses one tracked frame while reduced motion is static",()=>{const normal=harness({reduced:false});game.render(fixedTask(),normal.context);assert.equal(normal.frameActive,true);normal.step(16.7);normal.step(33.4);assert.ok(normal.qa[ID].inspect().frames>=2);normal.dispose();const reduced=harness();game.render(fixedTask(),reduced.context);assert.equal(reduced.frameActive,false);assert.equal(parts(reduced).stage.dataset.reduced,"true");reduced.dispose()});
test("DPR is capped, all six visual states are inspectable, and canvas fits",()=>{const h=harness({viewport:{width:402,height:874,dpr:4}});game.render(fixedTask(),h.context);const api=h.qa[ID],canvas=api.inspect().canvas;assert.equal(canvas.dpr,3);assert.equal(canvas.pixelWidth,canvas.cssWidth*3);assert.equal(canvas.pixelHeight,canvas.cssHeight*3);assert.ok(canvas.cssWidth<=402);for(const scene of ["initial","drag","progress","illegal","success","timeout"])assert.equal(api.showScene(scene),true);h.dispose()});
test("dispose aborts pending success, deadline, listener, frame, and QA work",async()=>{const previousRaf=globalThis.requestAnimationFrame,previousCancel=globalThis.cancelAnimationFrame;let id=0;const frames=new Map();globalThis.requestAnimationFrame=fn=>{frames.set(++id,fn);return id};globalThis.cancelAnimationFrame=key=>frames.delete(key);try{const owner=documentFor(),host=owner.createElement("div"),qa={},finishes=[],runtime=createGameRuntime({host,qa,reducedMotion:false,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(fixedTask(),runtime.context);qa[ID].solve();assert.ok(runtime.inspect().timeouts>=2);runtime.dispose();await delay(920);assert.deepEqual(finishes,[]);assert.equal(qa[ID],undefined);assert.equal(frames.size,0);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(previousRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=previousRaf;if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}});
test("render uses ownerDocument and source has no raw lifetime or network primitive",()=>{const owner=documentFor(),old=globalThis.document;globalThis.document={createElement(){throw Error("global document used")}};try{const h=harness({owner});game.render(fixedTask(),h.context);const visit=node=>{assert.equal(node.ownerDocument,owner);node.children.forEach(visit)};visit(h.host);h.dispose()}finally{if(old===undefined)delete globalThis.document;else globalThis.document=old}assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon)\b/)});
