import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import game from "../src/games/spatial-lane-run-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";

const ID="spatial-lane-run-v1",moduleUrl=new URL("../src/games/spatial-lane-run-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8"),legacyFixtureSource=await readFile(new URL("./spatial-lane-run-v1.legacy-fixture.mjs",import.meta.url),"utf8");
const importFresh=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n// ${suffix}`).toString("base64")}`)).default;
function helpers(initial=0x51a9e){let seed=initial>>>0;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32),randomInt=(min,max)=>min+Math.floor(random()*(max-min+1)),pick=values=>values[randomInt(0,values.length-1)],shuffle=values=>{const copy=[...values];for(let i=copy.length-1;i>0;i--){const j=randomInt(0,i);[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};return{random,randomInt,pick,shuffle}}
function legacyGenerate(h){const themes=["dawn","noon","dusk"],theme=h.pick(themes),obstacles=[],groups=h.shuffle(["wall","trench","crates","gauntlet","trench","wall","crates","gauntlet"]).slice(0,h.randomInt(6,8));if(!groups.includes("trench"))groups[h.randomInt(0,groups.length-1)]="trench";if(!groups.includes("wall"))groups[0]="wall";const authorAt=new Set(h.shuffle(groups.map((group,index)=>index)).slice(0,h.randomInt(1,2)));let z=150;groups.forEach((group,index)=>{if(group==="wall")h.shuffle([0,1,2]).slice(0,2).forEach(lane=>obstacles.push({type:"rock",lane,z,seed:h.random()}));else if(group==="trench")[0,1,2].forEach(lane=>obstacles.push({type:"pit",lane,z}));else if(group==="crates"){const lanes=h.shuffle([0,1,2]),free=lanes[0],tnt=h.random()<.62?lanes[1]:-1;[0,1,2].forEach(lane=>{if(lane!==free)obstacles.push({type:lane===tnt?"tnt":"crate",lane,z})})}else{const lanes=h.shuffle([0,1,2]),rock=lanes[0],second=lanes[1],free=lanes[2];obstacles.push({type:"rock",lane:rock,z,seed:h.random()});obstacles.push({type:h.random()<.4?"tnt":"pit",lane:second,z});if(h.random()<.4)obstacles.push({type:"crate",lane:free,z})}z+=h.randomInt(58,78);if(authorAt.has(index)){obstacles.push({type:"author",lane:1,z:z-h.randomInt(26,34),phase:h.random()*6.28,sweep:h.random()<.5?1:-1});z+=h.randomInt(14,24)}});const scenery=[];for(let sz=40;sz<z+80;sz+=h.randomInt(14,30))scenery.push({z:sz,side:h.random()<.5?-1:1,offset:h.randomInt(13,26),kind:h.pick(["tree","tree","bush","stone"]),seed:h.random()});return{kind:"laneRun",prompt:"走るコースをタップで切り抜けて",help:"左右ボタンで位置、画面タップでジャンプ。穴と木箱は跳ぶ。岩と赤いTNTは跳ばずによける。",theme,obstacles,scenery,stageLength:z+70,speed:36,duration:45000}}

class ClassList{constructor(owner){this.owner=owner;this.set=new Set()}reset(value){this.set=new Set(String(value||"").split(/\s+/).filter(Boolean));this.sync()}sync(){this.owner._className=[...this.set].join(" ")}add(...v){v.forEach(x=>this.set.add(x));this.sync()}remove(...v){v.forEach(x=>this.set.delete(x));this.sync()}contains(v){return this.set.has(v)}}
const noop=()=>{};class Gradient{addColorStop(){}}
function context2d(){return new Proxy({globalAlpha:1,createLinearGradient:()=>new Gradient(),createRadialGradient:()=>new Gradient()},{get:(target,key)=>key in target?target[key]:noop,set:(target,key,value)=>(target[key]=value,true)})}
class Element extends EventTarget{constructor(tag,doc){super();this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.children=[];this.attributes=new Map();this.dataset={};this.style={};this._className="";this.classList=new ClassList(this);this.textContent="";this.tabIndex=-1;this.width=0;this.height=0;this.clientWidth=393;this.parentElement=null;this.ctx=this.tagName==="CANVAS"?context2d():null}set className(v){this._className=String(v);this.classList.reset(v)}get className(){return this._className}append(...nodes){nodes.forEach(node=>{node.parentElement=this;this.children.push(node)})}replaceChildren(...nodes){this.children=[];this.append(...nodes)}setAttribute(k,v){this.attributes.set(k,String(v))}getAttribute(k){return this.attributes.get(k)??null}focus(){this.ownerDocument.activeElement=this}getContext(){return this.ctx}getBoundingClientRect(){const width=Number.parseFloat(this.style.width)||this.clientWidth||393,height=Number.parseFloat(this.style.height)||252;return{left:0,top:0,width,height,right:width,bottom:height}}}
function documentFor(dpr=3){const view=new EventTarget();view.devicePixelRatio=dpr;const doc={activeElement:null,defaultView:view};doc.createElement=tag=>new Element(tag,doc);return doc}
function event(type,props={}){const result=new Event(type,{bubbles:true,cancelable:true});Object.entries(props).forEach(([key,value])=>Object.defineProperty(result,key,{value}));return result}
function harness({reduced=false,viewport={width:393,height:852,dpr:3},owner=documentFor(viewport.dpr)}={}){const controller=new AbortController(),host=owner.createElement("div"),qa={},jobs=[],listeners=new Set(),finishes=[];let frame=null,deadline=null,now=0,disposed=false;host.clientWidth=viewport.width;const dispose=()=>{if(disposed)return;disposed=true;controller.abort();jobs.forEach(job=>job.on=false);if(deadline)deadline.on=false;frame=null;listeners.forEach(item=>item.target.removeEventListener(item.type,item.fn,item.options));listeners.clear()};const context={host,signal:controller.signal,reducedMotion:reduced,viewport,qa,finish(correct,result){if(disposed||finishes.length)return false;finishes.push({correct:Boolean(correct),result});dispose();return true},later(fn,ms){const job={at:now+Math.max(0,ms),fn,on:true};jobs.push(job);return job},setDeadline(ms,fn){deadline={at:now+ms,fn,on:true};return deadline},frame(fn){frame=fn;return()=>{frame=null}},listen(target,type,fn,options){target.addEventListener(type,fn,options);const item={target,type,fn,options};listeners.add(item);return()=>{target.removeEventListener(type,fn,options);listeners.delete(item)}}};const runAll=()=>{while(!disposed){const job=jobs.filter(x=>x.on).sort((a,b)=>a.at-b.at)[0];if(!job)break;now=job.at;job.on=false;job.fn()}};const step=at=>{now=at;if(frame&&frame(at)===false)frame=null};const timeout=()=>{if(deadline?.on&&!disposed){deadline.on=false;deadline.fn()}};return{context,host,owner,qa,finishes,dispose,runAll,step,timeout,get frameActive(){return Boolean(frame)},get listeners(){return listeners.size}}}
const parts=h=>{const stage=h.host.children[1];return{stage,canvas:stage.children[0],pad:stage.children[1],buttons:stage.children[1].children,status:stage.children[2]}};
function taskWith(first="rock"){const kinds=[first,"pit","crate","tnt","rock","pit","crate","rock","pit","crate","rock","pit","author"],obstacles=kinds.map((type,index)=>({type,lane:type==="author"?1:0,z:150+index*58,...(type==="rock"?{seed:.37}:{}),...(type==="author"?{phase:1.2,sweep:1}:{})})),scenery=Array.from({length:38},(_,index)=>({z:40+index*24,side:index%2?-1:1,offset:16+index%9,kind:["tree","bush","stone"][index%3],seed:(index%10)/10}));return{kind:"laneRun",prompt:"走るコースをタップで切り抜けて",help:"左右ボタンで位置、画面タップでジャンプ。穴と木箱は跳ぶ。岩と赤いTNTは跳ばずによける。",theme:"dawn",obstacles,scenery,stageLength:980,speed:36,duration:45000}}


test("metadata keeps the published stable identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.2",tier:2,flavor:"wild",step:1,family:"spatial-lane-run",category:"spatial"}));
test("5,000 generated descriptors exactly preserve the published generator and validate",()=>{const actual=helpers(0xa8761a1),legacy=helpers(0xa8761a1),themes=new Set(),counts=new Set(),started=performance.now();for(let i=0;i<5000;i++){const task=game.generate(actual),reference=legacyGenerate(legacy);assert.deepEqual(task,reference,`generation ${i}`);assert.deepEqual(game.validate(task),[]);assert.doesNotThrow(()=>structuredClone(task));themes.add(task.theme);counts.add(task.obstacles.filter(item=>item.type==="author").length)}assert.deepEqual([...themes].sort(),["dawn","dusk","noon"]);assert.deepEqual([...counts].sort(),[1,2]);assert.ok(performance.now()-started<5000)});
test("generation requires injected randomness and validator rejects rule, route, goal, and save corruption",()=>{assert.throws(()=>game.generate(),/random/);const task=game.generate(helpers(8)),mutations=[{...task,kind:"runner"},{...task,prompt:"changed"},{...task,speed:35},{...task,duration:1},{...task,theme:"night"},{...task,stageLength:Math.max(...task.obstacles.map(x=>x.z))+10},{...task,obstacles:task.obstacles.filter(x=>x.type!=="author")},structuredClone(task)];mutations.at(-1).obstacles[0].lane=9;mutations.forEach((item,index)=>assert.ok(game.validate(item).length,`mutation ${index}`))});
test("JSON-saved plain task resumes in a fresh module and reaches a correct goal once",async()=>{const fresh=await importFresh(Date.now()),task=JSON.parse(JSON.stringify(taskWith())),h=harness();assert.deepEqual(fresh.validate(task),[]);fresh.render(task,h.context);const api=h.qa[ID];api.move(1);api.advance(22600);api.jump();api.advance(1100);api.advance(5000);assert.equal(api.inspect().result,"success");h.runAll();h.timeout();assert.deepEqual(h.finishes.map(x=>x.correct),[true]);assert.match(h.finishes[0].result.detail,/ゴール/)});
test("lane movement is causal and a rock fails even when jumped",()=>{const h=harness(),task=taskWith("rock");game.render(task,h.context);const api=h.qa[ID];assert.equal(api.inspect().lane,1);api.move(-1);assert.equal(api.inspect().lane,0);api.advance(3400);api.jump();api.advance(700);assert.equal(api.inspect().result,"failure");assert.match(api.inspect().detail,/岩/);h.runAll();assert.deepEqual(h.finishes.map(x=>x.correct),[false])});
test("pit and grounded crate reach failure terminals, airborne crate breaks with particles, and jumping TNT fails",()=>{const pit=harness();game.render(taskWith("pit"),pit.context);pit.qa[ID].move(-1);pit.qa[ID].advance(4000);assert.equal(pit.qa[ID].inspect().result,"failure");assert.equal(pit.qa[ID].inspect().done,true);assert.match(pit.qa[ID].inspect().detail,/穴/);const grounded=harness();game.render(taskWith("crate"),grounded.context);grounded.qa[ID].move(-1);grounded.qa[ID].advance(4000);assert.equal(grounded.qa[ID].inspect().result,"failure");assert.equal(grounded.qa[ID].inspect().items[0].hit,true);assert.match(grounded.qa[ID].inspect().detail,/木箱/);const crate=harness();game.render(taskWith("crate"),crate.context);crate.qa[ID].move(-1);crate.qa[ID].advance(3400);crate.qa[ID].jump();crate.qa[ID].advance(700);const broken=crate.qa[ID].inspect();assert.equal(broken.done,false);assert.equal(broken.result,null);assert.equal(broken.crates,1);assert.equal(broken.items[0].hit,true);assert.ok(broken.particles>0);crate.dispose();const tnt=harness();game.render(taskWith("tnt"),tnt.context);tnt.qa[ID].move(-1);tnt.qa[ID].advance(3400);tnt.qa[ID].jump();tnt.qa[ID].advance(700);assert.equal(tnt.qa[ID].inspect().result,"failure");assert.match(tnt.qa[ID].inspect().detail,/TNT/)});
test("touch buttons, canvas jump, keyboard, focus, and directional clamping work",()=>{const h=harness();game.render(taskWith(),h.context);const {stage,canvas,buttons}=parts(h),api=h.qa[ID];buttons[0].dispatchEvent(event("pointerdown",{pointerType:"touch"}));assert.equal(api.inspect().lane,0);buttons[0].dispatchEvent(event("pointerdown",{pointerType:"touch"}));assert.equal(api.inspect().lane,0);stage.dispatchEvent(event("keydown",{key:"ArrowRight"}));assert.equal(api.inspect().lane,1);assert.equal(h.owner.activeElement,buttons[2]);canvas.dispatchEvent(event("pointerdown",{pointerType:"touch"}));assert.ok(api.inspect().vy>0);h.dispose()});
test("direction and jump aria-pressed states remain semantically independent through landing",()=>{const h=harness(),task=taskWith();game.render(task,h.context);const {buttons}=parts(h),api=h.qa[ID],pressed=()=>buttons.map(button=>button.getAttribute("aria-pressed"));assert.deepEqual(pressed(),["false","false","false"]);api.move(-1);assert.deepEqual(pressed(),["true","false","false"]);api.move(1);api.move(1);assert.deepEqual(pressed(),["false","false","true"]);api.jump();assert.deepEqual(pressed(),["false","false","true"]);api.advance(16);assert.deepEqual(pressed(),["false","true","true"]);api.advance(900);assert.equal(api.inspect().y,0);assert.deepEqual(pressed(),["false","false","true"]);h.dispose()});
test("the moving author collision is causal and reaches the failure terminal",()=>{const task=taskWith("author"),author=task.obstacles[0];author.phase=4.915;const h=harness();game.render(task,h.context);const api=h.qa[ID];api.advance(4100);assert.equal(api.inspect().result,"failure");assert.equal(api.inspect().done,true);assert.equal(api.inspect().items[0].hit,true);assert.match(api.inspect().detail,/作者/);h.runAll();assert.deepEqual(h.finishes.map(item=>item.correct),[false])});
test("normal animation remains one tracked roughly-60fps loop",()=>{const h=harness();game.render(taskWith(),h.context);for(let i=0;i<121;i++)h.step(i*1000/60);const state=h.qa[ID].inspect();assert.equal(h.frameActive,true);assert.equal(state.frames,121);assert.ok(state.z>60&&state.z<75);h.dispose()});
test("reduced motion preserves play at slower speed without crash animation",()=>{const h=harness({reduced:true});game.render(taskWith(),h.context);const {stage}=parts(h);assert.equal(stage.dataset.reduced,"true");assert.equal(h.qa[ID].inspect().speed,28);h.qa[ID].advance(1000);assert.equal(Math.round(h.qa[ID].inspect().z),28);h.dispose()});
test("393/402 layouts cap DPR at 3 and expose twelve full visual states",()=>{for(const viewport of[{width:393,height:852,dpr:3},{width:402,height:874,dpr:4}]){const h=harness({viewport});game.render(taskWith(),h.context);const api=h.qa[ID],canvas=api.inspect().canvas;assert.equal(canvas.dpr,3);assert.equal(canvas.pixelWidth,canvas.cssWidth*3);assert.equal(canvas.pixelHeight,canvas.cssHeight*3);assert.ok(canvas.cssWidth<=viewport.width);for(const scene of["initial","input","jump","motion","progress","goal","rock","pit","crate","tnt","author","success","failure","invalid","timeout"])assert.equal(api.showScene(scene),true,scene);h.dispose()}});
test("deadline, pending outcome, and repeated timeout cannot double finish",()=>{const h=harness();game.render(taskWith(),h.context);h.timeout();h.timeout();assert.equal(h.qa[ID].inspect().result,"timeout");h.runAll();h.timeout();assert.equal(h.finishes.length,1);assert.equal(h.finishes[0].correct,false);assert.match(h.finishes[0].result.detail,/時間内/)});
test("dispose aborts frame, deadline, listeners, QA, and pending finish",async()=>{const oldRaf=globalThis.requestAnimationFrame,oldCancel=globalThis.cancelAnimationFrame;let id=0;const frames=new Map();globalThis.requestAnimationFrame=fn=>(frames.set(++id,fn),id);globalThis.cancelAnimationFrame=key=>frames.delete(key);try{const owner=documentFor(),host=owner.createElement("div"),qa={},finishes=[],runtime=createGameRuntime({host,qa,reducedMotion:false,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(taskWith("rock"),runtime.context);qa[ID].move(-1);qa[ID].advance(4000);assert.ok(runtime.inspect().timeouts>=2);runtime.dispose();await delay(650);assert.deepEqual(finishes,[]);assert.equal(qa[ID],undefined);assert.equal(frames.size,0);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(oldRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=oldRaf;if(oldCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=oldCancel}});
test("legacy causal evidence maps the motion query to matchMedia and times jumps from real reduced speed",()=>{assert.match(legacyFixtureSource,/reducedQuery=params\.get\("motion"\)==="reduced"/);assert.match(legacyFixtureSource,/key==="matches"\)return reducedQuery/);assert.match(legacyFixtureSource,/toHit=89\/state\.speed\*1000/);assert.doesNotMatch(legacyFixtureSource,/setTimeout\(\(\)=>api\.jump\(\),2020\)/)});
test("render owns its document and source has no raw lifetime, network, audio, or global DOM primitive",()=>{const owner=documentFor(),old=globalThis.document;globalThis.document={createElement(){throw Error("global document used")}};try{const h=harness({owner});game.render(taskWith(),h.context);const visit=node=>{assert.equal(node.ownerDocument,owner);node.children.forEach(visit)};visit(h.host);h.dispose()}finally{if(old===undefined)delete globalThis.document;else globalThis.document=old}assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement)\b/)});
