#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd); OUT=${1:-/tmp/agetest-spatial-rotation-v1-visual}; cd "$ROOT"
node tools/qa-browser-lanes.mjs start audit >/dev/null
rm -rf "$OUT";mkdir -p "$OUT"
variants=(legacy module);degrees=(90 180 270);metrics=(393x852 402x874);motions=(normal reduced);scenes=(initial focus wrong success timeout)
ready='(async()=>{for(let i=0;i<300;i++){if(window.__ROTATION_FIXTURE__&&document.documentElement.dataset.ready==="true")return true;await new Promise(r=>setTimeout(r,25))}throw Error("ready timeout")})()'
for variant in "${variants[@]}";do for degree in "${degrees[@]}";do for metric in "${metrics[@]}";do width=${metric%x*};height=${metric#*x};for motion in "${motions[@]}";do for scene in "${scenes[@]}";do
 node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/spatial-rotation-v1.fixture.html?variant=$variant&degree=$degree&scene=$scene&motion=$motion&width=$width" "$width" "$height" 3 >/dev/null
 node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null
 node tools/qa-browser-lanes.mjs eval audit 'window.__ROTATION_FIXTURE__.report()' >"$OUT/evidence-$variant-$degree-$metric-$scene-$motion.json"
 node tools/qa-browser-lanes.mjs screenshot audit "$OUT/$variant-$degree-$metric-$scene-$motion.png" >/dev/null
done;done;done;done;done
for variant in "${variants[@]}";do for metric in "${metrics[@]}";do width=${metric%x*};height=${metric#*x};node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/spatial-rotation-v1.fixture.html?variant=$variant&degree=90&scene=initial&width=$width" "$width" "$height" 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null;node tools/qa-browser-lanes.mjs eval audit '(async()=>{const f=window.__ROTATION_FIXTURE__,d=[];let p=performance.now();await new Promise(resolve=>{const tick=n=>{d.push(n-p);p=n;if(d.length===90)resolve();else requestAnimationFrame(tick)};requestAnimationFrame(tick)});const r=f.report();return{status:d.length===90&&r.runtime.frames===0&&!r.external.length&&!r.errors.length&&r.viewport.bodyScrollWidth<=r.width?"pass":"fail",variant:f.variant,frames:d.length,averageFrameMs:d.reduce((a,b)=>a+b,0)/d.length,maxFrameMs:Math.max(...d),gameOwnedFrames:r.runtime.frames,overflow:r.viewport.bodyScrollWidth>r.width,external:r.external,errors:r.errors,viewport:r.viewport}})()' >"$OUT/performance-$variant-$metric.json";done;done
for metric in 390x844 430x932;do width=${metric%x*};height=${metric#*x};for variant in "${variants[@]}";do for motion in "${motions[@]}";do for scene in initial success;do node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/spatial-rotation-v1.fixture.html?variant=$variant&degree=270&scene=$scene&motion=$motion&width=$width" "$width" "$height" 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null;node tools/qa-browser-lanes.mjs eval audit 'window.__ROTATION_FIXTURE__.report()' >"$OUT/supplemental-$variant-$metric-$scene-$motion.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/supplemental-$variant-$metric-$scene-$motion.png" >/dev/null;done;done;done;done
for variant in "${variants[@]}";do for degree in "${degrees[@]}";do for motion in "${motions[@]}";do
 node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/spatial-rotation-v1.fixture.html?variant=$variant&degree=$degree&scene=initial&motion=$motion&width=402&live=1" 402 874 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null
 node tools/qa-browser-lanes.mjs eval audit '(async()=>{const f=window.__ROTATION_FIXTURE__,answer=f.task.answer,button=[...document.querySelectorAll("button")].find(b=>b.textContent===answer),events=[];for(const type of["pointerdown","pointerup"]){button.dispatchEvent(new PointerEvent(type,{bubbles:true,cancelable:true,pointerId:71,pointerType:"touch",isPrimary:true}));events.push(type)}button.click();events.push("click");const locked=f.api.inspect();for(let i=0;i<30;i++){if(f.runtime.inspect().finished)break;await new Promise(r=>setTimeout(r,20))}const report=f.report();return{variant:f.variant,degrees:f.degrees,motion:f.motion,answer,events,locked,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()' >"$OUT/touch-$variant-$degree-$motion.json"
 node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/spatial-rotation-v1.fixture.html?variant=$variant&degree=$degree&scene=initial&motion=$motion&width=402&live=1" 402 874 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null
 node tools/qa-browser-lanes.mjs eval audit '(async()=>{const f=window.__ROTATION_FIXTURE__,buttons=[...document.querySelectorAll("button")],target=buttons.find(b=>b.textContent===f.task.answer),start=buttons[0];start.focus();const keys=[],press=k=>{document.activeElement.dispatchEvent(new KeyboardEvent("keydown",{key:k,bubbles:true,cancelable:true}));keys.push(k)},index=buttons.indexOf(target);if(index===1)press("ArrowRight");else if(index===2)press("ArrowDown");else if(index===3){press("ArrowRight");press("ArrowDown")}press("Enter");document.activeElement.click();const locked=f.api.inspect();for(let i=0;i<30;i++){if(f.runtime.inspect().finished)break;await new Promise(r=>setTimeout(r,20))}const report=f.report();return{variant:f.variant,degrees:f.degrees,motion:f.motion,answer:f.task.answer,keys,focusedText:target.textContent,locked,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()' >"$OUT/keyboard-$variant-$degree-$motion.json"
 node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/spatial-rotation-v1.fixture.html?variant=$variant&degree=$degree&scene=initial&motion=$motion&width=402&live=1&deadline=180" 402 874 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null
 node tools/qa-browser-lanes.mjs eval audit '(async()=>{const f=window.__ROTATION_FIXTURE__;for(let i=0;i<40;i++){if(f.runtime.inspect().finished)break;await new Promise(r=>setTimeout(r,20))}const report=f.report();return{variant:f.variant,degrees:f.degrees,motion:f.motion,state:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()' >"$OUT/deadline-$variant-$degree-$motion.json"
done;done;done
for motion in "${motions[@]}";do node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/spatial-rotation-v1.fixture.html?variant=module&degree=180&scene=initial&motion=$motion&width=402&live=1" 402 874 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null;node tools/qa-browser-lanes.mjs eval audit '(()=>{const f=window.__ROTATION_FIXTURE__;f.api.choose(f.task.answer);const before=f.runtime.inspect(),state=f.api.inspect();f.runtime.dispose();const report=f.report();return{motion:f.motion,state,before,after:f.runtime.inspect(),qaPresent:Boolean(f.qa[f.game.metadata.id]),finishes:report.finishes,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()' >"$OUT/dispose-module-$motion.json";done
OUT="$OUT" python - <<'PY'
from PIL import Image,ImageChops,ImageStat
from pathlib import Path
import json,math,os
root=Path(os.environ['OUT']);variants=['legacy','module'];degrees=[90,180,270];metrics=['393x852','402x874'];motions=['normal','reduced'];scenes=['initial','focus','wrong','success','timeout'];rows=[]
for v in variants:
 for d in degrees:
  for m in metrics:
   for s in scenes:
    a=Image.open(root/f'{v}-{d}-{m}-{s}-normal.png').convert('RGB');b=Image.open(root/f'{v}-{d}-{m}-{s}-reduced.png').convert('RGB');diff=ImageChops.difference(a,b);stat=ImageStat.Stat(diff);rows.append({'key':f'{v}-{d}-{m}-{s}','size':[a.width,a.height],'mae':round(sum(stat.mean)/3,3),'rmse':round(math.sqrt(sum(x*x for x in stat.rms)/3),3),'normalizedRMSE':round(math.sqrt(sum(x*x for x in stat.rms)/3)/255,6),'changed':round(sum(px!=(0,0,0) for px in diff.getdata())/(a.width*a.height),4)})
report={'canonicalViewports':[{'width':393,'height':852,'dpr':3},{'width':402,'height':874,'dpr':3}],'variants':variants,'degrees':degrees,'states':scenes,'comparisons':len(rows),'screenshots':len(rows)*2,'allDpr3':True,'allFullResolution':all(r['size'] in ([1179,2556],[1206,2622]) for r in rows),'meanMAE':round(sum(r['mae'] for r in rows)/len(rows),3),'maxMAE':max(r['mae'] for r in rows),'maxNormalizedRMSE':max(r['normalizedRMSE'] for r in rows),'meanChanged':round(sum(r['changed'] for r in rows)/len(rows),4),'rows':rows};(root/'comparison-report.json').write_text(json.dumps(report,indent=2))
def load(n):return json.loads((root/n).read_text())
e={'lane':{'name':'audit','cdp':9332,'http':8862},'canonical':{'viewports':report['canonicalViewports'],'variants':variants,'degrees':degrees,'states':scenes,'screenshots':report['screenshots']},'matrix':{v:{str(d):{m:{o:{s:load(f'evidence-{v}-{d}-{m}-{s}-{o}.json') for s in scenes} for o in motions} for m in metrics} for d in degrees} for v in variants},'touch':{v:{str(d):{o:load(f'touch-{v}-{d}-{o}.json') for o in motions} for d in degrees} for v in variants},'keyboard':{v:{str(d):{o:load(f'keyboard-{v}-{d}-{o}.json') for o in motions} for d in degrees} for v in variants},'deadline':{v:{str(d):{o:load(f'deadline-{v}-{d}-{o}.json') for o in motions} for d in degrees} for v in variants},'disposeModule':{o:load(f'dispose-module-{o}.json') for o in motions},'performance':{v:{m:load(f'performance-{v}-{m}.json') for m in metrics} for v in variants},'supplemental':{v:{m:{o:{s:load(f'supplemental-{v}-{m}-{s}-{o}.json') for s in ['initial','success']} for o in motions} for m in ['390x844','430x932']} for v in variants}};(root/'browser-evidence.json').write_text(json.dumps(e,ensure_ascii=False,indent=2));print(json.dumps({k:v for k,v in report.items() if k!='rows'},indent=2))
PY
