import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";

const moduleUrl=new URL("../src/games/spatial-commuter-seat-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8"),importGame=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n//${suffix}`).toString("base64")}`)).default,game=await importGame("primary"),ID="spatial-commuter-seat-v1";
function helpers(initial=0x5ea7){let seed=initial>>>0;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32),randomInt=(a,b)=>a+Math.floor(random()*(b-a+1)),shuffle=v=>{const a=[...v];for(let i=a.length-1;i;i--){const j=randomInt(0,i);[a[i],a[j]]=[a[j],a[i]]}return a};return{random,randomInt,shuffle,pick:v=>v[randomInt(0,v.length-1)]}}
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(v){this.values=new Set(String(v||"").split(/\s+/).filter(Boolean))}add(...v){v.forEach(x=>this.values.add(x));this.sync()}remove(...v){v.forEach(x=>this.values.delete(x));this.sync()}contains(v){return this.values.has(v)}toggle(v,force){const add=force===undefined?!this.values.has(v):force;add?this.values.add(v):this.values.delete(v);this.sync();return add}sync(){this.owner._className=[...this.values].join(" ")}}
class FakeStyle{constructor(){this.values=new Map()}setProperty(k,v){this.values.set(k,String(v))}}
const noop=()=>{};function canvasContext(){const gradient={addColorStop:noop};return new Proxy({createLinearGradient:()=>gradient,createRadialGradient:()=>gradient},{get:(target,key)=>key in target?target[key]:noop,set:(target,key,value)=>(target[key]=value,true)})}
class FakeElement extends EventTarget{constructor(tag,ownerDocument){super();this.tagName=tag.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.attributes=new Map();this.dataset={};this.style=new FakeStyle();this.classList=new FakeClassList(this);this._className="";this.textContent="";this.disabled=false;this.type="";this.tabIndex=-1;this.width=0;this.height=0}set className(v){this._className=String(v);this.classList.reset(v)}get className(){return this._className}append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this.children=[...nodes]}setAttribute(k,v){this.attributes.set(k,String(v))}getAttribute(k){return this.attributes.get(k)??null}focus(){this.ownerDocument.activeElement=this}get offsetWidth(){return 390}getContext(kind){return this.tagName==="CANVAS"&&kind==="2d"?canvasContext():null}getBoundingClientRect(){const width=Number.parseFloat(this.style.values.get("width"))||390,height=Number.parseFloat(this.style.values.get("height"))||464;return{left:0,top:0,width,height,right:width,bottom:height}}}
function fakeDocument(){const view=new EventTarget();view.devicePixelRatio=3;const doc={defaultView:view,activeElement:null};doc.createElement=tag=>new FakeElement(tag,doc);return doc}
function install(){const old=globalThis.document;globalThis.document=fakeDocument();return()=>{if(old===undefined)delete globalThis.document;else globalThis.document=old}}
function harness({reducedMotion=false,viewport={width:393,height:852,dpr:3},ownerDocument=globalThis.document}={}){const controller=new AbortController(),host=ownerDocument.createElement("div"),qa={},jobs=[],listeners=new Set(),finishes=[];let deadline=null,disposed=false,frames=0;host.getBoundingClientRect=()=>({left:0,top:0,width:viewport.width-16,height:viewport.height,right:viewport.width-16,bottom:viewport.height});const context={host,signal:controller.signal,qa,reducedMotion,viewport,finish(correct,result){if(disposed||finishes.length)return false;finishes.push({correct,result});return true},later(fn,ms){const job={fn,ms,active:true};jobs.push(job);return job},setDeadline(ms,fn){deadline={ms,fn,active:true};return deadline},frame(){frames++;throw Error("commuter game must not use a frame loop")},listen(target,type,fn,options){target.addEventListener(type,fn,options);const row={target,type,fn,options};listeners.add(row);return()=>{target.removeEventListener(type,fn,options);listeners.delete(row)}}};const runNext=()=>{const now=jobs.splice(0);now.forEach(job=>{if(job.active&&!disposed){job.active=false;job.fn()}})};const runAll=()=>{let guard=0;while(jobs.some(job=>job.active)){if(++guard>80)throw Error("job loop");runNext()}};const triggerDeadline=()=>{if(deadline?.active&&!disposed){deadline.active=false;deadline.fn()}};const dispose=()=>{if(disposed)return;controller.abort();disposed=true;jobs.forEach(job=>job.active=false);if(deadline)deadline.active=false;listeners.forEach(({target,type,fn,options})=>target.removeEventListener(type,fn,options));listeners.clear()};return{context,host,qa,finishes,runNext,runAll,triggerDeadline,dispose,get jobs(){return jobs.filter(job=>job.active).length},get delays(){return jobs.filter(job=>job.active).map(job=>job.ms)},get listeners(){return listeners.size},get frames(){return frames}}}
const stage=host=>host.children[1],scene=host=>stage(host).children[3],routeButtons=host=>scene(host).children[2].children,controls=host=>stage(host).children[4].children,ev=(type,props={})=>{const event=new Event(type,{bubbles:true,cancelable:true});Object.entries(props).forEach(([k,v])=>Object.defineProperty(event,k,{value:v}));return event};
const paths=task=>{const out=[];for(const a of task.layers[0])for(const b of task.layers[1])for(const c of task.layers[2])for(const d of task.layers[3])out.push([a.id,b.id,c.id,d.id]);return out};
const routeFor=(task,api,reason)=>paths(task).find(path=>api.simulate(path).reason===reason);
const play=(h,path)=>{for(const id of path){if(h.qa[ID].inspect().done)break;assert.equal(h.qa[ID].choose(id),true);assert.equal(h.qa[ID].commit(),true);h.runAll()}};

test("metadata is the reserved original-game identity",()=>{assert.deepEqual(game.metadata,{id:ID,introducedIn:"2.0",tier:2,flavor:"satisfying",step:1,family:"spatial-commuter-seat",category:"spatial"});assert.equal(typeof game.generate,"function");assert.equal(typeof game.validate,"function");assert.equal(typeof game.render,"function")});
test("render creates every node through context.host.ownerDocument",()=>{const old=globalThis.document,foreign=fakeDocument();globalThis.document={createElement(){throw Error("global document used")}};try{const h=harness({ownerDocument:foreign}),task=game.generate(helpers(1));game.render(task,h.context);const visit=node=>{assert.equal(node.ownerDocument,foreign);node.children.forEach(visit)};visit(h.host);h.dispose()}finally{if(old===undefined)delete globalThis.document;else globalThis.document=old}});
test("5000 generated commutes clone, validate, and retain bounded time-expanded proofs",()=>{const h=helpers(),sides=new Set(),palettes=new Set(),layouts=new Set(),start=performance.now();for(let i=0;i<5000;i++){const task=game.generate(h);assert.deepEqual(game.validate(task),[],`task ${i}`);assert.doesNotThrow(()=>structuredClone(task));assert.ok(task.total<=108);assert.ok(task.wins>=2);assert.ok(Object.values(task.failureCounts).every(count=>count>0));assert.equal(task.answer.length,4);assert.equal(task.nearRoute.length,4);sides.add(task.targetSeat.side);palettes.add(task.palette);layouts.add(task.people[0].positions[0].x.toFixed(3))}assert.equal(sides.size,2);assert.equal(palettes.size,2);assert.ok(layouts.size>=8);assert.ok(performance.now()-start<7000)});
test("hostile helpers terminate at a verified authored fallback",()=>{const task=game.generate({random:()=>0,randomInt:()=>999,shuffle:v=>v,pick:v=>v[0]});assert.deepEqual(game.validate(task),[]);assert.equal(task.targetSeat.side,"left");assert.ok(task.wins>=2);assert.ok(task.total<=108)});
test("validator rejects forged geometry, IDs, roles, answers, near route, and proof counts",()=>{const task=game.generate(helpers(5));const geometry=structuredClone(task);geometry.clearance=.02;assert.match(game.validate(geometry).join(" | "),/clearance/);const ids=structuredClone(task);ids.layers[1][0].id=ids.layers[0][0].id;assert.match(game.validate(ids).join(" | "),/duplicate/);const role=structuredClone(task);role.people[4].role="runner";assert.match(game.validate(role).join(" | "),/roles|role/);const answer=structuredClone(task);answer.answer=[...answer.nearRoute].reverse();assert.match(game.validate(answer).join(" | "),/answer/);const near=structuredClone(task);near.nearRoute=[...near.answer].reverse();assert.match(game.validate(near).join(" | "),/nearRoute/);const counts=structuredClone(task);counts.wins++;counts.total--;counts.failureCounts.collision++;assert.match(game.validate(counts).join(" | "),/wins|total|failure counts/);const copy=structuredClone(task);copy.prompt="changed";copy.duration=1;assert.match(game.validate(copy).join(" | "),/prompt/);assert.match(game.validate(copy).join(" | "),/duration/)});
test("malformed plain data reports issues without throwing",()=>{let issues;assert.doesNotThrow(()=>{issues=game.validate({kind:"commuterSeat",layers:[null],people:null})});assert.ok(issues.length>8)});
test("plain JSON resumes in a fresh module and the canonical route seats exactly once",async()=>{const restore=install();try{const task=JSON.parse(JSON.stringify(game.generate(helpers(7)))),fresh=await importGame(`resume-${Date.now()}`),h=harness({reducedMotion:true});assert.deepEqual(fresh.validate(task),[]);fresh.render(task,h.context);play(h,task.answer);assert.equal(h.qa[ID].inspect().result,"success");assert.deepEqual(h.finishes.map(x=>x.correct),[true]);assert.equal(h.qa[ID].inspect().route.length,4);h.triggerDeadline();assert.equal(h.finishes.length,1)}finally{restore()}});
test("a second legal route also succeeds and near-miss clearance remains safe",()=>{const restore=install();try{const task=game.generate(helpers(8)),h=harness({reducedMotion:true});game.render(task,h.context);const winners=paths(task).filter(path=>h.qa[ID].simulate(path).ok);assert.ok(winners.length>=2);assert.notDeepEqual(winners[0],winners[1]);play(h,task.nearRoute);assert.equal(h.qa[ID].inspect().result,"success");assert.equal(h.finishes[0].correct,true)}finally{restore()}});
for(const [reason,title] of [["collision","collision with a standing passenger or bag"],["blocked-alighter","blocking the alighting passenger"],["seat-taken","the competing passenger taking the seat"],["door-close","remaining beside the closing door"]])test(`${title} is a distinct deterministic failure`,()=>{const restore=install();try{const task=game.generate(helpers(reason.length)),h=harness({reducedMotion:true});game.render(task,h.context);const route=routeFor(task,h.qa[ID],reason);assert.ok(route,reason);play(h,route);const state=h.qa[ID].inspect();assert.equal(state.done,true);assert.equal(state.result,reason);assert.deepEqual(h.finishes.map(x=>x.correct),[false]);assert.equal(stage(h.host).classList.contains(reason),true);if(reason==="seat-taken"){const panel=stage(h.host).children[2],badge=scene(h.host).children[4];assert.equal(badge.textContent,"先客着席 / OCCUPIED");assert.match(panel.children[0].textContent,/目的の席/);assert.match(panel.children[1].textContent,/先客/);assert.doesNotMatch(panel.children.map(node=>node.textContent).join(" "),/OPEN|光る空席/)}}finally{restore()}});
test("invalid route input is reversible and consumes neither step nor route",()=>{const restore=install();try{const task=game.generate(helpers(13)),h=harness({reducedMotion:true});game.render(task,h.context);assert.equal(h.qa[ID].choose("missing-node"),false);let state=h.qa[ID].inspect();assert.equal(state.invalid,true);assert.deepEqual(state.invalidTarget,{x:.07,y:.52,reason:"座席で通行不可"});assert.match(state.status,/座席を横切る/);const evidence=scene(h.host).children[5];assert.equal(evidence.children[0].textContent,"×");assert.equal(evidence.children[1].textContent,"座席で通行不可");assert.equal(state.step,0);assert.deepEqual(state.route,[]);assert.equal(h.finishes.length,0);h.runAll();state=h.qa[ID].inspect();assert.equal(state.invalid,false);assert.equal(state.invalidTarget,null);assert.equal(state.step,0)}finally{restore()}});
test("reduced motion keeps nonzero PREVIEW, MOVING midpoint, arrival, and resolve stages",()=>{const restore=install();try{const task=game.generate(helpers(14)),h=harness({reducedMotion:true});game.render(task,h.context);assert.equal(h.qa[ID].choose(task.answer[0]),true);assert.equal(h.qa[ID].commit(),true);let state=h.qa[ID].inspect();assert.equal(state.phase,"PREVIEW");assert.ok(h.delays.every(ms=>ms>0));h.runNext();state=h.qa[ID].inspect();assert.equal(state.phase,"MOVING");assert.notDeepEqual(state.visual,state.current);assert.ok(h.delays.every(ms=>ms>0));const midpoint={...state.visual};h.runNext();state=h.qa[ID].inspect();assert.equal(state.phase,"MOVING");assert.notDeepEqual(state.visual,midpoint);assert.ok(h.delays.every(ms=>ms>0));h.runNext();state=h.qa[ID].inspect();assert.equal(state.phase,"SELECT");assert.equal(state.step,1);assert.equal(h.frames,0)}finally{restore()}});
test("deadline is a distinct timeout and cannot double finish",()=>{const restore=install();try{const task=game.generate(helpers(15)),h=harness();game.render(task,h.context);h.triggerDeadline();assert.equal(h.qa[ID].inspect().result,"timeout");h.runAll();h.triggerDeadline();assert.deepEqual(h.finishes.map(x=>x.correct),[false]);assert.equal(h.finishes[0].result.reason,"timeout");assert.equal(stage(h.host).classList.contains("timeout"),true)}finally{restore()}});
test("dispose during movement clears jobs, deadline, listeners, and QA without finish",()=>{const restore=install();try{const task=game.generate(helpers(16)),h=harness();game.render(task,h.context);h.qa[ID].choose(task.answer[0]);h.qa[ID].commit();assert.ok(h.jobs>0);h.dispose();h.runAll();h.triggerDeadline();assert.equal(h.finishes.length,0);assert.equal(h.jobs,0);assert.equal(h.listeners,0);assert.equal(h.qa[ID],undefined)}finally{restore()}});
test("real kernel abort removes every commuter-owned resource",async()=>{const restore=install(),oldRaf=globalThis.requestAnimationFrame,oldCancel=globalThis.cancelAnimationFrame;globalThis.requestAnimationFrame=fn=>setTimeout(()=>fn(performance.now()),0);globalThis.cancelAnimationFrame=id=>clearTimeout(id);try{const task=game.generate(helpers(17)),qa={},finishes=[],host=document.createElement("div");host.getBoundingClientRect=()=>({width:393,height:852});const runtime=createGameRuntime({host,qa,reducedMotion:false,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(task,runtime.context);qa[ID].choose(task.answer[0]);qa[ID].commit();runtime.dispose();assert.equal(qa[ID],undefined);await delay(800);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{restore();if(oldRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=oldRaf;if(oldCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=oldCancel}});
test("touch, keyboard focus, observable ARIA, controls, reduced mode, and DPR remain usable",()=>{const restore=install();try{const task=game.generate(helpers(18)),h=harness({reducedMotion:true,viewport:{width:402,height:874,dpr:3}});game.render(task,h.context);const buttons=routeButtons(h.host);assert.ok(buttons.length>=3);assert.equal(document.activeElement,buttons[0]);buttons[0].dispatchEvent(ev("keydown",{key:"ArrowRight"}));assert.equal(document.activeElement,buttons[1]);buttons[1].dispatchEvent(ev("click",{pointerType:"touch",detail:1}));assert.equal(h.qa[ID].inspect().pending,buttons[1].dataset.id);assert.match(buttons[1].getAttribute("aria-label"),/歩目.*(通路|鞄|立客|降車)/);controls(h.host)[1].dispatchEvent(ev("click",{detail:1}));assert.equal(h.qa[ID].inspect().phase,"PREVIEW");h.runAll();const canvas=h.qa[ID].inspect().canvas;assert.equal(canvas.dpr,3);assert.equal(canvas.width,canvas.cssWidth*3);assert.equal(canvas.height,canvas.cssHeight*3);assert.equal(stage(h.host).dataset.reduced,"true");assert.equal(h.frames,0)}finally{restore()}});
test("one and twelve generated proofs stay within the interaction budget",()=>{const h=helpers(19),a=performance.now(),one=game.generate(h);assert.deepEqual(game.validate(one),[]);const oneMs=performance.now()-a,b=performance.now();for(let i=0;i<12;i++){const task=game.generate(h);assert.deepEqual(game.validate(task),[])}const twelveMs=performance.now()-b;assert.ok(oneMs<100);assert.ok(twelveMs<800)});
test("source is ownerDocument-only, tracked-lifetime, network-free, audio-free, and emoji-free",()=>{assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|webkitAudioContext|new Audio)\b/);assert.doesNotMatch(source,/[\u{1F300}-\u{1FAFF}]/u)});
