import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";

const moduleUrl=new URL("../src/games/spatial-draw-shelter-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8");
const importGame=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n// ${suffix}`).toString("base64")}`)).default,game=await importGame("primary"),ID="spatial-draw-shelter-v1";
const helpers=(index=0)=>({pick:values=>values[index%values.length]});
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}sync(){this.owner._className=[...this.values].join(" ")}}
class FakeStyle{constructor(){this.values=new Map()}setProperty(key,value){this.values.set(key,String(value))}getPropertyValue(key){return this.values.get(key)||""}}
const noop=()=>{};function canvasContext(){const gradient={addColorStop:noop};return new Proxy({createLinearGradient:()=>gradient,createRadialGradient:()=>gradient,measureText:text=>({width:String(text).length*8})},{get:(target,key)=>key in target?target[key]:noop,set:(target,key,value)=>(target[key]=value,true)})}
class FakeElement extends EventTarget{constructor(tag,ownerDocument){super();this.tagName=tag.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.attributes=new Map();this.dataset={};this.style=new FakeStyle();this.classList=new FakeClassList(this);this._className="";this.textContent="";this.disabled=false;this.type="";this.tabIndex=-1;this.width=0;this.height=0}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this.children=[...nodes]}setAttribute(key,value){this.attributes.set(key,String(value))}getAttribute(key){return this.attributes.get(key)??null}focus(){this.ownerDocument.activeElement=this}getContext(kind){return this.tagName==="CANVAS"&&kind==="2d"?canvasContext():null}getBoundingClientRect(){const width=Number.parseFloat(this.style.width)||390,height=Number.parseFloat(this.style.height)||406;return{left:0,top:0,width,height,right:width,bottom:height}}}
function fakeDocument(name="doc"){const view=new EventTarget();view.devicePixelRatio=3;const documentRef={name,defaultView:view,activeElement:null};documentRef.createElement=tag=>new FakeElement(tag,documentRef);return documentRef}
function installDocument(){const previous=globalThis.document;globalThis.document=fakeDocument();return()=>{if(previous===undefined)delete globalThis.document;else globalThis.document=previous}}
function harness({reducedMotion=false,viewport={width:393,height:852,dpr:3},ownerDocument=globalThis.document}={}){const controller=new AbortController(),host=ownerDocument.createElement("div"),qa={},jobs=[],listeners=new Set(),finishes=[];let deadline=null,disposed=false,frameFn=null,frameCalls=0;host.getBoundingClientRect=()=>({left:0,top:0,width:viewport.width-16,height:viewport.height,right:viewport.width-16,bottom:viewport.height});const context={host,signal:controller.signal,qa,reducedMotion,viewport,finish(correct,detail){if(disposed||finishes.length)return false;finishes.push({correct,detail});return true},later(fn,ms){const job={fn,ms,active:true};jobs.push(job);return job},setDeadline(ms,fn){deadline={ms,fn,active:true};return deadline},frame(fn){frameFn=fn;frameCalls++;return()=>{frameFn=null}},listen(target,type,fn,options){target.addEventListener(type,fn,options);const row={target,type,fn,options};listeners.add(row);return()=>{target.removeEventListener(type,fn,options);listeners.delete(row)}}};const runNext=()=>{const ready=jobs.splice(0);ready.forEach(job=>{if(job.active&&!disposed){job.active=false;job.fn()}})};const runAll=()=>{let guard=0;while(jobs.some(job=>job.active)){if(++guard>200)throw new Error("pending loop");runNext()}};const runFrame=time=>{if(!frameFn||disposed)return false;const keep=frameFn(time);if(keep===false)frameFn=null;return keep};const triggerDeadline=()=>{if(deadline?.active&&!disposed){deadline.active=false;deadline.fn()}};const dispose=()=>{if(disposed)return;controller.abort();disposed=true;jobs.forEach(job=>job.active=false);if(deadline)deadline.active=false;frameFn=null;for(const row of listeners)row.target.removeEventListener(row.type,row.fn,row.options);listeners.clear()};return{context,host,qa,finishes,runNext,runAll,runFrame,triggerDeadline,dispose,get delays(){return jobs.filter(job=>job.active).map(job=>job.ms)},get pending(){return jobs.filter(job=>job.active).length},get listenerCount(){return listeners.size},get frameCalls(){return frameCalls}}}
const ev=(type,props={})=>{const event=new Event(type,{bubbles:true,cancelable:true});for(const [key,value] of Object.entries(props))Object.defineProperty(event,key,{value});return event};
const stage=host=>host.children[1],board=host=>stage(host).children[2],canvas=host=>board(host).children[0],controls=host=>stage(host).children[3].children;
const advanceToEnd=(h,limit=110)=>{h.qa[ID].advance(limit);h.runAll();return h.qa[ID].inspect()};

test("metadata is the reserved 2.0 spatial identity",()=>{assert.deepEqual(game.metadata,{id:ID,introducedIn:"2.0",tier:3,flavor:"wild",step:1,family:"spatial-draw-shelter",category:"spatial"});assert.equal(typeof game.generate,"function");assert.equal(typeof game.validate,"function");assert.equal(typeof game.render,"function")});
test("2,000 generated tasks remain bounded, plain, authored, and finite-proven",()=>{const ids=new Set(),started=performance.now();for(let index=0;index<2000;index++){const task=game.generate(helpers(index));assert.deepEqual(game.validate(task),[],task.layoutId);assert.deepEqual(structuredClone(task),task);ids.add(task.layoutId);assert.equal(task.proof.canonical.outcome,"success");assert.equal(task.proof.collapse.outcome,"collapse");assert.equal(task.proof.sting.outcome,"sting");assert.equal(task.proof.canonical.steps,96);assert.ok(task.proof.canonical.collisions>=1);assert.ok(task.proof.canonical.length<=task.maxLength);assert.equal(task.proof.canonical.twoAnchors,true)}assert.equal(ids.size,4);assert.ok(performance.now()-started<6000)});
test("validator rejects changed authored terrain, false proof, tangled canonical semantics, and simulation timing",()=>{const task=game.generate(helpers(0)),mutate=fn=>{const value=structuredClone(task);fn(value);return game.validate(value).join(" | ")};assert.match(mutate(value=>value.proof.canonical.outcome="sting"),/proof/);assert.match(mutate(value=>value.terrain.groundY=.8),/authored garden/);assert.match(mutate(value=>value.canonical=value.witnesses.collapse),/authored garden|canonical/);assert.match(mutate(value=>value.maxLength=9),/maxLength/);assert.match(mutate(value=>value.stepMs=20),/simulation timing/);assert.match(mutate(value=>value.anchors[0].id=value.anchors[1].id),/anchor/);assert.doesNotThrow(()=>game.validate({kind:"drawShelter",anchors:null,targets:null,bees:null,witnesses:null}));assert.ok(game.validate(null).length)});
test("plain JSON resumes in a fresh module and canonical dynamic barrier succeeds once",async()=>{const restore=installDocument();try{const task=JSON.parse(JSON.stringify(game.generate(helpers(1)))),fresh=await importGame(`resume-${Date.now()}`),h=harness({reducedMotion:true});assert.deepEqual(fresh.validate(task),[]);fresh.render(task,h.context);assert.equal(h.qa[ID].solve(),true);h.runAll();const state=h.qa[ID].inspect();assert.equal(state.result,"success");assert.equal(state.physics.collisions,task.proof.canonical.collisions);assert.deepEqual(h.finishes.map(item=>item.correct),[true]);h.triggerDeadline();h.runAll();assert.equal(h.finishes.length,1)}finally{restore()}});
test("unanchored and over-budget strokes are rejected without deploying or finishing",()=>{const restore=installDocument();try{const task=game.generate(helpers(0)),h=harness({reducedMotion:true});game.render(task,h.context);assert.equal(h.qa[ID].deploy([{x:.5,y:.4},{x:.6,y:.3}]),false);assert.equal(h.qa[ID].inspect().invalidReason,"unanchored");assert.equal(h.finishes.length,0);h.runAll();assert.equal(h.qa[ID].inspect().phase,"READY");const a=task.anchors[0],long=[{x:a.x,y:a.y},{x:.95,y:.05},{x:.05,y:.05},{x:.95,y:.9}];assert.equal(h.qa[ID].deploy(long),false);assert.equal(h.qa[ID].inspect().invalidReason,"over-budget");assert.equal(h.finishes.length,0);h.runAll();assert.equal(h.qa[ID].inspect().phase,"READY")}finally{restore()}});
test("bounded pointer sampling cannot skip the budget or exceed 64 points",()=>{const restore=installDocument();try{const task=game.generate(helpers(0)),h=harness({reducedMotion:true});game.render(task,h.context);assert.equal(h.qa[ID].begin(task.anchors[0]),true);for(let index=0;index<90;index++)h.qa[ID].append({x:index%2?.96:.04,y:.08+(index%8)*.1});const state=h.qa[ID].inspect();assert.ok(state.input.length<=64);assert.ok(state.inputLength<=task.maxLength+1e-9);assert.equal(state.overBudget,true);assert.equal(h.qa[ID].release(),false);h.runAll();assert.equal(h.qa[ID].inspect().phase,"READY")}finally{restore()}});
test("free-end witness sags into the protected circles and produces collapse once",()=>{const restore=installDocument();try{const task=game.generate(helpers(2)),h=harness({reducedMotion:true});game.render(task,h.context);assert.equal(h.qa[ID].deploy(task.witnesses.collapse),true);const before=h.qa[ID].inspect().physics.nodes;const state=advanceToEnd(h);assert.equal(state.result,"collapse");assert.notDeepEqual(state.physics.nodes,before);assert.deepEqual(h.finishes.map(item=>item.detail.reason),["collapse"]);h.triggerDeadline();h.runAll();assert.equal(h.finishes.length,1)}finally{restore()}});
test("low anchored witness leaves the trajectory open and produces sting once",()=>{const restore=installDocument();try{const task=game.generate(helpers(3)),h=harness({reducedMotion:true});game.render(task,h.context);assert.equal(h.qa[ID].deploy(task.witnesses.sting),true);const state=advanceToEnd(h);assert.equal(state.result,"sting");assert.equal(state.physics.end,task.anchors.at(-1).id);assert.deepEqual(h.finishes.map(item=>item.correct),[false]);assert.match(h.finishes[0].detail.detail,/群れ/)}finally{restore()}});
test("canonical hornet impacts deform the constrained ribbon instead of using a static hitbox",()=>{const restore=installDocument();try{const task=game.generate(helpers(0)),h=harness({reducedMotion:true});game.render(task,h.context);h.qa[ID].deploy(task.canonical);const initial=h.qa[ID].inspect().physics;h.qa[ID].advance(70);const moved=h.qa[ID].inspect().physics;assert.notDeepEqual(moved.nodes,initial.nodes);assert.notDeepEqual(moved.bees,initial.bees);h.qa[ID].advance(40);h.runAll();const final=h.qa[ID].inspect();assert.equal(final.result,"success");assert.ok(final.physics.collisions>=1);assert.equal(final.physics.start,task.anchors[0].id);assert.equal(final.physics.end,task.anchors[1].id)}finally{restore()}});
test("reduced motion advances deterministic nonzero tracked steps without a continuous frame",()=>{const restore=installDocument();try{const task=game.generate(helpers(1)),h=harness({reducedMotion:true});game.render(task,h.context);assert.equal(h.frameCalls,0);h.qa[ID].deploy(task.canonical);assert.deepEqual(h.delays,[100]);h.runNext();assert.equal(h.qa[ID].inspect().physics.step,4);assert.ok(h.delays.every(ms=>ms>0));h.runAll();assert.equal(h.qa[ID].inspect().result,"success");assert.deepEqual(h.finishes.map(item=>item.correct),[true])}finally{restore()}});
test("normal tracked frame accumulates fixed 25ms physics at approximately 60fps",()=>{const restore=installDocument();try{const task=game.generate(helpers(0)),h=harness();game.render(task,h.context);assert.equal(h.frameCalls,1);h.qa[ID].deploy(task.canonical);for(let frame=0;frame<180&&!h.qa[ID].inspect().done;frame++)h.runFrame(frame*1000/60);h.runAll();assert.equal(h.qa[ID].inspect().result,"success");assert.equal(h.qa[ID].inspect().physics.step,96);assert.deepEqual(h.finishes.map(item=>item.correct),[true])}finally{restore()}});
test("keyboard lattice and touch drawing share the one continuous sampled ribbon",()=>{const restore=installDocument();try{const task=game.generate(helpers(0)),h=harness({reducedMotion:true,viewport:{width:402,height:874,dpr:3}});game.render(task,h.context);const pads=controls(h.host);assert.equal(document.activeElement,board(h.host));pads[0].dispatchEvent(ev("click",{detail:0}));assert.equal(h.qa[ID].inspect().phase,"DRAWING");board(h.host).dispatchEvent(ev("keydown",{key:"ArrowUp"}));board(h.host).dispatchEvent(ev("keydown",{key:"ArrowRight"}));assert.ok(h.qa[ID].inspect().input.length>1);board(h.host).dispatchEvent(ev("keydown",{key:"Escape"}));assert.equal(h.qa[ID].inspect().phase,"READY");const c=canvas(h.host),first=task.canonical[0],last=task.canonical.at(-1),pointerId=9,{cssWidth,cssHeight}=h.qa[ID].inspect().canvas;c.dispatchEvent(ev("pointerdown",{pointerId,clientX:first.x*cssWidth,clientY:first.y*cssHeight,pointerType:"touch"}));for(const p of task.canonical.slice(1,-1))c.dispatchEvent(ev("pointermove",{pointerId,clientX:p.x*cssWidth,clientY:p.y*cssHeight,pointerType:"touch"}));c.dispatchEvent(ev("pointerup",{pointerId,clientX:last.x*cssWidth,clientY:last.y*cssHeight,pointerType:"touch"}));assert.equal(h.qa[ID].inspect().phase,"HAZARD");const backing=h.qa[ID].inspect().canvas;assert.equal(backing.dpr,3);assert.equal(backing.width,backing.cssWidth*3);assert.equal(stage(h.host).dataset.reduced,"true")}finally{restore()}});
test("deadline before shelter deployment renders timeout and commits incorrect once",()=>{const restore=installDocument();try{const task=game.generate(helpers(0)),h=harness();game.render(task,h.context);h.triggerDeadline();h.runAll();assert.equal(h.qa[ID].inspect().result,"timeout");assert.equal(stage(h.host).dataset.result,"TIMEOUT");assert.deepEqual(h.finishes.map(item=>item.correct),[false]);h.triggerDeadline();h.runAll();assert.equal(h.finishes.length,1)}finally{restore()}});
test("dispose during live hazard cancels reduced steps, deadline, listeners, QA, and finish",()=>{const restore=installDocument();try{const task=game.generate(helpers(0)),h=harness({reducedMotion:true});game.render(task,h.context);h.qa[ID].deploy(task.canonical);assert.ok(h.pending>0);h.dispose();h.runAll();h.triggerDeadline();assert.equal(h.finishes.length,0);assert.equal(h.pending,0);assert.equal(h.listenerCount,0);assert.equal(h.qa[ID],undefined)}finally{restore()}});
test("real kernel disposal leaves no frame, timer, listener, QA, or finish alive",async()=>{const restore=installDocument(),oldRaf=globalThis.requestAnimationFrame,oldCancel=globalThis.cancelAnimationFrame;globalThis.requestAnimationFrame=fn=>setTimeout(()=>fn(performance.now()),0);globalThis.cancelAnimationFrame=id=>clearTimeout(id);try{const task=game.generate(helpers(0)),qa={},finishes=[],host=document.createElement("div");host.getBoundingClientRect=()=>({width:393,height:852});const runtime=createGameRuntime({host,qa,reducedMotion:false,viewport:{width:393,height:852,dpr:3},onFinish:(correct,detail)=>finishes.push({correct,detail})});game.render(task,runtime.context);qa[ID].deploy(task.canonical);runtime.dispose();await delay(700);assert.equal(qa[ID],undefined);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{restore();if(oldRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=oldRaf;if(oldCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=oldCancel}});
test("render owns DOM through ownerDocument and source has no raw lifetime, network, or audio path",()=>{const previous=globalThis.document,foreign=fakeDocument("foreign");globalThis.document={createElement(){throw new Error("global document used")}};try{const h=harness({ownerDocument:foreign});game.render(game.generate(helpers(0)),h.context);const visit=node=>{assert.equal(node.ownerDocument,foreign);for(const child of node.children||[])visit(child)};visit(h.host);h.dispose()}finally{if(previous===undefined)delete globalThis.document;else globalThis.document=previous}assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|webkitAudioContext|new Audio)\b/)});
