import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";

const moduleUrl=new URL("../src/games/spatial-rope-untangle-v1.js",import.meta.url),moduleSource=await readFile(moduleUrl,"utf8");
const importGame=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${moduleSource}\n// ${suffix}`).toString("base64")}`)).default;
const game=await importGame("primary"),ID="spatial-rope-untangle-v1";
function randomHelpers(initialSeed=0x71e5){let seed=initialSeed>>>0;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32),randomInt=(min,max)=>min+Math.floor(random()*(max-min+1));return{random,randomInt,pick:values=>values[randomInt(0,values.length-1)],shuffle:values=>[...values]}}
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}toggle(value,force){const add=force===undefined?!this.values.has(value):force;add?this.values.add(value):this.values.delete(value);this.sync();return add}sync(){this.owner._className=[...this.values].join(" ")}}
class FakeStyle{constructor(){this.values=new Map()}setProperty(name,value){this.values.set(name,String(value))}}
const noop=()=>{};function fakeCanvasContext(){const gradient={addColorStop:noop};return new Proxy({createLinearGradient:()=>gradient,createRadialGradient:()=>gradient},{get(target,key){return key in target?target[key]:noop},set(target,key,value){target[key]=value;return true}})}
class FakeElement extends EventTarget{constructor(tagName,ownerDocument){super();this.tagName=tagName.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.attributes=new Map();this.dataset={};this.style=new FakeStyle();this.classList=new FakeClassList(this);this._className="";this.textContent="";this.type="";this.disabled=false;this.width=0;this.height=0}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this.children=[...nodes]}setAttribute(name,value){this.attributes.set(name,String(value))}getAttribute(name){return this.attributes.get(name)??null}focus(){this.ownerDocument.activeElement=this}get offsetWidth(){return 390}getContext(kind){return this.tagName==="CANVAS"&&kind==="2d"?fakeCanvasContext():null}getBoundingClientRect(){const width=Number.parseFloat(this.style.width)||390,height=Number.parseFloat(this.style.height)||367;return{left:0,top:0,width,height,right:width,bottom:height}}}
function createFakeDocument(name="document"){const view=new EventTarget();view.devicePixelRatio=3;const documentRef={name,activeElement:null,defaultView:view};documentRef.createElement=tag=>new FakeElement(tag,documentRef);return documentRef}
function installFakeDocument(){const previous=globalThis.document;globalThis.document=createFakeDocument("global");return()=>{if(previous===undefined)delete globalThis.document;else globalThis.document=previous}}
function createHarness({reducedMotion=false,viewport={width:390,height:844,dpr:2},ownerDocument=globalThis.document}={}){const controller=new AbortController(),host=ownerDocument.createElement("div"),qa={},pending=[],listeners=new Set(),finishes=[];let deadline=null,disposed=false,frameCalls=0;host.getBoundingClientRect=()=>({left:0,top:0,width:viewport.width-16,height:viewport.height});const context={host,signal:controller.signal,reducedMotion,viewport,qa,finish(correct,result){if(disposed||finishes.length)return false;finishes.push({correct,result});return true},setDeadline(ms,fn){deadline={ms,fn,active:true};return deadline},later(fn,ms){const job={fn,ms,active:true};pending.push(job);return job},frame(){frameCalls++;return()=>{}},listen(target,type,fn,options){target.addEventListener(type,fn,options);const record={target,type,fn,options};listeners.add(record);return()=>{target.removeEventListener(type,fn,options);listeners.delete(record)}}};const runAll=()=>{while(pending.some(job=>job.active)){const jobs=pending.splice(0);jobs.forEach(job=>{if(job.active&&!disposed){job.active=false;job.fn()}})}};const triggerDeadline=()=>{if(deadline?.active&&!disposed){deadline.active=false;deadline.fn()}};const dispose=()=>{if(disposed)return;controller.abort();disposed=true;pending.forEach(job=>job.active=false);if(deadline)deadline.active=false;listeners.forEach(({target,type,fn,options})=>target.removeEventListener(type,fn,options));listeners.clear()};return{context,host,qa,finishes,runAll,triggerDeadline,dispose,get pendingCount(){return pending.filter(job=>job.active).length},get listenerCount(){return listeners.size},get frameCalls(){return frameCalls}}}
const eventWith=(type,properties={})=>{const event=new Event(type,{bubbles:true,cancelable:true});Object.entries(properties).forEach(([key,value])=>Object.defineProperty(event,key,{value}));return event};
const pegButtons=host=>host.children[1].children[1].children[1].children;
const controls=host=>host.children[1].children[2].children;
const legacyTask=()=>({kind:"ropeUntangle",prompt:"ロープの交差をゼロに",help:"杭をドラッグして動かします。",points:[{x:.2,y:.2},{x:.8,y:.3},{x:.3,y:.8},{x:.75,y:.75},{x:.2,y:.5},{x:.55,y:.15}],edges:Array.from({length:6},(_,i)=>[i,(i+1)%6]),start:2,nodes:6,duration:70000});

test("metadata is the published stable identity",()=>{assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.8",tier:2,flavor:"quirky",step:1,family:"spatial-rope-untangle",category:"spatial"});assert.equal(typeof game.generate,"function");assert.equal(typeof game.validate,"function");assert.equal(typeof game.render,"function")});
test("render creates every node from host.ownerDocument",()=>{const previous=globalThis.document,foreign=createFakeDocument("iframe");globalThis.document={createElement(){throw Error("global document used")}};try{const harness=createHarness({ownerDocument:foreign}),task=game.generate(randomHelpers(2));game.render(task,harness.context);const visit=node=>{assert.equal(node.ownerDocument,foreign);node.children.forEach(visit)};visit(harness.host);assert.equal(foreign.activeElement,pegButtons(harness.host)[0]);harness.dispose()}finally{if(previous===undefined)delete globalThis.document;else globalThis.document=previous}});
test("5000 generated tangles are cloneable, strict 3-7 crossings, separated, and convex-solvable",()=>{const helpers=randomHelpers(),distribution=new Map(),started=performance.now();for(let index=0;index<5000;index++){const task=game.generate(helpers),issues=game.validate(task);assert.deepEqual(issues,[],`generation ${index}: ${issues}`);assert.doesNotThrow(()=>structuredClone(task));assert.ok(task.start>=3&&task.start<=7);assert.equal(task.points.length,task.nodes);distribution.set(task.start,(distribution.get(task.start)||0)+1)}assert.deepEqual([...distribution.keys()].sort(),[3,4,5,6,7]);assert.ok(performance.now()-started<4000)});
test("bounded generation uses an authored three-crossing fallback",()=>{const task=game.generate({random:()=>0,randomInt:min=>min});assert.equal(task.start,3);assert.deepEqual(game.validate(task),[])});
test("validator rejects false crossing counts, malformed graphs, close pegs, and tangled solutions",()=>{const task=game.generate(randomHelpers(13));const count=structuredClone(task);count.start++;assert.match(game.validate(count).join(" | "),/start does not match/);const graph=structuredClone(task);graph.edges[0]=[0,3];assert.match(game.validate(graph).join(" | "),/edges/);const close=structuredClone(task);close.points[1]={...close.points[0]};assert.match(game.validate(close).join(" | "),/0.16 apart/);const answer=structuredClone(task);answer.solution=structuredClone(task.points);assert.match(game.validate(answer).join(" | "),/solution still contains crossings/)});
test("the exact published fallback remains accepted and resumes to a real correct finish",()=>{const restore=installFakeDocument();try{const task=legacyTask();assert.deepEqual(game.validate(task),[]);const harness=createHarness();game.render(structuredClone(task),harness.context);assert.equal(harness.qa[ID].inspect().crossings,2);harness.qa[ID].solve();harness.runAll();assert.deepEqual(harness.finishes.map(entry=>entry.correct),[true]);assert.equal(harness.qa[ID].inspect().crossings,0);assert.equal(task.solution,undefined)}finally{restore()}});
test("plain generated JSON without additive fields re-proves and completes after fresh reload",async()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(22));delete task.solution;delete task.difficulty;const fresh=await importGame(`fresh-${Date.now()}`);assert.deepEqual(fresh.validate(task),[]);const harness=createHarness();fresh.render(structuredClone(task),harness.context);harness.qa[ID].solve();harness.runAll();assert.deepEqual(harness.finishes.map(entry=>entry.correct),[true]);harness.triggerDeadline();assert.equal(harness.finishes.length,1)}finally{restore()}});
test("dragging a peg onto another is illegal and snaps back without changing the tangle",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(31)),harness=createHarness({reducedMotion:true});game.render(task,harness.context);const pegs=pegButtons(harness.host),before=harness.qa[ID].inspect(),target=before.points[1],pointerId=7;pegs[0].dispatchEvent(eventWith("pointerdown",{pointerId,clientX:before.points[0].x*390,clientY:before.points[0].y*367}));assert.equal(pegs[0].classList.contains("aru-dragging"),true);pegs[0].dispatchEvent(eventWith("pointermove",{pointerId,clientX:target.x*390,clientY:target.y*367}));assert.equal(harness.qa[ID].inspect().invalid,true);pegs[0].dispatchEvent(eventWith("pointerup",{pointerId}));assert.deepEqual(harness.qa[ID].inspect().points,before.points);assert.equal(harness.qa[ID].inspect().crossings,before.crossings);assert.match(harness.qa[ID].inspect().status,/戻しました/)}finally{restore()}});
test("accessible convex placement reduces crossings and finishes exactly once",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(41)),harness=createHarness();game.render(task,harness.context);let reduced=false;for(let index=0;index<task.nodes&&!harness.qa[ID].inspect().done;index++){harness.qa[ID].select(index);harness.qa[ID].align();if(harness.qa[ID].inspect().crossings<task.start)reduced=true}harness.runAll();assert.equal(reduced,true);assert.deepEqual(harness.finishes.map(entry=>entry.correct),[true]);harness.triggerDeadline();assert.equal(harness.finishes.length,1)}finally{restore()}});
test("deadline with crossings remaining finishes incorrect exactly once",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(51)),harness=createHarness();game.render(task,harness.context);harness.triggerDeadline();harness.triggerDeadline();assert.deepEqual(harness.finishes.map(entry=>entry.correct),[false]);assert.match(harness.finishes[0].result.detail,/交差/);assert.equal(harness.host.children[1].children[1].classList.contains("aru-timeout"),true)}finally{restore()}});
test("dispose clears QA, deadline, listeners, pending success, and tracked frame ownership",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(61)),harness=createHarness();game.render(task,harness.context);harness.qa[ID].solve();assert.ok(harness.pendingCount>0);assert.equal(harness.frameCalls,1);harness.dispose();harness.runAll();harness.triggerDeadline();assert.equal(harness.finishes.length,0);assert.equal(harness.pendingCount,0);assert.equal(harness.listenerCount,0);assert.equal(harness.qa[ID],undefined)}finally{restore()}});
test("real createGameRuntime abort removes QA and cancels frame, deadline, and celebration",async()=>{const restore=installFakeDocument(),previousRaf=globalThis.requestAnimationFrame,previousCancel=globalThis.cancelAnimationFrame;globalThis.requestAnimationFrame=callback=>setTimeout(()=>callback(performance.now()),0);globalThis.cancelAnimationFrame=id=>clearTimeout(id);try{const task=game.generate(randomHelpers(66)),qa={},finishes=[],host=document.createElement("div");host.getBoundingClientRect=()=>({width:393,height:852});const runtime=createGameRuntime({host,qa,reducedMotion:false,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(task,runtime.context);qa[ID].solve();assert.ok(runtime.inspect().timeouts>=2);runtime.dispose();assert.equal(qa[ID],undefined);await delay(900);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{restore();if(previousRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=previousRaf;if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}});
test("touch and keyboard alternatives move pegs with focus and preserve DPR/reduced motion",()=>{const restore=installFakeDocument();try{const task=game.generate(randomHelpers(71)),harness=createHarness({reducedMotion:true,viewport:{width:402,height:874,dpr:3}});game.render(task,harness.context);const pegs=pegButtons(harness.host),pads=controls(harness.host),before=harness.qa[ID].inspect();assert.equal(document.activeElement,pegs[0]);pegs[0].dispatchEvent(eventWith("keydown",{key:"ArrowRight",shiftKey:false}));assert.notEqual(harness.qa[ID].inspect().points[0].x,before.points[0].x);pegs[1].dispatchEvent(eventWith("click",{detail:0}));assert.equal(harness.qa[ID].inspect().selected,1);assert.ok([...pads].every(button=>!button.disabled));pads[4].dispatchEvent(eventWith("keydown",{key:"Enter"}));assert.equal(harness.qa[ID].inspect().points[1].x,task.solution[1].x);const canvas=harness.qa[ID].inspect().canvas;assert.equal(canvas.dpr,3);assert.equal(canvas.width,canvas.cssWidth*3);assert.equal(harness.frameCalls,0);assert.equal(harness.host.children[1].dataset.reduced,"true")}finally{restore()}});
test("source uses ownerDocument and tracked lifetime primitives without network paths",()=>{assert.match(moduleSource,/context\.host\?\.ownerDocument/);assert.doesNotMatch(moduleSource,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(moduleSource,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(moduleSource,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon)\b/)});
