import game from "../src/games/spatial-pipe-flow-v1.js";import{createGameRuntime}from"../src/game-kernel.js";
const params=new URLSearchParams(location.search),width=Number(params.get("width"))||393,reduced=params.get("motion")==="reduced",auto=params.get("auto")==="1";document.body.style.width=`${width}px`;
const task={kind:"pipeFlow",prompt:"水を通せ",help:"パイプをタップすると回ります。左の水源から右のゴールまでつなげてください。",cells:[{"r":0,"c":0,"mask":6,"turn":3,"role":"empty"},{"r":0,"c":1,"mask":10,"turn":2,"role":"empty"},{"r":0,"c":2,"mask":12,"turn":0,"role":"empty"},{"r":0,"c":3,"mask":0,"turn":0,"role":"empty"},{"r":1,"c":0,"mask":1,"turn":0,"role":"source"},{"r":1,"c":1,"mask":2,"turn":0,"role":"empty"},{"r":1,"c":2,"mask":5,"turn":2,"role":"empty"},{"r":1,"c":3,"mask":0,"turn":0,"role":"empty"},{"r":2,"c":0,"mask":0,"turn":0,"role":"empty"},{"r":2,"c":1,"mask":6,"turn":3,"role":"empty"},{"r":2,"c":2,"mask":9,"turn":0,"role":"empty"},{"r":2,"c":3,"mask":0,"turn":0,"role":"empty"},{"r":3,"c":0,"mask":0,"turn":0,"role":"empty"},{"r":3,"c":1,"mask":3,"turn":3,"role":"empty"},{"r":3,"c":2,"mask":10,"turn":1,"role":"empty"},{"r":3,"c":3,"mask":8,"turn":3,"role":"goal"}],size:4,duration:70000};
const host=document.querySelector("#challenge"),result=document.querySelector("#result"),qa={},frameDeltas=[];let previous=performance.now(),monitoring=true,runtime,controls=null,initial=null;const monitor=now=>{if(!monitoring)return;frameDeltas.push(now-previous);previous=now;if(frameDeltas.length<900)requestAnimationFrame(monitor)};requestAnimationFrame(monitor);
const finish=(correct,detail)=>{monitoring=false;result.hidden=false;result.textContent=`${correct?"成功":"失敗"} — ${detail.detail}`;if(!auto)return;setTimeout(()=>{const inspection=runtime.inspect(),failures=[];if(!correct)failures.push("solve failed");if(!controls?.touch||!controls?.keyboard)failures.push("controls failed");if(!(inspection.disposed&&inspection.aborted&&!inspection.timeouts&&!inspection.frames&&!inspection.listeners))failures.push("cleanup failed");if(document.body.scrollWidth>width)failures.push("overflow");const report={status:failures.length?"fail":"pass",failures,correct,detail,controls,viewport:{width,dpr:devicePixelRatio,touchEvents:"ontouchstart"in window,pointerEvents:"PointerEvent"in window,bodyScrollWidth:document.body.scrollWidth},canvas:initial.canvas,runtime:inspection,resources:performance.getEntriesByType("resource").map(x=>new URL(x.name).pathname)};const pre=document.createElement("pre");pre.dataset.status=report.status;pre.textContent=JSON.stringify(report,null,2);document.body.replaceChildren(pre)},0)};
runtime=createGameRuntime({host,reducedMotion:reduced,viewport:{width,height:innerHeight,dpr:devicePixelRatio},qa,onFinish:finish});game.render(task,runtime.context);const api=qa[game.metadata.id];initial=api.inspect();
if(auto){const stage=host.querySelector(".spf-stage"),canvas=host.querySelector(".spf-canvas"),rect=canvas.getBoundingClientRect();canvas.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerType:"touch",clientX:rect.left+rect.width*.16,clientY:rect.top+rect.height*.38}));const touch=api.inspect().taps===1;stage.dispatchEvent(new KeyboardEvent("keydown",{bubbles:true,cancelable:true,key:"ArrowRight"}));const selected=api.inspect().selected;stage.dispatchEvent(new KeyboardEvent("keydown",{bubbles:true,cancelable:true,key:"Enter"}));const keyboard=api.inspect().selected===selected&&document.activeElement===stage;controls={touch,keyboard};const steps=api.solution();for(const step of steps)for(let n=0;n<step.turns&&qa[game.metadata.id];n++)qa[game.metadata.id].rotate(step.index)}
const scene=params.get("scene");if(scene)api.showScene(scene);
if(params.get("measureLog")==="1")setTimeout(()=>{monitoring=false;const stable=frameDeltas.slice(5),inspection=api.inspect(),query=new URLSearchParams({frames:String(stable.length),averageFrameMs:(stable.reduce((a,b)=>a+b,0)/Math.max(1,stable.length)).toFixed(3),maxFrameMs:Math.max(0,...stable).toFixed(3),gameFrames:String(inspection.frames),pixelWidth:String(inspection.canvas.pixelWidth),pixelHeight:String(inspection.canvas.pixelHeight),dpr:String(inspection.canvas.dpr)});location.replace(`spatial-pipe-flow-v1.performance-result.html?${query}`)},1500);
window.__PIPE_FIXTURE__={task,qa,runtime,evidence:()=>({game:qa[game.metadata.id]?.inspect(),runtime:runtime.inspect()})};
