import game from "../src/games/spatial-flip-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";
const TASKS=Object.freeze([
{kind:"rotation",prompt:"左右をひっくり返すと？",help:"鏡に映した形です。",symbol:"→",options:["↖","←","↘","↗"],answer:"←",duration:6500},
{kind:"rotation",prompt:"左右をひっくり返すと？",help:"鏡に映した形です。",symbol:"←",options:["↙","↗","→","↘"],answer:"→",duration:6500},
{kind:"rotation",prompt:"左右をひっくり返すと？",help:"鏡に映した形です。",symbol:"↗",options:["↖","↙","→","↘"],answer:"↖",duration:6500},
{kind:"rotation",prompt:"左右をひっくり返すと？",help:"鏡に映した形です。",symbol:"↘",options:["←","↙","↖","→"],answer:"↙",duration:6500},
{kind:"rotation",prompt:"左右をひっくり返すと？",help:"鏡に映した形です。",symbol:"↖",options:["↘","↗","→","←"],answer:"↗",duration:6500},
{kind:"rotation",prompt:"左右をひっくり返すと？",help:"鏡に映した形です。",symbol:"↙",options:["↘","↖","←","↗"],answer:"↘",duration:6500}
]),params=new URLSearchParams(location.search),pair=Math.max(0,Math.min(5,Number(params.get("pair"))||0)),TASK=TASKS[pair],width=Number(params.get("width"))||393,motion=params.get("motion")==="reduced"?"reduced":"normal",scene=params.get("scene")||"initial",reduced=motion==="reduced",live=params.get("live")==="1",host=document.querySelector("#challenge"),qa={},finishes=[],errors=[];document.body.style.width=`${width}px`;addEventListener("error",event=>errors.push(event.message||"page error"));addEventListener("unhandledrejection",event=>errors.push(String(event.reason)));
const runtime=createGameRuntime({host,qa,reducedMotion:reduced,viewport:{width,height:innerHeight,dpr:devicePixelRatio},onFinish:(correct,result)=>finishes.push({correct,result})}),startedAt=performance.now();game.render(structuredClone(TASK),runtime.context);const api=qa[game.metadata.id];if(!live&&!api.showScene(scene))throw new Error(`unknown scene ${scene}`);
const terminal=state=>state.result==="success"?{correct:true,result:{answerLabel:TASK.answer}}:state.result==="wrong"?{correct:false,result:{answerLabel:TASK.answer}}:state.result==="timeout"?{correct:false,result:{detail:"時間切れです。脳は定時退社しました。",answerLabel:TASK.answer}}:null,evidence=()=>{const resources=performance.getEntriesByType("resource"),external=resources.filter(entry=>new URL(entry.name).origin!==location.origin),state=api.inspect();return{variant:"module",pair,scene,live,motion,width,dpr:devicePixelRatio,task:structuredClone(TASK),constants:{rows:TASKS.map(task=>[task.symbol,task.answer]),arrows:["→","←","↗","↖","↘","↙"],duration:6500},state,computed:{source:state.source,answer:state.answer,options:state.buttons.map(button=>button.text),choicesEnabled:state.choicesEnabled,result:state.result,selected:state.selected,payload:terminal(state),feedbackStages:state.feedbackStages,focused:state.buttons.findIndex(button=>button.focused)},finishes:structuredClone(finishes),layout:{scrollWidth:document.body.scrollWidth,innerWidth,canvas:state.canvas},resources:resources.map(entry=>entry.name),external:external.map(entry=>entry.name),errors:[...errors]}};
window.__FLIP_MODULE_FIXTURE__={game,tasks:structuredClone(TASKS),task:structuredClone(TASK),pair,qa,api,runtime,startedAt,evidence};document.documentElement.dataset.ready="true";
