#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.."&&pwd);STAMP=$(date +%Y%m%d-%H%M%S);OUT=${1:-/tmp/agetest-spatial-photo-layout-v1-audit-$STAMP};cd "$ROOT";[[ ! -e "$OUT" ]]||{ echo "output exists" >&2;exit 2;};mkdir -p "$OUT";node tools/qa-browser-lanes.mjs start audit >/dev/null
ready='(async()=>{for(let i=0;i<240;i++){if(window.__PHOTO_LAYOUT_FIXTURE__&&document.documentElement.dataset.ready==="true")return true;await new Promise(r=>setTimeout(r,25))}throw Error("ready")})()';nav(){ local v=$1 s=$2 m=$3 w=$4 h=$5 live=${6:-0};node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/spatial-photo-layout-v1.fixture.html?variant=$v&scene=$s&motion=$m&width=$w&live=$live" "$w" "$h" 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null;}
variants=(0 1 2 3);metrics=(393x852 402x874);motions=(normal reduced);scenes=(initial selected rotated partial wrong-frame wrong-orientation success timeout)
for v in "${variants[@]}";do for metric in "${metrics[@]}";do w=${metric%x*};h=${metric#*x};for m in "${motions[@]}";do for s in "${scenes[@]}";do nav "$v" "$s" "$m" "$w" "$h";node tools/qa-browser-lanes.mjs eval audit 'window.__PHOTO_LAYOUT_FIXTURE__.report()' >"$OUT/evidence-$v-$metric-$s-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/album$v-$metric-$s-$m.png" >/dev/null;done;nav "$v" initial "$m" "$w" "$h" 1;node tools/qa-browser-lanes.mjs eval audit '(()=>{const f=window.__PHOTO_LAYOUT_FIXTURE__,b=f.api.elements.photos[0];b.focus();document.body.classList.add("fixture-focus");return{focused:b===document.activeElement,state:f.api.inspect(),report:f.report()}})()' >"$OUT/focus-$v-$metric-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/focus-$v-$metric-$m.png" >/dev/null;done;done;done
for metric in 390x844 430x932;do w=${metric%x*};h=${metric#*x};for v in "${variants[@]}";do for m in "${motions[@]}";do for s in initial success;do nav "$v" "$s" "$m" "$w" "$h";node tools/qa-browser-lanes.mjs eval audit 'window.__PHOTO_LAYOUT_FIXTURE__.report()' >"$OUT/boundary-$v-$metric-$s-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/boundary-album$v-$metric-$s-$m.png" >/dev/null;done;done;done;done
cue='(()=>{const f=window.__PHOTO_LAYOUT_FIXTURE__;return{variant:f.variant,turned:f.task.photos.filter(p=>p.startRotation===90).map(p=>p.id),photos:f.api.elements.photos.map(b=>({id:b.dataset.photo,orientation:b.dataset.orientation,answer:b.getAttribute("data-answer"),correct:b.getAttribute("data-correct"),rect:b.getBoundingClientRect().toJSON()})),frames:[...f.api.elements.frames.values()].map(b=>({id:b.dataset.frame,orientation:b.dataset.orientation,answer:b.getAttribute("data-answer"),correct:b.getAttribute("data-correct"),rect:b.getBoundingClientRect().toJSON()})),rotate:f.api.elements.rotateButton.getBoundingClientRect().toJSON(),report:f.report()}})()';for v in "${variants[@]}";do nav "$v" initial normal 393 852;node tools/qa-browser-lanes.mjs eval audit "$cue" >"$OUT/no-hidden-cue-$v.json";done
touch='(async()=>{const f=window.__PHOTO_LAYOUT_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms)),trace=[],select=b=>{const q=b.getBoundingClientRect(),o={bubbles:true,cancelable:true,pointerId:70,pointerType:"touch",button:0,clientX:q.left+q.width/2,clientY:q.top+q.height/2};b.dispatchEvent(new PointerEvent("pointerdown",o));b.dispatchEvent(new PointerEvent("pointercancel",o))},drag=(b,s,id)=>{const a=b.getBoundingClientRect(),z=s.getBoundingClientRect(),down={bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",button:0,clientX:a.left+a.width/2,clientY:a.top+a.height/2},up={...down,clientX:z.left+z.width/2,clientY:z.top+z.height/2};b.dispatchEvent(new PointerEvent("pointerdown",down));b.dispatchEvent(new PointerEvent("pointermove",up));b.dispatchEvent(new PointerEvent("pointerup",up))};for(let i=0;i<6;i++){const b=f.api.elements.photos[i];if(f.api.inspect().rotations[i]===90){select(b);f.api.elements.rotateButton.click();await wait(f.motion==="reduced"?155:195)}const frame=f.api.elements.frames.get(`frame-${f.task.photos[i].id}`);drag(b,frame,100+i);await wait(f.motion==="reduced"?155:195);trace.push({location:f.api.inspect().locations[i],rotation:f.api.inspect().rotations[i]})}await wait(240);const report=f.report();return{status:report.status,variant:f.variant,motion:f.motion,trace,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,targets:report.targets,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()';for v in "${variants[@]}";do for m in "${motions[@]}";do nav "$v" initial "$m" 390 844 1;node tools/qa-browser-lanes.mjs eval audit "$touch" >"$OUT/touch-success-$v-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/touch-success-$v-$m.png" >/dev/null;done;done
keyboard='(async()=>{const f=window.__PHOTO_LAYOUT_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms)),trace=[];for(let i=0;i<6;i++){const b=f.api.elements.photos[i];b.focus();if(f.api.inspect().rotations[i]===90){b.dispatchEvent(new KeyboardEvent("keydown",{key:"R",bubbles:true,cancelable:true}));await wait(f.motion==="reduced"?155:195)}b.dispatchEvent(new KeyboardEvent("keydown",{key:" ",bubbles:true,cancelable:true}));if(i===0){b.dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowRight",bubbles:true,cancelable:true}));b.dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowLeft",bubbles:true,cancelable:true}))}b.dispatchEvent(new KeyboardEvent("keydown",{key:" ",bubbles:true,cancelable:true}));await wait(f.motion==="reduced"?155:195);trace.push(f.api.inspect().locations[i])}await wait(240);const report=f.report();return{status:report.status,variant:f.variant,motion:f.motion,trace,sawArrow:true,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,targets:report.targets,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()';for pair in 0:normal 3:reduced;do v=${pair%:*};m=${pair#*:};nav "$v" initial "$m" 430 932 1;node tools/qa-browser-lanes.mjs eval audit "$keyboard" >"$OUT/keyboard-$v-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/keyboard-success-$v-$m.png" >/dev/null;done
reject='(async()=>{const f=window.__PHOTO_LAYOUT_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms)),drag=(b,s,id)=>{const a=b.getBoundingClientRect(),z=s.getBoundingClientRect(),d={bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",button:0,clientX:a.left+a.width/2,clientY:a.top+a.height/2},u={...d,clientX:z.left+z.width/2,clientY:z.top+z.height/2};b.dispatchEvent(new PointerEvent("pointerdown",d));b.dispatchEvent(new PointerEvent("pointermove",u));b.dispatchEvent(new PointerEvent("pointerup",u))};let upright=f.task.photos.findIndex(p=>p.startRotation===0),turned=f.task.photos.findIndex(p=>p.startRotation===90),wrong=f.task.frames.find(x=>x.photoId!==f.task.photos[upright].id).id;drag(f.api.elements.photos[upright],f.api.elements.frames.get(wrong),211);const frameDuring=f.api.inspect();await wait(f.motion==="reduced"?155:195);const frameAfter=f.api.inspect();drag(f.api.elements.photos[turned],f.api.elements.frames.get(`frame-${f.task.photos[turned].id}`),212);const orientationDuring=f.api.inspect();await wait(f.motion==="reduced"?155:195);const orientationAfter=f.api.inspect();const b=f.api.elements.photos[turned],q=b.getBoundingClientRect(),o={bubbles:true,cancelable:true,pointerId:213,pointerType:"touch",button:0,clientX:q.left+q.width/2,clientY:q.top+q.height/2};b.dispatchEvent(new PointerEvent("pointerdown",o));b.dispatchEvent(new PointerEvent("pointercancel",o));f.api.elements.rotateButton.click();await wait(f.motion==="reduced"?155:195);drag(b,f.api.elements.frames.get(`frame-${f.task.photos[turned].id}`),214);await wait(f.motion==="reduced"?155:195);const placed=f.api.inspect();const tray=f.api.elements.tray.getBoundingClientRect(),a=b.getBoundingClientRect(),d={bubbles:true,cancelable:true,pointerId:215,pointerType:"touch",button:0,clientX:a.left+a.width/2,clientY:a.top+a.height/2},u={...d,clientX:tray.left+tray.width/2,clientY:tray.top+tray.height/2};b.dispatchEvent(new PointerEvent("pointerdown",d));b.dispatchEvent(new PointerEvent("pointermove",u));b.dispatchEvent(new PointerEvent("pointerup",u));await wait(f.motion==="reduced"?155:195);const report=f.report();return{motion:f.motion,upright,turned,frameDuring,frameAfter,orientationDuring,orientationAfter,placed,afterReturn:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()';for m in "${motions[@]}";do nav 2 initial "$m" 390 844 1;node tools/qa-browser-lanes.mjs eval audit "$reject" >"$OUT/reject-reverse-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/reject-reverse-$m.png" >/dev/null;done
deadline='(async()=>{const f=window.__PHOTO_LAYOUT_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms));f.api.showScene("partial");const before=f.api.inspect();for(let i=0;i<220;i++){if(f.report().finishes.length)break;await wait(100)}const elapsed=performance.now()-f.renderedAt,report=f.report();return{motion:f.motion,elapsed,before,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()';nav 1 initial normal 390 844 1;node tools/qa-browser-lanes.mjs eval audit "$deadline" >"$OUT/deadline-390x844-normal.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/deadline-390x844-normal.png" >/dev/null;nav 1 initial reduced 430 932 1;node tools/qa-browser-lanes.mjs eval audit "$deadline" >"$OUT/deadline-430x932-reduced.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/deadline-430x932-reduced.png" >/dev/null
disposeNormal='(async()=>{const f=window.__PHOTO_LAYOUT_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms)),b=f.api.elements.photos[0],q=b.getBoundingClientRect(),o={bubbles:true,cancelable:true,pointerId:301,pointerType:"touch",button:0,clientX:q.left+q.width/2,clientY:q.top+q.height/2};b.dispatchEvent(new PointerEvent("pointerdown",o));const state=f.api.inspect(),before=f.runtime.inspect();f.runtime.dispose();await wait(230);return{state,before,after:f.runtime.inspect(),qaPresent:Boolean(f.qa[f.game.metadata.id]),finishes:f.report().finishes}})()';disposeReduced='(async()=>{const f=window.__PHOTO_LAYOUT_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms));f.api.rotate(0);const state=f.api.inspect(),before=f.runtime.inspect();f.runtime.dispose();await wait(230);return{state,before,after:f.runtime.inspect(),qaPresent:Boolean(f.qa[f.game.metadata.id]),finishes:f.report().finishes}})()';nav 0 initial normal 390 844 1;node tools/qa-browser-lanes.mjs eval audit "$disposeNormal" >"$OUT/dispose-390x844-normal.json";nav 0 initial reduced 430 932 1;node tools/qa-browser-lanes.mjs eval audit "$disposeReduced" >"$OUT/dispose-430x932-reduced.json"
perf='(async()=>{const f=window.__PHOTO_LAYOUT_FIXTURE__,b=f.api.elements.photos[0],q=b.getBoundingClientRect(),d=[],o={bubbles:true,cancelable:true,pointerId:401,pointerType:"touch",button:0,clientX:q.left+q.width/2,clientY:q.top+q.height/2};b.dispatchEvent(new PointerEvent("pointerdown",o));const ownedAtStart=f.runtime.inspect().frames;let p=performance.now();await new Promise(resolve=>{const tick=n=>{d.push(n-p);p=n;if(d.length===90)resolve();else requestAnimationFrame(tick)};requestAnimationFrame(tick)});const report=f.report(),runtime=f.runtime.inspect(),expected=f.motion==="normal"?1:0,result={status:d.length===90&&ownedAtStart===expected&&runtime.frames===expected&&!report.external.length&&!report.errors.length&&report.viewport.bodyScrollWidth<=report.width?"pass":"fail",motion:f.motion,frames:d.length,averageFrameMs:d.reduce((a,b)=>a+b,0)/d.length,maxFrameMs:Math.max(...d),ownedAtStart,gameOwnedFrames:runtime.frames,state:f.api.inspect(),runtime,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors};f.runtime.dispose();return result})()';nav 0 initial normal 390 844 1;node tools/qa-browser-lanes.mjs eval audit "$perf" >"$OUT/performance-390x844-normal.json";nav 3 initial reduced 430 932 1;node tools/qa-browser-lanes.mjs eval audit "$perf" >"$OUT/performance-430x932-reduced.json"
OUT="$OUT" python - <<'PY'
from pathlib import Path
from PIL import Image,ImageChops,ImageStat
import json,math,os,subprocess
r=Path(os.environ['OUT']);variants=range(4);metrics=['393x852','402x874'];motions=['normal','reduced'];scenes=['initial','selected','rotated','partial','wrong-frame','wrong-orientation','success','timeout'];rows=[];fail=[]
for v in variants:
 for metric in metrics:
  for scene in scenes:
   a=Image.open(r/f'album{v}-{metric}-{scene}-normal.png').convert('RGB');b=Image.open(r/f'album{v}-{metric}-{scene}-reduced.png').convert('RGB');d=ImageChops.difference(a,b);st=ImageStat.Stat(d);rows.append({'key':f'{v}-{metric}-{scene}','size':[a.width,a.height],'mae':round(sum(st.mean)/3,3),'normalizedRMSE':round(math.sqrt(sum(x*x for x in st.rms)/3)/255,6),'changed':round(sum(px!=(0,0,0) for px in d.getdata())/(a.width*a.height),5)})
   for m in motions:
    e=json.loads((r/f'evidence-{v}-{metric}-{scene}-{m}.json').read_text());s=e['state'];ok=(scene!='initial' or all(x=='tray' for x in s['locations'])) and (scene!='selected' or s['selected']==0) and (scene!='rotated' or s['selected']==0) and (scene!='partial' or s['evaluation']['placed']==3) and (scene!='wrong-frame' or s['rejectReason']=='frame') and (scene!='wrong-orientation' or s['rejectReason']=='orientation') and (scene!='success' or s['result']=='success' and s['evaluation']['complete']) and (scene!='timeout' or s['result']=='timeout')
    if e['status']!='pass' or e['dpr']!=3 or e['errors'] or e['external'] or e['viewport']['bodyScrollWidth']>e['width'] or min(min(t['height'],t['width']) for t in e['targets'])<44 or not ok:fail.append(f'evidence {v} {metric} {scene} {m}')
for v in variants:
 e=json.loads((r/f'no-hidden-cue-{v}.json').read_text())
 if len(e['turned'])<2 or len(e['photos'])!=6 or len(e['frames'])!=6 or any(x['answer'] or x['correct'] or min(x['rect']['width'],x['rect']['height'])<44 for x in e['photos']+e['frames']) or min(e['rotate']['width'],e['rotate']['height'])<44:fail.append(f'cue {v}')
for v in variants:
 for m in motions:
  e=json.loads((r/f'touch-success-{v}-{m}.json').read_text())
  if not(e['status']=='pass' and all(x['rotation']==0 and x['location'].startswith('frame-') for x in e['trace']) and e['after']['result']=='success' and len(e['finishes'])==1 and e['finishes'][0]['correct'] and not e['overflow'] and not e['errors']):fail.append(f'touch {v} {m}')
for v,m in [(0,'normal'),(3,'reduced')]:
 e=json.loads((r/f'keyboard-{v}-{m}.json').read_text())
 if not(e['sawArrow'] and e['after']['result']=='success' and len(e['finishes'])==1 and e['finishes'][0]['correct'] and not e['overflow']):fail.append(f'keyboard {v} {m}')
for m in motions:
 e=json.loads((r/f'reject-reverse-{m}.json').read_text());u=e['upright'];t=e['turned']
 if not(e['frameDuring']['rejectReason']=='frame' and e['frameAfter']['locations'][u]=='tray' and e['orientationDuring']['rejectReason']=='orientation' and e['orientationAfter']['locations'][t]=='tray' and e['placed']['locations'][t].startswith('frame-') and e['afterReturn']['locations'][t]=='tray' and not e['finishes']):fail.append(f'reject {m}')
for metric,m in [('390x844','normal'),('430x932','reduced')]:
 e=json.loads((r/f'deadline-{metric}-{m}.json').read_text())
 if not(19750<=e['elapsed']<=20550 and e['after']['result']=='timeout' and e['before']['locations']==e['after']['locations'] and e['before']['rotations']==e['after']['rotations'] and e['before']['selected']==e['after']['selected'] and len(e['finishes'])==1):fail.append(f'deadline {metric} {m}')
 e=json.loads((r/f'dispose-{metric}-{m}.json').read_text())
 if not(e['after']['disposed'] and e['after']['timeouts']==0 and e['after']['frames']==0 and e['after']['listeners']==0 and not e['qaPresent'] and not e['finishes']):fail.append(f'dispose {metric} {m}')
 e=json.loads((r/f'performance-{metric}-{m}.json').read_text())
 if not(e['status']=='pass' and e['frames']==90 and e['ownedAtStart']==(1 if m=='normal' else 0) and e['gameOwnedFrames']==(1 if m=='normal' else 0) and not e['overflow'] and not e['errors']):fail.append(f'perf {metric} {m}')
for metric in ['390x844','430x932']:
 w,h=map(int,metric.split('x'))
 for v in variants:
  for m in motions:
   for s in ['initial','success']:
    e=json.loads((r/f'boundary-{v}-{metric}-{s}-{m}.json').read_text());im=Image.open(r/f'boundary-album{v}-{metric}-{s}-{m}.png')
    if e['status']!='pass' or e['dpr']!=3 or e['errors'] or e['external'] or e['viewport']['bodyScrollWidth']>w or min(min(t['height'],t['width']) for t in e['targets'])<44 or im.size!=(w*3,h*3):fail.append(f'boundary {v} {metric} {s} {m}')
for v in variants:
 for metric in metrics:
  for m in motions:
   e=json.loads((r/f'focus-{v}-{metric}-{m}.json').read_text())
   if not e['focused'] or e['report']['status']!='pass':fail.append(f'focus {v} {metric} {m}')
files=[str(r/f'album0-393x852-{s}-normal.png') for s in scenes];subprocess.run(['magick','montage',*files,'-thumbnail','393x852','-tile','8x1','-geometry','+4+0',str(r/'director-contact-sheet.png')],check=True)
report={'status':'pass' if not fail else 'fail','canonicalViewports':[{'width':393,'height':852,'dpr':3},{'width':402,'height':874,'dpr':3}],'variants':list(variants),'states':scenes,'comparisons':len(rows),'canonicalScreenshots':len(rows)*2,'focusScreenshots':16,'boundaryScreenshots':32,'touchRoutes':8,'keyboardRoutes':2,'rejectionReversalRoutes':2,'allDpr3':not any('evidence' in x for x in fail),'allFullResolution':all(x['size'] in ([1179,2556],[1206,2622]) for x in rows),'maxMAE':max(x['mae'] for x in rows),'maxNormalizedRMSE':max(x['normalizedRMSE'] for x in rows),'failures':fail,'rows':rows};(r/'comparison-report.json').write_text(json.dumps(report,indent=2));print(json.dumps({k:v for k,v in report.items() if k!='rows'},indent=2));raise SystemExit(bool(fail))
PY
echo "$OUT"
