import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {performance} from "node:perf_hooks";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";

const moduleUrl=new URL("../src/games/spatial-sand-channel-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8"),importGame=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n//${suffix}`).toString("base64")}`)).default,game=await importGame("primary"),ID="spatial-sand-channel-v1";
function helpers(initial=0x5a7d){let seed=initial>>>0;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32),randomInt=(a,b)=>a+Math.floor(random()*(b-a+1)),shuffle=value=>{const array=[...value];for(let i=array.length-1;i;i--){const j=randomInt(0,i);[array[i],array[j]]=[array[j],array[i]]}return array};return{random,randomInt,shuffle,pick:value=>value[randomInt(0,value.length-1)]}}
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}toggle(value,force){const add=force===undefined?!this.values.has(value):force;add?this.values.add(value):this.values.delete(value);this.sync();return add}sync(){this.owner._className=[...this.values].join(" ")}}
class FakeStyle{constructor(){this.values=new Map()}setProperty(key,value){this.values.set(key,String(value))}}
const noop=()=>{};function canvasContext(){const gradient={addColorStop:noop};return new Proxy({createLinearGradient:()=>gradient,createRadialGradient:()=>gradient},{get:(target,key)=>key in target?target[key]:noop,set:(target,key,value)=>(target[key]=value,true)})}
class FakeElement extends EventTarget{constructor(tag,ownerDocument){super();this.tagName=tag.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.attributes=new Map();this.dataset={};this.style=new FakeStyle();this.classList=new FakeClassList(this);this._className="";this.textContent="";this.disabled=false;this.type="";this.tabIndex=-1;this.width=0;this.height=0}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this.children=[...nodes]}setAttribute(key,value){this.attributes.set(key,String(value))}getAttribute(key){return this.attributes.get(key)??null}focus(){this.ownerDocument.activeElement=this}get offsetWidth(){return 390}getContext(kind){return this.tagName==="CANVAS"&&kind==="2d"?canvasContext():null}getBoundingClientRect(){const styledWidth=Number.parseFloat(this.style.values.get("width")),styledHeight=Number.parseFloat(this.style.values.get("height")),width=Number.isFinite(styledWidth)?styledWidth:390,height=Number.isFinite(styledHeight)?styledHeight:this.classList.contains("ssc-tray")?504:504;return{left:0,top:0,width,height,right:width,bottom:height}}setPointerCapture(){}releasePointerCapture(){}}
class FakeDocument{constructor(){this.activeElement=null;this.created=[];this.defaultView=new EventTarget();this.defaultView.devicePixelRatio=3}createElement(tag){const node=new FakeElement(tag,this);this.created.push(node);return node}}
function harness({reducedMotion=false}={}){const document=new FakeDocument(),host=new FakeElement("div",document),qa={},controller=new AbortController(),jobs=[],frames=[],listeners=[],finishes=[],delays=[],deadline={callback:null,active:false};let disposed=false,nextId=0;const later=(fn,ms)=>{const job={id:++nextId,fn,ms,active:true};jobs.push(job);delays.push(ms);return()=>{job.active=false}};const frame=fn=>{const item={fn,active:true};frames.push(item);return()=>{item.active=false}};const context={host,signal:controller.signal,reducedMotion,viewport:{width:390,height:844,dpr:3},qa,later,frame,listen:(target,type,fn,options)=>{target.addEventListener(type,fn,options);const item={target,type,fn,options,active:true};listeners.push(item);return()=>{if(item.active){item.active=false;target.removeEventListener(type,fn,options)}}},setDeadline:(ms,fn)=>{deadline.callback=fn;deadline.active=true;delays.push(ms)},finish:(correct,result)=>{if(!disposed)finishes.push({correct,result})}};controller.signal.addEventListener("abort",()=>{disposed=true;deadline.active=false;jobs.forEach(job=>job.active=false);frames.forEach(item=>item.active=false)},{once:true});const runNext=()=>{const job=jobs.find(item=>item.active);if(!job)return false;job.active=false;job.fn();return true};return{context,host,qa,document,finishes,delays,get jobs(){return jobs.filter(job=>job.active).length},get frames(){return frames.filter(item=>item.active).length},get listeners(){return listeners.filter(item=>item.active).length},runNext,runAll(limit=250){let count=0;while(runNext()&&count++<limit);assert.ok(count<limit,"jobs did not settle")},runFrame(time){for(const item of frames.filter(frame=>frame.active))if(item.fn(time)===false)item.active=false},triggerDeadline(){if(deadline.active){deadline.active=false;deadline.callback?.()}},dispose(){controller.abort();listeners.forEach(item=>{if(item.active)item.target.removeEventListener(item.type,item.fn,item.options);item.active=false})}}}
const stage=host=>host.children[1],canvas=host=>stage(host).children[1].children[0];function install(){const previous={document:globalThis.document,request:globalThis.requestAnimationFrame,cancel:globalThis.cancelAnimationFrame};globalThis.document={createElement(){throw new Error("global document used")}};globalThis.requestAnimationFrame=fn=>1;globalThis.cancelAnimationFrame=()=>{};return()=>{for(const [key,value] of Object.entries(previous)){if(value===undefined)delete globalThis[key];else globalThis[key]=value}}}
function playReduced(task,plan){const h=harness({reducedMotion:true});game.render(task,h.context);const api=h.qa[ID];assert.equal(api.applyPlan(plan),true);assert.equal(api.release(),true);h.runAll();return{h,api,state:api.inspect()}}

test("metadata is the reserved original spatial identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"2.0",tier:3,flavor:"satisfying",step:1,family:"spatial-sand-channel",category:"spatial"}));
test("render creates all nodes through host.ownerDocument and DPR3 canvas",()=>{const restore=install();try{const task=game.generate(helpers()),h=harness();game.render(task,h.context);assert.ok(h.document.created.length>=15);assert.ok(h.document.created.every(node=>node.ownerDocument===h.host.ownerDocument));const state=h.qa[ID].inspect();assert.equal(state.phase,"DIG");assert.equal(state.canvas.width,state.canvas.cssWidth*3);assert.equal(state.canvas.height,state.canvas.cssHeight*3)}finally{restore()}});
test("250 generated trays clone, validate, and retain every exact authored flow proof",()=>{const variants=new Set();for(let i=0;i<250;i++){const task=game.generate(helpers(i+1));variants.add(task.variant);assert.deepEqual(game.validate(task),[]);assert.doesNotThrow(()=>structuredClone(task));assert.equal(task.proof.canonical.vessel,120);assert.equal(task.proof.nearPass.vessel,97);assert.equal(task.proof.nearFail.vessel,49);for(const proof of Object.values(task.proof)){assert.equal(proof.conserved,true);assert.equal(proof.total,120);assert.equal(proof.tick,118)}}for(let variant=0;variant<3;variant++){const values=[variant,variant],task=game.generate({randomInt:()=>values.shift()});assert.equal(task.variant,variant);assert.deepEqual(game.validate(task),[])}});
test("generation is finite under hostile helper extrema",()=>{for(const value of [-1,0,2,999,NaN,Infinity]){let calls=0;const task=game.generate({randomInt:()=>{calls++;return value}});assert.ok(calls<=2);assert.deepEqual(game.validate(task),[])}});
test("validator rejects forged geometry, plans, constants, resume, palette, proof, and conservation",()=>{const base=game.generate(helpers(4)),mutations=[task=>task.route[0].x++,task=>task.plans.canonical[0].depth=1,task=>task.totalWater=121,task=>task.resume={phase:"DIG",cuts:[{index:2,depth:4}],removed:4},task=>task.palette.water="#ffffff",task=>task.proof.canonical.vessel=119,task=>task.proof.nearPass.total=119];for(const mutate of mutations){const task=structuredClone(base);mutate(task);assert.ok(game.validate(task).length>0)}assert.doesNotThrow(()=>game.validate({}));assert.ok(game.validate(null).length)});
test("the actual simulator separates canonical, near threshold, blockage, drain, hazard, weak wall, and over-dig",()=>{const restore=install();try{const task=game.generate(helpers(5)),h=harness();game.render(task,h.context);const api=h.qa[ID],expected={canonical:"success",nearPass:"success",nearFail:"near-fail",blocked:"blocked-flow",drain:"drain-leak",contamination:"contamination",weakWall:"weak-wall",overDig:"over-dig"};for(const [plan,result] of Object.entries(expected)){const flow=api.simulate(task.plans[plan]);assert.equal(flow.result,result);assert.equal(flow.total,120);assert.equal(flow.conserved,true)}assert.ok(api.simulate(task.plans.nearPass).vessel>=90);assert.ok(api.simulate(task.plans.nearFail).vessel<90)}finally{restore()}});
test("canonical and near-pass both succeed once while retaining different finite quantities",()=>{const restore=install();try{for(const plan of ["canonical","nearPass"]){const task=game.generate(helpers(plan.length)),{h,state}=playReduced(task,plan);assert.equal(state.result,"success");assert.equal(state.flow.conserved,true);assert.equal(state.flow.total,120);assert.deepEqual(h.finishes.map(item=>item.correct),[true]);assert.equal(state.flow.vessel,plan==="canonical"?120:97);h.triggerDeadline();assert.equal(h.finishes.length,1)}}finally{restore()}});
for(const [plan,result] of [["nearFail","near-fail"],["blocked","blocked-flow"],["drain","drain-leak"],["contamination","contamination"],["weakWall","weak-wall"],["overDig","over-dig"]])test(`${result} is a distinct reachable terminal`,()=>{const restore=install();try{const task=game.generate(helpers(plan.length)),{h,state}=playReduced(task,plan);assert.equal(state.result,result);assert.equal(state.flow.total,120);assert.equal(state.flow.conserved,true);assert.deepEqual(h.finishes.map(item=>item.correct),[false]);assert.equal(stage(h.host).classList.contains(result),true)}finally{restore()}});
test("plain JSON resume retains the exact sparse terrain mask and removed material",async()=>{const restore=install();try{const task=game.generate(helpers(13)),h=harness();game.render(task,h.context);const api=h.qa[ID];api.dig(task.route[0].x,task.route[0].y,2);api.dig(task.route[1].x,task.route[1].y,1);const resume=JSON.parse(JSON.stringify(api.snapshot()));assert.equal(resume.phase,"DIG");assert.equal(resume.removed,3);const saved=JSON.parse(JSON.stringify({...task,resume})),fresh=await importGame(`resume-${Date.now()}`),next=harness();assert.deepEqual(fresh.validate(saved),[]);fresh.render(saved,next.context);assert.deepEqual(next.qa[ID].snapshot(),resume)}finally{restore()}});
test("partial excavation is reversible with clear and consumes no outcome",()=>{const restore=install();try{const task=game.generate(helpers(14)),h=harness();game.render(task,h.context);const api=h.qa[ID];assert.equal(api.dig(9,5,2),true);assert.equal(api.inspect().removed,2);assert.equal(api.clear(),true);assert.equal(api.inspect().removed,0);assert.equal(api.inspect().phase,"DIG");assert.equal(h.finishes.length,0);assert.equal(api.release(),false)}finally{restore()}});
test("normal motion advances actual water on one owned frame loop and stops it",()=>{const restore=install();try{const task=game.generate(helpers(15)),h=harness();game.render(task,h.context);const api=h.qa[ID];api.applyPlan("canonical");api.release();assert.equal(h.frames,1);let previous=api.inspect().flow.tick;for(let i=0;i<130&&!api.inspect().done;i++){h.runFrame(i*34);const current=api.inspect().flow.tick;assert.ok(current>=previous);previous=current}assert.equal(api.inspect().result,"success");assert.equal(h.frames,0);h.runAll();assert.deepEqual(h.finishes.map(item=>item.correct),[true])}finally{restore()}});
test("reduced motion uses nonzero tracked elapsed batches and no frame",()=>{const restore=install();try{const task=game.generate(helpers(16)),h=harness({reducedMotion:true});game.render(task,h.context);const api=h.qa[ID];api.applyPlan("canonical");api.release();assert.equal(h.frames,0);assert.equal(api.inspect().flow.tick,0);h.runNext();assert.equal(api.inspect().flow.tick,3);assert.ok(h.delays.every(ms=>ms>0));h.runAll();assert.equal(api.inspect().result,"success");assert.equal(h.frames,0)}finally{restore()}});
test("deadline preserves current terrain and water quantities and commits once",()=>{const restore=install();try{const task=game.generate(helpers(17)),h=harness({reducedMotion:true});game.render(task,h.context);const api=h.qa[ID];api.applyPlan("nearPass");api.release();h.runNext();const before=api.inspect();h.triggerDeadline();h.runAll();const after=api.inspect();assert.equal(after.result,"timeout");assert.equal(after.removed,before.removed);assert.equal(after.flow.total,120);assert.deepEqual(h.finishes.map(item=>item.result.reason),["timeout"]);h.triggerDeadline();assert.equal(h.finishes.length,1)}finally{restore()}});
test("dispose during flow clears timer/frame/listeners/QA and cannot finish",()=>{const restore=install();try{for(const reducedMotion of [false,true]){const task=game.generate(helpers(18)),h=harness({reducedMotion});game.render(task,h.context);h.qa[ID].applyPlan("canonical");h.qa[ID].release();assert.ok(h.jobs+h.frames>0);h.dispose();h.runAll();h.runFrame(999);h.triggerDeadline();assert.equal(h.jobs,0);assert.equal(h.frames,0);assert.equal(h.listeners,0);assert.equal(h.finishes.length,0);assert.equal(h.qa[ID],undefined)}}finally{restore()}});
test("touch drag and keyboard cursor/dig/release share bounded excavation",()=>{const restore=install();try{const task=game.generate(helpers(19)),h=harness({reducedMotion:true});game.render(task,h.context);const api=h.qa[ID],surface=canvas(h.host);surface.focus();assert.equal(h.document.activeElement,surface);const pointer=(type,x,y)=>{const event=new Event(type,{cancelable:true});for(const [key,value] of Object.entries({pointerId:7,clientX:x,clientY:y}))Object.defineProperty(event,key,{value});surface.dispatchEvent(event)};pointer("pointerdown",195,75);pointer("pointermove",190,120);pointer("pointerup",190,120);const afterTouch=api.inspect().removed;assert.ok(afterTouch>0);const key=new Event("keydown",{cancelable:true});Object.defineProperty(key,"key",{value:"ArrowRight"});surface.dispatchEvent(key);const space=new Event("keydown",{cancelable:true});Object.defineProperty(space,"key",{value:" "});surface.dispatchEvent(space);assert.ok(api.inspect().removed>=afterTouch);assert.match(source,/:focus-visible/)}finally{restore()}});
test("real kernel disposal leaves no surviving sand-channel work",async()=>{const restore=install();try{const document=new FakeDocument(),host=new FakeElement("div",document),finishes=[],runtime=createGameRuntime({host,onFinish:(...args)=>finishes.push(args),viewport:{width:390,height:844,dpr:3},reducedMotion:true,qa:{}});game.render(game.generate(helpers(20)),runtime.context);runtime.context.qa[ID].applyPlan("canonical");runtime.context.qa[ID].release();runtime.dispose();await delay(500);assert.equal(finishes.length,0);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{restore()}});
test("generation plus eight real proof simulations stay within interaction budget",()=>{const start=performance.now();for(let i=0;i<100;i++){const task=game.generate(helpers(i+30));assert.deepEqual(game.validate(task),[])}assert.ok(performance.now()-start<2500)});
test("source is ownerDocument-only, bounded, tracked, network-free, audio-free, and emoji-free",()=>{assert.doesNotMatch(source,/\bdocument\.createElement\b/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|webkitAudioContext|new Audio)\b/);assert.doesNotMatch(source,/[\u{1F300}-\u{1FAFF}]/u);assert.match(source,/context\.frame/);assert.match(source,/context\.later/);assert.match(source,/context\.setDeadline/);assert.match(source,/context\.listen/);assert.match(source,/released = active \+ vessel \+ drain \+ contamination \+ weak-wall loss|conserved/)});
