import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import game from "../src/games/spatial-pipe-flow-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";
const ID="spatial-pipe-flow-v1",source=await readFile(new URL("../src/games/spatial-pipe-flow-v1.js",import.meta.url),"utf8"),DIRS=[[-1,0],[0,1],[1,0],[0,-1]];
function helpers(seed=0x1a10f10){const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32),randomInt=(a,b)=>a+Math.floor(random()*(b-a+1)),shuffle=v=>{v=[...v];for(let i=v.length-1;i;i--){const j=randomInt(0,i);[v[i],v[j]]=[v[j],v[i]]}return v};return{random,randomInt,shuffle,pick:v=>v[randomInt(0,v.length-1)]}}
const has=(cell,dir)=>cell.mask>>((dir+4-cell.turn)%4)&1;
function connection(cells){const source=cells.find(x=>x.role==="source"),goal=cells.find(x=>x.role==="goal"),map=new Map(cells.map(x=>[`${x.r},${x.c}`,x])),lit=new Set([`${source.r},${source.c}`]),stack=[source];while(stack.length){const cell=stack.pop();DIRS.forEach(([dr,dc],dir)=>{if(!has(cell,dir))return;const next=map.get(`${cell.r+dr},${cell.c+dc}`);if(!next||!has(next,(dir+2)%4)||lit.has(`${next.r},${next.c}`))return;lit.add(`${next.r},${next.c}`);stack.push(next)})}return{ok:lit.has(`${goal.r},${goal.c}`),lit}}
const fallback=()=>JSON.parse('{"kind":"pipeFlow","prompt":"水を通せ","help":"パイプをタップすると回ります。","cells":[{"r":0,"c":0,"mask":0,"turn":0,"role":"empty"},{"r":0,"c":1,"mask":0,"turn":0,"role":"empty"},{"r":0,"c":2,"mask":0,"turn":0,"role":"empty"},{"r":0,"c":3,"mask":0,"turn":0,"role":"empty"},{"r":1,"c":0,"mask":2,"turn":0,"role":"source"},{"r":1,"c":1,"mask":10,"turn":1,"role":"empty"},{"r":1,"c":2,"mask":10,"turn":0,"role":"empty"},{"r":1,"c":3,"mask":8,"turn":1,"role":"goal"},{"r":2,"c":0,"mask":0,"turn":0,"role":"empty"},{"r":2,"c":1,"mask":0,"turn":0,"role":"empty"},{"r":2,"c":2,"mask":0,"turn":0,"role":"empty"},{"r":2,"c":3,"mask":0,"turn":0,"role":"empty"},{"r":3,"c":0,"mask":0,"turn":0,"role":"empty"},{"r":3,"c":1,"mask":0,"turn":0,"role":"empty"},{"r":3,"c":2,"mask":0,"turn":0,"role":"empty"},{"r":3,"c":3,"mask":0,"turn":0,"role":"empty"}],"size":4,"duration":70000}');
class Gradient{addColorStop(){}}
class Ctx{constructor(){this.text=[];this.globalAlpha=1;this.shadowBlur=0}setTransform(){}clearRect(){}save(){}restore(){}translate(){}rotate(){}fillRect(){}beginPath(){}moveTo(){}lineTo(){}stroke(){}fill(){}arc(){}roundRect(){}setLineDash(){}fillText(t){this.text.push(String(t))}createLinearGradient(){return new Gradient()}createRadialGradient(){return new Gradient()}}
class El extends EventTarget{constructor(tag,doc){super();this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.children=[];this.attributes=new Map();this.dataset={};this.style={};this.className="";this.textContent="";this.tabIndex=-1;this.clientWidth=393;this.width=0;this.height=0;this.ctx=this.tagName==="CANVAS"?new Ctx():null}append(...x){this.children.push(...x)}replaceChildren(...x){this.children=[...x]}setAttribute(k,v){this.attributes.set(k,String(v))}getAttribute(k){return this.attributes.get(k)}focus(){this.ownerDocument.activeElement=this}getContext(){return this.ctx}getBoundingClientRect(){const width=parseFloat(this.style.width)||this.clientWidth,height=parseFloat(this.style.height)||400;return{left:0,top:0,width,height}}}
class View extends EventTarget{constructor(dpr){super();this.devicePixelRatio=dpr}}
function doc(dpr=3){const d={activeElement:null,defaultView:new View(dpr)};d.createElement=t=>new El(t,d);return d}
function event(type,props={}){const e=new Event(type,{bubbles:true,cancelable:true});Object.entries(props).forEach(([k,v])=>Object.defineProperty(e,k,{value:v}));return e}
function harness({reduced=true,viewport={width:393,height:852,dpr:3},owner=doc(viewport.dpr)}={}){const controller=new AbortController(),host=owner.createElement("div"),qa={},jobs=[],listeners=new Set(),finishes=[];let frame=null,deadline=null,now=0,disposed=false;const dispose=()=>{if(disposed)return;disposed=true;controller.abort();jobs.forEach(j=>j.on=false);frame=null;if(deadline)deadline.on=false;listeners.forEach(x=>x.t.removeEventListener(x.type,x.fn,x.opt));listeners.clear()};const context={host,signal:controller.signal,reducedMotion:reduced,viewport,qa,finish(correct,result){if(disposed||finishes.length)return false;finishes.push({correct,result});dispose();return true},later(fn,ms){const j={at:now+ms,fn,on:true};jobs.push(j);return j},setDeadline(ms,fn){deadline={at:now+ms,fn,on:true};return deadline},frame(fn){frame=fn;return()=>frame=null},listen(t,type,fn,opt){t.addEventListener(type,fn,opt);const x={t,type,fn,opt};listeners.add(x);return()=>{t.removeEventListener(type,fn,opt);listeners.delete(x)}}};const runAll=()=>{while(true){const j=jobs.filter(x=>x.on).sort((a,b)=>a.at-b.at)[0];if(!j)break;now=j.at;j.on=false;j.fn()}};const step=t=>{now=t;if(frame&&frame(t)===false)frame=null};const timeout=()=>{if(deadline?.on){deadline.on=false;deadline.fn()}};return{context,host,owner,qa,finishes,runAll,step,timeout,dispose,get listeners(){return listeners.size},get frame(){return!!frame}}}
const parts=h=>{const stage=h.host.children[1],[canvas,status,help]=stage.children;return{stage,canvas,status,help}};
test("metadata preserves the published stable identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.10",tier:2,flavor:"satisfying",step:1,family:"spatial-pipe-flow",category:"spatial"}));
test("5,000 generations are cloneable, initially broken, and solved by zero rotation",()=>{const h=helpers(),start=performance.now();for(let i=0;i<5000;i++){const task=game.generate(h);assert.deepEqual(game.validate(task),[],`task ${i}`);assert.doesNotThrow(()=>structuredClone(task));assert.equal(connection(task.cells).ok,false);const solved=task.cells.map(x=>({...x,turn:0}));assert.equal(connection(solved).ok,true)}assert.ok(performance.now()-start<5000)});
test("bounded generation returns the exact published fallback",()=>{const task=game.generate({randomInt:min=>min,shuffle:()=>[]});assert.deepEqual(task,fallback());assert.deepEqual(game.validate(task),[])});
test("validator rejects connected starts, broken solutions, duplicate coordinates, roles, masks and copy changes",()=>{const task=game.generate(helpers(7)),solved={...task,cells:task.cells.map(x=>({...x,turn:0}))},broken=structuredClone(task);broken.cells.find(x=>x.role==="source").mask=0;const duplicate=structuredClone(task);duplicate.cells[1].r=duplicate.cells[0].r;duplicate.cells[1].c=duplicate.cells[0].c;[solved,broken,duplicate,{...task,prompt:"changed"},{...task,duration:1},{...task,size:5},{...task,cells:task.cells.map((x,i)=>i?x:{...x,mask:16})}].forEach((x,i)=>assert.ok(game.validate(x).length,`mutation ${i}`))});
test("published plain-data resume rotates to a correct finish once",()=>{const h=harness();game.render(fallback(),h.context);const api=h.qa[ID],steps=api.solution();for(const step of steps)for(let n=0;n<step.turns&&h.qa[ID];n++)h.qa[ID].rotate(step.index);h.runAll();assert.equal(h.finishes.length,1);assert.equal(h.finishes[0].correct,true);assert.match(h.finishes[0].result.detail,/水を通しました/);assert.equal(ID in h.qa,false)});
test("pointer and keyboard select and rotate with visible focus",()=>{const h=harness(),task=fallback();game.render(task,h.context);const {stage,canvas}=parts(h),api=h.qa[ID],before=api.inspect();canvas.dispatchEvent(event("pointerdown",{clientX:110,clientY:160,pointerType:"touch"}));const afterPointer=api.inspect();assert.ok(afterPointer.taps>=before.taps);stage.dispatchEvent(event("keydown",{key:"ArrowDown"}));stage.dispatchEvent(event("keydown",{key:"ArrowRight"}));const selected=api.inspect().selected;stage.dispatchEvent(event("keydown",{key:"Enter"}));assert.equal(api.inspect().selected,selected);assert.equal(h.owner.activeElement,stage);h.dispose()});
test("normal rotation animates and reduced motion has no continuous frame",()=>{const normal=harness({reduced:false});game.render(fallback(),normal.context);const api=normal.qa[ID],index=api.solution()[0].index;api.rotate(index);normal.step(0);normal.step(200);assert.equal(api.inspect().rotating,false);assert.equal(normal.frame,true);normal.dispose();const reduced=harness();game.render(fallback(),reduced.context);assert.equal(reduced.frame,false);reduced.dispose()});
test("DPR canvas, visual states, partial flow and near solve remain inspectable",()=>{const h=harness({viewport:{width:402,height:874,dpr:4}});game.render(fallback(),h.context);const api=h.qa[ID];assert.equal(api.inspect().canvas.dpr,3);assert.equal(api.inspect().canvas.pixelWidth,api.inspect().canvas.cssWidth*3);for(const scene of ["initial","rotation","partial-flow","near-solve","success","timeout"])assert.equal(api.showScene(scene),true);h.dispose()});
test("deadline fails once and disposal clears tracked work and QA",async()=>{const h=harness();game.render(fallback(),h.context);h.timeout();h.timeout();assert.equal(h.finishes.length,1);assert.equal(h.finishes[0].correct,false);assert.match(h.finishes[0].result.detail,/時間切れ/);const prevR=globalThis.requestAnimationFrame,prevC=globalThis.cancelAnimationFrame;let id=0;const frames=new Map();globalThis.requestAnimationFrame=fn=>{frames.set(++id,fn);return id};globalThis.cancelAnimationFrame=n=>frames.delete(n);try{const owner=doc(),host=owner.createElement("div"),qa={},runtime=createGameRuntime({host,onFinish:()=>assert.fail(),reducedMotion:false,viewport:{width:393,height:852,dpr:3},qa});game.render(fallback(),runtime.context);assert.ok(qa[ID]);runtime.dispose();await delay(5);assert.equal(ID in qa,false);assert.equal(frames.size,0);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(prevR===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=prevR;if(prevC===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=prevC}});
test("ownerDocument isolation and source lifetime audit",()=>{const owner=doc(),old=globalThis.document;globalThis.document={createElement(){throw Error("global document")}};try{const h=harness({owner});game.render(fallback(),h.context);const visit=n=>{assert.equal(n.ownerDocument,owner);n.children.forEach(visit)};visit(h.host);h.dispose()}finally{if(old===undefined)delete globalThis.document;else globalThis.document=old}assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|addEventListener|fetch|XMLHttpRequest|WebSocket)\b/)});
