import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import game from "../src/games/spatial-cube-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";
const ID="spatial-cube-v1",source=await readFile(new URL("../src/games/spatial-cube-v1.js",import.meta.url),"utf8"),appSource=await readFile(new URL("../app.js",import.meta.url),"utf8"),COLORS=[{name:"むらさき",hex:"#A66DC2"},{name:"みどり",hex:"#6BAE8E"},{name:"きいろ",hex:"#D5A93F"},{name:"あお",hex:"#5A88BE"},{name:"ピンク",hex:"#D983A0"},{name:"しろ",hex:"#D8D4DC"}],SEQUENCES=[["right","up"],["up","right"],["right","left"],["up","down"],["right","up","left"],["up","right","down"],["right","left","up"],["up","down","right"],["right","left","right"],["up","down","up"]];
const importFresh=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n// ${suffix}`).toString("base64")}`)).default;
const faceAfter=turns=>{let state=[0,1,2,3,4,5];for(const turn of turns){const[f,r,b,l,t,d]=state;state=turn==="right"?[r,b,l,f,t,d]:turn==="left"?[l,f,r,b,t,d]:turn==="up"?[t,r,d,l,b,f]:[d,r,t,l,f,b]}return state[0]};
function helpers(initial=0x51a9e){let seed=initial>>>0;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32),randomInt=(min,max)=>min+Math.floor(random()*(max-min+1)),pick=values=>values[randomInt(0,values.length-1)],shuffle=values=>{const copy=[...values];for(let i=copy.length-1;i>0;i--){const j=randomInt(0,i);[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};return{random,randomInt,pick,shuffle}}
function legacyGenerate(h){const colors=h.shuffle(COLORS),turns=h.pick(SEQUENCES),answer=colors[faceAfter(turns)].name;return{kind:"cube",prompt:"色の位置を覚えて、最後の正面は？",help:"見えている3面を覚えてください。回転すると色が隠れます。",colors,turns,answer,options:h.shuffle([answer,...h.shuffle(colors.filter(color=>color.name!==answer)).slice(0,3).map(color=>color.name)]),duration:8500}}
const frozen=()=>({kind:"cube",prompt:"色の位置を覚えて、最後の正面は？",help:"見えている3面を覚えてください。回転すると色が隠れます。",colors:structuredClone(COLORS),turns:["right","up"],answer:"ピンク",options:["あお","ピンク","むらさき","しろ"],duration:8500});
class ClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(v){this.values=new Set(String(v||"").split(/\s+/).filter(Boolean));this.sync()}sync(){this.owner._className=[...this.values].join(" ")}add(...v){v.forEach(x=>this.values.add(x));this.sync()}remove(...v){v.forEach(x=>this.values.delete(x));this.sync()}contains(v){return this.values.has(v)}toggle(v,force){const next=force===undefined?!this.values.has(v):Boolean(force);if(next)this.values.add(v);else this.values.delete(v);this.sync();return next}}
const noop=()=>{};class Gradient{addColorStop(){}}function context2d(){return new Proxy({globalAlpha:1,createRadialGradient:()=>new Gradient()},{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)})}
class Element extends EventTarget{constructor(tag,owner){super();this.tagName=tag.toUpperCase();this.ownerDocument=owner;this.children=[];this.parentElement=null;this.attributes=new Map();this.dataset={};this.style={};this._className="";this.classList=new ClassList(this);this.textContent="";this.tabIndex=-1;this.clientWidth=393;this.width=0;this.height=0;this.hidden=false;this.disabled=false;this.type="";this.ctx=this.tagName==="CANVAS"?context2d():null}set className(v){this._className=String(v);this.classList.reset(v)}get className(){return this._className}append(...nodes){for(const node of nodes){node.parentElement=this;this.children.push(node)}}replaceChildren(...nodes){this.children=[];this.append(...nodes)}setAttribute(k,v){this.attributes.set(k,String(v))}getAttribute(k){return this.attributes.get(k)??null}focus(){this.ownerDocument.activeElement=this}getContext(){return this.ctx}click(){if(!this.disabled)this.dispatchEvent(new Event("click",{bubbles:true,cancelable:true}))}getBoundingClientRect(){const width=Number.parseFloat(this.style.width)||this.clientWidth||393,height=Number.parseFloat(this.style.height)||224;return{left:0,top:0,width,height,right:width,bottom:height}}}
function documentFor(dpr=3){const view=new EventTarget();view.devicePixelRatio=dpr;const owner={defaultView:view,activeElement:null};owner.createElement=tag=>new Element(tag,owner);return owner}
function harness({reduced=false,viewport={width:393,height:852,dpr:3},owner=documentFor(viewport.dpr)}={}){const controller=new AbortController(),host=owner.createElement("div"),qa={},jobs=[],listeners=new Set(),finishes=[];host.clientWidth=viewport.width;let deadline=null,now=0,disposed=false,finishCalls=0;const dispose=()=>{if(disposed)return;disposed=true;controller.abort();jobs.forEach(job=>job.on=false);if(deadline)deadline.on=false;for(const item of listeners)item.target.removeEventListener(item.type,item.fn,item.options);listeners.clear()};const context={host,signal:controller.signal,reducedMotion:reduced,viewport,qa,finish(correct,result={}){finishCalls++;if(disposed||finishes.length)return false;finishes.push({correct:Boolean(correct),result});dispose();return true},later(fn,ms){const job={at:now+Math.max(0,Number(ms)||0),fn,on:true};jobs.push(job);return job},setDeadline(ms,fn){deadline={at:now+ms,fn,on:true};return deadline},frame(){throw Error("cube must not book frames")},listen(target,type,fn,options){target.addEventListener(type,fn,options);const item={target,type,fn,options};listeners.add(item);return()=>{target.removeEventListener(type,fn,options);listeners.delete(item)}}};const runTo=target=>{while(!disposed){const job=jobs.filter(x=>x.on&&x.at<=target).sort((a,b)=>a.at-b.at)[0];if(!job)break;now=job.at;job.on=false;job.fn()}now=target};const triggerDeadline=()=>{if(deadline?.on&&!disposed){deadline.on=false;deadline.fn();return true}return false};return{context,host,owner,qa,jobs,finishes,dispose,runTo,triggerDeadline,get now(){return now},get finishCalls(){return finishCalls}}}
function mount(options={}){const h=harness(options),task=options.task||frozen();game.render(task,h.context);const api=h.qa[ID],stage=h.host.children[1],scene=stage.children[0],turns=stage.children[1],status=stage.children[2],choices=stage.children[3];return Object.assign(h,{task,api,stage,scene,canvas:scene.children[0],turns,status,choices,buttons:choices.children})}

test("metadata preserves published stable identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.0",tier:2,flavor:"satisfying",step:1,family:"spatial-cube",category:"spatial"}));
test("10,000 generations exactly preserve archived factory random calls, objects, turns, answer, and options",()=>{const a=helpers(0xa8761a1),b=helpers(0xa8761a1),sequences=new Set();for(let i=0;i<10000;i++){const actual=game.generate(a),legacy=legacyGenerate(b);assert.deepEqual(actual,legacy,`generation ${i}`);assert.deepEqual(Object.keys(actual),["kind","prompt","help","colors","turns","answer","options","duration"]);assert.deepEqual(game.validate(actual),[]);assert.doesNotThrow(()=>structuredClone(actual));sequences.add(actual.turns.join(","))}assert.equal(sequences.size,10)});
test("all current authored sequences produce the exact face permutation answer",()=>{for(const turns of SEQUENCES){const task=frozen();task.turns=[...turns];task.answer=task.colors[faceAfter(turns)].name;if(!task.options.includes(task.answer))task.options[0]=task.answer;assert.deepEqual(game.validate(task),[],turns.join(","));assert.equal(task.answer,task.colors[faceAfter(turns)].name)}});
test("generator requires helpers and validator rejects color, turn, answer, option, copy, and timing mutations",()=>{assert.throws(()=>game.generate(),/shuffle/);assert.throws(()=>game.generate({shuffle:x=>[...x],pick:()=>["spin"]}),/supplied sequence/);const valid=frozen(),items=[null,{...valid,kind:"rotation"},{...valid,prompt:"changed"},{...valid,help:"changed"},{...valid,duration:1},structuredClone(valid),structuredClone(valid),{...valid,turns:["up","up"]},{...valid,answer:"あお"},{...valid,options:["ピンク","ピンク","あお","しろ"]}];items[5].colors[0].hex="#000";items[6].colors.pop();for(const item of items)assert.ok(game.validate(item).length)});
test("legacy factory is removed while current cube constants, permutation, and renderer timings remain pinned",()=>{assert.doesNotMatch(appSource,/\{id:"spatial-cube-v1",version:"1\.0",category:"spatial",make:/);for(const exact of["const CUBE_COLORS=[","const CUBE_TURN_SEQUENCES=[","function cubeFaceAfterTurns(turns)","},2400)","reducedMotion?320:700","reducedMotion?120:260"])assert.ok(appSource.includes(exact),exact)});
test("plain JSON fresh-module resume hides before turning and correct choice returns exact payload once",async()=>{const fresh=await importFresh(Date.now()),task=JSON.parse(JSON.stringify(frozen())),h=harness();fresh.render(task,h.context);const api=h.qa[ID];h.runTo(2400);assert.equal(api.inspect().masked,true);h.runTo(4060);assert.equal(api.inspect().choicesEnabled,true);api.choose(task.answer);assert.deepEqual(h.finishes,[{correct:true,result:{answerLabel:"ピンク"}}]);api.timeout();assert.equal(h.finishes.length,1)});
test("normal timing preserves 2400 encoding, 260 first delay, 700 turns, and delayed choice enable",()=>{const h=mount();h.runTo(2399);assert.equal(h.api.inspect().phase,"ENCODE");assert.equal(h.api.inspect().masked,false);h.runTo(2400);assert.equal(h.api.inspect().phase,"HIDDEN");assert.equal(h.turns.hidden,false);assert.ok(h.buttons.every(x=>x.disabled));h.runTo(2659);assert.equal(h.api.inspect().step,0);h.runTo(2660);assert.equal(h.api.inspect().step,1);h.runTo(3359);assert.equal(h.api.inspect().step,1);h.runTo(3360);assert.equal(h.api.inspect().step,2);assert.equal(h.api.inspect().choicesEnabled,false);h.runTo(4059);assert.equal(h.api.inspect().choicesEnabled,false);h.runTo(4060);assert.equal(h.api.inspect().choicesEnabled,true);assert.ok(h.buttons.every(x=>!x.disabled));assert.equal(h.owner.activeElement,h.buttons[0]);h.dispose()});
test("reduced timing uses deterministic nonzero 120/320 stages and no continuous frame",()=>{const h=mount({reduced:true});h.runTo(2400);assert.equal(h.api.inspect().masked,true);h.runTo(2519);assert.equal(h.api.inspect().stages,0);h.runTo(2520);assert.equal(h.api.inspect().stages,1);h.runTo(2840);assert.equal(h.api.inspect().stages,2);h.runTo(3160);assert.equal(h.api.inspect().choicesEnabled,true);assert.deepEqual(h.api.inspect().timing,{encodeMs:2400,firstDelay:120,turnDelay:320,duration:8500});h.dispose()});
test("mask happens before every turn and hidden stages never expose answer colors",()=>{const h=mount();h.runTo(2400);assert.equal(h.api.inspect().masked,true);const initialFaces=h.api.inspect().faces;h.runTo(2660);assert.equal(h.api.inspect().masked,true);assert.notDeepEqual(h.api.inspect().faces,initialFaces);assert.equal(h.canvas.getAttribute("aria-label").includes(h.task.answer),false);h.dispose()});
test("wrong and success choices preserve exact answerLabel result meaning and lock input",()=>{for(const correct of[false,true]){const h=mount();h.runTo(4060);const selected=correct?h.task.answer:h.task.options.find(x=>x!==h.task.answer),button=h.buttons.find(x=>x.textContent===selected);button.click();assert.deepEqual(h.finishes,[{correct,result:{answerLabel:h.task.answer}}]);assert.equal(h.api.inspect().result,correct?"success":"wrong");assert.ok(h.buttons.every(x=>x.disabled));h.buttons.find(x=>x.textContent===h.task.answer).click();assert.equal(h.finishes.length,1)}});
test("native choice buttons support touch click and keyboard activation with focus",()=>{const h=mount();h.runTo(4060);assert.equal(h.owner.activeElement,h.buttons[0]);const answer=h.buttons.find(x=>x.textContent===h.task.answer);answer.dispatchEvent(new Event("click",{bubbles:true,cancelable:true}));assert.equal(h.finishes[0].correct,true);const second=mount();second.runTo(4060);const wrong=second.buttons.find(x=>x.textContent!==second.task.answer);wrong.focus();const keyEvent=new Event("keydown",{bubbles:true,cancelable:true});Object.defineProperty(keyEvent,"key",{value:"Enter"});wrong.dispatchEvent(keyEvent);assert.equal(second.finishes[0].correct,false)});
test("deadline starts only after choices and returns exact generic timeout payload",()=>{const h=mount();assert.equal(h.triggerDeadline(),false);h.runTo(4059);assert.equal(h.triggerDeadline(),false);h.runTo(4060);assert.equal(h.triggerDeadline(),true);assert.deepEqual(h.finishes,[{correct:false,result:{detail:"時間切れです。脳は定時退社しました。",answerLabel:"ピンク"}}]);assert.equal(h.api.inspect().result,"timeout")});
test("393/402 DPR3 layouts expose all eight parity states with answer hidden until terminal",()=>{for(const reduced of[false,true])for(const viewport of[{width:393,height:852,dpr:3},{width:402,height:874,dpr:4}]){const h=mount({reduced,viewport}),canvas=h.api.inspect().canvas;assert.equal(canvas.dpr,3);assert.equal(canvas.pixelWidth,canvas.cssWidth*3);assert.equal(canvas.pixelHeight,canvas.cssHeight*3);for(const scene of["initial","turn1","turn2","final-hidden","choices","wrong","success","timeout"]){assert.equal(h.api.showScene(scene),true,scene);if(!["wrong","success","timeout"].includes(scene))assert.equal(h.api.inspect().detail.includes(h.task.answer),false)}h.dispose()}});
test("dispose during encoding or hidden turns cancels timers, listeners, QA, and finish",async()=>{const oldRaf=globalThis.requestAnimationFrame,oldCancel=globalThis.cancelAnimationFrame;globalThis.requestAnimationFrame=()=>{throw Error("unexpected frame")};globalThis.cancelAnimationFrame=()=>{};try{for(const at of[0,2500]){const owner=documentFor(),host=owner.createElement("div"),qa={},finishes=[],runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(frozen(),runtime.context);if(at)await delay(at);runtime.dispose();await delay(400);assert.deepEqual(finishes,[]);assert.equal(qa[ID],undefined);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}}finally{if(oldRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=oldRaf;if(oldCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=oldCancel}});
test("ownerDocument and source forbid raw lifetime, network, audio, asset, and answer-leak paths",()=>{const owner=documentFor(),old=globalThis.document;globalThis.document={createElement(){throw Error("global document used")}};try{const h=mount({owner});const visit=node=>{assert.equal(node.ownerDocument,owner);node.children.forEach(visit)};visit(h.host);h.dispose()}finally{if(old===undefined)delete globalThis.document;else globalThis.document=old}assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement)\b/);assert.doesNotMatch(source,/(?:\.src\s*=|url\s*\()/)});
