import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import game from "../src/games/spatial-flip-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";
const ID="spatial-flip-v1",source=await readFile(new URL("../src/games/spatial-flip-v1.js",import.meta.url),"utf8"),appSource=await readFile(new URL("../app.js",import.meta.url),"utf8"),ROWS=[["→","←"],["←","→"],["↗","↖"],["↘","↙"],["↖","↗"],["↙","↘"]],ARROWS=["→","←","↗","↖","↘","↙"];
const importFresh=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n// ${suffix}`).toString("base64")}`)).default;
function helpers(initial=0x71f11){let seed=initial>>>0;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32),randomInt=(min,max)=>min+Math.floor(random()*(max-min+1)),pick=values=>values[randomInt(0,values.length-1)],shuffle=values=>{const copy=[...values];for(let i=copy.length-1;i>0;i--){const j=randomInt(0,i);[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};return{pick,shuffle}}
function legacyGenerate(h){const r=h.pick(ROWS),pool=ARROWS.filter(value=>value!==r[0]&&value!==r[1]);return{kind:"rotation",prompt:"左右をひっくり返すと？",help:"鏡に映した形です。",symbol:r[0],options:h.shuffle([r[1],...h.shuffle(pool).slice(0,3)]),answer:r[1],duration:6500}}
const taskFor=(index=0)=>{const[symbol,answer]=ROWS[index],pool=ARROWS.filter(x=>x!==symbol&&x!==answer);return{kind:"rotation",prompt:"左右をひっくり返すと？",help:"鏡に映した形です。",symbol,options:[pool[1],answer,pool[2],pool[0]],answer,duration:6500}};
class ClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(v){this.values=new Set(String(v||"").split(/\s+/).filter(Boolean));this.sync()}sync(){this.owner._className=[...this.values].join(" ")}add(...v){v.forEach(x=>this.values.add(x));this.sync()}remove(...v){v.forEach(x=>this.values.delete(x));this.sync()}contains(v){return this.values.has(v)}toggle(v,force){const next=force===undefined?!this.values.has(v):Boolean(force);next?this.values.add(v):this.values.delete(v);this.sync();return next}}
const noop=()=>{};class Gradient{addColorStop(){}}function context2d(){return new Proxy({globalAlpha:1,createLinearGradient:()=>new Gradient()},{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)})}
class Element extends EventTarget{constructor(tag,owner){super();this.tagName=tag.toUpperCase();this.ownerDocument=owner;this.children=[];this.parentElement=null;this.attributes=new Map();this.dataset={};this.style={};this._className="";this.classList=new ClassList(this);this.textContent="";this.clientWidth=393;this.width=0;this.height=0;this.disabled=false;this.type="";this.ctx=this.tagName==="CANVAS"?context2d():null}set className(v){this._className=String(v);this.classList.reset(v)}get className(){return this._className}append(...nodes){for(const node of nodes){node.parentElement=this;this.children.push(node)}}replaceChildren(...nodes){this.children=[];this.append(...nodes)}setAttribute(k,v){this.attributes.set(k,String(v))}getAttribute(k){return this.attributes.get(k)??null}focus(){this.ownerDocument.activeElement=this}blur(){if(this.ownerDocument.activeElement===this)this.ownerDocument.activeElement=null}getContext(){return this.ctx}click(){if(!this.disabled)this.dispatchEvent(new Event("click",{bubbles:true,cancelable:true}))}getBoundingClientRect(){const width=Number.parseFloat(this.style.width)||this.clientWidth||393,height=Number.parseFloat(this.style.height)||198;return{left:0,top:0,width,height,right:width,bottom:height}}}
function documentFor(dpr=3){const view=new EventTarget();view.devicePixelRatio=dpr;const owner={defaultView:view,activeElement:null};owner.createElement=tag=>new Element(tag,owner);return owner}
function harness({reduced=false,viewport={width:393,height:852,dpr:3},owner=documentFor(viewport.dpr)}={}){const controller=new AbortController(),host=owner.createElement("div"),qa={},listeners=new Set(),finishes=[];host.clientWidth=viewport.width;let deadline=null,disposed=false,finishCalls=0;const dispose=()=>{if(disposed)return;disposed=true;controller.abort();if(deadline)deadline.on=false;for(const item of listeners)item.target.removeEventListener(item.type,item.fn,item.options);listeners.clear()};const context={host,qa,signal:controller.signal,reducedMotion:reduced,viewport,finish(correct,result={}){finishCalls++;if(disposed||finishes.length)return false;finishes.push({correct:Boolean(correct),result});dispose();return true},setDeadline(ms,fn){deadline={ms,fn,on:true};return deadline},listen(target,type,fn,options){target.addEventListener(type,fn,options);const item={target,type,fn,options};listeners.add(item);return()=>{target.removeEventListener(type,fn,options);listeners.delete(item)}},later(){throw Error("flip must not schedule non-deadline timers")},frame(){throw Error("flip must not book frames")}};const triggerDeadline=()=>{if(deadline?.on&&!disposed){deadline.on=false;deadline.fn();return true}return false};return{context,host,owner,qa,finishes,dispose,triggerDeadline,get finishCalls(){return finishCalls},get deadline(){return deadline}}}
function mount(options={}){const h=harness(options),task=options.task||taskFor();game.render(task,h.context);const api=h.qa[ID],stage=h.host.children[1],scene=stage.children[0],status=stage.children[1],choices=stage.children[2];return Object.assign(h,{task,api,stage,scene,canvas:scene.children[0],status,choices,buttons:choices.children})}

test("metadata preserves published stable identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.15",tier:1,flavor:"classic",step:1,family:"spatial-flip",category:"spatial"}));
test("10,000 generations exactly preserve current row pick, exclusions, nested shuffle, outer shuffle, and task shape",()=>{const a=helpers(0xa8761a1),b=helpers(0xa8761a1),seen=new Set();for(let i=0;i<10000;i++){const actual=game.generate(a),legacy=legacyGenerate(b);assert.deepEqual(actual,legacy,`generation ${i}`);assert.deepEqual(Object.keys(actual),["kind","prompt","help","symbol","options","answer","duration"]);assert.deepEqual(game.validate(actual),[]);assert.doesNotThrow(()=>structuredClone(actual));seen.add(`${actual.symbol}${actual.answer}`)}assert.equal(seen.size,6)});
test("all six exact pairs preserve source exclusion and answer identity",()=>{for(let index=0;index<ROWS.length;index++){const task=taskFor(index),[symbol,answer]=ROWS[index];assert.deepEqual(game.validate(task),[]);assert.equal(task.symbol,symbol);assert.equal(task.answer,answer);assert.equal(task.options.includes(symbol),false);assert.equal(task.options.includes(answer),true)}});
test("generator requires injected helpers and supplied rows",()=>{assert.throws(()=>game.generate(),/pick and shuffle/);assert.throws(()=>game.generate({pick:()=>["↑","↓"],shuffle:x=>[...x]}),/supplied row/)});
test("validator rejects copy, duration, symbol, answer, duplicate, source, and foreign option mutations",()=>{const valid=taskFor(),items=[null,{...valid,kind:"choice"},{...valid,prompt:"changed"},{...valid,help:"changed"},{...valid,duration:7000},{...valid,symbol:"↑"},{...valid,answer:"→"},{...valid,options:["←","←","↗","↖"]},{...valid,options:["←","→","↗","↖"]},{...valid,options:["←","↑","↗","↖"]}];for(const item of items)assert.ok(game.validate(item).length)});
test("source authority pins exact current factory and generic rotation renderer branch",()=>{for(const exact of['const rows=[["→","←"],["←","→"],["↗","↖"],["↘","↙"],["↖","↗"],["↙","↘"]],r=pick(rows)','const pool=["→","←","↗","↖","↘","↙"].filter(value=>value!==r[0]&&value!==r[1])','options:shuffle([r[1],...shuffle(pool).slice(0,3)])','if(task.kind==="rotation")','visual.className="big-symbol"','makeChoices(task,{symbol:true});startDeadline(task.duration,()=>genericTimeout(task))'])assert.ok(appSource.includes(exact),exact)});
test("plain JSON fresh-module resume shows exact symbol/options and succeeds immediately with exact payload",async()=>{const fresh=await importFresh(Date.now()),task=JSON.parse(JSON.stringify(taskFor(2))),h=harness();fresh.render(task,h.context);const api=h.qa[ID],before=api.inspect();assert.equal(before.source,"↗");assert.deepEqual(before.buttons.map(x=>x.text),task.options);assert.equal(before.choicesEnabled,true);api.choose(task.answer);assert.deepEqual(h.finishes,[{correct:true,result:{answerLabel:"↖"}}]);assert.equal(api.inspect().feedbackStages,1)});
test("wrong and success preserve exact answerLabel, retained feedback, lock, and single finish",()=>{for(const correct of[false,true]){const h=mount(),selected=correct?h.task.answer:h.task.options.find(x=>x!==h.task.answer);h.api.choose(selected);assert.deepEqual(h.finishes,[{correct,result:{answerLabel:h.task.answer}}]);const state=h.api.inspect();assert.equal(state.result,correct?"success":"wrong");assert.equal(state.selected,selected);assert.equal(state.choicesEnabled,false);assert.equal(state.feedbackStages,1);assert.ok(h.buttons.every(x=>x.disabled));h.api.choose(h.task.answer);assert.equal(h.finishes.length,1)}});
test("real button click and explicit Enter/Space activation share focus and exact choice behavior",()=>{for(const key of["Enter"," "]){const h=mount(),answer=h.buttons.find(x=>x.textContent===h.task.answer);answer.focus();const event=new Event("keydown",{bubbles:true,cancelable:true});Object.defineProperty(event,"key",{value:key});answer.dispatchEvent(event);assert.equal(event.defaultPrevented,true);assert.deepEqual(h.finishes,[{correct:true,result:{answerLabel:h.task.answer}}])}const click=mount();click.buttons.find(x=>x.textContent!==click.task.answer).click();assert.equal(click.finishes[0].correct,false)});
test("6500ms deadline begins at render and returns exact generic timeout payload",()=>{const h=mount();assert.equal(h.deadline.ms,6500);assert.equal(h.triggerDeadline(),true);assert.deepEqual(h.finishes,[{correct:false,result:{detail:"時間切れです。脳は定時退社しました。",answerLabel:"←"}}]);assert.equal(h.api.inspect().result,"timeout");assert.equal(h.api.inspect().feedbackStages,1);assert.equal(h.triggerDeadline(),false)});
test("normal and reduced retain nonzero terminal feedback with zero continuous frames",()=>{for(const reduced of[false,true]){const h=mount({reduced});h.api.choose(h.task.answer);const state=h.api.inspect();assert.equal(state.reduced,reduced);assert.equal(state.feedbackStages,1);assert.equal(state.frames,0)}});
test("393/402 DPR3 layouts expose five scenes for every pair without pre-answer reveal",()=>{for(let pair=0;pair<6;pair++)for(const reduced of[false,true])for(const viewport of[{width:393,height:852,dpr:3},{width:402,height:874,dpr:4}]){const h=mount({task:taskFor(pair),reduced,viewport}),canvas=h.api.inspect().canvas;assert.equal(canvas.dpr,3);assert.equal(canvas.pixelWidth,canvas.cssWidth*3);assert.equal(canvas.pixelHeight,canvas.cssHeight*3);assert.equal(h.canvas.getAttribute("aria-label").includes(h.task.answer),false);for(const scene of["initial","focus","wrong","success","timeout"]){assert.equal(h.api.showScene(scene),true);const state=h.api.inspect();if(scene==="initial"||scene==="focus"){assert.equal(state.done,false);assert.equal(state.status.includes(h.task.answer),false)}}h.dispose()}});
test("real runtime disposal cancels deadline/listeners/QA without finish",async()=>{const owner=documentFor(),host=owner.createElement("div"),qa={},finishes=[],oldRaf=globalThis.requestAnimationFrame,oldCancel=globalThis.cancelAnimationFrame;globalThis.requestAnimationFrame=()=>{throw Error("unexpected frame")};globalThis.cancelAnimationFrame=()=>{};try{const runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(taskFor(),runtime.context);runtime.dispose();await delay(80);assert.deepEqual(finishes,[]);assert.equal(qa[ID],undefined);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(oldRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=oldRaf;if(oldCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=oldCancel}});
test("ownerDocument and source forbid raw lifetime, network, audio, asset, and answer-preview paths",()=>{const owner=documentFor(),old=globalThis.document;globalThis.document={createElement(){throw Error("global document used")}};try{const h=mount({owner});const visit=node=>{assert.equal(node.ownerDocument,owner);node.children.forEach(visit)};visit(h.host);h.dispose()}finally{if(old===undefined)delete globalThis.document;else globalThis.document=old}assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement)\b/);assert.doesNotMatch(source,/(?:\.src\s*=|url\s*\()/)});
