import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";

const moduleUrl=new URL("../src/games/spatial-screen-protector-v1.js",import.meta.url),moduleSource=await readFile(moduleUrl,"utf8");
const importGame=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${moduleSource}\n// ${suffix}`).toString("base64")}`)).default;
const game=await importGame("primary"),ID="spatial-screen-protector-v1";
function randomHelpers(initialSeed=0x5c12f17){let seed=initialSeed>>>0;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32),randomInt=(min,max)=>min+Math.floor(random()*(max-min+1));return{random,randomInt,pick:values=>values[randomInt(0,values.length-1)],shuffle:values=>[...values]}}
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}toggle(value,force){const add=force===undefined?!this.values.has(value):force;add?this.values.add(value):this.values.delete(value);this.sync();return add}sync(){this.owner._className=[...this.values].join(" ")}}
class FakeStyle{constructor(){this.values=new Map()}setProperty(name,value){this.values.set(name,String(value))}}
const noop=()=>{};function fakeCanvasContext(){const gradient={addColorStop:noop};return new Proxy({createLinearGradient:()=>gradient,createRadialGradient:()=>gradient},{get(target,key){return key in target?target[key]:noop},set(target,key,value){target[key]=value;return true}})}
class FakeElement extends EventTarget{constructor(tagName,ownerDocument){super();this.tagName=tagName.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.attributes=new Map();this.dataset={};this.style=new FakeStyle();this.classList=new FakeClassList(this);this._className="";this.textContent="";this.type="";this.disabled=false;this.width=0;this.height=0;this.tabIndex=-1}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this.children=[...nodes]}setAttribute(name,value){this.attributes.set(name,String(value))}getAttribute(name){return this.attributes.get(name)??null}focus(){this.ownerDocument.activeElement=this}getContext(kind){return this.tagName==="CANVAS"&&kind==="2d"?fakeCanvasContext():null}getBoundingClientRect(){const width=Number.parseFloat(this.style.width)||390,height=Number.parseFloat(this.style.height)||530;return{left:0,top:0,width,height,right:width,bottom:height}}setPointerCapture(){} }
function createFakeDocument(name="document"){const view=new EventTarget();view.devicePixelRatio=3;const documentRef={name,activeElement:null,defaultView:view};documentRef.createElement=tag=>new FakeElement(tag,documentRef);return documentRef}
function installFakeDocument(){const previous=globalThis.document;globalThis.document=createFakeDocument("global");return()=>{if(previous===undefined)delete globalThis.document;else globalThis.document=previous}}
function createHarness({reducedMotion=false,viewport={width:390,height:844,dpr:2},ownerDocument=globalThis.document}={}){const controller=new AbortController(),host=ownerDocument.createElement("div"),qa={},pending=[],listeners=new Set(),finishes=[];let deadline=null,disposed=false,frameCalls=0;host.getBoundingClientRect=()=>({left:0,top:0,width:viewport.width-16,height:viewport.height});const context={host,signal:controller.signal,reducedMotion,viewport,qa,finish(correct,result){if(disposed||finishes.length)return false;finishes.push({correct,result});return true},setDeadline(ms,fn){deadline={ms,fn,active:true};return deadline},later(fn,ms){const job={fn,ms,active:true};pending.push(job);return job},frame(){frameCalls++;return()=>{}},listen(target,type,fn,options){target.addEventListener(type,fn,options);const record={target,type,fn,options};listeners.add(record);return()=>{target.removeEventListener(type,fn,options);listeners.delete(record)}}};const runNext=()=>{const job=pending.find(entry=>entry.active);if(job&&!disposed){job.active=false;job.fn()}return job};const runAll=()=>{let guard=0;while(pending.some(job=>job.active)&&guard++<100){const jobs=pending.splice(0);jobs.forEach(job=>{if(job.active&&!disposed){job.active=false;job.fn()}})}};const triggerDeadline=()=>{if(deadline?.active&&!disposed){deadline.active=false;deadline.fn()}};const dispose=()=>{if(disposed)return;controller.abort();disposed=true;pending.forEach(job=>job.active=false);if(deadline)deadline.active=false;listeners.forEach(({target,type,fn,options})=>target.removeEventListener(type,fn,options));listeners.clear()};return{context,host,qa,finishes,runNext,runAll,triggerDeadline,dispose,get pendingCount(){return pending.filter(job=>job.active).length},get listenerCount(){return listeners.size},get frameCalls(){return frameCalls}}}
const eventWith=(type,properties={})=>{const event=new Event(type,{bubbles:true,cancelable:true});Object.entries(properties).forEach(([key,value])=>Object.defineProperty(event,key,{value}));return event};
const stage=host=>host.children[1],board=host=>stage(host).children[1],laneButtons=host=>stage(host).children[2].children,actionButtons=host=>stage(host).children[3].children;
const settle=(api,harness,lane)=>{assert.equal(api.seal(lane),true);assert.equal(api.inspect().busy,true);harness.runAll();return api.inspect()};

test("metadata and module interface publish the requested stable identity",()=>{assert.deepEqual(game.metadata,{id:ID,introducedIn:"2.0",tier:3,flavor:"satisfying",step:1,family:"spatial-screen-protector",category:"spatial"});assert.equal(typeof game.generate,"function");assert.equal(typeof game.validate,"function");assert.equal(typeof game.render,"function")});
test("generation stays within three finite authored cloneable layouts",()=>{const helpers=randomHelpers(),seen=new Set();for(let index=0;index<300;index++){const task=game.generate(helpers);seen.add(task.layout);assert.deepEqual(game.validate(task),[]);assert.doesNotThrow(()=>structuredClone(task));assert.equal(task.bubbles.length,5);assert.deepEqual(task.bubbles.map(bubble=>bubble.band),[1,2,3,4,5])}assert.deepEqual([...seen].sort(),["aurora-fold","prism-fan","silver-zig"])});
test("every authored proof exhausts 3^5 pressure paths with one causal solution",()=>{for(let index=0;index<3;index++){const task=game.generate({randomInt:()=>index});assert.deepEqual(task.proof,{totalPaths:243,successPaths:1,trappedPaths:242,canonical:task.solution,recovery:{mistakeBand:task.proof.recovery.mistakeBand,wrongLane:"left",peelBands:1,resealLane:task.solution[task.proof.recovery.mistakeBand-1],finishesAfterReseal:true}});task.bubbles.forEach((bubble,band)=>{const expected=bubble.exit==="right"?"left":bubble.exit==="left"?"right":"center";assert.equal(task.solution[band],expected)})}});
test("validator rejects forged proof, geometry, escape edges, peel bounds, and unknown layouts",()=>{const base=game.generate({randomInt:()=>0});for(const mutate of[task=>task.proof.successPaths++,task=>task.bubbles[0].x=.5,task=>task.bubbles[1].exit="top",task=>task.maxPeel=2,task=>task.layout="procedural",task=>task.solution[0]="right"]){const task=structuredClone(base);mutate(task);assert.notDeepEqual(game.validate(task),[])}});
test("plain JSON save revalidates and resumes to the same causal solution after fresh import",async()=>{const restore=installFakeDocument();try{const saved=JSON.parse(JSON.stringify(game.generate({randomInt:()=>1}))),fresh=await importGame(`fresh-${Date.now()}`),harness=createHarness({reducedMotion:true});assert.deepEqual(fresh.validate(saved),[]);fresh.render(saved,harness.context);const api=harness.qa[ID];for(const lane of saved.solution){api.seal(lane);harness.runAll()}harness.runAll();assert.deepEqual(harness.finishes.map(entry=>[entry.correct,entry.result.outcome]),[[true,"success"]])}finally{restore()}});
test("canonical pressure vectors deform and migrate every bubble to a real edge before success",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:()=>0}),harness=createHarness(),api=(game.render(task,harness.context),harness.qa[ID]);task.solution.forEach((lane,index)=>{const before=api.inspect().bubbles[index];assert.equal(before.escaped,false);api.seal(lane);assert.equal(api.inspect().animation.correct,true);assert.equal(api.inspect().front,index);harness.runAll();const after=api.inspect().bubbles[index];assert.equal(after.escaped,true);assert.ok(after.x<0||after.x>1||after.y<0)});harness.runAll();assert.deepEqual(harness.finishes.map(entry=>[entry.correct,entry.result.outcome]),[[true,"success"]]);assert.equal(api.inspect().remaining,0);harness.triggerDeadline();assert.equal(harness.finishes.length,1)}finally{restore()}});
test("wrong pressure traps a deformed bubble, one peel restores it, and resealing recovers",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:()=>0}),harness=createHarness({reducedMotion:true});game.render(task,harness.context);const api=harness.qa[ID];settle(api,harness,task.solution[0]);const wrong=task.proof.recovery.wrongLane;settle(api,harness,wrong);assert.equal(api.inspect().outcome,"trapped");assert.equal(api.inspect().trapped,1);assert.ok(api.inspect().bubbles[1].rx>api.inspect().bubbles[1].radius);assert.equal(api.peel(),true);harness.runAll();assert.equal(api.inspect().front,1);assert.equal(api.inspect().trapped,0);assert.equal(api.inspect().bubbles[1].escaped,false);for(let index=1;index<5;index++)settle(api,harness,task.solution[index]);harness.runAll();assert.deepEqual(harness.finishes.map(entry=>entry.correct),[true]);assert.equal(harness.finishes[0].result.tension,1)}finally{restore()}});
test("sealing an unescaped bubble to the top produces the distinct trapped terminal",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:()=>1}),harness=createHarness();game.render(task,harness.context);const api=harness.qa[ID];const wrong=task.solution[0]==="left"?"right":"left";settle(api,harness,wrong);for(let index=1;index<5;index++)settle(api,harness,task.solution[index]);harness.runAll();assert.deepEqual(harness.finishes.map(entry=>[entry.correct,entry.result.outcome]),[[false,"trapped"]]);assert.ok(api.inspect().remaining>0);assert.equal(board(harness.host).classList.contains("ssp-trapped"),true)}finally{restore()}});
test("a second peel exceeds bounded tension and produces overpeel rather than a free reset",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:()=>2}),harness=createHarness();game.render(task,harness.context);const api=harness.qa[ID];settle(api,harness,task.solution[0]);api.peel();harness.runAll();settle(api,harness,task.solution[0]);assert.equal(api.peel(),true);assert.equal(api.inspect().busy,true);harness.runAll();assert.deepEqual(harness.finishes.map(entry=>[entry.correct,entry.result.outcome]),[[false,"overpeel"]]);assert.equal(api.inspect().totalPeel,2);assert.equal(board(harness.host).classList.contains("ssp-overpeel"),true)}finally{restore()}});
test("tap alone cannot remove bubbles or advance, and an upper start is invalid",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:()=>0}),harness=createHarness({reducedMotion:true});game.render(task,harness.context);const api=harness.qa[ID],surface=board(harness.host),before=api.inspect();surface.dispatchEvent(eventWith("pointerdown",{pointerId:4,clientX:190,clientY:500}));surface.dispatchEvent(eventWith("pointerup",{pointerId:4,clientX:190,clientY:500}));assert.equal(api.inspect().front,before.front);assert.equal(api.inspect().remaining,before.remaining);surface.dispatchEvent(eventWith("pointerdown",{pointerId:5,clientX:190,clientY:120}));assert.equal(api.inspect().outcome,"invalid");assert.equal(api.inspect().invalidCount,1);harness.runAll();assert.equal(api.inspect().outcome,"active");assert.equal(api.peel(),false);assert.equal(api.inspect().invalidCount,2)}finally{restore()}});
test("a captured touch path advances bands using the pressure lane at each crossing",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:()=>0}),harness=createHarness({reducedMotion:true});game.render(task,harness.context);const api=harness.qa[ID],surface=board(harness.host),pointerId=9;surface.dispatchEvent(eventWith("pointerdown",{pointerId,clientX:78,clientY:500}));assert.equal(api.inspect().dragging,true);surface.dispatchEvent(eventWith("pointermove",{pointerId,clientX:78,clientY:390}));assert.equal(api.inspect().busy,true);harness.runAll();assert.equal(api.inspect().front,1);assert.equal(api.inspect().bubbles[0].escaped,true);surface.dispatchEvent(eventWith("pointermove",{pointerId,clientX:312,clientY:318}));harness.runAll();assert.equal(api.inspect().front,2);assert.equal(api.inspect().lane,"right");assert.equal(api.inspect().bubbles[1].escaped,true);surface.dispatchEvent(eventWith("pointerup",{pointerId,clientX:312,clientY:318}));assert.equal(api.inspect().dragging,false)}finally{restore()}});
test("keyboard and controls select pressure, seal, peel, focus, and retain DPR3",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:()=>0}),harness=createHarness({reducedMotion:true,viewport:{width:402,height:874,dpr:3}});game.render(task,harness.context);const api=harness.qa[ID],surface=board(harness.host),lanes=laneButtons(harness.host),actions=actionButtons(harness.host);assert.equal(document.activeElement,surface);surface.dispatchEvent(eventWith("keydown",{key:"ArrowLeft"}));assert.equal(api.inspect().lane,"left");assert.equal(lanes[0].getAttribute("aria-pressed"),"true");surface.dispatchEvent(eventWith("keydown",{key:"ArrowUp"}));harness.runAll();assert.equal(api.inspect().front,1);surface.dispatchEvent(eventWith("keydown",{key:"ArrowDown"}));harness.runAll();assert.equal(api.inspect().front,0);lanes[1].dispatchEvent(eventWith("click",{detail:0}));assert.equal(api.inspect().lane,"center");actions[0].dispatchEvent(eventWith("click",{detail:0}));assert.equal(api.inspect().busy,true);const canvas=api.inspect().canvas;assert.equal(canvas.dpr,3);assert.equal(canvas.width,canvas.cssWidth*3);assert.equal(harness.frameCalls,0);assert.match(api.inspect().aria,/残り気泡/)}finally{restore()}});
test("reduced motion uses nonzero tracked deformation stages and no continuous frame",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:()=>0}),harness=createHarness({reducedMotion:true});game.render(task,harness.context);const api=harness.qa[ID];api.seal(task.solution[0]);assert.equal(harness.frameCalls,0);assert.equal(harness.pendingCount,2);assert.equal(api.inspect().animation.progress,.08);harness.runNext();assert.equal(api.inspect().animation.progress,.52);assert.equal(api.inspect().front,0);harness.runAll();assert.equal(api.inspect().front,1);assert.equal(api.inspect().busy,false)}finally{restore()}});
test("deadline preserves causal progress and reports the distinct timeout once",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:()=>0}),harness=createHarness();game.render(task,harness.context);const api=harness.qa[ID];settle(api,harness,task.solution[0]);const before=api.inspect();harness.triggerDeadline();harness.runAll();assert.deepEqual(harness.finishes.map(entry=>[entry.correct,entry.result.outcome]),[[false,"timeout"]]);assert.equal(harness.finishes[0].result.front,before.front);assert.equal(harness.finishes[0].result.remaining,before.remaining);assert.equal(board(harness.host).classList.contains("ssp-timeout"),true);harness.triggerDeadline();assert.equal(harness.finishes.length,1)}finally{restore()}});
test("render creates nodes from host.ownerDocument and normal motion owns exactly one frame",()=>{const previous=globalThis.document,foreign=createFakeDocument("iframe");globalThis.document={createElement(){throw Error("global document used")}};try{const harness=createHarness({ownerDocument:foreign}),task=game.generate({randomInt:()=>0});game.render(task,harness.context);const visit=node=>{assert.equal(node.ownerDocument,foreign);node.children.forEach(visit)};visit(harness.host);assert.equal(harness.frameCalls,1);harness.dispose()}finally{if(previous===undefined)delete globalThis.document;else globalThis.document=previous}});
test("dispose removes QA, listeners, deadline, stages, and prevents a late finish",()=>{const restore=installFakeDocument();try{const task=game.generate({randomInt:()=>0}),harness=createHarness();game.render(task,harness.context);harness.qa[ID].seal(task.solution[0]);assert.ok(harness.pendingCount>0);harness.dispose();harness.runAll();harness.triggerDeadline();assert.equal(harness.qa[ID],undefined);assert.equal(harness.listenerCount,0);assert.equal(harness.pendingCount,0);assert.deepEqual(harness.finishes,[])}finally{restore()}});
test("real runtime disposal cancels stages, frame, deadline, and module QA",async()=>{const restore=installFakeDocument(),previousRaf=globalThis.requestAnimationFrame,previousCancel=globalThis.cancelAnimationFrame;globalThis.requestAnimationFrame=callback=>setTimeout(()=>callback(performance.now()),0);globalThis.cancelAnimationFrame=id=>clearTimeout(id);try{const task=game.generate({randomInt:()=>0}),qa={},finishes=[],host=document.createElement("div");host.getBoundingClientRect=()=>({width:393,height:852});const runtime=createGameRuntime({host,qa,reducedMotion:false,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(task,runtime.context);qa[ID].seal(task.solution[0]);assert.ok(runtime.inspect().timeouts>=3);runtime.dispose();await delay(280);assert.equal(qa[ID],undefined);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{restore();if(previousRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=previousRaf;if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}});
test("source uses tracked ownership and contains no network, audio, emoji, or raw timer path",()=>{assert.match(moduleSource,/context\.host\?\.ownerDocument/);assert.doesNotMatch(moduleSource,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(moduleSource,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(moduleSource,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement)\b/);assert.doesNotMatch(moduleSource,/[\u{1F300}-\u{1FAFF}]/u)});
