import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import game from "../src/games/spatial-emoji-fps-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";
const ID="spatial-emoji-fps-v1",MULTISET=["🤓","😀","🐶","🤓","🤑","🐱","🐼","🤓"],POSITIONS=[[21,25,-30,.9],[49,22,20,1.05],[76,28,-10,.95],[29,50,35,1.13],[67,52,5,1],[20,69,-20,.88],[49,72,45,1.16],[78,67,-5,.94]],source=await readFile(new URL("../src/games/spatial-emoji-fps-v1.js",import.meta.url),"utf8"),legacy=await readFile(new URL("../app.js",import.meta.url),"utf8");
const fixed=()=>({kind:"emojiFps",prompt:"🤓だけを3体ロックオン",help:"😀・🤑・動物は押さないで。",targets:[...MULTISET],duration:8000});
class ClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean));this.sync()}sync(){this.owner._className=[...this.values].join(" ")}add(...items){items.forEach(item=>this.values.add(item));this.sync()}remove(...items){items.forEach(item=>this.values.delete(item));this.sync()}contains(item){return this.values.has(item)}toggle(item,force){const add=force===undefined?!this.values.has(item):force;add?this.values.add(item):this.values.delete(item);this.sync();return add}}
class Style{constructor(){this.values=new Map()}setProperty(key,value){this.values.set(key,String(value))}getPropertyValue(key){return this.values.get(key)||""}}
class Element extends EventTarget{constructor(tag,ownerDocument){super();this.tagName=tag.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.parentElement=null;this.attributes=new Map();this.dataset={};this.style=new Style();this.classList=new ClassList(this);this._className="";this.textContent="";this.type="";this.disabled=false;this.hidden=false;this.tabIndex=-1;this.id=""}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}append(...nodes){nodes.forEach(node=>{node.parentElement=this;this.children.push(node)})}replaceChildren(...nodes){this.children=[];this.append(...nodes)}setAttribute(key,value){this.attributes.set(key,String(value))}getAttribute(key){return this.attributes.get(key)??null}focus(){this.ownerDocument.activeElement=this}getBoundingClientRect(){return{left:0,top:0,width:393,height:224,right:393,bottom:224}}}
function documentFor({dpr=3,now=0}={}){const view=new EventTarget();view.devicePixelRatio=dpr;let clock=now;view.performance={now:()=>clock};const owner={activeElement:null,defaultView:view,setTime:value=>{clock=value}};owner.createElement=tag=>new Element(tag,owner);return owner}
function event(type,properties={}){const value=new Event(type,{bubbles:true,cancelable:true});Object.entries(properties).forEach(([key,item])=>Object.defineProperty(value,key,{value:item}));return value}
function harness({reduced=true,viewport={width:393,height:852,dpr:3},owner=documentFor({dpr:viewport.dpr})}={}){const controller=new AbortController(),host=owner.createElement("div"),qa={},jobs=[],listeners=new Set(),finishes=[];let deadline=null,frame=null,time=0,disposed=false;host.getBoundingClientRect=()=>({left:0,top:0,width:viewport.width,height:viewport.height,right:viewport.width,bottom:viewport.height});const dispose=()=>{if(disposed)return;controller.abort();disposed=true;jobs.forEach(job=>job.active=false);if(deadline)deadline.active=false;frame=null;listeners.forEach(item=>item.target.removeEventListener(item.type,item.fn,item.options));listeners.clear()};const context={host,signal:controller.signal,reducedMotion:reduced,viewport,qa,finish(correct,result){if(disposed||finishes.length)return false;finishes.push({correct,result});return true},later(fn,ms){const job={fn,at:time+ms,active:true};jobs.push(job);return job},setDeadline(ms,fn){deadline={fn,at:time+ms,active:true};return deadline},frame(fn){frame=fn;return()=>{frame=null}},listen(target,type,fn,options){target.addEventListener(type,fn,options);const item={target,type,fn,options};listeners.add(item);return()=>{target.removeEventListener(type,fn,options);listeners.delete(item)}}};const runNext=()=>{const job=jobs.filter(value=>value.active).sort((a,b)=>a.at-b.at)[0];if(!job)return false;time=job.at;job.active=false;job.fn();return true},runAll=()=>{let guard=0;while(runNext()&&guard++<100);assert.ok(guard<100)},step=at=>{time=at;if(frame&&frame(at)===false)frame=null},timeout=()=>{if(deadline?.active&&!disposed){deadline.active=false;deadline.fn()}};return{context,host,owner,qa,finishes,dispose,runNext,runAll,step,timeout,get pending(){return jobs.filter(value=>value.active).length},get frame(){return Boolean(frame)},get listeners(){return listeners.size}}}
const parts=h=>{const stage=h.host.children[1],arena=stage.children[1],world=arena.children[0];return{stage,status:stage.children[0],arena,world,targets:world.children.slice(5),counter:world.children[3],terminal:world.children[4]}};
const settle=(h,index)=>{assert.equal(h.qa[ID].select(index),true);assert.equal(h.qa[ID].completeTransition(),true)};

test("metadata preserves the published stable identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.0",tier:3,flavor:"wild",step:1,family:"spatial-emoji-fps",category:"spatial"}));
test("current app legacy source retains the exact generator, renderer positions, and details",()=>{assert.match(legacy,/kind:"emojiFps",prompt:"🤓だけを3体ロックオン",help:"😀・🤑・動物は押さないで。",targets:shuffle\(\["🤓","😀","🐶","🤓","🤑","🐱","🐼","🤓"\]\),duration:8000/);assert.match(legacy,/positions=\[\[21,25,-30,\.9\],\[49,22,20,1\.05\],\[76,28,-10,\.95\],\[29,50,35,1\.13\],\[67,52,5,1\],\[20,69,-20,\.88\],\[49,72,45,1\.16\],\[78,67,-5,\.94\]\]/);assert.match(legacy,/\$\{emoji\}は一般通行人でした。/);assert.match(legacy,/🤓を全員ロックオンしました。/);assert.match(legacy,/🤓が3D通路へ消えました。/)});
test("5000 generations clone, validate, and preserve only shuffled published multisets",()=>{const orders=new Set(),started=performance.now();for(let index=0;index<5000;index++){const shift=index%8,task=game.generate({shuffle:values=>values.slice(shift).concat(values.slice(0,shift))});assert.doesNotThrow(()=>structuredClone(task));assert.deepEqual(game.validate(task),[]);assert.deepEqual(Object.keys(task),["kind","prompt","help","targets","duration"]);assert.deepEqual([...task.targets].sort(),[...MULTISET].sort());orders.add(task.targets.join("|"))}assert.ok(orders.size>=6);assert.ok(performance.now()-started<2500)});
test("generation is bounded and falls back exactly under hostile shuffle output",()=>{for(const output of [null,[],["🤓"],Array(8).fill("🤓"),"bad"]){const task=game.generate({shuffle:()=>output});assert.deepEqual(task,fixed());assert.deepEqual(game.validate(task),[])}assert.throws(()=>game.generate({}),/shuffle/)});
test("validator rejects kind, copy, duration, multiset, order shape, and additive fields",()=>{const task=fixed(),cases=[{...task,kind:"choice"},{...task,prompt:"別"},{...task,help:"別"},{...task,duration:7999},{...task,targets:task.targets.slice(1)},{...task,targets:task.targets.map((value,index)=>index===0?"😀":value)},{...task,extra:true}];for(const [index,value] of cases.entries())assert.ok(game.validate(value).length,`case ${index}`);assert.doesNotThrow(()=>game.validate({}));assert.ok(game.validate(null).length)});
test("render creates all nodes through ownerDocument and maps exact index geometry",()=>{const owner=documentFor(),h=harness({owner}),previous=globalThis.document;globalThis.document={createElement(){throw new Error("global document used")}};try{game.render(fixed(),h.context);const {arena,targets}=parts(h);assert.equal(arena.ownerDocument,owner);assert.equal(targets.length,8);targets.forEach((button,index)=>{assert.equal(button.textContent,MULTISET[index]);assert.equal(button.style.getPropertyValue("--entity-x"),`${POSITIONS[index][0]}%`);assert.equal(button.style.getPropertyValue("--entity-y"),`${POSITIONS[index][1]}%`);assert.equal(button.style.getPropertyValue("--entity-z"),`${POSITIONS[index][2]}px`);assert.equal(button.style.getPropertyValue("--entity-scale"),String(POSITIONS[index][3]));assert.equal(button.style.getPropertyValue("--float-delay"),`${index*-.18}s`);assert.match(button.getAttribute("aria-label"),new RegExp(`^${index+1}番`))});assert.deepEqual(h.qa[ID].inspect().targets.map(value=>value.position),POSITIONS)}finally{h.dispose();if(previous===undefined)delete globalThis.document;else globalThis.document=previous}});
test("plain saved task locks exactly indices 0, 3, 7 and succeeds once",()=>{const task=JSON.parse(JSON.stringify(fixed())),h=harness();game.render(task,h.context);settle(h,0);assert.equal(h.qa[ID].inspect().hits,1);assert.deepEqual(h.qa[ID].inspect().removed,[0]);settle(h,3);assert.equal(h.qa[ID].inspect().counter,"LOCK 2 / 3");settle(h,7);const state=h.qa[ID].inspect();assert.equal(state.result,"success");assert.deepEqual(state.removed,[0,3,7]);assert.deepEqual(h.finishes.map(value=>value.correct),[true]);assert.equal(h.finishes[0].result.detail,"🤓を全員ロックオンしました。");assert.ok(h.finishes[0].result.quality>=0&&h.finishes[0].result.quality<=1);h.timeout();assert.equal(h.finishes.length,1);h.dispose()});
test("LOCK 1 and LOCK 2 stages remove one stable identity and lock repeat input",()=>{const h=harness();game.render(fixed(),h.context);assert.equal(h.qa[ID].select(0),true);assert.equal(h.qa[ID].inspect().busy,true);assert.equal(h.qa[ID].select(3),false);assert.equal(h.qa[ID].inspect().hits,0);h.qa[ID].completeTransition();let state=h.qa[ID].inspect();assert.equal(state.hits,1);assert.deepEqual(state.active.map((value,index)=>value?null:index).filter(value=>value!==null),[0]);assert.equal(h.qa[ID].select(0),false);settle(h,3);state=h.qa[ID].inspect();assert.equal(state.hits,2);assert.deepEqual(state.removed,[0,3]);assert.equal(state.done,false);h.dispose()});
test("every published distractor fails immediately with exact bystander detail",()=>{for(const index of [1,2,4,5,6]){const h=harness();game.render(fixed(),h.context);const emoji=MULTISET[index];assert.equal(h.qa[ID].select(index),true);assert.equal(h.qa[ID].inspect().result,"bystander");assert.equal(h.qa[ID].inspect().failedIndex,index);assert.deepEqual(h.finishes,[{correct:false,result:{detail:`${emoji}は一般通行人でした。`}}]);h.timeout();assert.equal(h.finishes.length,1);h.dispose()}});
test("timeout preserves unresolved targets and exact published detail once",()=>{const h=harness();game.render(fixed(),h.context);settle(h,0);const active=[...h.qa[ID].inspect().active];h.timeout();const state=h.qa[ID].inspect();assert.equal(state.result,"timeout");assert.deepEqual(state.active,active);assert.deepEqual(h.finishes,[{correct:false,result:{detail:"🤓が3D通路へ消えました。"}}]);h.timeout();assert.equal(h.finishes.length,1);h.dispose()});
test("success quality remains exact elapsed-over-8000 legacy semantics",()=>{const owner=documentFor({now:1000}),h=harness({owner});game.render(fixed(),h.context);settle(h,0);settle(h,3);owner.setTime(5000);settle(h,7);assert.equal(h.finishes[0].result.quality,.5);h.dispose()});
test("normal acquisition owns a finite tracked frame while reduced exposes three nonzero stages",()=>{const normal=harness({reduced:false});game.render(fixed(),normal.context);assert.equal(normal.frame,false);normal.qa[ID].select(0);assert.equal(normal.frame,true);normal.step(0);assert.equal(normal.qa[ID].inspect().locking.progress,0);normal.step(130);assert.equal(normal.qa[ID].inspect().locking.progress,.5);normal.step(270);assert.equal(normal.qa[ID].inspect().hits,1);assert.equal(normal.frame,false);normal.dispose();const reduced=harness();game.render(fixed(),reduced.context);assert.equal(reduced.frame,false);reduced.qa[ID].select(0);assert.equal(reduced.pending,3);reduced.runNext();assert.equal(reduced.qa[ID].inspect().locking.progress,.45);reduced.runNext();assert.equal(reduced.qa[ID].inspect().locking.progress,.8);reduced.runNext();assert.equal(reduced.qa[ID].inspect().hits,1);assert.equal(reduced.frame,false);reduced.dispose()});
test("keyboard uses fixed-position spatial navigation, Enter, focus ring state, and direct target input",()=>{const h=harness();game.render(fixed(),h.context);const {arena,stage,targets}=parts(h);assert.equal(h.owner.activeElement,arena);arena.dispatchEvent(event("keydown",{key:"ArrowDown"}));let state=h.qa[ID].inspect();assert.equal(state.focusIndex,3);assert.equal(state.keyboard,true);assert.equal(targets[3].dataset.spatial,"true");arena.dispatchEvent(event("keydown",{key:"Enter"}));assert.equal(h.qa[ID].inspect().locking.index,3);h.qa[ID].completeTransition();targets[1].dispatchEvent(event("pointerdown",{pointerType:"touch"}));state=h.qa[ID].inspect();assert.equal(state.result,"bystander");assert.equal(state.failedIndex,1);assert.equal(stage.dataset.busy,"false");h.dispose()});
test("DPR3, hit size, target order, and focus API remain inspectable at both widths",()=>{for(const width of [393,402]){const h=harness({viewport:{width,height:width===393?852:874,dpr:4}});game.render(fixed(),h.context);const api=h.qa[ID],state=api.inspect();assert.equal(state.dpr,3);assert.equal(state.hitSizeRem,3.15);assert.deepEqual(state.targets.map(value=>value.emoji),MULTISET);assert.equal(api.focus(7),true);assert.equal(api.inspect().focusIndex,7);assert.equal(api.move("left"),true);assert.notEqual(api.inspect().focusIndex,7);h.dispose()}});
test("dispose during reduced acquisition cancels stages, deadline, listeners, QA, and finish",()=>{const h=harness();game.render(fixed(),h.context);h.qa[ID].select(0);assert.equal(h.pending,3);h.dispose();h.runAll();h.timeout();assert.equal(h.qa[ID],undefined);assert.equal(h.pending,0);assert.equal(h.listeners,0);assert.deepEqual(h.finishes,[])});
test("real reduced runtime disposal leaves no delayed lock or commit",async()=>{const previousCancel=globalThis.cancelAnimationFrame;globalThis.cancelAnimationFrame=()=>{};try{const owner=documentFor(),host=owner.createElement("div"),qa={},finishes=[];host.getBoundingClientRect=()=>({left:0,top:0,width:393,height:852,right:393,bottom:852});const runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(fixed(),runtime.context);qa[ID].select(0);await delay(80);assert.equal(qa[ID].inspect().locking.progress,.45);runtime.dispose();assert.equal(qa[ID],undefined);await delay(220);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}});
test("source is ownerDocument-only, tracked-lifetime, and asset/audio/network free",()=>{assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement|new Image)\b/);assert.doesNotMatch(source,/https?:\/\//);assert.match(source,/animation:sef-float 1\.2s ease-in-out var\(--float-delay\) infinite alternate/);assert.match(source,/@keyframes sef-float\{to\{margin-top:-6px/);assert.match(source,/data-reduced=true.*animation:none!important/);assert.doesNotMatch(source,/\.(?:png|jpe?g|gif|webp|svg|mp3|wav|ogg)["']/i)});
