import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import game from "../src/games/spatial-golf-putt-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";
const ID="spatial-golf-putt-v1",moduleUrl=new URL("../src/games/spatial-golf-putt-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8"),appSource=await readFile(new URL("../app.js",import.meta.url),"utf8"),legacyFixtureSource=await readFile(new URL("./spatial-golf-putt-v1.legacy-fixture.mjs",import.meta.url),"utf8"),paritySource=await readFile(new URL("./spatial-golf-putt-v1.parity-qa.mjs",import.meta.url),"utf8");
const importFresh=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n// ${suffix}`).toString("base64")}`)).default;
const task=()=>({kind:"golfPutt",prompt:"グリーンを読んでホールイン",help:"白いボールを押さえ、打ちたい方向と反対へ引いて離す。",ball:{x:30,y:72},hole:{x:68,y:30},slope:{x:2,y:-1},mounds:[{x:22,y:28,size:34},{x:51,y:49,size:46},{x:78,y:72,size:40}],duration:14000});
function helpers(initial=0x51a9e){let seed=initial>>>0;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32),randomInt=(min,max)=>min+Math.floor(random()*(max-min+1));return{random,randomInt}}
function legacyGenerate(h){const ball={x:h.randomInt(22,38),y:h.randomInt(66,80)},hole={x:h.randomInt(58,78),y:h.randomInt(22,39)},slope={x:h.randomInt(-3,3),y:h.randomInt(-2,2)},mounds=Array.from({length:3},()=>({x:h.randomInt(15,85),y:h.randomInt(16,84),size:h.randomInt(28,52)}));if(!slope.x&&!slope.y)slope.x=2;return{kind:"golfPutt",prompt:"グリーンを読んでホールイン",help:"白いボールを押さえ、打ちたい方向と反対へ引いて離す。",ball,hole,slope,mounds,duration:14000}}
class ClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(v){this.values=new Set(String(v||"").split(/\s+/).filter(Boolean));this.sync()}sync(){this.owner._className=[...this.values].join(" ")}add(...v){v.forEach(x=>this.values.add(x));this.sync()}remove(...v){v.forEach(x=>this.values.delete(x));this.sync()}contains(v){return this.values.has(v)}}
const noop=()=>{};class Gradient{addColorStop(){}}function context2d(){return new Proxy({globalAlpha:1,createLinearGradient:()=>new Gradient(),createRadialGradient:()=>new Gradient()},{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)})}
class Element extends EventTarget{constructor(tag,owner){super();this.tagName=tag.toUpperCase();this.ownerDocument=owner;this.children=[];this.parentElement=null;this.attributes=new Map();this.dataset={};this.style={};this._className="";this.classList=new ClassList(this);this.textContent="";this.tabIndex=-1;this.clientWidth=393;this.width=0;this.height=0;this.ctx=this.tagName==="CANVAS"?context2d():null}set className(v){this._className=String(v);this.classList.reset(v)}get className(){return this._className}append(...nodes){for(const node of nodes){node.parentElement=this;this.children.push(node)}}replaceChildren(...nodes){this.children=[];this.append(...nodes)}setAttribute(k,v){this.attributes.set(k,String(v))}getAttribute(k){return this.attributes.get(k)??null}focus(){this.ownerDocument.activeElement=this}getContext(){return this.ctx}setPointerCapture(){}getBoundingClientRect(){const width=Number.parseFloat(this.style.width)||this.clientWidth||393,height=Number.parseFloat(this.style.height)||299;return{left:0,top:0,width,height,right:width,bottom:height}}}
function documentFor(dpr=3){const view=new EventTarget();view.devicePixelRatio=dpr;const owner={defaultView:view,activeElement:null};owner.createElement=tag=>new Element(tag,owner);return owner}
function event(type,props={}){const result=new Event(type,{bubbles:true,cancelable:true});for(const[k,v]of Object.entries(props))Object.defineProperty(result,k,{value:v});return result}
function harness({reduced=false,viewport={width:393,height:852,dpr:3},owner=documentFor(viewport.dpr)}={}){const controller=new AbortController(),host=owner.createElement("div"),qa={},jobs=[],listeners=new Set(),finishes=[];host.clientWidth=viewport.width;let frame=null,deadline=null,now=0,disposed=false,finishCalls=0;const dispose=()=>{if(disposed)return;disposed=true;controller.abort();for(const job of jobs)job.on=false;if(deadline)deadline.on=false;frame=null;for(const item of listeners)item.target.removeEventListener(item.type,item.fn,item.options);listeners.clear()};const context={host,signal:controller.signal,reducedMotion:reduced,viewport,qa,finish(correct,result={}){finishCalls++;if(disposed||finishes.length)return false;finishes.push({correct:Boolean(correct),result});dispose();return true},later(fn,ms){const job={at:now+Math.max(0,Number(ms)||0),fn,on:true};jobs.push(job);return job},setDeadline(ms,fn){deadline={at:now+ms,fn,on:true};return deadline},frame(fn){frame=fn;return()=>{frame=null}},listen(target,type,fn,options){target.addEventListener(type,fn,options);const item={target,type,fn,options};listeners.add(item);return()=>{target.removeEventListener(type,fn,options);listeners.delete(item)}}};const runTo=target=>{while(!disposed){const job=jobs.filter(x=>x.on&&x.at<=target).sort((a,b)=>a.at-b.at)[0];if(!job)break;now=job.at;job.on=false;job.fn()}now=target};const runAll=()=>{while(!disposed){const job=jobs.filter(x=>x.on).sort((a,b)=>a.at-b.at)[0];if(!job)break;runTo(job.at)}};const triggerDeadline=()=>{if(deadline?.on&&!disposed){deadline.on=false;deadline.fn();return true}return false};const step=time=>{if(frame&&frame(time)===false)frame=null};return{context,host,owner,qa,finishes,dispose,runTo,runAll,triggerDeadline,step,get frameActive(){return Boolean(frame)},get now(){return now},get finishCalls(){return finishCalls}}}
function mount(options={}){const h=harness(options),value=options.task||task();game.render(value,h.context);const api=h.qa[ID],stage=h.host.children[1],board=stage.children[1];return Object.assign(h,{task:value,api,stage,board,canvas:board.children[0],status:stage.children[2]})}
const near=(a,b,t=1e-8)=>Math.abs(a-b)<=t;

test("metadata preserves the published identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.0",tier:2,flavor:"wild",step:1,family:"spatial-golf-putt",category:"spatial"}));
test("10,000 generations exactly preserve current app.js random order, ranges, shape, and zero correction",()=>{const a=helpers(0xa8761a1),b=helpers(0xa8761a1),slopes=new Set(),started=performance.now();for(let i=0;i<10000;i++){const actual=game.generate(a),legacy=legacyGenerate(b);assert.deepEqual(actual,legacy,`generation ${i}`);assert.deepEqual(Object.keys(actual),["kind","prompt","help","ball","hole","slope","mounds","duration"]);assert.deepEqual(game.validate(actual),[]);assert.doesNotThrow(()=>structuredClone(actual));assert.ok(actual.slope.x||actual.slope.y);slopes.add(`${actual.slope.x},${actual.slope.y}`)}assert.ok(slopes.has("2,0"));assert.ok(performance.now()-started<4000)});
test("generator requires randomInt and validator rejects every rule/range/shape retune",()=>{assert.throws(()=>game.generate(),/randomInt/);const valid=task(),mutations=[null,{...valid,kind:"golf"},{...valid,prompt:"changed"},{...valid,help:"changed"},{...valid,duration:1},{...valid,ball:{x:21,y:72}},{...valid,hole:{x:79,y:30}},{...valid,slope:{x:0,y:0}},{...valid,slope:{x:4,y:0}},{...valid,mounds:valid.mounds.slice(1)},structuredClone(valid)];mutations.at(-1).mounds[0].size=53;for(const item of mutations)assert.ok(game.validate(item).length)});
test("source and parity fixtures pin exact current app.js factory, equations, and 56-frame matrix",()=>{assert.match(appSource,/\{id:"spatial-golf-putt-v1",version:"1\.0",category:"spatial",make:/);for(const exact of["const powerScale=2","shot.length<18","clamp(task.ball.x+shotX+task.slope.x,3,97)","distance<=7.5","},950)","Math.hypot(event.clientX-cx,event.clientY-cy)>48"]){assert.ok(appSource.includes(exact),exact);assert.ok(legacyFixtureSource.includes(exact),`fixture ${exact}`)}assert.match(paritySource,/scenes=\["initial","aim","short-pull","mid-putt","in-hole","miss","timeout"\]/);assert.match(paritySource,/viewports=\[\[393,852\],\[402,874\]\]/);assert.match(paritySource,/frames\.length===56/)});
test("plain saved JSON resumes in a fresh module and keyboard ideal shot lands exactly in the cup",async()=>{const fresh=await importFresh(Date.now()),value=JSON.parse(JSON.stringify(task())),h=harness();fresh.render(value,h.context);const api=h.qa[ID],stage=h.host.children[1],board=stage.children[1];board.dispatchEvent(event("keydown",{key:"Enter"}));const moving=api.inspect();assert.equal(moving.played,true);assert.ok(near(moving.final.x,value.hole.x));assert.ok(near(moving.final.y,value.hole.y));h.runTo(949);assert.equal(h.finishes.length,0);h.runTo(950);assert.deepEqual(h.finishes.map(x=>x.correct),[true]);assert.equal(h.finishes[0].result.quality,1);assert.equal(h.finishes[0].result.detail,"ナイスイン！引きと傾斜を読み切りました。");h.triggerDeadline();assert.equal(h.finishes.length,1)});
test("ideal and final equations preserve slope addition and exact measured green geometry",()=>{const h=mount(),s=h.api.inspect(),expectedX=(h.task.hole.x-h.task.ball.x-h.task.slope.x)*s.geometry.width/100,expectedY=(h.task.hole.y-h.task.ball.y-h.task.slope.y)*s.geometry.height/100;assert.ok(near(s.ideal.x,expectedX));assert.ok(near(s.ideal.y,expectedY));const final=h.api.computeFinal(s.ideal);assert.ok(near(final.x,h.task.hole.x));assert.ok(near(final.y,h.task.hole.y));assert.deepEqual(s.constants,{powerScale:2,minPull:18,cupRadius:7.5,settleMs:950,clamp:[3,97]});h.dispose()});
test("pointer drag starts only within 48px and release flies opposite pull at power two",()=>{const h=mount(),s=h.api.inspect(),ball={x:h.task.ball.x/100*s.geometry.width,y:h.task.ball.y/100*s.geometry.height};assert.equal(h.api.begin(ball.x+49,ball.y),false);assert.equal(h.api.inspect().dragging,false);assert.equal(h.api.begin(ball.x,ball.y),true);h.api.drag(ball.x-30,ball.y+24);assert.equal(h.api.release(),true);const state=h.api.inspect();assert.ok(near(state.shot.x,60));assert.ok(near(state.shot.y,-48));assert.ok(near(state.final.x,clamp(h.task.ball.x+60/s.geometry.width*100+h.task.slope.x,3,97)));assert.ok(near(state.final.y,clamp(h.task.ball.y-48/s.geometry.height*100+h.task.slope.y,3,97)));h.dispose()});
test("short pull and pointer cancel reset without consuming the one shot",()=>{const h=mount(),s=h.api.inspect(),x=h.task.ball.x/100*s.geometry.width,y=h.task.ball.y/100*s.geometry.height;h.api.begin(x,y);h.api.drag(x+10,y+6);assert.equal(h.api.release(),false);assert.equal(h.api.inspect().played,false);assert.match(h.api.inspect().status,/もう少し/);h.api.begin(x,y);h.api.drag(x-25,y);h.board.dispatchEvent(event("pointercancel",{pointerId:1}));assert.equal(h.api.inspect().dragging,false);assert.equal(h.api.inspect().played,false);h.dispose()});
test("final coordinates clamp at 3..97 and miss copy uses rounded percent-distance",()=>{const h=mount();assert.equal(h.api.putt(9999,-9999),true);let state=h.api.inspect();assert.deepEqual(state.final,{x:97,y:3});h.runTo(950);state=h.api.inspect();const distance=Math.hypot(97-h.task.hole.x,3-h.task.hole.y);assert.ok(near(state.distance,distance));assert.equal(state.result,"miss");assert.equal(h.finishes[0].result.detail,`カップまで、あと${Math.max(1,Math.round(distance))}歩でした。`)});
test("cup radius includes exactly 7.5 and quality remains the published distance/8 formula",()=>{for(const [offset,correct]of[[7.5,true],[7.5001,false]]){const h=mount(),s=h.api.inspect(),shotX=(h.task.hole.x+offset-h.task.ball.x-h.task.slope.x)*s.geometry.width/100,shotY=(h.task.hole.y-h.task.ball.y-h.task.slope.y)*s.geometry.height/100;h.api.putt(shotX,shotY);h.runTo(950);assert.equal(h.finishes[0].correct,correct,offset);if(correct)assert.ok(near(h.finishes[0].result.quality,1-7.5/8));else assert.match(h.finishes[0].result.detail,/カップまで/)}});
test("Enter and Space share ideal shot, retain focus, and input locks after play",()=>{for(const key of["Enter"," "]){const h=mount();assert.equal(h.owner.activeElement,h.board);h.board.dispatchEvent(event("keydown",{key}));const before=h.api.inspect();assert.equal(before.played,true);h.board.dispatchEvent(event("keydown",{key}));assert.equal(h.api.inspect().shot.length,before.shot.length);h.runAll();assert.equal(h.finishes.length,1)}});
test("normal presentation uses one tracked visual frame and still settles at 950ms",()=>{const h=mount(),shot=h.api.inspect().ideal;base: {h.api.putt(shot.x,shot.y)}assert.equal(h.frameActive,true);const start=performance.now();for(let i=0;i<55;i++)h.step(start+i*1000/60);assert.ok(h.api.inspect().frames>=50);assert.ok(h.api.inspect().progress>.9);h.runTo(949);assert.equal(h.finishes.length,0);h.runTo(950);assert.equal(h.finishes.length,1);assert.equal(h.finishes[0].correct,true)});
test("reduced motion uses deterministic nonzero tracked stages and no continuous frame",()=>{const h=mount({reduced:true}),shot=h.api.inspect().ideal;h.api.putt(shot.x,shot.y);assert.equal(h.frameActive,false);h.runTo(299);assert.equal(h.api.inspect().stages,0);h.runTo(300);assert.equal(h.api.inspect().stages,1);assert.ok(h.api.inspect().progress>0);h.runTo(620);assert.equal(h.api.inspect().stages,2);assert.equal(h.frameActive,false);h.runTo(950);assert.equal(h.finishes[0].correct,true)});
test("deadline preserves exact timeout copy and cannot double finish",()=>{const h=mount();h.triggerDeadline();h.triggerDeadline();assert.equal(h.api.inspect().result,"timeout");assert.equal(h.finishes.length,1);assert.equal(h.finishes[0].result.detail,"芝を読んでいる間に日が暮れました。");assert.equal(h.finishes[0].correct,false)});
test("393/402 layouts cap DPR3 and expose all seven parity scenes",()=>{for(const reduced of[false,true])for(const viewport of[{width:393,height:852,dpr:3},{width:402,height:874,dpr:4}]){const h=mount({reduced,viewport}),canvas=h.api.inspect().canvas;assert.equal(canvas.dpr,3);assert.equal(canvas.pixelWidth,canvas.cssWidth*3);assert.equal(canvas.pixelHeight,canvas.cssHeight*3);assert.ok(canvas.cssWidth<=viewport.width);for(const scene of["initial","aim","short-pull","mid-putt","in-hole","miss","timeout"])assert.equal(h.api.showScene(scene),true,scene);h.dispose()}});
test("real runtime disposal clears frame, deadline, stages, listeners, QA, and pending finish",async()=>{const oldRaf=globalThis.requestAnimationFrame,oldCancel=globalThis.cancelAnimationFrame;let id=0;const frames=new Map();globalThis.requestAnimationFrame=fn=>(frames.set(++id,fn),id);globalThis.cancelAnimationFrame=key=>frames.delete(key);try{const owner=documentFor(),host=owner.createElement("div"),qa={},finishes=[],runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(task(),runtime.context);const api=qa[ID],shot=api.inspect().ideal;api.putt(shot.x,shot.y);assert.ok(runtime.inspect().timeouts>=4);runtime.dispose();await delay(1000);assert.deepEqual(finishes,[]);assert.equal(qa[ID],undefined);assert.equal(frames.size,0);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(oldRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=oldRaf;if(oldCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=oldCancel}});
test("render owns its ownerDocument and source has no raw lifetime, network, audio, or asset primitive",()=>{const owner=documentFor(),old=globalThis.document;globalThis.document={createElement(){throw Error("global document used")}};try{const h=mount({owner});const visit=node=>{assert.equal(node.ownerDocument,owner);node.children.forEach(visit)};visit(h.host);h.dispose()}finally{if(old===undefined)delete globalThis.document;else globalThis.document=old}assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement)\b/);assert.doesNotMatch(source,/(?:\.src\s*=|url\s*\()/)});
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
