import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";

const moduleUrl=new URL("../src/games/spatial-suitcase-pack-v1.js",import.meta.url),moduleSource=await readFile(moduleUrl,"utf8");
const importGame=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${moduleSource}\n// ${suffix}`).toString("base64")}`)).default;
const game=await importGame("primary"),ID="spatial-suitcase-pack-v1",ITEM_IDS=["coat","boots","glass","notebook","pouch"];

class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}toggle(value,force){const add=force===undefined?!this.values.has(value):force;add?this.values.add(value):this.values.delete(value);this.sync();return add}sync(){this.owner._className=[...this.values].join(" ")}}
class FakeStyle{constructor(){this.values=new Map()}setProperty(name,value){this.values.set(name,String(value))}}
class FakeElement extends EventTarget{constructor(tagName,ownerDocument){super();this.tagName=tagName.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.attributes=new Map();this.dataset={};this.style=new FakeStyle();this.classList=new FakeClassList(this);this._className="";this.textContent="";this.type="";this.disabled=false;this.hidden=false;this.tabIndex=-1}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this.children=[...nodes]}setAttribute(name,value){this.attributes.set(name,String(value))}getAttribute(name){return this.attributes.get(name)??null}focus(){this.ownerDocument.activeElement=this}getBoundingClientRect(){return{left:0,top:0,width:390,height:530,right:390,bottom:530}}}
function createFakeDocument(name="document"){const view=new EventTarget();view.devicePixelRatio=3;const documentRef={name,activeElement:null,defaultView:view};documentRef.createElement=tag=>new FakeElement(tag,documentRef);return documentRef}
function installFakeDocument(){const previous=globalThis.document;globalThis.document=createFakeDocument("global");return()=>{if(previous===undefined)delete globalThis.document;else globalThis.document=previous}}
function createHarness({reducedMotion=false,viewport={width:390,height:844,dpr:3},ownerDocument=globalThis.document}={}){const controller=new AbortController(),host=ownerDocument.createElement("div"),qa={},pending=[],listeners=new Set(),finishes=[];let deadline=null,disposed=false,frameCalls=0;host.getBoundingClientRect=()=>({left:0,top:0,width:viewport.width-16,height:viewport.height,right:viewport.width-16,bottom:viewport.height});const context={host,signal:controller.signal,reducedMotion,viewport,qa,finish(correct,result){if(disposed||finishes.length)return false;finishes.push({correct,result:structuredClone(result)});return true},setDeadline(ms,fn){deadline={ms,fn,active:true}},later(fn,ms){const job={fn,ms,active:true};pending.push(job);return job},frame(){frameCalls++;return()=>{}},listen(target,type,fn,options){target.addEventListener(type,fn,options);const record={target,type,fn,options};listeners.add(record);return()=>{target.removeEventListener(type,fn,options);listeners.delete(record)}}};const runNext=()=>{const job=pending.find(entry=>entry.active);if(job&&!disposed){job.active=false;job.fn()}return job};const runAll=()=>{let guard=0;while(pending.some(job=>job.active)&&guard++<100){const jobs=pending.splice(0);jobs.forEach(job=>{if(job.active&&!disposed){job.active=false;job.fn()}})}};const triggerDeadline=()=>{if(deadline?.active&&!disposed){deadline.active=false;deadline.fn()}};const dispose=()=>{if(disposed)return;controller.abort();disposed=true;pending.forEach(job=>job.active=false);if(deadline)deadline.active=false;listeners.forEach(({target,type,fn,options})=>target.removeEventListener(type,fn,options));listeners.clear()};return{context,host,qa,finishes,runNext,runAll,triggerDeadline,dispose,get pendingCount(){return pending.filter(job=>job.active).length},get listenerCount(){return listeners.size},get deadline(){return deadline},get frameCalls(){return frameCalls}}}
const eventWith=(type,properties={})=>{const event=new Event(type,{bubbles:true,cancelable:true});Object.entries(properties).forEach(([key,value])=>Object.defineProperty(event,key,{value}));return event};
const taskAt=(index,order=ITEM_IDS)=>game.generate({pick:rows=>rows[index],shuffle:()=>[...order]});
const renderAt=({index=0,task=taskAt(index),reducedMotion=false,viewport}={})=>{const harness=createHarness({reducedMotion,viewport});game.render(task,harness.context);return{task,harness,api:harness.qa[ID]}};

const normalize=shape=>{const minX=Math.min(...shape.map(cell=>cell[0])),minY=Math.min(...shape.map(cell=>cell[1]));return shape.map(([x,y])=>[x-minX,y-minY]).sort((a,b)=>a[1]-b[1]||a[0]-b[0])};
const rotate=shape=>normalize(shape.map(([x,y])=>[-y,x]));
const key=shape=>normalize(shape).map(cell=>cell.join(",")).join(";");
const orientations=shape=>{const result=[];let current=normalize(shape);for(let turn=0;turn<4;turn++){if(!result.some(value=>key(value)===key(current)))result.push(current);current=rotate(current)}return result};
function independentSolutions(task,limit=4){const blocked=new Set(task.blocked),candidates=task.items.map(item=>{const result=[];orientations(item.shape).forEach((shape,orientation)=>{const width=1+Math.max(...shape.map(cell=>cell[0])),height=1+Math.max(...shape.map(cell=>cell[1]));for(let y=0;y<=task.height-height;y++)for(let x=0;x<=task.width-width;x++){const cells=shape.map(([dx,dy])=>(y+dy)*task.width+x+dx);if(!cells.some(cell=>blocked.has(cell)))result.push({orientation,x,y,cells})}});return result}),solutions=[];const visit=(remaining,occupied,placed)=>{if(solutions.length>=limit)return;if(!remaining.length){solutions.push(placed);return}let selected=-1,available=null;for(const item of remaining){const choices=candidates[item].filter(placement=>placement.cells.every(cell=>!occupied.has(cell)));if(!choices.length)return;if(!available||choices.length<available.length){selected=item;available=choices}}for(const placement of available){placement.cells.forEach(cell=>occupied.add(cell));visit(remaining.filter(item=>item!==selected),occupied,[...placed,{item:selected,...placement}]);placement.cells.forEach(cell=>occupied.delete(cell))}};visit(task.items.map((_,index)=>index),new Set(blocked),[]);return{solutions,candidates}}
const closeAndSettle=(api,harness)=>{assert.equal(api.close(),true);harness.runAll();assert.equal(harness.finishes.length,1);return harness.finishes[0]};

test("metadata publishes the assigned tier-three satisfying original",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"2.0",tier:3,flavor:"satisfying",step:1,family:"spatial-suitcase-pack",category:"spatial"}));
test("generation calls pick then shuffle once and only card order changes",()=>{const calls=[],task=game.generate({pick:rows=>(calls.push(["pick",rows.length]),rows[2]),shuffle:ids=>(calls.push(["shuffle",ids.join("|")]),[...ids].reverse())});assert.deepEqual(calls,[['pick',3],['shuffle',ITEM_IDS.join('|')]]);assert.equal(task.layout,"diagonal-pair");assert.deepEqual(task.itemOrder,[...ITEM_IDS].reverse());assert.deepEqual(game.validate(task),[]);assert.doesNotThrow(()=>structuredClone(task))});
test("three authored grids independently exhaust to exactly one, two, and three tilings",()=>{for(let index=0;index<3;index++){const task=taskAt(index),independent=independentSolutions(task);assert.equal(independent.solutions.length,index+1);assert.equal(task.proof.solutionCount,index+1);assert.equal(task.proof.usableCells,18);assert.equal(task.proof.itemCells,18);assert.equal(task.proof.totalCandidatePlacements,independent.candidates.flat().length);assert.deepEqual(game.validate(task),[])}});
test("every exhaustive tiling requires rotation and compression at the exact height boundary",()=>{for(let index=0;index<3;index++){const task=taskAt(index),solutions=independentSolutions(task).solutions;assert.ok(solutions.every(solution=>solution.some(placement=>placement.orientation!==0)));assert.equal(task.limit,2);assert.equal(task.proof.compressedHeight,2);assert.equal(task.proof.rawHeight,3);assert.equal(task.proof.oneOver,true);assert.equal(task.items.find(item=>item.id==="coat").height-task.items.find(item=>item.id==="coat").compressedHeight,1)}});
test("validator rejects geometry, proof, inventory, compression, placement, order, and retunes",()=>{const base=taskAt(0),mutations=[task=>task.blocked[0]=3,task=>task.proof.solutionCount=2,task=>task.itemOrder[0]=task.itemOrder[1],task=>task.items[0].shape.pop(),task=>task.state.items[1].compressed=true,task=>task.state.items[0].orientation=99,task=>task.state.items[0].placement={x:0,y:0,order:1},task=>{task.state.items[0].placement={x:1,y:1,order:1};task.state.items[1].placement={x:1,y:1,order:1}},task=>task.state.extra=true,task=>task.duration=1];for(const mutate of mutations){const task=structuredClone(base);mutate(task);assert.notDeepEqual(game.validate(task),[])}});
test("hundreds of tasks stay bounded cloneable and card order never changes proof",()=>{const orders=[];for(let index=0;index<360;index++){const row=index%3,order=[...ITEM_IDS.slice(index%5),...ITEM_IDS.slice(0,index%5)],task=game.generate({pick:rows=>rows[row],shuffle:()=>order});assert.deepEqual(game.validate(task),[]);assert.doesNotThrow(()=>structuredClone(task));assert.equal(task.proof.solutionCount,row+1);orders.push(task.itemOrder.join("|"))}assert.ok(new Set(orders).size>=5)});
test("render uses ownerDocument and exposes five essentials, twenty cells, finite controls, and no frame",()=>{const previous=globalThis.document,foreign=createFakeDocument("iframe");globalThis.document={createElement(){throw Error("global document used")}};try{const harness=createHarness({ownerDocument:foreign,viewport:{width:402,height:874,dpr:3}}),task=taskAt(0);game.render(task,harness.context);const api=harness.qa[ID],visit=node=>{assert.equal(node.ownerDocument,foreign);node.children.forEach(visit)};visit(harness.host);assert.equal(api.elements.itemButtons.size,5);assert.equal(api.elements.miniCells.size,5);assert.deepEqual([...api.elements.miniCells.entries()].map(([id,preview])=>[id,preview.cells.length]),[["coat",5],["boots",4],["glass",4],["notebook",3],["pouch",2]]);assert.equal(api.elements.gridButtons.length,20);assert.equal(api.inspect().analysis.placed,0);assert.equal(harness.frameCalls,0);assert.equal(harness.deadline.ms,60000);assert.equal(foreign.activeElement,null)}finally{if(previous===undefined)delete globalThis.document;else globalThis.document=previous}});
test("direct selection rotates, compresses once, places, moves, and removes exact state",()=>{const restore=installFakeDocument();try{const{harness,api}=renderAt({reducedMotion:true});assert.equal(api.select("coat"),true);const beforePreview=api.elements.miniCells.get("coat").cells.map(cell=>[cell.style.left,cell.style.top]);assert.equal(api.rotate(),true);assert.equal(api.inspect().state.items.find(item=>item.id==="coat").orientation,1);assert.notDeepEqual(api.elements.miniCells.get("coat").cells.map(cell=>[cell.style.left,cell.style.top]),beforePreview);assert.equal(api.compress(),true);assert.equal(api.elements.miniCells.get("coat").mini.getAttribute("data-height"),"H2");assert.equal(api.compress(),false);assert.equal(api.inspect().state.items.find(item=>item.id==="coat").compressed,true);assert.equal(api.place("coat",0,0),false);assert.equal(api.place("coat",1,0),true);const first=api.inspect().state.items.find(item=>item.id==="coat").placement;assert.equal(first.order,1);assert.equal(api.place("coat",2,0),true);assert.equal(api.inspect().state.items.find(item=>item.id==="coat").placement.order,2);assert.equal(api.remove(),true);assert.equal(api.inspect().state.items.find(item=>item.id==="coat").placement,null);harness.runAll();assert.equal(api.inspect().snapStage,2)}finally{restore()}});
test("captured touch drag snaps a visible pouch into the case",()=>{const restore=installFakeDocument();try{const{api,harness}=renderAt({reducedMotion:true}),button=api.elements.itemButtons.get("pouch"),view=document.defaultView,pointerId=7;button.dispatchEvent(eventWith("pointerdown",{pointerId,clientX:20,clientY:650}));assert.equal(api.inspect().drag.id,"pouch");view.dispatchEvent(eventWith("pointermove",{pointerId,clientX:117,clientY:66}));assert.deepEqual(api.inspect().ghost,{x:1,y:0});view.dispatchEvent(eventWith("pointerup",{pointerId,clientX:117,clientY:66}));const record=api.inspect().state.items.find(item=>item.id==="pouch");assert.deepEqual(record.placement,{x:1,y:0,order:1});assert.equal(api.inspect().drag,null);harness.runAll()}finally{restore()}});
test("native zero-detail keyboard controls select, rotate, place, move focus, and retain visible state",()=>{const restore=installFakeDocument();try{const{api}=renderAt({reducedMotion:true}),glass=api.elements.itemButtons.get("glass");glass.dispatchEvent(eventWith("click",{detail:0}));api.elements.rotateButton.dispatchEvent(eventWith("click",{detail:0}));assert.equal(api.inspect().state.items.find(item=>item.id==="glass").orientation,1);api.elements.gridButtons[1].dispatchEvent(eventWith("click",{detail:0}));assert.deepEqual(api.inspect().state.items.find(item=>item.id==="glass").placement,{x:1,y:0,order:1});api.elements.gridButtons[1].focus();api.elements.gridButtons[1].dispatchEvent(eventWith("keydown",{key:"ArrowDown"}));assert.equal(document.activeElement,api.elements.gridButtons[6]);assert.match(api.elements.grid.getAttribute("aria-label"),/最高1\/2/)}finally{restore()}});
test("all one-to-three exhaustive solution paths close successfully exactly once",()=>{const restore=installFakeDocument();try{for(let index=0;index<3;index++)for(let solution=0;solution<index+1;solution++){const{api,harness}=renderAt({index,reducedMotion:true});assert.equal(api.applySolution(solution,true),true);const before=api.inspect();assert.equal(before.analysis.outcome,"success");assert.equal(before.analysis.highest,2);const finish=closeAndSettle(api,harness);assert.deepEqual([finish.correct,finish.result.outcome],[true,"success"]);assert.equal(api.inspect().lid,"success");harness.triggerDeadline();assert.equal(harness.finishes.length,1)}}finally{restore()}});
test("uncompressed exact tiling is one over and leaves the lid visibly raised",()=>{const restore=installFakeDocument();try{const{api,harness}=renderAt({index:1,reducedMotion:true});api.scene("raised-lid");assert.equal(api.inspect().analysis.highest,3);const finish=closeAndSettle(api,harness);assert.deepEqual([finish.correct,finish.result.outcome,finish.result.analysis.highest],[false,"raised-lid",3]);assert.equal(api.inspect().lid,"raised-lid")}finally{restore()}});
test("missing essential close retains the illuminated tray inventory",()=>{const restore=installFakeDocument();try{const{api,harness}=renderAt({index:2,reducedMotion:true});api.scene("missing-essential");assert.deepEqual(api.inspect().analysis.missing,["pouch"]);const finish=closeAndSettle(api,harness);assert.equal(finish.result.outcome,"missing-essential");assert.deepEqual(finish.result.analysis.missing,["pouch"]);assert.equal(finish.result.state.items.find(item=>item.id==="pouch").placement,null)}finally{restore()}});
test("a newer hard piece over glass produces the crushed-fragile outcome and crack state in every layout",()=>{const restore=installFakeDocument();try{for(let index=0;index<3;index++){const{api,harness}=renderAt({index,reducedMotion:true});api.scene("crushed-fragile");assert.deepEqual(api.inspect().analysis.crushed,["glass"]);assert.ok(api.elements.pieceButtons.get("glass").some(button=>button.classList.contains("crushed")));const finish=closeAndSettle(api,harness);assert.equal(finish.result.outcome,"crushed-fragile");assert.deepEqual(finish.result.analysis.crushed,["glass"])}}finally{restore()}});
test("glass on top creates a non-crushing recoverable overlap and gap bad pack",()=>{const restore=installFakeDocument();try{const{api,harness}=renderAt({index:0,reducedMotion:true});api.scene("bad-pack");const analysis=api.inspect().analysis;assert.equal(analysis.outcome,"bad-pack");assert.deepEqual(analysis.crushed,[]);assert.ok(analysis.overlaps.length>0);assert.ok(analysis.gaps.length>0);assert.ok(analysis.highest<=2);const finish=closeAndSettle(api,harness);assert.equal(finish.result.outcome,"bad-pack");assert.deepEqual(finish.result.analysis.overlaps,analysis.overlaps);assert.deepEqual(finish.result.analysis.gaps,analysis.gaps)}finally{restore()}});
test("timeout commits exact retained placement, rotation, compression, heights, and fragile state once",()=>{const restore=installFakeDocument();try{const{api,harness}=renderAt({index:2});api.scene("crushed-fragile");const before=api.inspect();harness.triggerDeadline();assert.equal(harness.finishes.length,1);const finish=harness.finishes[0];assert.deepEqual([finish.correct,finish.result.outcome],[false,"timeout"]);assert.deepEqual(finish.result.state,before.state);assert.deepEqual(finish.result.analysis.heights,before.analysis.heights);assert.deepEqual(finish.result.analysis.crushed,before.analysis.crushed);harness.triggerDeadline();api.timeout();assert.equal(harness.finishes.length,1)}finally{restore()}});
test("plain JSON mid-pack resume validates and reproduces exact geometry before close",async()=>{const restore=installFakeDocument();try{const{api}=renderAt({index:1,reducedMotion:true});api.select("coat");api.rotate();api.compress();api.place("coat",0,0);const saved=JSON.parse(JSON.stringify(api.snapshotTask())),before=api.inspect(),fresh=await importGame(`resume-${Date.now()}`),harness=createHarness({reducedMotion:true});assert.deepEqual(fresh.validate(saved),[]);fresh.render(saved,harness.context);const resumed=harness.qa[ID].inspect();assert.deepEqual(resumed.state,before.state);assert.deepEqual(resumed.analysis.heights,before.analysis.heights);assert.deepEqual(resumed.analysis.stacks,before.analysis.stacks);assert.equal(resumed.selected,null)}finally{restore()}});
test("reduced motion retains nonzero tracked snap and two close stages without frames",()=>{const restore=installFakeDocument();try{const{api,harness}=renderAt({reducedMotion:true});api.select("pouch");api.place("pouch",1,0);assert.equal(api.inspect().snapStage,1);assert.equal(harness.pendingCount,1);assert.equal(harness.frameCalls,0);harness.runNext();assert.equal(api.inspect().snapStage,2);api.scene("success");api.close();assert.equal(api.inspect().closeStage,0);assert.equal(harness.pendingCount,2);harness.runNext();assert.equal(api.inspect().closeStage,1);assert.equal(harness.finishes.length,0);harness.runNext();assert.equal(api.inspect().closeStage,2);assert.equal(harness.finishes.length,1)}finally{restore()}});
test("dispose during close clears QA, deadline, stages, listeners, and late finish",()=>{const restore=installFakeDocument();try{const{api,harness}=renderAt();api.scene("success");api.close();assert.ok(harness.pendingCount>=2);harness.dispose();harness.runAll();harness.triggerDeadline();assert.equal(harness.qa[ID],undefined);assert.equal(harness.pendingCount,0);assert.equal(harness.listenerCount,0);assert.deepEqual(harness.finishes,[]);assert.equal(api.inspect().disposed,true)}finally{restore()}});
test("real runtime disposal synchronously removes all tracked ownership",async()=>{const restore=installFakeDocument(),previousCancel=globalThis.cancelAnimationFrame;globalThis.cancelAnimationFrame=id=>clearTimeout(id);try{const qa={},finishes=[],host=document.createElement("div"),runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(taskAt(0),runtime.context);qa[ID].scene("success");qa[ID].close();assert.ok(runtime.inspect().timeouts>=3);runtime.dispose();await delay(120);assert.equal(qa[ID],undefined);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{restore();if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}});
test("300 cold renders remain bounded with fixed finite DOM and no frame workload",()=>{const restore=installFakeDocument();try{let latest=null;const started=performance.now();for(let index=0;index<300;index++){latest?.harness.dispose();const harness=createHarness({reducedMotion:false,viewport:{width:430,height:932,dpr:3}});game.render(taskAt(index%3),harness.context);latest={harness,api:harness.qa[ID]}}const elapsed=performance.now()-started,{harness,api}=latest;assert.ok(elapsed<4000,`300 renders took ${elapsed}ms`);assert.equal(harness.frameCalls,0);assert.equal(api.elements.gridButtons.length,20);assert.equal(api.elements.itemButtons.size,5);assert.equal([...api.elements.pieceButtons.values()].flat().length,18);assert.ok(harness.host.children.length===2);harness.dispose()}finally{restore()}});
test("source is ownerDocument-only, context-tracked, offline, frame/audio/emoji-free, and cue-free",()=>{assert.match(moduleSource,/context\.host\?\.ownerDocument/);assert.doesNotMatch(moduleSource,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(moduleSource,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(moduleSource,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement)\b/);assert.doesNotMatch(moduleSource,/[\p{Extended_Pictographic}]/u);assert.doesNotMatch(moduleSource,/data-(?:answer|correct|target|solution)|className\s*=\s*["'][^"']*(?:answer|correct|target|solution)/);assert.match(moduleSource,/\.spk-piece\[hidden\].*display:none!important/);assert.doesNotMatch(moduleSource,/itemOrder\[0\]\)\.focus/)});
