import game from "../src/games/spatial-flow-link-v1.js";import{createGameRuntime}from"../src/game-kernel.js";
const params=new URLSearchParams(location.search),width=Number(params.get("width"))||393,reduced=params.get("motion")==="reduced",auto=params.get("auto")==="1";document.body.style.width=`${width}px`;
const route=[];for(let r=0;r<5;r++)for(let i=0;i<5;i++)route.push({r,c:r%2?4-i:i});const lengths=[6,6,6,7],solution=[];let cursor=0;lengths.forEach(length=>{solution.push(route.slice(cursor,cursor+length));cursor+=length});
const task={kind:"flowLink",prompt:"同じ色をつないで",help:"色の点から指をなぞって同じ色へ。すべての色をつなぎ、全部のマスを埋めれば成功です。",endpoints:solution.map((path,color)=>({color,a:{...path[0]},b:{...path.at(-1)}})),solution,size:5,duration:80000};
const host=document.querySelector("#challenge"),result=document.querySelector("#result"),qa={},frameDeltas=[];let previous=performance.now(),monitoring=true,runtime,controls=null,initial=null;const monitor=now=>{if(!monitoring)return;frameDeltas.push(now-previous);previous=now;if(frameDeltas.length<900)requestAnimationFrame(monitor)};requestAnimationFrame(monitor);
const finish=(correct,detail)=>{monitoring=false;result.hidden=false;result.textContent=`${correct?"成功":"失敗"} — ${detail.detail}`;if(!auto)return;setTimeout(()=>{const inspection=runtime.inspect(),failures=[];if(!correct)failures.push("solve failed");if(!controls?.touch||!controls?.keyboard)failures.push("controls failed");if(!(inspection.disposed&&inspection.aborted&&!inspection.timeouts&&!inspection.frames&&!inspection.listeners))failures.push("cleanup failed");if(document.body.scrollWidth>width)failures.push("overflow");const report={status:failures.length?"fail":"pass",failures,correct,detail,controls,viewport:{width,dpr:devicePixelRatio,touchEvents:"ontouchstart"in window,pointerEvents:"PointerEvent"in window,bodyScrollWidth:document.body.scrollWidth},canvas:initial.canvas,runtime:inspection,resources:performance.getEntriesByType("resource").map(x=>new URL(x.name).pathname)};const pre=document.createElement("pre");pre.dataset.status=report.status;pre.textContent=JSON.stringify(report,null,2);document.body.replaceChildren(pre)},0)};
runtime=createGameRuntime({host,reducedMotion:reduced,viewport:{width,height:innerHeight,dpr:devicePixelRatio},qa,onFinish:finish});game.render(task,runtime.context);const api=qa[game.metadata.id];initial=api.inspect();
if(auto){const canvas=host.querySelector(".afl-canvas"),rect=canvas.getBoundingClientRect(),cx=rect.left+rect.width*.17,cy=rect.top+rect.height*.215;canvas.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:7,pointerType:"touch",clientX:cx,clientY:cy}));canvas.dispatchEvent(new PointerEvent("pointermove",{bubbles:true,cancelable:true,pointerId:7,pointerType:"touch",clientX:cx+rect.width*.165,clientY:cy}));const touch=api.inspect().drag===0&&api.inspect().paths[0].length>=2;canvas.dispatchEvent(new PointerEvent("pointerup",{bubbles:true,cancelable:true,pointerId:7,pointerType:"touch",clientX:cx+rect.width*.165,clientY:cy}));canvas.dispatchEvent(new KeyboardEvent("keydown",{bubbles:true,cancelable:true,key:"Enter"}));canvas.dispatchEvent(new KeyboardEvent("keydown",{bubbles:true,cancelable:true,key:"ArrowRight"}));const keyboard=api.inspect().drag===0&&document.activeElement===canvas;canvas.dispatchEvent(new KeyboardEvent("keydown",{bubbles:true,cancelable:true,key:"Enter"}));controls={touch,keyboard};api.solve()}
const scene=params.get("scene");if(scene)api.showScene(scene);
if(params.get("measureLog")==="1")setTimeout(()=>{monitoring=false;const stable=frameDeltas.slice(5),inspection=api.inspect(),query=new URLSearchParams({frames:String(stable.length),averageFrameMs:(stable.reduce((a,b)=>a+b,0)/Math.max(1,stable.length)).toFixed(3),maxFrameMs:Math.max(0,...stable).toFixed(3),gameFrames:String(inspection.frames),pixelWidth:String(inspection.canvas.pixelWidth),pixelHeight:String(inspection.canvas.pixelHeight),dpr:String(inspection.canvas.dpr)});location.replace(`spatial-flow-link-v1.performance-result.html?${query}`)},1500);
window.__FLOW_FIXTURE__={task,qa,runtime,evidence:()=>({game:qa[game.metadata.id]?.inspect(),runtime:runtime.inspect()})};
