import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import game from "../src/games/spatial-sheep-home-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";

const ID="spatial-sheep-home-v1",source=await readFile(new URL("../src/games/spatial-sheep-home-v1.js",import.meta.url),"utf8");
const generate=variant=>game.generate({randomInt:()=>variant});
class ClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean));this.sync()}sync(){this.owner._className=[...this.values].join(" ")}add(...items){items.forEach(item=>this.values.add(item));this.sync()}remove(...items){items.forEach(item=>this.values.delete(item));this.sync()}contains(item){return this.values.has(item)}toggle(item,force){const add=force===undefined?!this.values.has(item):force;add?this.values.add(item):this.values.delete(item);this.sync();return add}}
class Style{constructor(){this.values=new Map()}setProperty(key,value){this.values.set(key,String(value))}}
const noop=()=>{};class Gradient{addColorStop(){}}function canvasContext(){return new Proxy({globalAlpha:1,createLinearGradient:()=>new Gradient(),createRadialGradient:()=>new Gradient()},{get(object,key){return key in object?object[key]:noop},set(object,key,value){object[key]=value;return true}})}
class Element extends EventTarget{constructor(tag,doc){super();this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.children=[];this.parentElement=null;this.attributes=new Map();this.dataset={};this.style=new Style();this.classList=new ClassList(this);this._className="";this.textContent="";this.type="";this.disabled=false;this.tabIndex=-1;this.width=0;this.height=0;this.context=this.tagName==="CANVAS"?canvasContext():null}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}append(...nodes){nodes.forEach(node=>{node.parentElement=this;this.children.push(node)})}replaceChildren(...nodes){this.children=[];this.append(...nodes)}setAttribute(key,value){this.attributes.set(key,String(value))}getAttribute(key){return this.attributes.get(key)??null}focus(){this.ownerDocument.activeElement=this}getContext(){return this.context}getBoundingClientRect(){const width=Number.parseFloat(this.style.values.get("width"))||393,height=Number.parseFloat(this.style.values.get("height"))||456;return{left:0,top:0,width,height,right:width,bottom:height}}}
function documentFor(dpr=3){const view=new EventTarget();view.devicePixelRatio=dpr;const doc={activeElement:null,defaultView:view};doc.createElement=tag=>new Element(tag,doc);return doc}
function event(type,properties={}){const value=new Event(type,{bubbles:true,cancelable:true});Object.entries(properties).forEach(([key,item])=>Object.defineProperty(value,key,{value:item}));return value}
function harness({reduced=true,viewport={width:393,height:852,dpr:3},owner=documentFor(viewport.dpr)}={}){const controller=new AbortController(),host=owner.createElement("div"),qa={},jobs=[],listeners=new Set(),finishes=[];let deadline=null,frame=null,time=0,disposed=false;host.getBoundingClientRect=()=>({left:0,top:0,width:viewport.width,height:viewport.height});const dispose=()=>{if(disposed)return;controller.abort();disposed=true;jobs.forEach(job=>job.active=false);if(deadline)deadline.active=false;frame=null;listeners.forEach(item=>item.target.removeEventListener(item.type,item.fn,item.options));listeners.clear()};const context={host,signal:controller.signal,reducedMotion:reduced,viewport,qa,finish(correct,result){if(disposed||finishes.length)return false;finishes.push({correct,result});return true},later(fn,ms){const job={fn,at:time+ms,active:true};jobs.push(job);return job},setDeadline(ms,fn){deadline={fn,at:time+ms,active:true};return deadline},frame(fn){frame=fn;return()=>{frame=null}},listen(target,type,fn,options){target.addEventListener(type,fn,options);const item={target,type,fn,options};listeners.add(item);return()=>{target.removeEventListener(type,fn,options);listeners.delete(item)}}};const runNext=()=>{const job=jobs.filter(item=>item.active).sort((a,b)=>a.at-b.at)[0];if(!job)return false;time=job.at;job.active=false;job.fn();return true};const runAll=()=>{while(runNext());};const step=at=>{time=at;if(frame&&frame(at)===false)frame=null};const timeout=()=>{if(deadline?.active&&!disposed){deadline.active=false;deadline.fn()}};return{context,host,owner,qa,finishes,dispose,runNext,runAll,step,timeout,get pending(){return jobs.filter(item=>item.active).length},get frame(){return Boolean(frame)},get listeners(){return listeners.size}}}
const parts=h=>{const stage=h.host.children[1];return{stage,status:stage.children[0],canvas:stage.children[1],controls:stage.children[2],progress:stage.children[3]}};
function runPath(h,path){for(const action of path){assert.equal(h.qa[ID].act(action),true,action);h.runAll()}}
function findWolfPath(api,maxDepth=10){const queue=[{state:api.initial(),path:[]}],seen=new Set();while(queue.length){const node=queue.shift();if(node.path.length>=maxDepth)continue;for(const action of ["G","N","E","S","W"]){const result=api.simulate(node.state,action);if(!result.valid)continue;const path=[...node.path,action];if(result.state.result==="wolf")return path;if(result.state.result)continue;const key=JSON.stringify(result.state);if(!seen.has(key)){seen.add(key);queue.push({state:result.state,path})}}}return null}

test("metadata is the accepted original-game identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"2.0",tier:3,flavor:"satisfying",step:1,family:"spatial-sheep-home",category:"spatial"}));
test("1000 finite layouts clone, validate, and retain minimum bounded proofs",()=>{const started=performance.now(),solutions=new Set();for(let index=0;index<1000;index++){const task=generate(index%2);assert.doesNotThrow(()=>structuredClone(task));assert.deepEqual(game.validate(task),[]);assert.equal(task.sheep.length,4);assert.equal(task.proof.lattice,5);assert.equal(task.proof.maxDepth,12);assert.equal(task.proof.minMoves,9);assert.ok(task.proof.nodes<=20000);solutions.add(task.solution.join(""))}assert.equal(solutions.size,2);assert.ok(performance.now()-started<5000)});
test("authored mirrors require two gathers and safely replay every sheep through the gate",()=>{for(const variant of [0,1]){const task=generate(variant),h=harness();game.render(task,h.context);const api=h.qa[ID];assert.equal(task.solution.filter(action=>action==="G").length,2);let state=api.initial();for(const action of task.solution){const result=api.simulate(state,action);assert.equal(result.valid,true);assert.notEqual(result.state.result,"escape");assert.notEqual(result.state.result,"wolf");state=result.state}assert.equal(state.result,"success");assert.ok(state.sheep.every(item=>item.home&&!item.escaped));assert.equal(new Set(state.sheep.map(item=>`${item.x},${item.y}`)).size,4);h.dispose()}});
test("validator rejects geometry, fence, wind, patrol, rules, solution, and proof mutations",()=>{const task=generate(0),items=[];for(const [key,value] of [["duration",1],["maxMoves",2],["wind","N"]])items.push({...task,[key]:value});const sheep=structuredClone(task);sheep.sheep[1].x=sheep.sheep[0].x;sheep.sheep[1].y=sheep.sheep[0].y;items.push(sheep);const fence=structuredClone(task);fence.fences.pop();items.push(fence);const wolf=structuredClone(task);wolf.wolf.path[0]={x:-1,y:0};items.push(wolf);const solution=structuredClone(task);solution.solution=["N"];solution.proof.minMoves=1;items.push(solution);const proof=structuredClone(task);proof.proof.nodes=99999;items.push(proof);items.forEach((item,index)=>assert.ok(game.validate(item).length,`mutation ${index}`))});
test("plain JSON resume follows the stored proof and commits one real success",()=>{const task=JSON.parse(JSON.stringify(generate(0))),h=harness();game.render(task,h.context);runPath(h,task.solution);assert.deepEqual(h.finishes.map(item=>item.correct),[true]);assert.match(h.finishes[0].result.detail,/4頭/);h.timeout();assert.equal(h.finishes.length,1)});
test("blocked fence command is invalid and leaves flock and wolf unchanged",()=>{const h=harness(),task=generate(0);game.render(task,h.context);runPath(h,task.solution.slice(0,3));const before=h.qa[ID].inspect().game;assert.equal(h.qa[ID].act("N"),false);const after=h.qa[ID].inspect();assert.equal(after.invalid,true);assert.deepEqual(after.game,before);assert.match(after.status,/柵/);h.runAll();assert.equal(h.qa[ID].inspect().invalid,false);h.dispose()});
test("moving against wind without gathering produces a distinct escape failure once",()=>{const h=harness(),task=generate(0);game.render(task,h.context);assert.equal(h.qa[ID].act("E"),true);h.runAll();assert.deepEqual(h.finishes.map(item=>item.correct),[false]);assert.equal(h.qa[ID].inspect().result,"escape");assert.match(h.finishes[0].result.detail,/風/);h.timeout();assert.equal(h.finishes.length,1)});
test("wolf patrol contact is a separate reachable failure",()=>{const h=harness(),task=generate(0);game.render(task,h.context);const path=findWolfPath(h.qa[ID],12);assert.ok(path,"wolf contact path must be reachable");runPath(h,path);assert.deepEqual(h.finishes.map(item=>item.correct),[false]);assert.equal(h.qa[ID].inspect().result,"wolf");assert.match(h.finishes[0].result.detail,/狼/)});
test("timeout preserves the real remaining count and cannot double finish",()=>{const h=harness();game.render(generate(0),h.context);h.timeout();h.timeout();h.runAll();assert.deepEqual(h.finishes.map(item=>item.correct),[false]);assert.equal(h.qa[ID].inspect().result,"timeout");assert.match(h.finishes[0].result.detail,/0頭/)});
test("touch pasture, keyboard, focus, and busy input lock share the same actions",()=>{const h=harness(),task=generate(0);game.render(task,h.context);const {canvas,stage}=parts(h);assert.equal(h.owner.activeElement,canvas);const rect=canvas.getBoundingClientRect();canvas.dispatchEvent(event("pointerdown",{clientX:rect.width*.22,clientY:rect.height*.72,pointerType:"touch",pointerId:4}));assert.equal(h.qa[ID].inspect().busy,true);const moves=h.qa[ID].inspect().game.moves;canvas.dispatchEvent(event("keydown",{key:"ArrowUp"}));assert.equal(h.qa[ID].inspect().game.moves,moves);h.runAll();canvas.dispatchEvent(event("keydown",{key:"ArrowUp"}));assert.equal(stage.dataset.keyboard,"true");assert.equal(h.qa[ID].inspect().busy,true);h.dispose()});
test("normal motion uses owned frames while reduced motion exposes tracked mid and settle stages",()=>{const normal=harness({reduced:false});game.render(generate(0),normal.context);assert.equal(normal.frame,true);normal.qa[ID].act("G");normal.step(0);normal.step(260);assert.equal(normal.qa[ID].inspect().busy,true);normal.step(540);assert.equal(normal.qa[ID].inspect().busy,false);normal.dispose();const reduced=harness();game.render(generate(0),reduced.context);reduced.qa[ID].act("G");assert.equal(reduced.pending,2);assert.equal(reduced.qa[ID].inspect().busy,true);reduced.runNext();assert.equal(reduced.qa[ID].inspect().phase,"mid-command");reduced.runNext();assert.equal(reduced.qa[ID].inspect().phase,"settled");assert.equal(reduced.qa[ID].inspect().busy,false);reduced.dispose()});
test("DPR backing and ten concept-required visual states remain inspectable",()=>{const h=harness({viewport:{width:402,height:874,dpr:4}});game.render(generate(0),h.context);const api=h.qa[ID],canvas=api.inspect().canvas;assert.equal(canvas.dpr,3);assert.equal(canvas.pixelWidth,canvas.cssWidth*3);assert.equal(canvas.pixelHeight,canvas.cssHeight*3);assert.equal(api.showScene("success"),true);assert.deepEqual(api.inspect().hud,{flock:"まとまり",footer:"全頭帰還",wind:"東→西の風"});for(const scene of ["initial","gather","valid-move","wind-blocked","fence-invalid","wolf-pressure","success","escape","wolf","timeout"])assert.equal(api.showScene(scene),true);h.dispose()});
test("dispose cancels reduced stages, deadline, frame, listeners, QA, and finish",async()=>{const staged=harness();game.render(generate(0),staged.context);staged.qa[ID].act("G");assert.equal(staged.pending,2);staged.dispose();staged.runAll();staged.timeout();assert.equal(staged.qa[ID],undefined);assert.equal(staged.finishes.length,0);assert.equal(staged.pending,0);assert.equal(staged.listeners,0);const previousRaf=globalThis.requestAnimationFrame,previousCancel=globalThis.cancelAnimationFrame;let id=0;const frames=new Map();globalThis.requestAnimationFrame=fn=>{frames.set(++id,fn);return id};globalThis.cancelAnimationFrame=key=>frames.delete(key);try{const owner=documentFor(),host=owner.createElement("div"),qa={},finishes=[],runtime=createGameRuntime({host,qa,reducedMotion:false,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(generate(0),runtime.context);qa[ID].act("G");runtime.dispose();await delay(500);assert.equal(qa[ID],undefined);assert.deepEqual(finishes,[]);assert.equal(frames.size,0);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{if(previousRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=previousRaf;if(previousCancel===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=previousCancel}assert.match(source,/context\.host\?\.ownerDocument/);assert.doesNotMatch(source,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement)\b/)});
