import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";
const moduleUrl=new URL("../src/games/spatial-shelf-balance-v1.js",import.meta.url),moduleSource=await readFile(moduleUrl,"utf8");
const importGame=async suffix=>(await import(`data:text/javascript;base64,${Buffer.from(`${moduleSource}\n//${suffix}`).toString("base64")}`)).default;
const game=await importGame("primary"),ID="spatial-shelf-balance-v1",IDS=["vase","lantern","orb","bowl","frame","stack"];
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(v){this.values=new Set(String(v||"").split(/\s+/).filter(Boolean))}add(...v){v.forEach(x=>this.values.add(x));this.sync()}remove(...v){v.forEach(x=>this.values.delete(x));this.sync()}contains(v){return this.values.has(v)}toggle(v,f){const add=f===undefined?!this.values.has(v):f;add?this.values.add(v):this.values.delete(v);this.sync();return add}sync(){this.owner._className=[...this.values].join(" ")}}
class FakeStyle{setProperty(name,value){this[name]=String(value)}}
class FakeElement extends EventTarget{constructor(tag,doc){super();this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.children=[];this.attributes=new Map();this.dataset={};this.style=new FakeStyle();this.classList=new FakeClassList(this);this._className="";this.textContent="";this.disabled=false;this.type=""}set className(v){this._className=String(v);this.classList.reset(v)}get className(){return this._className}append(...n){this.children.push(...n)}replaceChildren(...n){this.children=[...n]}setAttribute(k,v){this.attributes.set(k,String(v))}getAttribute(k){return this.attributes.get(k)??null}focus(){this.ownerDocument.activeElement=this}getBoundingClientRect(){return{left:0,top:0,width:390,height:320,right:390,bottom:320}}}
function fakeDocument(name="doc"){const view=new EventTarget();view.devicePixelRatio=3;const doc={name,defaultView:view,activeElement:null};doc.createElement=tag=>new FakeElement(tag,doc);return doc}
function installDocument(){const prev=globalThis.document;globalThis.document=fakeDocument();return()=>{if(prev===undefined)delete globalThis.document;else globalThis.document=prev}}
function harness({reducedMotion=false,ownerDocument=globalThis.document,viewport={width:393,height:852,dpr:3}}={}){const controller=new AbortController(),host=ownerDocument.createElement("div"),qa={},pending=[],listeners=new Set(),finishes=[];let deadline=null,disposed=false,frames=0;const context={host,signal:controller.signal,qa,reducedMotion,viewport,finish(correct,result){if(disposed||finishes.length)return false;finishes.push({correct,result:structuredClone(result)});return true},later(fn,ms){const j={fn,ms,active:true};pending.push(j);return j},setDeadline(ms,fn){deadline={ms,fn,active:true}},frame(){frames++;return()=>{}},listen(target,type,fn,options){target.addEventListener(type,fn,options);const r={target,type,fn,options};listeners.add(r);return()=>{target.removeEventListener(type,fn,options);listeners.delete(r)}}};const runMs=ms=>{const job=pending.find(j=>j.active&&j.ms===ms);if(job&&!disposed){job.active=false;job.fn()}return job};const runAll=()=>{let guard=0;while(pending.some(j=>j.active)&&guard++<100){const jobs=pending.splice(0);for(const j of jobs)if(j.active&&!disposed){j.active=false;j.fn()}}};const trigger=()=>{if(deadline?.active&&!disposed){deadline.active=false;deadline.fn()}};const dispose=()=>{if(disposed)return;controller.abort();disposed=true;pending.forEach(j=>j.active=false);if(deadline)deadline.active=false;listeners.forEach(r=>r.target.removeEventListener(r.type,r.fn,r.options));listeners.clear()};return{context,host,qa,pending,finishes,runMs,runAll,trigger,dispose,get pendingCount(){return pending.filter(j=>j.active).length},get listeners(){return listeners.size},get deadline(){return deadline},get frames(){return frames}}}
const eventWith=(type,props={})=>{const e=new Event(type,{bubbles:true,cancelable:true});for(const[k,v]of Object.entries(props))Object.defineProperty(e,k,{value:v});return e};
const taskAt=i=>game.generate({pick:rows=>rows[i]});
const renderAt=({index=0,task=taskAt(index),reducedMotion=false,ownerDocument=globalThis.document}={})=>{const h=harness({reducedMotion,ownerDocument});game.render(task,h.context);return{h,api:h.qa[ID],task}};
function* perms(a,n=0){if(n===a.length){yield[...a];return}for(let i=n;i<a.length;i++){[a[n],a[i]]=[a[i],a[n]];yield*perms(a,n+1);[a[n],a[i]]=[a[i],a[n]]}}
function assess(task,p){const by=new Map(task.items.map(i=>[i.id,i]));let moment=0;for(let i=0;i<6;i++)moment+=by.get(p[i]).weight*task.slots[i].column;const hidden=[];for(let c=0;c<3;c++)if(by.get(p[3+c]).height===3)hidden.push(p[c]);return{difference:Math.abs(moment),hidden,success:moment===0&&!hidden.length}}
const enumerate=task=>{const all=[...perms([...IDS])],valid=all.filter(p=>assess(task,p).success),balancedHidden=all.filter(p=>{const a=assess(task,p);return!a.difference&&a.hidden.length}),visibleUnbalanced=all.filter(p=>{const a=assess(task,p);return a.difference&&!a.hidden.length});return{all,valid,balancedHidden,visibleUnbalanced}};

test("metadata is the assigned tier-two satisfying original",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"2.0",tier:2,flavor:"satisfying",step:1,family:"spatial-shelf-balance",category:"spatial"}));
test("generation picks one of three finite starts exactly once",()=>{let calls=0;const task=game.generate({pick:rows=>(calls++,rows[2])});assert.equal(calls,1);assert.equal(task.layout,"rose-window");assert.equal(task.duration,22000);assert.deepEqual(game.validate(task),[]);assert.doesNotThrow(()=>structuredClone(task))});
test("independent 6-factorial enumeration proves all exact layout classes",()=>{for(let i=0;i<3;i++){const task=taskAt(i),e=enumerate(task);assert.equal(e.all.length,720);assert.equal(e.valid.length,32);assert.equal(e.balancedHidden.length,128);assert.equal(e.visibleUnbalanced.length,112);assert.equal(task.proof.validLayouts,32);assert.equal(task.proof.everySwapReversible,true)}});
test("large-first visibly hides two and authored starts never begin successful",()=>{for(let i=0;i<3;i++){const task=taskAt(i),naive=assess(task,task.proof.naiveLargeFirst.positions),start=assess(task,task.start);assert.equal(naive.hidden.length,2);assert.ok(naive.difference>0);assert.equal(start.success,false);assert.deepEqual(task.proof.start,{difference:start.difference,hiddenCount:start.hidden.length})}});
test("validator rejects rule, slot, proof, start, permutation, move, and extra-field changes",()=>{const base=taskAt(0),changes=[t=>t.duration=1,t=>t.items[0].weight=2,t=>t.slots[0].column=0,t=>t.proof.validLayouts=1,t=>t.start.reverse(),t=>t.state.positions[0]=t.state.positions[1],t=>t.state.moves=-1,t=>t.state.extra=true];for(const change of changes){const task=structuredClone(base);change(task);assert.notDeepEqual(game.validate(task),[])}});
test("render owns warm shelf DOM and exposes only three quantities with six objects and slots",()=>{const prev=globalThis.document,foreign=fakeDocument("foreign");globalThis.document={createElement(){throw Error("global document")}};try{const{h,api}=renderAt({ownerDocument:foreign});const visit=n=>{assert.equal(n.ownerDocument,foreign);n.children.forEach(visit)};visit(h.host);assert.equal(api.elements.readout.children.length,3);assert.equal(api.elements.objectButtons.size,6);assert.ok([...api.elements.objectButtons.values()].every(button=>button.children[1].textContent==="動かす"));assert.equal(api.elements.board.children.find(child=>child.className==="shb-bays").children.length,3);for(const bay of api.elements.bayNodes){assert.equal(bay.children.length,3);assert.equal(bay.children[0].className,"shb-tier rear");assert.equal(bay.children[0].children[0].textContent,"後ろ");assert.equal(bay.children[1].className,"shb-tier front");assert.equal(bay.children[1].children[0].textContent,"前");assert.equal(bay.children[2].className,"shb-occlusion-edge")}assert.equal(api.elements.depthKey.children[2].textContent,"背高 → 後ろ");assert.equal(api.elements.depthKey.getAttribute("aria-hidden"),"true");assert.deepEqual(api.elements.beamCues.children.map(node=>node.textContent),["左","0","右"]);assert.equal(api.elements.beam.className,"shb-beam heavy-left");assert.equal(api.elements.slotButtons.length,6);assert.match(api.elements.differenceNode.textContent,/左右差/);assert.match(api.elements.hiddenNode.textContent,/かくれ/);assert.equal(api.elements.timeNode.textContent,"残り 22秒");assert.equal(api.elements.timeNode.classList.contains("time"),true);assert.equal(h.deadline.ms,22000);assert.equal(h.frames,0)}finally{if(prev===undefined)delete globalThis.document;else globalThis.document=prev}});
test("initial tall-front state has literal hidden identities and no selected target",()=>{const restore=installDocument();try{const{api}=renderAt();const s=api.inspect();assert.equal(s.analysis.hiddenCount,2);assert.equal(s.selected,null);assert.equal(s.target,-1);assert.equal(api.elements.bayNodes.filter(node=>node.classList.contains("occluded")).length,s.analysis.hiddenCount);assert.equal([...api.elements.objectButtons.values()].filter(node=>node.classList.contains("covers-rear")).length,2);for(const id of s.analysis.hidden)assert.equal(api.elements.objectButtons.get(id).classList.contains("hidden"),true)}finally{restore()}});
test("one swap is an involution and every arrangement remains reversible",()=>{const restore=installDocument();try{const{h,api}=renderAt({reducedMotion:true}),before=api.inspect().positions;assert.equal(api.swapSlots(0,1),true);h.runMs(38);assert.equal(api.inspect().moves,1);assert.equal(api.swapSlots(0,1),true);h.runMs(38);assert.deepEqual(api.inspect().positions,before);assert.equal(api.inspect().moves,2)}finally{restore()}});
test("captured touch drag swaps occupied shelf positions in one gesture",()=>{const restore=installDocument();try{const{h,api}=renderAt({reducedMotion:true}),id=api.inspect().positions[0],button=api.elements.objectButtons.get(id),view=document.defaultView,pointerId=8;button.dispatchEvent(eventWith("pointerdown",{pointerId,clientX:70,clientY:145}));assert.equal(api.inspect().drag.id,id);view.dispatchEvent(eventWith("pointermove",{pointerId,clientX:195,clientY:147}));assert.equal(api.inspect().target,1);view.dispatchEvent(eventWith("pointerup",{pointerId,clientX:195,clientY:147}));assert.equal(api.inspect().positions[1],id);assert.equal(api.inspect().snapStage,1);h.runMs(38);assert.equal(api.inspect().busy,false)}finally{restore()}});
test("release outside cancels and preserves exact permutation",()=>{const restore=installDocument();try{const{api}=renderAt({reducedMotion:true}),before=api.inspect().positions,id=before[0],view=document.defaultView;api.elements.objectButtons.get(id).dispatchEvent(eventWith("pointerdown",{pointerId:3}));view.dispatchEvent(eventWith("pointermove",{pointerId:3,clientX:-20,clientY:-20}));view.dispatchEvent(eventWith("pointerup",{pointerId:3,clientX:-20,clientY:-20}));assert.deepEqual(api.inspect().positions,before);assert.equal(api.inspect().moves,0)}finally{restore()}});
test("keyboard arrows and zero-detail slot activation share exact swaps and focus",()=>{const restore=installDocument();try{const{h,api}=renderAt({reducedMotion:true}),id=api.inspect().positions[0],button=api.elements.objectButtons.get(id);button.focus();button.dispatchEvent(eventWith("keydown",{key:"ArrowRight"}));assert.equal(api.inspect().positions[1],id);h.runMs(38);const moved=api.inspect().positions[1];api.elements.objectButtons.get(moved).dispatchEvent(eventWith("click",{detail:0}));api.elements.slotButtons[0].dispatchEvent(eventWith("click",{detail:0}));h.runMs(38);assert.equal(api.inspect().positions[0],id);assert.equal(document.activeElement,button)}finally{restore()}});
test("balanced-hidden and unobscured-unbalanced stay nonterminal and visibly distinct",()=>{const restore=installDocument();try{const task=taskAt(0),e=enumerate(task),{api}=renderAt({task,reducedMotion:true});api.applyPositions(e.balancedHidden[0]);let state=api.inspect();assert.equal(state.analysis.difference,0);assert.ok(state.analysis.hiddenCount>0);assert.equal(state.done,false);assert.equal(api.elements.beam.className,"shb-beam balanced");assert.equal(api.elements.bayNodes.filter(node=>node.classList.contains("occluded")).length,state.analysis.hiddenCount);api.applyPositions(e.visibleUnbalanced[0]);state=api.inspect();assert.ok(state.analysis.difference>0);assert.equal(state.analysis.hiddenCount,0);assert.equal(state.done,false);assert.equal(api.elements.bayNodes.some(node=>node.classList.contains("occluded")),false);assert.match(api.elements.beam.className,/heavy-(?:left|right)/)}finally{restore()}});
test("signed heavy marker points to each physical side and zero removes it",()=>{const restore=installDocument();try{const task=taskAt(0),e=enumerate(task),{api}=renderAt({task,reducedMotion:true}),signed=e.visibleUnbalanced.map(positions=>({positions,moment:positions.reduce((sum,id,index)=>sum+task.items.find(item=>item.id===id).weight*task.slots[index].column,0)})),left=signed.find(row=>row.moment<0),right=signed.find(row=>row.moment>0),zero=e.balancedHidden[0];api.applyPositions(left.positions);assert.equal(api.elements.beam.className,"shb-beam heavy-left");assert.ok(Number(api.elements.beam.style.transform.match(/-?\d+(?:\.\d+)?/)[0])<0);api.applyPositions(right.positions);assert.equal(api.elements.beam.className,"shb-beam heavy-right");assert.ok(Number(api.elements.beam.style.transform.match(/-?\d+(?:\.\d+)?/)[0])>0);api.applyPositions(zero);assert.equal(api.elements.beam.className,"shb-beam balanced");assert.equal(api.elements.beam.style.transform,"rotate(0deg)")}finally{restore()}});
test("success occurs only after a real snapped exchange and commits once",()=>{const restore=installDocument();try{const task=taskAt(0),solution=enumerate(task).valid[0],near=[...solution];let pair=null;for(let a=0;a<6&&!pair;a++)for(let b=a+1;b<6;b++){const trial=[...solution];[trial[a],trial[b]]=[trial[b],trial[a]];if(!assess(task,trial).success){near.splice(0,6,...trial);pair=[a,b];break}}const{h,api}=renderAt({task,reducedMotion:true});api.applyPositions(near);assert.equal(api.inspect().analysis.success,false);assert.equal(api.swapSlots(pair[0],pair[1]),true);assert.equal(h.finishes.length,0);h.runMs(38);assert.equal(api.inspect().analysis.success,true);assert.equal(api.inspect().done,true);assert.equal(h.finishes.length,0);h.runMs(60);assert.deepEqual(h.finishes.map(x=>[x.correct,x.result.outcome]),[[true,"success"]]);h.trigger();assert.equal(h.finishes.length,1)}finally{restore()}});
test("timeout retains exact arrangement, difference, hidden identities, and moves once",()=>{const restore=installDocument();try{const{h,api}=renderAt({reducedMotion:true});api.swapSlots(0,1);h.runMs(38);const before=api.inspect();h.trigger();assert.equal(h.finishes.length,1);const finish=h.finishes[0];assert.deepEqual([finish.correct,finish.result.outcome],[false,"timeout"]);assert.deepEqual(finish.result.state,{positions:before.positions,moves:before.moves});assert.deepEqual(finish.result.analysis.hidden,before.analysis.hidden);assert.equal(finish.result.analysis.difference,before.analysis.difference);h.trigger();assert.equal(h.finishes.length,1)}finally{restore()}});
test("visible second ticker is tracked, bounded, and stops at zero",()=>{const restore=installDocument();try{const{h,api}=renderAt();assert.equal(api.inspect().remaining,22);h.runMs(1000);assert.equal(api.inspect().remaining,21);h.runAll();assert.equal(api.inspect().remaining,0);assert.equal(h.frames,0)}finally{restore()}});
test("plain JSON mid-arrangement resume validates and reproduces exact analysis",async()=>{const restore=installDocument();try{const{h,api}=renderAt({index:1,reducedMotion:true});api.swapSlots(0,2);h.runMs(38);const saved=JSON.parse(JSON.stringify(api.snapshotTask())),before=api.inspect(),fresh=await importGame(`resume-${Date.now()}`),next=harness({reducedMotion:true});assert.deepEqual(fresh.validate(saved),[]);fresh.render(saved,next.context);const after=next.qa[ID].inspect();assert.deepEqual(after.positions,before.positions);assert.equal(after.moves,before.moves);assert.deepEqual(after.analysis,before.analysis)}finally{restore()}});
test("reduced mode owns a nonzero snap and static nonzero finish without frames",()=>{const restore=installDocument();try{const task=taskAt(0),solution=enumerate(task).valid[0],near=[...solution];let pair=null;for(let a=0;a<6&&!pair;a++)for(let b=a+1;b<6;b++){const trial=[...solution];[trial[a],trial[b]]=[trial[b],trial[a]];if(!assess(task,trial).success){near.splice(0,6,...trial);pair=[a,b];break}}const{h,api}=renderAt({task,reducedMotion:true});api.applyPositions(near);api.swapSlots(pair[0],pair[1]);assert.equal(api.inspect().snapStage,1);assert.ok(h.pending.some(j=>j.active&&j.ms===38));assert.equal(h.frames,0);h.runMs(38);assert.ok(h.pending.some(j=>j.active&&j.ms===60));h.runMs(60);assert.equal(h.finishes.length,1)}finally{restore()}});
test("dispose during snap clears tick, stage, deadline, listeners, QA, and late finish",()=>{const restore=installDocument();try{const{h,api}=renderAt();api.swapSlots(0,1);assert.ok(h.pendingCount>=2);h.dispose();h.runAll();h.trigger();assert.equal(h.qa[ID],undefined);assert.equal(h.pendingCount,0);assert.equal(h.listeners,0);assert.deepEqual(h.finishes,[]);assert.equal(api.inspect().disposed,true)}finally{restore()}});
test("real runtime disposal leaves no shelf work",async()=>{const restore=installDocument(),prev=globalThis.cancelAnimationFrame;globalThis.cancelAnimationFrame=id=>clearTimeout(id);try{const qa={},finishes=[],host=document.createElement("div"),runtime=createGameRuntime({host,qa,reducedMotion:true,viewport:{width:393,height:852,dpr:3},onFinish:(correct,result)=>finishes.push({correct,result})});game.render(taskAt(0),runtime.context);qa[ID].swapSlots(0,1);runtime.dispose();await delay(180);assert.equal(qa[ID],undefined);assert.deepEqual(finishes,[]);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{restore();if(prev===undefined)delete globalThis.cancelAnimationFrame;else globalThis.cancelAnimationFrame=prev}});
test("300 cold renders stay finite with fixed objects, slots, quantities, and no frames",()=>{const restore=installDocument();try{let latest;const start=performance.now();for(let i=0;i<300;i++){latest?.h.dispose();latest=renderAt({index:i%3,reducedMotion:i%2===0})}assert.ok(performance.now()-start<4000);assert.equal(latest.api.elements.objectButtons.size,6);assert.equal(latest.api.elements.slotButtons.length,6);assert.equal(latest.api.elements.readout.children.length,3);assert.equal(latest.h.frames,0);latest.h.dispose()}finally{restore()}});
test("source is ownerDocument-only, tracked, offline, frame/audio/emoji-free, and cue-free",()=>{assert.match(moduleSource,/context\.host\?\.ownerDocument/);assert.doesNotMatch(moduleSource,/\bdocument\.createElement\s*\(/);assert.doesNotMatch(moduleSource,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(moduleSource,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|HTMLAudioElement)\b/);assert.doesNotMatch(moduleSource,/[\p{Extended_Pictographic}]/u);assert.doesNotMatch(moduleSource,/data-(?:answer|correct|target|solution)/)});
