import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";
const moduleUrl=new URL("../src/games/timing-three-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8"),importGame=async tag=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n//${tag}`).toString("base64")}`)).default,game=await importGame("primary"),ID="timing-three-v1",PROMPT="体内時計で3秒を測って",HELP="スタート後、3秒だと思ったらタップ。",COUNTDOWN_HELP="3・2・1のあと、自動で計測が始まります。",RUNNING_HELP="数字は出ません。己を信じて。";
const published=()=>({kind:"timing",prompt:PROMPT,help:HELP,duration:9000});
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}add(...values){values.forEach(value=>this.values.add(value));this.owner._className=[...this.values].join(" ")}}
class FakeElement extends EventTarget{constructor(tag,ownerDocument){super();this.tagName=tag.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.attributes=new Map();this.classList=new FakeClassList(this);this._className="";this.textContent="";this.disabled=false;this.hidden=false;this.type="";this.style={}}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}append(...nodes){this.children.push(...nodes)}setAttribute(key,value){this.attributes.set(key,String(value))}focus(){this.ownerDocument.activeElement=this}getBoundingClientRect(){return{left:0,top:0,width:360,height:56,right:360,bottom:56}}}
class FakeDocument{constructor(){this.activeElement=null;this.created=[]}createElement(tag){const node=new FakeElement(tag,this);this.created.push(node);return node}}
function harness({reducedMotion=false}={}){const document=new FakeDocument(),host=new FakeElement("div",document),qa={},controller=new AbortController(),jobs=[],listeners=[],finishes=[];let nowValue=0,disposed=false,deadline={active:false,ms:0,fn:null};const context={host,signal:controller.signal,reducedMotion,viewport:{width:390,height:844,dpr:3},qa,now:()=>nowValue,later:(fn,ms)=>{const job={fn,ms,active:true};jobs.push(job);return()=>job.active=false},frame:()=>{throw new Error("timing-three must not frame")},listen:(target,type,fn,options)=>{target.addEventListener(type,fn,options);const item={target,type,fn,options,active:true};listeners.push(item);return()=>{if(item.active){item.active=false;target.removeEventListener(type,fn,options)}}},setDeadline:(ms,fn)=>{deadline={active:true,ms,fn}},finish:(correct,result)=>{if(!disposed)finishes.push({correct,result})}};controller.signal.addEventListener("abort",()=>{disposed=true;jobs.forEach(job=>job.active=false);deadline.active=false},{once:true});return{context,host,qa,document,finishes,setNow:value=>nowValue=value,run(ms){nowValue=ms;const job=jobs.find(v=>v.active&&v.ms===ms);assert.ok(job);job.active=false;job.fn()},triggerDeadline(){if(deadline.active){deadline.active=false;deadline.fn()}},get deadline(){return deadline},get activeJobs(){return jobs.filter(v=>v.active).length},get activeListeners(){return listeners.filter(v=>v.active).length},dispose(){controller.abort();listeners.forEach(v=>{if(v.active)v.target.removeEventListener(v.type,v.fn,v.options);v.active=false})}}}
function click(node,detail=1){const event=new Event("click",{bubbles:true,cancelable:true});Object.defineProperty(event,"detail",{value:detail});node.dispatchEvent(event)}
function install(){const prior={document:globalThis.document,requestAnimationFrame:globalThis.requestAnimationFrame,cancelAnimationFrame:globalThis.cancelAnimationFrame};globalThis.document={createElement(){throw new Error("global document")}};globalThis.requestAnimationFrame=()=>1;globalThis.cancelAnimationFrame=()=>{};return()=>{for(const [key,value] of Object.entries(prior)){if(value===undefined)delete globalThis[key];else globalThis[key]=value}}}
const begin=h=>{h.run(1000);h.run(2000);h.run(3000);return h.qa[ID]};

test("metadata is the published v1.0 identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.0",tier:2,flavor:"wild",step:1,family:"timing-three",category:"timing"}));
test("1000 generations preserve exact four-field factory JSON without helper reads",()=>{let calls=0;for(let i=0;i<1000;i++){const actual=game.generate(new Proxy({},{get(){calls++;throw new Error("helper")}})),expected=published();assert.deepEqual(actual,expected);assert.equal(JSON.stringify(actual),JSON.stringify(expected));assert.deepEqual(game.validate(actual),[])}assert.equal(calls,0)});
test("validator rejects retunes and especially added target/tolerance fields",()=>{const mutations=[v=>v.kind="stopwatch",v=>v.prompt+="!",v=>v.help="changed",v=>v.duration=9001,v=>v.targetSeconds=3,v=>v.toleranceMs=650,v=>v.elapsed=0];for(const mutate of mutations){const value=published();mutate(value);assert.ok(game.validate(value).length)}for(const value of [null,[],"timing"])assert.ok(game.validate(value).length)});
test("render owns DOM, starts disabled 3, and resolves exact renderer defaults",()=>{const restore=install();try{const h=harness();game.render(published(),h.context);const state=h.qa[ID].inspect();assert.ok(h.document.created.every(node=>node.ownerDocument===h.document));assert.deepEqual({phase:state.phase,text:state.buttonText,disabled:state.buttonDisabled,status:state.status,jobs:h.activeJobs,timer:state.timerVisible,seconds:state.seconds,target:state.target,tolerance:state.tolerance,deadline:state.internalDeadline},{phase:"COUNTDOWN_3",text:"3",disabled:true,status:COUNTDOWN_HELP,jobs:3,timer:false,seconds:3,target:3000,tolerance:650,deadline:5200})}finally{restore()}});
test("normal and reduced exact 3-2-1 countdown is nonzero and input-inert",()=>{const restore=install();try{for(const reducedMotion of [false,true]){const h=harness({reducedMotion});game.render(published(),h.context);const api=h.qa[ID];click(api.elements.button,0);h.run(1000);assert.equal(api.inspect().buttonText,"2");click(api.elements.button,0);h.run(2000);assert.equal(api.inspect().buttonText,"1");assert.equal(api.inspect().phase,"COUNTDOWN_1");assert.equal(h.finishes.length,0);assert.equal(h.deadline.active,false)}}finally{restore()}});
test("begin at 3000 hides elapsed, focuses exact CTA, and books 5200 only",()=>{const restore=install();try{for(const reducedMotion of [false,true]){const h=harness({reducedMotion});game.render(published(),h.context);const state=begin(h).inspect();assert.equal(state.phase,"RUNNING");assert.equal(state.started,3000);assert.equal(state.buttonText,"3秒だと思ったら、タップ！");assert.equal(state.status,RUNNING_HELP);assert.equal(state.focused,true);assert.equal(state.outcomeHidden,true);assert.equal(h.deadline.ms,5200);assert.equal(h.activeJobs,0);assert.doesNotMatch(`${state.buttonText} ${state.status}`,/\d+\.\d+|経過|残り/)}}finally{restore()}});
test("post-begin CTA is pinned to exact current renderer default copy",()=>{const restore=install();try{const h=harness();game.render(published(),h.context);const api=begin(h);assert.equal(api.elements.button.textContent,"3秒だと思ったら、タップ！");assert.match(source,/button\.textContent=`\$\{seconds\}秒だと思ったら、タップ！`/)}finally{restore()}});
test("inclusive default 650ms boundaries at 2.35 and 3.65 succeed",()=>{const restore=install();try{for(const elapsed of [2350,3650]){const h=harness();game.render(published(),h.context);const api=begin(h);h.setNow(3000+elapsed);api.stop();assert.deepEqual(h.finishes,[{correct:true,result:{reactionMs:elapsed,quality:1-650/(650*2.6),detail:`あなたの3秒は ${(elapsed/1000).toFixed(2)} 秒でした。`}}])}}finally{restore()}});
test("early 2.00 result uses default denominator exactly",()=>{const restore=install();try{const h=harness();game.render(published(),h.context);const api=begin(h);h.setNow(5000);api.stop();assert.equal(api.inspect().phase,"EARLY");assert.deepEqual(h.finishes,[{correct:false,result:{reactionMs:2000,quality:1-1000/(650*2.6),detail:"あなたの3秒は 2.00 秒でした。"}}])}finally{restore()}});
test("win 3.00 result is exact and locks",()=>{const restore=install();try{const h=harness();game.render(published(),h.context);const api=begin(h);h.setNow(6000);click(api.elements.button);assert.deepEqual(h.finishes,[{correct:true,result:{reactionMs:3000,quality:1,detail:"あなたの3秒は 3.00 秒でした。"}}]);api.stop();h.triggerDeadline();assert.equal(h.finishes.length,1);assert.equal(api.inspect().buttonDisabled,true)}finally{restore()}});
test("late 4.00 result uses default denominator exactly",()=>{const restore=install();try{const h=harness();game.render(published(),h.context);const api=begin(h);h.setNow(7000);api.stop();assert.equal(api.inspect().phase,"LATE");assert.deepEqual(h.finishes,[{correct:false,result:{reactionMs:4000,quality:1-1000/(650*2.6),detail:"あなたの3秒は 4.00 秒でした。"}}])}finally{restore()}});
test("quality clamps to zero while preserving exact detail",()=>{const restore=install();try{const h=harness();game.render(published(),h.context);const api=begin(h);h.setNow(3000);api.stop();assert.deepEqual(h.finishes,[{correct:false,result:{reactionMs:0,quality:0,detail:"あなたの3秒は 0.00 秒でした。"}}])}finally{restore()}});
test("timeout is default target plus 2200 with exact five-second copy",()=>{const restore=install();try{const h=harness();game.render(published(),h.context);const api=begin(h);assert.equal(h.deadline.ms,5200);h.setNow(8200);h.triggerDeadline();assert.equal(api.inspect().phase,"TIMEOUT");assert.deepEqual(h.finishes,[{correct:false,result:{detail:"5秒を超えました。時空から戻ってください。"}}]);api.stop();assert.equal(h.finishes.length,1)}finally{restore()}});
test("pointer and native zero-detail keyboard click share stop",()=>{const restore=install();try{for(const detail of [1,0]){const h=harness();game.render(published(),h.context);const api=begin(h);h.setNow(6000);click(api.elements.button,detail);assert.equal(h.finishes[0].correct,true);assert.equal(h.finishes[0].result.reactionMs,3000)}assert.match(source,/:focus-visible/)}finally{restore()}});
test("plain JSON fresh resume retains absent default fields and exact result",async()=>{const restore=install();try{const saved=JSON.parse(JSON.stringify(game.generate({}))),fresh=await importGame(`resume-${Date.now()}`),h=harness({reducedMotion:true});assert.deepEqual(Object.keys(saved),["kind","prompt","help","duration"]);fresh.render(saved,h.context);begin(h);h.setNow(6000);h.qa[ID].stop();assert.deepEqual(h.finishes,[{correct:true,result:{reactionMs:3000,quality:1,detail:"あなたの3秒は 3.00 秒でした。"}}])}finally{restore()}});
test("dispose during countdown and running clears all work",()=>{const restore=install();try{for(const running of [false,true]){const h=harness();game.render(published(),h.context);if(running)begin(h);h.dispose();assert.equal(h.activeJobs,0);assert.equal(h.deadline.active,false);assert.equal(h.activeListeners,0);assert.equal(h.qa[ID],undefined);assert.equal(h.finishes.length,0)}}finally{restore()}});
test("real kernel disposal leaves no surviving work",async()=>{const restore=install();try{const document=new FakeDocument(),host=new FakeElement("div",document),finishes=[],runtime=createGameRuntime({host,onFinish:(...args)=>finishes.push(args),reducedMotion:true,viewport:{width:390,height:844,dpr:3},qa:{}});game.render(published(),runtime.context);runtime.dispose();await delay(100);assert.equal(finishes.length,0);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{restore()}});
test("generation and validation are bounded across 10000 tasks",()=>{for(let i=0;i<10000;i++)assert.deepEqual(game.validate(game.generate({})),[])});
test("source is tracked, frame-free, and has no forbidden paths",()=>{assert.doesNotMatch(source,/\bdocument\.createElement\b/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|webkitAudioContext|new Audio|localStorage|sessionStorage)\b/);assert.match(source,/context\.later\(\(\)=>setCount\(2\),1000\)/);assert.match(source,/context\.later\(\(\)=>setCount\(1\),2000\)/);assert.match(source,/context\.later\(begin,3000\)/);assert.match(source,/context\.setDeadline\(internalDeadline/);assert.doesNotMatch(source,/context\.frame/);assert.match(source,/context\.listen/)});
