import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {performance} from "node:perf_hooks";
import {setTimeout as delay} from "node:timers/promises";
import {createGameRuntime} from "../src/game-kernel.js";
const moduleUrl=new URL("../src/games/timing-five-v1.js",import.meta.url),source=await readFile(moduleUrl,"utf8"),importGame=async tag=>(await import(`data:text/javascript;base64,${Buffer.from(`${source}\n//${tag}`).toString("base64")}`)).default,game=await importGame("primary"),ID="timing-five-v1",PROMPT="体内時計で5秒を測って",HELP="スタート後、5秒だと思ったらタップ。",COUNTDOWN_HELP="3・2・1のあと、自動で計測が始まります。",RUNNING_HELP="数字は出ません。己を信じて。";
const published=()=>({kind:"timing",prompt:PROMPT,help:HELP,targetSeconds:5,toleranceMs:800,duration:12000});
class FakeClassList{constructor(owner){this.owner=owner;this.values=new Set()}reset(value){this.values=new Set(String(value||"").split(/\s+/).filter(Boolean))}add(...values){values.forEach(value=>this.values.add(value));this.sync()}remove(...values){values.forEach(value=>this.values.delete(value));this.sync()}contains(value){return this.values.has(value)}sync(){this.owner._className=[...this.values].join(" ")}}
class FakeElement extends EventTarget{constructor(tag,ownerDocument){super();this.tagName=tag.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.attributes=new Map();this.classList=new FakeClassList(this);this._className="";this.textContent="";this.disabled=false;this.hidden=false;this.type="";this.style={}}set className(value){this._className=String(value);this.classList.reset(value)}get className(){return this._className}append(...nodes){this.children.push(...nodes)}setAttribute(key,value){this.attributes.set(key,String(value))}getAttribute(key){return this.attributes.get(key)??null}focus(){this.ownerDocument.activeElement=this}getBoundingClientRect(){return{left:0,top:0,width:360,height:56,right:360,bottom:56}}}
class FakeDocument{constructor(){this.activeElement=null;this.created=[]}createElement(tag){const node=new FakeElement(tag,this);this.created.push(node);return node}}
function harness({reducedMotion=false,initialNow=0}={}){const document=new FakeDocument(),host=new FakeElement("div",document),qa={},controller=new AbortController(),jobs=[],listeners=[],finishes=[];let nowValue=initialNow,disposed=false,deadline={active:false,ms:0,fn:null};const context={host,signal:controller.signal,reducedMotion,viewport:{width:390,height:844,dpr:3},qa,now:()=>nowValue,later:(fn,ms)=>{const job={fn,ms,active:true};jobs.push(job);return()=>job.active=false},frame:()=>{throw new Error("timing-five must not book a frame")},listen:(target,type,fn,options)=>{target.addEventListener(type,fn,options);const item={target,type,fn,options,active:true};listeners.push(item);return()=>{if(item.active){item.active=false;target.removeEventListener(type,fn,options)}}},setDeadline:(ms,fn)=>{deadline={active:true,ms,fn}},finish:(correct,result)=>{if(!disposed)finishes.push({correct,result})}};controller.signal.addEventListener("abort",()=>{disposed=true;jobs.forEach(job=>job.active=false);deadline.active=false},{once:true});return{context,host,qa,document,finishes,setNow:value=>nowValue=value,run(ms,at=ms){nowValue=at;const job=jobs.find(value=>value.active&&value.ms===ms);assert.ok(job,`missing ${ms}ms stage`);job.active=false;job.fn()},triggerDeadline(){if(deadline.active){deadline.active=false;deadline.fn()}},get deadline(){return deadline},get activeJobs(){return jobs.filter(job=>job.active).length},get activeListeners(){return listeners.filter(listener=>listener.active).length},dispose(){controller.abort();listeners.forEach(item=>{if(item.active)item.target.removeEventListener(item.type,item.fn,item.options);item.active=false})}}}
function click(node,detail=1){const event=new Event("click",{bubbles:true,cancelable:true});Object.defineProperty(event,"detail",{value:detail});node.dispatchEvent(event)}
function install(){const previous={document:globalThis.document,requestAnimationFrame:globalThis.requestAnimationFrame,cancelAnimationFrame:globalThis.cancelAnimationFrame};globalThis.document={createElement(){throw new Error("global document used")}};globalThis.requestAnimationFrame=()=>1;globalThis.cancelAnimationFrame=()=>{};return()=>{for(const [key,value] of Object.entries(previous)){if(value===undefined)delete globalThis[key];else globalThis[key]=value}}}
const begin=h=>{h.run(1000,1000);h.run(2000,2000);h.run(3000,3000);return h.qa[ID]};

test("metadata is the published stable identity",()=>assert.deepEqual(game.metadata,{id:ID,introducedIn:"1.0",tier:2,flavor:"wild",step:1,family:"timing-five",category:"timing"}));
test("generation is byte-equivalent to the current app.js factory and ignores helpers",()=>{let calls=0;for(let i=0;i<1000;i++){const actual=game.generate(new Proxy({},{get(){calls++;throw new Error("helper must not be read")}})),expected=published();assert.deepEqual(actual,expected);assert.equal(JSON.stringify(actual),JSON.stringify(expected));assert.deepEqual(game.validate(actual),[])}assert.equal(calls,0)});
test("validator rejects every semantic retune and extra renderer state",()=>{const mutations=[task=>task.kind="stopwatch",task=>task.prompt+="!",task=>task.help="changed",task=>task.targetSeconds=4,task=>task.toleranceMs=801,task=>task.duration=10200,task=>task.elapsed=0];for(const mutate of mutations){const task=published();mutate(task);assert.ok(game.validate(task).length)}for(const task of [null,[],"timing"])assert.ok(game.validate(task).length)});
test("render is ownerDocument-only with exact disabled 3 and hidden timer CSS",()=>{const restore=install();try{const h=harness();game.render(published(),h.context);const api=h.qa[ID],{button,status}=api.elements;assert.ok(h.document.created.length>=7);assert.ok(h.document.created.every(node=>node.ownerDocument===h.document));assert.equal(api.inspect().phase,"COUNTDOWN_3");assert.equal(button.textContent,"3");assert.equal(button.disabled,true);assert.equal(status.textContent,COUNTDOWN_HELP);assert.equal(h.activeJobs,3);assert.deepEqual(h.deadline,{active:false,ms:0,fn:null});assert.match(source,/timer-track/);assert.equal(api.inspect().timerVisible,false)}finally{restore()}});
test("countdown advances 3 to 2 at 1000 and 1 at 2000 without accepting input",()=>{const restore=install();try{for(const reducedMotion of [false,true]){const h=harness({reducedMotion});game.render(published(),h.context);const api=h.qa[ID],button=api.elements.button;click(button,0);assert.equal(h.finishes.length,0);h.run(1000,1000);assert.equal(api.inspect().phase,"COUNTDOWN_2");assert.equal(button.textContent,"2");click(button,0);assert.equal(h.finishes.length,0);h.run(2000,2000);assert.equal(api.inspect().phase,"COUNTDOWN_1");assert.equal(button.textContent,"1");assert.equal(button.disabled,true);assert.equal(h.deadline.active,false)}}finally{restore()}});
test("begin is exact at 3000, hides elapsed, focuses stop, and books only 7200ms",()=>{const restore=install();try{for(const reducedMotion of [false,true]){const h=harness({reducedMotion});game.render(published(),h.context);const api=begin(h),state=api.inspect(),button=api.elements.button;assert.equal(state.phase,"RUNNING");assert.equal(state.started,3000);assert.equal(button.disabled,false);assert.equal(button.textContent,"ストップ！");assert.equal(state.status,RUNNING_HELP);assert.equal(state.focused,true);assert.equal(h.document.activeElement,button);assert.equal(h.deadline.ms,7200);assert.equal(h.deadline.active,true);assert.equal(h.activeJobs,0);assert.doesNotMatch(`${button.textContent} ${state.status}`,/\d+\.\d+|経過|残り/);assert.equal(state.outcomeHidden,true)}}finally{restore()}});
test("exact 800ms early and late tolerance boundaries are inclusive",()=>{const restore=install();try{for(const elapsed of [4200,5800]){const h=harness();game.render(published(),h.context);const api=begin(h);h.setNow(3000+elapsed);click(api.elements.button);assert.equal(h.finishes.length,1);assert.equal(h.finishes[0].correct,true);assert.equal(h.finishes[0].result.reactionMs,elapsed);assert.equal(h.finishes[0].result.quality,1-800/(800*2.6));assert.equal(h.finishes[0].result.detail,`あなたの5秒は ${(elapsed/1000).toFixed(2)} 秒でした。`)}}finally{restore()}});
test("early stop uses real elapsed, exact quality, and two-decimal detail",()=>{const restore=install();try{const h=harness();game.render(published(),h.context);const api=begin(h);h.setNow(7199.5);api.stop();const result=h.finishes[0];assert.equal(result.correct,false);assert.equal(api.inspect().phase,"EARLY");assert.deepEqual(result.result,{reactionMs:4200,quality:1-800.5/(800*2.6),detail:"あなたの5秒は 4.20 秒でした。"})}finally{restore()}});
test("five-second stop is exact success and locks all later input",()=>{const restore=install();try{const h=harness();game.render(published(),h.context);const api=begin(h);h.setNow(8000);click(api.elements.button,1);assert.deepEqual(h.finishes,[{correct:true,result:{reactionMs:5000,quality:1,detail:"あなたの5秒は 5.00 秒でした。"}}]);assert.equal(api.inspect().phase,"WIN");assert.equal(api.elements.button.disabled,true);api.stop();h.triggerDeadline();assert.equal(h.finishes.length,1)}finally{restore()}});
test("late stop remains incorrect with exact unclamped formula and detail",()=>{const restore=install();try{const h=harness();game.render(published(),h.context);const api=begin(h);h.setNow(9000);api.stop();assert.equal(api.inspect().phase,"LATE");assert.deepEqual(h.finishes,[{correct:false,result:{reactionMs:6000,quality:1-1000/(800*2.6),detail:"あなたの5秒は 6.00 秒でした。"}}])}finally{restore()}});
test("quality clamps to zero without changing reaction or two-decimal output",()=>{const restore=install();try{const h=harness();game.render(published(),h.context);const api=begin(h);h.setNow(3000);api.stop();assert.deepEqual(h.finishes,[{correct:false,result:{reactionMs:0,quality:0,detail:"あなたの5秒は 0.00 秒でした。"}}])}finally{restore()}});
test("internal timeout is 7200ms after begin with exact seven-second copy",()=>{const restore=install();try{const h=harness();game.render(published(),h.context);const api=begin(h);assert.equal(h.deadline.ms,7200);h.setNow(10200);h.triggerDeadline();assert.equal(api.inspect().phase,"TIMEOUT");assert.deepEqual(h.finishes,[{correct:false,result:{detail:"7秒を超えました。時空から戻ってください。"}}]);api.stop();assert.equal(h.finishes.length,1)}finally{restore()}});
test("pointer and native zero-detail keyboard clicks share the stop path",()=>{const restore=install();try{for(const detail of [1,0]){const h=harness();game.render(published(),h.context);const api=begin(h);h.setNow(8000);click(api.elements.button,detail);assert.equal(h.finishes[0].correct,true);assert.equal(h.finishes[0].result.reactionMs,5000)}assert.match(source,/:focus-visible/)}finally{restore()}});
test("plain JSON resume in a fresh module restarts exact countdown and proof",async()=>{const restore=install();try{const saved=JSON.parse(JSON.stringify(game.generate({}))),fresh=await importGame(`resume-${Date.now()}`),h=harness({reducedMotion:true});assert.deepEqual(fresh.validate(saved),[]);fresh.render(saved,h.context);assert.equal(h.qa[ID].inspect().taskJSON,JSON.stringify(saved));begin(h);h.setNow(8000);h.qa[ID].stop();assert.deepEqual(h.finishes,[{correct:true,result:{reactionMs:5000,quality:1,detail:"あなたの5秒は 5.00 秒でした。"}}])}finally{restore()}});
test("dispose during countdown and running clears stages, deadline, listeners, QA, and finish",()=>{const restore=install();try{for(const running of [false,true]){const h=harness({reducedMotion:true});game.render(published(),h.context);if(running)begin(h);assert.ok(h.activeListeners>0);h.dispose();assert.equal(h.activeJobs,0);assert.equal(h.deadline.active,false);assert.equal(h.activeListeners,0);assert.equal(h.qa[ID],undefined);h.triggerDeadline();assert.equal(h.finishes.length,0)}}finally{restore()}});
test("real kernel disposal leaves no surviving timing work",async()=>{const restore=install();try{const document=new FakeDocument(),host=new FakeElement("div",document),finishes=[],runtime=createGameRuntime({host,onFinish:(...args)=>finishes.push(args),viewport:{width:390,height:844,dpr:3},reducedMotion:true,qa:{}});game.render(published(),runtime.context);runtime.dispose();await delay(100);assert.equal(finishes.length,0);assert.deepEqual(runtime.inspect(),{disposed:true,finished:false,finishCalls:0,commits:0,timeouts:0,frames:0,listeners:0,aborted:true})}finally{restore()}});
test("generation and validation remain inside the interaction budget",()=>{const start=performance.now();for(let i=0;i<10000;i++){const task=game.generate({});assert.deepEqual(game.validate(task),[])}assert.ok(performance.now()-start<1000)});
test("source uses tracked nonzero stages with no clock display, frame, or forbidden paths",()=>{assert.doesNotMatch(source,/\bdocument\.createElement\b/);assert.doesNotMatch(source,/\b(?:setTimeout|setInterval|requestAnimationFrame|cancelAnimationFrame|addEventListener)\s*\(/);assert.doesNotMatch(source,/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon|AudioContext|webkitAudioContext|new Audio|localStorage|sessionStorage)\b/);assert.doesNotMatch(source,/\b(?:src|href)\s*=/);assert.match(source,/context\.later\(\(\)=>setCount\(2\),1000\)/);assert.match(source,/context\.later\(\(\)=>setCount\(1\),2000\)/);assert.match(source,/context\.later\(begin,3000\)/);assert.match(source,/context\.setDeadline\(INTERNAL_DEADLINE/);assert.doesNotMatch(source,/context\.frame/);assert.match(source,/context\.listen/)});
