import game from "../src/games/timing-mochi-pound-v1.js";
import {createGameRuntime} from "../src/game-kernel.js";

const params=new URLSearchParams(location.search),scene=params.get("scene")||"initial",reduced=params.get("motion")==="reduced",width=Number(params.get("width"))||393,deadlineOverride=Number(params.get("deadline"))||null;document.body.style.width=`${width}px`;
const task=structuredClone(game.generate()),host=document.querySelector("#challenge"),resultNode=document.querySelector("#result"),qa={},started=performance.now(),resourcesBefore=performance.getEntriesByType("resource").length,errors=[];let outcome=null;
addEventListener("error",event=>errors.push(String(event.error?.stack||event.message)));addEventListener("unhandledrejection",event=>errors.push(String(event.reason?.stack||event.reason)));
const runtime=createGameRuntime({host,qa,reducedMotion:reduced,viewport:{width,height:innerHeight,dpr:devicePixelRatio},onFinish:(correct,detail)=>{outcome={correct,detail};resultNode.textContent=`${correct?"完成":"終了"}・${detail.reason}`}}),context={...runtime.context};
if(deadlineOverride!==null){const owned=context.setDeadline;context.setDeadline=(_ms,fn)=>owned(deadlineOverride,fn)}
game.render(structuredClone(task),context);const api=qa[game.metadata.id];
if(scene!=="live")api.showScene(scene);
const report=()=>{const resources=performance.getEntriesByType("resource"),external=resources.filter(entry=>new URL(entry.name).origin!==location.origin),state=api.inspect(),board=document.querySelector(".tmp-board"),boardRect=board.getBoundingClientRect(),canvas=document.querySelector(".tmp-canvas"),canvasRect=canvas.getBoundingClientRect(),label=document.querySelector(".tmp-hint"),labelRect=label.getBoundingClientRect(),labelStyle=getComputedStyle(label);return{status:errors.length||external.length||document.body.scrollWidth>width?"fail":"pass",scene,reduced,width,elapsedMs:performance.now()-started,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio,bodyScrollWidth:document.body.scrollWidth,bodyScrollHeight:document.body.scrollHeight},task:structuredClone(task),game:state,runtime:runtime.inspect(),outcome:outcome?structuredClone(outcome):null,focused:document.activeElement===board,board:{left:boardRect.left,top:boardRect.top,width:boardRect.width,height:boardRect.height,bottom:boardRect.bottom},canvasRect:{left:canvasRect.left,top:canvasRect.top,width:canvasRect.width,height:canvasRect.height},fictionLabel:{text:label.textContent,left:labelRect.left,top:labelRect.top,right:labelRect.right,bottom:labelRect.bottom,width:labelRect.width,height:labelRect.height,display:labelStyle.display,visibility:labelStyle.visibility,opacity:labelStyle.opacity},resourcesAdded:resources.length-resourcesBefore,external:external.map(entry=>entry.name),errors:[...errors]}};
window.__TMP_FIXTURE__={game,task,qa,api,runtime,report,deadlineOverride};document.documentElement.dataset.ready="true";
