#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.."&&pwd);STAMP=$(date +%Y%m%d-%H%M%S);OUT=${1:-/tmp/agetest-timing-milk-pour-v1-audit-$STAMP};cd "$ROOT";[[ ! -e "$OUT" ]]||{ echo "output exists" >&2;exit 2;};mkdir -p "$OUT";node tools/qa-browser-lanes.mjs start audit >/dev/null
ready='(async()=>{for(let i=0;i<240;i++){if(window.__MILK_POUR_FIXTURE__&&document.documentElement.dataset.ready==="true")return true;await new Promise(r=>setTimeout(r,25))}throw Error("ready")})()';nav(){ local v=$1 s=$2 m=$3 w=$4 h=$5 live=${6:-0};node tools/qa-browser-lanes.mjs navigate audit "http://127.0.0.1:8862/test/timing-milk-pour-v1.fixture.html?variant=$v&scene=$s&motion=$m&width=$w&live=$live" "$w" "$h" 3 >/dev/null;node tools/qa-browser-lanes.mjs eval audit "$ready" >/dev/null;}
variants=(0 1 2 3);metrics=(393x852 402x874);motions=(normal reduced);scenes=(initial holding released after-1 after-2 good-foam underfill recoverable wiped overflow timeout)
for v in "${variants[@]}";do for metric in "${metrics[@]}";do w=${metric%x*};h=${metric#*x};for m in "${motions[@]}";do for s in "${scenes[@]}";do nav "$v" "$s" "$m" "$w" "$h";node tools/qa-browser-lanes.mjs eval audit 'window.__MILK_POUR_FIXTURE__.report()' >"$OUT/evidence-$v-$metric-$s-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/cup$v-$metric-$s-$m.png" >/dev/null;done;nav "$v" initial "$m" "$w" "$h" 1;node tools/qa-browser-lanes.mjs eval audit '(()=>{const f=window.__MILK_POUR_FIXTURE__,b=f.api.elements.pourButton;b.focus();document.body.classList.add("fixture-focus");return{focused:b===document.activeElement,state:f.api.inspect(),report:f.report()}})()' >"$OUT/focus-$v-$metric-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/focus-$v-$metric-$m.png" >/dev/null;done;done;done
for metric in 390x844 430x932;do w=${metric%x*};h=${metric#*x};for v in "${variants[@]}";do for m in "${motions[@]}";do for s in initial good-foam;do nav "$v" "$s" "$m" "$w" "$h";node tools/qa-browser-lanes.mjs eval audit 'window.__MILK_POUR_FIXTURE__.report()' >"$OUT/boundary-$v-$metric-$s-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/boundary-cup$v-$metric-$s-$m.png" >/dev/null;done;done;done;done
cue='(()=>{const f=window.__MILK_POUR_FIXTURE__,p=f.api.elements.pourButton,s=f.api.inspect();return{variant:f.variant,button:{text:p.textContent,answer:p.getAttribute("data-answer"),correct:p.getAttribute("data-correct"),width:p.getBoundingClientRect().width,height:p.getBoundingClientRect().height},state:s,task:f.task,report:f.report()}})()';for v in "${variants[@]}";do nav "$v" initial normal 402 874;node tools/qa-browser-lanes.mjs eval audit "$cue" >"$OUT/no-cue-$v.json";done
success='(async()=>{const f=window.__MILK_POUR_FIXTURE__,b=f.api.elements.pourButton,wait=ms=>new Promise(r=>setTimeout(r,ms)),fire=t=>b.dispatchEvent(new PointerEvent(t,{bubbles:true,cancelable:true,pointerId:81,pointerType:"touch",isPrimary:true}));fire("pointerdown");const holding=f.api.inspect();await wait(f.task.proof.releaseFromStep*f.task.quantumMs+40);fire("pointerup");const released=f.api.inspect();await wait(f.motion==="reduced"?430:600);const report=f.report();return{status:report.status,variant:f.variant,motion:f.motion,holding,released,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,targets:report.targets,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()'
for v in "${variants[@]}";do for m in "${motions[@]}";do nav "$v" initial "$m" 402 874 1;node tools/qa-browser-lanes.mjs eval audit "$success" >"$OUT/touch-success-$v-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/touch-success-$v-$m.png" >/dev/null;done;done
keyboard='(async()=>{const f=window.__MILK_POUR_FIXTURE__,b=f.api.elements.pourButton,wait=ms=>new Promise(r=>setTimeout(r,ms)),key=(t,k)=>b.dispatchEvent(new KeyboardEvent(t,{key:k,bubbles:true,cancelable:true}));b.focus();key("keydown"," ");const holding=f.api.inspect();await wait(f.task.proof.releaseFromStep*f.task.quantumMs+40);key("keyup"," ");const released=f.api.inspect();await wait(f.motion==="reduced"?430:600);const report=f.report();return{status:report.status,variant:f.variant,motion:f.motion,holding,released,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,focused:b===document.activeElement,targets:report.targets,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()';for pair in 0:normal 3:reduced;do v=${pair%:*};m=${pair#*:};nav "$v" initial "$m" 402 874 1;node tools/qa-browser-lanes.mjs eval audit "$keyboard" >"$OUT/keyboard-$v-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/keyboard-success-$v-$m.png" >/dev/null;done
overflowRetry='(async()=>{const f=window.__MILK_POUR_FIXTURE__,b=f.api.elements.pourButton,w=f.api.elements.wipeButton,wait=ms=>new Promise(r=>setTimeout(r,ms)),fire=t=>b.dispatchEvent(new PointerEvent(t,{bubbles:true,cancelable:true,pointerId:91,pointerType:"touch",isPrimary:true}));fire("pointerdown");await wait((f.task.proof.releaseToStep+1)*100+50);fire("pointerup");await wait(f.motion==="reduced"?350:450);const spill=f.api.inspect();w.click();const wiping=f.api.inspect();await wait(f.motion==="reduced"?140:250);const wiped=f.api.inspect();fire("pointerdown");await wait(f.task.proof.releaseFromStep*100+40);fire("pointerup");await wait(f.motion==="reduced"?430:600);const report=f.report();return{motion:f.motion,spill,wiping,wiped,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()';for m in "${motions[@]}";do nav 1 initial "$m" 402 874 1;node tools/qa-browser-lanes.mjs eval audit "$overflowRetry" >"$OUT/overflow-retry-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/overflow-retry-$m.png" >/dev/null;done
deadline='(async()=>{const f=window.__MILK_POUR_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms));f.api.showScene("recoverable");const before=f.api.inspect();f.runtime.context.setDeadline(180,f.api.timeout);await wait(500);const report=f.report();return{motion:f.motion,before,after:f.api.inspect(),runtime:f.runtime.inspect(),finishes:report.finishes,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors}})()';dispose='(async()=>{const f=window.__MILK_POUR_FIXTURE__,wait=ms=>new Promise(r=>setTimeout(r,ms));f.api.startHold();const state=f.api.inspect(),before=f.runtime.inspect();f.runtime.dispose();await wait(260);return{motion:f.motion,state,before,after:f.runtime.inspect(),disposedState:f.api.inspect(),qaPresent:Boolean(f.qa[f.game.metadata.id]),finishes:f.report().finishes}})()';for m in "${motions[@]}";do nav 2 initial "$m" 402 874 1;node tools/qa-browser-lanes.mjs eval audit "$deadline" >"$OUT/deadline-$m.json";node tools/qa-browser-lanes.mjs screenshot audit "$OUT/deadline-$m.png" >/dev/null;nav 2 initial "$m" 402 874 1;node tools/qa-browser-lanes.mjs eval audit "$dispose" >"$OUT/dispose-$m.json";done
perf='(async()=>{const f=window.__MILK_POUR_FIXTURE__,b=f.api.elements.pourButton,d=[],wait=ms=>new Promise(r=>setTimeout(r,ms));b.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:99,pointerType:"touch"}));let p=performance.now();await new Promise(resolve=>{const tick=n=>{d.push(n-p);p=n;if(d.length===90)resolve();else requestAnimationFrame(tick)};requestAnimationFrame(tick)});const state=f.api.inspect(),report=f.report(),runtime=f.runtime.inspect(),expected=f.motion==="normal"?1:0,result={status:d.length===90&&runtime.frames===expected&&!report.external.length&&!report.errors.length&&report.viewport.bodyScrollWidth<=report.width?"pass":"fail",motion:f.motion,frames:d.length,averageFrameMs:d.reduce((a,b)=>a+b,0)/d.length,maxFrameMs:Math.max(...d),gameOwnedFrames:runtime.frames,state,runtime,overflow:report.viewport.bodyScrollWidth>report.width,external:report.external,errors:report.errors};f.runtime.dispose();return result})()';for metric in "${metrics[@]}";do w=${metric%x*};h=${metric#*x};for m in "${motions[@]}";do nav 1 initial "$m" "$w" "$h" 1;node tools/qa-browser-lanes.mjs eval audit "$perf" >"$OUT/performance-$metric-$m.json";done;done
OUT="$OUT" python - <<'PY'
from pathlib import Path
from PIL import Image,ImageChops,ImageStat
import json,math,os
r=Path(os.environ['OUT']);variants=range(4);metrics=['393x852','402x874'];motions=['normal','reduced'];scenes=['initial','holding','released','after-1','after-2','good-foam','underfill','recoverable','wiped','overflow','timeout'];expected={'initial':None,'holding':None,'released':None,'after-1':None,'after-2':None,'good-foam':'good-foam','underfill':'underfill','recoverable':None,'wiped':None,'overflow':'overflow','timeout':'timeout'};rows=[];fail=[]
for v in variants:
 for metric in metrics:
  for scene in scenes:
   a=Image.open(r/f'cup{v}-{metric}-{scene}-normal.png').convert('RGB');b=Image.open(r/f'cup{v}-{metric}-{scene}-reduced.png').convert('RGB');d=ImageChops.difference(a,b);st=ImageStat.Stat(d);rows.append({'key':f'{v}-{metric}-{scene}','size':[a.width,a.height],'mae':round(sum(st.mean)/3,3),'normalizedRMSE':round(math.sqrt(sum(x*x for x in st.rms)/3)/255,6),'changed':round(sum(px!=(0,0,0) for px in d.getdata())/(a.width*a.height),5)})
   for m in motions:
    e=json.loads((r/f'evidence-{v}-{metric}-{scene}-{m}.json').read_text());s=e['state'];ok=s['outcome']==expected[scene] and (scene!='recoverable' or s['phase']=='recoverable') and (scene!='wiped' or s['wipes']==1 and s['level']==0) and (scene not in ['after-1','after-2'] or s['afterStage']==int(scene[-1]))
    if e['status']!='pass' or e['dpr']!=3 or e['errors'] or e['external'] or e['viewport']['bodyScrollWidth']>e['width'] or min(t['height'] for t in e['targets'])<44 or min(t['width'] for t in e['targets'])<44 or not ok:fail.append(f'evidence {v} {metric} {scene} {m}')
for v in variants:
 e=json.loads((r/f'no-cue-{v}.json').read_text())
 if e['button']['answer'] or e['button']['correct'] or e['button']['height']<44 or e['button']['width']<44 or e['state']['level']!=0:fail.append(f'cue {v}')
for v in variants:
 for m in motions:
  e=json.loads((r/f'touch-success-{v}-{m}.json').read_text())
  if not(e['status']=='pass' and e['holding']['holding'] and e['released']['phase']=='afterflow' and e['after']['outcome']=='good-foam' and len(e['finishes'])==1 and e['finishes'][0]['correct'] and min(t['height'] for t in e['targets'])>=44 and not e['overflow'] and not e['errors']):fail.append(f'touch {v} {m}')
for v,m in [(0,'normal'),(3,'reduced')]:
 e=json.loads((r/f'keyboard-{v}-{m}.json').read_text())
 if not(e['holding']['focused'] and e['after']['outcome']=='good-foam' and len(e['finishes'])==1 and e['finishes'][0]['correct']):fail.append(f'keyboard {v} {m}')
for m in motions:
 e=json.loads((r/f'overflow-retry-{m}.json').read_text())
 if not(e['spill']['phase']=='recoverable' and e['wiped']['wipes']==1 and e['wiped']['level']==0 and e['after']['outcome']=='good-foam' and len(e['finishes'])==1):fail.append(f'retry {m}')
 e=json.loads((r/f'deadline-{m}.json').read_text())
 if not(e['after']['outcome']=='timeout' and len(e['finishes'])==1 and all(e['before'][k]==e['after'][k] for k in ['level','wipes','attempts','phase'])):fail.append(f'deadline {m}')
 e=json.loads((r/f'dispose-{m}.json').read_text())
 if not(e['after']['disposed'] and e['after']['timeouts']==0 and e['after']['frames']==0 and e['after']['listeners']==0 and not e['qaPresent'] and not e['finishes']):fail.append(f'dispose {m}')
for metric in metrics:
 for m in motions:
  e=json.loads((r/f'performance-{metric}-{m}.json').read_text())
  if not(e['status']=='pass' and e['frames']==90 and e['gameOwnedFrames']==(1 if m=='normal' else 0) and not e['overflow'] and not e['errors']):fail.append(f'perf {metric} {m}')
for metric in ['390x844','430x932']:
 w,h=map(int,metric.split('x'))
 for v in variants:
  for m in motions:
   for s in ['initial','good-foam']:
    e=json.loads((r/f'boundary-{v}-{metric}-{s}-{m}.json').read_text());im=Image.open(r/f'boundary-cup{v}-{metric}-{s}-{m}.png')
    if e['status']!='pass' or e['dpr']!=3 or e['errors'] or e['external'] or e['viewport']['bodyScrollWidth']>w or min(t['height'] for t in e['targets'])<44 or im.size!=(w*3,h*3):fail.append(f'boundary {v} {metric} {s} {m}')
for v in variants:
 for metric in metrics:
  for m in motions:
   e=json.loads((r/f'focus-{v}-{metric}-{m}.json').read_text())
   if not e['focused'] or e['report']['status']!='pass':fail.append(f'focus {v} {metric} {m}')
report={'status':'pass' if not fail else 'fail','canonicalViewports':[{'width':393,'height':852,'dpr':3},{'width':402,'height':874,'dpr':3}],'variants':list(variants),'states':scenes,'comparisons':len(rows),'canonicalScreenshots':len(rows)*2,'focusScreenshots':16,'boundaryScreenshots':32,'touchRoutes':8,'keyboardRoutes':2,'retryRoutes':2,'allDpr3':not any('evidence' in x for x in fail),'allFullResolution':all(x['size'] in ([1179,2556],[1206,2622]) for x in rows),'maxMAE':max(x['mae'] for x in rows),'maxNormalizedRMSE':max(x['normalizedRMSE'] for x in rows),'failures':fail,'rows':rows};(r/'comparison-report.json').write_text(json.dumps(report,indent=2));print(json.dumps({k:v for k,v in report.items() if k!='rows'},indent=2));raise SystemExit(bool(fail))
PY
echo "$OUT"
