const COLORS=Object.freeze([
  Object.freeze({name:"むらさき",hex:"#A66DC2"}),Object.freeze({name:"みどり",hex:"#6BAE8E"}),Object.freeze({name:"きいろ",hex:"#D5A93F"}),
  Object.freeze({name:"あお",hex:"#5A88BE"}),Object.freeze({name:"ピンク",hex:"#D983A0"}),Object.freeze({name:"しろ",hex:"#D8D4DC"})
]);
const LABELS=Object.freeze({right:"右面→正面",left:"左面→正面",up:"上面→正面",down:"下面→正面"});
const SEQUENCES=Object.freeze([
  Object.freeze(["right","up"]),Object.freeze(["up","right"]),Object.freeze(["right","left"]),Object.freeze(["up","down"]),
  Object.freeze(["right","up","left"]),Object.freeze(["up","right","down"]),Object.freeze(["right","left","up"]),Object.freeze(["up","down","right"]),
  Object.freeze(["right","left","right"]),Object.freeze(["up","down","up"])
]);
const PROMPT="色の位置を覚えて、最後の正面は？",HELP="見えている3面を覚えてください。回転すると色が隠れます。",DURATION=8500,ENCODE_MS=2400;
const metadata=Object.freeze({id:"spatial-cube-v1",introducedIn:"1.0",tier:2,flavor:"satisfying",step:1,family:"spatial-cube",category:"spatial"});
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
function turnState(state,turn){const[front,right,back,left,top,bottom]=state;if(turn==="right")return[right,back,left,front,top,bottom];if(turn==="left")return[left,front,right,back,top,bottom];if(turn==="up")return[top,right,bottom,left,back,front];return[bottom,right,top,left,front,back]}
function faceStateAfter(turns,count=turns.length){let state=[0,1,2,3,4,5];for(let index=0;index<Math.min(count,turns.length);index++)state=turnState(state,turns[index]);return state}
function faceAfter(turns){return faceStateAfter(turns)[0]}
function generate({shuffle,pick}={}){
  if(typeof shuffle!=="function"||typeof pick!=="function")throw new TypeError(`${metadata.id}: shuffle and pick are required`);
  const colors=shuffle(COLORS),turns=pick(SEQUENCES);if(!SEQUENCES.includes(turns))throw new TypeError(`${metadata.id}: pick must return a supplied sequence`);const answer=colors[faceAfter(turns)].name,distractors=shuffle(colors.filter(color=>color.name!==answer)).slice(0,3).map(color=>color.name),options=shuffle([answer,...distractors]);
  return{kind:"cube",prompt:PROMPT,help:HELP,colors,turns,answer,options,duration:DURATION};
}
function validate(task){
  const issues=[];if(!task||typeof task!=="object")return["task must be an object"];
  if(task.kind!=="cube")issues.push("kind must remain cube");if(task.prompt!==PROMPT)issues.push("prompt changed");if(task.help!==HELP)issues.push("help changed");if(task.duration!==DURATION)issues.push(`duration must remain ${DURATION}ms`);
  const colors=Array.isArray(task.colors)?task.colors:[];if(colors.length!==COLORS.length||new Set(colors.map(item=>item?.name)).size!==COLORS.length||colors.some(item=>!COLORS.some(color=>same(item,color))))issues.push("colors must be the exact six published objects in shuffled order");
  const turns=Array.isArray(task.turns)?task.turns:[];if(!SEQUENCES.some(sequence=>same(sequence,turns)))issues.push("turns must be one published sequence");
  const expected=colors.length===6&&turns.length?colors[faceAfter(turns)]?.name:null;if(task.answer!==expected)issues.push("answer does not match the final front face");
  const options=Array.isArray(task.options)?task.options:[];if(options.length!==4||new Set(options).size!==4||!options.includes(task.answer)||options.some(value=>!colors.some(color=>color.name===value)))issues.push("options must contain the answer and three unique published distractors");
  return issues;
}
const STYLE=`
.cb-stage{box-sizing:border-box;width:100%;max-width:430px;margin-inline:auto;display:grid;gap:.48rem;color:#392f40;outline:none;contain:layout paint}.cb-stage:focus-visible{outline:4px solid #68447b;outline-offset:3px;border-radius:1rem}.cb-scene{position:relative;overflow:hidden;border:1px solid #d6cadc;border-radius:1rem;background:radial-gradient(circle at 50% 36%,#fff 0,#f3ebf7 58%,#e5d8eb 100%);box-shadow:0 11px 26px rgba(63,42,73,.16)}.cb-canvas{box-sizing:border-box;display:block;width:100%;height:100%}.cb-turns{display:flex;min-height:2rem;flex-wrap:wrap;justify-content:center;gap:.3rem}.cb-turns[hidden]{display:none}.cb-turn{padding:.28rem .46rem;border:1.5px solid #d6c5df;border-radius:999px;background:#f8f2fa;color:#725d7c;font:900 .66rem/1.2 system-ui;white-space:nowrap}.cb-turn.active{border-color:#75478d;background:#75478d;color:#fff;box-shadow:0 3px 9px rgba(87,50,103,.2)}.cb-turn.done{border-color:#b7c7a8;background:#e3eedb;color:#4c6c40}.cb-status{min-height:2.65rem;margin:0;padding:.48rem .65rem;border:1px solid #ddd2e2;border-radius:.72rem;background:#fff;color:#67586d;text-align:center;font:850 .74rem/1.4 system-ui}.cb-choices{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.42rem}.cb-choice{box-sizing:border-box;min-height:3rem;border:1.5px solid #d9c9e0;border-radius:.78rem;background:#fff;color:#5b3b69;font:900 .78rem/1.2 system-ui;touch-action:manipulation}.cb-choice:disabled{background:#eee9f0;color:#918696;opacity:.75}.cb-choice:focus-visible{outline:4px solid #68447b;outline-offset:2px}.cb-choice.selected{border-color:#8b579f;box-shadow:inset 0 0 0 2px #8b579f}.cb-stage[data-result=SUCCESS] .cb-status{border-color:#88c298;background:#e3f4e7;color:#27633a}.cb-stage[data-result=WRONG] .cb-status,.cb-stage[data-result=TIMEOUT] .cb-status{border-color:#d9918b;background:#fde9e6;color:#84372f}.cb-stage[data-reduced=true] *{animation:none!important;transition:none!important}@media(prefers-reduced-motion:reduce){.cb-stage *{animation:none!important;transition:none!important}}
`;
function render(task,context){
  const issues=validate(task);if(issues.length)throw new Error(`${metadata.id}: ${issues.join("; ")}`);const documentRef=context.host?.ownerDocument;if(!documentRef?.createElement)throw new TypeError(`${metadata.id}: context.host.ownerDocument is required`);const view=documentRef.defaultView||globalThis,reduced=Boolean(context.reducedMotion),turnDelay=reduced?320:700,firstDelay=reduced?120:260;
  const style=documentRef.createElement("style"),stage=documentRef.createElement("section"),scene=documentRef.createElement("div"),canvas=documentRef.createElement("canvas"),turnsWrap=documentRef.createElement("div"),status=documentRef.createElement("p"),choices=documentRef.createElement("div");style.textContent=STYLE;stage.className="cb-stage";stage.dataset.reduced=String(reduced);scene.className="cb-scene";canvas.className="cb-canvas";canvas.setAttribute("role","img");canvas.setAttribute("aria-label","正面、右面、上面の三面が見える色付き立方体");scene.append(canvas);turnsWrap.className="cb-turns";turnsWrap.hidden=true;turnsWrap.setAttribute("aria-label",`回転順: ${task.turns.map(turn=>LABELS[turn]).join("、")}`);status.className="cb-status";status.setAttribute("role","status");status.setAttribute("aria-live","polite");status.textContent="見えている正面・右面・上面の色を覚えてください";choices.className="cb-choices";stage.append(scene,turnsWrap,status,choices);context.host.replaceChildren(style,stage);
  const drawing=canvas.getContext("2d");if(!drawing)throw new Error(`${metadata.id}: 2D canvas is unavailable`);const badges=[],buttons=[];task.turns.forEach((turn,index)=>{const badge=documentRef.createElement("span");badge.className="cb-turn";badge.textContent=`${index+1}. ${LABELS[turn]}`;turnsWrap.append(badge);badges.push(badge)});
  const state={phase:"ENCODE",masked:false,step:0,faces:[0,1,2,3,4,5],choicesEnabled:false,done:false,disposed:false,result:null,selected:null,detail:"",finishCalls:0,stages:0};let W=393,H=225,dpr=1,staticScene=false;
  const resize=()=>{const measured=scene.getBoundingClientRect?.().width||stage.getBoundingClientRect?.().width||stage.clientWidth||context.viewport?.width||393;W=Math.max(280,Math.min(430,Math.round(measured)));H=Math.round(W*.57);dpr=Math.max(1,Math.min(3,Number(context.viewport?.dpr||view.devicePixelRatio||1)));canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);canvas.style.width=`${W}px`;canvas.style.height=`${H}px`;scene.style.height=`${H}px`;paint()};
  const polygon=(points,fill)=>{drawing.beginPath();drawing.moveTo(points[0][0],points[0][1]);for(const[x,y]of points.slice(1))drawing.lineTo(x,y);drawing.closePath();drawing.fillStyle=fill;drawing.fill();drawing.strokeStyle="rgba(57,43,65,.48)";drawing.lineWidth=Math.max(2,W*.007);drawing.stroke()};
  const labelFace=(points,text)=>{const x=points.reduce((sum,p)=>sum+p[0],0)/points.length,y=points.reduce((sum,p)=>sum+p[1],0)/points.length;drawing.fillStyle="#fff";drawing.font=`950 ${Math.round(W*.035)}px system-ui`;drawing.textAlign="center";drawing.textBaseline="middle";drawing.shadowColor="rgba(36,24,42,.55)";drawing.shadowBlur=3;drawing.fillText(text,x,y);drawing.shadowBlur=0;drawing.textAlign="left";drawing.textBaseline="alphabetic"};
  function paint(){drawing.setTransform(dpr,0,0,dpr,0,0);drawing.clearRect(0,0,W,H);const glow=drawing.createRadialGradient(W*.5,H*.5,0,W*.5,H*.5,W*.43);glow.addColorStop(0,"rgba(255,255,255,.88)");glow.addColorStop(1,"rgba(166,109,194,.04)");drawing.fillStyle=glow;drawing.fillRect(0,0,W,H);drawing.fillStyle="rgba(73,55,82,.16)";drawing.beginPath();drawing.ellipse(W*.5,H*.84,W*.25,H*.065,0,0,Math.PI*2);drawing.fill();const cx=W*.47,cy=H*.48,s=W*.19,front=[[cx-s*.62,cy-s*.38],[cx+s*.2,cy-s*.38],[cx+s*.2,cy+s*.5],[cx-s*.62,cy+s*.5]],right=[[cx+s*.2,cy-s*.38],[cx+s*.66,cy-s*.66],[cx+s*.66,cy+s*.2],[cx+s*.2,cy+s*.5]],top=[[cx-s*.62,cy-s*.38],[cx-s*.15,cy-s*.66],[cx+s*.66,cy-s*.66],[cx+s*.2,cy-s*.38]],faces=[front,right,top],indexes=[state.faces[0],state.faces[1],state.faces[4]];faces.forEach((points,index)=>{const color=task.colors[indexes[index]],fill=state.masked?["#51475a","#453d4e","#61566a"][index]:color.hex;polygon(points,fill);labelFace(points,state.masked?"?":color.name)});drawing.fillStyle="rgba(255,255,255,.5)";drawing.font=`800 ${Math.round(W*.024)}px system-ui`;drawing.textAlign="center";drawing.fillText(state.masked?`HIDDEN TURN ${state.step} / ${task.turns.length}`:"3 FACES / 2.4 sec",W*.5,H*.94);drawing.textAlign="left"}
  const paintBadges=active=>{badges.forEach((badge,index)=>{badge.classList.toggle("active",index===active);badge.classList.toggle("done",active===null||index<active)})};
  const enableChoices=()=>{if(state.done||state.disposed||staticScene)return;state.phase="CHOICES";state.choicesEnabled=true;paintBadges(null);buttons.forEach(button=>button.disabled=false);status.textContent="最後に正面へ来た色を、記憶で選んで。";buttons[0]?.focus({preventScroll:true});context.setDeadline(task.duration,()=>finish(false,null,"timeout"));paint()};
  const advance=()=>{if(state.done||state.disposed||staticScene)return;if(state.step>=task.turns.length){enableChoices();return}paintBadges(state.step);state.faces=turnState(state.faces,task.turns[state.step]);state.step++;state.stages++;state.phase=`TURN${state.step}`;status.textContent=`${state.step}手目: ${LABELS[task.turns[state.step-1]]}`;paint();context.later(advance,turnDelay)};
  const mask=()=>{if(state.done||state.disposed||staticScene)return;state.masked=true;state.phase="HIDDEN";turnsWrap.hidden=false;status.textContent=`色は隠れました。${task.turns.map(turn=>LABELS[turn]).join(" → ")} の順です。`;paint();context.later(advance,firstDelay)};
  const finish=(correct,selected,result=correct?"success":"wrong")=>{state.finishCalls++;if(state.done||state.disposed)return false;state.done=true;state.choicesEnabled=false;state.result=result;state.selected=selected;state.phase=result.toUpperCase();stage.dataset.result=state.phase;buttons.forEach(button=>button.disabled=true);if(result==="timeout"){state.detail="時間切れです。脳は定時退社しました。";status.textContent=state.detail}else{state.detail=correct?`正解。最後の正面は${task.answer}`:`残念。最後の正面は${task.answer}`;status.textContent=state.detail}paint();const payload=result==="timeout"?{detail:"時間切れです。脳は定時退社しました。",answerLabel:task.answer}:{answerLabel:task.answer};return context.finish(correct,payload)};
  task.options.forEach(value=>{const button=documentRef.createElement("button");button.type="button";button.className="cb-choice";button.textContent=value;button.disabled=true;const choose=()=>{if(!state.choicesEnabled||state.done)return;button.classList.add("selected");finish(value===task.answer,value)};context.listen(button,"click",choose);context.listen(button,"keydown",event=>{if(event.key!=="Enter"&&event.key!==" ")return;event.preventDefault();choose()});choices.append(button);buttons.push(button)});
  const showScene=sceneName=>{if(state.disposed)return false;staticScene=true;Object.assign(state,{phase:"ENCODE",masked:false,step:0,faces:[0,1,2,3,4,5],choicesEnabled:false,done:false,result:null,selected:null,detail:""});delete stage.dataset.result;turnsWrap.hidden=true;buttons.forEach(button=>{button.disabled=true;button.classList.remove("selected")});paintBadges(-1);const apply=count=>{state.masked=true;turnsWrap.hidden=false;state.faces=faceStateAfter(task.turns,count);state.step=count;state.stages=count};if(sceneName==="initial"){}else if(sceneName==="turn1"){apply(1);state.phase="TURN1";paintBadges(0)}else if(sceneName==="turn2"){apply(Math.min(2,task.turns.length));state.phase="TURN2";paintBadges(1)}else if(sceneName==="final-hidden"){apply(task.turns.length);state.phase="HIDDEN";paintBadges(task.turns.length-1)}else if(sceneName==="choices"){apply(task.turns.length);state.phase="CHOICES";state.choicesEnabled=true;paintBadges(null);buttons.forEach(button=>button.disabled=false)}else if(sceneName==="wrong"||sceneName==="success"){apply(task.turns.length);state.phase=sceneName.toUpperCase();state.choicesEnabled=false;state.done=true;state.result=sceneName;state.selected=sceneName==="success"?task.answer:task.options.find(value=>value!==task.answer);stage.dataset.result=state.phase;paintBadges(null);buttons.forEach(button=>{button.disabled=true;button.classList.toggle("selected",button.textContent===state.selected)});state.detail=sceneName==="success"?`正解。最後の正面は${task.answer}`:`残念。最後の正面は${task.answer}`}else if(sceneName==="timeout"){apply(task.turns.length);state.phase="TIMEOUT";state.done=true;state.result="timeout";state.detail="時間切れです。脳は定時退社しました。";stage.dataset.result="TIMEOUT";paintBadges(null)}else return false;status.textContent=state.detail||(sceneName==="initial"?"見えている正面・右面・上面の色を覚えてください":sceneName==="choices"?"最後に正面へ来た色を、記憶で選んで。":`色は隠れています。${state.step}手目まで回転`);paint();return true};
  const inspect=()=>({phase:state.phase,masked:state.masked,step:state.step,faces:[...state.faces],frontIndex:state.faces[0],frontName:task.colors[state.faces[0]].name,choicesEnabled:state.choicesEnabled,done:state.done,disposed:state.disposed,result:state.result,selected:state.selected,detail:state.detail,finishCalls:state.finishCalls,stages:state.stages,timing:{encodeMs:ENCODE_MS,firstDelay,turnDelay,duration:task.duration},canvas:{cssWidth:W,cssHeight:H,pixelWidth:canvas.width,pixelHeight:canvas.height,dpr},status:status.textContent,buttons:buttons.map(button=>({text:button.textContent,disabled:button.disabled,selected:button.classList.contains("selected")})),reduced});
  const qaApi={advance,mask,enableChoices,choose:value=>{const button=buttons.find(item=>item.textContent===value);button?.click();return Boolean(button)},timeout:()=>finish(false,null,"timeout"),showScene,inspect};resize();paint();context.later(mask,ENCODE_MS);if(view&&typeof view.dispatchEvent==="function")context.listen(view,"resize",resize,{passive:true});if(context.qa&&typeof context.qa==="object")context.qa[metadata.id]=qaApi;context.listen(context.signal,"abort",()=>{state.disposed=true;if(context.qa?.[metadata.id]===qaApi)delete context.qa[metadata.id]},{once:true});
}
export default Object.freeze({metadata,generate,validate,render});
